### PR TITLE
Rename Auth0 custom table to match documentation

### PR DESCRIPTION
**Pull request by rene-ammerlaan**
Required items, please complete
   
   Change(s):
   - Updated log type for Auth0Connector/main.py

   Reason for Change(s):
   - The Function App creates an invalid table named `Auth0_CL`, which doesn't match with the settings and documentation.

   Testing Completed:
   - ..

   Checked that the validations are passing and have addressed any issues that are present:
   -..

### CODE REVIEW

**Comment by v-vdixit** [comment]
@rene-ammerlaan We are looking into this, will update you shortly, Thanks!

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Sorry for the delay. We will review and provide you the update by 17th Feb EOD.
Thanks

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Can you please share the impact on existing customers and also requesting you to update the same file in the zip as well.
Thanks

**Comment by rene-ammerlaan** [comment]
@v-mchatla existing customers would need to change their use-cases to the new table name `Auth0AM_CL`. The alternative is to change all settings and references from `Auth0AM_CL` to `Auth0_CL`.

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Can you please updated the zip as well. 
Thanks

**Comment by rene-ammerlaan** [comment]
@microsoft-github-policy-service agree company="Nederlandse Loterij BV"

**Comment by rene-ammerlaan** [comment]
@v-mchatla I've updated the ZIP file

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan 
Do we have any update on the zip update?
Thanks

**Comment by rene-ammerlaan** [comment]
@v-mchatla as mentioned the update zip file is in the PR.

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Thanks for accommodating the requested changes, will check and get back to you.
Thanks

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Changes look good. Can you please add union in the parse for both of these tables Auth0_CL and Auth0AM_CL instead of running on Auth0AM_CL, so that it will return accurate results for existing customers as they are going to have the data in 2 different tables at least for next couple of months - currently they are getting the logs in Auth0_CL table and new logs will get injected into Auth0AM_CL.
Let me know if you need any other details.
Thanks

**Comment by rene-ammerlaan** [comment]
@v-mchatla I've added the union to the parser file, but with this change we add a temporary union that should be removed later. The query was previously broken due to the mismatch in table name, so we could also ignore that legacy table name entirely. This avoids the need to cleanup this union.

**Comment by v-mchatla** [comment]
Hi @rene-ammerlaan,
Agree, just to ensure that there won't be any impact to the existing customer.
Thanks

**Review by v-mchatla — APPROVED** [review]
Changes look good

**Pull request merged**
