### PR TITLE
SecurityScorecard Cybersecurity Ratings Solution initial submission

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Required items, please complete
   
   Change(s):
   - Added SecurityScorecard Cybersecurity Ratings Solution for certification.

   Reason for Change(s):
   - New product

   Version Updated:
   - Initial version

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
We are reviewing your changes. Meanwhile can you please share the sample data to test workbook.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, We are reviewing your changes. Meanwhile can you please share the sample data to test workbook. Thanks

@v-mchatla 
We have added sample data to the respected folder.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Below are the review points, need your help in fixing few of them.
1. We are good with the logo, create UI and Data connector files.
2. Main Template is failing with following validation error. Can you please check if you can fix it.
image
3. Workbook Testing is still pending - Need your help in removing the _s/_g from the column names so that it will get ingested properly in our workspace.
4. Need your confirmation on the Solution ID. Generally, we will follow the solution ID format as publisher ID. Offer ID. seems in your case offer ID has 3 different names separated by ','. Is it acceptable?
Let me know if you need any help over here.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, Below are the review points, need your help in fixing few of them.
> 
> 1. We are good with the logo, create UI and Data connector files.
> 2. Main Template is failing with following validation error. Can you please check if you can fix it.
>    image
> 3. Workbook Testing is still pending - Need your help in removing the _s/_g from the column names so that it will get ingested properly in our workspace.
> 4. Need your confirmation on the Solution ID. Generally, we will follow the solution ID format as publisher ID. Offer ID. seems in your case offer ID has 3 different names separated by ','. Is it acceptable?
>    Let me know if you need any help over here.
>    Thanks

@v-mchatla
We have fixed the problem no 3 and 4.

Regarding point 2 firstly the error that you mentioned is not generated in our environment and still we tried to find out solution but we are unable to find it.
So if possible can you help us out?

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Thanks for the details. There was some issue in dumping the latest data to the log Analytics. Somehow, I managed to test with old sample data shared and it's working fine.
I'm still working on the main template validation issue; will keep you posted once done.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, Thanks for the details. There was some issue in dumping the latest data to the log Analytics. Somehow, I managed to test with old sample data shared and it's working fine. I'm still working on the main template validation issue; will keep you posted once done. Thanks

@v-mchatla Understood. Thanks for the Update. Let me know if other changes required.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
I will be checking with my internal team as I didn't get any clue on where its failing. I will update you once the investigation is completed.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, I will be checking with my internal team as I didn't get any clue on where its failing. I will update you once the Analysis is completed. Thanks

@v-mchatla Thanks for the update. Request to please take on priority and try to merge it as fast as you can.
Thanks!

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Sure, I will keep you posted on the same.
Thanks

**Comment by v-spadarthi** [comment]
@v-mchatla : Could you please check and provide an update. Thanks!

**Comment by jayeshprajapaticrest** [comment]
@v-mchatla @v-spadarthi 
Is there any update?

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Sorry for the delay. Because of some other priority items, I didn't get a chance to continue on this PR. Today I will definitely spare sometime to identify the issue and provide you the update.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, Sorry for the delay. Because of some other priority items, I didn't get a chance to continue on this PR. Today I will definitely spare sometime to identify the issue and provide you the update. Thanks

OK Understood.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
I have added workbook metadata and raised a PR for the same. Can you please take latest from master once the [PR](https://github.com/Azure/Azure-Sentinel/pull/6540) is merged and recreate the package, so that all the fields in the main template should be properly filled with data. I hope this will fix the maintemplate validation issue. Let me know if you need any help over there
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, I have added workbook metadata and raised a PR for the same. Can you please take latest from master once the [PR](https://github.com/Azure/Azure-Sentinel/pull/6540) is merged and recreate the package, so that all the fields in the main template should be properly filled with data. I hope this will fix the maintemplate validation issue. Let me know if you need any help over there Thanks

@v-mchatla 
Sure, Waiting for merging of this workbook changes [PR](https://github.com/Azure/Azure-Sentinel/pull/6540). Once the has been merged then will take update and then recreate package and commit it in the same current PR and will update you.
Thanks

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Thanks for completing the requested changes. I will test main template If there were no errors I will proceed merging this PR.
Thanks

**Comment by jayeshprajapaticrest** [comment]
@v-mchatla 
[PR ](https://github.com/Azure/Azure-Sentinel/pull/6540)for workbook metadata is merged. So I will take update and create solution with the updates changes.
Will inform you here once I done with that.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest, 
Sure, let me know once you are done with the changes.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, Sure, let me know once you are done with the changes. Thanks

@v-mchatla 
Changes are done and committed to this PR.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
With the workbook metadata update the below description populated correctly. But the maintemplate validation error is still there.
image
To fix that you need to remove the workbook description from the data file and recreate the package using the updated input file. I have tested the same from my end, this fix worked.
Kindly remove the workbook description and recreate the package.
image

Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, With the workbook metadata update the below description populated correctly. But the maintemplate validation error is still there. image To fix that you need to remove the workbook description from the data file and recreate the package using the updated input file. I have tested the same from my end, this fix worked. Kindly remove the workbook description and recreate the package. image
> 
> Thanks

@v-mchatla 
I have removed workbook description, recreated the solution and committed.
Thanks.

**Comment by v-mchatla** [comment]
Hi @jayeshprajapaticrest,
Thanks for making the changes. I will review and provide update.
Thanks

**Review by v-mchatla — APPROVED** [review]
Changes looks good. Approving this PR

**Review by v-dvedak — APPROVED** [review]

**Comment by jayeshprajapaticrest** [comment]
@v-mchatla Thanks for your support.

**Pull request merged**
