### PR TITLE
Update CiscoWSAEvent.yaml to work with AsyncOS 15

### PR DESCRIPTION
**Pull request by bfelder**
AsyncOS 15 sends an additional LogLevel field in the syslog message which needs to be correctly handled in the parser.

   Required items, please complete
   
   Change(s):
   - Updated parser in CiscoWSAEvent.yaml 

   Reason for Change(s):
   - Reflect formal change in AsyncOS 15

   Version Updated:
   - No.

   Testing Completed:
   - Yes. Running in productive environment.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes. Code running in productive environment.

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @bfelder, Please package the solution using V3 tool 
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-prasadboke** [comment]
Hello @bfelder, Please accept license agreement

**Comment by v-prasadboke** [comment]
Hello @bfelder, Please accept the license agreement so that we can move further with the process

**Comment by bfelder** [comment]
@microsoft-github-policy-service agree

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
