### PR TITLE
NetFlow

### PR DESCRIPTION
**Pull request by dicolanl**
## Proposed Changes
NetFlow Collector using FileBeat and Logstash on VMSS
Workbook
Parser

### CODE REVIEW

**Comment by v-sabiraj** [comment]
This branch has conflicts that must be resolved, Thanks.

**Comment by v-jayakal** [comment]
@dicolanl - Can you please convert this into solution as discussed with Sapan and resolve conflicts? Thanks.

**Comment by dicolanl** [comment]
@v-jayakal will try to do it this week.

**Comment by dicolanl** [comment]
@v-jayakal Moved to solutions and cleaned up validations and conflicts!

**Comment by NikTripathi** [comment]
@dicolanl Please remove WorkbookMetadata file. As it is a solution we don't need it.

**Comment by dicolanl** [comment]
> @dicolanl Please remove WorkbookMetadata file. As it is a solution we don't need it.

@NikTripathi  Done!

**Comment by v-sabiraj** [comment]
Hey @dicolanl , This branch has conflicts that must be resolved, thanks.

**Comment by dicolanl** [comment]
@v-sabiraj  resolved.

**Comment by v-sabiraj** [comment]
Hey @dicolanl, please add the sample data of netflow_CL in [sample data folder](https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom),you can refer the other sample data from folder for your reference, thanks.

**Comment by dicolanl** [comment]
@v-sabiraj The lab i used 6 months to build this has since be taken down.  I am also in the process of moving households.  I wont be able to do this until at least august 2022.  

Could we move ahead with an exception? else leave it open until august?

**Review by NikTripathi — APPROVED** [review]

**Comment by v-sabiraj** [comment]
Hey @dicolanl, can you please close PR this for now, you can open once you are back. Thanks.

**Comment by v-sabiraj** [comment]
Hey @dicolanl, can you please close this PR for now, you can open once you are back. Thanks.

**Pull request closed without merging**
