### PR TITLE
V1.0.6

### PR DESCRIPTION
**Pull request by liranylevy**
Publish v 1.0.6

### CODE REVIEW

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytic rules. Thank you.

**Comment by liranylevy** [comment]
@aprakash13 can we please speed this up ?

**Comment by NikTripathi** [comment]
@liranylevy  There are conflicts can you please resolve it.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Overall, the changes look good. Might be a good idea to increment the version number of those analytic rule where there are changes to the query. As @NikTripathi suggested, please resolve the conflicts as well and we can go ahead and approve these. Thanks.

**Comment by liranylevy** [comment]
resolve conflicts

**Comment by liranylevy** [comment]
@NikTripathi @aprakash13 resolved conflicts

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
