### PR TITLE
Solutions workbook

### PR DESCRIPTION
**Pull request by garybushey**
Required items, please complete
   
   Change(s):
   Added the Tool/SolutionData folder and added the PowerShell to create the CSV files, a sample CSV file, a sample PowerBI file, and the workbook

   Reason for Change(s):
   First push

   Version Updated:
N/A

   Testing Completed:
   Testing completed in MS Sentinel instance

   Checked that the validations are passing and have addressed any issues that are present:
  N/A

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @garybushey, could you please update your branch with master? Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, please update your branch with master? Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, could you please update your branch with master? Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, please update your branch with master? Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey,
few check are stuck so please update your branch from master. Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, 
As we are unable to figure out why checks are stuck, we would like you to take the latest master and push it. Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, please update your branch with master? Thanks

**Comment by v-atulyadav** [comment]
Hi @garybushey, please update on above. Thanks

**Comment by v-rusraut** [comment]
Hi @garybushey,
Please work on above comment.

**Comment by v-atulyadav** [comment]
Hi @garybushey,
As we are unable to figure out why checks are stuck, we would like you to take the latest master and push it. Thanks

**Comment by v-atulyadav** [comment]
We wanted to check on the status of PR #9188. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by v-atulyadav** [comment]
Since we have not received a response in the last 7 days, we are closing your PR #9188 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
