### PR TITLE
Remove inconsistent BOMs from detections

### PR DESCRIPTION
**Pull request by pemontto**
Fixes #

Some detection analytics have [byte order marks (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark). This can make working with them unpredictable.

<details>
<summary>Files with BOM</summary>

```bash
❯ find . -type f |
while read file
do
    if [ "`head -c 3 -- "$file"`" == $'\xef\xbb\xbf' ]
    then
        echo "❌ BOM in: $file"
    else
        echo "✅ NO BOM $file"
    fi
done
✅ NO BOM ./AzureActivity/RareOperations.yaml
❌ BOM in: ./AzureActivity/Creating_Anomalous_Number_Of_Resources_detection.yaml
❌ BOM in: ./AzureActivity/NewResourceGroupsDeployedTo.yaml
❌ BOM in: ./AzureActivity/Granting_Permissions_To_Account_detection.yaml
✅ NO BOM ./AzureActivity/Creation_of_Expensive_Computes_in _Azure.yaml
❌ BOM in: ./SigninLogs/SigninBruteForce-AzurePortal.yaml
❌ BOM in: ./SigninLogs/FailedLogonToAzurePortal.yaml
❌ BOM in: ./SigninLogs/BypassCondAccessRule.yaml
✅ NO BOM ./SigninLogs/SigninPasswordSpray.yaml
❌ BOM in: ./SigninLogs/DistribPassCrackAttempt.yaml
✅ NO BOM ./SigninLogs/Brute Force Attack against GitHub Account.yaml
❌ BOM in: ./SigninLogs/SigninAttemptsByIPviaDisabledAccounts.yaml
❌ BOM in: ./SigninLogs/AnomalousUserAppSigninLocationIncrease-detection.yaml
❌ BOM in: ./SigninLogs/SuccessThenFail_DiffIP_SameUserandApp.yaml
✅ NO BOM ./SigninLogs/Sign-in Burst from Multiple Locations.yaml
✅ NO BOM ./SigninLogs/ExplicitMFADeny.yaml
❌ BOM in: ./SigninLogs/DisabledAccountSigninsAcrossManyApplications.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_AWSCloudTrail.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_SecurityAlert.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_SecurityEvent.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/URLEntity_AuditLogs.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_W3CIISLog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_OfficeActivity.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/URLEntity_SecurityAlerts.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_SigninLogs.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/DomainEntity_DnsEvents.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_VMConnection.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_AzureActivity.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_AzureActivity.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/FileHashEntity_CommonSecurityLog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/DomainEntity_CommonSecurityLog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/FileHashEntity_Covid19_CommonSecurityLog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/URLEntity_Syslog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_DnsEvents.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/FileHashEntity_SecurityEvent.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/DomainEntity_PaloAlto.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_AzureNetworkAnalytics.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/DomainEntity_Syslog.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/DomainEntity_SecurityAlert.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_WireData.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPEntity_OfficeActivity.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/URLEntity_PaloAlto.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/IPentity_SigninLogs.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/EmailEntity_PaloAlto.yaml
✅ NO BOM ./ThreatIntelligenceIndicator/URLEntity_OfficeActivity.yaml
❌ BOM in: ./AWSCloudTrail/AWS_ClearStopChangeTrailLogs.yaml
❌ BOM in: ./AWSCloudTrail/AWS_ChangeToRDSDatabase.yaml
✅ NO BOM ./AWSCloudTrail/AWS_FullAdminPolicyAttachedToRolesUsersGroups.yaml
❌ BOM in: ./AWSCloudTrail/AWS_ChangeToVPC.yaml
❌ BOM in: ./AWSCloudTrail/AWS_IngressEgressSecurityGroupChange.yaml
❌ BOM in: ./AWSCloudTrail/AWS_ConsoleLogonWithoutMFA.yaml
❌ BOM in: ./AWSCloudTrail/AWS_LoadBalancerSecGroupChange.yaml
❌ BOM in: ./AWSCloudTrail/AWS_CredentialHijack.yaml
❌ BOM in: ./W3CIISLog/HighFailedLogonCountByUser.yaml
❌ BOM in: ./W3CIISLog/HighPortCountByClientIP.yaml
❌ BOM in: ./W3CIISLog/HighFailedLogonCountByClientIP.yaml
❌ BOM in: ./W3CIISLog/AnomomlousUserAgentConnection.yaml
✅ NO BOM ./W3CIISLog/MaliciousAlertLinkedWebRequests.yaml
❌ BOM in: ./Syslog/ssh_NewlyInternetExposed.yaml
❌ BOM in: ./Syslog/ssh_potentialBruteForce.yaml
❌ BOM in: ./Syslog/squid_cryptomining_pools.yaml
❌ BOM in: ./Syslog/FailedLogonAttempts_UnknownUser.yaml
❌ BOM in: ./Syslog/squid_tor_proxies.yaml
✅ NO BOM ./SymantecVIP/ExcessiveFailedAuthenticationsfromInvalidInputs.yaml
✅ NO BOM ./SymantecVIP/ClientDeniedAccess.yaml
✅ NO BOM ./AzureDevOpsAuditing/AzDOHistoricPrPolicyBypassing.yaml
✅ NO BOM ./AzureDevOpsAuditing/AzDOServiceConnectionUsage.yaml
✅ NO BOM ./AzureDevOpsAuditing/AzDOPatSessionMisuse.yaml
✅ NO BOM ./AzureDevOpsAuditing/AzDOHistoricServiceConnectionAdds.yaml
✅ NO BOM ./AzureDevOpsAuditing/AzDOAdminGroupAdditions.yaml
✅ NO BOM ./AzureFirewall/SeveralDenyActionsRegistered.yaml
✅ NO BOM ./SophosXGFirewall/PortScanDetected.yaml
✅ NO BOM ./SophosXGFirewall/ExcessiveAmountofDeniedConnectionsfromASingleSource.yaml
✅ NO BOM ./ProofpointTAP/MalwareAttachmentDelivered.yaml
✅ NO BOM ./ProofpointTAP/MalwareLinkClicked.yaml
✅ NO BOM ./LAQueryLogs/UserSearchingForVIPUserActivity.yaml
❌ BOM in: ./MultipleDataSources/SigninFirewallCorrelation.yaml
✅ NO BOM ./MultipleDataSources/IridiumIOCs.yaml
✅ NO BOM ./MultipleDataSources/BariumDomainIOC112020.yaml
✅ NO BOM ./MultipleDataSources/MultiplePasswordresetsbyUser.yaml
✅ NO BOM ./MultipleDataSources/BariumIPIOC112020.yaml
✅ NO BOM ./MultipleDataSources/KnownPHOSPHORUSDomainsIP-October2020.yaml
❌ BOM in: ./MultipleDataSources/MalformedUserAgents.yaml
✅ NO BOM ./MultipleDataSources/HostAADCorrelation.yaml
❌ BOM in: ./MultipleDataSources/NetworkEndpointCorrelation.yaml
✅ NO BOM ./MultipleDataSources/CERIUMOct292020IOCs.yaml
✅ NO BOM ./MultipleDataSources/AAD_PAVPN_Correlation.yaml
✅ NO BOM ./MultipleDataSources/AWSConsoleAADCorrelation.yaml
❌ BOM in: ./MultipleDataSources/NewUserAgentLast24h.yaml
✅ NO BOM ./MultipleDataSources/AnomalousIPUsageFollowedByTeamsAction.yaml
✅ NO BOM ./MultipleDataSources/AADHostLoginCorrelation.yaml
✅ NO BOM ./MultipleDataSources/ZincOct292020IOCs.yaml
✅ NO BOM ./MultipleDataSources/GalliumIOCs.yaml
✅ NO BOM ./MultipleDataSources/ThalliumIOCs.yaml
✅ NO BOM ./MultipleDataSources/Manganese_VPN-IOCs.yaml
✅ NO BOM ./MultipleDataSources/MFADisable.yaml
❌ BOM in: ./MultipleDataSources/PHOSPHORUSMarch2019IOCs.yaml
✅ NO BOM ./MultipleDataSources/STRONTIUMJuly2019IOCs.yaml
✅ NO BOM ./MultipleDataSources/AADAWSConsoleCorrelation.yaml
✅ NO BOM ./MultipleDataSources/STRONTIUMOct292020IOCs.yaml
❌ BOM in: ./MultipleDataSources/TimeSeriesAnomaly-MultiVendor_DataExfiltration.yaml
❌ BOM in: ./SecurityEvent/powershell_empire.yaml
❌ BOM in: ./SecurityEvent/password_never_expires.yaml
❌ BOM in: ./SecurityEvent/malware_in_recyclebin.yaml
❌ BOM in: ./SecurityEvent/GroupCreatedAddedToPrivlegeGroup_1h.yaml
❌ BOM in: ./SecurityEvent/PotentialKerberoast.yaml
❌ BOM in: ./SecurityEvent/UserCreatedAddedToBuiltinAdmins_1d.yaml
❌ BOM in: ./SecurityEvent/UserAccountCreatedDeleted_10m.yaml
❌ BOM in: ./SecurityEvent/UserAccountAddedToPrivlegeGroup_1h.yaml
❌ BOM in: ./SecurityEvent/base64_encoded_pefile.yaml
❌ BOM in: ./SecurityEvent/password_not_set.yaml
❌ BOM in: ./SecurityEvent/gte_6_FailedLogons_10m.yaml
✅ NO BOM ./SecurityEvent/RDP_MultipleConnectionsFromSingleSystem.yaml
❌ BOM in: ./SecurityEvent/TimeSeriesAnomaly-ProcessExecutions.yaml
✅ NO BOM ./SecurityEvent/RDP_Nesting.yaml
❌ BOM in: ./SecurityEvent/execute_base64_decodedpayload.yaml
✅ NO BOM ./SecurityEvent/MultipleFailedFollowedBySuccess.yaml
❌ BOM in: ./SecurityEvent/UserAccountAdd-Removed.yaml
✅ NO BOM ./SecurityEvent/RDP_RareConnection.yaml
❌ BOM in: ./SecurityEvent/SecurityEventLogCleared.yaml
❌ BOM in: ./SecurityEvent/UserAccountEnabledDisabled_10m.yaml
❌ BOM in: ./SecurityEvent/ExcessiveLogonFailures.yaml
❌ BOM in: ./DnsEvents/DNS_HighNXDomainCount_detection.yaml
❌ BOM in: ./DnsEvents/DNS_Miners.yaml
❌ BOM in: ./DnsEvents/DNS_TorProxies.yaml
❌ BOM in: ./DnsEvents/DNS_HighReverseDNSCount_detection.yaml
✅ NO BOM ./readme.md
❌ BOM in: ./AuditLogs/RareApplicationConsent.yaml
❌ BOM in: ./AuditLogs/MaliciousOAuthApp_PwnAuth.yaml
❌ BOM in: ./AuditLogs/MaliciousOAuthApp_O365AttackToolkit.yaml
❌ BOM in: ./AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml
✅ NO BOM ./AuditLogs/UseraddedtoPrivilgedGroups.yaml
✅ NO BOM ./QualysVM/NewHighSeverityVulnDetectedAcrossMulitpleHosts.yaml
✅ NO BOM ./QualysVM/HighNumberofVulnDetected.yaml
✅ NO BOM ./SymantecProxySG/ExcessiveDeniedProxyTraffic.yaml
✅ NO BOM ./SymantecProxySG/UserAccessedSuspiciousURLCategories.yaml
✅ NO BOM ./GitHub/Threat Intel Matches to GitHub Audit Logs.yaml
✅ NO BOM ./GitHub/Two Factor Authentication Disabled.yaml
✅ NO BOM ./GitHub/GitHub Activities from Infrequent Country.yaml
✅ NO BOM ./GitHub/Security Vulnerability in Repo.yaml
✅ NO BOM ./EsetSMC/eset-threats.yaml
✅ NO BOM ./EsetSMC/eset-sites-blocked.yaml
✅ NO BOM ./InfobloxNIOS/ExcessiveNXDOMAINDNSQueries.yaml
✅ NO BOM ./InfobloxNIOS/PotentialDHCPStarvationAttack.yaml
✅ NO BOM ./VMwareCarbonBlack/KnownMalwareDetected.yaml
✅ NO BOM ./VMwareCarbonBlack/CriticalThreatDetected.yaml
❌ BOM in: ./OfficeActivity/Office_MailForwarding.yaml
❌ BOM in: ./OfficeActivity/SharePoint_Downloads_byNewUserAgent.yaml
✅ NO BOM ./OfficeActivity/Office_Uploaded_Executables.yaml
❌ BOM in: ./OfficeActivity/office_policytampering.yaml
✅ NO BOM ./OfficeActivity/StrontiumCredHarvesting.yaml
❌ BOM in: ./OfficeActivity/SharePoint_Downloads_byNewIP.yaml
❌ BOM in: ./OfficeActivity/RareOfficeOperations.yaml
✅ NO BOM ./OfficeActivity/MultipleTeamsDeletes.yaml
✅ NO BOM ./OfficeActivity/Mail_redirect_via_ExO_transport_rule.yaml
✅ NO BOM ./OfficeActivity/Malicious_Inbox_Rule.yaml
❌ BOM in: ./OfficeActivity/exchange_auditlogdisabled.yaml
✅ NO BOM ./OfficeActivity/ExternalUserAddedRemovedInTeams.yaml
✅ NO BOM ./OktaSSO/FailedLoginsFromUnknownOrInvalidUser.yaml
✅ NO BOM ./OktaSSO/LoginfromUsersfromDifferentCountrieswithin3hours.yaml
✅ NO BOM ./OktaSSO/PasswordSpray.yaml
✅ NO BOM ./SecurityAlert/CorrelateIPC_Unfamiliar-Atypical
✅ NO BOM ./SecurityAlert/CorrelateIPC_Unfamiliar-Atypical.yaml
✅ NO BOM ./PulseConnectSecure/PulseConnectSecureVPN-DistinctFailedUserLogin.yaml
✅ NO BOM ./PulseConnectSecure/PulseConnectSecureVPN-BruteForce.yaml
❌ BOM in: ./AzureDiagnostics/TimeSeriesKeyvaultAccessAnomaly.yaml
❌ BOM in: ./AzureDiagnostics/KeyvaultMassSecretRetrieval.yaml
❌ BOM in: ./AzureDiagnostics/KeyVaultSensitiveOperations.yaml
❌ BOM in: ./CommonSecurityLog/PaloAlto-NetworkBeaconing.yaml
✅ NO BOM ./CommonSecurityLog/MultiVendor-PossibleDGAContacts.yaml
❌ BOM in: ./CommonSecurityLog/CiscoASA-ThreatDetectionMessage.yaml
✅ NO BOM ./CommonSecurityLog/Zscaler-LowVolumeDomainRequests.yaml
❌ BOM in: ./CommonSecurityLog/CiscoASA-AvgAttackDetectRateIncrease.yaml
❌ BOM in: ./CommonSecurityLog/PaloAlto-PortScanning.yaml
❌ BOM in: ./CommonSecurityLog/TimeSeriesAnomaly-MultiVendor_NetworkTraffic.yaml
✅ NO BOM ./CommonSecurityLog/Wazuh-Large Number of Web errors from an IP.yaml
✅ NO BOM ./CommonSecurityLog/Fortinet-NetworkBeaconPattern.yaml
✅ NO BOM ./ZoomLogs/SupiciousLinkSharing.yaml
✅ NO BOM ./ZoomLogs/E2EEDisbaled.yaml
✅ NO BOM ./ZoomLogs/JoiningMeetingFromAnotherTimeZone.yaml
✅ NO BOM ./ZoomLogs/ExternalUserAccess.yaml
```

</details>

## Proposed Changes

Remove BOMs

### CODE REVIEW

**Comment by pemontto** [comment]
Ideally we'd also check for this in the DetectionsValidations pipeline

**Comment by pemontto** [comment]
Expected pipeline failure as BOMs were removed from the ID.

As an example of where this is an issue, if I create a new file in VSCode `PaloAlto-PortScanning-vscode.yaml` and copy paste the content from the existing rule `Detections/CommonSecurityLog/PaloAlto-PortScanning.yaml` the BOM isn't capture so the files and IDs differ.

Screen Shot 2020-11-19 at 17 15 10

**Comment by shainw** [comment]
@oshvartz - Thoughts on adding this to the Validations?

**Review by laithhisham — APPROVED** [review]

**Review by laithhisham — COMMENTED** [review]
@oshvartz - wondering if the removal of the BOMs requires any changes on our side when updating the templates

**Comment by oshvartz** [comment]
validation of BOM is a bit annoying IMO becuse some OM are using it by default (like mac OS) I would say we maybe need to avoid committing BOM - I vagally remember there is a way to strip BOM using .gitattribute (we should put in the root of the repo)
example https://github.com/sindresorhus/strip-bom/blob/master/.gitattributes 
@laithhisham can you check it

**Review by shainw — APPROVED** [review]
ready to complete and we will look at how to handle in the future.

**Pull request merged**
