### PR TITLE
Create Function CETWorkingTime.txt

### PR DESCRIPTION
**Pull request by ep3p**
Change(s):
   - Add a function that computes if a datetime value or the current time is working time (according to a work schedule).

   Reason for Change(s):
   - Thought this could be interesting to assess the severity of an event.
   - I don't know if there is something similar already in KQL.

______________________________________________
Currently this does **not work for time limits in the work schedule that are not o'clock** .

### CODE REVIEW

**Comment by ep3p** [comment]
On July Azure Data Explorer introduced the function ```datetime_utc_to_local()```, so now maybe this function is not so interesting (no need to compute daylight saving time dates)

**Comment by v-marimanda** [comment]
Hi @manishkumar1991 Can you please take a look and provide your sign off. thanks!!

**Comment by v-sabiraj** [comment]
> @manishkumar1991 Here you have an example with the demo environment. Please, take in account this function was configured for UTC+2, so in Display time try to select UTC+2
> 
> image
> 
> https://portal.azure.com#@0637680a-67ee-4b63-acdf-ac82cfcde5ad/blade/Microsoft_Azure_Monitoring_Logs/DemoLogsBlade/resourceId/%2FDemo/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA61WyW7bMBC9%252ByvmKKGOU7dNurg%252BOUkRoL3ULnoUGGlksZZIg6TsKk3%252FvUPKFq0FQRJUgCGKnOXNm4XO0cCt%252FinVhov1ihcIcwgSZjAy9PHJrky9e1wGoszzMPwzAnrOz%252BE2BSy2phqDYRuEuFQKhQEr6kRy8rBlSmMSNXbJHE%252FTgGtry7sLxyDkPqCX35od%252FSwNUwaYSADpl8lSaZApSfK8gj0FADrOMClz7%252Fa4EWmrG1kd8vxh1hcgk8fj6fuBcy4MCs13bcmLAclU8YRVLbF3nRhscBZ6Y9TBJ%252F7bpN0ej53WITcFcRw1qVijqZCpoMsvMXg5humlZ%252B%252BaOHuuX9J5rtePba9W%252FV4KdOki16lGo2GHSpcafqwWjc%252B9xaQi2opqKctbNrM2bqSCBVWUYjlcl0pukQln2HNfFkVX%252Bc0jyksn722Q3EIW29IccDLHVeV4WpPgjuUlumIzx3gclQNx3HClTe3oarkiHK7yZLpH3ARUEzItpDBZ8GRC3xKhYRjWwVjjPowrVuV8nRlYsp1NYouTJcZSJP8TyfT1CZTa%252FBOxxJJGQmw6A6A3E165mdDbvkNDmAUEbW4nk06IBLFXCON%252BYYW%252BZ22yaTeyuZ67L5nSOhjAe6Jlu5uULI9uKlYHToeiPINpEp5PE4ptOus3GOkPaTUR9yfAZNLtTt9s39GUSsCdlLlNCRcJj5mx2eApsLpkue73fMw0Bm5ln9PwPsOFawYhjccSuq1T7hq8A%252FN2Mgn6Q%252FbMFhLdF6rEsUX%252BjfJIdoyEVUZjndaPwvH8vRTJwDjvYvJOnohuPj%252FAewmg7q3RRXPjzhu%252FKcs1hqO%252Fs9GSrwUXX%252BVajx4Afxt7N9aNcRjd9vUFBSpKf0IytkeY4vforuuIiSpoiYRwR7C5CLwV6vssJNWtkr%252BoVtsmx%252B2%252FDx1j%252FwCUHRvRXwgAAA%253D%253D/timespan/P1D

Hey @ep3p, the line 1 in code is commented where as in image it is not. Can you please check on this once.

**Comment by ep3p** [comment]
> Hey @ep3p, the line 1 in code is commented where as in image it is not. Can you please check on this once.

Hello @manishkumar1991 

The first line is commented because, when you save a function in a LogAnalytics workspace, you don't need to define a function using a ```let``` statement, you can execute the operations (the code of the function) directly.

image

image

Here I show the example of this function saved in my workspace. You can observe the tab is called "IsWorkingTime" (the name I used to save the function) and the ```let``` statement is commented (as in the code of this pull request).

image

BUT, if you don't want to save a function, or if you need to define a function just in a single query, the ```let``` statement will have to be uncommented.
 
In the demo environment I passed as an example I can't save a function because the workspace is not mine, but I can show the code works using the ```let``` statement. That's why in the example the ```let``` statement is uncommented, but in this pull request it is not.

**Comment by v-spadarthi** [comment]
Hi @manishkumar1991: Can you please take a look and provide your sign off. thanks!!

**Comment by v-mchatla** [comment]
Hi @manishkumar1991,
Author has addressed the comments. Please provide your feedback.
Thanks

**Comment by ep3p** [comment]
I am really sorry, I thought the demo environment link worked. I have edited my previous comment. The new link should work.

https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/DemoLogsBlade/resourceId/%2FDemo/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA61WyW7bMBC9%252ByvmKKGOU7dNurg%252BOUkRoL3ULnoUGGlksZZIg6TsKk3%252FvUPKFq0FQRJUgCGKnOXNm4XO0cCt%252FinVhov1ihcIcwgSZjAy9PHJrky9e1wGoszzMPwzAnrOz%252BE2BSy2phqDYRuEuFQKhQEr6kRy8rBlSmMSNXbJHE%252FTgGtry7sLxyDkPqCX35od%252FSwNUwaYSADpl8lSaZApSfK8gj0FADrOMClz7%252Fa4EWmrG1kd8vxh1hcgk8fj6fuBcy4MCs13bcmLAclU8YRVLbF3nRhscBZ6Y9TBJ%252F7bpN0ej53WITcFcRw1qVijqZCpoMsvMXg5humlZ%252B%252BaOHuuX9J5rtePba9W%252FV4KdOki16lGo2GHSpcafqwWjc%252B9xaQi2opqKctbNrM2bqSCBVWUYjlcl0pukQln2HNfFkVX%252Bc0jyksn722Q3EIW29IccDLHVeV4WpPgjuUlumIzx3gclQNx3HClTe3oarkiHK7yZLpH3ARUEzItpDBZ8GRC3xKhYRjWwVjjPowrVuV8nRlYsp1NYouTJcZSJP8TyfT1CZTa%252FBOxxJJGQmw6A6A3E165mdDbvkNDmAUEbW4nk06IBLFXCON%252BYYW%252BZ22yaTeyuZ67L5nSOhjAe6Jlu5uULI9uKlYHToeiPINpEp5PE4ptOus3GOkPaTUR9yfAZNLtTt9s39GUSsCdlLlNCRcJj5mx2eApsLpkue73fMw0Bm5ln9PwPsOFawYhjccSuq1T7hq8A%252FN2Mgn6Q%252FbMFhLdF6rEsUX%252BjfJIdoyEVUZjndaPwvH8vRTJwDjvYvJOnohuPj%252FAewmg7q3RRXPjzhu%252FKcs1hqO%252Fs9GSrwUXX%252BVajx4Afxt7N9aNcRjd9vUFBSpKf0IytkeY4vforuuIiSpoiYRwR7C5CLwV6vssJNWtkr%252BoVtsmx%252B2%252FDx1j%252FwCUHRvRXwgAAA%253D%253D/timespan/P1D

**Comment by v-mchatla** [comment]
Hi @ep3p 
Thanks for the update
@manishkumar1991 - Can you please review and provide your approval.
Thanks

**Comment by v-mchatla** [comment]
Hi @manishkumar1991 
Can you please review and provide your approval.
Thanks

**Comment by v-mchatla** [comment]
Hi @manishkumar1991 
Can you please review or route it to someone who can review it.
Thanks

**Comment by v-mchatla** [comment]
Hi @manishkumar1991
It would be great if you can spare some time to review this or assign it to someone who can review it.
Thanks

**Comment by v-spadarthi** [comment]
Hi @manishkumar1991
It would be great if you can spare some time to review this or assign it to someone who can review it.
Thanks

**Comment by manishkumar1991** [comment]
@ep3p, provided function is not generic it contains many hard coded values with respect to time and location/time zone, and please specify business need of it,

**Comment by ep3p** [comment]
@manishkumar1991 In the comments of the code it is explained that this code has to be adapted for each business.

```
// This query can help you to compute if a date (or the current time) happens during a predefined working schedule, it returns true or false.
//
// This should be adapted for each working schedule and time zone (https://docs.microsoft.com/azure/data-explorer/kusto/query/timezone)
```

The business need might come from the example that a same event may not have the same severity, depending if the event happens outside working hours or during working hours.

A domain admin account creation event may not have the same severity for a business if it happens at 10:00 AM , or at 03:00 AM .

This function can help you to compute a boolean value, true or false. The business will decide what to do with that information.

Moreover, the functions specified in this folder https://github.com/Azure/Azure-Sentinel/tree/master/Functions do not have any effect on client's Sentinel workspaces.

Adding a function in this folder will only let a Github visitor know a possibly interesting function for its needs.

If you think this is not a interesting function for any business, you might close this Pull Request.

Thank you for your time.

**Comment by v-mchatla** [comment]
Hi @manishkumar1991 
Author has provided comments, can you please check and respond accordingly.
Thanks

**Review by manishkumar1991 — APPROVED** [review]
Approved, Function looks good

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
