### PR TITLE
Add hunting queries for Remote Monitoring and Management tools

### PR DESCRIPTION
**Pull request by jischell-msft**
Change(s):
   - Advanced Hunting Queries for RMM tools added

   Reason for Change(s):
   - Hunting queries do not currently exist for RMM tools

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes (see comment 1)

### CODE REVIEW

**Comment by jischell-msft** [comment]
request for input: kql validation failing for non-ascii characters on
- Hunting Queries/Microsoft 365 Defender/RemoteManagementMonitoring/rmm_DWService_filesig.yaml
- Hunting Queries/Microsoft 365 Defender/RemoteManagementMonitoring/rmm_ServerEye_createproc.yaml
- Hunting Queries/Microsoft 365 Defender/RemoteManagementMonitoring/rmm_ServerEye_filesig.yaml
- Hunting Queries/Microsoft 365 Defender/RemoteManagementMonitoring/rmm_ServerEye_netconn.yaml

All of these queries are searching by Signer or CompanyName, where an umlaut is present in the proper name. How can this check be bypassed?

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, 
1. Several queries have exceeded 255 characters in their descriptions, please shorten them.
2. Please provide us with sample data so that we can test the queries.
Thank you.

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, 
The validation for non-ascii characters has been cleared. The above suggestions need to be taken into consideration. Thanks

**Comment by jischell-msft** [comment]
@v-atulyadav - Thanks for updating the queries requiring umlaut characters.

- For the 'description exceeds 255 characters' issue, where is this documented/ listed as a requirement? I could not find supporting checks/ documentation.
- For test data, is this a request for input data that will allow all 163 queries to be tested?

**Comment by v-atulyadav** [comment]
Hi @jischell-msft,

1. When attempting to create a hunting query, if the description exceeds 255 characters, it doesn't allow the creation of a query due to a content hub validation. Currently, there is no documentation available, But we refer to the [Query Style Guide](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide) to create an analytical rule or hunting query.
image
2. For test data, is this a request for input data that will allow all 163 queries to be tested? **Yes**

**Comment by jischell-msft** [comment]
@v-atulyadav 
- The Query Style Guide (https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#description) description section does not reference the 255 character limit either.
- Where should the test input data be shared/ sent?

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, 
1. As I mentioned earlier character limit exceed doesn't allow the creation of a query due to a content hub validation. 
2. You can add test data in below location. I would prefer to have a single table that includes all columns.
https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom

**Comment by jischell-msft** [comment]
@v-atulyadav 
- Descriptions have been updated to be less than the currently undocumented (will open issue) 255 character limit
- Test data will not be input at this time

**Comment by v-prasadboke** [comment]
Hello @jischell-msft, Thanks for the humble response. We will take a look at this and respond you with the same.

**Comment by jischell-msft** [comment]
@v-atulyadav, @v-prasadboke, bumping this pr

**Comment by v-rusraut** [comment]
Hi @jischell-msft,
We are working on it , we will provide you an update on 21 Nov 2023.
Thanks

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, please act on below points
1. File rmm_ZohoAssist_filesig.yaml  has no query
image
2. The dataTypes DeviceFileCertificateInfo, which is used in few rules against connectId MicrosoftThreatProtection, is not present in the mappings as per [Query Style Guide]

https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide

image
image

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, please update on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @jischell-msft, 
Could you please review the comments suggested above and act accordingly? Thanks

**Comment by jischell-msft** [comment]
@v-atulyadav 

- rmm_ZohoAssist_filesig.yaml has been updated to include query.

- DeviceFileCertificateInfo data type is used in current solutions/ connectors, please reference the Microsoft Defender XDR solution ( https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Defender%20XDR/Data%20Connectors/MicrosoftThreatProtection.JSON )

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
