### PR TITLE
Update on GitHub Advanced Security workbook

### PR DESCRIPTION
**Pull request by AlexDeMichieli**
In this PR I am updating the current GitHub Advanced Security workbook. 

New features:

- Filtering by organizations
- Filtering by repository topics

Screenshot 2023-08-22 at 11 04 49 AM

@v-spadarthi 
@NikTripathi 

I could not find a way to conditionally render filters (**repositories** and **repo topic**s). The idea behind these filters is that if repositories are selected, the topics filter should not be enabled, and vice versa. I was able to find a workaround where you have to deselect all repositories in order to activate the repo topics filter, but it's not ideal. Do you have any recommendations on how to improve this functionality?

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Thank you for raising this PR. This PR will be investigated and will update you by 25 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, I was trying to test the playbook but I have incomplete sample data.
Can you please share the sample data to the test the workbook, Thanks.

**Comment by AlexDeMichieli** [comment]
> Hello @AlexDeMichieli, I was trying to test the playbook but I have incomplete sample data. Can you please share the sample data to the test the workbook, Thanks.


Hi @v-prasadboke ; what test data are you missing? and how can I export test data from Sentinel? thanks!

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, We already have sample data for table githubscanaudit_CL but its incomplete.
Please modify these sample data ( https://github.com/Azure/Azure-Sentinel/blob/05276177f3272a3d374550676ba12643ab37388c/Sample%20Data/githubscanaudit_CL.json#L4 ) as per required results. 

Also please share the working images of these workbook.
Thanks,
Prasad Boke.

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke, please find below the screenshots of the dashboards

Screenshot 2023-08-27 at 10 04 01 PM
Screenshot 2023-08-27 at 10 04 14 PM
Screenshot 2023-08-27 at 10 04 29 PM
Screenshot 2023-08-27 at 10 04 42 PM

I've included additional data in the document you've shared (here's the link to download it). It should be enough to test the "topics" filter. I left some comments in the JSON file that describe the data:

https://drive.google.com/file/d/1aBrcCORfJnTxO4IrTUIvrfTXxV1l2Z0P/view?usp=sharing

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Thank you for sharing the sample data and working images of workbook. 
Will examine this images and update you about the same before EOD.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, all looks good. Please resolve the Branch conflicts so this PR can get merged

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke , for some reason I cannot solve the merge conflict nor see what areas of the workbook should get fixed. When I pull the master branch into my feature branch, no changes occur.  The new file should completely override the previous one.

**Comment by v-prasadboke** [comment]
> Hi @v-prasadboke , for some reason I cannot solve the merge conflict nor see what areas of the workbook should get fixed. When I pull the master branch into my feature branch, no changes occur. The new file should completely override the previous one.

Yes that is right, Or what we can do is we can overwrite the older workbook with the new one. 
First pull the latest from master and as you see a merge conflict overwrite the older one with new one.
Thanks.

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke , I'm stuck, sorry! I tried following your steps with no avail. I can't seem to fix the merge conflict. Is there anything you could do on your end? Thanks!

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, I've resolved the merge conflicts. You can proceed with repackaging the solution.
Thank you.

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke , thanks for the help! Before moving forward, I wanted to pick your brain on something.  Currently, the repository and topics filters are mutually exclusive, but not in a smart way. You'll need to deselect all repositories in order to activate the repo topics filter, but it's not ideal. Do you have any recommendations on how to improve this functionality?

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, We are having a discussion about this. And update you about the same before 04 September, 2023.
Meanwhile you can repackage the solution using V3 tool.
Thanks.

**Comment by v-prasadboke** [comment]
> Hi @v-prasadboke , thanks for the help! Before moving forward, I wanted to pick your brain on something. Currently, the repository and topics filters are mutually exclusive, but not in a smart way. You'll need to deselect all repositories in order to activate the repo topics filter, but it's not ideal. Do you have any recommendations on how to improve this functionality?

Hello @AlexDeMichieli, Sorry but for repo and topic I'm seeing only 1 option 
image
image

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Hope you are doing well. We just wanted to know if there are any updates on the above requested changes.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Please drop me a mail with attached json file.
v-prasadboke@microsoft.com
Thanks.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, I've received the json file. Will review it and update you about the same before 12 September, 2023.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli , Reason behind zip 3.0.0 even if repackaged to 3.0.1 is the latest 3.0.0 is not live yet.

I dont have the access to partner center where github solution can be pushed to live, If you have the access to the partner center please push the solution to live

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Looks like you have not repackaged the solution properly.
image

Please Repackage the solution again properly.

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke , I'll give it another shot and I'll let you know if I have any issues

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Thank you for the updates.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, The 3.0.0 of Github is live. You can repackage the solution with 3.0.1 Thanks

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Hope the issue is resolved with 3.0.1 repackaging and you are repackaging it too. Just wanted to know some updates on the solution. Thanks.

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Please confirm on the maintemplate.
Thanks.

**Comment by AlexDeMichieli** [comment]
> Hello @AlexDeMichieli, Please confirm on the maintemplate. Thanks.

Hi Prasad, I'll be back to the office next Tuesday. Thanks so much for repackaging the solution! I just wanted to confirm the next steps. Can I pull from the branch, get the mainTemplate.json and publish it?

**Comment by v-prasadboke** [comment]
Hello @AlexDeMichieli, Review is not completed yet. I was waiting for your confirmation on maintemplate. Is it ok or not?
I'll review the maintemplate and get it merged.
Please keep the solution on hold for publishing.

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke , the maintemplate looks fine to me! Thanks!

**Comment by v-prasadboke** [comment]
Thank you @AlexDeMichieli for confirmation.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by AlexDeMichieli** [comment]
Hi @v-prasadboke, what would be the next step? Thanks!

**Pull request merged**
