### PR TITLE
GN 3.0.1 updates

### PR DESCRIPTION
**Pull request by punkrokk**
Required items, please complete
   
   Change(s):
   - Update metadata, instructions and a bug in Data Connector. 
   - Data connector -> v1.0.1
   - Solution -> v3.0.1

   Reason for Change(s):
   - Docs and Data Connector Bugfix

   Version Updated:

   Testing Completed:
   - Tested in Azure Function App and Sentinel

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @punkrokk,

- We updated below files , please extract these files from zip file
[Updated Files.zip](https://github.com/Azure/Azure-Sentinel/files/13577347/Updated.Files.zip) and replace files in your solution folder, also update createUidefinition and mainTemplate in package 3.0.1 as well.

1. createUiDefintion - Added release note link.
2. mainTemplate       - Removed duplicate text 'using Azure Functions',
3. ReleaseNotes        - Changed the sequence of version, new version should be on top.

-  Please remove text   'Using Azure Functions' from file 'GreyNoiseConnector_UploadIndicatorsAPI.json', as our packaging tool will automatically generate this.
image

Thanks

**Comment by punkrokk** [comment]
I updated everything you asked for @v-rusraut

**Comment by v-rusraut** [comment]
Hi @punkrokk,

In Package version zip file we only need to keep createUiDefinition and mainTemplate file.
Please replace  your package zip 3.0.1  with  attached zip file.
[3.0.1.zip](https://github.com/Azure/Azure-Sentinel/files/13596571/3.0.1.zip)

Thanks

**Comment by punkrokk** [comment]
> Hi @punkrokk,
> 
> In Package version zip file we only need to keep createUiDefinition and mainTemplate file. Please replace your package zip 3.0.1 with attached zip file. [3.0.1.zip](https://github.com/Azure/Azure-Sentinel/files/13596571/3.0.1.zip)
> 
> Thanks

@v-rusraut fixed.

**Review by v-rusraut — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
