### PR TITLE
solution created fortiwebcloud

### PR DESCRIPTION
**Pull request by v-laanjana**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution 
fortiwebcloud
See guidance below
Version Updated:
2.0.0
See guidance below
[test doc](https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBCEB97C2-2DE6-462F-9CA5-F0116F691956%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Fortiwebcloud.docx&action=default&mobileredirect=true&share=IQHCl-u85i0vRpyl8BFvaRlWAUGmDV5ovZ2gw1i0VgmYE60)

See guidance below
This is an 3P solution.

### CODE REVIEW

**Comment by NikTripathi** [comment]
@v-atulyadav  Please have a look.

**Comment by v-atulyadav** [comment]
We closed this PR as solution is on hold.

**Comment by v-laanjana** [comment]
@v-atulyadav  please review and let me know as your closed wrong PR.

**Comment by v-laanjana** [comment]
Team we have dependency  from FTE

**Comment by v-laanjana** [comment]
waiting confirmation from FTE.

**Comment by v-atulyadav** [comment]
We are awaiting confirmation from FTE

**Comment by v-atulyadav** [comment]
There is a dependency on FTEs

**Comment by v-atulyadav** [comment]
waiting confirmation from FTE.

**Comment by v-atulyadav** [comment]
waiting confirmation from FTE.

**Comment by v-spadarthi** [comment]
waiting confirmation from FTE.

**Comment by v-atulyadav** [comment]
There is a dependency on FTEs

**Comment by v-atulyadav** [comment]
Hi @v-laanjana , can you please check on above.

**Comment by v-spadarthi** [comment]
@v-atulyadav please review and let @v-laanjana  know as your closed wrong PR.

**Review by v-atulyadav — COMMENTED** [review]
@v-laanjana , please replace text from `Azure Sentinel` to `Microsoft Sentinel` from playbooks readme file.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
