### PR TITLE
Update file for deployment using PowerShell - AlertIQ

### PR DESCRIPTION
**Pull request by hvanh2122**
changed API version for data connectors and add more connectors

### CODE REVIEW

**Comment by NikTripathi** [comment]
@sreedharande Please have a look and if ok please approve. Thanks

**Comment by v-laanjana** [comment]
@sreedharande Please have a look and if ok please approve. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande, please check and provide your feedback. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , @hvanh2122 made some changes to the file, please check them. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande ,Please check the changes made by @hvanh2122 to the file. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande, Could you please check for the changes @hvanh2122 made almost a month ago. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande, @hvanh2122 made some changes almost a month ago, could you please check them. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande , @hvanh2122 made some changes to the file, please check them. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande ,Please check the changes made by @hvanh2122 to the file. Thank you.

**Comment by v-atulyadav** [comment]
Hi @sreedharande, Could you please check for the changes @hvanh2122 made almost a month ago. Thank you

**Comment by v-atulyadav** [comment]
Hi @sreedharande , please check the changes made by @hvanh2122 to the file. Thank you.

**Comment by v-spadarthi** [comment]
Hi @sreedharande , please check the changes made by @hvanh2122 to the file. Thank you.

**Review by sreedharande — CHANGES_REQUESTED** [review]
@hvanh2122 - May i know the reason for adding new file again - i didnt see changes - can you please close this PR and open new PR with only changes

**Comment by hvanh2122** [comment]
Hi @sreedharande, I created a new PR with only changes to the files. Please check them. Thank you!!

**Pull request closed without merging**
