### PR TITLE
 - synack solution with Data Connector

### PR DESCRIPTION
**Pull request by andriykozynets**
The Synack Data Connector provides an Azure Function that creates Sentinel Incidents for each Vulnerability in Synack platform. Only Sentinel Incidents Rest API is used. The log analytics REST API is not used.

There is a couple of places I have some concerns about.

1. The Data Connector template https://github.com/synack/Azure-Sentinel/blob/synack_integration/Solutions/Synack/Data%20Connectors/Synack_API_FunctionApp.json has a "Deploy to Azure" button that uses git path to Function deployment template and the path is to our Synack fork of the repo and synack_integration branch
`[Deploy To Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fsynack%2FAzure-Sentinel%2Fsynack_integration%2FSolutions%2FSynack%2FData%2520Connectors%2Fazuredeploy_Synack_API_FunctionApp.json)`

2. The Azure Function deployment template https://github.com/synack/Azure-Sentinel/blob/synack_integration/Solutions/Synack/Data%20Connectors/azuredeploy_Synack_API_FunctionApp.json uses zip package file referenced from our repo fork and branch, similar to point 1.
`{
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "https://github.com/synack/Azure-Sentinel/blob/synack_integration/Solutions/Synack/Data%20Connectors/SynackConn.zip?raw=true"
            }`

I believe that at some point these paths will transform to "https://aka.ms/***" -like paths, but I don't have full understanding how and when this should be done.

### CODE REVIEW

**Comment by NikTripathi** [comment]
@andriykozynets We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from Azure:master so that the PR Validations can be executed.... Thanks!!!

**Comment by ashishsyal** [comment]
@andriykozynets - Can you update if you have followed last comment from @NikTripathi

**Comment by andriykozynets** [comment]
> @andriykozynets - Can you update if you have followed last comment from @NikTripathi

Hi @NikTripathi , @ashishsyal 
I didn't reply yet because we are discussing our solution with your team now (namely with Preeti Krishna and Eric Burkholder). Part of the discussion is that this will probably not be packaged as a Data Connector, but will have a different packaging type. I asked Preeti if it still makes sense for use to work on this PR, but I didn't get a response yet.

P.S. otherwise, the code in this PR is the latest, we don't have anything new to commit.

Kind regards,
Andrey K

**Comment by v-rucdu** [comment]
> > @andriykozynets - Can you update if you have followed last comment from @NikTripathi
> 
> Hi @NikTripathi , @ashishsyal I didn't reply yet because we are discussing our solution with your team now (namely with Preeti Krishna and Eric Burkholder). Part of the discussion is that this will probably not be packaged as a Data Connector, but will have a different packaging type. I asked Preeti if it still makes sense for use to work on this PR, but I didn't get a response yet.
> 
> P.S. otherwise, the code in this PR is the latest, we don't have anything new to commit.
> 
> Kind regards, Andrey K

@andriykozynets : I see that you have raised another [PR](https://github.com/Azure/Azure-Sentinel/pull/4008) with the same content, so if this PR is not required can you please close this?.... Thanks!!

**Comment by andriykozynets** [comment]
Closing this pull request as this is not relevant anymore. We have another PR for Synack Sentinel Solution https://github.com/Azure/Azure-Sentinel/pull/4008

**Pull request closed without merging**
