### PR TITLE
feat: add Playbooks/Enrich-Intezer-Analyze

### PR DESCRIPTION
**Pull request by juju4**
Change(s):
   - add Playbooks/Enrich-Intezer-Analyze - https://www.intezer.com/blog/malware-analysis/intezer-analyze-free-community-edition
/

   Reason for Change(s):
   - Data Enrichment

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @rahul0216, can you please review this and provide your feedback accordingly. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rahul0216, can you please provide your feedback accordingly. Thanks

**Comment by manishkumar1991** [comment]
@juju4 , 
for creating the playbooks arm template
kindly use the playbook arm template generator tool for creating the playbook template and then fill out all the necessary meta data ,

Kindly check below link for arm template generator
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator

And then kindly fill up the meta data details as well 
kindly check below link for reference on metadata details
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/ThreatXCloud/Playbooks/ThreatXPlaybooks/ThreatX-BlockIP-URL

Kindly check the below arm template code and readme file on how to integrate the keyvault with logic app for fetching the secrets and mention the steps as well in readme file on how to create and store the api key in keyvault and also how to assign the access policies to key vaults

**Comment by juju4** [comment]
Metadata added.

Thanks for the [Playbook-ARM-Template-Generator](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator) reference. I will use it next time.

What is needed to change on key vault use?
What are the differences and why does it matter?
I followed a similar scheme than some existing playbook of this repository.

**Comment by manishkumar1991** [comment]
@juju4 Permission to access key vault keys should be provided else user will get an error 
image

Kindly mention the steps on how to get access to key vault using access polices.
image

Second ,
You have hard coded the Key name in logic app and didn't mentioned in readme file that user has to create the secret in keyvault with same name .
image

third :
Api key is visible while doing the deployment of the playbook .

All above mentioned issues need to be resolved only then the playbook will work.

**Comment by v-atulyadav** [comment]
Hi @juju4, please resolve playbook issues mentioned by @manishkumar1991. Thanks.

**Comment by juju4** [comment]
1. added
2. In Prerequisites, there is already: "Keyvault to store Intezer API key as secret malware-intezer-api-key". want something else?
3. I don't understand. The api key is in the keyvault and use only at run. Only the keyvault reference can appear during playbook deployment.

The playbook is already working in production in my environment since many months and deployed through Sentinel Repository feature.

**Comment by v-atulyadav** [comment]
Hi @manishkumar1991, @juju4 has responded to your comments, please check and respond accordingly. Thanks.

**Review by manishkumar1991 — APPROVED** [review]
approved

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Comment by juju4** [comment]
Thanks!

**Pull request merged**
