### PR TITLE
04 21 2023  as azure ad enable user

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - New Playbook
   - Because the playbook is meant to be used with a playbook we put out previously, documentation has been updated in this other playbook so that each can reference one another
   - Update to our company name

   Reason for Change(s):
   - See above

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @manishkumar1991 @rahul0216,
Please provide your feedback
Thanks

**Comment by v-rbajaj** [comment]
Hi @manishkumar1991, @rahul0216, can you please look into this PR?

**Comment by manishkumar1991** [comment]
> Hi @manishkumar1991, @rahul0216, can you please look into this PR?

Reviewing

**Review by manishkumar1991 — APPROVED** [review]
approved

**Review by rahul0216 — APPROVED** [review]
Changes look good.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
