### PR TITLE
093022 as zscaler add domains to url category

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - Updated azuredeploy.json, readme.md, and images

   Reason for Change(s):
   - our company has refined our documentation process and Azure has new "best practices" for playbooks. Both have been implemented

   Version Updated:
   -n/a

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @devikamehra, @rushriva 
Did you get a chance to review these PRs. Let us know if you need any details over here.
Thanks

**Comment by v-spadarthi** [comment]
Hi @devikamehra, @rushriva
Did you get a chance to review these PRs. Let us know if you need any details over here.
Thanks

**Comment by v-mchatla** [comment]
Hi @manishkumar1991,
Could you please review the playbooks and provide your feedback.
Thanks

**Comment by manishkumar1991** [comment]
@AcceleryntSecurityDev please confirm if you have used, our "playbook arm template generator tool" for generating the arm template of provided playbook, if not requesting you to please use the below link to generate the arm template and update the PR

https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please address @manishkumar1991 comments.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please try creating the playbooks using playbook arm template generator tool if not done earlier. and also accept license/cla to accept your contribution.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please try creating the playbooks using playbook arm template generator tool if not done earlier. and also accept license/cla to accept your contribution.
Thanks

**Comment by v-mchatla** [comment]
> Hi @AcceleryntSecurityDev,
> Can you please try creating the playbooks using playbook arm template generator tool if not done earlier. and also accept license/cla to accept your contribution.

Hi @AcceleryntSecurityDev 
can you please confirm on the tool you have used for playbook preparation.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please try creating the playbooks using playbook arm template generator tool. and also accept CLA to accept your contribution.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please try creating the playbooks using playbook arm template generator tool. and also accept CLA to accept your contribution.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
We wanted to check on the status of PR #6282 . PR is pending from more than 30 days. Let us know if any assistance is required for this PR. As Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please go through the steps mentioned [here](https://github.com/microsoft/contributorlicenseagreement).
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please go through the steps mentioned above and accept CLA

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please go through the steps mentioned above and accept CLA.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev,
Can you please go through the steps mentioned above and accept CLA.
Thanks

**Comment by v-mchatla** [comment]
Hi @AcceleryntSecurityDev  
Since we have not received response from last 7 days, we are closing your PR per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. 
Thank you for your cooperation.

**Pull request closed without merging**
