### PR TITLE
Ashwin/mar23 Bugfixes FileHash extraction logic and Static URL to Servicetags

### PR DESCRIPTION
**Pull request by ashwin-patil**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - updated Servicetags.json URL as static from mstic github which is updated weekly via Github Action.
   - updated various IOC queries file hash extraction logic to avoid it as coming as null

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Review by petebryan — DISMISSED** [review]

**Comment by v-prasadboke** [comment]
Hello @ashwin-patil KQL validation check is failing for the PR 
can you please resolve the failures

**Comment by ashwin-patil** [comment]
> Hello @ashwin-patil KQL validation check is failing for the PR can you please resolve the failures

Still working on the changes. will respond once PR is ready to review.

**Comment by v-atulyadav** [comment]
Hi @ashwin-patil, would it be possible for you to mark this PR as a draft until it is ready for review? Thanks

**Comment by ashwin-patil** [comment]
> Hi @ashwin-patil, would it be possible for you to mark this PR as a draft until it is ready for review? Thanks

The PR is ready now. All checks are passing.

**Review by petebryan — APPROVED** [review]

**Pull request merged**
