### PR TITLE
transformations/filtering review

### PR DESCRIPTION
**Pull request by juju4**
Change(s):
   - See guidance below

   Reason for Change(s):
   - Review and more straightforward deployment with Sentinel Repository Feature
   - More documentation

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by javiersoriano** [comment]
Please remove the changes to the README file as PowerShell instructions are more complex than using the "Deploy to Azure" button, and we don't want users to default to that, nor the intention is to replace the documentation.

It would be good to add a link to the official docs on this: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/data-collection-transformations

**Comment by javiersoriano** [comment]
@juju4 I'd like to remove some of the things you highlight in the limitations as these are already documented.

* Microsoft.Insights/dataCollectionRules must be deployed in same location than their target Azure Logs Analytics. **(KEEP)**
* From a syntax perspective
  * transformKql seems to always start with "source", not the targeted table name **(REMOVE)**
  * Targeted table name is defined by streams value (Microsoft-Table-AWSVPCFlow, Microsoft-Syslog...). See documentation for supported values. **(KEEP)**

**Comment by v-atulyadav** [comment]
Hi @juju4, please check above comments from @javiersoriano and act accordingly.  Thanks

**Comment by v-atulyadav** [comment]
Hi @juju4.
I would appreciate it if you checked the above comments from @javiersoriano and responded accordingly.
Thanks

**Comment by v-atulyadav** [comment]
Hi @juju4, hope you are doing well. Just wanted to check if you got a chance to look at the suggestions shared. Please feel free to reach out to us for any queries and/or support. Thanks

**Comment by juju4** [comment]
docs change done

**Comment by javiersoriano** [comment]
Thanks @juju4 . @v-atulyadav please merge

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
