### PR TITLE
Dev/normalization/z scaler dns update to latest cef

### PR DESCRIPTION
**Pull request by oshezaf**

### CODE REVIEW

**Review by yaronMSFT — COMMENTED** [review]
on The vim file need to change version and date

**Comment by oshezaf** [comment]
@YaronFruchtmann : thanks. updated version/date. Good to merge?

**Review by yaronMSFT — APPROVED** [review]
Good to go

**Comment by oshezaf** [comment]
@YaronFruchtmann : technically you should approve so I don't have to force merge... Anyways I did merge.

**Pull request merged**
