### PR TITLE
11 01 2024  as iam master playbook

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
  - New playbook

   Reason for Change(s):
  - New playbook

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

image

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Thanks for raising this PR. You have raised common playbooks in this https://github.com/Azure/Azure-Sentinel/pull/9770 can you please check once

**Comment by AcceleryntSecurityDev** [comment]
@v-prasadboke These playbooks are two different versions of one another. This has azure ad playbooks plus two additional okta playbooks. We thought to make the other version, https://github.com/Azure/Azure-Sentinel/pull/9770, for the azure ad customers that do not use okta. The same playbooks are needed in each version because the master playbook template will not deploy without them. The idea here is that a user is picking either one version of this master playbook or the other, depending on if they use okta or not.

**Comment by v-prasadboke** [comment]
Got it @AcceleryntSecurityDev, I'll continue to investigate this PR

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Please add 
"source": {
    "kind": "Community"
}
in the metadata section of playbooks

**Comment by AcceleryntSecurityDev** [comment]
> Hello @AcceleryntSecurityDev, Please add "source": { "kind": "Community" } in the metadata section of playbooks

This has been done, thanks

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
