### PR TITLE
New M365 hunting queries added and v2 of an existed query added

### PR DESCRIPTION
**Pull request by kddx0178318**
New queries added:

Command and Control:
-Detects URLs in regkey RegistryValueData.
-WebDav Client Execution - Network connections using DavSetCookie - BY IP - Botnet detection.

Initial Access:
-File Archiver in the browser URL click.

Execution:
-Suspicious behavior wscript launching JS

V2 of an existed query added:

Persistence:
-riskySignInToNewMFAMethod_V2

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by kddx0178318** [comment]
@microsoft-github-policy-service agree

**Comment by v-atulyadav** [comment]
Hi @kddx0178318,
KQL validation failures please see below for your reference. Thanks
image

**Comment by kddx0178318** [comment]
Hi @v-atulyadav , I really don't know what's wrong into my code. I don't even use dictionaries, only sets for printing the results, I tried change spaces, and other characters in my code which perhaps make this fail unsuccessfully. All the queries have almost all errors somehow as per https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=74626&view=ms.vss-test-web.build-test-results-tab.

The most similar thing to a dictionary that i have is the make_set() function, which, i can't remove, otherwise the result of the query will make no sense, will give many FPs, etc.

I've used these queries since I've created them both in M365 and Sentinel (a bit adapted like Timestamp, added as Timegenerated) and always worked. Not sure why not pass the checks..

I would really appreciate your help and support here. Thanks a lot! :)

**Comment by kddx0178318** [comment]
Hey @v-atulyadav , I am still unable to commit the queries. Any more suggestions? Thanks in advance.

**Comment by v-atulyadav** [comment]
Hi @kddx0178318,
I have modified one query, as shown below. You need to update all queries accordingly. 
image
You can refer Query Style Guide (https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide) for the same
And also, you need to add missing columns to the sample data.
image
Also upload sample data in below location
https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom

**Comment by v-atulyadav** [comment]
Hi @kddx0178318,
Please act on above suggestions. Thanks

**Comment by v-atulyadav** [comment]
Hi @kddx0178318,
We are waiting for your response. Thanks

**Comment by kddx0178318** [comment]
hi @v-atulyadav , apologies for the delayed response, Im having some personal issues and i can't dedicate right now time to this, hence, let me close the pull and open it again once everything is more calm for me, again, apologies again for bothering. Thanks a lot for all the support, will be back.

**Pull request closed without merging**
