### PR TITLE
EndpointThreatEssetials_AnalyticsRules

### PR DESCRIPTION
**Pull request by vakohl**
Required items, please complete
   
   Change(s):
   - Case-sensitivity, Entity mapping

   Reason for Change(s):
   - rules re-validation

   Version Updated:
   - various

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by rahul0216 — COMMENTED** [review]
Rule PotentialRemoteDesktopTunneling.yaml has Name and UPNSuffix as Identifier for Account Entity but for many other rules Account Entity has only Name identifier. Any specific reason?

**Comment by vakohl** [comment]
> Rule PotentialRemoteDesktopTunneling.yaml has Name and UPNSuffix as Identifier for Account Entity but for many other rules Account Entity has only Name identifier. Any specific reason?

**Comment by vakohl** [comment]
> Rule PotentialRemoteDesktopTunneling.yaml has Name and UPNSuffix as Identifier for Account Entity but for many other rules Account Entity has only Name identifier. Any specific reason?

thanks for checking @rahul0216 Mostly other rules are based on 'Event' table. I found 'User' value in that table is always coming as windows username unlike email or UPN format. That's the reason I didn't split User.

**Review by rahul0216 — APPROVED** [review]
Changes look good.

**Pull request merged**
