### PR TITLE
Azure WAF TemplateSpec-DO NOT MERGE AS 1P

### PR DESCRIPTION
**Pull request by v-sabiraj**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Azure Active Directory Identity Protection.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - [Test Doc]
See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by mkchiliveri — DISMISSED** [review]
Looks good, Approved.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Can you please get confirmation on the PR merge or closure.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj
Can you please get confirmation on the PR merge or closure.
Thanks

**Comment by v-mchatla** [comment]
We are working on Skip Validations

**Comment by v-mchatla** [comment]
Its having duplicate Analytic Rule. Checking with Ashish to create dependency.
Thanks

**Comment by v-mchatla** [comment]
Checking with Ashish to create dependency for Analytic Rule.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Can you please get more details on how to add dependency for duplicate Analytic Rule and provide an update.
Thanks

**Comment by v-spadarthi** [comment]
Hi @v-sabiraj
Can you please get more details on how to add dependency for duplicate Analytic Rule and provide an update.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj
Can you please get more details on how to add dependency for duplicate Analytic Rule and provide an update.
Thanks

**Comment by v-mchatla** [comment]
Hi,
We are working on how to add dependency. Will keep you posted once done with the changes.
Thanks

**Comment by v-mchatla** [comment]
Hi,
We are working on how to add dependency. For now we kept it in backlog, once we got the required information will make necessary changes and close it.
Thanks

**Comment by v-mchatla** [comment]
Hi,
We are working on how to add dependency. For now we kept it in backlog, once we got the required information will make necessary changes and close it.
Thanks

**Comment by v-mchatla** [comment]
Hi,
We are working on how to add dependency. For now we kept it in backlog, once we got the required information will make necessary changes and close it.
Thanks

**Comment by v-mchatla** [comment]
Hi,
We are working on how to add dependency. For now we kept it in backlog, once we got the required information will make necessary changes and close it.
Thanks

**Comment by v-mchatla** [comment]
Hi,
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi 
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi
It's still on hold. We will provide update once done.
Thanks

**Comment by v-mchatla** [comment]
Hi,
Converted to draft as need some time to fix these.
Thanks

**Comment by v-sabiraj** [comment]
Closing this Pr as another PR(https://github.com/Azure/Azure-Sentinel/pull/6938) is raised for same file changes.

**Pull request closed without merging**
