### PR TITLE
Created Package

### PR DESCRIPTION
**Pull request by NCsteven**
Created package

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @NCsteven, please act on below points

1. please repackage this solution using this tool --> https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2 with version 2.0.0 instead of 1.0.0.

2. Also include data file in `Solutions/NetClean ProActive/Data/` path.
3. Add workbook preview images in `Solutions\NetClean ProActive/Workbooks/Images/Preview/` path.
4. please add metadata for workbook in `Tools\Create-Azure-Sentinel-Solution\V2\WorkbookMetadata\WorkbooksMetadata.json`
5. Also add sample data in `Sample Data/` path.

**Comment by NCsteven** [comment]
Hi @v-atulyadav 
i have updated the packages and modified the data connector instructions since they where not properly shown in Sentinel.
the sample data should already be present in: 
https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Netclean_Incidents_CL.json

please let me know if i have misunderstood anything, i will just check so everything works as expected and i will push the new files later today.


BR
Steven

**Comment by v-atulyadav** [comment]
Hi @NCsteven, 
Input folders and files should not be included in this PR.

image

Also resolve branch conflicts.
Thanks

**Comment by v-atulyadav** [comment]
Hi @NCsteven, can we schedule a call to discuss on this PR? if yes then schedule a call ASAP. my mail id is v-atulyadav@microsoft.com we are working in IST timezone.

**Comment by v-atulyadav** [comment]
Hi @NCsteven, Thank you for the fixes. We will provide you with an update by the end of the day today.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
