### PR TITLE
update solution Atlassian Jira Audit with playbook

### PR DESCRIPTION
**Pull request by v-laanjana**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution 
Atlassian Jira Audit
See guidance below
Version Updated:
2.0.0
See guidance below
Testing Completed:
The link for test results is
[Sentinel Solution Migratio](https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B713A5F28-86CC-4711-8D10-5E0E3EBDCE4E%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Atlassian%20Jira%20Audit.docx&action=default&mobileredirect=true&share=IQEoXzpxzIYRR40QXg4-vc5OAef83wmASBZwdG91TkPZbAM)n

See guidance below
This is an 3P solution.

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Please update description for data connector and workbook
image
image

**Comment by v-sabiraj** [comment]
Please update the providers, it is showing as Application actual it should be Atlassian
image
image

**Comment by v-sabiraj** [comment]
colons missing after costs
image

**Comment by v-sabiraj** [comment]
Update title according to trigger
image

**Review by v-sabiraj — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
