### PR TITLE
Updated Playbooks with the change of Adaptive card title.

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Required items, please complete
   
   Change(s):
   - Updated adaptive card action by adding meaningful title information in the playbook.

   Reason for Change(s):
   - For better understanding of user input form and its submission message which is sent to the MS Teams channel.

   Version Updated:
   - 2.0.2

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hello @jayeshprajapaticrest 

As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using V3 tool Please go through this readme file on how to use the V3 tool https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

And we need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by v-rusraut** [comment]
Hi @jayeshprajapaticrest 
Please check comment above and act accordingly.
Thanks

**Comment by v-rusraut** [comment]
Hi @jayeshprajapaticrest 
Please check comment above and act accordingly.
And also, to resolve validation issue, take latest from master branch into your branch and push again.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest Please check comment above and act accordingly. And also, to resolve validation issue, take latest from master branch into your branch and push again. Thanks

Sure will do it.

**Comment by v-rusraut** [comment]
hi @jayeshprajapaticrest 
Any Update ?
We are waiting for your response.
Thanks

**Comment by jayeshprajapaticrest** [comment]
> hi @jayeshprajapaticrest Any Update ? We are waiting for your response. Thanks

@v-rusraut 
Done the changes as suggested above.
Please proceed. Thanks

**Comment by v-rusraut** [comment]
Hi @jayeshprajapaticrest,
Thanks for reply, we will provide update on 04 Aug 2023.

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, please check below few points and change accordingly.

1. Playbooks deployment is failing due to null values, so either remove the entire line or replace null with values.
 a. RubrikRansomwareDiscoveryAndVMRecovery
 
image

b. RubrikRansomwareDiscoveryAndFileRecovery
image

c. RubrikIOCScan
image

2. Createui file cosmetic change
 - It would be helpful if you put a space between `.` and Azure. You need to give space in the Data file to accommodate this change.
 
image
image

**Note: Once all the above changes have been incorporated, the solution needs to be repackaged.**

**Comment by jayeshprajapaticrest** [comment]
@v-atulyadav Will check and update you as soon as possible.

**Comment by v-atulyadav** [comment]
Thanks @jayeshprajapaticrest.

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest,
We'd appreciate it if you could let us know when your work is finished. Feel free to contact us with any queries or support.
Thanks

**Comment by jayeshprajapaticrest** [comment]
@v-atulyadav 
- Done with the createui cosmetic related changes.
- Regarding failing of the deployment of Playbooks, We have again deployed in our environment and we are able to deploy playbooks successfully without failed even if it contains the null values.

**Note:** The pointed null values related thing is not the part of this PR(i.e. We didn't assign the null value. Its already in the previously merged PR.)

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, 
Can you please attach screenshots of the successfully running playbooks here? Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, Can you please attach screenshots of the successfully running playbooks here? Thanks

@v-atulyadav Do I need to share screenshot of the successfully deployed playbook? OR about the successfully ran playbook?

**Comment by jayeshprajapaticrest** [comment]
@v-atulyadav 
Please find the attached screenshot of successfully deployed playbooks in our environment which are failing in your environment.
a. RubrikRansomwareDiscoveryAndVMRecovery
RubrikRansomwareDiscoveryAndVMRecovery
b. RubrikRansomwareDiscoveryAndFileRecovery
RubrikRansomwareDiscoveryAndFileRecovery
c. RubrikIOCScan
RubrikIOCScan

Let me know if anything if required. Thanks!!

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, it would be great if you shared screenshots of successfully run playbooks. Thanks

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, please share running playbooks screenshots. Thanks

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, we will be waiting for screenshots of the successfully running playbooks. Thanks

**Comment by v-atulyadav** [comment]
Hi @jayeshprajapaticrest, 
Could you please share the screenshots of the running playbooks? Thanks

**Comment by jayeshprajapaticrest** [comment]
@v-atulyadav 
Please find the attached screenshot of Running Playbook.
[IOC.pdf](https://github.com/Azure/Azure-Sentinel/files/12407966/IOC.pdf)
[VMRecovery.pdf](https://github.com/Azure/Azure-Sentinel/files/12407967/VMRecovery.pdf)

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
