### PR TITLE
Fixing broken link

### PR DESCRIPTION
**Pull request by tj-senserva**
Required items, please complete
   
   Change(s):
   - Updated JSON template files to replace broken link

   Reason for Change(s):
   - Fixing broken link

   Version Updated:
   - Yes
   - 2.0.2

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @tj-senserva, As suggested below, please update all occurrences of API version in Maintemplate.json and include it in the zip file as well. Thanks
image

**Comment by tj-senserva** [comment]
Hi @v-atulyadav, these changes have been made

**Comment by v-atulyadav** [comment]
Hi @tj-senserva, 
There are changes in Maintemplate.json, but this maintemplate has not been included in zip file, as zip file maintemplate still contains the old API version.

image

**Comment by v-atulyadav** [comment]
Hi @tj-senserva, please act on comments. Thanks

**Comment by tj-senserva** [comment]
@v-atulyadav Done

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
