### PR TITLE
Update KQL Training Solution to Address Issues

### PR DESCRIPTION
**Pull request by malowe101**
Required items, please complete
   
   Change(s):
   - Updated IntroToKQL workbook to fix ongoing issue that breaks the tool.
   - Updated the details file to update 2.0.0 to 2.0.1
   - Updated maintemplate to contain the new JSON for the IntotoKQL JSON
   - Updated 2.0.0.zip to 2.0.1.zip that contains the new maintemplate file

   Reason for Change(s):
   - IntoToKQL workbook had an issue that broke the tool and prevented users from being able to use it.

   Testing Completed:
   - Workbook has been deployed from code and it works as expected.

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by malowe101** [comment]
I cannot repackage this solution as Microsoft has removed admin privileges on local machines. I cannot install the required components to repackage the content.

**Comment by v-atulyadav** [comment]
Hi @malowe101,

Please refer to the guidelines below to repackage the solution with version 3.0.0.

Please package the solution using V3 tool, please go through this readme file on how to use the V3 tool.
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

Add ReleaseNotes file for solution,please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by v-atulyadav** [comment]
Hi @malowe101, hope you are doing well. Just wanted to check if you got a chance to look at the suggestions shared. Please feel free to reach out to us for any queries and/or support. Thanks

**Comment by v-atulyadav** [comment]
Hi @malowe101, 
I would appreciate it if you checked the suggested changes above and acted accordingly. Thanks

**Comment by v-atulyadav** [comment]
Hi @malowe101, 
I've repackaged the solution with v3 and am now trying to clear validations. I'll test the package and let you know by 11 Aug 2023. Thanks

**Comment by v-atulyadav** [comment]
Hi @malowe101,
As we did not delete older versions from the solution, we have included 2.0.0 as well. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by malowe101** [comment]
Sorry, I have been in and out of office. My apologies for the lack of response but thank you for assisting in getting this addressed. Regarding repackaging, the company has locked down local accounts so we cannot run the packaging script if we do not have the correct components for it already installed.

**Pull request merged**
