### PR TITLE
Azure DDOS Protection pkg update

### PR DESCRIPTION
**Pull request by v-prasadboke**
Change(s):
   - New Schema for Data connector: DDOS.json 
   - New Schema for Create UI Definition 

     Version Updated:
   - 2.0.3
   - Resolved PR #7217  

   Testing Completed:
   - Yes
   - Link:- https://microsoft-my.sharepoint.com/:w:/p/v-prasadboke/Eaj09KRcJy1DuAbU3mJAZU0BAZt5vuw9KM7ebHaVgHQ16g?e=ol0mp3
   
   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, will provide you an update on this ASAP.

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, data connector description link not showing.

image

**Review by v-atulyadav — DISMISSED** [review]

**Comment by v-prasadboke** [comment]
Do Not merge

**Comment by cwatson-cat** [comment]
> Hi @v-prasadboke, data connector description link not showing.
> 
> image

I think that's expected. My understanding is that the 1P connectors are hard-coded in the UI. I've updated the description so we can pull the description down into Microsoft Sentinel Documentation (from the repo). @prtanej

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
