### PR TITLE
ZeroFox Solution: Fix project structure for Data Connector deployment

### PR DESCRIPTION
**Pull request by DNRRomero**
Change(s):
   - Reorganized the project structure for azure function-based data connectors in the ZeroFox Solution.

   Reason for Change(s):
   - The current project structure causes issues during deployment that block use by ZeroFox users

   Version Updated:
   - No

   Testing Completed:
   - Need Help

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by DNRRomero** [comment]
Hi @v-sudkharat, we created the PR as requested

**Comment by v-sudkharat** [comment]
@DNRRomero, I just checked the updated zip file and found that, Inside the zip there are sub-folder is created and due to that the function apps do not get displayed. 
So, Could you please correct it and retest it once by taking ref. of below screenshots, and if still having issue. Please let me know will schedule a call for Tomorrow. Thanks! 

1. Inside the zip file remove below highlighted folder, which is not required: -

image

 2. Inside the zip file there is subfolder with the name "AzureFunctionZeroFoxCTI" which contain the function app. So please just place those files outside and remove that created sub-folder. 
 
image

Expected : Below zi there is not subfolder added -

image

**Comment by DNRRomero** [comment]
Hey @v-sudkharat  given your instructions, I was able to deploy our data connectors, thank you!
image
The app should be ready for repackaging

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, The changes look good now. Could you please re-package this solution and commit the into this PR. 
Regarding the connector, as it displayed into the function so please add the connector successfully connected screenshots over here for both the connector- 
**1. CTI connector 
2. Alerts connecto**r 

After successfully connected the connector, please add screenshot link below :-
image

And for azure functions, need to add screenshots with function app working successfully. Thanks!

**Comment by DNRRomero** [comment]
Hi @v-sudkharat  I re submitted the changes you requested and, while trying to re deploy my main template for testing I received the following error
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/-dc-t36lq3wueus7i' for type 'Microsoft.OperationalInsights/workspaces/providers/contentTemplates' at line '96' and column '87' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}

**Comment by DNRRomero** [comment]
Hi @v-sudkharat  I have all connectors working, can we sync?
The solution is ready for merge

**Comment by DNRRomero** [comment]
Hi @v-sudkharat  
Alerts CCP connector works as expected
image

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, Thanks for the update, I will review the content, and can we block time on 21-05-2024 for a sync?

**Comment by DNRRomero** [comment]
Hey @v-sudkharat , can it be the 20th? or better yet some day this week? the 21st is a holiday in my country

**Comment by v-sudkharat** [comment]
@DNRRomero, ok, I will send an invite over mail.

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, please revert the changes for below highlighted solution folder :- 
image

**Comment by v-sudkharat** [comment]
Remove the duplicate data connector description from Createui file and update the same into 3.0.1 zip as well. -
image

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, Is function app started received logs for remaining data types?

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, We are still waiting for your response. Thanks!

**Comment by DNRRomero** [comment]
Hi @v-sudkharat, so far the rest of the connectors have not shown up as connected.
I've been looking at the code to compare those that work with those that did not but have not found anything different, do you have an idea of what might be happening?

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, Any update for logs for function app?

**Comment by DNRRomero** [comment]
Hi @v-sudkharat bI saw the logs and connectivity criteria and they are all standard for all connectors, could it be that not all logs are appearing in application insights?

**Comment by v-sudkharat** [comment]
@DNRRomero, It should. Can you commit latest changes and let me know so i can review it.

**Comment by DNRRomero** [comment]
Hi @v-sudkharat  any chance we could meet? I've been trying to identify the issue but have not made much progress

**Comment by v-sudkharat** [comment]
@DNRRomero, Sure. we can connect. Meantime can I have demo credentials from your end to investigate the function app from my end. 
Please share it mail ID, so i can check on it.

**Comment by v-sudkharat** [comment]
@DNRRomero, waiting for your response.

**Comment by DNRRomero** [comment]
Hi @v-sudkharat given what we discussed today, I added some changes that should fix some of the issues we have encountered so far, any other issues that may appear are related to our internal API and should be fixed under another PR upon further investigation!

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, Thanks for adding changes. Kindly check on below few points : - 

1. Please remove the below highlighted file which is not required: -
image

2. After checking the createUI file, find out the duplicate data connector description text, please remove one of them and add same changes into zip: - 
image

3. After testing the function app, now able to see the data ingesting for 10 functions: 
image

while testing remaining of them, found that the Testing Account provided to me is does not have the required permissions to get the data: 
image

Could you please check updated connector by your Account which have the required access and data into it. And share the successfully connected screenshots with us. 

**Please update this branch from master.**  

Thanks!

**Comment by DNRRomero** [comment]
hey @v-sudkharat  I added the changes requested
also here is the screenshot with the 10 connectors

image

**Comment by v-sudkharat** [comment]
@DNRRomero, Great. Changes looks good now. Approving the PR and proceeding to Merging it. 
Please let us know if you have anything for us. Thanks!

**Comment by DNRRomero** [comment]
> @DNRRomero, waiting for your response. 

Hi @v-sudkharat hi @sukster  no comments on my side, is there anything left for the PR merge?

**Review by v-sudkharat — APPROVED** [review]
Changes looks good

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
