### PR TITLE
bug-fix-5088 - Columns not fetched from Tenable.IO

### PR DESCRIPTION
**Pull request by dnetoa**
bug-fix-5088 - Columns not fetched from Tenable.IO
   
   Change(s):
   - Fixing two columns not fetched from TenableIO APIs (bios_uuid_s and last_scan_id_s) referenced on parser
   
   Reason for Change(s):
   - Fix for issue #5088
   
   Version Updated:
   - N/A

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@dnetoa : Please fix below error.
While testing parser in our environment we are getting error.
image

**Comment by dnetoa** [comment]
I have validated on my deployment from tenable solution.

**Comment by v-spadarthi** [comment]
@dnetoa : Could you please provide us the updated sample data. Thanks!!

**Comment by NikTripathi** [comment]
@dnetoa Is there any update?

**Comment by v-atulyadav** [comment]
Hi @dnetoa , please provide sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , please provide sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , please provide sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , please provide sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , please provide sample data. Thanks.

**Comment by v-atulyadav** [comment]
We wanted to check on the status of PR #<6088>. PR is pending from more than 30 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , we still waiting for sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , we waiting for sample data. Thanks.

**Comment by v-atulyadav** [comment]
Hi @dnetoa , since we have not received response from last 7 days, we are closing your https://github.com/Azure/Azure-Sentinel/pull/6088 per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
