### PR TITLE
Workbook complete rewrite for Microsoft Sentinel Cost

### PR DESCRIPTION
**Pull request by noodlemctwoodle**
Updated Workbook and Images

Change(s):
## Version 1.6.2
- Added additional descriptions for all fields
- Added additional informational bubbles for parameters
- Added Automatic cost calculation based on [external data](https://raw.githubusercontent.com/noodlemctwoodle/SentinelPublic/main/ExternalData/AllSentinelPrices.json) store in GitHub and updated automatically by [GitHub Actions](https://github.com/noodlemctwoodle/SentinelPublic/blob/main/.github/workflows/AllSentinelPrices.yml).
- Now supports GBP, EUR, USD
- Added Basic Logs
- Added Auxiliary Logs
- Updated Commitment Tiers

Reason for Change(s):
https://github.com/Azure/Azure-Sentinel/issues/10711
   
Testing Completed:
 - Tested in multiple workspaces

Additional items such as DCR will come at a later date.

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Can you update the branch from master once.

**Comment by v-prasadboke** [comment]
Can you try to resolve the validation error. Its for files pointing to your repo. You can add them in GitHub repo

**Comment by noodlemctwoodle** [comment]
> Can you try to resolve the validation error. Its for files pointing to your repo. You can add them in GitHub repo

I have a GitHub action that keeps the prices up to date, can I add that action to this repo?

**Comment by v-prasadboke** [comment]
> > Can you try to resolve the validation error. Its for files pointing to your repo. You can add them in GitHub repo
> 
> I have a GitHub action that keeps the prices up to date, can I add that action to this repo?

Need to check this once internallu

**Comment by rahul0216** [comment]
Hi @noodlemctwoodle, this is one good feature addition to workbook. **You can add the GitHub action to repo**, but
1. Update it to store json/csv file to https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Feeds
2. Update the workbook to access AllSentinelPrices.json file form https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Feeds

Let us know if any confusion.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Please provide your feedback

**Comment by v-prasadboke** [comment]
We wanted to check on the status of PR #11003. PR is pending for more than 25 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by v-prasadboke** [comment]
Since we have not received a response in the last 7 days, we are closing your PR #11003 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 

If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Comment by noodlemctwoodle** [comment]
Apologies, been super busy, I am looking at a different way to do this rather than using a GitHub Action, I will recommit once done :)

**Pull request closed without merging**
