### PR TITLE
Garrison ULTRA Remote Logs solution

### PR DESCRIPTION
**Pull request by rdekanter**
Change(s):

- New solution for Garrison ULTRA Remote Logs

Reason for Change(s):

- New solution

Testing Completed:

- Yes

Checked that the validations are passing and have addressed any issues that are present:

- Yes

### CODE REVIEW

**Comment by rdekanter** [comment]
@microsoft-github-policy-service agree company="Garrison Technology Ltd"




Garrison Technology Limited, registered in England and Wales with registered number: 09286531. Our registered address is 117 Waterloo Road, London, SE1 8UL. Our VAT number is GB209458886

Except for the email issued by Garrison to enable access to the Garrison ULTRA Trial Service, Garrison does not conclude contracts via email. This email (including any attachments and any subsequent emails in this chain) is SUBJECT TO CONTRACT and STRICTLY CONFIDENTIAL.

This email incorporates Garrison’s email policy which can be found here<https://www.garrison.com/legal>.

**Comment by theolukensgarrison** [comment]
Hi @v-prasadboke, we haven't had a response here in a while. Could you please advise on what else we need to do to get this merged? Thanks!

**Comment by v-prasadboke** [comment]
Hello @rdekanter & @theolukensgarrison can you provide me write access to this branch. 
Also please update this branch from master. 

Need to check validation failures. 
And apologies for the delay in response

**Comment by rdekanter** [comment]
@v-prasadboke - we have updated to the main branch and you have a pending access invite.

**Comment by theolukensgarrison** [comment]
Hi @v-prasadboke, just reaching out again. What is there left for us to do here? Thanks!

**Comment by v-prasadboke** [comment]
> Hi @v-prasadboke, just reaching out again. What is there left for us to do here? Thanks!

Hello @theolukensgarrison im checking what permissions are failing or missing

**Comment by v-prasadboke** [comment]
Hello @rdekanter & @theolukensgarrison, I have some doubts about the connector. We are checking this internally if anyhow we can overcome this failure

**Pull request merged**
