### PR TITLE
Update SysmonFullDeployment.json

### PR DESCRIPTION
**Pull request by Tungsten66**
Required items, please complete
   
   Change(s):
   - Updated SysmonFullDeployment.json

   Reason for Change(s):
   - The following files no longer exist:
    	1. https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimFileEvent/ARM/vimFileEventMicrosoftSysmonCreated/vimFileEventMicrosoftSysmonCreated.json
	2. https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimFileEvent/ARM/vimFileEventMicrosoftSysmonDeleted/vimFileEventMicrosoftSysmonDeleted.json
   - A new file appears to have been created that merges the Create and Delete together and it called - https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimFileEvent/ARM/vimFileEventMicrosoftSysmon/vimFileEventMicrosoftSysmon.json

	Received this error when running - 

	{"code": "MultipleErrorsOccurred", "message": "Multiple error occurred: BadRequest,BadRequest. Please see details."}

	Inner Errors:
	{"code": "InvalidContentLink", "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimFileEvent/ARM/vimFileEventMicrosoftSysmonCreated/vimFileEventMicrosoftSysmonCreated.json'. The 	tracking Id is 'd5aa6f77-947a-4b22-b453-a54538208e8f'. Please see https://aka.ms/arm-deploy-resources for usage details."}

	Inner Errors:
	{"code": "InvalidContentLink", "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimFileEvent/ARM/vimFileEventMicrosoftSysmonDeleted/vimFileEventMicrosoftSysmonDeleted.json'. The 	tracking Id is 'd5aa6f77-947a-4b22-b453-a54538208e8f'. Please see https://aka.ms/arm-deploy-resources for usage details."}

	

   Version Updated:
   - NA

   Testing Completed:
   - Need Help, I tested by editing the template through the Deploy to Azure link and it appeared to work.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes, tested by editing the template through the Deploy to Azure link.

### CODE REVIEW

**Comment by devikamehra** [comment]
@Tungsten66 Thank you for correcting this. Can you please modify the readme as well for completeness. I don't see any other improvement that might be required in this PR.

**Comment by v-atulyadav** [comment]
Hi @Tungsten66, please act on @devikamehra's comments. Thanks

**Comment by Tungsten66** [comment]
Submitted pull request to Update README.md #8429

**Review by Tungsten66 — COMMENTED** [review]
Missed updating the name in original pull request - Update SysmonFullDeployment.json #8226

**Review by devikamehra — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
