### PR TITLE
Fixed Entity mapping on line 48

### PR DESCRIPTION
**Pull request by kapetanios55**
Changed Entity mapping on line 48 - It was populated with an empty value

   Required items, please complete
   
   Change(s):
   - Changed line 48 entity mapping from "IPCustomEntity" to "IPAddress"
   

   Reason for Change(s):
   - Template Error

   Version Updated:
   - New version 1.0.4

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @kapetanios55,
Please fix the validation errors.
Thnaks

**Comment by kapetanios55** [comment]
> Hi @kapetanios55, Please fix the validation errors. Thanks

@v-mchatla - what exactly is the validation error here? Can you please elaborate on what I need to fix?

**Comment by v-mchatla** [comment]
Hi @kapetanios55,
I didn't get a chance to check on this. Today I will check and update you the details.
Thanks

**Comment by v-mchatla** [comment]
Hi @kapetanios55,
Sorry for the delay. I have assigned with priority work, didnt get a chance to look into it. Let me check and get back to you.
Thanks

**Comment by v-mchatla** [comment]
Hi @kapetanios55,
Sorry for the delay in response. You need to remove IPCustomEntity = IPAddress this part from the extend then you can directly map the column IPAddress to the entity. Please refer #6995 test pr i have raised to check the validation failure as validation build in this PR is no more available.
Thanks

**Comment by kapetanios55** [comment]
> Hi @kapetanios55, Sorry for the delay in response. You need to remove IPCustomEntity = IPAddress this part from the extend then you can directly map the column IPAddress to the entity. Please refer #6995 test pr i have raised to check the validation failure as validation build in this PR is no more available. Thanks

@v-mchatla. What I have done here is

**Comment by kapetanios55** [comment]
Closed by mistake - Understood, I will check this gain

**Pull request closed without merging**
