### PR TITLE
Armorblox sentinel solution

### PR DESCRIPTION
**Pull request by SamhithaTatipalli**

### CODE REVIEW

**Comment by SamhithaTatipalli** [comment]
@urajat , @absanjay2022, Please find the PR for Azure Sentinel Integration.

**Comment by SamhithaTatipalli** [comment]
@v-spadarthi , Could you please provide an update on this PR?

**Comment by SamhithaTatipalli** [comment]
Hi @v-spadarthi,
 
Could you please let us know about the ETA of this PR?

Regards,
Samhitha.

**Review by v-atulyadav — COMMENTED** [review]
Hi @SamhithaTatipalli , We need to have all contents in single zip folder and not in another folder inside that zip file.

image

image

**Comment by SamhithaTatipalli** [comment]
Hi @v-atulyadav , folder was misplaced and  I made the changes now. Please let me know for other concerns.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
