### PR TITLE
Add package files for Red Canary Solution

### PR DESCRIPTION
**Pull request by rc-iwoodley**
Change(s):

Added **createUiDefinition.json** and **mainTemplate.json** files in preparation for deploying the Red Canary Solution to the Marketplace.

Version Updated:

No

Checked that the validations are passing and have addressed any issues that are present:

Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@rc-iwoodley  Please provide zip folder with latest version. thanks!!

**Comment by vmanojreddy** [comment]
@rc-iwoodley Please provide zip folder with latest version. thanks!!

**Comment by rc-iwoodley** [comment]
Update: all files updated, this is ready for review.

**Comment by vmanojreddy** [comment]
Hi @rc-iwoodley  We running arm-ttk it getting failed can please take look and fix it. Please refer below screen shot. Thanks!!!
image

**Comment by vmanojreddy** [comment]
Hi @rc-iwoodley We running arm-ttk it getting failed can please take look and fix it. thanks!!!

**Comment by rc-iwoodley** [comment]
Hello @vmanojreddy, the latest changes should address that validation failure. Thank you!

**Comment by vmanojreddy** [comment]
@rc-iwoodley  still i am seeing same issue running arm-ttk. Please take look once. thanks!!!

**Comment by v-sabiraj** [comment]
@rc-iwoodley, solution zip folder should only contain createUiDefinition and mainTemplate files, I see that some folder __MACOSX is added in that zip folder, will you please update the zip by removing that folder, thanks.
image

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
