### PR TITLE
Bosch AIShield Solution

### PR DESCRIPTION
**Pull request by udanashivm**
Fixes #

## Proposed Changes
  - Bosch AIShield connector, parser, Analytics Rule

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@aprakash13 ,please review Analytics Rules ,thanks.

**Comment by v-sabiraj** [comment]
Please fix the "timestamp_s" to "timestamp_t" for parser, thanks.

**Comment by udanashivm** [comment]
> Please fix the "timestamp_s" to "timestamp_t" for parser, thanks.

Done

**Comment by v-sabiraj** [comment]
@aprakash13 ,please review Analytics Rules ,thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13 , please review and approve Analytic Rules.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
It seems that the current template has a couple of additional fields that are not normally used. 
Can you please follow the example analytical rule here to create your analytics template:
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/FailedLogonToAzurePortal.yaml

More guidance:
https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide

**Comment by udanashivm** [comment]
> It seems that the current template has a couple of additional fields that are not normally used. Can you please follow the example analytical rule here to create your analytics template: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/FailedLogonToAzurePortal.yaml
> 
> More guidance: https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide

@aprakash13, Done. Thanks!

**Comment by v-sabiraj** [comment]
Please add schema for data connector, thanks.

**Comment by udanashivm** [comment]
> Please add schema for data connector, thanks.

@v-sabiraj , I have already added metadata details in data connector file. Please let me know if anything missing. Thanks!

**Comment by v-sabiraj** [comment]
@aprakash13 , please review and approve requested changes, thanks.

**Review by v-sabiraj — APPROVED** [review]

**Comment by v-sabiraj** [comment]
Data Connectors looks good.

**Review by aprakash13 — COMMENTED** [review]
Looks good from a query perspective. Please feel free to approve/merge if other components look good.

**Pull request merged**
