### PR TITLE
Threat Intelligence template spec solution

### PR DESCRIPTION
**Pull request by v-sabiraj**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@v-mchatla, can you please review this,thanks.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
I have reviewed the PR. Changes are good except 2 Analytic Rules and 1 Hunting Query. For these rules are failing with some errors. 
1. (Preview) TI map Domain entity to Web Session Events (ASIM Web Session schema)
2. TI map IP entity to AzureFirewall
3. Preview - TI map File entity to WireData Event
Please let me know if you are able to test it end to end.
Thanks

**Comment by v-sabiraj** [comment]
@v-mchatla, the solution is already live we are adding it in GitHub in solutions, thanks.

**Comment by v-mchatla** [comment]
> @v-mchatla, the solution is already live we are adding it in GitHub in solutions, thanks.

Understand, but we need to make sure everything is working right. Just check if it is not working for you then will try to fix it. And also add skip validations.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Can you please accommodate the requested changes and let me know so that I can review and merge it.
Thanks

**Comment by v-sabiraj** [comment]
Hey @v-mchatla, Azure diagnostics data is not there in workspace, I'll test the queries soon and let you know, thanks.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
Can you please provide update once you are done with testing.
Thanks

**Comment by v-sabiraj** [comment]
Hi team, waiting for customer to response. Thanks.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
Sure, please keep us posted once we got confirmation from the author

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
Do we have any update on this.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
Can you please provide update on this.
Thanks

**Comment by v-sabiraj** [comment]
@v-mchatla, please review and merge this, thanks.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
I have verified the skip validations and they look good.
Please fix analytic rule and hunting queries mentioned earlier and also create short link for the below Analytic Rule.

image
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,
Please resolve the conflicts, so that I can merge.
Thanks

**Review by v-mchatla — APPROVED** [review]
As per your latest update we are able to test the queries in a different workspace and that should be fine.
Please add valid screenshots and comments for the queries.
Thanks

**Comment by v-sabiraj** [comment]
Hi @v-mchatla, as discussed with you we don't have Wire Data table in our workspace, I checked with a guy from Threat Intelligence, according to that we need to first setup wire data table in workspace and then after that it work.

**Comment by v-dvedak** [comment]
Merged since Meena has approved the PR

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
