### PR TITLE
Cybersixgill Actionable Alerts offerid update

### PR DESCRIPTION
**Pull request by loginsoft-integrations**
Change(s):
   - Offer ID update for existing solution

   Reason for Change(s):
   - Initial ID was too long, couldn't create offer in Partner Center with that ID

   Version Updated:
   - NA

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @loginsoft-integrations , please change the version to 2.0.1 in Solution_Cybersixgill_Actionable_Alerts.json too.

**Comment by syed-loginsoft** [comment]
Are you referring to file this `Tools\Create-Azure-Sentinel-Solution\V2\input\Solution_Cybersixgill_Actionable_Alerts.json`

I was asked not commit this file. Can you please confirm ?

**Comment by v-rbajaj** [comment]
The file is correct but the path is wrong. This is the correct path `Solutions\Cybersixgill-Actionable-Alerts\Data\Solution_Cybersixgill_Actionable_Alerts.json`

**Comment by loginsoft-integrations** [comment]
Done.

**Review by v-rbajaj — APPROVED** [review]

**Pull request merged**
