### PR TITLE
Adding Mandiant Advantage Threat Intelligence Solution

### PR DESCRIPTION
**Pull request by chrishultin**
Required items, please complete
   
   Change(s):
   - Initial commit for adding Mandiant Advantage Threat Intelligence solution

   Reason for Change(s):
   - Adding Mandiant Advantage Threat Intelligence solution

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@chrishultin : While checking Logo we are getting below error please check and fix it.
image
Ensure raw file of logo does not have any of the following:
1.cls and style formats
2.embedded png formats
3.data-name

**Comment by v-spadarthi** [comment]
@manishkumar1991 :Please review the playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
Logo is good validation passed
image
Once playbook reviewed and approved from @manishkumar1991 we can be good to merge.
@chrishultin: Seems some issue with Contributor License Agreement acceptance, please try to sign [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/Azure-Sentinel?pullRequest=5593) again to accept your contribution.

**Comment by v-mchatla** [comment]
Hi @manishkumar1991 
Can you please review the playbooks and provide your feedback.
thanks

**Comment by v-sabiraj** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin, can you please check on feedback from Manish?
Also please sign in license/cla, thanks.

**Comment by v-spadarthi** [comment]
@chrishultin : We wanted to check on the status of [PR](https://github.com/Azure/Azure-Sentinel/pull/6245) . PR is pending from more than 60 days. Let us know if any assistance is required for this PR. As Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by chrishultin** [comment]
Apologies for the delay.  I've been waiting for my company to approve my signing of the CLA before proceeding.

**Comment by v-spadarthi** [comment]
@chrishultin : we are waiting for the update from author.

**Comment by v-spadarthi** [comment]
@chrishultin : we are waiting for the update from author.

**Comment by v-spadarthi** [comment]
@chrishultin : we are waiting for the update from author.

**Comment by v-spadarthi** [comment]
@chrishultin : we are waiting for the update from author.

**Comment by v-spadarthi** [comment]
@chrishultin : we are waiting for the update from author.

**Comment by v-mchatla** [comment]
> Apologies for the delay. I've been waiting for my company to approve my signing of the CLA before proceeding.

Hi @chrishultin,
Can you please check and provide an update.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrishultin,
Can you please check and provide an update.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrishultin,
Can you please check and provide an update.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrishultin,
Can you please check and provide an update.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrishultin,
Can you please check and provide an update.
Thanks

**Comment by v-mchatla** [comment]
@chrishultin : We wanted to check on the status of https://github.com/Azure/Azure-Sentinel/pull/6245 . PR is pending from more than 60 days. Let us know if any assistance is required for this PR. As Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-spadarthi** [comment]
@chrishultin : We are waiting for the update from author.

**Comment by v-spadarthi** [comment]
@chrishultin : We are waiting for the update from author.

**Comment by v-dvedak** [comment]
Hi @chrishultin, Since we have not received response from last 7 days, we are closing your PR per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
