### PR TITLE
Ingest-CanaryTokens: update CanaryToken API usage, Remove duplicate GeoIP, resourceTags and location as parameters, docs

### PR DESCRIPTION
**Pull request by juju4**
Change(s):
   - update Ingest-CanaryTokens as not currently usable as is

   Reason for Change(s):
   - update CanaryToken API usage
   - Remove duplicate GeoIP
   - resourceTags and location as parameters
   - docs
   - add ARM template metadata

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @juju4 Thanks for raising this PR. Please repackage the solution with V3 tool. Also please resolve failed validations. 
Thanks.

**Comment by juju4** [comment]
Are you referring to https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3?

Just to be clear, I'm not the creator of the playbook.
I tested it, found a few issues and a bit of extra features that I'm pushing here.
Also, it likely overlaps https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/HoneyTokens but done in different way (aka Thinkst Canary tool based)

Sorry, but reasons for failed validations are unclear to me
```
1 files changed in current PR after filter. File Type Filter: azuredeploy.json, File path Filter: Playbooks,Solutions, File Kind Filter: Modified
Playbooks validation failed. File path: Playbooks/Ingest-CanaryTokens/azuredeploy.json. Error message: Invalid Schema. Validation errors: instance.resources[0] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[0].tags is not of a type(s) object. Description: Name-value pairs to add to the resource, instance.resources[1] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[1].tags is not of a type(s) object. Description: Name-value pairs to add to the resource

```
= schema is valid as I'm using it with Sentinel Repository CI/CD feature and deployment is functional including tags

**Comment by v-prasadboke** [comment]
Sorry @juju4, I'll take a loot at the Playbook. I thought this Playbook is from a solution but this is a standalone Playbook. 
No need to repackage it. 
I'll update you about the same before 11 October, 2023.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @juju4 can you please update the branch from master, I'm unable to go through the Validation errors.

**Comment by v-prasadboke** [comment]
Hello @juju4 please update the branch from master

**Comment by juju4** [comment]
merge master done

**Comment by v-prasadboke** [comment]
Hello @juju4, Sorry for the late reply but can you please resolve the validation errors. 
You can refer this playbook for more clarification.

**Comment by v-prasadboke** [comment]
Hello @juju4, Please resolve validation errors. 
Thanks.

**Comment by juju4** [comment]
Sorry, but I'm unclear on what to fix
```
1 files changed in current PR after filter. File Type Filter: azuredeploy.json, File path Filter: Playbooks,Solutions, File Kind Filter: Modified
Playbooks validation failed. File path: Playbooks/Ingest-CanaryTokens/azuredeploy.json. Error message: Invalid Schema. Validation errors: instance.resources[0] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[0].tags is not of a type(s) object. Description: Name-value pairs to add to the resource, instance.resources[1] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[1].tags is not of a type(s) object. Description: Name-value pairs to add to the resource
```
resource.tags is passed as parameter and is an array/object.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ThreatXCloud/Playbooks/ThreatXPlaybooks/ThreatX-Enrichment/azuredeploy.json#L584 only has fixed non-parameterized tags
used in other playbook https://github.com/search?q=repo%3AAzure%2FAzure-Sentinel%20parameters%20resourceTags&type=code
if better way to pass it, please say how.

As a reminder, playbook is deployed in my prod environment with sentinel repository feature and works.

**Comment by v-prasadboke** [comment]
Hello @juju4 sorry for the inconvenience we are still trying to find out why the validation check is failing for.

**Comment by v-prasadboke** [comment]
Hello @juju4 this is still under investigation, We will update you before 31 October, 2023. 
Thanks.

**Comment by v-prasadboke** [comment]
Hello @juju4, Playbook's schema is incorrect. I'm trying to correct the playbook schema

**Comment by v-prasadboke** [comment]
Hello @juju4 we are still trying to get the reason behind failed validation error, We will provide you some update before 08 November, 2023.

**Comment by v-prasadboke** [comment]
Hello @edx-sayed-salman, Sorry for the inconvenience but due to lack of availability I was unable to test the PR.
I'll review this PR and Will respond you back by 15 November, 2023.
Thanks and sorry for the delay in review.

**Comment by v-prasadboke** [comment]
Hello @juju4, This PR is still under discussion within the team. We will update you shortly about this. Also if possible can you please try to resolve the validation error.

**Comment by juju4** [comment]
> Hello @juju4, This PR is still under discussion within the team. We will update you shortly about this. Also if possible can you please try to resolve the validation error.

This is still the same than https://github.com/Azure/Azure-Sentinel/pull/9130#issuecomment-1773889477

and unclear to me why an error
```
1 files changed in current PR after filter. File Type Filter: azuredeploy.json, File path Filter: Playbooks,Solutions, File Kind Filter: Modified
Playbooks validation failed. File path: Playbooks/Ingest-CanaryTokens/azuredeploy.json. Error message: Invalid Schema. Validation errors: instance.resources[0] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[0].tags is not of a type(s) object. Description: Name-value pairs to add to the resource, instance.resources[1] does not match allOf schema [subschema 1] with 1 error[s]:, instance.resources[1].tags is not of a type(s) object. Description: Name-value pairs to add to the resource
```

**Comment by v-prasadboke** [comment]
Sorry @juju4 But Its a bit complicated for me and I'm trying to find the issue which is causing the Validation failure. I even gone through various playbook which has somewhat same reference but still cant get it.

**Comment by v-prasadboke** [comment]
Hello @juju4, Can we connect for this Validation failure. 
I work in IST time zone and my mail id is v-prasadboke@microsoft.com
Please let me know your time zone and availability so that we can schedule a call for the same.

**Comment by v-prasadboke** [comment]
Hello Julien, Please let me know If we can schedule a call. 
Thanks.

**Comment by v-prasadboke** [comment]
Hi Julien please let us know if we can schedule a call. 
You can reach out to me on teams and mail at v-prasadboke@microsoft.com

**Comment by v-prasadboke** [comment]
Still can we connect.

**Comment by v-prasadboke** [comment]
Hello @juju4 we can discuss the validation error over a call

**Comment by v-prasadboke** [comment]
Sorry @juju4 didnt got time to check mails. Can you add Rob in this PR.

**Comment by v-prasadboke** [comment]
Hello @juju4, I've resolved the validation error. Can you please take a look at it.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
