### PR TITLE
Azure activity package update

### PR DESCRIPTION
**Pull request by v-prasadboke**
Change(s):
   - Update Data Connector  AzureActivity.json

   Reason for Change(s):
   - Change in schema in AzureActivity.json

   Version Updated:
   - 2.0.2
   - Resolved PR #7216 

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Do not merge 
Still working on this one

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, have you completed work with this PR?

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, have you completed work with this PR?

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, please respond on above.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
