### PR TITLE
Add PostDeployment fields to metadata

### PR DESCRIPTION
**Pull request by lior-tamir**
This PR relevant to Playbook Templates Tab

## Proposed Changes

  - For playbooks which have instructions after deployment, move these instructions from "prerequisites" to "postDeployment".
  - Delete duplicate screenshot and rename to dark/light screenshots in IdentityProtectionTeamsBotResponse playbook
  -

### CODE REVIEW

**Comment by NikTripathi** [comment]
@anki-narravula Can you please check and approve?

**Comment by anki-narravula** [comment]
HI @lior-tamir  - Looks like this is very old PR. I am not sure you still want to merge these changes. If we need to merge, there are couple of conflicts that need to be resolved. Can you please take care. Thank you.

**Comment by v-sabiraj** [comment]
Hey @lior-tamir , will you please resolve the conflicts, thanks.

**Comment by vmanojreddy** [comment]
Hey @lior-tamir , will you please resolve the conflicts, thanks.

**Comment by vmanojreddy** [comment]
Hey @lior-tamir , will you please resolve the conflicts, thanks.

**Comment by vmanojreddy** [comment]
Hey @lior-tamir, We wanted to check on the status of this PR [Add PostDeployment fields to metadata #3155](https://github.com/Azure/Azure-Sentinel/pull/3155). It is pending from more than 60 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by vmanojreddy** [comment]
Hi @lior-tamir  Since we have not received response from last 7 days, we are closing your PR [Add PostDeployment fields to metadata #3155](https://github.com/Azure/Azure-Sentinel/pull/3155) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
