### PR TITLE
Update file for deployment using PowerShell - AlertIQ

### PR DESCRIPTION
**Pull request by hvanh2122**
Change(s):
- Updated file connectors.json
- Updated file SentinelallInOne.ps1

Reason for Change(s):
- Add more connectors and change to the new API

Version Updated:
- Yes

Testing Completed:
- Yes 
result1
result2

Checked that the validations are passing and have addressed any issues that are present:
- Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
We are checking with Ruchir for this PR

**Comment by v-spadarthi** [comment]
Waiting for the update from Ruchir

**Comment by v-spadarthi** [comment]
Waiting for the update from Ruchir

**Comment by rushriva** [comment]
> Waiting for the update from Ruchir



> Waiting for the update from Ruchir

@hvanh2122  - Please provide PR details in following format - 

 Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below


# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)


-----------------------------------------------------------------------------------------------------------

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please address the @rushriva comments

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please address the @rushriva comments

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please address the @rushriva comments

**Comment by hvanh2122** [comment]
I changed the PR details as requested by @rushriva. Please check. Thank you

**Comment by rushriva** [comment]
@hvanh2122  - Please provide more details around this change, why this change was needed? Can you also provide test screenshots for this change.

**Comment by v-spadarthi** [comment]
@hvanh2122: Please provide more details around this change, why this change was needed? Can you also provide test screenshots for this change as requested by @rushriva

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please provide more details on this PR to understand as requested by @rushriva

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please provide more details on this PR to understand as requested by @rushriva

**Comment by v-spadarthi** [comment]
@hvanh2122 : Please provide more details on this PR to understand as requested by @rushriva

**Comment by hvanh2122** [comment]
I changed the PR details as requested by @rushriva. Please check. Thank you

**Comment by v-spadarthi** [comment]
@rushriva : Author addressed as requested by you please check and provide your feedback. Thanks!

**Comment by v-mchatla** [comment]
> I changed the PR details as requested by @rushriva. Please check. Thank you

Hi @rushriva,
Can you please review the changes again and provide your feedback
Thanks

**Comment by v-spadarthi** [comment]
Hi @rushriva,
Can you please review the changes again and provide your feedback
Thanks

**Comment by v-spadarthi** [comment]
Hi @rushriva,
Can you please review the changes again and provide your feedback
Thanks

**Comment by v-spadarthi** [comment]
Hi @rushriva/ @rahul0216,
Can you please review the changes again and provide your feedback
Thanks

**Comment by javiersoriano** [comment]
looks good to me @anki-narravula

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
