### PR TITLE
Created Microsoft PowerBI Activity Workbook 

### PR DESCRIPTION
**Pull request by samikroy**
Created Microsoft PowerBI Activity Workbook 
   
  This workbook contains
Overview
Activity Over Time
Events Occured
Workspace Used
Report Accessed
Dataset Accessed
Activity by DistributionMethod
Activity through UserAgent
Datasets
Dataset Directly Accessed
Activity Directly on Datastes
Direct Datasets Activities
Reports
Activities Across Reports
IP and User Activity Trend
IP Address Activity Trend
User Activity Trend
User Activity Across IP Addresses

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@samikroy, please add metadata in this file (https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json)

**Comment by v-sabiraj** [comment]
@samikroy, there are few conflicts in the branch can you please check and resolve, thanks.

**Comment by v-sabiraj** [comment]
@samikroy also I think this file (Solutions/Microsoft PowerBI/Workbooks/Images/Preview/readme.txt) is added by mistake, please check and remove. Thanks.

**Comment by samikroy** [comment]
@v-sabiraj - Have updated as requested. Could you please have a look.
Thank you.

**Comment by samikroy** [comment]
@v-sabiraj - Could you please share for any changes or approve this PR.
Thank you.

**Review by v-sabiraj — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Comment by samikroy** [comment]
Thanks a lot @v-sabiraj & @v-dvedak for the approval & merge.

**Pull request merged**
