### PR TITLE
VMware SD-WAN and SASE Solution v1.0.0

### PR DESCRIPTION
**Pull request by stlaszlo**
Change(s):
   - Added new solution: VMware SD-WAN and SASE (v1.0.0)
   - Included Function App for VMware Edge Cloud Orchestrator API integration
   - Included Analytics Rules for VMware SD-WAN and SASE
   - Included Hunting Queries for VMware SD-WAN and SASE
   - Included Workbook for VMware SD-WAN and SASE

   Reason for Change(s):
   - New Solution Added

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by stlaszlo** [comment]
@microsoft-github-policy-service agree company="VMware Inc"

**Comment by v-prasadboke** [comment]
Hello @stlaszlo, Input file and SolutionMetadata file are missing from the Solution folder. Can you please add those. 
These files are required for Solution repackaging. 
You can refer to this Solution for more info. https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Armorblox

Input file is present in **Data** folder

**Comment by v-prasadboke** [comment]
Hello @stlaszlo, Please go on with the above requested changes.

**Comment by stlaszlo** [comment]
@v-prasadboke ack, work in progress.

**Comment by v-prasadboke** [comment]
Hello @stlaszlo Thanks for letting me know. Update me once when it's done. 
You can ping me on teams at v-prasadboke@microsoft.com

**Comment by stlaszlo** [comment]
@v-prasadboke I've committed the changes, sorry for the delayed update, but the company killed off MS Teams last week :)

**Comment by v-prasadboke** [comment]
> @v-prasadboke I've committed the changes, sorry for the delayed update, but the company killed off MS Teams last week :)

Thanks for the updates @stlaszlo, I'll take a look at this changes and let you know before 21 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @stlaszlo, can you please resolve the Code QL errors. 
Thanks.

**Comment by v-prasadboke** [comment]
Hello @stlaszlo, Can you please provide write/push access to this Branch. 
You can do that by heading over to repo's setting and select collaboration from the left blades and invite me as an collaborator. 
Thanks.

**Comment by stlaszlo** [comment]
@v-prasadboke collaborator invite is out, many thanks for flagging this. I will also check the CodeQL errors and fix them.

**Comment by v-prasadboke** [comment]
Hello @stlaszlo, Solution is missing with data connector. It has azure deploy  file can you please add data connector to it. 
Also folder structure inside the zip is missing with python libraries please add it as well. 

you can refer to this solutions data connector for more clarification  https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AtlassianJiraAudit/Data%20Connectors

**Comment by stlaszlo** [comment]
Ack, I'll check and fix, thanks.

**Comment by v-prasadboke** [comment]
Hello  @stlaszlo, Any updates on the above mentioned comments,.

**Pull request closed without merging**
