### PR TITLE
Entity trigger playbooks

### PR DESCRIPTION
**Pull request by anki-narravula**
Required items, please complete

- Added new entity trigger playbooks
   
   Change(s):
   - Added new playbooks (Entity trigger)

   Reason for Change(s):
   - Added new playbooks (Entity trigger)

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by lior-tamir** [comment]
1. Can we remove the "(private preview)" from the trigger name? Both in the code and in the screenshots.
2. MDE - Isolate machine is a copy of get investigation package - missing the new playbook
3. Workflow resource -> Metadata: Wherever there are not prerequisites, please remove this field (no need to write prerequisites: "none")

**Review by rahul0216 — DISMISSED** [review]
Azure Firewall Playbooks and images look good.

**Comment by v-sabiraj** [comment]
@rahul0216, can you please check and confirm if we can merge this? thanks.

**Comment by v-sabiraj** [comment]
@rahul0216, please confirm if we can merge this? thanks.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
