### PR TITLE
Create MicrosoftSentinelCost(GBP).json

### PR DESCRIPTION
**Pull request by noodlemctwoodle**
## Microsoft Sentinel Cost Summary (GBP)

 Change(s):

- Submitted workbook with Cost in GBP (£)
- Updated Breakdown of billable ingestion by log category to expand all tables. This removes bundling of unknown tables to be set as "Other"

Reason for Change(s):

- There is no Workbook out of the box for costs in GBP (£)
- Tables of Other can be difficult to identify what logs you are actually paying for

### OLD
image

### NEW
image

Version Updated:

- Cloned AzureSentinelCost.json which is in USD ($)

Testing Completed:

- Tested in multiple workspaces and confirmed working

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@noodlemctwoodle : Please add workbook meta data in below path
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json
After deploying the workbook we could see below looking good
image
If you add any preview images please add and once you add the workbook metadata, we will be good to merge.

**Comment by v-spadarthi** [comment]
@noodlemctwoodle : Please resolve the above comments.

**Comment by noodlemctwoodle** [comment]
I'll do it today

**Comment by noodlemctwoodle** [comment]
@v-spadarthi Pushed changes with updated meta and images.

**Comment by v-spadarthi** [comment]
@noodlemctwoodle : Please resolve the conflicts. Thanks!

**Review by v-spadarthi — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]
Approving as reviewed by Suresh

**Pull request merged**
