### PR TITLE
PRAAS Sentinel Solution

### PR DESCRIPTION
**Pull request by ToroNZ**
Required items, please complete

Change(s):

    Added the initial version for PRAAS product solution

Reason for Change(s):

    New solution

Version Updated:

    Initial Version

Testing Completed:

    Done

Checked that the validations are passing and have addressed any issues that are present:

    Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @ToroNZ, Repackage this solution with version 2.0.0 using this tool https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2.

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, Thanks for making those changes. Please add `Solutions/PRAAS/Data/Solution_PRAAS.json` file

**Comment by v-rbajaj** [comment]
> > Hi @ToroNZ, Thanks for making those changes. Please add `Solutions/PRAAS/Data/Solution_PRAAS.json` file
> 
> This has been done. Cheers

Hi @ToroNZ, the create ui seems to be broken, please fix this in create UI, Solution_PRAAS and in the package zip. Thanks
image

**Comment by v-rbajaj** [comment]
@ToroNZ, can you please provide some update on this?

> > > Hi @ToroNZ, Thanks for making those changes. Please add `Solutions/PRAAS/Data/Solution_PRAAS.json` file
> > 
> > 
> > This has been done. Cheers
> 
> Hi @ToroNZ, the create ui seems to be broken, please fix this in create UI, Solution_PRAAS and in the package zip. Thanks image

**Comment by v-rbajaj** [comment]
@ToroNZ, 
please provide some update on this PR.

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, we don't need to have another version of the solution, please remove the new 2.0.1.

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, I can still see 2.0.1 zip. 
Anyway, as per new guidelines we need to package the solution with version 3.0.0, please go through the readme file
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3

Please incorporate all the required changes in 3.0.0 zip and remove 2.0.0 and 2.0.1 zip.

Also do add release notes, please follow this link -https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, can you please make requested changes from the above comment?

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, can you please act on above comment?

**Comment by v-rbajaj** [comment]
Thanks @ToroNZ

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, thanks for making these changes, we will provide an update by 3 Aug 2023

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, the main template deployment is failing. We are looking into it. 

Apart from that, we would want to know which type of Data connector are you trying to build with this solution?

**Comment by v-rbajaj** [comment]
> Hi @ToroNZ, the main template deployment is failing. We are looking into it.
> 
> Apart from that, we would want to know which type of Data connector are you trying to build with this solution?

Hi @ToroNZ, we think that you are trying to build a function app type data connector. 
Please add the missing files in data connector folder according to these files
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Bitglass/Data%20Connectors

For example: the zip file, azuredeploy file, host file, requirements etc are missing, please add them.

Then package the solution using this tool https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3
Please go through the readme.md file and follow the instructions mentioned there.

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, can you please look into the above comment and provide some update on this PR?

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, can you please look into the above comment and provide some update on this PR?

**Comment by v-rbajaj** [comment]
Hi @ToroNZ, can you please provide some update on this PR?

**Comment by v-rbajaj** [comment]
Hi @ToroNZ,
We wanted to check on the status of PR #8277. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

**Comment by v-rbajaj** [comment]
Hi @ToroNZ Since we have not received a response in the last 7 days, we are closing your PR #8277 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 

If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
