### PR TITLE
Azurekid/multiple data sources/updated techniques

### PR DESCRIPTION
**Pull request by azurekid**
Required items, please complete
   
   Change(s):
   - added missing mitre techniques

   Reason for Change(s):
   - missing mitre techniques

   Version Updated:
   - Yes

   Testing Completed:
   - Yes, using Pester

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by aprakash13 — APPROVED** [review]
Thanks @azurekid

**Comment by azurekid** [comment]
@aprakash13 I noticed a merge conflict and fixed this
As a result, I needed to update the version number of some detections to pass the test.

**Review by aprakash13 — APPROVED** [review]

**Comment by v-sabiraj** [comment]
@azurekid, there are some data connectors removed /deleted, is there any reason for that? as it is affecting the solutions.

**Comment by azurekid** [comment]
> @azurekid, there are some data connectors removed /deleted, is there any reason for that? as it is affecting the solutions.

Hi and thanks for looking in to this.
I didn't add the removal of data connectors in my Pull Request when looking at my initial branch and commits.

I think these are removed on a merge origin/master but where not part of my updates.

**Comment by v-sabiraj** [comment]
@azurekid , will you please raise a pr for the changes that were not needed and got committed in this?

**Comment by azurekid** [comment]
> @azurekid , will you please raise a pr for the changes that were not needed and got committed in this?

Hi, I just did, but also noticed that @aprakash13 has reverted all changes.
How would you like me to proceed? I had all ready created a PR that was reverting the deleted files #5508

**Pull request merged**
