### PR TITLE
Fix for #3669

### PR DESCRIPTION
**Pull request by samikroy**
Fix for #3669 and addition of AADNonInteractiveUserSignInLogs to the query.

### CODE REVIEW

**Comment by samikroy** [comment]
@javiersoriano - please review here.

**Comment by javiersoriano** [comment]
@shainw @petebryan please check if this the new logic is correct

**Comment by shainw** [comment]
@javiersoriano - I don't think we want to include non-interactive signins in Azure.  The AWS login is interactive to the "console".

**Comment by samikroy** [comment]
> @javiersoriano - I don't think we want to include non-interactive signins in Azure. The AWS login is interactive to the "console".

@shainw & @javiersoriano - Updated the query as per the suggestion & review comments.
Thank you.

**Review by shainw — APPROVED** [review]

**Pull request merged**
