### PR TITLE
🐛 Fix invalid YAML

### PR DESCRIPTION
**Pull request by pemontto**
Required items, please complete
   
   Change(s):
   - Remove trailing tabs `\t`

   Reason for Change(s):
   - Fix analytics with invalid YAML that cause parsers to barf

   Version Updated: ✅

   Testing Completed: ✅

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @pemontto,
Could you please repackage these solutions. You can check below link for your reference. Thanks
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by pemontto** [comment]
@v-atulyadav repackaged based on docs provided 👍

**Comment by v-atulyadav** [comment]
Hi @pemontto,
Veritas is a partner solution, and in this solution metadata file, it shows Microsoft support, so we need to modify this file accordingly. Thanks

**Comment by v-atulyadav** [comment]
Hi @pemontto,
Moving this into draft until further update. Thanks

**Comment by pemontto** [comment]
@v-atulyadav, this is the same metadata file from 6 months ago. What should it be changed to? I don't work for Veritas, but these rules are breaking CI/CD pipelines.

`Solutions/Veritas NetBackup/Data/Solution_NetBackup.json`
```json
{
	"Name": "Veritas NetBackup",
	"Author": "Microsoft - support@microsoft.com",
	"Logo": "<img src=\"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Logos/Azure_Sentinel.svg\" width=\"75px\" height=\"75px\">",
	"Description": "The [Veritas](https://www.veritas.com/) solution for Microsoft Sentinel allows you to analyze NetBackup audit events. The solution uses analytics rules to automatically generate incidents when an abnormal user activity is detected in NetBackup.",
	"Analytic Rules": [
		"Analytic Rules/NetBackup_many_Anomalies.yaml",
		"Analytic Rules/NetBackup_many_login_fail.yaml"
		],
	"Metadata": "SolutionMetadata.json",
	"BasePath": "C:\\GitHub\\Azure-Sentinel\\Solutions\\Veritas NetBackup",
	"Version": "3.0.0",
	"TemplateSpec": true,
	"Is1PConnector": false
}
```

**Comment by v-atulyadav** [comment]
Hi @pemontto,
The original author has raised a PR for changes, and we will incorporate your changes into that PR. Thanks

**Comment by v-atulyadav** [comment]
Hi @pemontto,
We have raised a new PR #10837 for Spycloud solution changes mentioned in this PR, requesting you to uncommit these changes from this PR. Thanks

**Comment by v-atulyadav** [comment]
Hi @pemontto,
We have raised a new PR #10852 for Veritas solution changes mentioned in this PR. 
This request is being closed because your two solutions changes have been implemented. Thanks

**Pull request closed without merging**
