### PR TITLE
03242023  as remove domains from zscaler url category

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - New playbook

   Reason for Change(s):
   - New playbook

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @manishkumar1991 @rahul0216,
Please provide your feedback on this
Thanks

**Comment by manishkumar1991** [comment]
We are looking into this

**Comment by v-atulyadav** [comment]
Hi @manishkumar1991, thanks for your acknowledgement.

**Review by manishkumar1991 — APPROVED** [review]
Approved, Playbooks looks fine.

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
