### PR TITLE
Users/gaemslie/8504

### LINKED ISSUE #8504: Dynatrace data connectors paging not working as expected
**Describe the bug**
Dynatrace solution data connector paging does not seem to be working. Only the first page of events is ingested. 

**To Reproduce**
1. Connect Dynatrace Runtime Vulnerabilities connector to a Dynatrace tenant with more than 10 reported vulnerabilities.
2. Wait till data ingested
3. query data and confirm only 10 events were ingested.

**Expected behavior**
Page correctly and ingest all available events returned by rest API

** More details **
Current polling config

image

initial rest request looks like this

> api/v2/securityProblems?fields=+riskAssessment&pageSize=10&from=now-5m&to=now

but must look like this for second page

> api/v2/securityProblems?nextPageKey=vu8XQiDj3q0SIU59....

currently testing this polling config

image

this is the raw rest response from same rest endpoint

image

LAWS only has 11 items since connected

image

### PR DESCRIPTION
**Pull request by keyoke**
Applies connector updates to resolve #8504, to enable paging behaviour changes implemented by Microsoft Team

### CODE REVIEW

**Comment by v-sudkharat** [comment]
Hi @keyoke, thank you for raising Pull Request with us! You should expect an initial response to your Pull Request from the team within 2 business days. Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, could you please have a look at below comment. Thanks!
https://github.com/Azure/Azure-Sentinel/issues/8504#issuecomment-1748172604

**Comment by v-sudkharat** [comment]
Hi @keyoke, hope you are doing well, just want to know should we start to review this PR if no, could you please mark it as Draft PR. Thanks!

**Comment by keyoke** [comment]
@v-sudkharat please review this issue is again resolved on the Microsoft side

**Comment by v-sudkharat** [comment]
Hi @keyoke, thanks for clarify. 
As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using "V3 tool". and add "Release Notes" for solution.
Please read this readme file for instructions on using the "V3 tool" and while creating "Release Notes".

V3 Tool Link: - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md
Release Notes Link: - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, thanks for clarify. As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using "V3 tool". and add "Release Notes" for solution. Please read this readme file for instructions on using the "V3 tool" and while creating "Release Notes".
> 
> V3 Tool Link: - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md Release Notes Link: - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md
> 
> Thanks!

hi @v-sudkharat  I have done as requested. please review

**Comment by v-sudkharat** [comment]
Hi @keyoke, thank you for accommodating the suggested changes! We will review the Pull Request and get back to you by - 
20-10-2023.
Meanwhile, please can you add the successfully running/connected screenshot of "Data Connector."
Thanks!

**Comment by v-sudkharat** [comment]
@keyoke, Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, could you please add the `ReleaseNotes` reference in `createUiDefinition.json` file and also add some detailed description in below highlighted screenshot.
Sharing the createUiDefinition.json` file in the chat for add ReleaseNotes reference. -[createUiDefinition.zip](https://github.com/Azure/Azure-Sentinel/files/13042549/createUiDefinition.zip)
image


I see you added the `ReleaseNotes` reference in Workbook description, please remove it. 
image

We are working on review the other content of solution, meanwhile, we don't have the live environment, so, please share the screenshot of all working playbooks and Data Connectors.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, please have a look at above comment. Thanks!

**Comment by keyoke** [comment]
> createUiDefinition.zip

hello @v-sudkharat  I have made the required changes

**Comment by v-sudkharat** [comment]
Hi @keyoke, thanks for committing the changes. I can see you added the release notes reference in different path -
image

Please refer below screenshot to adding the ReleaseNote reference. - 
image

we don't have the live environment, so, please share the screenshot of all working playbooks. Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, thanks for committing the changes. I can see you added the release notes reference in different path - image
> 
> Please refer below screenshot to adding the ReleaseNote reference. - image
> 
> we don't have the live environment, so, please share the screenshot of all working playbooks. Thanks!

ok I have moved this line

image

image

**Comment by v-sudkharat** [comment]
@keyoke, if you don't required, can you please remove the zip which highlighted in Red. 
And also revert the change for highlighted in "Yellow". 

image

**Comment by keyoke** [comment]
> @keyoke, if you don't required, can you please remove the zip which highlighted in Red. And also revert the change for highlighted in "Yellow".
> 
> image

done

**Comment by v-sudkharat** [comment]
Hi @keyoke, we are facing some issue, while testing the content. Please update the sample data for below tables: -

```
DynatraceAttacks_CL.json
DynatraceProblems_CL.json 
DynatraceAuditLogs_CL.json
DynatraceSecurityProblems_CL.json 
```
Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, we are facing some issue, while testing the content. Please update the sample data for below tables: -
> 
> ```
> DynatraceAttacks_CL.json
> DynatraceProblems_CL.json 
> DynatraceAuditLogs_CL.json
> DynatraceSecurityProblems_CL.json 
> ```
> 
> Thanks!

Hi @v-sudkharat,
What exactly is the issue?
Thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, we are unable to save the Parser - 
image

**Comment by keyoke** [comment]
> Hi @keyoke, we are unable to save the Parser - image

against actual data works fine
image

image

image

image

**Comment by v-sudkharat** [comment]
@keyoke, we updated the `createUiDefinition.json` for Release Notes, please update below shared file with existing one. Thanks!
[createUiDefinition.zip](https://github.com/Azure/Azure-Sentinel/files/13163813/createUiDefinition.zip)

**Comment by keyoke** [comment]
> @keyoke, we updated the `createUiDefinition.json` for Release Notes, please update below shared file with existing one. Thanks! [createUiDefinition.zip](https://github.com/Azure/Azure-Sentinel/files/13163813/createUiDefinition.zip)

ok that should be done

**Comment by v-sudkharat** [comment]
@keyoke , please have a look at this comment -https://github.com/Azure/Azure-Sentinel/pull/9148#issuecomment-1778832821
Thanks!

**Comment by keyoke** [comment]
> Hello @keyoke, these screenshots are ok. As you may know the Analytic rules is parser dependent, to test those we do need to save the parsers. Due to lack of sample data parsers are showing us below result. Can you please provide updated sample data with us. image

ok I have added the required sample data

**Comment by v-sudkharat** [comment]
@keyoke, thanks for providing new the sample data with us, you can keep the old one, which is highlighted below. 
image


please have a look at this comment - https://github.com/Azure/Azure-Sentinel/pull/9148#issuecomment-1782689922

Also, the 3.0.0 zip contains only 2 files - createUiDefinition.json and mainTemplate.json 
Please remove the subfolders inside the zip file.
image


Thanks!

**Comment by keyoke** [comment]
> @keyoke, thanks for providing new the sample data with us, you can keep the old one, which is highlighted below. image
> 
> please have a look at this comment - [#9148 (comment)](https://github.com/Azure/Azure-Sentinel/pull/9148#issuecomment-1782689922)
> 
> Also, the 3.0.0 zip contains only 2 files - createUiDefinition.json and mainTemplate.json Please remove the subfolders inside the zip file. image
> 
> Thanks!

ok have done this

**Comment by v-sudkharat** [comment]
@keyoke, thanks. please have a look on below comment - 
image

**Comment by keyoke** [comment]
> @keyoke, thanks. please have a look on below comment - image

ok have reverted

**Comment by v-sudkharat** [comment]
Hi @keyoke, Thanks for making suggested changes.

**Review by v-sudkharat — APPROVED** [review]
Changes Looks Good. 
Adding the Screenshots of Solution Tested Successfully : -

1. Main template deployment Successful - 
DeploymentDone

2. Data Connector Page - 

 
dataConnector 1 good
dataConnector 2 good
dataConnector 3 good
dataConnector 4 good

Analytic Rule Validated and Created Successfully

Analytic rule 1 Done
Analytic rule 2 Done
Analytic rule 3 Done
Analytic rule 4 Done
Analytic rule 5 Done

Workbook Created Successfully - 
 
WorkbookDone

CreateUi Looks good (logo is visible) - 

CreateUi

All Solution content created successfully. 

Dashboard

(Note: Data connector Successfully connected, and playbook successfully deployed screenshot is added in PR itself)

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
