### PR TITLE
090122 as compromised machine tagging

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - New playbook

   Reason for Change(s):
   - New playbook

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by hollyollyoxenfree** [comment]
@devikamehra @rushriva @v-spadarthi : Hello all, I just wanted to follow up with this. Has anyone had a chance to review?

**Comment by v-atulyadav** [comment]
Hi @devikamehra and @rushriva , please review the playbooks and provide your feedback accordingly. Thanks!!

**Comment by v-atulyadav** [comment]
Hi @devikamehra and @rushriva , please review the playbooks and provide your feedback accordingly. Thanks.

**Comment by v-atulyadav** [comment]
Hi @devikamehra and @rushriva , please review the playbooks and provide your feedback accordingly. Thanks.

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @AcceleryntSecurityDev - Thank you for your submission. Sorry for delay in review. 
- We have recently migrated to new approach (template specs) and as part of this, now having metadata object is mandatory for every playbook. 
- You can find the instructions here - https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide#contribution-guidelines
- For examples you can refer this playbook https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Playbooks/OktaPlaybooks/Okta-EnrichIncidentWithUserDetails/azuredeploy.json 
- As a best practice, we recommend sentinel connection in playbooks uses "ManagedSecurityIdentity".
Please refer Sample [Template](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json) for sample template. For more details, refer [this](https://techcommunity.microsoft.com/t5/azure-sentinel/what-s-new-managed-identity-for-azure-sentinel-logic-apps/ba-p/2068204). Make sure to do changes at 3 places 

image

image

image

**Comment by AcceleryntSecurityDev** [comment]
@anki-narravula changes have been made, please review.

**Comment by v-atulyadav** [comment]
Hi @rushriva @devikamehra @anki-narravula , @AcceleryntSecurityDev has made some changes can you please review and provide feedback accordingly. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rushriva @devikamehra @anki-narravula , @AcceleryntSecurityDev has made some changes can you please review and provide feedback accordingly. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rushriva @devikamehra @anki-narravula , @AcceleryntSecurityDev has made some changes 10 days ago can you please check for the same. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rushriva @devikamehra @anki-narravula, @AcceleryntSecurityDev made some changes twelve days ago, so please check them. Thanks.

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
