### PR TITLE
Updated data connector code with the fix of pagination and checkpoint related issue and repackaged it with v3 tool

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Change(s):
   - Updated data connector code with the fix of pagination and checkpoint related issue and repackaged it with v3 tool

   Reason for Change(s):
   - Issue with the pagination and some checkpointing

   Version Updated:
   - Created and updated solution with the latest v3 tool and updated version to 3.0.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest Please create a custom table schema for BitSight_Alerts_CL under this folder .script/tests/KqlvalidationsTests/CustomTables 
And this PR will investigated and will update about the same before 17 January, 2024.

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Please try to resolve Code Ql errors and Proceed with the above requested changes.

**Comment by niralishah-crest** [comment]
> Hello @jayeshprajapaticrest, Please try to resolve Code Ql errors and Proceed with the above requested changes.

@v-prasadboke We have fixed the codeQL erros and KQLValidation errors and updated the PR.
Thanks

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Thanks for committing the requested changes. I'll take a look at it and come back to you by 23 January, 2024.

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Can you share working images of function app. Thanks

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, We are waiting for the function app images

**Comment by niralishah-crest** [comment]
> Hello @jayeshprajapaticrest, We are waiting for the function app images

@v-prasadboke 
Please find attached screenshots of running function app.

PortFolioCompanies

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
