### PR TITLE
Create Process Tree function from make-graph

### PR DESCRIPTION
**Pull request by hchiphong**
Required items, please complete
   
   Change(s):
   - Create Process Tree from make-graph

   Reason for Change(s):
   - New function

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

### CODE REVIEW

**Comment by hchiphong** [comment]
> @hchiphong please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by v-atulyadav** [comment]
Hi @hchiphong,
Thank you for raising Pull Request with us! We will review it and get back to you by 25 Sep 2023. Thanks

**Comment by v-sabiraj** [comment]
Hey @hchiphong , we checked on the query but there is no result for the query, can you please add screenshot of working query function, thanks.

image

**Comment by hchiphong** [comment]
Hey @v-sabiraj. I believe Defender hasn't had make-graph function yet. If we run query in Sentinel or ADX we should result as screenshot shows:
image

**Review by v-sabiraj — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
