### PR TITLE
Infoblox CDC update Parser

### PR DESCRIPTION
**Pull request by sschuur**
Change(s):
   - Update [InfobloxCDC.yam](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Infoblox%20Cloud%20Data%20Connector/Parsers/InfobloxCDC.yaml)l to manually parse with extract() rather than dynamically due to slowness
   - Update [InfobloxCDCB1TDWorkbook.json](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Infoblox%20Cloud%20Data%20Connector/Workbooks) to remove extra AdditionalExtensionsParsedNested field no longer used. Otherwise unchanged
   - Update workbook [infoblox_logo.svg](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/Images/Logos/infoblox_logo.svg)
   - Update metadata in [WorkbooksMetadata.json](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json)
   
   Reason for Change(s):
   - Parser too slow

   Version Updated:
   - No analytic rules updated

   Testing Completed:
   - Testing correctly in my own environment
----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @sschuur,
Thanks for raising this PR. This PR will be investigated and we will update you about the same before 27 February, 2024

**Comment by v-prasadboke** [comment]
Hello @sschuur, We are facing problem while custom deploying the maintemplate. we are trying to resolve it and will get back to you by 29 February, 2024.

**Comment by sschuur** [comment]
Hi @v-prasadboke, I have not updated the changes to be reflected in the maintemplate yet. Would you like me to do that now?

**Comment by v-prasadboke** [comment]
> Hi @v-prasadboke, I have not updated the changes to be reflected in the maintemplate yet. Would you like me to do that now?

I repackaged the solution locally and tried deploying it.

**Comment by sschuur** [comment]
@v-prasadboke sure, i am working on packaging it now.

**Comment by sschuur** [comment]
Hi @v-prasadboke , I pushed the updated packages. They look good in [manual validation](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3#manual-validation). New AMA data connector looks good too. 
image

**Comment by sschuur** [comment]
Hi @v-prasadboke , looks like its getting stuck on the instruction steps for the data connectors. Can these lines just be deleted outright? 

                           
                               
                            "title": "Step A. Configure the Common Event Format (CEF) via AMA data connector",
                                "description": "...",
                                "instructions": []
                              },
                              {
                                "title": "Step B. Configure Infoblox BloxOne to send Syslog data to the Infoblox Cloud Data Connector to forward to the Syslog agent",
                                "description": "...",
                                "instructions": []
                              },
`

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
