### PR TITLE
Possible Fix for #4541

### PR DESCRIPTION
**Pull request by samikroy**
Possible Fix for #4541 

Reset-AADPassword playbook not working with default OOB template

   Required items, please complete

- Update PS script
- Updated the logic app / playbook definition.

### CODE REVIEW

**Comment by samikroy** [comment]
@anki-narravula & @v-spadarthi  - Please let me know for further changes to this.

**Comment by samikroy** [comment]
@lior-tamir & @BenjiSec - Could you please help merging this !

**Comment by BenjiSec** [comment]
@samikroy - I'll have to change few things and will make new PR. Need to add control if user doesn't have a manager and will change connection for checking manager to HTTP. Also this is template so need to change template versioning as well as add release notes.

**Comment by Yaniv-Shasha** [comment]
template error

**Comment by samikroy** [comment]
> @samikroy - I'll have to change few things and will make new PR. Need to add control if user doesn't have a manager and will change connection for checking manager to HTTP. Also this is template so need to change template versioning as well as add release notes.

@BenjiSec - Thank you for sharing this.

**Pull request closed without merging**
