### PR TITLE
Added Playbooks and Analytic Rules for Pure Storage Solutions

### PR DESCRIPTION
**Pull request by skeerthivasan**
Required items, please complete

Change(s):
Addition of playbooks and analytic rules for Pure Storage Solutions

Reason for Change(s):
Addition of playbooks and analytic rules for Pure Storage Solutions

Version Updated:
Yes

Testing Completed:
Yes

Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by skeerthivasan** [comment]
@v-prasadboke , Thanks for looking into this, Let me know if there are any actions required from my end.

**Comment by v-prasadboke** [comment]
> @v-prasadboke , Thanks for looking into this, Let me know if there are any actions required from my end.

Hello @skeerthivasan, Please fill up the metadata details in all the playbooks

**Comment by skeerthivasan** [comment]
> > @v-prasadboke , Thanks for looking into this, Let me know if there are any actions required from my end.
> 
> Hello @skeerthivasan, Please fill up the metadata details in all the playbooks

Hi @v-prasadboke , Thanks for your inputs, I've added requested details, please check and proceed.

**Comment by v-prasadboke** [comment]
Thanks @skeerthivasan, For committing the required changes

**Comment by skeerthivasan** [comment]
> Thanks @skeerthivasan, For committing the required changes

@v-prasadboke , if its all fine, please proceed with merging. We need to push the changes into solutions package asap.

**Comment by skeerthivasan** [comment]
> > Thanks @skeerthivasan, For committing the required changes
> 
> @v-prasadboke , if its all fine, please proceed with merging. We need to push the changes into solutions package asap.

@v-prasadboke , did you get chance to look at this ? please help us in expediting, thanks

**Comment by skeerthivasan** [comment]
@v-prasadboke , I have fixed file issue and repushed, checks are passing now. Please check and proceed

**Comment by skeerthivasan** [comment]
> @v-prasadboke , I have fixed file issue and repushed, checks are passing now. Please check and proceed

@v-prasadboke , can you please provide an update on this ? Thanks for your understanding.

**Comment by v-prasadboke** [comment]
> > @v-prasadboke , I have fixed file issue and repushed, checks are passing now. Please check and proceed
> 
> @v-prasadboke , can you please provide an update on this ? Thanks for your understanding.

Hello @skeerthivasan, There's something wrong with playbooks. After deploying the solution playbooks cannot be seen in the automation blade. 

I'm finding the issue first

**Comment by skeerthivasan** [comment]
> > > @v-prasadboke , I have fixed file issue and repushed, checks are passing now. Please check and proceed
> > 
> > 
> > @v-prasadboke , can you please provide an update on this ? Thanks for your understanding.
> 
> Hello @skeerthivasan, There's something wrong with playbooks. After deploying the solution playbooks cannot be seen in the automation blade.
> 
> I'm finding the issue first

@v-prasadboke , thanks for the update, I haven't seen any errors while packaging. Its strange to have this issue.
Let me know if you have any further pointers to proceed ? If required, I can join on a call to assist, let me know.

**Comment by skeerthivasan** [comment]
> > > > @v-prasadboke , I have fixed file issue and repushed, checks are passing now. Please check and proceed
> > > 
> > > 
> > > @v-prasadboke , can you please provide an update on this ? Thanks for your understanding.
> > 
> > 
> > Hello @skeerthivasan, There's something wrong with playbooks. After deploying the solution playbooks cannot be seen in the automation blade.
> > I'm finding the issue first
> 
> @v-prasadboke , thanks for the update, I haven't seen any errors while packaging. Its strange to have this issue. Let me know if you have any further pointers to proceed ? If required, I can join on a call to assist, let me know.

@v-prasadboke , I was able to figure out the template issue and fixed the same. Also tested using preview links, its working fine. Please check and proceed with merge. Also solution offer certification(pushed from partner page) is pending for manual validation. If that comes to your review, please push the same or let relevant team to expedite. Thanks in advance.

**Comment by skeerthivasan** [comment]
@v-prasadboke , Any updates on this please

**Review by v-rusraut — DISMISSED** [review]

**Review by v-rusraut — APPROVED** [review]

**Comment by skeerthivasan** [comment]
@v-prasadboke @v-rusraut , Thanks for merging PR. 
Please take care of Solution offer review in Marketplace as well.

**Pull request merged**
