### PR TITLE
Log4j solution enrichment

### PR DESCRIPTION
**Pull request by rushriva**
Following playbooks and workbook are added to enrich Log4j Solution - 
1. Playbooks - BatchImportToSentinel, Log4jIndicatorProcessor
These playbooks automate the ingest of threat indicators into the ThreatIntelligenceIndicator table of an Azure Sentinel workspace. 
2. WorkBook - Log4j_Impact_Assessment_Workbook
This Workbook provides a consolidated view of all Security Incidents, Alerts and Asset Vulnerability information related to Log4j across multi-Tenant environments.

### CODE REVIEW

**Comment by NikTripathi** [comment]
@anki-narravula Please review playbooks.

**Review by NikTripathi — CHANGES_REQUESTED** [review]
Workbook queries are failing.
image
image

**Review by NikTripathi — APPROVED** [review]
Workbook looks good.

**Review by anki-narravula — APPROVED** [review]
Playbooks looks good. Approved to merge

**Pull request merged**
