### PR TITLE
Initial Branch from old Closed PR #7696

### PR DESCRIPTION
**Pull request by sriley0975**
This is the NEW AUHOMIZE Solution
Files modified:
	modified:   .script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json
	modified:   Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json
Files added:
	.script/tests/KqlvalidationsTests/CustomTables/Authomize_v2_CL.json
	Logos/Authomize.svg
	Sample Data/Authomize_v2_CL.csv
	Solutions/Authomize/Analytic Rules/
	Solutions/Authomize/Data Connectors/
	Solutions/Authomize/Data/
	Solutions/Authomize/Hunting queries/
	Solutions/Authomize/Package/
	Solutions/Authomize/SolutionMetadata.json
	Solutions/Authomize/Workbooks/
	Workbooks/Images/Logos/authomize.svg

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by sriley0975** [comment]
This is a continuation of work from the original - We closed out PR @7696 to remove files that should not have been modified and were missed - 
NOTE: Created initial Data Connector Azure Function - testing right now - will update the Data Connector components as needed.

**Comment by sriley0975** [comment]
@v-atulyadav Hi - this is the new updated content - I copied the original and updated a new branch with details. Working the data connector for verification of tests this weekend. Let me know if you find anything in this initial.

**Comment by v-atulyadav** [comment]
Hi @sriley0975,

As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using V3 tool Please go through this readme file on how to use the V3 tool https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

And we need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by v-atulyadav** [comment]
> OK - understood - will look at t he new V3 guidance and repackage solution.

Thanks @sriley0975.

**Comment by sriley0975** [comment]
Doing a walkthrough of app function to update readme.md with final install instructions. Expect to have that done today. I will also supply a deployment ARM file (not sure if this is required).

**Comment by v-atulyadav** [comment]
Hi @sriley0975, 
Thanks for packaging this solution with v3. We need to rectify below mentioned points.
1. **Release Note file**
 - Version should be 3.0.0 instead of 1.0.0
 - Date format of Date Modified column is DD-MM-YYYY 
 
image

2. Please revert 2.0.0 commit as we need only **3.0.0**.
image

3. Please remove **older version** from 3.0.0 zip.
image

4. **Data connector validation failure**. 
 - In `AuthomizeCustomConnector.json` file you have mentioned link for readme file but in this solution readme file was not attached please include this file.
image

5. **Solution validation failure**
 - PublisherId should be in lowercase so please change this in `SolutionMetadata.json` and repackage the solution again
 
image

**Comment by v-atulyadav** [comment]
Hi @sriley0975, hope you are doing well. Just wanted to check if you got a chance to look at the suggestions shared. Please feel free to reach out to us for any queries and/or support. Thanks

**Comment by sriley0975** [comment]
Hi @v-atulyadav sorry for the delay - found an issue with my app when doing the readme.md file - The current readme.md needed some heavy lifting to make it easier for customer to install function app. I'm new to function apps so it has been a bit of a learning curve as I try and make it work correctly on my test environment.

I'm currently on vacation, but I did make all the other suggested changes which I can submit if you want to start reviewing those. Let me know if you want me to do that? Meanwhile I have to work on the final piece at thee end of this week when I come back from my holidays. I should have something for you over this coming weekend.

Let me know if you want me to release to you what I have current done and then send you the latest on the data connector and readme.md file this weekend or wait until I have finished everything and release.

**Comment by sriley0975** [comment]
OK – I’ll aim to submit this weekend so all changes are reviewed at once.

**Comment by v-atulyadav** [comment]
Hi @sriley0975, 
I would appreciate if you could let us know once you've completed the suggested changes and also checked for conflicts in the branch.
Thanks

**Comment by sriley0975** [comment]
sorry for the delay - I became sick and have only just returned back to work - I will be working this today onwards. Thank you.
________________________________

**Comment by v-atulyadav** [comment]
Noted @sriley0975. Thanks

**Comment by sriley0975** [comment]
Yes – working – found some issues with function – tables not working properly – may switch to blob tomorrow morning else all done…

From: v-atulyadav ***@***.***>
Date: Tuesday, August 15, 2023 at 11:41 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>, waiting for your response. Thanks

**Comment by v-atulyadav** [comment]
Thanks @sriley0975.

**Comment by v-atulyadav** [comment]
Hi @sriley0975,
Please inform us once you've completed the suggested changes and checked for conflicts in the branch. Thanks

**Comment by sriley0975** [comment]
Thanks for the followup working it – will update as soon as released

From: v-atulyadav ***@***.***>
Date: Monday, August 21, 2023 at 11:19 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>,
Please inform us once you've completed the suggested changes and checked for conflicts in the branch. Thanks

**Comment by v-atulyadav** [comment]
Noted @sriley0975, thanks.

**Comment by sriley0975** [comment]
Hi @v-atulyadav - I have the scripted tested and documented will be posting later today.

**Comment by v-atulyadav** [comment]
Noted @sriley0975. Thanks

**Comment by v-atulyadav** [comment]
Hi @sriley0975,
I can see that you have updated metadata in each analytical rule and hunting query. Could you please remove this metadata from these files and repackage the solution again?
image

**Comment by sriley0975** [comment]
Strange - I didn’t update those might have been missed from another time - updating and will submit again.

Steven Riley | Director Technical Partner Enablement | Authomize
North America | Mobile: 801.361.4957 | www.authomize.com
________________________________

**Comment by sriley0975** [comment]
Please find attached the latest connector Monitor runs.

[A screenshot of a computer  Description automatically generated]

From: v-atulyadav ***@***.***>
Date: Thursday, September 14, 2023 at 8:40 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Thanks @sriley0975<https://github.com/sriley0975>. Also, please look into the branch conflicts.

**Comment by v-atulyadav** [comment]
Hi @sriley0975, could you please look into branch conflicts. thanks

**Comment by sriley0975** [comment]
I’ll double check this.

From: v-atulyadav ***@***.***>
Date: Monday, September 18, 2023 at 9:21 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>, could you please look into branch conflicts. thanks

**Comment by v-atulyadav** [comment]
Thanks @sriley0975.

**Comment by v-atulyadav** [comment]
Hi @sriley0975, please resolve branch conflicts. Thanks

**Comment by v-atulyadav** [comment]
Hi @sriley0975, could you please resolve branch conflicts. Thanks

**Comment by sriley0975** [comment]
Sorry for the slowness here – I’m traveling internationally so have been out of pocket

Working this today – I will work in more detail to ensure I have conflicts resolved.

I’ll rebase and go through any conflicts I have manually – obviously, I’m missing something here.

Sorry for the delay.

From: v-atulyadav ***@***.***>
Date: Monday, September 25, 2023 at 7:12 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>, could you please resolve branch conflicts. Thanks

**Comment by v-atulyadav** [comment]
Noted @sriley0975. Thanks

**Comment by sriley0975** [comment]
@Atul Yadav (TATA CONSULTANCY SERVICES ***@***.***> updated

git push origin Authomize-Solution-v2 --force-with-lease
Enumerating objects: 33793, done.
Counting objects: 100% (24492/24492), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9414/9414), done.
Writing objects: 100% (22108/22108), 411.30 MiB | 15.43 MiB/s, done.
Total 22108 (delta 14971), reused 19299 (delta 12426), pack-reused 0
remote: Resolving deltas: 100% (14971/14971), completed with 683 local objects.
To https://github.com/sriley0975/Azure-Sentinel.git
+ 433fae18c8...67b8c46583 Authomize-Solution-v2 -> Authomize-Solution-v2 (forced update)

From: v-atulyadav ***@***.***>
Date: Tuesday, September 26, 2023 at 2:25 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Noted @sriley0975<https://github.com/sriley0975>. Thanks

**Comment by v-atulyadav** [comment]
Hi @sriley0975,
The data connector permission block has been modified. Please replace the attached connector (extract the zip file for the connector file). This will clear DataConnectorValidations.
.
[AuthomizeCustomConnector.zip](https://github.com/Azure/Azure-Sentinel/files/12830574/AuthomizeCustomConnector.zip)

**Comment by v-atulyadav** [comment]
Noted @sriley0975. Thanks

**Comment by v-atulyadav** [comment]
Hi @sriley0975.
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

**Comment by sriley0975** [comment]
Thank you – changes will be made today and updates performed.

From: v-atulyadav ***@***.***>
Date: Sunday, October 15, 2023 at 10:35 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>.
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

**Comment by sriley0975** [comment]
Sorry this took so long – I’m back on deck for the rest of the week

I just pushed update for DataConnectorValidations

cheers

From: v-atulyadav ***@***.***>
Date: Friday, October 6, 2023 at 5:49 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>,
The data connector permission block has been modified. Please replace the attached connector (extract the zip file for the connector file). This will clear DataConnectorValidations.
.
AuthomizeCustomConnector.zip<https://github.com/Azure/Azure-Sentinel/files/12830574/AuthomizeCustomConnector.zip>

**Comment by sriley0975** [comment]
Updated with new AuthomizeCustomConnector

**Comment by v-atulyadav** [comment]
Hi @sriley0975, we are still getting connector validation failures.
The data connector permission block has been modified. Please replace the attached connector (extract the zip file for the connector file).
[AuthomizeCustomConnector.zip](https://github.com/Azure/Azure-Sentinel/files/12981970/AuthomizeCustomConnector.zip)

And also could you please grant me the access for your branch so I can push few commits. Thanks

**Comment by sriley0975** [comment]
I will do it again…I will grant access

From: v-atulyadav ***@***.***>
Date: Tuesday, October 17, 2023 at 10:44 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Steven Riley ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Initial Branch from old Closed PR #7696 (PR #8603)

Hi @sriley0975<https://github.com/sriley0975>, we are still getting connector validation failures.
The data connector permission block has been modified. Please replace the attached connector (extract the zip file for the connector file).
AuthomizeCustomConnector.zip<https://github.com/Azure/Azure-Sentinel/files/12981970/AuthomizeCustomConnector.zip>

And also could you please grant me the access for your branch so I can push few commits. Thanks

**Comment by v-atulyadav** [comment]
Hi @sriley0975, hyperlinkvalidation failing beacuse of below
In AuthomizeCustomConnector.json file you have mentioned link for readme file but in this solution readme file was not attached please include this file. Thanks
image

**Comment by v-atulyadav** [comment]
AuthomizeConnector

**Review by v-atulyadav — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
