### PR TITLE
MTTC/MTTT Calculation are inconsistent in Security Operations Efficiency workbook

### PR DESCRIPTION
**Pull request by briandelmsft**
Change(s):
   - Changed the Mean time to triage and Mean time to closure to actual calculate the mean.  The current iteration of the workbook calculates the median which is not standard for this metric.

   Reason for Change(s):
   - Industry standard calculations for MTTx is to use a mean (average) not a median/50th percentile
   - Also part of the workbook with MTTC/MTTT BY Owner already used means, but the overall numbers used a median so this change is also important for consistency in the workbook itself

   Version Updated:
   - N/A

   Testing Completed:
   - Yes, deploys without error

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes, validates successfully

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @briandelmsft, will provide feedback on this soon. Thanks

**Review by v-atulyadav — COMMENTED** [review]
Hi @briandelmsft, can you please update workbook metadata as per below highlighted properties. Thanks.

image

**Comment by v-atulyadav** [comment]
Hi @briandelmsft, take a look at the comments above. Thanks

**Comment by briandelmsft** [comment]
@v-atulyadav I have made the requested additions to the metadata file

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
