### PR TITLE
New connector template for SyslogAma

### PR DESCRIPTION
**Pull request by haim-na**
Required items, please complete
   
   Change(s):
   - Add new connector template for the syslog solution.

   Reason for Change(s):
   - New connector.

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @haim-na,
Please work on below points.
1.  There is validation error due missing property **additionalRequirementBanner**, please add this property.


Refer link  : https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_Syslog_template.json.

2. After clicking on **Create data collection rule** new page open but it is not working properly,please resolve this issue.



Thanks

**Comment by v-rusraut** [comment]
Hi @haim-na,
Please work on above comment.
Thanks

**Comment by v-rusraut** [comment]
Hi @haim-na,
Please work on above provided comment.
Thanks

**Comment by v-rusraut** [comment]
Hi @haim-na,
We fixed additionalRequirementBanner validation issue,
but now getting permission issue, Please add permission which match with Syslog Connector Template.
image

Please refer link :  https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_Syslog_template.json.
Thanks

**Comment by haim-na** [comment]
I've updated both syslog connector templates to match the needed permissions

**Comment by v-rusraut** [comment]
Hi @haim-na,

Still there is permission validation issue.
Please update permission similar to below screen shot.
image

Refer Link:  https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_Syslog_template.json

Thanks

**Comment by v-rusraut** [comment]
Hi @haim-na,
We are working on fixing validation issue. We will provide you an update on 24 Jan 2024.
Thanks

**Review by v-rusraut — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
