### PR TITLE
AWS_ConsoleLogonWithoutMFA change when UserIdentityUserName is empty

### PR DESCRIPTION
**Pull request by AndreasRogge**
Required items, please complete
   
   Change(s):
     - Updated KQL for AWS_ConsoleLogonWithoutMFA.yaml
     - Checked if UserIdentityUserName is empty and when yes user UserIdentityPrincipalID and just everything behind ":"

   Reason for Change(s):
   - UserIdentityUserName was almost everytime empty in my cases

   Version Updated:
   - Yes, version set from 1.0.0 to 1.0.1

   Testing Completed:
   - Tested the KQL in my environment

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Comment by v-spadarthi** [comment]
@AndreasRogge : Please resolve the conflicts.
image

I could see

**Comment by AndreasRogge** [comment]
> @AndreasRogge : Please resolve the conflicts. image

Sorry but I don't know what the conflict is. There is no new line at the end of the file and "kind: Scheduled" should be a valid value. Could you help me out?

**Comment by v-spadarthi** [comment]
@AndreasRogge : Please resolve the conflicts 
image

**Comment by AndreasRogge** [comment]
> @AndreasRogge : Please resolve the conflicts image

@v-spadarthi: I saw this but what is the error behind this? As I already wrote there is no newline and this kind (scheduled) should be supported.

**Comment by v-spadarthi** [comment]
@AndreasRogge : Please remove the below contents from above file
Keep only one Kind:Scheduled only
image
image

**Comment by AndreasRogge** [comment]
> @AndreasRogge : Please remove the below contents from above file Keep only one Kind:Scheduled only image image

@v-spadarthi : Thanks four your reply. There is only one "kind: Scheduled" in Code:
image

**Comment by v-spadarthi** [comment]
@AndreasRogge : Still, we could see conflicts, please check and let us know if you need any help

**Comment by AndreasRogge** [comment]
@v-spadarthi : Is this allright now?

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review the detections and provide your signoff. Thanks!

**Review by aprakash13 — APPROVED** [review]
Thanks @AndreasRogge for the changes.

**Pull request merged**
