### PR TITLE
Create mechanism to exclude activities based on environment variable

### PR DESCRIPTION
**Pull request by beachfires**
Change(s):
   - Added mechanism to exclude Google Workspace activities based on environment variable

   Reason for Change(s):
   - Resolves ISSUE #8115 

   Version updated:
   - N/A

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-vdixit** [comment]
Hi @beachfires we have reviewed and tested the change you have made, we will discuss with the team and update you shortly, thanks!

**Review by v-vdixit — APPROVED** [review]

**Comment by beachfires** [comment]
@v-vdixit Thank you! Will the Google connector in Sentinel be updated with this change automatically or do I have to action something?

**Comment by v-vdixit** [comment]
> @v-vdixit Thank you! Will the Google connector in Sentinel be updated with this change automatically or do I have to action something?

Hi @beachfires we will repackage and update the solution from our end to publish the latest changes, thanks!

**Comment by beachfires** [comment]
The function app still points to the old version of the function app code? Have you released the updated version yet? What's the release process?

**Pull request merged**
