### PR TITLE
Fire Eye NX Data Connector

### PR DESCRIPTION
**Pull request by vu-socprime**
Fixes #

## Proposed Changes

  - add Fire Eye NX Data Connector

### CODE REVIEW

**Comment by v-admahe** [comment]
@vu-socprime Parser is giving error on project rename it didn't identify the column name. Could you please make a required changes.

image

Thanks,
Aditi

**Comment by vu-socprime** [comment]
> @vu-socprime Parser is giving error on project rename it didn't identify the column name. Could you please make a required changes.
> 
> image
> 
> Thanks,
> Aditi

@v-admahe The parser is correct. This error occurs when there are no data in the table.

**Comment by v-admahe** [comment]
> @v-admahe The parser is correct. This error occurs when there are no data in the table.

@vu-socprime Some of the field mention in parser are not available in sample data as well like :
anomaly , osinfo , sname,vlan,link

Thanks,
Aditi Maheshwari

**Comment by vu-socprime** [comment]
> > @v-admahe The parser is correct. This error occurs when there are no data in the table.
> 
> @vu-socprime Some of the field mention in parser are not available in sample data as well like :
> anomaly , osinfo , sname,vlan,link. This is the reason parser is giving error.
> 
> Thanks,
> Aditi Maheshwari

@v-admahe All that fields are present in sample data as DeviceCustom fields. This error occurs when there are no data in the table. Try to use other time period in the query that contains FireEyeNX events in CommonSecurityLog table.

**Review by v-rucdu — APPROVED** [review]

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
