### PR TITLE
Created an automation to keep service tags updated.

### PR DESCRIPTION
**Pull request by samikroy**
Created an automation to keep service tags updated.

### CODE REVIEW

**Comment by samikroy** [comment]
@NikTripathi - This automation is based on PowerShell to extract azure service tags from download center and save as a json file for further analytics to refer this.
But, tagged as JavaScript. Please let me know for any modifications.

**Review by sreedharande — CHANGES_REQUESTED** [review]
Can you move this to under tools. Add README, Steps to use it

**Comment by samikroy** [comment]
> Can you move this to under tools. Add README, Steps to use it

@sreedharande - Thank you for sharing this, will be able to similar file here :
https://github.com/samikroy/SyncMSServiceTags/blob/main/README.md

In addition, have a question - As this is a corn job (schedule) based on devops pipeline hence moving this as a tool will make it static and we will still have old file references in the rules like - #4266 

Please advise.

**Comment by v-sabiraj** [comment]
Hey @sreedharande, can you please check and provide your feedback, thanks.

**Comment by samikroy** [comment]
> Hey @sreedharande, can you please check and provide your feedback, thanks.

@sreedharande - Updated into tools folder as requested, please review & let me know for further updates.

**Comment by samikroy** [comment]
@sreedharande - Could you please help with merge for this.

**Comment by v-sabiraj** [comment]
Hey @sreedharande, can you please approve the changes, so the PR can be merged, thanks.

**Comment by vmanojreddy** [comment]
Hey @sreedharande, can you please approve the changes, so the PR can be merged, thanks.

**Comment by v-marimanda** [comment]
Hey @sreedharande, can you please approve the changes, so the PR can be merged, thanks.

**Review by v-rucdu — DISMISSED** [review]

**Comment by v-mchatla** [comment]
Hi @sreedharande 
Can you please review the changes and provide your comments.
Thanks

**Comment by NikTripathi** [comment]
@sreedharande Please look into this.

**Comment by v-marimanda** [comment]
@sreedharande Please look into this.

**Comment by v-mchatla** [comment]
Hi @sreedharande 
The author @samikroy already addressed your feedback. Can you please review once again and provide your approval
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande 
It would be great if you could review the PR and provide your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande 
Can you please review or route to someone who can review and provide signoff.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande
The author @samikroy already addressed your feedback. Can you please review once again and provide your approval or route it to someone who can review.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande ,
Can you please review and approve the PR
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande 
Please review or assign someone to review this PR.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande
Please review or assign someone to review this PR.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande
Please review or assign someone to review this PR. Let us know if you need any other details.
Thanks

**Comment by v-spadarthi** [comment]
Hi @sreedharande
Please review or assign someone to review this PR. Let us know if you need any other details.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande
Please review or assign someone to review this PR. Let us know if you need any other details.
Thanks

**Comment by v-spadarthi** [comment]
Hi @sreedharande
Please review or assign someone to review this PR. Let us know if you need any other details.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande
Please review and provide your signoff, so that we can merge this PR.
Thanks

**Comment by sreedharande** [comment]
@samikroy - Can you please remove .github/workflows folder. Keep your code in the parent folder. After review, we will add to workflows folder

**Comment by samikroy** [comment]
> @samikroy - Can you please remove .github/workflows folder. Keep your code in the parent folder. After review, we will add to workflows folder

@sreedharande - Thank you for your response. Have done the changes requested, please have review & let me know.

**Comment by v-mchatla** [comment]
Hi @sreedharande,
Author has addressed your comments. Can you please review the changes once again and provide your feedback if any.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande,
Author has addressed your comments. Can you please review the changes once again and provide your feedback if any.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande,
It would be great if you can spare sometime on this and provide your feedback.
Thanks

**Review by sreedharande — APPROVED** [review]

**Comment by samikroy** [comment]
@sreedharande  & @v-mchatla - Thank you for the approval & merge.
As requested earlier comment,
the workflow file was moved to the parent folder and was mentioned to be moved to the workflow folder after the merge.
Could you please help here.

**Pull request merged**
