### PR TITLE
Corrects MITRE techniques to right format.

### PR DESCRIPTION
**Pull request by Korving-F**
This PR updates a set of Scheduled/NRT rules tagged with incorrectly formatted MITRE techniques.
Trying to deploy these returns an error like: `Invalid data model. [ The technique TXXXX.XXX is invalid. The expected format is T####, where # represents a digit.]`
   
   Change(s): Multiple detection rules:
```bash
Azure-Sentinel  Detections   mitre_updates_on_rules  grep -Po 'T\d{4}.\d{3}' -rnw . | sort -u
./AlsidForAD/DCSync.yaml:17:T1003.006
./AlsidForAD/GoldenTicket.yaml:17:T1558.001
./AlsidForAD/LSASSMemory.yaml:17:T1003.001
./AlsidForAD/PasswordSpraying.yaml:17:T1110.003
./AuditLogs/AccountCreatedandDeletedinShortTimeframe.yaml:18:T1078.004
./AuditLogs/AccountCreatedDeletedByNonApprovedUser.yaml:18:T1078.004
./AuditLogs/AdminPromoAfterRoleMgmtAppPermissionGrant.yaml:21:T1098.003
./AuditLogs/AzureADRoleManagementPermissionGrant.yaml:22:T1098.003
./AuditLogs/BulkChangestoPrivilegedAccountPermissions.yaml:18:T1078.004
./AuditLogs/FirstAppOrServicePrincipalCredential.yaml:20:T1550.001
./AuditLogs/NewAppOrServicePrincipalCredential.yaml:20:T1550.001
./AuditLogs/NRT_NewAppOrServicePrincipalCredential.yaml:16:T1550.001
./AuditLogs/NRT_PIMElevationRequestRejected.yaml:14:T1078.004
./AuditLogs/PIMElevationRequestRejected.yaml:18:T1078.004
./AuditLogs/PrivlegedRoleAssignedOutsidePIM.yaml:18:T1078.004
./AuditLogs/UserAssignedPrivilegedRole.yaml:18:T1078.004
./AzureActivity/AADHybridHealthADFSServiceDelete.yaml:20:T1578.003
./AzureDevOpsAuditing/ADOAgentPoolCreatedDeleted.yaml:17:T1578.002
./AzureDevOpsAuditing/ADOAuditStreamDisabled.yaml:16:T1562.008
./AzureDevOpsAuditing/NewPAPCAPCASaddedtoADO.yaml:17:T1078.004
./DeviceEvents/SolarWinds_TEARDROP_Process-IOCs.yaml:21:T1543.003
./MultipleDataSources/NOBELIUM_IOCsMay2021.yaml:56:T1102.002
./MultipleDataSources/NOBELIUM_IOCsMay2021.yaml:57:T1204.001
./MultipleDataSources/PrivilegedAccountsSigninFailureSpikes.yaml:22:T1078.004
./MultipleDataSources/UnusualGuestActivity.yaml:24:T1078.004
./MultipleDataSources/UnusualGuestActivity.yaml:25:T1136.003
./MultipleDataSources/UnusualGuestActivity.yaml:26:T1087.004
./MultipleDataSources/ZincJan272021IOCs.yaml:48:T1071.001
./SecurityEvent/StartStopHealthService.yaml:21:T1562.001
./SigninLogs/AzureAADPowerShellAnomaly.yaml:22:T1078.004
./SigninLogs/MFARejectedbyUser.yaml:18:T1078.004
./SigninLogs/NRT_MFARejectedbyUser.yaml:14:T1078.004
./SigninLogs/UserAccounts-CABlockedSigninSpikes.yaml:22:T1078.004
```

   Reason for Change(s):
   - Needed for correct mappings to be deployed and rule deployments to not be rejected. 

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - Versions for all rules were updated.

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@Korving-F Please resolve the conflicts. Thanks!!

**Comment by vmanojreddy** [comment]
@Korving-F Please resolve the conflicts. Thanks!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks!!

**Comment by Korving-F** [comment]
@vmanojreddy bump ^_^

**Comment by Korving-F** [comment]
@aprakash13: This affects GUI-based deployments as well. Two examples of why these trailing subtechniques should be trimmed imho.

**Alsid (DCSync, Golden Ticket, LSASS Memory, Password Spraying)**
image
image


**User Assigned Privileged Role**
image
image

**Comment by v-sabiraj** [comment]
Hey @aprakash13, can you please review the detections, thanks.

**Comment by aprakash13** [comment]
Thanks. Discussing with the product team regarding support for MITRE SubTechnique.

**Comment by Korving-F** [comment]
Thanks for the follow up :)

**Comment by aprakash13** [comment]
> Thanks for the follow up :)

The issue has been fixed now. Would you please take a look and confirm so that we can close this PR out? Thanks for all your help @Korving-F 
image

**Pull request closed without merging**
