### PR TITLE
Udated solution package with the changes of field mapping with Extern…

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Required items, please complete
   
   Change(s):
   - Update the data code and workbook

   Reason for Change(s):
   - In previous version we mapped our threat id with the External Id field of intelligence indicator which would be further used in joining query in workbook to achieve one usecase of threat report details.
   - After some time our data connector running results in failed state due to there is an update from your management API which accept the External ID value with some specific format with GUID and because of our customable mapped threat ID with the External ID field due to invalid format. So we have fixed this changes to make our data connector working successfully and joining in the workbook panel working correctly to achieve our usecase.

   Version Updated:
   - 2.0.1

   Testing Completed:
   - Tested data connector working correctly as expected without having any errors. And data would be available in the workbook.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by jayeshprajapaticrest** [comment]
@v-atulyadav @v-rbajaj 
Can you please look into this PR as it has the minimal changes due to the changes in one field acceptance value changes?

**Comment by v-rbajaj** [comment]
Hi @jayeshprajapaticrest, please include this file `Solutions\CofenseTriage\Data\Solution_CofenseTriage.json` in the PR

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, please include this file `Solutions\CofenseTriage\Data\Solution_CofenseTriage.json` in the PR

@v-rbajaj Added please check. Let me know is other thing is required. Else can you please approve it ASAP.
Thanks

**Comment by v-rbajaj** [comment]
Hi @rahul0216, can you please take a look at workbook changes?

**Comment by jayeshprajapaticrest** [comment]
> > Hi @jayeshprajapaticrest, please include this file `Solutions\CofenseTriage\Data\Solution_CofenseTriage.json` in the PR
> 
> @v-rbajaj Added please check. Let me know is other thing is required. Else can you please approve it ASAP. Thanks

@v-rbajaj Done

@rahul0216 Can you please update on the Workbook review?

Cc: @v-atulyadav @v-prasadboke

**Comment by v-rbajaj** [comment]
Hi @jayeshprajapaticrest, can you please fix the failing ARM TTK validation?
image

**Comment by v-rbajaj** [comment]
@jayeshprajapaticrest, can you please update the label and text in create ui?

**Comment by jayeshprajapaticrest** [comment]
@v-rbajaj 
Fixed Armttk related error. Can you please proceed with the merging?
Thanks

**Review by v-rbajaj — APPROVED** [review]

**Pull request merged**
