### PR TITLE
Perimeter 81: Fixed Pkg

### PR DESCRIPTION
**Pull request by msft-sm**
Perimeter 81: Fixed Pkg
- Azure Sentinel to Microsoft Sentinel

   Required items, please complete
   
   Change(s):
- Azure Sentinel to Microsoft Sentinel

   Reason for Change(s):
- Azure Sentinel to Microsoft Sentinel

   Version Updated:
   - N/A

   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by msft-sm** [comment]
@v-dvedak 
Perimeter 81 fixed v. 2.0.1 from "Azure Sentinel" to "Microsoft Sentinel".

**Comment by v-dvedak** [comment]
@msft-sm , I see changes in 2.0.1. Please accommodate the changes for text Microsoft Sentinel in data connector [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Perimeter%2081/Data%20Connectors/Perimeter81ActivityLogs.json) as well.
Also, I suggest if you could change offer id to all lowercase in SolutionMetadata.json and mainTemplate.json.

**Comment by msft-sm** [comment]
@v-dvedak 
Fixed Perimeter 81 Data Connector from "Azure Sentinel" to "Microsoft Sentinel".

**Comment by msft-sm** [comment]
@v-dvedak 
Fixed Perimeter 81 offerID to all lower-case letters.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
