### PR TITLE
Update InsiderRiskManagement.json

### PR DESCRIPTION
**Pull request by thbanasi**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by NikTripathi — COMMENTED** [review]
Hi @thbanasi I think workbook is taking too much of memory. It is failing every time during testing.
image
Is it an expected behavior?

**Comment by thbanasi** [comment]
@Nikhil Tripathi (TATA CONSULTANCY SERVICES ***@***.***>,

It’s not expected behavior 😊. I think both the quantity and complexity of queries makes it too heavy for processing/performance. I’ve pushed another PR to limit the Workspace Parameter to a single workspace which makes it much faster on my end. Please give it another try and feel free to share snaps if you see anything unusual.

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Principal Product Manager
SCS | Microsoft Sentinel
***@***.******@***.***>



***@***.***

LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0>

**Comment by NikTripathi** [comment]
Hi @thbanasi Still getting the similar out of memory error.
image

**Comment by thbanasi** [comment]
@Nikhil Tripathi (TATA CONSULTANCY SERVICES ***@***.***>,

I pushed another PR update today. I've reduced parameters to single selections for performance. I've also removed recommended connectors and lighthouse sections which reduce the code base by ~3K lines. Please let me know if this resolves your error. Note, I'm using Edge/Chrome browsers in the CyberSecuritySOC tenant. Please let me know your thoughts, thanks.

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Principal Product Manager
SCS | Microsoft Sentinel
***@***.******@***.***>



***@***.***

LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0>

**Comment by thbanasi** [comment]
Team, would it be possible to review/approve and package this offering?

**Comment by NikTripathi** [comment]
HI @thbanasi We are now getting error as below.
image

**Comment by thbanasi** [comment]
@Nikhil Tripathi (TATA CONSULTANCY SERVICES ***@***.***>,

Yes, this is expected behavior if you don't have all the Sentinel data tables such as BehaviorAnalytics which is populated by the Entity Behavior Blade. Would it be possible to test/validate in the Ninja Demo<https://microsofteur.sharepoint.com/teams/SecurityDemos> for desired state?

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Principal Product Manager
SCS | Microsoft Sentinel
***@***.******@***.***>



***@***.***

LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0>

**Comment by NikTripathi** [comment]
Hi @thbanasi I am checking it in the workspace provided by you. CyberSOC, I think that contains all the required tables.

**Comment by thbanasi** [comment]
Perfect, thanks so much!

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Principal Product Manager
SCS | Microsoft Sentinel
***@***.******@***.***>



***@***.***

LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0>

**Comment by NikTripathi** [comment]
> Perfect, thanks so much! Very Respectfully, TJ Banasik CISSP-ISSEP,ISSAP,ISSMP Principal Product Manager SCS | Microsoft Sentinel ***@***.******@***.***> ***@***.*** LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0> From: NikTripathi ***@***.***> Sent: Thursday, September 8, 2022 3:27 PM To: Azure/Azure-Sentinel ***@***.***> Cc: TJ Banasik ***@***.***>; Mention ***@***.***> Subject: Re: [Azure/Azure-Sentinel] Update InsiderRiskManagement.json (PR #5946) Hi @thbanasi<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthbanasi&data=05%7C01%7CThomas.Banasik%40microsoft.com%7C85a9598f5157492296ba08da91d023b3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637982620386599914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a%2BUuveLKCSmmjhtlERHHN27u9pscPCiczdT8dTLGat4%3D&reserved=0> I am checking it in the workspace provided by you. CyberSOC, I think that contains all the required tables. - Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fpull%2F5946%23issuecomment-1241135170&data=05%7C01%7CThomas.Banasik%40microsoft.com%7C85a9598f5157492296ba08da91d023b3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637982620386599914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RCS%2B54bmJrnArXGgARHz%2BmVCk20UHdnDGUfsoyrd6EA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM6PREVBOIBDDCESEXLEQV3V5I4ZJANCNFSM57BXNNVQ&data=05%7C01%7CThomas.Banasik%40microsoft.com%7C85a9598f5157492296ba08da91d023b3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637982620386599914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IgeA5xi%2FvFGG6Gl%2BMp5UfDPY%2B66CNZjd2Ezokq1egA8%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Hi @thbanasi These queries are failing in **cybersecuritysoc** workspace and I think it's not the expected behavior. 
Please let me know what needs to be done.
Thanks

**Review by NikTripathi — APPROVED** [review]

**Comment by thbanasi** [comment]
@Nikhil Tripathi (TATA CONSULTANCY SERVICES ***@***.***>,

No worries, I'll ping you on Teams to walk through it.

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Principal Product Manager
SCS | Microsoft Sentinel
***@***.******@***.***>



***@***.***

LinkedIn: In/tjbanasik<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Ftjbanasik&data=04%7C01%7CThomas.Banasik%40microsoft.com%7C3243d1aec08b47f0c43b08da0dac0c99%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837329843702609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eSpfjHt5IJ9fvfOZp7Lquv9ZBADnY6jaxC7m4kHJVLw%3D&reserved=0>

**Pull request merged**
