### PR TITLE
Add Jamf Protect to Sentinel Solutions

### PR DESCRIPTION
**Pull request by txhaflaire**
Required items, please complete
   
   Change(s):
   - Add Jamf Protect to Sentinel Content Hub

   Reason for Change(s):
   - First commit

   Version Updated:
   - 1.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by txhaflaire** [comment]
@microsoft-github-policy-service agree [company="Jamf"]

**Comment by txhaflaire** [comment]
@microsoft-github-policy-service agree company="Jamf"

**Comment by v-spadarthi** [comment]
@txhaflaire : Please resolve the below comments
1. Logo should move to this folder https://github.com/Azure/Azure-Sentinel/tree/master/Logos
image Logo validation passed
2.Workbook we are getting below errors please provide the sample data to test
image
3.In Solution Input file please delete below and playbooks as well descriptions and text why because this solution has only workbook as per the PR
image
4.Could you please create a package 2.0.0 by using tool V2 and change the version in solution input file version to 2.0.0.
5.Move the solution input file under Data folder 
Ex: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Citrix%20ADC
6.Remove the Solution input file from Tools folder.

**Comment by txhaflaire** [comment]
@v-spadarthi Please guide me on how to create the package, either on macOS and Windows i'm failing running the script as it's only reporting back on CiscoDuoSecurity

**Comment by txhaflaire** [comment]
Screenshot 2022-10-13 at 11 41 15

@v-spadarthi 
Screenshot 2022-10-13 at 11 42 16

**Comment by v-spadarthi** [comment]
@txhaflaire : Please follow the below URL and do the package creation. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by txhaflaire** [comment]
@v-spadarthi i have followed all steps by step, please look at the attached screenshot as it errors out.

**Comment by v-spadarthi** [comment]
@txhaflaire : While creating package you need to keep your input file(Solution_JamfProtect.json) in below path 
Azure-Sentinel\Tools\Create-Azure-Sentinel-Solution\V2\input .

**Comment by txhaflaire** [comment]
@v-spadarthi I had that initially, what worked was deleting the existing Solution_Cisco file from the folder and the script runs as expected!

**Comment by v-spadarthi** [comment]
@txhaflaire : Please resolve the below errors
 Create UI definition looks fine
image
Main template we are getting errors please fix this
image
Please add workbook metadata for below path and above error will resolve the issue.
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json

**Comment by v-spadarthi** [comment]
@txhaflaire : we will check and let you know the update.

**Comment by v-spadarthi** [comment]
@txhaflaire : Please fix the conflicts. Thanks!

**Comment by txhaflaire** [comment]
@v-spadarthi please mention which conflitcs.

**Comment by v-spadarthi** [comment]
@txhaflaire : Please see the below 
image
You can revert the changes from V2/WorkbookMetadata/WorkbooksMetadata.json  here and i've addded  your changes here please take latest this file and check your changes and again create the package by using V2 tool. Thanks!

**Review by txhaflaire — COMMENTED** [review]
removed WorkbooksMetaData.json

**Comment by v-spadarthi** [comment]
@txhaflaire : Thanks for fixing the issues
Main template 
image
CreateUI definition
image
Arm-ttk validation 
image

**Review by v-spadarthi — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
