### PR TITLE
Zerofox/fix connector timeout

### PR DESCRIPTION
**Pull request by DNRRomero**
Required items, please complete
   
   Change(s):
   - removed the identity breach connector due to being incompatible with time-based trigger
   - Added async logic to Sentinel connector to improve performance
   - added logging entries for observability
   - changed the ZeroFox connector to generate entry batches instead of single entries

   Reason for Change(s):
   - There was a case of missing logs, combined with missing entries of the ZeroFox feeds
   - Identity Breach connector required additional data which was incompatible with user needs, and thus was never usable

   Version Updated:
   - Yes

   Testing Completed:
   - Yes, Local tests were done on personal Sentinel workspace

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes
-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by zkto — APPROVED** [review]

**Comment by DNRRomero** [comment]
Hi @v-prasadboke , are there any comments regarding our PR?
here is a list of our connectors functioning, we implemented some fixes so that our data connector matched the ZeroFox API requirements better. Here's a list of active connectors
image

**Comment by v-prasadboke** [comment]
Can you share the invocation logs screenshot 
It will expedite the merging process

**Review by v-prasadboke — DISMISSED** [review]

**Comment by DNRRomero** [comment]
> Can you share the invocation logs screenshot It will expedite the merging process
Hi @v-prasadboke 
Here are a few invocations, there are some errors because I was trying to improve the code and broke it by mistake
image

**Comment by v-prasadboke** [comment]
So the current changes which this PR has, is it breaking or working

**Comment by DNRRomero** [comment]
> So the current changes which this PR has, is it breaking or working 
> 

@v-prasadboke it is working

**Comment by v-prasadboke** [comment]
Ok Thanks for the confirmation

**Review by v-prasadboke — APPROVED** [review]

**Comment by DNRRomero** [comment]
Hi @v-prasadboke  after discussing with our security team, you were given write access to our forked repo, feel free to include the commits you require
on a separate line, I saw that our release notes were included into the main branch before the code is that expected?

**Comment by DNRRomero** [comment]
> Thanks for the access @DNRRomero, Are there any more changes in your queue to the function app.

@v-prasadboke  none at all

**Review by v-prasadboke — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
