### PR TITLE
Add ReversingLabs playbook

### PR DESCRIPTION
**Pull request by ivukovicRL**

### CODE REVIEW

**Comment by ivukovicRL** [comment]
@dicolanl @sarah-yo Hi, can you point me in right direction on how to solve DocumentsLinkValidation check fail?

**Comment by dicolanl** [comment]
@ivukovicRL you have links like this https://docs.microsoft.com/en-us/connectors/reversinglabsintelligence/. since we want to support folks who speak all languages we check for en-us or other specific languages.

Just remove the language specifier (in this case en-us) and the link will still work and default to the the users language.  correct link https://docs.microsoft.com/connectors/reversinglabsintelligence/

**Comment by ivukovicRL** [comment]
@dicolanl thx, fixed

**Comment by ivukovicRL** [comment]
@dicolanl Hi, when can we expect this to be merged? Is there anything else that we need to do on our side?

**Review by dicolanl — APPROVED** [review]

**Pull request merged**
