### PR TITLE
Commit to "Gigamon-Connector"

### PR DESCRIPTION
**Pull request by Mrudula-Oruganti-Gigamon**
Created a folder with "Gigamon Connector" under Solutions

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by Mrudula-Oruganti-Gigamon** [comment]
@microsoft-github-policy-service agree company="Gigamon"

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon Please repackage the solution using V3 tool. 
Instructions on using V3 tool - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

Also please share sample data to test the content of the solution.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
@v-prasadboke , I have added Gigamon_CL.json to the folder https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.

When i try to re-run, it is throwing an error. Below are the logs for reference. Could you help me if i missed any ?

https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=66324&view=logs&j=2bbe2297-1b5b-54f3-6060-67e7b289f6c3&t=eead14d6-24b1-5ed7-a5d7-ebab03b6d5f8

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon thank you for pointing this out. Will sure take a look at it.

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon I guess you mistakenly committed extra changes to this PR. Should I revert those changes.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Sure @v-prasadboke . Please do the needful. I am able to deploy the templates using both Json files using sanbox. However, i am facing an issue while committing it.  FYI, I have installed Arm-ttk inside GitHub folder and seems that has created an issue. I have moved it out of GitHub folder and tried of re-committing it. But i am still facing the issue.

**Comment by v-prasadboke** [comment]
I've reverted the commit. Please confirm on the commit once. Thanks.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Thanks @v-prasadboke . Some checks haven't completed yet. It's been a while. Is this expected ?? Also, please share the next steps.

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon

Please repackage the solution using V3 tool.
Instructions on using V3 tool - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-SentinelSolution/V3/README.md
Share sample data to test the content of the solution.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Thanks @v-prasadboke . Packaging has done successfully. 

I was successfully able to test "createUIDefinition.json". But, it is throwing below error when i test "mainTemplate.json". 

Attaching the images for reference. Could you please let me know which i am missing ??
Screenshot 2023-10-06 at 12 58 18 PM
Screenshot 2023-10-06 at 12 58 53 PM

**Comment by v-prasadboke** [comment]
Can you please click on error details and provide me the screenshot

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Hi @v-prasadboke , here is the latest update. I was successfully able to deploy the templates. However, i am facing an issue while commiting . Few validations are failing due to that. Any suggestions ?

**Comment by v-prasadboke** [comment]
First I would suggest to resolve validation checks on this PR.

**Review by v-prasadboke — COMMENTED** [review]
Hello @Mrudula-Oruganti-Gigamon this commit again added multiple commits to the PR.

**Comment by v-prasadboke** [comment]
Can we can connect on call for this. Please do share your mail id so I can drop a mail.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Sure @v-prasadboke . My id is : mrudula.oruganti@gigamon.com

**Comment by Mrudula-Oruganti-Gigamon** [comment]
@v-prasadboke , For some reason, it is throwing error at logovalidation. Could you please help me on this ?

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon Thanks for the updates. I'll investigate the changes and will update you about the same before 13 Ocotber, 2023.

**Comment by v-prasadboke** [comment]
Hi @Mrudula-Oruganti-Gigamon Please share the sample data.

**Comment by v-prasadboke** [comment]
[CitrixAnalytics_indicatorEventDetails_CL.json](https://github.com/Azure/Azure-Sentinel/files/12890744/CitrixAnalytics_indicatorEventDetails_CL.json)

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon as discussed in the call, Share the sample data as it gets available

**Comment by v-atulyadav** [comment]
Hi @Mrudula-Oruganti-Gigamon,
Could you please provide us with a sample data? and look into the conflicts between the branches as well. Thanks.

**Comment by Mrudula-Oruganti-Gigamon** [comment]
Thanks @v-prasadboke for being patience. Below is the sample data for reference. Thanks.
[1695376125000000_1695376148000007.json](https://github.com/Azure/Azure-Sentinel/files/13113761/1695376125000000_1695376148000007.json)

**Comment by Mrudula-Oruganti-Gigamon** [comment]
@v-prasadboke , When i try to perform re-packaging , it is throwing below error Prasad. Could you please help me for the reason behind it ?
"Error occured in catch of createSolutionV3 file Error details are The property 'descriptionHtml' cannot be found on this object. Verify that the property exists and can be set."
Could you please help me on this ?

**Comment by v-prasadboke** [comment]
Hello @Mrudula-Oruganti-Gigamon Description is short, Please add a few lines more.
Other than this all looks good

**Review by v-prasadboke — DISMISSED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
