### PR TITLE
MimecastTIRegional : Fixed workspace default log retention bug

### PR DESCRIPTION
**Pull request by SmitR01**
Change(s):
   - Updated Data connector

   Reason for Change(s):
   - do not set workspace default log retention to 30 days

   Version Updated:
   - Yes, 3.0.2

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @SmitR01,
Thanks for raising this PR. This PR will be investigated and we will update you about the same before 05 March, 2024

**Comment by v-rusraut** [comment]
Hi @SmitR01,
Please share the working images of the Function app.
Thanks

**Comment by SmitR01** [comment]
> Hi @SmitR01, Please share the working images of the Function app. Thanks

image
image

**Review by v-rusraut — APPROVED** [review]

**Comment by v-atulyadav** [comment]
Hi @SmitR01,
Please accept license agreement. Thanks

**Comment by v-rusraut** [comment]
Hi @SmitR01,
Please work on above comment.
Thanks

**Comment by SmitR01** [comment]
> Hi @SmitR01, Please accept license agreement. Thanks

@microsoft-github-policy-service agree company="Mimecast"

**Comment by v-rusraut** [comment]
Hi @SmitR01,
Please add below line in comment box instead of reply.
**@microsoft-github-policy-service agree company="Mimecast"**
Thanks

**Comment by SmitR01** [comment]
@microsoft-github-policy-service agree company="Mimecast"

**Comment by v-rusraut** [comment]
@microsoft-github-policy-service agree company="MimecastTIRegional"

**Comment by SmitR01** [comment]
@microsoft-github-policy-service agree company="MimecastTIRegional"

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
