### PR TITLE
Recorded Future Hunt

### PR DESCRIPTION
**Pull request by RecordedFutureOskbo**
Required items, please complete
   
   Change(s):
   - Added Recorded Future Automated Threat hunt.
      - 2 logic apps
      - 1 workbook
      - 4 Analytic Rules
   - Restructure readme by moving playbooks in to directories.

   Reason for Change(s):
   - New Recorded Future Automated Threat Hunt feature

   Version Updated:
   - This PR only contains new analytic rules

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by RecordedFutureOskbo** [comment]
Finally ready for review!

**Comment by v-prasadboke** [comment]
Hey Thanks @RecordedFutureOskbo, for marking this PR as ready. This PR will be investigated and we will provide you an update by 07 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Thanks for sharing the sample data. Will get back to you by 14 December,2023.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Can you share sample data for detections and hunting queries as well. 
imdns and nThreatIntelligenceIndicator table

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Please shorten the given playbook titles. Limit for playbook title is 45 characters.
`RecordedFuture-HASH-Obs_in_Underground-TIProcessor`
`RecordedFuture-IP-Actively_Comm_C2_Server-TIProcessor`
`RecordedFuture-URL-Recent_Rep_by_Insikt-TIProcessor`
`RecordedFuture-IOC_Enrichment-IP_Domain_URL_Hash`
`RecordedFuture-ActorThreatHunt-IndicatorImport`

Please do check once other Playbook titles as well which are crossing a limit of 45 characters.

**Comment by v-prasadboke** [comment]
> > Hello @RecordedFutureOskbo, Please shorten the given playbook titles. Limit for playbook title is 45 characters. `RecordedFuture-HASH-Obs_in_Underground-TIProcessor` `RecordedFuture-IP-Actively_Comm_C2_Server-TIProcessor` `RecordedFuture-URL-Recent_Rep_by_Insikt-TIProcessor` `RecordedFuture-IOC_Enrichment-IP_Domain_URL_Hash` `RecordedFuture-ActorThreatHunt-IndicatorImport`
> > Please do check once other Playbook titles as well which are crossing a limit of 45 characters.
> 
> We want to deprecate some of those playbooks and if we change name customers will get new templates and the old will just remain as is in current installations. Is there a way to rename playbooks in solutions installations? image

Hello @RecordedFutureOskbo, We have a way to rename the playbook. When we click on create playbook it takes us to a page where we have selection for resource group etc. also we have an option to rename to playbook. 

But anyways these playbooks are going to get deprecated and giving them new title would lead to cause issue to old customers so its ok.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
