### PR TITLE
Set Correct User AGent Strings for Dynatrace Connectors and Playbook templates

### PR DESCRIPTION
**Pull request by keyoke**
Required items, please complete
   
   Change(s):

updated User Agent Strings for Dynatrace Connectors and Playbook templates

   Reason for Change(s):

Set Correct User AGent Strings for Dynatrace Connectors and Playbook templates

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @keyoke, Thanks for raising this PR. This PR will be investigated and will respond back with an update till 24 November, 2023.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @keyoke Can you please share the working and latest images of the Playbooks. 
Thanks.

**Comment by v-prasadboke** [comment]
Hello @keyoke, Please share the above requested artifacts.

**Comment by v-prasadboke** [comment]
Hello @keyoke Please share the requested images

**Comment by keyoke** [comment]
Enrich_DynatraceApplicationSecurityAttackIncident

image

**Comment by v-prasadboke** [comment]
Hello @keyoke, Can you share logic app images for all the playbook also please resolve Validation errors.

**Comment by keyoke** [comment]
> Hello @keyoke, Can you share logic app images for all the playbook also please resolve Validation errors.

should be done

**Comment by v-prasadboke** [comment]
Hello @keyoke, Thanks for sharing the images. Will check it once and get back to you before 21 December, 2023.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
