### PR TITLE
Updated Data Connector code with fix of jsondecoder error and upgraded python version from 3.9 to 3.11 for BitSight

### PR DESCRIPTION
**Pull request by niralishah-crest**
Change(s):
   - Updated Data Connector code.
   - Upgrade python version from 3.9 to 3.11

   Reason for Change(s):
   - to fix checkpoint file corruption issue

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by niralishah-crest** [comment]
@v-shukore Any update on this PR review?

**Comment by v-shukore** [comment]
Hi @niralishah-crest,
As per your PR title, please update the checkpoint solution files. Currently, you have only updated the BitSight solution files. Our team has made changes to the checkpoint solution, so please refer to this PR for your reference.
https://github.com/Azure/Azure-Sentinel/pull/11137
Also, update the version to 3.11 in the `BitSight_API_FunctionApp.json` file and repackage the solution.

**Comment by niralishah-crest** [comment]
@v-shukore This PR id regarding changes done to fix jsondecoder error in BitSight Solution which we have developed earlier. So we have updated files for BitSight Data Connector.
Regarding python version, we have add python packages of 3.11 in Data Connector zip and also updated version in azuredeploy_BitSight_API_FunctionApp.json file

**Comment by v-shukore** [comment]
Hi @niralishah-crest, please share the success running data connector screenshot with us. Thanks..!!

**Comment by niralishah-crest** [comment]
@v-shukore Please find the SS for running function app invocations.
image
image
image

**Review by v-shukore — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
