### PR TITLE
InfobloxNIOS Parser - DHCPAck Fix

### PR DESCRIPTION
**Pull request by elforb**
This change aims to fix the DHCPAck log parsing in the InfobloxNIOS Parser.

Fixes #
  - Modified the regex which parses DHCPAck logs
  - Modified the capture groups used for `Relay` and `LeaseDuration`
  - Update regex in DNSClient Parsing to make view portion optional, to ensure current data can be matched.
- "r-l-e" type of logs raw string field is not starting with ' ':' hence making it as Optional

### CODE REVIEW

**Comment by shainw** [comment]
@acnccd - Can you have a look at this to confirm this change as you originally submitted the parser?

**Comment by acnccd** [comment]
@shainw judging from log sample I found in a screenshot from a link http://www.callevanetworks.com/understanding-infoblox-isc-dhcp-and-abandoned-leases/, the suggested changes would work. If there was sample data with DHCPACK events we could further validate.

**Comment by shainw** [comment]
> @shainw judging from log sample I found in a screenshot from a link http://www.callevanetworks.com/understanding-infoblox-isc-dhcp-and-abandoned-leases/, the suggested changes would work. If there was sample data with DHCPACK events we could further validate.

Agreed, @elforb - can you supply the sample log please?

**Comment by elforb** [comment]
The sample log is as follows:
Jun 4 12:20:09 130.191.200.2 dhcpd[7625]: DHCPACK on 10.130.17.107 to b6:57:72:77:93:cc via eth2 relay 10.130.255.254 lease-duration 28727 (RENEW) uid 01:b6:57:72:77:93:cc

It's also available in the linked issue, #2408

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
