### PR TITLE
Sap Version 2.0.27 

### PR DESCRIPTION
**Pull request by oferInbar**
Required items, please complete
   
   Change(s):
  Version 2.0.27 changes:
1. Added a new workbook "SAP - Security Audit log and Initial Access"
2. Rolled back API version for watchlists to 2021-03-01-preview and added IsDeleted = False
3. added some images

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@aprakash13, Can you please review the Analytic rules, thanks.

**Comment by v-sabiraj** [comment]
@oferInbar, please resolve the conflicts, thanks.

**Comment by v-sabiraj** [comment]
'SAP' is showing as invalid connectorIds. If a new connector is used and already configured in the Portal, please add it's Id to the list in '[ValidConnectorIds.json](https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json)' file.

**Comment by v-sabiraj** [comment]
@oferInbar, can you please resolve the conflicts, and also please resolve the comments that we discussed, thanks.

**Comment by v-spadarthi** [comment]
@oferInbar, can you please resolve the conflicts, and also please resolve the comments suggested by @v-sabiraj

**Comment by v-sabiraj** [comment]
@oferInbar , have you got chance to look into this?

**Comment by v-sabiraj** [comment]
@oferInbar , please on the changes, thanks

**Comment by v-sabiraj** [comment]
@oferInbar, can you please resolve the conflicts?

**Comment by v-sabiraj** [comment]
Hey @oferInbar, will you please have a look into this?

**Comment by v-sabiraj** [comment]
@oferInbar , any update?

**Comment by v-sabiraj** [comment]
> @oferInbar , any update?

@oferInbar, can you please check and move the PR in draft?

**Comment by v-sabiraj** [comment]
@oferInbar, can you please check and update the PR?

**Comment by oferInbar** [comment]
closing this PR as we have released a newer version

**Pull request closed without merging**
