### PR TITLE
SAP Version 2.0.17 (initial)

### PR DESCRIPTION
**Pull request by oferInbar**
SAP Version 2.0.17 (initial)

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for entire solution

   Reason for Change(s):
   - Solution version V2

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@oferInbar : Please resolve the below comments
For workbook Solutions/SAP/Workbooks/SAP - Audit Log Browser.json while deploying in our eco-connector-test environment we got below 
image
For workbook Solutions/SAP/Workbooks/SAP - Initial Access & Attempts to Bypass SAP Security Mechanisms.json while deploying in our eco-connector-test environment we got below 
image
image
image
image
For workbook Solutions/SAP/Workbooks/SAP - Persistency & Data exfiltration.json while deploying in our eco-connector-test environment we got below 
image
image
image
image
image
For workbook Solutions/SAP/Workbooks/SAP - Suspicious Privileges Operations.json while deploying in our eco-connector-test environment we got below 
image
image
image
After deploying main template it got deployed successfully 
image
image
In CreateUI definition it is not showing the Parsers please fix this issue
image

Please resolve the validation checks as well.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Analytic Rules. Thanks!

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Took a quick look at the submitted queries. All the analytical rule in the GitHub repository follows a standard template - starting with 'id' followed by 'name' then 'description' - so on and so forth. Can we please have all the queries organized in a similar fashion. Here is a quick example of the query template structure that I am referring to: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/AccountCreatedDeletedByNonApprovedUser.yaml

Also, the query fields seem to have a lot of carriage return and new lines (\r \n ) that are not needed, and the query field should be presented similar to the example link above.

Please also fix the validation errors.

**Comment by v-mchatla** [comment]
Hi @oferInbar
We wanted to check on the status of PR #5625. PR is pending from more than 30 days. Let us know if any assistance is required for this PR. As per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by oferInbar** [comment]
hi,
since this is a big solution and there were many rejections, we had to revise the package and this takes time. 
it will be a few weeks before we have all rejects handled. if possible please approve so we can have the initial content available for the end user and customer service for the meantime.

thanks,
Ofer

**Comment by NikTripathi** [comment]
@v-spadarthi Please look into this and do the needful.

**Comment by v-spadarthi** [comment]
HI @oferInbar  Could you please fix the validation errors then only we can initiate the approval. Thanks!!

**Comment by v-spadarthi** [comment]
HI @oferInbar Could you please fix the validation errors then only we can initiate the approval. Thanks!!

**Comment by v-spadarthi** [comment]
HI @oferInbar Could you please fix the validation errors then only we can initiate the approval. Thanks!!

**Comment by v-spadarthi** [comment]
HI @oferInbar Could you please fix the validation errors then only we can initiate the approval. Thanks!!

**Comment by v-spadarthi** [comment]
HI @oferInbar Could you please fix the validation errors then only we can initiate the approval. Thanks!!

**Pull request closed without merging**
