### PR TITLE
Semolend snow integration

### PR DESCRIPTION
**Pull request by Sebmolendijk**
Add ServiceNow-Sentinel bi-directional integration via a ServiceNow app (**/Tools/ServiceNow-Sentinel-Sync**).

Folder contains:

- README with detailed installation and configuration
- XML file - the app to be deployed on the ServiceNow platform
- documentation screenshots

The app is installed on the ServiceNow platform and rely on the Sentinel API to keep incidents to sync.
It's already being used internally for some months and by design partners.

Once merged, announcement will be in the following blog post: https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/announcing-microsoft-sentinel-servicenow-bi-directional-sync/ba-p/3037972

Development was done in partnership with PG (Ely Abramovitch).

### CODE REVIEW

**Comment by preetikr** [comment]
Thanks, @Sebmolendijk for this contribution. I think it'd be great to land this as a solution in Content hub. Can we please sync on this? You can reach out to me at preetikr@microsoft.com for next steps + user experience aspects. Thanks.

**Comment by Sebmolendijk** [comment]
> Thanks, @Sebmolendijk for this contribution. I think it'd be great to land this as a solution in Content hub. Can we please sync on this? You can reach out to me at [preetikr@microsoft.com](mailto:preetikr@microsoft.com) for next steps + user experience aspects. Thanks.

Hi @preetikr ,

I sent you an email. If you want, ping me on Teams once you're online to discuss that. 

Thanks!

**Comment by v-sabiraj** [comment]
Hey @Sebmolendijk, can we take this forward or should we close this?

**Comment by vmanojreddy** [comment]
Hey @Sebmolendijk, can we take this forward or should we close this?

**Comment by Sebmolendijk** [comment]
@v-sabiraj as we're working directly with Preeti and team to have the app published in another way, we can close this PR.

**Pull request closed without merging**
