### PR TITLE
Tenable Playbooks

### PR DESCRIPTION
**Pull request by vu-socprime**
Changes:
   - added Tenable Platform API Logic Apps Custom connector
   - added Tenable Vulnerability Management API Logic Apps Custom connector
   - added Tenable-EnrichIncidentWithAssetsInfo playbook
   - added Tenable-EnrichIncidentWithVulnInfo playbook
   - added Tenable-LaunchScan playbook

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @vu-socprime - Can you please make following changes. Thanks in advance

1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example 
```
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
```
3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)

**Comment by v-mchatla** [comment]
Hi @vu-socprime 
We wanted to check on the status of PR #5566. PR is pending from more than 28 days. Let us know if any assistance is required for this PR. As per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by vu-socprime** [comment]
> Hi @vu-socprime
> We wanted to check on the status of PR #5566. PR is pending from more than 28 days. Let us know if any assistance is required for this PR. As per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

Hi @v-mchatla @anki-narravula 
Playbooks require some updates and they are still under development.

**Comment by v-spadarthi** [comment]
Hi @vu-socprime,
We wanted to you know any ETA for this ?

**Comment by NikTripathi** [comment]
HI @vu-socprime You can move this PR into draft and reopen once it is ready for review.

**Comment by v-sabiraj** [comment]
Hey @vu-socprime, this Pr is in draft, can you please check and make it open if needed, thanks.

**Comment by vu-socprime** [comment]
> Hey @vu-socprime, this Pr is in draft, can you please check and make it open if needed, thanks.

Hi, @v-sabiraj, I will finish some updates and then open PR, thanks.

**Comment by v-sabiraj** [comment]
> > Hey @vu-socprime, this Pr is in draft, can you please check and make it open if needed, thanks.
> 
> Hi, @v-sabiraj, I will finish some updates and then open PR, thanks.

Ok sure, @vu-socprime please let us know once done.

**Comment by vu-socprime** [comment]
> Hi @vu-socprime - Can you please make following changes. Thanks in advance
> 
> 1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
> 2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example
> 
> ```
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
> ```
> 
>  3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
> 4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
> 5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)

@anki-narravula Done

**Comment by vu-socprime** [comment]
> > > Hey @vu-socprime, this Pr is in draft, can you please check and make it open if needed, thanks.
> > 
> > 
> > Hi, @v-sabiraj, I will finish some updates and then open PR, thanks.
> 
> Ok sure, @vu-socprime please let us know once done.

@v-sabiraj Done

**Comment by v-spadarthi** [comment]
@v-sabiraj : Please have a look and provide an update

**Comment by v-sabiraj** [comment]
@anki-narravula, can you please review this, thanks.

**Comment by v-spadarthi** [comment]
@anki-narravula, can you please review this, thanks.

**Review by manishkumar1991 — APPROVED** [review]
Changes suggested by anki , is done by soc, hence approving

**Review by anki-narravula — APPROVED** [review]

**Comment by v-sabiraj** [comment]
Merging this as already approved by @anki-narravula, thanks.

**Pull request merged**
