### PR TITLE
Corrects typo in workbook.

### PR DESCRIPTION
**Pull request by Korving-F**
This PR corrects a minor typo in the insecure protocols workbook template.
   
   Change(s):
   - Minor typo fix

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @Korving-F, value for "fromTemplateId" must be other than "sentinel-UserWorkbook". Please update it, thanks.

**Comment by v-sabiraj** [comment]
@Korving-F ,please add workbook metadata file, thanks.

**Comment by Korving-F** [comment]
@v-sabiraj: do you mean a version update to the following section in WorkbooksMetadata.json?
```json
  {
    "workbookKey": "InsecureProtocolsWorkbook",
    "logoFileName": "Microsoft_logo.svg",
    "description": "Gain insights into insecure protocol traffic by collecting and analyzing security events from Microsoft products.\nYou can view analytics and quickly identify use of weak authentication as well as sources of legacy protocol traffic, like NTLM and SMBv1.\nYou will also have the ability to monitor use of weak ciphers, allowing you to find weak spots in your organization's security.",
    "dataTypesDependencies": [ "SecurityEvent", "Event", "SigninLogs" ],
    "dataConnectorsDependencies": [ "SecurityEvents", "AzureActiveDirectory", "WindowsSecurityEvents" ],
    "previewImagesFileNames": [ "InsecureProtocolsWhite1.png", "InsecureProtocolsBlack1.png", "InsecureProtocolsWhite2.png", "InsecureProtocolsBlack2.png" ],
    "version": "2.0",
    "title": "Insecure Protocols",
    "templateRelativePath": "InsecureProtocols.json",
    "subtitle": "",
    "provider": "Microsoft"
  },
```

**Comment by v-sabiraj** [comment]
> @v-sabiraj: do you mean a version update to the following section in WorkbooksMetadata.json?
> 
> ```json
>   {
>     "workbookKey": "InsecureProtocolsWorkbook",
>     "logoFileName": "Microsoft_logo.svg",
>     "description": "Gain insights into insecure protocol traffic by collecting and analyzing security events from Microsoft products.\nYou can view analytics and quickly identify use of weak authentication as well as sources of legacy protocol traffic, like NTLM and SMBv1.\nYou will also have the ability to monitor use of weak ciphers, allowing you to find weak spots in your organization's security.",
>     "dataTypesDependencies": [ "SecurityEvent", "Event", "SigninLogs" ],
>     "dataConnectorsDependencies": [ "SecurityEvents", "AzureActiveDirectory", "WindowsSecurityEvents" ],
>     "previewImagesFileNames": [ "InsecureProtocolsWhite1.png", "InsecureProtocolsBlack1.png", "InsecureProtocolsWhite2.png", "InsecureProtocolsBlack2.png" ],
>     "version": "2.0",
>     "title": "Insecure Protocols",
>     "templateRelativePath": "InsecureProtocols.json",
>     "subtitle": "",
>     "provider": "Microsoft"
>   },
> ```

@Korving-F ,yes need to update the version in WorkbooksMetadata.json

**Review by v-sabiraj — APPROVED** [review]

**Pull request merged**
