### PR TITLE
SentinelCentral updated Workbook

### PR DESCRIPTION
**Pull request by clivewatson**
New version

   Required items, please complete
   
   Change(s):
   - SKU info added in [Ingestion] tab, and Content Hub info added from within the [Tables] tab.

   Reason for Change(s):
   - Updates

   Version Updated:
   - 2.3.0

   Testing Completed:
   - Yes

### CODE REVIEW

**Review by clivewatson — COMMENTED** [review]
fix, remove invalid Resource

**Comment by v-prasadboke** [comment]
Hello @clivewatson Please add logo and working images of the workbook to this location 
https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks/Images
Thanks.

**Comment by CliveWatsonQC** [comment]
Hello, there is no logo, and the screenshots are unchanged: https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/Images/Preview/SentinelCentralWhite.png  

I think the error is refencing a file in another solution.

**Comment by v-prasadboke** [comment]
Hello @clivewatson You added the metadata to an outdated Workbooksmetadata file. I copied your metadata and added it to the latest one which I committed to this PR. 
Also as this Workbook is standalone I have also added the entities which are needed for the standalone workbook. 
Please fill details for the fields which are marked with --- from line no. 6690.
Please do share sample data to test the workbook. 
Thanks.

**Review by CliveWatsonQC — APPROVED** [review]

**Comment by CliveWatsonQC** [comment]
I dont have the ability to EDIT the file anymore to make these changes, how do I enable that?

**Comment by v-prasadboke** [comment]
Hello @clivewatson dont know why but even after upgrading the version of workbook a check is failing for the same. 
This is still being investigated, Will update you about the same before 11 October, 2023.

**Comment by CliveWatsonQC** [comment]
Thank you @v-prasadboke

**Comment by v-prasadboke** [comment]
Hello @clivewatson, Can you share the sample data to test the workbook. 
Thanks.

**Comment by CliveWatsonQC** [comment]
I can show you test results, but it needs multiple Workspaces and Data Tables to function - you have to have the systems in place to test.  You could run it against two+ test Microsoft Sentinel workspaces you have acess to. 

I think the instructions need an update, these are all new asks I haven't had to do before: https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks#how-to-update-an-existing-workbook

**Comment by v-prasadboke** [comment]
Hi @clivewatson sorry for the inconvenience but the validation check is failing for Version increment. 
I'll update you today by EOD for the same.

**Comment by v-prasadboke** [comment]
Hello @clivewatson, validation have passed. Continuing with my investigation. Thanks.
And I have more than 2 accessible workspace. Still you can share the working images of workbook.

**Comment by CliveWatsonQC** [comment]
Hi, here is the screenshot, with PII removed.

image

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
