### PR TITLE
Add solution: Dynamics 365 data connector

### PR DESCRIPTION
**Pull request by kingwil**
Required items, please complete
   
   Change(s):
   - Addition of new solution package for Dynamics 365 data collector
   
   Reason for Change(s):
   - Publish 1P data connector

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @kingwil,
Please correct the base path in data file to remove the Data Connector failed validations,
the correct path should "Github/Azure-Sentinel/Solutions/Dynamic 365"
image

**Comment by kingwil** [comment]
> Hello @kingwil, Please correct the base path in data file to remove the Data Connector failed validations, the correct path should "Github/Azure-Sentinel/Solutions/Dynamic 365" image

Hi @v-prasadboke . Please confirm, updated the path as suggested.

**Comment by v-prasadboke** [comment]
Hello @kingwil try removing the slash ' / ' in the data connector path before the data connector in the input file

**Comment by kingwil** [comment]
> Hello @kingwil try removing the slash ' / ' in the data connector path before the data connector in the input file

hi @v-prasadboke I tried this , and a few other variations on it without success.

**Comment by v-prasadboke** [comment]
Hello @kingwil schema was missing for dynamics 365 acitivty for the data connector 
that was the reason data connector validation was failing 
i have raised a PR #7386  for the addition of schema to the utility folder 
let that pr get merged and we will check into this then

**Comment by v-prasadboke** [comment]
Hello @kingwil Mine PR is merged #7386 for the schema 
now try updatting your branch from the master and re run the checks

**Comment by v-prasadboke** [comment]
### Changes in CreateUIdefination 
Screenshot 2023-02-22 152225

Hello @kingwil please correct the **'' /n ''** with **'' \n ''** marked in white and add " \n\n " between costs: and a marked in blue, It should be like " costs: \n\n a "

Screenshot 2023-02-22 152533
And please the change selected text with 

This solution installs the data connector for ingesting Dynamics 365 CRM logs into Microsoft Sentinel. After installing the solution, configure and enable this data connector by following guidance in Manage solution view.

**Comment by v-prasadboke** [comment]
all looks good

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
