### PR TITLE
Re-branded the "Cyberpion" to "IONIX"

### PR DESCRIPTION
**Pull request by yotam-ionix**
Change(s):
   - Rebranded the "Cyberpion" to "IONIX". This includes;
   - Folder change (Cyberpion to IONIX)
   - Logo changes
   - Analytic Rules name and description change (version up to 1.0.1)
   - Data Connector title, description, links, publisher and subscription name (data types and id stay the same) (version up to 1.1.0)
   - Workbook title change (version up to 1.1.0)
   - Solution version update to 3.0.0, and metadata updated to reflect new provider, mail, link, etc..

   Reason for Change(s):
   - Company re-branding. 

   Version Updated:
   - Yes
   - As specified above: Workbook (1.0.0 -> 1.1.0), Analytic Rule (1.0.0 -> 1.0.1), Connector (1.0.0 -> 1.1.0) 

   Testing Completed:
   - Yes (no change to data)

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes (seems to have passed)

### CODE REVIEW

**Comment by yotam-ionix** [comment]
@microsoft-github-policy-service agree [company="IONIX"]

**Comment by yotam-ionix** [comment]
@microsoft-github-policy-service agree company="IONIX"

**Comment by v-atulyadav** [comment]
Hi @yotam-ionix, 
Thank you for raising Pull Request with us! We will review the Pull Request and get back to you by 21 Aug 2023.

**Comment by v-atulyadav** [comment]
Hi @yotam-ionix, 
This solution's contents look good, but it would be nice if you could include released notes with it. Please refer below guidance for the same.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

**Comment by yotam-ionix** [comment]
If I already have your attention, I just wanted to ask why we don't see the "Next Steps" tab in our connector page (to view the sample queries)? We didn't make any changes to the connector and suddenly they stopped appearing.

image

Thanks!

**Comment by v-atulyadav** [comment]
Hi @yotam-ionix, 
For all data connectors, this tab has been completely removed from content hub. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by yotam-ionix** [comment]
Hey, I noticed I forgot to add the new createUiDefinition.json to the zip file (3.0.0.zip).
I'll open a new PR updating the zip.

**Pull request merged**
