### PR TITLE
ADOMaliciousToolingDetections1

### PR DESCRIPTION
**Pull request by zanecop**
Change(s):
   - Added a new Azure DevOps Auditing detection for some nearly released tooling.

   Reason for Change(s):
   - Newly released tooling targeting Azure DevOps

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - in process.

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @zanecop, thanks for raising this PR, we will review this PR by 20 Nov 2023.

**Comment by v-atulyadav** [comment]
Hi @zanecop, 
relevantTechniques is missing from rule. Please refer to the links below for the Query Style Guide and the Tactics and Techniques relation for your reference.
https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide
https://attack.mitre.org/versions/v11/matrices/enterprise/

**Comment by v-prasadboke** [comment]
Hello @zanecop, Can you please respond to the above comments.

**Comment by v-rbajaj** [comment]
Hi @zanecop, can you provide an update on the above comments?

**Comment by v-rbajaj** [comment]
Hi @zanecop, can you please provide an update on above comment?

**Comment by zanecop** [comment]
There isn't a Mitre technique for using malicious tooling against SCM.

Mitre specifically does not cover SaaS platforms like Azure DevOps, what technique should I use?

image

**Review by v-rbajaj — APPROVED** [review]

**Pull request merged**
