### PR TITLE
Updated last pull time from 90 to 30 days

### PR DESCRIPTION
**Pull request by syed-loginsoft**
…onal

   Required items, please complete
   
   Change(s):
   - Updated pull from days to 30 from 90

   Reason for Change(s):
   - Pulling from 90 days returns records that are no longer relavant

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

image

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @syed-loginsoft, Thank you for raising this PR. This PR will be investigated and we will update you about the same before 19 April, 2024.

**Comment by v-prasadboke** [comment]
Hello @syed-loginsoft, I have updated the zip with init.py file

Can you please once share working images of function app.

**Comment by v-prasadboke** [comment]
Hello @syed-loginsoft, We are waiting for your feedback

**Comment by syed-loginsoft** [comment]
Please find the screenshots
image

image

image

image

**Pull request merged**
