### PR TITLE
Users/demehra/update skiplist

### PR DESCRIPTION
**Pull request by devikamehra**
Adding skip items of ASIM Network detection

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @devikamehra,
Please resolve the conflicts.
Thanks

**Comment by v-mchatla** [comment]
Hi @devikamehra,
Please resolve the conflicts.
Thanks

**Comment by v-mchatla** [comment]
Hi @devikamehra,
Can you please resolve the conflicts. If you need some time to work on it, please move it to draft and resume once you get time.
Thanks

**Comment by devikamehra** [comment]
This is not required any longer.

**Pull request closed without merging**
