### PR TITLE
Remove unused labraries in requirements.txt and add links

### PR DESCRIPTION
**Pull request by FortiNDR-Integration**
Required items, please complete
   
   Change(s):
   - Remove unused libraries in requirements.txt
   - Add links for parser and deploy

   Reason for Change(s):
   - Some libraries are not used
   - There are missing links as they are links to files in Azure Sentinel repo

   Version Updated:
   - no

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by FortiNDR-Integration** [comment]
Hi, from the last PR, we got feedback:https://github.com/Azure/Azure-Sentinel/pull/9802#issuecomment-1916315298, about missing Python libraries, could you please be more specific about what is missing?

**Comment by v-prasadboke** [comment]
Hello @FortiNDR-Integration, Thanks for raising this PR. Will investigate this and update you about the same before 01 February, 2024.

**Comment by v-prasadboke** [comment]
Hello @FortiNDR-Integration, just got to know this solution won't be published by Microsoft's Partner center.
Please update publisher id as per your partner center id

**Comment by FortiNDR-Integration** [comment]
> Hello @FortiNDR-Integration, just got to know this solution won't be published by Microsoft's Partner center. Please update publisher id as per your partner center id

Hello @v-prasadboke , we have updated the publisher id and also the support information, please review, thanks

**Comment by FortiNDR-Integration** [comment]
@v-prasadboke We have also updated the logo for the solution, but the auto validation failed, could you please help with it?

**Comment by v-prasadboke** [comment]
Also this zip is missing with python packages please add them

**Comment by FortiNDR-Integration** [comment]
> Also this zip is missing with python packages please add them

Hi @v-prasadboke could you be more specific about what is missing? I saw this comment in the last PR and couldn't find exactly what you are talking about.

**Comment by v-prasadboke** [comment]
Can we schedule a call for the same for tomorrow i.e 06 February, 2024. I work in IST time zone. Please let me know your availability and Time zone so we can plan for the same. 
Please share your mail id too so I can send you an invite for the call.

**Comment by FortiNDR-Integration** [comment]
> Can we schedule a call for the same for tomorrow i.e 06 February, 2024. I work in IST time zone. Please let me know your availability and Time zone so we can plan for the same. Please share your mail id too so I can send you an invite for the call.

HI @v-prasadboke, let's have a call,  I work in EST, my email is sxiuyang@fortinet.com. I'm available all day 9am-5pm est. Thanks

**Comment by v-prasadboke** [comment]
Hello @FortiNDR-Integration, Is 8:30 pm IST comfortable with you. It will be 10:00 am EST for 07 February, 2024.

**Comment by FortiNDR-Integration** [comment]
> Hello @FortiNDR-Integration, Is 8:30 pm IST comfortable with you. It will be 10:00 am EST for 07 February, 2024.

Hi @v-prasadboke , that works for me, please send me an invitation for it to sxiuyang@fortinet.com and emesabarrameda@fortinet.com. Thank you for your help.

**Comment by v-prasadboke** [comment]
C:\GitHub\Azure-Sentinel\Solutions\Cloudflare\Data Connectors\CloudflareConn.zip\.python_packages\lib\site-packages

**Comment by FortiNDR-Integration** [comment]
Hi @v-prasadboke , thanks for the call and the explanations, we have updated the zip file for the data connector and added the Python libraries, please review again.

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
