### PR TITLE
Update Connector_Syslog_CiscoMeraki.json to include firewall logs

### PR DESCRIPTION
**Pull request by tduarte14**
In Firmware MX18.101 and newer, the syslog messages for "flows" has been changed to "firewall", "vpn_firewall", "cellular_firewall" or "bridge_anyconnect_client_vpn_firewall" depending on which rule was matched, so added firewall filter to the instructions.

   Required items, please complete
   
   Change(s):
   - included filtering for "firewall" messages since they are an update on the "flows" events.

   Reason for Change(s):
   - In Firmware MX18.101 and newer, the syslog messages for "flows" has been changed to "firewall", "vpn_firewall", "cellular_firewall" or "bridge_anyconnect_client_vpn_firewall" depending on which rule was matched, so added firewall filter to the instructions. See https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Server_Overview_and_Configuration

   Version Updated:
   - Not applicable

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @tduarte14,
Please repackage this solution using v3 tool. Thanks

**Comment by tduarte14** [comment]
Hi @v-atulyadav why does this need to be repackaged that way?
I'm already wasting my time sharing a fix for something that is not properly done and you want to give me more work on my side?

**Comment by v-atulyadav** [comment]
Hi @tduarte14,
Any change made in the connector file does not appear in the solution unless it is repackaged. I understand and appreciate your efforts towards this fix. We will repackage this solution and raise a PR for it. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by tduarte14** [comment]
Thank you

**Pull request merged**
