### PR TITLE
fix bug with 500 column limit

### PR DESCRIPTION
**Pull request by KateShapovalova**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by NikTripathi** [comment]
@KateShapovalova I think we need to modify the parser as well accordingly. What do you think?

**Comment by KateShapovalova** [comment]
> @KateShapovalova I think we need to modify the parser as well accordingly. What do you think?

@NikTripathi there is no need because what was parsed wasn't changed.

**Comment by NikTripathi** [comment]
Hi @KateShapovalova we are getting an error as below,
"Result: Failure Exception: TypeError: argument of type 'NoneType' is not iterable Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 46, in main process_events(stream_client, StreamOcid, cursor, sentinel_connector, start_ts) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 123, in process_events if "current" in event["data"]["stateChange"]:"

I think we are not handling all the formats.
Can you please rectify it so that it can handle all the format?
Thanks

**Comment by KateShapovalova** [comment]
@NikTripathi, ok, can you please share a sample json that I can use to reproduce the bug?

**Comment by v-atulyadav** [comment]
Hi @KateShapovalova , can you please provide sample json asked by @NikTripathi

**Comment by KateShapovalova** [comment]
@NikTripathi, I added raw sample data in "Solutions\Oracle Cloud Infrastructure\Data Connectors\OCI_Logs_CL.json", you can check with it.

**Comment by NikTripathi** [comment]
Hi @KateShapovalova Attaching the json format we are receiving.
[OCISampleJson.docx](https://github.com/Azure/Azure-Sentinel/files/9661613/OCISampleJson.docx)

**Comment by v-atulyadav** [comment]
Hi @KateShapovalova Attaching the json format we are receiving.
[OCISampleJson.docx](https://github.com/Azure/Azure-Sentinel/files/9661613/OCISampleJson.docx)

**Comment by v-spadarthi** [comment]
@KateShapovalova :  
Sample data ingested 
image
After testing function app we are getting below error please fix it
image

**Comment by KateShapovalova** [comment]
@NikTripathi, @v-atulyadav, @v-spadarthi I added updated sample data that the python script ingests to Sentinel. You can find it by the path: "Solutions\Oracle Cloud Infrastructure\Data Connectors\OCI_Sample_Logs_CL.json". Please, ingest this data to Sentinel and test.

**Comment by v-atulyadav** [comment]
Hi @KateShapovalova  , we are looking into this.

**Comment by v-atulyadav** [comment]
Hi @KateShapovalova, we are checking on this and soon will give you feedback regarding this. Thanks

**Comment by v-atulyadav** [comment]
Waiting on Customer's response.

**Comment by v-atulyadav** [comment]
We are waiting for the customer's response.

**Comment by v-atulyadav** [comment]
Currently, we are waiting for the customer's response.

**Comment by v-atulyadav** [comment]
The customer has yet to respond.

**Pull request closed without merging**
