### PR TITLE
Updated Bitwarden publisher, offer id's and solution description

### PR DESCRIPTION
**Pull request by mzieniukbw**
Required items, please complete
   
   Change(s):
   - Updated solutions: publisher id, offer id, description

   Reason for Change(s):
   - Consistency with the yet to be published offer

   Version Updated:
   - No

   Testing Completed:
   - No

   Checked that the validations are passing and have addressed any issues that are present:
   - No

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-shukore** [comment]
Hi @mzieniukbw,
Please update the publisher ID in the SolutionMetadata file as mentioned in Partner Center. In Partner Center, you have mentioned `8bit-solutions-llc`, but in the SolutionMetadata file, it is `bitwarden-inc`.

Also, please confirm that you mentioned the category as `Security - Threat Protection` in the SolutionMetadata file, but you haven't selected this security category in Partner Center.
image

Note: please repackage the solution again after all these changes.

**Comment by mzieniukbw** [comment]
@v-shukore I have updated the domain categories.
We have also updated the publisher id and categories in Partner Center, which should now match this PR.

**Comment by mzieniukbw** [comment]
@v-shukore Apologies, it looks like we updated publisher name, not id, which does not seem to be editable in Partner Center.
Since it's not possible to update publisher id, we will have to start the process in Partner Center from scratch - i will let you know when finished.

**Comment by mzieniukbw** [comment]
@v-shukore I have updated the domain categories and publisher id.
We decided not to change the publisher id in Partner Center, since we already offer other Microsoft solutions under that id.

**Review by v-shukore — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
