### PR TITLE
Update NOBELIUM_IOCsMay2021.yaml

### LINKED ISSUE #7885: NOBELIUM - Domain, Hash and IP IOCs - May 2022 should be fixed or removed from repo
**Describe the bug**
The rule Sentinel Rule [NOBELIUM - Domain, Hash and IP IOCs - May 2021](https://github.com/Azure/Azure-Sentinel/blob/c6dce9c3aa4d4b4d02423ac4eb5a6b677a39e432/Solutions/Legacy%20IOC%20based%20Threat%20Protection/Analytic%20Rules/NOBELIUM_IOCsMay2021.yaml) references an external watchlist of CSVs which, when requested, returns a 404. 

This blocks execution of of the rule on a customer's Sentinel instance with the following error from the SentinelHealth table:

```
"StoragePathNotFound","Description":"The query referred to a storage path that was not found.
```

The reference for the unavailable CSV can be seen on line 98:
```
  [@"https://raw.githubusercontent.com/microsoft/mstic/master/Indicators/May21-NOBELIUM/May21NOBELIUMIoCs.csv"] with (format="csv", ignoreFirstRecord=True);

```

**To Reproduce**
1. Attempt to deploy *NOBELIUM - Domain, Hash and IP IOCs - May 2021* as an analytic rule to Sentinel
2. The validation wizard will fail because it cannot contact the external CSV referenced at line 98. 

**Expected behavior**
The rule wizard should complete without error. The rule should execute on it's schedule without populating errors in the SentinelHealth table. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Version 112.0.1722.48 (Official build) (64-bit)

**Additional context**
Rule should be rectified to include an updated CSV location or removed from this repo.

### PR DESCRIPTION
**Pull request by samikroy**
Seems a recent change caused this
Bug fix #7885 

image

@best-geek

Please have a look at this if this fits your need

https://raw.githubusercontent.com/microsoft/mstic/master/Indicators/May21-MidnightBlizzard/May21MidnightBlizzardIoCs.csv

@v-amolpatil , @v-vdixit , @v-rbajaj - Request your review and merger

### CODE REVIEW

**Comment by best-geek** [comment]
Hi @samikroy ! 

Yes, this looks like it resolve the runtime issue of the rule. I can see the merge is blocked currently. Can you confirm once the merge goes through, it will be pushed to Content Hub in Sentinel? 

Kind Regards,
N

**Comment by v-sabiraj** [comment]
Hi @samikroy / @best-geek, I have raised pr for same reason, can you please check this. https://github.com/Azure/Azure-Sentinel/pull/7901

**Comment by v-rbajaj** [comment]
Hi @samikroy, Can you please have a look at @v-sabiraj's comment. 
Can you please resolve the conflicts ?

**Comment by samikroy** [comment]
> Hi @samikroy, Can you please have a look at @v-sabiraj's comment. Can you please resolve the conflicts ?

@v-rbajaj - conflicts removed. Now, this PR stands with no change due to the PR #7901 merger to the main.

**Pull request closed without merging**
