### PR TITLE
Creating Azure Purview Solution. Added Workbook, Data Connector, and …

### PR DESCRIPTION
**Pull request by rheabansal**
…Analytic Rules. Uploaded Sample Data

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytic rules. Thanks.

**Review by NikTripathi — CHANGES_REQUESTED** [review]
Hi @rheabansal , Can you please provide sample data in .csv or .json format.

**Review by aprakash13 — COMMENTED** [review]
Queries look good. Feel free to merge once the validation errors are addressed and other components look good.

**Comment by rheabansal** [comment]
> Hi @rheabansal , Can you please provide sample data in .csv or .json format.

Hi @NikTripathi Updated the file to be a .csv

**Review by NikTripathi — APPROVED** [review]
Data connector looks good.

**Comment by rheabansal** [comment]
hey @aprakash13 @NikTripathi ! Would you be able to help with the Validation failures in both the Detections and Data Connector? 
Thank you for all the help so far!

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
