### PR TITLE
Hunting queries windows event batch7

### PR DESCRIPTION
**Pull request by yaelrbergman**
Change(s):
Add Windows Event Data to the following Hunting Queries:

Hunting   Queries/SecurityEvent/RareProcbyServiceAccount.yaml
Hunting Queries/SecurityEvent/RareProcess_forWinHost.yaml
Hunting Queries/SecurityEvent/RareProcessWithCmdLine.yaml
Hunting Queries/SecurityEvent/CustomUserList_FailedLogons.yaml

Reason for Change(s):
Part of adding Windows Event data source project

Version Updated:
No
Testing Completed:
Yes
Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Hunting Queries. Thanks.

**Comment by vmanojreddy** [comment]
@oshezaf  Please review Hunting Queries. Thanks!!!

**Comment by v-mchatla** [comment]
Hi @oshezaf
Can we close this and reopen whenever required as you have labelled it as differed.
Thanks

**Comment by oshezaf** [comment]
Done

**Pull request closed without merging**
