### PR TITLE
create LastPass Solution

### PR DESCRIPTION
**Pull request by ThijsLecomte**
Fixes #
Copy of PR 
@v-jayakal, @NikTripathi 

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by ThijsLecomte** [comment]
Only issue is that there is a validation issue on the watchlist, but the watchlist is a part of this PR?

Can we merge with this error? If we can't, I need to remove this rule

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytic rules. Thanks.

**Comment by ThijsLecomte** [comment]
@NikTripathi  please know that Analytic rules have already been reviewed in this PR: https://github.com/Azure/Azure-Sentinel/pull/3402#issuecomment-990646567

**Comment by ThijsLecomte** [comment]
reopening as closing was a mistaken...

**Comment by v-rucdu** [comment]
We have sign-off from Ajeet Prakash in old [PR](https://github.com/Azure/Azure-Sentinel/pull/3402). 
The error is related to watchlist hence merging the PR

**Comment by yaronMSFT** [comment]
@ThijsLecomte , @v-rucdu , please add a [validation exception](https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/SkipValidationsTemplates.json)

**Comment by shainw** [comment]
@v-rucdu - not including an exception breaks the build validations for any future PRs.  Please do not ignore the validation and bypass them.

**Comment by ThijsLecomte** [comment]
@yaronMSFT , @v-rucdu had no idea this was a thing...
I have added it through another PR: https://github.com/Azure/Azure-Sentinel/pull/3714

**Comment by shainw** [comment]
@ThijsLecomte - no worries, I already added it in #3713, I have closed your PR.  Make sure you sync master. :)

**Pull request merged**
