### PR TITLE
Tanium Solution 2.0.0

### PR DESCRIPTION
**Pull request by sdball**
Change(s):
   - Update playbooks in solution to be self contained logic apps
   - Update Workbook with additional visualizations

   Reason for Change(s):
   - Self contained logic apps mean we no longer need our customers to setup an additional VM to handle API communications

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Package build shows all green for checks

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@sdball : Please address below comments
While deploying Create UI definition we could see playbooks 7 but in solution folder we could see 6
image
image
In CreateUI definition Logo should be referred from Logos folder (https://github.com/Azure/Azure-Sentinel/tree/b4a26ac37fae3128e43b887e5c72c93562139ead/Logos) 
Please provide the solution Input file for your reference(https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution)  and keep it in under Data folder
please follow the folder structure like this(https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/OracleWebLogicServer) to create the solution
After deploying workbook we got below errors pleas fix
In Threat Response Section 
image
image
In Comply section we are getting below
image

while checking Workbook Queries, we got below error please fix
image

**Comment by sdball** [comment]
> While deploying Create UI definition we could see playbooks 7 but in solution folder we could see 6
> image
> image

You are comparing the new 1.0.10 Tanium solution build with the master branch. You need to compare to the PR branch e.g.

image

> In CreateUI definition Logo should be referred from Logos folder (https://github.com/Azure/Azure-Sentinel/tree/b4a26ac37fae3128e43b887e5c72c93562139ead/Logos)

Done. Now using

```
"Logo": "<img src=\"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Logos/Tanium.svg\" width=\"75px\" height=\"75px\">",
```

> Please provide the solution Input file for your reference(https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution) and keep it in under Data folder

Done. We now have `Solutions/Tanium/Data/Solution_Tanium.json`

> please follow the folder structure like this(https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/OracleWebLogicServer) to create the solution

Done.

> After deploying workbook we got below errors pleas fix In Threat Response Section image image

Our workbook requires custom data being sent to Log Analytics from a Tanium Server and does not function on its own.

> In Comply section we are getting below image

Same issue here: the workbook requires a custom data table.

> while checking Workbook Queries, we got below error please fix image

Same issue here as well: the workbook requires custom data.

**Comment by ajcollins0** [comment]
I previously added sample data in this folder for your reference @v-spadarthi: 
(there are multiple CSV file with our data as examples found in this folder - I posed two examples below) 
https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/TaniumThreatResponse_CL.csv
https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/TaniumMainAsset_CL.csv

**Comment by NikTripathi** [comment]
HI @sdball , Every time we are deploying the main template we are getting SKU quota exceed limit. 
image
I created a new resource group as well but this issue is still there. Is it expected or do we need to make any change?
Thanks

**Comment by sdball** [comment]
@NikTripathi Hello! Yes this is expected if you don't use the same integration account for each playbook. You can either use the same integration account for each playbook or switch to one of the paid integration account tiers.

**Comment by rushriva** [comment]
@sdball - Hello Stephen, Deploy to Azure buttons are not present. Each Readme must have "Deploy to Azure" and "Deloy to Azure Gov" buttons.  Playbook screenshots are also missing. Please do the needful. 
Thanks, 
Ruchir Shrivastava

**Comment by sdball** [comment]
@rushriva Done! The README files for the playbooks now have the "Deploy to Azure" and "Deploy to Azure Gov" buttons and have screenshots.

**Comment by v-spadarthi** [comment]
@sdball : While checking on workbook we are getting below errors please fix even though we ingested sample data also
In Threat Response section we are getting below error
image
It is expecting  timestamp_t but sample data is there in string format 
image
In Patch Section we are getting below error
image
image
I didn't seen any sample data for  below tables 
TaniumHighUptime_CL
TaniumPatchListCompliance_CL
TaniumPatchListApplicability_CL

**Comment by sdball** [comment]
@v-spadarthi I'll track down the required updates to our custom logs tables.

Is there a way to describe per-solution parameters vs per-playbook parameters? It would be a nicer experience for users if they only had to paste in their server hostname and api token once instead of per playbook.

And is there a better way to use integration accounts? Our playbooks need an integration account to run inline JavaScript but I don't want users to have to create one per playbook. I've seen mixed results when importing the solution and declaring the same integration account: sometimes it works, sometimes it fails validation.

**Comment by sdball** [comment]
@v-spadarthi Can you point to docs or references for properly providing a `Timestamp_t` in a CSV of sample data? I've through through other existing samples and found mixed results e.g.`ZimperiumMitigationLog_CL.csv`, `Darktrace_IngestedLogs.csv` provide the data as we do while `BetterMTDIncidentLog_CL.csv` provides dates in the CSV as the following format "2020-08-10T09:01:35.855Z"

**Comment by sdball** [comment]
Exporting our current `TaniumThreatResponse_CL` data outputs a CSV file with the dates formatted as we've given. e.g.

"9/8/2022, 1:03:26.000 PM"

**Comment by sdball** [comment]
I've added three new sample data CSVs for those missing tables. I'm happy to revise our data as needed to fit required formats but I am not sure how to proceed there.

**Comment by v-spadarthi** [comment]
@sdball : Thanks for sharing the missing sample data after ingestion Patch section is working fine
image
But still Threat response section getting an error could you please provide us the sample data for TaniumThreatResponse_CL in .json format 
image
image

**Comment by sdball** [comment]
@v-spadarthi Thank you for the update! I've added a re-export of our TaniumThreatResponse_CL table in the hopes that it was actually something wrong with the file. I've also added a JSON version but I had to transform that myself locally as I did not find a way to export logs in JSON format.

For reference here's how those two queries look with our current data

intel-names-over-time

threat-response-alerts-by-process-name

**Review by shainw — COMMENTED** [review]
The Analytic Rule changes is approved, just a Description change.

**Comment by v-spadarthi** [comment]
@sdball : Thanks for providing the sample data and workbook looks good
Could you please update the package with V2 version (2.0.0). Thanks!!

**Comment by sdball** [comment]
@v-spadarthi Sorry can you clarify. Do you mean you'd like us to update our Tanium Solution version to 2.0.0? Or that we need to use Create-Azure-Sentinel-Solution/V2?

**Comment by v-spadarthi** [comment]
@sdball : Package should be used to Create-Azure-Sentinel-Solution/V2 and create a package. Thanks!!

**Comment by sdball** [comment]
@v-spadarthi Ok will do! Thanks for all of your help on this.

**Comment by sdball** [comment]
I've rebased this branch with upstream master to ensure I had the latest V2 tooling and built Solutions/Tanium using V2.

**Comment by sdball** [comment]
@v-spadarthi Unfortunately the package files created by the V2 process seem to be somewhat broken.

The `createUiDefinition.json` file dropped from 38106 bytes to 7423 and seems to be missing all the playbook parameters.

The `mainTemplate.json` file contents seem to have the playbooks defined correctly but they fail to load when manually tested by https://aka.ms/AzureSentinelPrP

**Comment by sdball** [comment]
Aha they don't fail. The playbooks are actually installed as templates that are then used to deploy the playbooks separately.

**Comment by sdball** [comment]
Is there anything more that needs to be done to get approval?

**Comment by v-spadarthi** [comment]
@sdball :  While deploying main template in content hub and we got below 
image
This can be fixed by adding meta data in playbooks azuredeploy.json file please refer this [link](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide#add-metadata) to define the meata data parameters.
For example image

**Comment by sdball** [comment]
I've made the metadata declaration changes, thanks for the helpful README link! I've also rebased with master and rebuilt to ensure I'm on the latest tooling.

**Comment by v-spadarthi** [comment]
@sdball : While deploying the CreateUI definition we could see below but dataconnector and workbooks missing please fix it
image
While deploying Maintemplate, dataconnector and workbooks missing please see below please fix it
image

**Comment by sdball** [comment]
I removed the data connector intentionally: we weren't really using that part of our solution. Our current approach is primarily based around the playbooks, analytics rules, and workbooks.

I'll look into the workbooks missing because that's a problem.

**Comment by sdball** [comment]
I believe I've fixed the missing workbook issue. It appears that the local build failed to pull workbook metadata from github.com due to a local Internet issue which caused the workbook to not be included in the solution build. Thanks for the catch!

**Comment by v-spadarthi** [comment]
Deployed the CreateUI definition and Main template looking good.
image
image

**Review by v-spadarthi — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]
Suresh Babu has reviewed, approving, and merging the PR

**Pull request merged**
