### PR TITLE
Microsoft Defender for Cloud template spec solution -> DO NOT MERGE A…

### PR DESCRIPTION
**Pull request by v-dvedak**
…S 1P

Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution **Microsoft Defender for Cloud**.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - https://microsoftapc.sharepoint.com/:f:/t/SentinelCATTeam/EkdL2-KHeLVEuxMQMIajPj4BfA88igtUQSvTwFeIwA3-YQ?e=B1MwkS

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by mkchiliveri — DISMISSED** [review]
Looks good, Approved.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Can you please get confirmation on the PR merging as its already approved.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj ,
Could you please check and confirm whether we need these changes or not.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Are we waiting on the skip validations?
Thanks

**Comment by v-mchatla** [comment]
We are working on skipvalidations

**Review by v-mchatla — APPROVED** [review]
changes are already approved. Added skip validations.

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
