### PR TITLE
Update AMATrackingWorkbook

### PR DESCRIPTION
**Pull request by Nchristis**
Fixed the workbook, added previews and changed metadata for amatrackingworkbook

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @Nchristis, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by v-jayakal** [comment]
@Nchristis - Can you please resolve the conflict and validation issues. Thanks.

**Comment by v-sabiraj** [comment]
Hey @Nchristis, request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed and please resolve the conflicts. Thanks.

**Comment by v-jayakal** [comment]
@Nchristis - Please resolve conflicts. Validation issues can be resolved by rebasing with master branch (get latest from master and merge your changes). Thanks.

**Comment by Nchristis** [comment]
Apologies for not noticing
Deleted PR

**Pull request closed without merging**
