### PR TITLE
User Map v1.4

### PR DESCRIPTION
**Pull request by clivewatson**
Required items, please complete
   
   Change(s):
   - Watchlist capability added and geoLocation IP lookup also added 

   Reason for Change(s):
   - New features added

   Version Updated:
   - v1.3 to V1.4

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by clivewatson** [comment]
Note sure what this error is?  The version is set to be 1.4 in the WorkbooksMetadata.json
 
 2022-02-14T12:54:31.3734071Z WorkbooksMetadata Validation Failed. File path: Workbooks/WorkbooksMetadata.json. Error message: The workbook UserMap.json has been modified but the version has not been incremented in the Workbooks/WorkbooksMetadata.json file.

**Comment by v-sabiraj** [comment]
The workbook UserMap.json has been modified but the version has not been incremented in WorkbooksMetadata.json file, please update, thanks.

**Comment by clivewatson** [comment]
> The workbook UserMap.json has been modified but the version has not been incremented in WorkbooksMetadata.json file, please update, thanks.

**Comment by v-sabiraj** [comment]
Hey @clivewatson , if you check the [WorkbooksMetadata.json](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json) , the metadata for the previous workbooks of User Map is not added, and if we add the WorkbookMetadata now, by default it will take version as 1.0. ,thanks.

**Comment by clivewatson** [comment]
I thought that as well, but I have tried 10.0 and it fails to validate with the same error - just updated the file so you can see that

**Comment by clivewatson** [comment]
Any idea, on how I add this Workbook and the correct metadata details?

**Comment by v-sabiraj** [comment]
@clivewatson ,This branch has conflicts that must be resolved. thanks

**Comment by v-sabiraj** [comment]
Hey @clivewatson , do the workbook need to be published in templates of workbook or you just want to be published in GitHub?

**Comment by CliveWatsonQC** [comment]
I was hoping to add this as a Template now - its been a standalone workbook for a few years in the Github.

**Comment by clivewatson** [comment]
Done, but same error as before

**Pull request merged**
