### PR TITLE
Zimperium: Fixed Pkg

### PR DESCRIPTION
**Pull request by msft-sm**
Zimperium: Fixed Pkg
- Azure Sentinel to Microsoft Sentinel

   Required items, please complete
   
   Change(s):
   - Azure Sentinel to Microsoft Sentinel

   Reason for Change(s):
   - Azure Sentinel to Microsoft Sentinel

   Version Updated:
   - N/A
   - 
   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by msft-sm** [comment]
@v-dvedak 
I used 2.0.1. Let me know if this is reflected in this PR.

**Comment by v-dvedak** [comment]
@msft-sm , I see changes in 2.0.1. Please accommodate the changes for text Microsoft Sentinel in data connector [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Zimperium%20Mobile%20Threat%20Defense/Data%20Connectors/Zimperium%20MTD%20Alerts.json) as well.

**Comment by msft-sm** [comment]
@v-dvedak 
Hmmm... I'm not seeing the changes I made for the data connector here. Let me know if you see it.

**Comment by v-dvedak** [comment]
> @v-dvedak Hmmm... I'm not seeing the changes I made for the data connector here. Let me know if you see it.

@msft-sm, I don't see any commit from you for yesterday. The one that is visible is the first commit you made when raising the PR.

**Comment by msft-sm** [comment]
@v-dvedak 
I don't know what happened. Let me start over. Sigh...

**Pull request closed without merging**
