### PR TITLE
Template spec solution update for cisco umbrella

### PR DESCRIPTION
**Pull request by v-marimanda**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution cisco umbrella
See guidance below
Version Updated:
2.0.0
See guidance below
Testing Completed:

The link for test results is

https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B6F441A9A-80F1-4FE7-809F-CB00125F10A1%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20ciscoumbrella.docx&action=default&mobileredirect=true&share=IQGaGkRv8YDnT4CfywASXxChAYKxp7bTJ3ZLfIBM89IaVdE

See guidance below
This is an 3P solution.

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda , please change text from `Azure Sentinel` to `Microsoft Sentinel`

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda , missing text is their 

image

**Review by v-atulyadav — COMMENTED** [review]
Hey @v-marimanda , please change data connector & parser text as per text doc

image

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda  , data connector text has Azure Sentinel please change

image

**Review by v-atulyadav — APPROVED** [review]

**Review by v-sabiraj — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
