### PR TITLE
New Playbook to Synchronize list of TOR Exit Node IP Addresses to Named Location list in Azure AD

### PR DESCRIPTION
**Pull request by SCStelz**
Added a new Playbook example for synchronizing a list of TOR Exit Node IP Addresses using Big Data Cloud's free API to a Named Location list within Conditional Access.

### CODE REVIEW

**Comment by sreedharande** [comment]
@SCStelz - 

1. Please remove ARM Template from json folder and put it in root folder. Path should be as follows
Playbooks/Update-NamedLocations-TOR/azuredeploy.json

2. Please add "Deploy to Azure Gov" Button.

**Comment by SCStelz** [comment]
> @SCStelz -
> 
> 1. Please remove ARM Template from json folder and put it in root folder. Path should be as follows
>    Playbooks/Update-NamedLocations-TOR/azuredeploy.json
> 2. Please add "Deploy to Azure Gov" Button.

Updates have been made, thanks for the quick response.

**Comment by SCStelz** [comment]
Added a new Playbook example for Adding Compromised Passwords to the Azure AD Banned Password List via Paid Dehashed API. Those files have also been included in this pull request. Sorry, should of waited for this one to complete.

**Comment by sreedharande** [comment]
@SCStelz - Thanks for making the changes. Can you please create new pull request for Playbooks/Get-CompromisedPasswords/azuredeploy.json instead of merging into existing PR.

**Comment by SCStelz** [comment]
Other Playbook files have been removed, once this one's approved i'll submit a new one, thanks.

**Pull request merged**
