### PR TITLE
Create Tomcat.log

### PR DESCRIPTION
**Pull request by 0ccupi3R**
Pull Request : https://github.com/Azure/Azure-Sentinel/pull/8372
#8372 

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, We wanted sample data, this looks like log file. We don't require this to test the functionality of the parser. 

Please check in this link, sample data for syslog parsers are either in .json or .txt - https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Syslog

**Comment by 0ccupi3R** [comment]
> Hi @0ccupi3R, We wanted sample data, this looks like log file. We don't require this to test the functionality of the parser.
> 
> Please check in this link, sample data for syslog parsers are either in .json or .txt - https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Syslog

@v-rbajaj 
Apologies, I was not aware of the extension. So, I just updated the it to .txt

**Comment by v-rbajaj** [comment]
> > Hi @0ccupi3R, We wanted sample data, this looks like log file. We don't require this to test the functionality of the parser.
> > Please check in this link, sample data for syslog parsers are either in .json or .txt - https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Syslog
> 
> @v-rbajaj Apologies, I was not aware of the extension. So, I just updated the it to .txt

Hi @0ccupi3R, they are still logs. 
Can you please refer to any syslog type sample data from that folder?
Please provide sample data in that format.

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, can you please provide some update on this PR?

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, can you please provide update on this PR.

**Review by 0ccupi3R — COMMENTED** [review]
@v-rbajaj 

Please find the sample logs. I hope this what you are looking for.

**Comment by v-rbajaj** [comment]
> @v-rbajaj
> 
> Apologies for the delay. The parsed logs (for the submitted parser) are uploaded.

Thanks for making these changes, we will get back you once we are done with the review of the parser.

**Review by v-rbajaj — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
