### PR TITLE
Forcepoint CASB template spec solution

### PR DESCRIPTION
**Pull request by v-dvedak**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution **Forcepoint CASB**.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - https://microsoftapc.sharepoint.com/teams/SentinelCATTeam/Shared%20Documents/Forms/AllItems.aspx?ct=1651456572074%2C1651727202806&or=Teams%2DHL%2CTeams%2DHL&ga=1&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA0MTgwMDgwOCJ9&isAscending=false&id=%2Fteams%2FSentinelCATTeam%2FShared%20Documents%2FGeneral%2FTemplateSpecs%2FTest%20Results%2FSentinel%20Solution%20Migration%2D%20TemplateSpec%20%2D%20Forcepoint%20CASB&sortField=Created&viewid=f2d90c2a%2D176b%2D48a0%2D864a%2D33113ced8d59

See guidance below
This is an **ISV** solution.

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Need to change the SolutionId - currently it is publisherId_test.offerId_test
Waiting for Eric

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-mchatla** [comment]
Hi @anki-narravula 
Did we get any confirmation on the Solution Id from Eric.
Thanks

**Comment by anki-narravula** [comment]
> Hi @anki-narravula Did we get any confirmation on the Solution Id from Eric. Thanks

Please check in catalog file and update here accordingly. You can merge once you have this added. If not available, you can followup with Eric or Sherry

**Comment by v-mchatla** [comment]
Hi @anki-narravula 
Thanks for the details. I will work on this.
Thanks

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-amolpatil** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-spadarthi** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Review by v-sabiraj — APPROVED** [review]

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
