### PR TITLE
Windowsevent batch13

### PR DESCRIPTION
**Pull request by yaelrbergman**
Change(s):
Detections/MultipleDataSources/ActiniumFeb2022.yaml
Detections/MultipleDataSources/Dev-0586_Jan2022_IOC.yaml
Detections/SecurityEvent/AdminSDHolder_Modifications.yaml
Detections/SecurityEvent/FakeComputerAccountCreated.yaml
Detections/SecurityEvent/SdeletedeployedviaGPOandrunrecursively.yaml
Reason for Change(s):
Added WindowsEvent data in addition to security event

Version Updated:
Yes

Testing Completed:
Yes
Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks.

**Comment by oshezaf** [comment]
@vmanojreddy : please let us manage ASIM and WindowsEvents PRs.

**Comment by vmanojreddy** [comment]
@oshezaf  can you please took a look and provide your feedback. thanks!!

**Comment by v-mchatla** [comment]
Hi @oshezaf 
Can we close this and reopen whenever required as you have labelled it as differed.
Thanks

**Comment by oshezaf** [comment]
Done

**Pull request closed without merging**
