### PR TITLE
add WithSecure Elements data connector

### PR DESCRIPTION
**Pull request by HubertSzymanski5**
Required items, please complete
   
   Change(s):
   - Add WithSecure Elements via Connector data connector

   Reason for Change(s):
   - Add new data connector for WithSecure Elements solution

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @HubertSzymanski5 
Can you please provide the sample data in .json or .csv format
Thanks

**Comment by HubertSzymanski5** [comment]
Hello!
I've added sample data in CEF.
https://github.com/Azure/Azure-Sentinel/blob/8d98c4628504c28b22e2ec1b5769dfa1080302e4/Sample%20Data/CEF/WithSecureViaConnectorSampleData.txt
Should I reformat it to .csv?

**Comment by NikTripathi** [comment]
Hi @HubertSzymanski5 please add in .csv or .json format. That would be more helpful. Thanks

**Comment by HubertSzymanski5** [comment]
Hello!
I've updated PR with 
[sample data in csv](https://github.com/Azure/Azure-Sentinel/blob/1ad5dfbab7449c1c8964f1f0f535ed83a7bd5052/Sample%20Data/CEF/WithSecureViaConnectorSampleData.csv) as well.

**Comment by v-laanjana** [comment]
@HubertSzymanski5 Thanks for update. we are checking and update you ASAP.

**Comment by v-mchatla** [comment]
@v-laanjana : Could you please provide an update on this.

**Comment by v-laanjana** [comment]
@v-mchatla sure will update ASAP

**Comment by v-spadarthi** [comment]
Sample data ingested
image
Logo looking good
image
@HubertSzymanski5 : Please resolve the below comments
In DataConnector please replace the text from azure sentinel to microsoft sentinel whereever it is applicable and version also change to 1.0.0
image
Please make sure whether it is EPP or EEP for below screenshot correct it
image

**Comment by v-mchatla** [comment]
Hi @HubertSzymanski5 
Please address @v-mchatla comments.
Thanks

**Comment by HubertSzymanski5** [comment]
Hi!
Sorry I missed notification previously.
I've made requested changes.
I have a question: do I need to specify some property in data connector json to actually use uploaded logo? I couldn't find that in docs.

**Comment by NikTripathi** [comment]
Hi @HubertSzymanski5 No, We don't have to add any property. 

@v-mchatla Can you please look and approve.

**Comment by v-laanjana** [comment]
@v-mchatla Can you please  have look.

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Please replace the text from azure sentinel to Microsoft sentinel wherever it is applicable still we could see azure sentinel in .md file
image

**Comment by HubertSzymanski5** [comment]
@v-spadarthi my bad! Done ;)

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Thank you for the fixing the comments.
Could you please move the Data connector under Solution folder like below.
For example:
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Citrix%20ADC/Data%20Connectors
If you need any help over here, please let us know.

**Comment by HubertSzymanski5** [comment]
Hi!
I moved everything from `DataConnectors/WithSecure` to `Solutions/WithSecure/Data Connectors` → connector JSON and MD files.

**Comment by v-spadarthi** [comment]
We are checking with PM team

**Comment by v-spadarthi** [comment]
We are checking with PM team once we get update from them will update you

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : We got update from PM team, they are suggesting to add some analytics and/or a workbook.Thanks!

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Could you please check with Eric(erburk@microsoft.com) for this they are suggesting adding some analytics and/or a workbook. Thanks!

**Comment by HubertSzymanski5** [comment]
Hi!
So we contacted with Eric :) I was away and seems that Serge Haumont sent an email.
They agreed that for now we would like to go with Data Connector only and then create Analytics Rules and Workbooks as we need to prepare them and understand how can we make them as valuable as possible. :)

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Thanks for the update.
Could you please create a solution package by using V2 tool
Please follow the below URL and do the package creation. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Please create a package by using below URL. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Please create a package by using below URL. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by HubertSzymanski5** [comment]
Hi! Sorry I had few days off.
I'll jump right to it.
Is there anything else I should do?

**Comment by HubertSzymanski5** [comment]
Hi,
So I've wanted to ask if You have instructions for Linux, but I saw there is PowerShell for Linux.
After all seems like the script `createSolutionV2.ps1` doesn't work it tries to download some files to `C:\` as on attached screenshot
image
Can You please help with that issue?

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : First you need to create a Solution input file and keep it in under solution/Data folder after that we need to create a Package.
For example, refer this solution https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Agari
while creating package you need to keep the Solution input file in below folder path
C:\GitHub\Azure-Sentinel\Tools\Create-Azure-Sentinel-Solution\V2\input
After that you need to point to below and run the createSolutionV2.ps1
image

**Comment by HubertSzymanski5** [comment]
Yes, I've created those two files. I have few questions to those, but first I wanted to make it work.
Is this path `C:\GitHub\...` hardcoded? I use Ubuntu and there is no `C:\`. I thought script will use that `basePath` from input file.
Is there any way to make it work on Linux / Ubuntu?

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : The base path is not hardcoded you can provide your path and do the package creation.

**Comment by HubertSzymanski5** [comment]
@v-spadarthi That's good info, thank You, but how can I do that?
In `Tools/Create-Azure-Sentinel-Solution/input` I've created my `Solution_WithSecureElementsViaConnector.json` file as it's in instruction. Then there is this `BasePath` property. In my file it looks like this:
image
And it gives that error as I posted above.

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : We will check and provide you an update.

**Comment by HubertSzymanski5** [comment]
@v-spadarthi  I think I found what was wrong.
First of all on master `input` file is not empty and contains other solutions files (I think those should be removed):
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/input
and for V2:
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2/input

Then nothing showed, but it's because there is some mismatch in https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md.
As it states
image
And then:
image
I assume path in former should be `\Tools\Create-Sentinel-Solution\V2\input`. So I moved it there
After that it seems script runs, as for now it has not finished, but runs :)

**Comment by HubertSzymanski5** [comment]
I think I managed to create this package.
In separate commit I removed files from input directories (and I haven't uploaded my input file to prevent issues for others).
Please ignore PS. above. All the tests were fine later on - only first run was printing everything to console. Rest had nice simple output with message what went wrong.

Please take a look and let me know if there is anything to do.
What I wanted to ask before is about `support` section.
WithSecure doesn't have public support email address. All issues should be sent via form on our support page.
Therefor I removed `email` from `support` and went just with `link`, is that possible?

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Please add the Input file under Solutions/WithSecureElementsViaConnector/Data folder and keep it here
below are looking good.
Create UI definition looking good
image
Main template looking good
image
Arm-ttk also running fine
image

**Comment by HubertSzymanski5** [comment]
Thank You @v-spadarthi.
Input file added.

**Review by v-spadarthi — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Comment by v-dvedak** [comment]
Approved and merged since Suresh's has approved the PR

**Comment by HubertSzymanski5** [comment]
Hi!
Can You tell me when it will be visible? So far I cannot see this in portal.

**Comment by v-spadarthi** [comment]
@HubertSzymanski5 : Please read the below document and publish your solution
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/README.md
If still need any further support, feel free to reach out us.

**Pull request merged**
