### PR TITLE
[SOLUTION: NXLog AIX Audit 2.0.1]

### PR DESCRIPTION
**Pull request by jszigetvari-nxlog**
This PR addresses the feedback received from Microsoft regarding broken links

CHANGES:

- Corrected outdated NXLog documentation and support URLs
- Updated Package 2.0.0.zip to 2.0.1.zip
- Updated all mentions of Microsoft Azure Sentinel to Microsoft Sentinel

REASONS FOR CHANGE(S):

- To address the findings raised by Microsoft for this and other solutions
- I took over the maintenance tasks from former colleagues who worked on this earlier

VERSION UPDATED:

- Yes, to version 2.0.1

TESTING COMPLETED:

- Need Help / I did not do any actual tests on this, but compared to the in-repo data created by my former colleagues, I only made metadata changes

RAN VALIDATIONS:

- Yes, all validations returned passed

This work is associated with NXLog's Jira Issue IN-272

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @jszigetvari-nxlog 
1. Please  provide data connector log screen shot.

2. Please update data connector description in CreateUiDefinition and in zip file  with below description

    **data connector description**
    This solution installs the data connector that uses the AIX Audit subsystem to read events directly from the kernel for 
    capturing audit events into Microsoft Sentinel. After installing the solution, configure and enable this data connector by 
    following guidance in Manage solution view.
 
    The solution installs a parser that transforms ingested data. The transformed logs can be accessed using the 
    NXLog_parsed_AIX_Audit_view Kusto Function alias.
3. Getting error while running arm-ttk


Please update api version in mainTemplate and in zip file  from 2021-06-01 to  2022-10-01 at below highlighted place.

**Comment by jszigetvari-nxlog** [comment]
@v-rusraut 
> 1. Please provide data connector log screen shot.

Could you please elaborate a bit further where I could get that screenshot, and from what exactly?
I will take care of the rest.

**Comment by v-rusraut** [comment]
Hi @jszigetvari-nxlog

Steps for data connector log screen shots
1. Search solution in content hub and click on Manage buttton.



2. Click on data connector link



3. Click on NXlog AIX Audit
image

4. Provide complete screen shot  of below highlighted section

**Comment by jszigetvari-nxlog** [comment]
@v-rusraut Thanks for the screenshots, they are very helpful!

I have one further question: How can I deploy my unpublished solutions to such a sandbox environment, where I can test my changes which are works in progress? (I noticed you deployed this unpublished version.)

**Comment by v-rusraut** [comment]
hi @jszigetvari-nxlog
Please commit your changes.

**Comment by jszigetvari-nxlog** [comment]
@v-rusraut After I correct the API version in `mainTemplate.json` and the descriptions in `createUiDefinition.json`, and run the `createSolutionV2.ps1` script, it will rewrite the original values in those files, even the API version too.
Am I supposed to update those files in the existing 2.0.1 package manually without running the script?

**Comment by jszigetvari-nxlog** [comment]
@v-rusraut I have edited the files, and manually copied the to the 2.0.1 package. It is less than ideal, but it satisfies the requirements.

**Comment by jszigetvari-nxlog** [comment]
@v-rusraut And finally here is the screenshot of the Data Connector working as intended.
This was the last missing item from the list requested. Thanks for guiding me through the process!
kép

**Review by v-rusraut — APPROVED** [review]

**Pull request merged**
