### PR TITLE
Wiz solution fix workbook

### PR DESCRIPTION
**Pull request by yanivblumWiz**
Required items, please complete
   
   Change(s):
   - updated workbook in the main template file

   Reason for Change(s):
   - queries failed

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Does the query from maintemplate matches with the query mentioned in actual workbook.
And please repackage the solution with V3 tool.
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Workbook metadata is missing from the workbookmetadata files. 
Also can you please share your mail id so we connect personally and try to get this Merged.
Thanks

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz, Workbook metadata is missing from the workbookmetadata files. Also can you please share your mail id so we connect personally and try to get this Merged. Thanks

hi @v-prasadboke, can you please elaborate on what are the  `workbookmetadata files`? I never heard about it so far or seen it. Can you please share some examples?
Also, my email is yaniv.blum@wiz.io feel free to email me as well :)

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Please visit the link mentioned below and for reference you can have look at any of metadata available in the workbook metadata file.
Thanks.
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz, Please visit the link mentioned below and for reference you can have look at any of metadata available in the workbook metadata file. Thanks. https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json

@v-prasadboke 
Done, please let me know if I need to do something else :)

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Thank you for committing the changes.

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz sorry for the inconvenience. I pushed master branch in your branch in this scenario the commit for Workbook metadata and images were lost. 
Can you please add them again.

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz sorry for the inconvenience. I pushed master branch in your branch in this scenario the commit for Workbook metadata and images were lost. Can you please add them again.

@v-prasadboke 
I think now it's okay again, let me know how it goes

**Comment by v-prasadboke** [comment]
Thank you @yanivblumWiz, Will update you till 04 October, 2023.

**Comment by yanivblumWiz** [comment]
> Hi @yanivblumWiz, We apologize for the delay, but due to lack of availability, we will update you on this by 06 Oct 2023. Thanks

@v-atulyadav, thanks for the update.
If you guys could please make an effort and merge this before, we would highly appreciate it as we have many customers waiting for this to be updated.

**Review by v-prasadboke — APPROVED** [review]

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, I corrected the support tier in maintemplate but dont have push access to this branch. So ill get this PR merged and raise another PR for latest zip file and release note.md

**Review by v-atulyadav — APPROVED** [review]

**Comment by yanivblumWiz** [comment]
@v-atulyadav Thanks!

**Pull request merged**
