### PR TITLE
Update AzureFirewall.JSON - Azure Firewall Connector to support resource specific log tables.

### PR DESCRIPTION
**Pull request by shabaz-github**
Updating the Azure Firewall Sentinel Connector with Resource Specific Logs

   Required items, please complete
   
   Change(s):
   - Updated AzureFirewall.JSON file for Azure Firewall Connector under Firewall Solution to support resource specific logs.

   Reason for Change(s):
   - To support the new resource specific logs in Azure Firewall Connector

   Version Updated:
   - Not Required as it is not a Detection/Analytic rule template

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 27 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, We are facing issue while repackaging the solution. Instruction steps which are newly added to the Data connector is not visible in the maintemplate after repackaging. 
We are still working on it and will update you about the same before 28 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, I was trying to include instruction steps in maintemplate but it bit of messed up. Can you please try to repackage solution from your side. 
Instruction on how to repackage solution using V3 tool https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by shabaz-github** [comment]
> Hello @shabaz-github, I was trying to include instruction steps in maintemplate but it bit of messed up. Can you please try to repackage solution from your side. Instruction on how to repackage solution using V3 tool https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

Hello @v-prasadboke, we haven't done it before, would need your team's assistance in repackaging. In the past we have just submitted the PR, which gets merged and then the Engineering Devs would help with repackaging.

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Just came to know this is a ccp connector and right now V3 tools doesnt supports ccp connector. Our Packaging tool team is working on the same. 
We will update you once its done.

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Sorry for delay in the process but we are still working on the Solution.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
