### PR TITLE
Confidence Score to IPEntity files

### PR DESCRIPTION
**Pull request by mmelndezlujn**
Required items, please complete
   
   Change(s):
   - Modified all IPEntity files to determine Alert Priority based on Confidence Score
   - Added logic to filter rows where confidence score was less than 51
   - Added alertDetailsOverride to coincide with the Alert Priority

   Reason for Change(s):
   - To add the Alert Priority 

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, Thanks for raising this PR. 
This PR will be investigated and will update you about the same before 13 October, 2023. 
Until then can you please clear the validation fails.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn please repackage the solution and please clear the validation fails. 
Instruction on repackaging the solution and using the V3 tool 
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, Please repackage the solution.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, Please repackage the solution after committing your final changes.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, We are waiting for your response.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, please respond to the above comments.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn please repackage the solution.

**Comment by v-prasadboke** [comment]
Hello Manuel, Please work on the above requested changes.

**Comment by v-prasadboke** [comment]
Hello there, @mmelndezlujn. Please notify us if any changes are still pending on your end.

**Comment by v-prasadboke** [comment]
Hello there, @mmelndezlujn. Could you please respond to the remarks above?

**Comment by mmelndezlujn** [comment]
> Hello there, @mmelndezlujn. Please notify us if any changes are still pending on your end.

Hello! I don't think there are any pending changes.

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, can you please work on the requested changes.

**Comment by aprakash13** [comment]
Task pending on me to review this PR by @mmelndezlujn and help with packaging effort. Would get this addressed by 11/15.

**Comment by v-prasadboke** [comment]
Thanks, Noted @aprakash13.

**Pull request closed without merging**
