### PR TITLE
Microsoft Sentinel solution for SAP® applications version 2.0.53

### PR DESCRIPTION
**Pull request by oferInbar**
Required items, please complete
   
   Change(s):
   - See guidance below
   - 12 new alert rules

   Reason for Change(s):
solution content

   Version Updated:
   - yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes
-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by v-mchatla** [comment]
Hi @devikamehra,
Can you please review the content and share your feedback.
Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra,
Can you please review the content and share your feedback.
Thanks

**Comment by v-vdixit** [comment]
Hi @devikamehra please provide your feedback, thanks!

**Comment by v-mchatla** [comment]
Hi @devikamehra, @rushriva,
Can you please review the changes and share your feedback.
Thanks

**Comment by rushriva** [comment]
@v-mchatla  can you please get conflicts resolve in this PR and validation passed.

**Comment by v-mchatla** [comment]
Hi
Working on fixing analytic Rule formatting.
Thanks

**Comment by oferInbar** [comment]
hi. please don't invest time in fixing formatting and suggest to me how to fix formatting and i will handle on the source of content

**Comment by rushriva** [comment]
@oferInbar  - Please add Connectorid "SAP" to github this will resolve validation error - 
 Error Message:
   System.Collections.Generic.KeyNotFoundException : The given key 'connectorId' was not present in the dictionary.

Thanks,
Ruchir

**Comment by v-mchatla** [comment]
Hi @oferInbar,
As discussed, please fix the validation errors. Let us know if you need any help.
Thanks

**Comment by v-mchatla** [comment]
Hi @oferInbar,
As discussed, please fix the validation errors. Let us know if you need any help.
Thanks

**Comment by oferInbar** [comment]
Thanks for offering to help.
I am currently working on a new commit to fix most if not all issues (and probably create a couple more 😊)

Thanks,

Ofer

**Comment by v-mchatla** [comment]
Hi @oferInbar,
Thanks for the update.
Thanks

**Comment by v-mchatla** [comment]
Hi @oferInbar,
If you need some time to rectify all the validation issues, you can move this PR to Draft and make it active once you are done with the changes.
Thanks

**Comment by oferInbar** [comment]
we have a new PR with version 2.0.63 so this one can be closed

**Pull request closed without merging**
