### PR TITLE
Simplify FailedLogonAttempts_UnknownUser.yaml

### PR DESCRIPTION
**Pull request by ep3p**
Change(s):
   - Simplify query and leave just 1 join.

   Reason for Change(s):
   - There are multiple unneded table calls that difficult the understanding of the query, and increase CPU time.

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13  Please review detections.

**Comment by vmanojreddy** [comment]
@aprakash13 Please review detections.

**Comment by vmanojreddy** [comment]
@aprakash13 Please review detections. thanks!!!

**Review by aprakash13 — COMMENTED** [review]
@russmcsec to take a look on this one.

**Comment by aprakash13** [comment]
Followed up with @russmcsec for help with this.

**Comment by vmanojreddy** [comment]
@russmcsec can you please take a look and provide your feedback. thanks!!!

**Review by aprakash13 — APPROVED** [review]
Thanks @ep3p

**Pull request merged**
