### PR TITLE
CustomTables_Feed

### PR DESCRIPTION
**Pull request by thbanasi**
SecurityIncident
InformationProtectionLogs_CL
SecurityRecommendation
CMMCPolicyMapping

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Thank TJ for putting these custom tables. I checked with the Engineering team and I do not think we have native support for these currently. 

It seems in the SecurityRecommendation.json file we probably need to add a couple of more columns like ResourceTenantId, TenantId etc. Can you please double check the schema and add the additional items and we can go ahead and merge this PR. Thanks TJ.

**Comment by thbanasi** [comment]
@Ajeet Prakash ***@***.***>,

Thanks so much, I've updated both the SecurityRecommendation and SecurityIncident tables per the getschema method, thanks.

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Senior Program Manager
C&AI, Sovereign Cloud Security Group
***@***.******@***.***>
(202) 658-8148



***@***.***

LinkedIn: In/tjbanasik<http://www.linkedin.com/in/tjbanasik>

**Review by aprakash13 — APPROVED** [review]
Thanks TJ for all your work here. Looks good to me and ready to be merged.

**Comment by thbanasi** [comment]
Perfect, thanks so much!

Very Respectfully,

TJ Banasik
CISSP-ISSEP,ISSAP,ISSMP
Senior Program Manager
C&AI, Sovereign Cloud Security Group
***@***.******@***.***>
(202) 658-8148



***@***.***

LinkedIn: In/tjbanasik<http://www.linkedin.com/in/tjbanasik>

**Pull request merged**
