### PR TITLE
Adding Retention Tab

### PR DESCRIPTION
**Pull request by samikroy**
Adding retention tab to incorporate with export to excel option.

## Proposed Changes

1. Display Workspace level retention.
2. Display Table level retention.
3. Both contains Export to excel functionality.

  -
  -
  -

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Please add preview images, thanks.

**Comment by samikroy** [comment]
> Please add preview images, thanks.

@v-sabiraj  - Thank you.

image

image

These are the images.

As this is 2.0 > 2.1 version upgrade do you suggest to add these previews to workbook preview images ?

**Review by NikTripathi — APPROVED** [review]
Workbook looks good.

**Comment by samikroy** [comment]
> Workbook looks good.

Thank you @NikTripathi

**Pull request merged**
