### PR TITLE
Configurable max sync window size in /Solutions/CiscoDuoSecurity

### PR DESCRIPTION
**Pull request by qbitflip**
Required items, please complete
   
   Change(s):
   - New configuration option MAX_SYNC_WINDOW_PER_RUN_MINUTES to allow specifying the maximum synchronisation window in minutes when ingestion is lagged for the authentication and trust_monitor sources for the Azure Function AzureFunctionCiscoDuo in the CiscoDuoSecurity solution.
   - Configuration setting is optional. The default setting remains at 60 minutes if not present.

   Reason for Change(s):
   - Allow reduction of maximum sync window for large organisations encountering Azure function timeout issues
   - Resolves issue #8727

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need help

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @qbitflip 
Thanks for the contribution. Can you please update the [zip](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CiscoDuoSecurity/Data%20Connectors/CiscoDuoSecurity_func.zip) file with the latest changes.
Thanks

**Comment by qbitflip** [comment]
@microsoft-github-policy-service agree company="Deakin University"

**Comment by qbitflip** [comment]
> Hi @qbitflip Thanks for the contribution. Can you please update the [zip](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CiscoDuoSecurity/Data%20Connectors/CiscoDuoSecurity_func.zip) file with the latest changes. Thanks

@v-mchatla of course, done.

**Comment by v-mchatla** [comment]
Hi @qbitflip 
Sorry for the delay in response. I will verify and update you in sometime.
Thanks

**Review by v-mchatla — APPROVED** [review]

**Pull request merged**
