### PR TITLE
Added new solution for Tenable App with the combining products of TenableVM and TenableIE

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Change(s):
   - Added new solution for Tenable App which contains two products named as Tenable VM(Vulnerability Management) and Tenable IE(Identity Exposure)

   Reason for Change(s):
   - Need to combined existing product named as Tenable IO and Tenable AD as single solution named Tenable App

   Version Updated:
   - Created new solution using latest version of 3.0.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by jayeshprajapaticrest** [comment]
> Hello @jayeshprajapaticrest, Thanks for raising this PR. Can you try to resolve the failed KQL validations.

Sure we are fixing it @v-prasadboke

**Comment by v-prasadboke** [comment]
Thanks @jayeshprajapaticrest

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke 
I have tried with many ways to fix this issue and also as I checked many time the provided kql query in the parser yaml file has not error or incomplete and unable to fix it. Can you please help me out on this?

**Comment by jayeshprajapaticrest** [comment]
Hi @v-prasadboke 
We have committed fix of CodeQL. Can you please proceed with the review and merge it as early as possible?

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Thanks for resolving the CodeQL errors. We will review the PR and provide you an update by 02 July, 2024.

**Comment by jayeshprajapaticrest** [comment]
> Hello @jayeshprajapaticrest, Thanks for resolving the CodeQL errors. We will review the PR and provide you an update by 02 July, 2024.

@v-prasadboke Any update on this PR merge?

**Review by v-prasadboke — APPROVED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke 
Thanks for merging the above PR.
The below shorthand URL is not working same as previously for other integration.
https://aka.ms/sentinel-TenableVMAzureSentinelConnector-functionapp
—>Solutions/Tenable App/Data Connectors/TenableVM/TenableVMAzureSentinelConnector.zip

Can you please fix this and let me know here?

**Pull request merged**
