### PR TITLE
sentinel1 analytic content

### PR DESCRIPTION
**Pull request by spsocprime**
## Proposed Changes

 Analytic content for SentinelOne

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@aprakash13 , please review Analytic Rules, Thank-you.

**Comment by spsocprime** [comment]
fixed

**Comment by v-sabiraj** [comment]
image
image
Please fix the workbook queries, Thanks.

**Comment by spsocprime** [comment]
fixed

**Comment by v-sabiraj** [comment]
image
Please fix the query, thanks.

**Comment by v-sabiraj** [comment]
image
image
Please fix the workbook queries, thanks.

**Comment by v-sabiraj** [comment]
@aprakash13 , please review Analytic Rules, Thankyou.

**Comment by v-sabiraj** [comment]
@aprakash13, please review and approve Analytic Rules, thanks.

**Review by v-sabiraj — APPROVED** [review]

**Comment by v-sabiraj** [comment]
Workbooks looks good, can merge once @aprakash13 review and approve, thanks.

**Review by aprakash13 — APPROVED** [review]
Overall, on a quick look the queries look good.

**Pull request merged**
