### PR TITLE
netskope playbook

### PR DESCRIPTION
**Pull request by saif-chaudhry**
Required items, please complete
   
   Change(s):
   - Request to Publish Netskope Playbook for Sentinel

   Reason for Change(s):
   - First Time Request.

   Version Updated:
   - N/A

   Testing Completed:
   - Yes.

   Checked that the validations are passing and have addressed any issues that are present:
   - The template deployment works when tested.

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by v-spadarthi** [comment]
@rahul0216 / @manishkumar1991 : Please review the Playbooks and provide your feedback. Thanks!

**Comment by saif-chaudhry** [comment]
@rahul0216 @v-spadarthi  let me know if anything is needed from my end.

**Review by rahul0216 — COMMENTED** [review]
@saif-chaudhry 
1. Do not create Keyvault resource. Use an existing Keyvault. Take Keyvault and secret name as parameters. 
2. There should be a parallel branch to handle failure of Netskope API call "Get URL List". A comment can be shown in incident. There are other API calls as well but at least failure for this first call should be handled.

**Comment by v-spadarthi** [comment]
@saif-chaudhry: Please address the @rahul0216  comments.

**Comment by saif-chaudhry** [comment]
> 

@rahul0216 Thanks for your feedback and review. I have added the API call failure to the playbook now. For the KV suggestion, we would like to provision a new one as part of the deployment to avoid any brownfield type deployment issues when customers are using this playbook. For better deployment experience we would like to request to allow the creation of KV as part of the playbook use. Let me know.

**Comment by v-spadarthi** [comment]
@rahul0216 : Please review the PR and provide your feedback.

**Review by rahul0216 — APPROVED** [review]
@saif-chaudhry 
Thanks for the changes. PR looks good.
@v-spadarthi 
**Please add the "deploy to azure" button once PR is merged to main branch.**

**Comment by v-spadarthi** [comment]
@rahul0216 : We will check with you for "deploy to azure" and will proceed

**Comment by v-spadarthi** [comment]
As discussed with @rahul0216 we are working on this and let you know the update.

**Comment by v-spadarthi** [comment]
@saif-chaudhry : Please change the text from azure Sentinel to Microsoft Sentinel in below.
If you find any where in your files please update all the places
I could see many places in your file please update.
image
image

**Comment by saif-chaudhry** [comment]
> @saif-chaudhry : Please change the text from azure Sentinel to Microsoft Sentinel in below.
> If you find any where in your files please update all the places
> I could see many places in your file please update.
> image
> image

@v-spadarthi I have updated the readme file as requested. This also include changes that @rahul0216 did... let me know if any issues.

**Comment by v-spadarthi** [comment]
We will check and let you know the update.

**Comment by v-spadarthi** [comment]
@saif-chaudhry : Please address the above comments.

**Comment by saif-chaudhry** [comment]
> @saif-chaudhry : Please address the above comments.

@v-spadarthi I have update the last occurrence of "Azure Sentinel" to "Microsoft Sentinel". Thanks.

**Comment by v-spadarthi** [comment]
We will check and let you know the update.

**Comment by v-spadarthi** [comment]
@rahul0216 : Please provide your approval .Thanks!

**Review by rahul0216 — APPROVED** [review]
Changes looks good.

**Review by v-rucdu — APPROVED** [review]

**Comment by v-spadarthi** [comment]
@rahul0216 : As per your instructions we added the Deploy to Azure and Deploy to Azure GOV buttons added
Raised another [PR](https://github.com/Azure/Azure-Sentinel/pull/6795) for above

**Pull request merged**
