### PR TITLE
CTERA Solution for Azure Sentinel

### PR DESCRIPTION
**Pull request by roberteliass**
Required items, please complete
   
   Change(s):
   Updated files:
   - Analytic Rules
       - RansomwareUserBlocked.yaml
       - RansomwareDetected.yaml
   - Data
       - Solution_CTERA.json
   - Data Connectors
       - CTERA_Data_Connector.json
   - Hunting Queries
       - MassAccessDenied.yaml
       - MassPermissionChanges.yaml
       - MassDeletions.yaml
   - Package
       - mainTemplate.json
       - createUiDefinition.json
   - Workbooks
       - CTERA_Workbook.json
   - ReleaseNotes.md
   - SolutionMetadata.json

   Reason for Change(s):
   - These updates include enhancements to the overall structure, improved detection capabilities, and better integration with the CTERA solution. Bug fixes and optimizations. Resolves validation issues encountered in prior submissions.

   Version Updated:
   - yes
   - Version field updated for Detections/Analytic Rule templates.

   Testing Completed:
   - Tested in Microsoft Sentinel environment without custom parsers, functions, or tables.
   - Validated functionality and ensured proper syntax execution.

   Checked that the validations are passing and have addressed any issues that are present:
    - Yes, validation checks were run, and all identified issues were addressed.

### CODE REVIEW

**Comment by roberteliass** [comment]
@v-prasadboke @v-atulyadav  What is the ETA for the code to be reviewed?

**Comment by v-prasadboke** [comment]
> @v-prasadboke @v-atulyadav What is the ETA for the code to be reviewed?

Hello @roberteliass, I'm on leave till 6th Oct. Will get back to you by 9th Oct

**Comment by v-prasadboke** [comment]
Hello @roberteliass, Please add workbook metadata to the workbooksmetadata file 
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json

Please try to resolve branch conflicts.

**Comment by roberteliass** [comment]
Hi,

Why this conflict is presented after the commit?
Also it's not inline with what I see on the pull request.
I see a conflict on this file .script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json

Lines - 252-258
<<<<<<< master
  "CTERA"
]
=======
  "IllumioSaaSDataConnector"
]
>>>>>>> master

If I resolve the conflict like I already did in the past it will go through the entire validation process again without ever getting to the code review.

Can you please clarify the process of getting the pull request approved?

Thanks,
Robert Elias
Product Manager
e. ***@***.******@***.***>
linkedin eliasrobert<http://www.linkedin.com/in/eliasrobert>

***@***.***

**Comment by roberteliass** [comment]
Hi,

I've updated the workbooksmetadata file and resolved the conflicts.
Please help promoting the pull request to be review and if no issues approved.

Thanks,
Robert Elias
Product Manager
e. ***@***.******@***.***>
linkedin eliasrobert<http://www.linkedin.com/in/eliasrobert>

***@***.***

**Comment by roberteliass** [comment]
Hi again,

Can you please help moving forward with the approval of the pull request, I am in a loop here.
I am pushing the pull request, then after the initial validation process, I usually wait for about a week before the arm-ttk runs (seems like someone is running it manually).

Then I wait for approval and in the meantime, I get a conflict message that I need to resolve, which is just another solution that was added before me.

Can you help me approving the solution promptly to avoid it.

Thanks,
Robert Elias
Product Manager
e. ***@***.******@***.***>
linkedin eliasrobert<http://www.linkedin.com/in/eliasrobert>

***@***.***



From: Robert Elias ***@***.***>
Sent: October 9, 2024 1:07 AM
To: Azure/Azure-Sentinel ***@***.***>; Azure/Azure-Sentinel ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/Azure-Sentinel] CTERA Solution for Azure Sentinel (PR #11169)

Hi,

I've updated the workbooksmetadata file and resolved the conflicts.
Please help promoting the pull request to be review and if no issues approved.

Thanks,
Robert Elias
Product Manager
e. ***@***.******@***.***>
linkedin eliasrobert<http://www.linkedin.com/in/eliasrobert>

***@***.***

**Comment by v-prasadboke** [comment]
Hello @roberteliass, Can you provide me write access to your branch

**Comment by roberteliass** [comment]
Hi,

You already had write access, I revoked and invited you again as a collaborator.

Thanks,
Robert Elias
Product Manager
e. ***@***.******@***.***>
linkedin eliasrobert<http://www.linkedin.com/in/eliasrobert>

***@***.***

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
