### PR TITLE
Reedit RareOperations.yaml to make it functional

### LINKED ISSUE #2976: Template regarding "Rare subscription-level operations in Azure" may not useful
**Describe the bug**
The script is here: https://github.com/Azure/Azure-Sentinel/blob/2cad1a602c99d6e3f8be2548e31e4ca63ed75c6f/Detections/AzureActivity/RareOperations.yaml

I believe this script will never return any result.

For the value of the ‘OperationNameValue’, it looks like this:
image

Thus, when we define SensitiveOperationList to "List keys", "List Storage Account Keys", "Register Subscription", "Create or Update Snapshot", "Create or Update Network Security Group", they will never meet the value of ‘OperationNameValue’:
image

However, when I switch one of those parameters inside the list:
image

Then, there will be some results that can be met.

**Expected behavior**
Reedit the template to make it functional.

### PR DESCRIPTION
**Pull request by Lodewyk-Git**
Changed OperationNameValue to OperationName

Fixes #2976

### CODE REVIEW

**Comment by Lodewyk-Git** [comment]
Has the same values as #2281

**Comment by shainw** [comment]
@Lodewyk-Git - These were missed on update of the field name, the value will be changed shortly which will make this PR not needed.  AzureActivity uses a new connector and the change to OperationNameValue is needed.  @ashwin-patil is implementing the fixes and we will post back when fixed.

**Comment by ashwin-patil** [comment]
PR #2867  has all the fixes where logic is not updated with the field `OperationNameValue` in queries, workbooks.

**Comment by Lodewyk-Git** [comment]
Ok Thanks @ashwin-patil, I wasn't aware of that request.

**Pull request closed without merging**
