### PR TITLE
feat: add Playbooks/Enrich-AzureResourceGraph-Incident

### PR DESCRIPTION
**Pull request by juju4**
Change(s):
   - add Playbooks/Enrich-AzureResourceGraph-Incident

   Reason for Change(s):
This logicapp calls Enrich-AzureResourceGraph (https://github.com/Azure/Azure-Sentinel/pull/7895) to comment Sentinel Incident based on ResourceGraph data

   Testing Completed:
   - Yes. used in production for many months

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes. Deployed in production with Sentinel Repository feature, precommit and psrule

### CODE REVIEW

**Review by rahul0216 — COMMENTED** [review]
Playbook required Azure Sentinel Contributor role add tag to incident.
Please add steps in readme file to add Azure Sentinel Contributor role.

**Comment by v-rbajaj** [comment]
Hi @juju4, can you please address Rahul's comment?

**Comment by v-rbajaj** [comment]
Hi @juju4, can you please look into Rahul's comment?

**Comment by juju4** [comment]
Added to readme.
Note that this was already listed in prerequisite of ARM template https://github.com/Azure/Azure-Sentinel/pull/7896/files#diff-e50d21fc51c101c2aa3507716454c453f4506c81c43ad3b7894bfa1c163c3fe7R11

**Review by rahul0216 — APPROVED** [review]
Changes look good.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
