### PR TITLE
add analytic content for VMwareESXi

### PR DESCRIPTION
**Pull request by spsocprime**
## Proposed Changes

 Added analytic content for VMWareESXi data connector

### CODE REVIEW

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytic rules. Thanks

**Review by NikTripathi — CHANGES_REQUESTED** [review]
Workbook looks good.

**Review by NikTripathi — DISMISSED** [review]
Workbook looks good.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Overall, the queries look good. A few things that need attention:

++When using extend, it's generally a good idea to have descriptive name vs one alphabet 
++We probably need a custom table for VMwareESXi
++Need to fix the validation errors before this can be merged.

**Comment by v-sabiraj** [comment]
Hey @spsocprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by v-jayakal** [comment]
@spsocprime - Can you please rebase with  master or get latest from master (merge from master), that will resolve the validation issues. Thanks.

**Comment by v-sabiraj** [comment]
The name 'VMwareESXi' does not refer to any known table, tabular variable or function. Please add  'VMwareESXi' in [Custom table](https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables). Thanks.

**Comment by v-sabiraj** [comment]
@aprakash13 ,please review and approve, thanks.

**Comment by spsocprime** [comment]
fixed

**Pull request merged**
