### PR TITLE
092122  as okta network zone update

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
New playbook

Reason for Change(s):
New playbook

Testing Completed:
Yes

### CODE REVIEW

**Review by manishkumar1991 — APPROVED** [review]
approved, Playbook Deployment looks fine

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @AcceleryntSecurityDev - Thank you for your submission. Sorry for delay in review. 
- We have recently migrated to new approach (template specs) and as part of this, now having metadata object is mandatory for every playbook. 
- You can find the instructions here - https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide#contribution-guidelines
- For examples you can refer this playbook https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Playbooks/OktaPlaybooks/Okta-EnrichIncidentWithUserDetails/azuredeploy.json 
- As a best practice, we recommend sentinel connection in playbooks uses "ManagedSecurityIdentity".
Please refer Sample [Template](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json) for sample template. For more details, refer [this](https://techcommunity.microsoft.com/t5/azure-sentinel/what-s-new-managed-identity-for-azure-sentinel-logic-apps/ba-p/2068204). Make sure to do changes at 3 places 

image

image

image

**Comment by manishkumar1991** [comment]
@AcceleryntSecurityDev Requesting you to please act on "anki-narravula" comments, and once done, please reply ,

**Comment by AcceleryntSecurityDev** [comment]
@anki-narravula @manishkumar1991 changes have been made. Please review.

**Comment by v-sabiraj** [comment]
Hi @anki-narravula, can you please review the changes done by @AcceleryntSecurityDev, thanks.

**Review by manishkumar1991 — APPROVED** [review]
approved

**Review by NikTripathi — APPROVED** [review]

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
