### PR TITLE
Added additional functionality to Auth0AM parser

### PR DESCRIPTION
**Pull request by noodlemctwoodle**
Complete overhaul of Auth0AM Parser

Change(s):
- Updated all columns and data names
- Split out a number of events for the platform
- Added IP Geolocation function for IP address lookups
- Added split by event types

Reason for Change(s):
- Adds additional granularity for creating custom detection rules.
- Adds additional granularity for creating custom hunting queries.
- Adds additional granularity for creating custom workbook.

Testing Completed:
 - Tested on Auth0AM data in Microsoft Sentinel

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Thanks for raising this PR. This PR will be investigated and we will get back to you with an update by 11 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle I've committed the requested changes. But a validation check is failing for the same. We are trying to resolve the validation error. We will get back to you by 13 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Sorry for the inconvenience but we are still investigating this Validation failure. 
Will get back to you by 19 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, I'm incredibly sorry for the improbability, I'm trying to resolve the validation error. 
I'll get back to you till 21 December, 2023  with a resolution with the possibilities.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, sorry for the inconvenience but we are still trying to find out what is causing the validation failure.

**Comment by noodlemctwoodle** [comment]
Any update on this?

**Comment by v-prasadboke** [comment]
@noodlemctwoodle still working on it

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, We have managed to resolve the validation failure. Sorry it took too long. Continuing to test the maintemplate.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, can you share sample data to test the content of the solution.

**Comment by noodlemctwoodle** [comment]
What format do you want the data in?

**Comment by v-prasadboke** [comment]
> What format do you want the data in?

json or csv

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Please share the sample data

**Comment by v-atulyadav** [comment]
Hi @noodlemctwoodle,
We are waiting for a sample data. Thanks

**Comment by noodlemctwoodle** [comment]
[Auth0_scrubbed.csv](https://github.com/Azure/Azure-Sentinel/files/14299063/Auth0_scrubbed.csv)

**Comment by noodlemctwoodle** [comment]
> Hi @noodlemctwoodle, We are waiting for a sample data. Thanks

Do you have an email address that I can send it to please?

**Comment by v-prasadboke** [comment]
v-prasadbokey@microsoft.com

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, 
Just to confirm did you shared the sample data

**Comment by noodlemctwoodle** [comment]
Sorry, it's been mental I'll share it tomorrow.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle,
Did you shared the sample data?
I was going through my mails but didnt found any.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, Can you please provide Sample data.

**Comment by v-prasadboke** [comment]
Hello @noodlemctwoodle, A gentle reminder. 
We have resolved the validation earlier but due to lack of sample data we are unable to test the content of the solution particularly. 

If you can share sample data over here or if you can mail me at v-prasadboke@microsoft.com would be helpful.

**Comment by v-prasadboke** [comment]
Thanks @noodlemctwoodle, I'll take a look at it once.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
