### PR TITLE
AIShield AI Security Monitoring connector updates

### PR DESCRIPTION
**Pull request by udanashivm**
Added  Analytics rules to support Image Classification Evasion, NLP, TSF, Tabular Classification Extraction

Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@udanashivm: 
Sample data ingested looking fine 
image
Parser also looking fine
image
Could you please create a package for above changes.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review Analytic rules.Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review Analytic rules.Thanks!

**Review by aprakash13 — COMMENTED** [review]
Looks good from a analytics perspective, Please feel free to merge if other components of the PR looks good.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please provide your approval. Thanks!

**Review by aprakash13 — APPROVED** [review]
Thanks

**Comment by v-spadarthi** [comment]
@udanashivm : Could you please update the package with Analytics and Parser changes. Thanks

**Comment by udanashivm** [comment]
> @udanashivm : Could you please update the package with Analytics and Parser changes. Thanks

Done. Thanks

**Comment by v-spadarthi** [comment]
Looking fine
image
image

**Comment by udanashivm** [comment]
> Looking fine image image

@v-spadarthi Thanks for the review. Could you please merge this PR?

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
