### PR TITLE
update WebApplicationFirewallFirewallEvents.json and template validation

### PR DESCRIPTION
**Pull request by tobystic**
Required items, please complete
   
   Change(s):
  update WebApplicationFirewallFirewallEvents.json and template validation

   Reason for Change(s):
  - new AFD premium WAF profile view to be added 

   Version Updated:
   -Not required

   Testing Completed:
  Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Review by NikTripathi — CHANGES_REQUESTED** [review]
Please add the workbookMetadata.json file also.

**Review by shainw — APPROVED** [review]
Approving for now, we can go back and look at better ways to make sure the workbook doesn't fail for no data scenarios instead of using the "FakeData" table

**Comment by shainw** [comment]
@NikTripathi - Do you mean for @tobystic to update the version number in the workbookMetadata.json file or something else?

**Comment by NikTripathi** [comment]
> @NikTripathi - Do you mean for @tobystic to update the version number in the workbookMetadata.json file or something else?

Yes. We need to update the version number in workbookMetadata.json filr.

**Pull request merged**
