### PR TITLE
JIRA Sync Engine for Azure Sentinel incidents

### PR DESCRIPTION
**Pull request by ThijsLecomte**
This is all the code (Playbooks/Functions and documentation) for a solution which synchronizes incidents between Azure Sentinel and JIRA.

It's documented in the Readme file and in the following blog post:
https://thecollective.eu/blog/setting-up-a-bidirectional-sync-between-sentinel-and-jira/

Proof of execution for every Playbook:
Sync incidents:
image

Sync status:
image

Sync link:
image

Sync assigned user:
image

### CODE REVIEW

**Comment by preetikr** [comment]
@ThijsLecomte - Will set some time for us to sync on this and chart next steps. Thanks. 
@sreedharande - please review the playbooks associated with this PR and share feedback. Thanks.

**Review by sreedharande — APPROVED** [review]
Looks good

**Review by lior-tamir — APPROVED** [review]

**Comment by lior-tamir** [comment]
@dicolanl @KobyKoren @sarah-yo @liatlishams @Yaniv-Shasha @preetikr  Can someone please approve? I'm not the code owner, so cannot do it from my user. Thanks!

**Review by lior-tamir — APPROVED** [review]

**Comment by LinkMJB** [comment]
I don't see the content of this "merged" PR in the `master` branch -- did this PR get reverted? Am I nuts? 
- Exists in the origin branch: https://github.com/ThijsLecomte/Azure-Sentinel/tree/d33c190231f1e13c962deb6c85ab150349cb6c89/Solutions/Sync%20incidents%20with%20JIRA
- 404 on the master branch: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Sync%20incidents%20with%20JIRA

**Comment by ThijsLecomte** [comment]
@LinkMJB , it's here => https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Sync%20incidents%20with%20JIRA

**Pull request merged**
