### PR TITLE
Reopened - Claroty xDome Solution

### PR DESCRIPTION
**Pull request by roysagi**
Required items, please complete

Change(s):

Adding new data connector for Claroty xDome
Reason for Change(s):

We want to create a custom CEF connector that will appear in Sentinel's Content Hub.
Version Updated:

NA
Testing Completed:

Yes
Checked that the validations are passing and have addressed any issues that are present:

Yes

 - Reopen of https://github.com/Azure/Azure-Sentinel/pull/9837

### CODE REVIEW

**Comment by roysagi** [comment]
@v-prasadboke - continued here - sorry for the inconvenience

**Comment by roysagi** [comment]
@v-prasadboke - Hi again!
I am still seeing this PR fail on the categories - any idea what am I doing wrong?
I have another question but do not want to post it publicly - could you please send me a email to roy.s@claroty.com

**Comment by v-prasadboke** [comment]
Hello @roysagi, 
As discussed in the call, MS team will take care of Validation failure and Sample data case as well.

**Comment by roysagi** [comment]
Hi @v-prasadboke - the build process seems to be stuck here - is there anything I can do to help?

**Comment by v-prasadboke** [comment]
Hello @roysagi, 
Validations are resolved, to perform your required actions for Sample data you can visit this blog

**Comment by roysagi** [comment]
@v-prasadboke - a missing link to blog?

**Comment by v-prasadboke** [comment]
> @v-prasadboke - a missing link to blog?

I'm extremely sorry for the miss. 
Here's the link for the blog. Hope this might help you. 

https://xebia.com/blog/deleting-your-commit-history/

**Pull request closed without merging**
