### PR TITLE
Bugfix tactics - techniques mismatch

### PR DESCRIPTION
**Pull request by azurekid**
## Before submitting this PR please ensure that you have read the following sections and then completed the template below:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures, there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated tactics
    
## After the submission has been made, please look at the Validation Checks:

> Check that the validations are passing and address any issues that are present. Let us know if you have tried fixing and need help.

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

## PR Template

-----------------------------------------------------------------------------------------------------------
 **Description for the PR:**
  Some Rule Templates have a mismatch in the tactics and techniques according to the Mitre Framework
  This causes errors when updating the detection rules through code as shown here:
  
  
image

**Testing Completed:**
  Yes : 

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Thank you. The changes look good.
We are getting some validation error because of the need to update the version number. Can you please update the version number of the three files mentioned in the error message below?

You **did not** change the version in this file: Detections/AuditLogs/FirstAppOrServicePrincipalCredential.yaml.
You **did not** change the version in this file: Detections/AuditLogs/NewAppOrServicePrincipalCredential.yaml.
You **did not** change the version in this file: Detections/SecurityEvent/GainCodeExecutionADFSViaSMB.yaml.

**Review by azurekid — COMMENTED** [review]
updated the version numbers and added an empty line at the end where required

**Comment by aprakash13** [comment]
> updated the version numbers and added an empty line at the end where required

Thanks. It seems we are still getting the validation error. You might want to update the version numbers for below files as well:

You **did not** change the version in this file: **Detections/SecurityEvent/GainCodeExecutionADFSViaSMB.yaml.**
You **did not** change the version in this file: **Detections/SecurityEvent/RDP_MultipleConnectionsFromSingleSystem.yaml.**

**Comment by azurekid** [comment]
All tests passed.

image

**Review by aprakash13 — APPROVED** [review]
The changes look good. Thanks.

**Pull request merged**
