### PR TITLE
Updating known Oauth App's

### PR DESCRIPTION
**Pull request by tvjust**
Simply grabbed this non exhaustive list of native first party App ID's https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in 

   Required items, please complete
   
   Change(s):
   - Updated Oauth app id's 

   Reason for Change(s):
   - Provides a better level of filtering to queries [like this one](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/MaliciousOAuthApp_O365AttackToolkit.yaml) 

   Version Updated:
   - N/A

   Testing Completed:
   - No

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by tvjust** [comment]
@microsoft-github-policy-service agree [company="Red Canary"]

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
@tvjust : Please provide me the table name to ingest the sample data.

**Comment by v-spadarthi** [comment]
We wanted to check on the status of PR #6498 . [PR](https://github.com/Azure/Azure-Sentinel/pull/6498) is pending from more than 30 days. Let us know if any assistance is required for this PR. As Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-spadarthi** [comment]
Waiting for the update from author.

**Comment by v-mchatla** [comment]
Waiting for the update from author.

**Comment by v-spadarthi** [comment]
Hi @tvjust  Since we have not received response from more than 7 days, we are closing your [PR](https://github.com/Azure/Azure-Sentinel/pull/6498) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
