### PR TITLE
Vectra AI SaaS - Initial Analytic templates

### PR DESCRIPTION
**Pull request by danymello**
Required items, please complete
   
   Change(s):
   - Added 2 analytic templates for this solution.

   Reason for Change(s):
   - New content to integrate Vectra's signal into Sentinel workflows.
   
   Version Updated:
   - Yes. Initial version 1.0.0

   Testing Completed:
   - Partially using a script to parse YAML file and push it to Sentinel with New-AzSentinelAlertRule function (does not support all parameters).

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @danymello,
Please work on below points:

1. To resolve validation issue , please add a custom scehma table at below path.
   Path : https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.
   For reference you can check any table from CustomTables Folder.

2. If the rules are data connector dependent, need to add requiredDataConnectors property, please refer below Analytic rule.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Network%20Session%20Essentials/Analytic%20Rules/AnomalyFoundInNetworkSessionTraffic.yaml

3. Status,tactics,relevantTechniques are missing, please add it.

Thanks

**Comment by danymello** [comment]
> Hi @danymello, Please work on below points:
> 
> 1. To resolve validation issue , please add a custom scehma table at below path.
>    Path : https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.
>    For reference you can check any table from CustomTables Folder.
> 2. If the rules are data connector dependent, need to add requiredDataConnectors property, please refer below Analytic rule.
>    https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Network%20Session%20Essentials/Analytic%20Rules/AnomalyFoundInNetworkSessionTraffic.yaml
> 3. Status,tactics,relevantTechniques are missing, please add it.
> 
> Thanks

Custom table schemas are already there: 

- Entity_Scoring_Data_CL: https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/CustomTables/Entity_Scoring_Data_CL.json
- Detections_Data_CL: https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/CustomTables/Detections_Data_CL.json

Analytic rules are using Parsers/Functions available in the Vectra XDR Solution. I added the connector requirements in both.

I added status only. I cannot map to any MITRE technics/techniques with the data available.

let me know if you see any other issue?

**Comment by v-rusraut** [comment]
Hi @danymello,

- To resolve validation error, we need to add table schemas for below
1. VectraDetections
2. VectraEntityScoring

Please add it in below path :
Path : https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.


- Please remove plus symbol from query 

image

Thanks

**Comment by danymello** [comment]
> Hi @danymello,
> 
> * To resolve validation error, we need to add table schemas for below
> 
> 1. VectraDetections
> 2. VectraEntityScoring
> 
> Please add it in below path : Path : https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.
> 
> * Please remove plus symbol from query
> 
> image
> 
> Thanks

All implemented.

**Comment by danymello** [comment]
> Hi @danymello,
> 
> * To resolve validation error, we need to add table schemas for below
> 
> 1. VectraDetections
> 2. VectraEntityScoring
> 
> Please add it in below path : Path : https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.
> 
> * Please remove plus symbol from query
> 
> image
> 
> Thanks

@v-rusraut, can we check if we are all good now?

**Pull request merged**
