### PR TITLE
Create workbook.json

### PR DESCRIPTION
**Pull request by AlexDeMichieli**
Adding workbook integration file

   Required items, please complete
   
   Change(s):
   - latest integration version

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@AlexDeMichieli :Please fix the validation errors and below issues as well
image
image
image
image
image

**Comment by AlexDeMichieli** [comment]
Hello @v-spadarthi , all checks have passed! I am unable to reproduce the error you're getting. There's a chance that your connector isn't set up correctly and you're not getting the data needed? You can follow the steps here:

https://github.com/Azure/Azure-Sentinel/blob/vetadika-testrepo/Solutions/GitHub/Data%20Connectors/GithubWebhook/README.md

On the GitHub side, you should allow the webhooks to send everything, or you could also check individual values. You may want to wait until some data is sent through the connector before starting to query as if no alerts are sent, some queries might throw errors.

**Comment by AlexDeMichieli** [comment]
You can also try to re run the query for the drop down menu, here's a video:

https://drive.google.com/file/d/1rY9piztAtK-yHCXp48hoGMYYjrZG6emT/view?usp=sharing

**Comment by v-spadarthi** [comment]
@AlexDeMichieli : Could you please provide us the sample data.

**Comment by AlexDeMichieli** [comment]
Hey @v-spadarthi, data can be retrieved by adding the webhook URL provided by the function referenced [in 
this guide ](https://github.com/Azure/Azure-Sentinel/blob/vetadika-testrepo/Solutions/GitHub/Data%20Connectors/GithubWebhook/README.md) to a GitHub org. 

Screen Shot 2022-08-01 at 11 03 48 PM

Let me know if you have any questions, I can always jump on a call if that makes it easier!

**Comment by v-spadarthi** [comment]
Looks Good. I have tested in "loganalyticsdevvetadika" workspace given by Prathibha.
image
image
image
image

@AlexDeMichieli : If you have any preview images for workbook you can add them.

**Comment by AlexDeMichieli** [comment]
Hey @v-spadarthi , I'm glad it's working as expected! I'm adding some images below, they're a bit tiny as the boards are wide and I tried to capture all the views together. 

# Secret Scanning 
secret_scanning

# Advanced Security
Advanced_Security

# Code Scanning
Code_Scanning

# Dependabot Alerts
Dependabot_Alerts

**Review by v-spadarthi — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
