### PR TITLE
Update BloodHound Enterprise Solution function app

### PR DESCRIPTION
**Pull request by gwhite-so**
Required items, please complete
   
   Change(s):
   - Update bhe_client.py function app data connector with new findings API endpoint

   Reason for Change(s):
   - The old findings API will be deprecated

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, Can you share invocation logs screenshot over here

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, can you share the invocation logs of the funciton app

**Comment by v-prasadboke** [comment]
Hello @gwhite-so we are waiting for the invocation logs can you please share them over here.

**Comment by gwhite-so** [comment]
> Hello @gwhite-so we are waiting for the invocation logs can you please share them over here.

Hey @v-prasadboke, sorry for the delayed response. It appears the aka.ms links in the Solution are not working. Could you update the aka.ms links so they are working and I'll deploy the app and send screenshots of the invocation logs.

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, 

- Go to your existing deployed function app. Select **Environment Variables** from the given option in left blade.
- Scroll down and click on **WEBSITE_RUN_FROM_PACKAGE**.
- A window will slide in right, and in the value option put this URL 
https://github.com/gwhite-so/Azure-Sentinel/raw/BHEUpdate/Solutions/BloodHound%20Enterprise/Data%20Connectors/bhe-funcapp.zip


image

**Comment by v-prasadboke** [comment]
Hello @gwhite-so please provide feedback to the above mentioned comment

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, we are waiting for your feedback

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, Can you please share invocation logs

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, Can you please provide us requested images above

**Comment by v-prasadboke** [comment]
We wanted to check on the status of PR #10701. PR is pending for more than 30+ days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by StephenHinck** [comment]
We'll get this information together for you over the next couple of weeks!

**Comment by v-prasadboke** [comment]
Hello @StephenHinck, Thanks for the reply. Will be waiting for the updates

**Comment by v-prasadboke** [comment]
Hello @gwhite-so, Its been long we havent heard anything from you yet. 

Can you provide us some update on this.

**Comment by v-prasadboke** [comment]
Hello @StephenHinck, Your last feedback on this PR was 60+ days ago. Could you please put on a expected date for us or atleast move this PR to draft state

**Comment by v-prasadboke** [comment]
as mentioned in the pr #11380 
There are major modifications in the PR and a new one has been raised for the same. 

Closing on this PR

**Pull request closed without merging**
