### PR TITLE
Removes trailing whitespace

### PR DESCRIPTION
**Pull request by Phrozyn**
Required items, please complete
   
   Change(s):
   - Updates to several threathunting queries and a sentinel detection to remove trailing whitespace.

   Reason for Change(s):
   - The trailing whitespace leads to programmatical issues when trying to work with these rules.

   Version Updated:
   - Did not feel this was needed, no logic updates were made, please correct me if this is in error.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes, these now pass our validations, where they previously failed due to the trailing whitespace, not sure how they got through your validations.

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please check hunting queries and provide an update. Thanks!

**Review by aprakash13 — APPROVED** [review]
Thanks

**Pull request merged**
