### PR TITLE
Create ASR--Rule-Ransomware-triggered.yaml

### PR DESCRIPTION
**Pull request by Bert-JanP**
Required items, please complete
   
   Change(s):
   - Added ASR--Rule-Ransomware-triggered

   Reason for Change(s):
   - Extra detection to detect possible starts of ransomware attacks

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Please fix the validation errors
Also add the relevantTechnique and entityMapping fields to the query.
Fell free to comment if help is needed for this.

**Comment by Bert-JanP** [comment]
How do I fix the last validation error about the DocumentsLinkValidation?

**Comment by v-spadarthi** [comment]
@aprakash13 : Please help to resolve the validation error and  review the hunting queries.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please help to resolve the validation error and review the hunting queries.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please help them to resolve the validation error and review the hunting queries.

**Review by aprakash13 — APPROVED** [review]
Thanks.

**Pull request merged**
