### PR TITLE
Forcepoint CSG Template Spec

### PR DESCRIPTION
**Pull request by elforb**
Change(s):
- Creating Forcepoint CSG Template Spec package with Data Connector and Workbook

Reason for Change(s):
- Solution Migration Effort is in progress

### CODE REVIEW

**Review by anki-narravula — COMMENTED** [review]
Publisher Id is not available for this. Waiting for Eric to provide publisher Id, once it is available we need to change and merge. Otherwise it looks good.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-spadarthi** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Review by v-mchatla — DISMISSED** [review]
Changes looks good. Approving the PR

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric on for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-mchatla** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-amolpatil** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Comment by v-spadarthi** [comment]
We are waiting on the confirmation from Eric for Solution Id

**Review by v-mchatla — APPROVED** [review]
Changes looks good. Approving the PR

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
