### PR TITLE
Add Mimecast TI Targeted Data connector

### PR DESCRIPTION
**Pull request by lstajcic**
## Proposed Changes

  - Add Mimecast TI Targeted Data connector

### CODE REVIEW

**Comment by lstajcic** [comment]
NPM install is failing in the pipeline.

**Comment by lstajcic** [comment]
I also need advice on what dataTypes field should look like for this Data connector. Data is submitted via https://docs.microsoft.com/en-us/graph/api/resources/tiindicator?view=graph-rest-beta so it is using ThreatIntelligenceIndicator table but this is Azure-Function Data connector. Also data is sent to Windows Defender ATP, not to Azure Sentinel in this one but the table it is using is still ThreatIntelligenceIndicator I guess.

Thank you in advance.

**Comment by v-sabiraj** [comment]
Hey @lstajcic, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by v-sabiraj** [comment]
Hey @lstajcic, request you to please update your PR branch with the latest changes from Azure:master so that the PR Validations can be executed. Thanks.

**Comment by v-sabiraj** [comment]
Data Connector Validation Failed. **MimecastTITargeted_API_AzureFunctionApp.json**  no such file or directory, open '.script/utils/schemas/_ConnectorSchema.json'. Please fix this , thanks.

**Comment by v-sabiraj** [comment]
Please add 'connectivityCriterias' for dataconnectors, Connectivity criteria should not be empty. Thanks.

**Comment by lstajcic** [comment]
@v-sabiraj I cannot add Connectivity criteria because there is no data in Log Analytics. This connector is used to send data to Windows Defender ATP.

**Comment by v-sabiraj** [comment]
Data Connector Validation Failed. MimecastTITargeted_API_AzureFunctionApp.json no such file or directory, open '.script/utils/schemas/_ConnectorSchema.json'. Please fix this , thanks.

**Comment by v-sabiraj** [comment]
Please update deploy to azure as **https://aka.ms/sentinel-MimecastTITargetedConnectorAzureFunctions-azuredeploy**

**Comment by lstajcic** [comment]
> Please update deploy to azure as **https://aka.ms/sentinel-MimecastTITargetedConnectorAzureFunctions-azuredeploy**

Done.

**Comment by lstajcic** [comment]
> Data Connector Validation Failed. MimecastTITargeted_API_AzureFunctionApp.json no such file or directory, open '.script/utils/schemas/_ConnectorSchema.json'. Please fix this , thanks.

@v-sabiraj Fixed.

**Comment by v-sabiraj** [comment]
Please update the deploy to azure with correct format. 
image
(https://aka.ms/deploytoazurebutton) must be in first bracket, thankyou.

**Comment by v-sabiraj** [comment]
@lstajcic , please fix the requested changes , thanks.

**Comment by v-sabiraj** [comment]
Please add graphQueries and sampleQueries, thanks.

**Comment by lstajcic** [comment]
@v-sabiraj it is not possible to add those queries because data is going to Windows Defender ATP.

**Comment by v-sabiraj** [comment]
> I also need advice on what dataTypes field should look like for this Data connector. Data is submitted via https://docs.microsoft.com/en-us/graph/api/resources/tiindicator?view=graph-rest-beta so it is using ThreatIntelligenceIndicator table but this is Azure-Function Data connector. Also data is sent to Windows Defender ATP, not to Azure Sentinel in this one but the table it is using is still ThreatIntelligenceIndicator I guess.
> 
> Thank you in advance.

Hey @lstajcic , as you mentioned, you are not posting data to Azure Sentinel instead sending the logs directly to Windows Defender ATP, there is no point in having this Data Connector here in Sentinel as the main purpose of having connector is not satisfied. Can you please move this to Windows Defender ATP repo?  Please let us know your thoughts and we can close this PR... Thanks

**Comment by lstajcic** [comment]
@v-sabiraj I am consulting with my product manager. Will get back to you.

**Comment by lstajcic** [comment]
@v-sabiraj Alright, it will be moved to Defender ATP repo in the future. We can close this one 😞

**Comment by NikTripathi** [comment]
Closing as per author's response.

**Pull request closed without merging**
