### PR TITLE
Added Pure Storage package

### PR DESCRIPTION
**Pull request by skeerthivasan**
Change(s):
   Initial Solution release for Pure Storage

   Reason for Change(s):
   Adding Parser only solution package for PureStorage

   Version Updated:
   No - First release

   Testing Completed:
    Yes

   Checked that the validations are passing and have addressed any issues that are present:
   Yes

### CODE REVIEW

**Comment by skeerthivasan** [comment]
@v-prasadboke , how to add multiple author name in the file - Solutions/Pure Storage/Data/Solution_PureStorage.json.
I see example as string, shall I put it as a list and proceed ? pls suggest.

**Comment by v-prasadboke** [comment]
Hello @skeerthivasan, You can put author name as Organization's name

**Comment by skeerthivasan** [comment]
> Hello @skeerthivasan, You can put author name as Organization's name

Thanks, I will update, repackaging is needed for this change ? or just editing will be fine ?

**Comment by v-prasadboke** [comment]
Repackaging is needed

**Comment by skeerthivasan** [comment]
> Repackaging is needed

Thanks, will do. We were following this readme, if org name to be filled as author - then input file section in the below needs update, pls check.
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3

**Comment by v-prasadboke** [comment]
> > Repackaging is needed
> 
> @v-prasadboke Thanks, will do. We were following this readme, if org name to be filled as author - then input file section in the below needs update, pls check. https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3

Thanks @skeerthivasan, for pointing this out.

**Comment by v-prasadboke** [comment]
Hello @skeerthivasan, I mistakenly force pushed in this branch. Can you please correct author once.

**Comment by v-prasadboke** [comment]
Other than this everythings good.

**Comment by skeerthivasan** [comment]
> Other than this everythings good.

@v-prasadboke , I've pushed it again, please check and proceed with further process

**Comment by skeerthivasan** [comment]
> > Other than this everythings good.
> 
> @v-prasadboke , I've pushed it again, please check and proceed with further process

@v-prasadboke , please check this PR and let me know if more info required from my side.
Else, proceed with further process

**Comment by v-prasadboke** [comment]
Sorry for the late reply @skeerthivasan, Ill get it done 
Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by skeerthivasan** [comment]
@v-atulyadav @v-prasadboke We have attempted to this solution package while creating Solution Offer in Market Place.
While uploading zip file, getting below error. Please suggest.

Package acceptance validation error: JsonSchemaValidationError The json file 'createUiDefinition.json' is invalid for the provided schema. Line Number: '0', Error: 'Invalid type. Expected Array but got Null.'

**Pull request merged**
