### PR TITLE
Fixes for IoT Solution Packages - bug fixes and new content

### PR DESCRIPTION
**Pull request by amitcohen25**
Required items, please complete
   
   Change(s):
   - Updated 14 existing analytic rules in IoTOTThreatMonitoringwithDefenderforIoT solution package with bug fixes: changed KQLS
   - Added 1 new analytic rule 
   - Edited workbook with new link
   
   Reason for Change(s):
   - Customer requests
   - Bug fixes

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Overall, the changes to the queries look good. 
However, there is one field **sentinelEntitiesMappings** that has been added to each of the analytic template. This is not part of the standard analytic template as documented here : https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide

Not sure if this is needed. Wondering, if this can be removed from the queries.

**Comment by NikTripathi** [comment]
> Overall, the changes to the queries look good. However, there is one field **sentinelEntitiesMappings** that has been added to each of the analytic template. This is not part of the standard analytic template as documented here : https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide
> 
> Not sure if this is needed. Wondering, if this can be removed from the queries.

image
image

**Review by NikTripathi — APPROVED** [review]

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Comment by v-sabiraj** [comment]
> > Overall, the changes to the queries look good. However, there is one field **sentinelEntitiesMappings** that has been added to each of the analytic template. This is not part of the standard analytic template as documented here : https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide
> > Not sure if this is needed. Wondering, if this can be removed from the queries.
> 
> image image

Hey @aprakash13, can you please check and approve this, thanks.

**Review by aprakash13 — APPROVED** [review]
Discussed with Amit about the new entity type. Approving this now.

**Pull request merged**
