### PR TITLE
Create AS-StealthDefend.yaml

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - New parser

   Reason for Change(s):
   - New parser

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @AcceleryntSecurityDev, 
Yaml file validation failures please check below error.
image
It is not possible for me to make changes to this forked branch until I become a contributor. Please send me an invitation link for contribution by going to Settings and looking for contributor.

**Comment by AcceleryntSecurityDev** [comment]
@v-atulyadav I removed the whitespace at the end of the file. Waiting to see if the new checks pass... It looks like you are already a contributor:
image
If this is not the case, am I looking in the right place, in the repository settings? https://github.com/Accelerynt-Security/Azure-Sentinel/settings/access 
I cannot find anything about adding contributors. Which endpoint should I be looking under? i.e.: /settings/[endpoint]

**Comment by v-atulyadav** [comment]
Hi @AcceleryntSecurityDev, I will check this. Thanks

**Comment by v-atulyadav** [comment]
Hi @AcceleryntSecurityDev, I will check this. Thanks

**Comment by v-atulyadav** [comment]
Hi @AcceleryntSecurityDev, 
I am still facing issues with pushing this branch. I have modified the file to pass validations. Please extract the zip file below and push the attached file to the PR.
[AS-StealthDefend.zip](https://github.com/Azure/Azure-Sentinel/files/13423789/AS-StealthDefend.zip)

**Comment by AcceleryntSecurityDev** [comment]
@v-atulyadav changes have been made, thank you

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
