### PR TITLE
Adding DoD Zero Trust Strategy Workbook v1.0 (Stand-alone)

### PR DESCRIPTION
**Pull request by ChhornGLim**
Change(s): 
   - Adding DoD Zero Trust Strategy Workbook v1.0 (Stand-alone)

   Reason for Change(s):
   - New Sentinel workbook in support of the latest DoD Zero Trust Strategy

   Version Updated: 
   - n/a (initial release v1.0 / minor revisions will be x.x and major revisions will be x.0)
   
  Testing Completed: 
   - Yes

   Checked that the validations are passing and have addressed any issues that are present: 
   - Yes

### CODE REVIEW

**Comment by ChhornGLim** [comment]
> @ChhornGLim please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

**Comment by ChhornGLim** [comment]
> > @ChhornGLim please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> > ```
> > @microsoft-github-policy-service agree [company="{your company}"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Options:
> > > 
> > > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > > 
> > > ```
> > > @microsoft-github-policy-service agree
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > > 
> > > ```
> > > @microsoft-github-policy-service agree company="Microsoft"
> > > ```
> > 
> > 
> > Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Comment by v-prasadboke** [comment]
Hello @ChhornGLim, Please change fromtemplateid 
  "fromTemplateId": "sentinel-UserWorkbook",

**Comment by ChhornGLim** [comment]
> Hello @ChhornGLim, Thank you for raising this PR. This PR will be investigated, Also can you please share sample data to test the workbook. And Please change fromtemplateid "fromTemplateId": "sentinel-UserWorkbook"

Done! Thank you, @v-prasadboke !

**Comment by ChhornGLim** [comment]
> Hello @ChhornGLim, Thank you for sharing the sample data. Continue to review this PR and update you about the same before 12 September, 2023.

Thank you for the update and assistance, @v-prasadboke!

**Comment by v-prasadboke** [comment]
Hello @ChhornGLim, Please resolve the validation fails. A link at line 15254 contains a hardcoded link. This link refers to a specific LA workspace which should not be the case. 

Also another check is failing for Links containing .us which should be replaced with .com. Thanks

**Comment by ChhornGLim** [comment]
> Hello @ChhornGLim, Please resolve the validation fails. A link at line 15254 contains a hardcoded link. This link refers to a specific LA workspace which should not be the case.
> 
> Also another check is failing for Links containing .us which should be replaced with .com. Thanks

@v-prasadboke - Thanks for bringing this to our attention! Links have been fixed and we have validated .us portal links.

**Comment by v-prasadboke** [comment]
1.    Hello @ChhornGLim, All the documentation links in the workbook should have .com links not .us  
       Please replace the [ https://____.us ] with [ https://____.com ].

2.    Simliar case has been found Same as earlier for hardcoded link mentioned at line 19407 , 
image

**Comment by v-prasadboke** [comment]
Hello @ChhornGLim, We are still investigating this PR. 
We will update you about the same before 19 September 2023.

**Comment by ChhornGLim** [comment]
> Hello @ChhornGLim, We are still investigating this PR. We will update you about the same before 19 September 2023.

@v-prasadboke - Removed all "/en-us/" from docs/resource links and cleaned up one remaining subscription-specific link (https://github.com/Azure/Azure-Sentinel/pull/8950/commits/a196fd345905f735a8fbbb53f99fc066add77951). Thanks!

**Review by v-prasadboke — APPROVED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
