### PR TITLE
Correct spelling errors for dynamics365workbooks

### PR DESCRIPTION
**Pull request by IISlapDashII**
Change(s):
   - Updated spelling errors in Dynamics365Workbooks.json
   - Updated Dynamics365WorkbookWhite.png - Reflected spelling changes
   - Updated Dynamics365WorkbookBlack.png - Reflected spelling changes

   Reason for Change(s):
   - Spelling errors (immediately noticeable)

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

### CODE REVIEW

**Comment by IISlapDashII** [comment]
@microsoft-github-policy-service agree

**Comment by v-spadarthi** [comment]
@IISlapDashII : Please fix the typos and validation error
1. Please correct the fromtemplateId
image
2. Please increase the version of the workbook in workbook meta data in below path https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json
3. Please fix the below typos
image
image
image

**Review by IISlapDashII — COMMENTED** [review]
Changes made & updated

**Comment by v-spadarthi** [comment]
@IISlapDashII : We could see still typos are there please fix it below as well.
In Record Retrieval Events section we could see still typos please fix it
image
In Record Export Events section we could see still typos please fix it
image
In Email Events  section we could see still typos please fix it
image

Once done the above changes please increase the version(Solution_Dynamics365.json) of the package and do the re-package it again.

**Comment by IISlapDashII** [comment]
@v-spadarthi My bad I have made the additional changes as advised. (Surprised V1 originally scrapped past).

**Comment by v-spadarthi** [comment]
@IISlapDashII : Could you please re-package it again by using V2 tool and please increase the version(Solution_Dynamics365.json) of the Input file.

**Comment by v-spadarthi** [comment]
We are moving the contents to standalone folders from solution folder for referenced [PR](#6594)

**Review by v-spadarthi — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Comment by v-dvedak** [comment]
Approved and merged since Suresh's has approved the PR

**Pull request merged**
