### PR TITLE
CyberARK EPM analytic content

### PR DESCRIPTION
**Pull request by spsocprime**
Required items, please complete
   
   Change(s):
   - Analytic content initial PR

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @aprakash13, will you please review Analytic Rules and Hunting queries, thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13, will you please review Analytic Rules and Hunting queries, thanks.

**Review by aprakash13 — APPROVED** [review]
Overall looks ok from a query perspective. Please feel free to merge if other components look good.

**Review by v-sabiraj — APPROVED** [review]
Workbook looks good.

**Pull request merged**
