### PR TITLE
Cisco ISE Data Connector - fix workbook

### PR DESCRIPTION
**Pull request by vu-socprime**

### CODE REVIEW

**Review by v-admahe — APPROVED** [review]

**Comment by preetikr** [comment]
@v-jayakal - please review this workbook change and move to solutions workbook for ISE - thanks

**Comment by v-jayakal** [comment]
@vu-socprime, the workbook for Cisco ISE has been moved to https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Cisco%20ISE/Workbooks folder. Can you please update the file and the PR? Updating of that file will resolve the conflict, Thanks.

**Comment by v-jayakal** [comment]
@vu-socprime, can you please raise a PR on the solution folder file? I have a sample PR here for reference https://github.com/Azure/Azure-Sentinel/pull/1954

**Comment by vu-socprime** [comment]
> @vu-socprime, can you please raise a PR on the solution folder file? I have a sample PR here for reference #1954

@v-jayakal I have creted new PR https://github.com/Azure/Azure-Sentinel/pull/1959

**Comment by v-jayakal** [comment]
New PR #1959 has been created for this, hence closing.

**Pull request closed without merging**
