### PR TITLE
Update in description of creatUIDefinition.json

### PR DESCRIPTION
**Pull request by MuhammadAli-snx**
Change(s):
   - Updated the description of createUIDefinition.json
   - Synced the description of createUIDefinition.json of package file.

   Reason for Change(s):
   - Concerns raised while publishing on marketplace

   Checked that the validations are passing and have addressed any issues that are present:
   - The test cases while creating the package are passed.

### CODE REVIEW

**Comment by MuhammadAli-snx** [comment]
> @MuhammadAli-snx please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="SlashNext Inc."
> > ```
> 
> Contributor License Agreement
> ### Contribution License Agreement
> 
> This Contribution License Agreement (**“Agreement”**) is agreed to by the party signing below (**“You”**), and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your contributions to Microsoft open source projects. This Agreement is effective as of the latest signature date below.
> 
>     1. **Definitions**.
>        **“Code”** means the computer software code, whether in human-readable or machine-executable form,
>        that is delivered by You to Microsoft under this Agreement.
>        **“Project”** means any of the projects owned or managed by Microsoft and offered under a license
>        approved by the Open Source Initiative ([www.opensource.org](http://www.opensource.org)).
>        **“Submit”** is the act of uploading, submitting, transmitting, or distributing code or other content to any
>        Project, including but not limited to communication on electronic mailing lists, source code control
>        systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
>        discussing and improving that Project, but excluding communication that is conspicuously marked or
>        otherwise designated in writing by You as “Not a Submission.”
>        **“Submission”** means the Code and any other copyrightable material Submitted by You, including any
>        associated comments and documentation.
> 
>     2. **Your Submission**. You must agree to the terms of this Agreement before making a Submission to any
>        Project. This Agreement covers any and all Submissions that You, now or in the future (except as
>        described in Section 4 below), Submit to any Project.
> 
>     3. **Originality of Work**. You represent that each of Your Submissions is entirely Your original work.
>        Should You wish to Submit materials that are not Your original work, You may Submit them separately
>        to the Project if You (a) retain all copyright and license information that was in the materials as You
>        received them, (b) in the description accompanying Your Submission, include the phrase “Submission
>        containing materials of a third party:” followed by the names of the third party and any licenses or other
>        restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
>        guidelines concerning Submissions.
> 
>     4. **Your Employer**. References to “employer” in this Agreement include Your employer or anyone else
>        for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
>        Submission is made in the course of Your work for an employer or Your employer has intellectual
>        property rights in Your Submission by contract or applicable law, You must secure permission from Your
>        employer to make the Submission before signing this Agreement. In that case, the term “You” in this
>        Agreement will refer to You and the employer collectively. If You change employers in the future and
>        desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
>        and secure permission from the new employer before Submitting those Submissions.
> 
>     5. **Licenses**.
> 
> 
>     * **Copyright License**. You grant Microsoft, and those who receive the Submission directly or
>       indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
>       Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
>       the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
>       parties.
> 
>     * **Patent License**. You grant Microsoft, and those who receive the Submission directly or
>       indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
>       Your patent claims that are necessarily infringed by the Submission or the combination of the
>       Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
>       import or otherwise dispose of the Submission alone or with the Project.
> 
>     * **Other Rights Reserved**. Each party reserves all rights not expressly granted in this Agreement.
>       No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
>       granted by implication, exhaustion, estoppel or otherwise.
> 
> 
>     6. **Representations and Warranties**. You represent that You are legally entitled to grant the above
>        licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
>        have disclosed under Section 3). You represent that You have secured permission from Your employer to
>        make the Submission in cases where Your Submission is made in the course of Your work for Your
>        employer or Your employer has intellectual property rights in Your Submission by contract or applicable
>        law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
>        have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
>        You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
>        REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
>        EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
>        PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
>        NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
> 
>     7. **Notice to Microsoft**. You agree to notify Microsoft in writing of any facts or circumstances of which
>        You later become aware that would make Your representations in this Agreement inaccurate in any
>        respect.
> 
>     8. **Information about Submissions**. You agree that contributions to Projects and information about
>        contributions may be maintained indefinitely and disclosed publicly, including Your name and other
>        information that You submit with Your Submission.
> 
>     9. **Governing Law/Jurisdiction**. This Agreement is governed by the laws of the State of Washington, and
>        the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
>        Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
>        exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
>        defenses of lack of personal jurisdiction and forum non-conveniens.
> 
>     10. **Entire Agreement/Assignment**. This Agreement is the entire agreement between the parties, and
>         supersedes any and all prior agreements, understandings or communications, written or oral, between
>         the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

**Comment by MuhammadAli-snx** [comment]
> @MuhammadAli-snx please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="SlashNext Inc."
> > ```
> 
> Contributor License Agreement

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, Thanks for raising this PR. This PR will be investigated and we will come back to you with an update by 19 February, 2024

**Comment by v-prasadboke** [comment]
No option to select while creating playbook. Kindly please look into this 
image

**Comment by MuhammadAli-snx** [comment]
> No option to select any value while creating playbook. Kindly please look into this image

When I deploy Playbook/SlashNextSecurityEventsForMSSentinel/azuredeploy.json using "Deploy from a Custom Template", it gives all the options as shown below. Kindly mention the file that you are trying to deploy and how, so I can reproduce the problem if it is.

Missing input issue

**Comment by v-prasadboke** [comment]
Try to create playbook from automation blade in Azure portal after custom deploying the maintemplate

**Comment by v-prasadboke** [comment]
Deploy the maintemplate to your Workspace. 
Head to content hub blade and search for solution. Click on the solution, in the lower right corner you will se option manage. 
Click on manage it would take you to Solutions page, here you will see playbook. 
Click on it and a option would appear in the lower right corner to create playbook.
Click on it and it would take you to Automation blade, again click on the playbook a option would appear to create playbook in the lower right corner. 
Head towards parameters section you will come to know the issue

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, 
Can we go on a call for this. I work in IST time zone. And my mail id is v-prasadboke@microsoft.com 
You can directly ping me on teams to discuss more about this.

**Comment by MuhammadAli-snx** [comment]
> v-prasadboke@microsoft.com

I have shared a meeting link over teams with you. Please check.

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx,
As discussed on the call you will be sharing the solution id. 
And I will check if there are any other solution with the same issue or fix. 
Also I'll be taking care of the solution for which it was declined from the partner center. 

Thanks,
Prasad

**Comment by MuhammadAli-snx** [comment]
**Points discussed in meeting with @v-prasadboke :**

- The earlier version of SlashNext SIEM app that we were trying to publish, does not have any issues with it. The raised concerns are to be fixed on Microsoft end.
- The issue of boolean values is to be investigated by Microsoft Sentinel team because the playbook we created works as intended. 
- The offer id is : **slashnext1598548183597.slashnext-security-events-for-microsoft-sentinel** 
- Microsoft Sentinel team will let us know further.

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke,

Any update regarding the drop down issue?

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, We have discussed this issue with Engineering team and its currently under analysis. 
Sorry for the delay but we will get this done soonest. 

Thanks,
Prasad

**Comment by v-prasadboke** [comment]
Hi @MuhammadAli-snx, We tried comparing the template from developer tools of playbook. They are irrelevant.
We have engineering team working on it.

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, 
After discussion with Engineering team we have came to know the playbooks template is a bit incorrect. 
Working on it. Will update you about it soonest.

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, We have came to know the issue we are facing for data type boolean is a bug.
Also I have found other problem. We have one parameter in playbook with integer data type. But while creating the playbook the type casting doesnt performs as expected. 

It is not accepting the integer value as integer but as string. 

image

We are working on it and get back to you soonest. 

Thanks and sorry for the inconvenience,
Prasad

**Comment by v-prasadboke** [comment]
Hello Ali, We have a update from content hub team 
The Automation playbook parameters page is designed to only accept string text boxes for Boolean and SecurityString data types.

But for int data type they have marked it as a bug and will be working on to resolve it.

For Boolean and SecureString data types, we don't support them currently, so this is a feature request. We will consider adding this feature in the next semester, but we don't have a specific timeline yet.

**Comment by MuhammadAli-snx** [comment]
Hi Prasad, 

Previously, SlashNext Security Events for Microsoft Sentinel app was **approved** by the Microsoft review team on 23 August 2023. When our team tried to **publish** the approved app on 29 January 2024, there were some concerns raised in the Microsoft Partner Center and those concerns were to be fixed and approved before publishing the app again. There is **NO** change in the code base related to the issues that you have reported regarding int and boolean data types as the previous app was approved and no concerns were raised.

Can you clarify that why these issues were not raised when the previous PR was approved? 

Link for the previously approved PR: https://github.com/Azure/Azure-Sentinel/pull/8140

Thanks.

**Comment by v-prasadboke** [comment]
> Hi Prasad,
> 
> Previously, SlashNext Security Events for Microsoft Sentinel app was **approved** by the Microsoft review team on 23 August 2023. When our team tried to **publish** the approved app on 29 January 2024, there were some concerns raised in the Microsoft Partner Center and those concerns were to be fixed and approved before publishing the app again. There is **NO** change in the code base related to the issues that you have reported regarding int and boolean data types as the previous app was approved and no concerns were raised.
> 
> Can you clarify that why these issues were not raised when the previous PR was approved?
> 
> Link for the previously approved PR: #8140
> 
> Thanks.

Hello @MuhammadAli-snx, 
You may have noticed I requested playbook images in the PR comments. Which you shared them.
Validated the playbook images and was approved on the basis of Images.

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, Please try to deploy the maintemplate from the latest commit pushed by me. 

Please try to create playbook from Content hub of your workspace

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke,

I have followed the steps and ran into an error while deploying the Playbook in Automation blade. The error is **ApiNotFound**. In maintemplate.json file, there is an API and the logic for the playbook. 

Previously, when I used to deploy the maintemplate, two templates were deployed i.e., API (Logic Connector) and Playbook. 

Now, it deploys three templates and the template I am trying to deploy requires the API (Logic Connector) to be deployed prior to  its deployment. There is no option to deploy the API (Logic Connector) either.

Kindly guide further.

**Comment by v-prasadboke** [comment]
Hi, Ali.
Fixed the playbook. 

Actually, the playbook connector and playbook were not properly mapped.

You can deploy the main template once and check it. 
Please notify me if any issues arise.

**Review by v-prasadboke — APPROVED** [review]

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke , 

I have tested it on my end, it works fine now.

**Review by v-atulyadav — APPROVED** [review]

**Review by v-sabiraj — DISMISSED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke @v-sabiraj @v-atulyadav ,

I am facing an issue while deploying the app from the marketplace. Can we schedule a call today and review the issue that I am having?

Thanks.

**Pull request merged**
