### PR TITLE
Create AS-StealthDefend.yaml

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Required items, please complete
   
   Change(s):
- New parser

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Thanks for raising this PR. Can you please provide me access to your branch.

**Comment by AcceleryntSecurityDev** [comment]
@v-prasadboke from what I can tell, this branch is public. What specifically do you need me to do?

**Comment by v-prasadboke** [comment]
As this is a forked branch I cannot push changes to this branch until I became a contributor to it. So to do that head to Settings look for contributor and send me an invitation link for contribution.

**Comment by v-prasadboke** [comment]
FunctionQuery: |
    CommonSecurityLog
    | where DeviceVendor == "STEALTHbits Technologies"
    | where DeviceProduct == "StealthDEFEND"
    | extend 
        threatType = extract("threatType=([^;]+)", 1, AdditionalExtensions),
        threatTime = todatetime(extract("threatTime=([^;]+)", 1, AdditionalExtensions)),
        users = extract("users=([^;]+)", 1, AdditionalExtensions),
        computers = extract("computers=([^;]+)", 1, AdditionalExtensions),
        fileName = extract("fileName=([^;]*)", 1, AdditionalExtensions), 
        newFileName = extract("newFileName=([^;]*)", 1, AdditionalExtensions), 
        process = extract("process=([^;]*)", 1, AdditionalExtensions), 
        evidence = extract("evidence=(.+)", 1, AdditionalExtensions)
        
        You can paste this query, this would resolve the validation error. Also can you share queries output screenshot.
Thanks.

**Comment by AcceleryntSecurityDev** [comment]
@v-prasadboke hmm, I've never had to do something like this before and it looks like this would eat up limited resources for my company. I'm just going to try and open a new PR rather than messing with something like this. 
image

**Comment by v-prasadboke** [comment]
[AS-StealthDefend.zip](https://github.com/Azure/Azure-Sentinel/files/13247326/AS-StealthDefend.zip)
Hello @AcceleryntSecurityDev instead pf creating a new branch please replace the parser of your branch with the parser in the zip. 
Thanks

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Please respond to the above mentioned changes.

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Please respond to the above mentioned comments.

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, You might be busy with something which is why its taking long to reply. 
It would be helpful if you provide us some updates on this. 
Thanks.

**Comment by v-rusraut** [comment]
Hi @AcceleryntSecurityDev,
Please provide update on above mentioned comments.

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Can you please provide some updates on the above comments.

**Comment by v-prasadboke** [comment]
Closing this PR as we have found a similar PR with identical changes. Also reviewer has provided the same resolution which is mentioned in this PR. 
#9333 
Thanks.

**Pull request closed without merging**
