### PR TITLE
fix: use real url to deployment package and ARM template

### PR DESCRIPTION
**Pull request by ws-mpiglas**
Shortened `aka.ms/` URLs don't work. In consequence connector can't get certificate.
   
   Change(s):
   - Use url  `https://github.com/Azure/Azure-Sentinel/raw/master/Solutions/WithSecureElementsViaFunction/Data%20Connectors/WithSecureElementsViaFunctionConn.zip` to deploy package
   - use url `https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Solutions/WithSecureElementsViaFunction/Data%20Connectors/azuredeploy_Connector_WithSecureElements_AzureFunction.json` in `Deploy to Azure` button

   Reason for Change(s):
   - Urls `https://aka.ms/sentinel-WithSecureElementsViaFunction-azuredeploy` and `https://aka.ms/sentinel-WithSecureElementsViaFunction-functionapp` don't work. In consequence connector can't get certificate.

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by ws-mpiglas** [comment]
@microsoft-github-policy-service agree [company="{WithSecure}"]

**Comment by ws-mpiglas** [comment]
@microsoft-github-policy-service agree company="WithSecure"

**Comment by v-prasadboke** [comment]
Hello @ws-mpiglas, Please package the solution using V3 tool 
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by ws-mpiglas** [comment]
Thanks @v-prasadboke. I've created new solution package. Do you know why  `https://aka.ms/sentinel-WithSecureElementsViaFunction-azuredeploy` and `https://aka.ms/sentinel-WithSecureElementsViaFunction-functionapp` didn't work? Other solutions in this git repository are using short urls and they are working fine.

**Comment by v-prasadboke** [comment]
> Thanks @v-prasadboke. I've created new solution package. Do you know why `https://aka.ms/sentinel-WithSecureElementsViaFunction-azuredeploy` and `https://aka.ms/sentinel-WithSecureElementsViaFunction-functionapp` didn't work? Other solutions in this git repository are using short urls and they are working fine.

Hello @ws-mpiglas, Sorry for the inconvenience but the shortlinks were not updated. 
I've updated them now you can try the shortlinks. Please check and confirm on it once.

If working you can close this PR

**Comment by v-prasadboke** [comment]
Hello @ws-mpiglas, We are waiting for your update

**Comment by ws-mpiglas** [comment]
Hi @v-prasadboke, certification was successful this time. Thanks for your support. I'm closing PR now

**Pull request closed without merging**
