### PR TITLE
Updated function app json file.

### PR DESCRIPTION
**Pull request by dhara-shah-sp**
Change(s):
   - Updated python version to 3.9

   Reason for Change(s):
  - One of our customer got following error and I ran pre-validator on our function app.
image001

   Version updated:
   - No

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-shukore** [comment]
Hi @dhara-shah-sp please deploy the function app file using custom deployment and once function app is created then check the  invocations logs and share the success screenshot.

**Comment by v-shukore** [comment]
Hello @dhara-shah-sp please respond and do the above mentioned steps. Thanks

**Comment by dhara-shah-sp** [comment]
@v-shukore : I am having some trouble following the steps and packaging. Can we please schedule a call anytime this week based on your availability ?

**Comment by dhara-shah-sp** [comment]
@v-shukore : @v-shukore : Can we please schedule a call anytime this week based on your availability ? Our customer is waiting for the new version hence this is a priority for us now.

**Comment by dhara-shah-sp** [comment]
@v-shukore : The invocation is throwing below error and I am unable to update the module. I would appreciate if you could guide me to do so by scheduling a call so as to get the new version out there as soon as possible.

Screenshot 2024-06-13 at 12 45 19 PM

**Comment by v-shukore** [comment]
Hi @dhara-shah-sp 
We updated function app packages, please follow below steps for configuration.

1. Go to Setting section of your function app
image

2. Click on Environment variables
image

3. Under the App setting click on WEBSITE_RUN_FROM_PACKAGE
image

4. Replace the value with below url (Copy existing value and paste it in notepad)
https://github.com/Azure/Azure-Sentinel/raw/12d79190f7839ff8495f038fe0641b850fd8ebed/Solutions/SailPointIdentityNow/Data%20Connectors/SearchEvent.zip

image

5. Apply changes

6. Go to Configuration section -> General settings
image


7. Change python version from 3.8 -> 3.9

8. Click on Save.

9. Restart function app
image

10. Check log in Monitor Section

**Comment by dhara-shah-sp** [comment]
Screenshot 2024-06-14 at 12 24 45 PM


@v-shukore : Please find the attached screenshot with invocation log

**Comment by v-shukore** [comment]
@dhara-shah-sp, Please update/replace our shared zip file which existing one and commit the changes. So, we can merge the correct changes into the master. 
And I can see branch conflict, so please resolve it. 
Please let us know if you have any questions. 
Thanks!

**Comment by dhara-shah-sp** [comment]
@v-shukore : I have uploaded updated zip file. 
Merge conflicts- it states that they are too complex to resolve in web editor? What does that mean and how can I resolve to successfully merge the PR ?

**Comment by dhara-shah-sp** [comment]
@v-shukore : Any update on the recent commit and above comment ?

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, 
Conflicts are because master has a different zip file and your PR has a different zip file. I have updated your zip with Master's missing zip content. Please upload the attached zip file. Thanks.

[SearchEvent.zip](https://github.com/user-attachments/files/16008345/SearchEvent.zip)

**Comment by dhara-shah-sp** [comment]
I have uploaded the new zip file and also added you and @v-shukore  as a contributor to this project. 
Thank you @v-atulyadav

**Comment by v-shukore** [comment]
Hi @dhara-shah-sp, After resolving the conflicts, I'm unable to push changes into this branch, as I don't have the push access. So, kindly could you please reverify the access which you provided to me. 

Thanks!

**Comment by dhara-shah-sp** [comment]
Screenshot 2024-07-03 at 12 46 59 PM


@v-shukore : I have added you as a contributor but the invite is still in pending state. Can you please verify if you have received the email ? If not, I can resend the invite. Thank you.

**Comment by v-shukore** [comment]
Hi @dhara-shah-sp Thanks for grant me the contributor access as I accept invite today. Will check and update you for the same.

Thanks..!!

**Comment by dhara-shah-sp** [comment]
Hi @v-shukore :  We have a customer waiting for the update hence can you please let us know what is the next step in order to close this PR ? 
Thank you!

**Comment by v-shukore** [comment]
Hii @dhara-shah-sp, we tried to push changes in your branch but getting same error, can we connect via a call to fix the conflicts? 
Please share your mail id with us below, so we can connect via call. Thanks! 
My mail ID : v-shukore@microsoft.com

**Comment by dhara-shah-sp** [comment]
Hi @v-shukore : My email id is dhara.shah@sailpoint.com

**Review by v-shukore — APPROVED** [review]

**Pull request merged**
