### PR TITLE
Created a new workbook for Syslog Overview

### PR DESCRIPTION
**Pull request by samikroy**
Required items, please complete
   
   Change(s):
   - New Workbook
   - Workbook Metadata
   - Preview Images

   Reason for Change(s):
   - New Workbook Added

### CODE REVIEW

**Comment by samikroy** [comment]
@vmanojreddy , @NikTripathi , @v-spadarthi  - Request your help for the approval & merge.

**Comment by vmanojreddy** [comment]
@samikroy  In work book query is failing please take a look into once.
image

**Comment by samikroy** [comment]
@vmanojreddy - Thank you for sharing this.
Able to get the same loaded for both the environments 

with Syslog

image

without Syslog

image


And here is the query 
```
Syslog
| distinct HostName
```
Could you please help me running this on the environment above

**Comment by vmanojreddy** [comment]
@samikroy  Hi Can please provide multiselect and unselect for workspace drop down.

**Comment by samikroy** [comment]
> @samikroy Hi can you please provide multiselect and unselect for workspace drop down.

It is already  in place  @vmanojreddy 

image

**Review by vmanojreddy — APPROVED** [review]

**Comment by samikroy** [comment]
@vmanojreddy  - Could you please help to merge this approved PR.

**Comment by samikroy** [comment]
@vmanojreddy - Could you help with the merge or let me know for any updates.

**Comment by samikroy** [comment]
@v-marimanda - Conflict is resolved now.
Could you please have & approve for merger.

**Review by v-marimanda — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
