### PR TITLE
Entity Work Jan 4 - Manny

### PR DESCRIPTION
**Pull request by mmelndezlujn**
Required items, please complete
   
   Change(s):
   - Working on some of the detections Shain asked us to focus on, mainly adding fullName identifiers

   Reason for Change(s):
   - Changes needed listed on Shain's dashboard

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - no

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, Shain has requested some changes please take a look at it

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, Shain has some requested changes. Kindly please have a look at it.
Thanks

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn,
Can you provide write access to your branch. I'll try to resolve validation errors.

**Comment by mmelndezlujn** [comment]
> Hello @mmelndezlujn, Can you provide write access to your branch. I'll try to resolve validation errors.

Hello @v-prasadboke, I am not sure if I can provide write access as I am not the repo owner. 

@shainw could you help me with this, please? :)

**Comment by v-prasadboke** [comment]
> > Hello @mmelndezlujn, Can you provide write access to your branch. I'll try to resolve validation errors.
> 
> Hello @v-prasadboke, I am not sure if I can provide write access as I am not the repo owner.
> 
> @shainw could you help me with this, please? :)

Hi @shainw, Any help on this.

**Comment by mmelndezlujn** [comment]
> Hello @mmelndezlujn, can you update the branch from master

done :)

**Comment by v-prasadboke** [comment]
Hello @mmelndezlujn, 
Sorry but I dont see the branch updated from master

**Comment by shainw** [comment]
> > > Hello @mmelndezlujn, Can you provide write access to your branch. I'll try to resolve validation errors.
> > 
> > 
> > Hello @v-prasadboke, I am not sure if I can provide write access as I am not the repo owner.
> > @shainw could you help me with this, please? :)
> 
> Hi @shainw, Any help on this.

@v-prasadboke and @mmelndezlujn - We are not going to complete this PR.  There are too many file changes in one PR and there are more changes that are needed based on my comments.  I am going to take the changes and break them down into 5-6 file submissions and extend the mappings I called out as needed.  I am closing this and will reference this in the new PRs.

**Pull request closed without merging**
