### PR TITLE
Asim dns infoblox parser update

### PR DESCRIPTION
**Pull request by vakohl**
Required items, please complete
   
   Change(s):
   - Updating the parse function logic to handle different SrcPortNumber format

   Reason for Change(s):
   - An issue was reported by a user. Old parser was not parsing DNS query logs correctly in some cases when the log format was slightly different. Probably due to a different version of Infoblox NIOS. Newer log was having an extra ':' just after SrcPortNumber in 'response' type, this wasn't the case with the old logs. Hence, causing parse function to fail. The updated code can handle both log formats.

   Version Updated:
   - 0.5.1 (VIM) and 0.1.3 (ASIM)

   Testing Completed:
   - Yes, Did test this updated parser with old as well as newer logs format 

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by oshezaf — COMMENTED** [review]
@vakohl : I think the changes are good, but we need to make sure we have the new sample added somewhere. Maybe add them [here](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Syslog/InfobloxNIOS.json)

**Comment by vakohl** [comment]
> @vakohl : I think the changes are good, but we need to make sure we have the new sample added somewhere. Maybe add them [here](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Syslog/InfobloxNIOS.json)

sure @oshezaf . I updated the new sample logs both our private repo as well as github public link you shared above using a different PR https://github.com/Azure/Azure-Sentinel/pull/7954

**Comment by vakohl** [comment]
hi @oshezaf , can you please help approving this PR?

**Comment by vakohl** [comment]
Github Issue link related to this PR: https://github.com/Azure/Azure-Sentinel/issues/7611

**Comment by oshezaf** [comment]
> hi @oshezaf , can you please help approving this PR?

I left a comment. General one. Can you see it?

**Comment by vakohl** [comment]
> > @vakohl : I think the changes are good, but we need to make sure we have the new sample added somewhere. Maybe add them [here](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Syslog/InfobloxNIOS.json)
> 
> sure @oshezaf . I updated the new sample logs both our private repo as well as github public link you shared above using a different PR #7954

@oshezaf are you referring to this comment? This has been taken care.

**Review by oshezaf — APPROVED** [review]

**Pull request merged**
