### PR TITLE
Update Module-1-Setting-up-the-environment.md

### PR DESCRIPTION
**Pull request by javiersoriano**
Fixing a typo in exercise 2 link

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by preetikr** [comment]
@javiersoriano - please resolve the conflicts and @ashishsyal / @v-jayakal once conflicts are resolved, please review/approve and update the solution package + publish changes. Thanks.

**Comment by javiersoriano** [comment]
Conflict resolved

**Comment by v-sabiraj** [comment]
@javiersoriano ,please just correct the typo "Trainig" ,thanks.

**Comment by javiersoriano** [comment]
Where do you see that typo @v-sabiraj ? Can't find it..

**Comment by v-sabiraj** [comment]
In line 52 , **In this exercise you will deploy the Trainig Lab solution into your existing workspace.** ,thanks.

**Comment by javiersoriano** [comment]
Thanks @v-sabiraj . Done!

**Pull request merged**
