### PR TITLE
Windows Forwarded Events TemplateSpec Solution-- DO NOT MERGE AS 1P

### PR DESCRIPTION
**Pull request by v-atulyadav**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Windows Forwarded Events.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B36CEB68E-E6FC-43EF-A360-EAE19C78CE48%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Windows%20Forwarded%20Events.docx&action=default&mobileredirect=true

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by mkchiliveri — APPROVED** [review]
Looks good, Approved.

**Review by mkchiliveri — CHANGES_REQUESTED** [review]
Looks like there are conflicts in this branch, please resolve.

**Review by mkchiliveri — DISMISSED** [review]
Looks good, Approved.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this. Thanks

**Comment by v-mchatla** [comment]
Hi @v-atulyadav 
Could you please resolve the conflicts and request for Review and approval.
Thanks

**Comment by v-marimanda** [comment]
@v-sabiraj Please look into this. Thanks

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
