### PR TITLE
Analytic fixes

### PR DESCRIPTION
**Pull request by pemontto**
Change(s):
   - Bring Proofpoint analytics inline with other email detections
     - `Detections/ProofpointPOD/ProofpointPODBinaryInAttachment.yaml`: add more binaryTypes
     - `Detections/ProofpointPOD/ProofpointPODEmailSenderInTIList.yaml`: remove errant newline that breaks event search
     - `Detections/ProofpointPOD/ProofpointPODMultipleArchivedAttachmentsToSameRecipient.yaml`: add more compressed file types and reference types in output
     - `Detections/ProofpointPOD/ProofpointPODSuspiciousAttachment.yaml`: make extension comparison lowercase and extract dst user from array
   - Fix incorrect `IpCustomEntity` case `IpCustomEntity != IPCustomEntity`
     - `Detections/ProofpointPOD/ProofpointPODWeakCiphers.yaml`: make the entity and field case match 
     - `Solutions/CiscoUmbrella/Analytic Rules`
     - `Detections/CiscoUmbrella`
   - Fix relevantTechniques for
     - `Solutions/ProofPointTap/Analytic Rules/MalwareAttachmentDelivered.yaml`
     - `Solutions/ProofPointTap/Analytic Rules/MalwareLinkClicked.yaml`
  - Update Cisco Meraki parser to extract ThreatName:
    - `Solutions/CiscoMeraki/Parsers/CiscoMeraki.txt`

   Version updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No - attempting to run on M1 MacOS `Could not find 'dotnet' host for the 'X64' architecture.`

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-laanjana** [comment]
@v-spadarthi Noted!!

**Comment by v-laanjana** [comment]
Team, we will check and let you know the update

**Comment by v-laanjana** [comment]
Team, we will check and let you know the update

**Review by shainw — DISMISSED** [review]
Sync with master please, this PR is behind now and has conflicts.

Why are we leaving duplicates in the Detections folder when we have them in the CiscoUmbrella Solutions folder?

For all Detections/AnalyticalRules - we no longer should be using entity mapping inline in the query.  Please just reference the column directly in the fieldMappings ColumnName field.  For example:
Remove this line
`| extend IPCustomEntity = SrcIpAddr, UrlCustomEntity = UrlOriginal`

And change the entity mapping field to:
```
entityMappings:
  - entityType: URL
    fieldMappings:
      - identifier: Url
        columnName: UrlOriginal
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: SrcIpAddr
```

**Comment by v-laanjana** [comment]
TEAM, we are working on one PR  which is having same solution. so I'll  look after that one.

**Review by aprakash13 — APPROVED** [review]
The changes in the PR looks good from a query perspective. Thanks @pemontto

**Comment by v-laanjana** [comment]
Team, we have one PR open for same solution.

**Comment by v-laanjana** [comment]
Team, we have one Open PR lets merge that one fist .

**Comment by v-laanjana** [comment]
Team, we are working.

**Comment by v-spadarthi** [comment]
CiscoMeraki parser looking fine 
image
@aprakash13 / @petebryan: Please review once again the Analytics and provide your approval. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the detections and provide your feedback. Thanks

**Review by aprakash13 — COMMENTED** [review]
The changes looks good to me from a analytic rule perspective. Please merge if other component of the PR looks good.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please provide your approval. Thanks!

**Review by aprakash13 — APPROVED** [review]
Thanks.

**Review by v-spadarthi — APPROVED** [review]
Parser looking good and Ajit approved for Analytics

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
