### PR TITLE
Windows Security Events Template Specs-- DO NOT MERGE AS 1P

### PR DESCRIPTION
**Pull request by v-sabiraj**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Windows Security Events

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - [Test Doc](https://microsoftapc.sharepoint.com/teams/SentinelCATTeam/Shared%20Documents/Forms/AllItems.aspx?ct=1651456572074%2C1651727202806&or=Teams%2DHL%2CTeams%2DHL&ga=1&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA0MTgwMDgwOCJ9&id=%2Fteams%2FSentinelCATTeam%2FShared%20Documents%2FGeneral%2FTemplateSpecs%2FTest%20Results%2FSentinel%20Solution%20Migration%20%2D%20TemplateSpec%20%2D%20Windows%20Security%20Events&viewid=f2d90c2a%2D176b%2D48a0%2D864a%2D33113ced8d59)
See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
@v-sabiraj  - can we remove this file .bak ?

image

**Review by manishkumar1991 — DISMISSED** [review]
Please confirm when changes are done

**Review by manishkumar1991 — APPROVED** [review]
approved

**Comment by v-mchatla** [comment]
Hi @v-sabiraj,

Can you please resolve the conflicts and also reply to Anki's request if it is already addressed.

Thanks

**Comment by v-spadarthi** [comment]
Hi @v-sabiraj,
Can you please resolve the conflicts. Thanks!!

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by v-mchatla** [comment]
Hi @v-sabiraj 
Do we need these changes, if yes please resolve the conflicts.
Thanks

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Do we need these changes, if yes please resolve the conflicts.
Thanks

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Do we need these changes, if yes please resolve the conflicts.
Thanks

**Comment by v-spadarthi** [comment]
Hi @v-sabiraj
Do we need these changes, if yes please resolve the conflicts.
Thanks

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Do we need these changes, if yes please resolve the conflicts.
Thanks

**Comment by v-marimanda** [comment]
@v-sabiraj and @v-atulyadav  Check are failing please take look once. thanks!!!

**Comment by v-atulyadav** [comment]
Hi @v-marimanda , checks are cleared now. Thanks.

**Review by v-dvedak — APPROVED** [review]

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
