### PR TITLE
Added a time chart as Sign-in Trend over Time

### PR DESCRIPTION
**Pull request by samikroy**
Fixes #

## Proposed Changes

Added this time chart to display Sign-in Trend over Time.
This has a TimeBrush enabled for the rest of the widgets to be filtered based on that.

### CODE REVIEW

**Comment by samikroy** [comment]
@v-rucdu - please let me know for any updates needed here.

**Comment by samikroy** [comment]
Request @v-rucdu & @liatlishams for your review.
Let me know for any further queries.
Thank you.

**Comment by NikTripathi** [comment]
Please add workbookMetadata.json file. Thanks

**Comment by samikroy** [comment]
> Please add workbookMetadata.json file. Thanks

@NikTripathi done.

**Review by NikTripathi — APPROVED** [review]
Workbooks looks good.

**Review by NikTripathi — CHANGES_REQUESTED** [review]
TimeRange is changed to TImeBrush and queries are showing that please set TimeBrush. Where can I set it?
image

**Comment by samikroy** [comment]
> . Where can I set it?

@NikTripathi  - Thank you for sharing this. Request you to have a look 
1. If the SigninLogs & AADNonInteractiveUserSignInLogs are available in the test environment.

~~~
SigninLogs
| summarize Time = max(TimeGenerated)
| where isnotempty(Time)
~~~

~~~
AADNonInteractiveUserSignInLogs
| summarize Time = max(TimeGenerated)
| where isnotempty(Time)
~~~
2. If existing Azure AD Sign-in logs workbook render any data.
As can see the current workbook loads where SigninLogs & AADNonInteractiveUserSignInLogs are present

image

**Review by NikTripathi — APPROVED** [review]
Workbook looks good

**Comment by samikroy** [comment]
@liatlishams  - Request you to review this.

**Comment by samikroy** [comment]
Thank you @v-rucdu for approving this.

**Pull request merged**
