### PR TITLE
Show only ConditionalAccessPolicies that failed

### PR DESCRIPTION
**Pull request by Palciny**
User can have defined lot of policies and original query was showing only 3. New query will filter only on ConditionalAccessPoliciesName that failed during the login process.

Required items, please complete

Change(s):
    Added filter that will show only ConditionalAccessPolicies that have failed

Reason for Change(s):
    Results were too broad

Version Updated:
    Yes

Testing Completed:
    Yes

Checked that the validations are passing and have addressed any issues that are present:
    Yes

### CODE REVIEW

**Comment by Palciny** [comment]
@petebryan please verify my change in the analytic query.

**Comment by v-spadarthi** [comment]
@petebryan : Please check analytics and provide your approval.Thanks!

**Comment by v-spadarthi** [comment]
@petebryan : Please check analytics and provide your approval.Thanks!

**Comment by v-spadarthi** [comment]
@petebryan : Please check analytics and provide your approval. Thanks!

**Comment by v-spadarthi** [comment]
@petebryan : Please check analytics and provide your approval. Thanks!

**Comment by Palciny** [comment]
@aprakash13 can you verify my changes? Thanks

**Comment by v-spadarthi** [comment]
@aprakash13 / @petebryan: Please check analytics and provide your approval. Thanks!

**Comment by v-spadarthi** [comment]
@Palciny : Please resolve the conflicts. Thanks!
image

**Pull request closed without merging**
