### PR TITLE
Windowsevent batch12

### PR DESCRIPTION
**Pull request by yaelrbergman**
Required items, please complete

Change(s):
Detections/SecurityEvent/NRT_execute_base64_decodedpayload.yaml
Detections/SecurityEvent/NRT_SecurityEventLogCleared.yaml
Detections/SecurityEvent/PotenialResourceBasedConstrainedDelegationAbuse.yaml
Detections/SecurityEvent/Potentialre-namedsdeleteusage.yaml
Detections/SecurityEvent/PotentialRemoteDesktopTunneling.yaml
Detections/SecurityEvent/UserPrincipalNameAssignedToUserAccount.yaml
Detections/SecurityEvent/WindowsBinariesExecutedfromNon-DefaultDirectory.yaml
Detections/SecurityEvent/NRT_base64_encoded_pefile.yaml

Reason for Change(s):
Added WindowsEvent data in addition to security event

Version Updated:
Yes

Testing Completed:
Yes
Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks.

**Comment by vmanojreddy** [comment]
@oshezaf Please review Detections. thanks!!!

**Comment by v-mchatla** [comment]
Hi @oshezaf 
Can you please provide update on this PR.
Thanks

**Comment by oshezaf** [comment]
Done

**Pull request closed without merging**
