### PR TITLE
PassiveDNS Improvements

### PR DESCRIPTION
**Pull request by jkerai1**
Change(s):
- Fixed Typo in Sentinel Comment
- Converted Timestamp To UTC from raw
- Secure Inputs/Outputs for API Request

   Reason for Change(s):
- Typo (extra . in comment) on IP Branch
- Easier to understand for end user what time is referring to (UTC) from Raw
- For security reasons ClientSecret should not be exposed in API Runs

   Testing Completed:
   - Yes, in a sentinel with no custom parsers.
   
   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by jkerai1** [comment]
@microsoft-github-policy-service agree

**Comment by v-atulyadav** [comment]
Hi @jkerai1, 
We are getting the authorization issue while deploying the playbook.
can you please provide us successful deployment and successful running playbook screenshot?
Thanks

**Comment by v-atulyadav** [comment]
Hi @jkerai1,
Thank you for raising Pull Request with us! We will review it internally and get back to you by shortly.
Thanks

**Comment by dennismercer** [comment]
From an MDTI API standpoint, it looks good.

**Comment by v-atulyadav** [comment]
Hi @dennismercer, can you please provide your approval on this PR?

**Comment by dennismercer** [comment]
> Hi @dennismercer, can you please provide your approval on this PR?

I have amended my comments after testing with the CAT Team.  This playbook has significant errors and I am unable to correct them.  Not Approved.

**Review by ajkallur — COMMENTED** [review]
multiple corrections needed, 

1.) where you have UTC date times their format values (mm/dd/yy) need correction.
image

2.) where you have UTC date times their reference field & format (mm/dd/yyy) values need correction.
image

3.) showing your subscription Id and resource group name
image

4.) we don't force only Managed Service Identity authentication ... Sentinel users are free to choose their authentication method 
image

**Comment by ajkallur** [comment]
@jkerai1 Apologize for the delay in reviewing this Pull request. 

we have looked at the changes, but the ARM template has many issues as highlighted above. Even if they are corrected, we don't see approving this playbook because we don't force use of managed identity.  the UTC DateTime formatting change and covering any secret visibility is a good suggestion that we will implement in the future in a way that all playbooks are updated uniformly in the solution not just this one. don't want this one playbook be odd man out. @dennismercer @manishkumar1991

**Comment by v-atulyadav** [comment]
Hi @jkerai1,
Please accept our apologies for the inconvenience. This PR is not being taken forward as per the comments of @ajkallur. Thanks

**Comment by jkerai1** [comment]
Ah thanks

The MI wasn't actually used it this was mistake of selecting Generating Gallery template when creating the Template from PS script

Yeah makes sense all playbooks to be updated uniformly 

The MDTI-Base also needs to be secured too something i forgot to do here

**Pull request closed without merging**
