### PR TITLE
02 03 2023  as incident host exposure level

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Change(s):
   - New playbook

   Reason for Change(s):
   - New playbook

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @rahul0216, @manishkumar1991,
Can you please review and share your thoughts on it.
Thanks

**Review by rahul0216 — COMMENTED** [review]
Mostly looks good. Few suggestions/asks,
1. Playbook name can be more informative like AS-Get-HostExposureLevel-From-MDE
2. You can add steps to assign "Microsoft Sentinel Contributor" role from GUI/portal as well
3. Please attached one screenshot of successful run of Playbook

**Comment by AcceleryntSecurityDev** [comment]
@rahul0216 First two items have been addressed. Here is a screen shot of a successful run on a test deployment. First two failures were before we figured out the microsoft sentinel contributor role was needed for the managed identity to be able to add comments to incidents. Nothing in the logic app was changed between the failed and successful runs- only the contributor role was added. 
image

**Review by rahul0216 — APPROVED** [review]
Thanks, changes look good.

**Review by v-mchatla — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
