### PR TITLE
Bug fixes for multiple Sysmon parsers

### PR DESCRIPTION
**Pull request by szabolevo**
Change(s):
   - Updated Sysmon-AllVersions_Parser.txt to fix parsing error
   - Updated Sysmon-v12.0.txt to fix syntax error for function call

   Reason for Change(s):
   - **Sysmon-AllVersions_Parser.txt**: parsing errors with project and extend operators
   - Resolves ISSUE #5700
   - Resolves ISSUE #5556 
   - **Updated Sysmon-v12.0.txt**: error with extract_all function calls: the 3rd parameter is expected to be a string; parsing errors caused by empty lines
   - Resolves ISSUE #5701 

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by oshezaf** [comment]
The ASIM fix was moved to PR https://github.com/Azure/Azure-Sentinel/pull/5721

**Comment by szabolevo** [comment]
> The ASIM fix was moved to PR #5721

Cool, thanks for the quick fix. I reverted the ASIM commit in this PR. Is that the right thing to do? In the future I'll separate similar ones to smaller PRs

**Comment by NikTripathi** [comment]
@szabolevo Are we waiting on something for this PR?

**Comment by oshezaf** [comment]
Hi @v-spadarthi. Not related to me. As noted above the parser that I own was fixed in a different PR and removed from this one. More generally, I think this PR is out of date.

**Comment by v-spadarthi** [comment]
@szabolevo : Could you please address the below errors
image
image

**Comment by v-spadarthi** [comment]
@szabolevo : Please address the above comments. Thanks!!

**Comment by v-spadarthi** [comment]
@szabolevo : Please address the above comments. Thanks!!

**Comment by v-spadarthi** [comment]
@szabolevo : Please address the above comments. Thanks!!

**Comment by szabolevo** [comment]
@v-spadarthi  - that was apparently in the code even before my commits. Anyway, I fixed it now, that should fix issue #5556 as well. I also updated the top PR comment so that it no longer references the file fixed in PR #5721

**Comment by v-mchatla** [comment]
Hi @szabolevo 
Thanks for the update.
@v-spadarthi - Can you please verify and confirm on the same.
Thanks

**Comment by NikTripathi** [comment]
@v-spadarthi Can you please provide an update on this?

**Comment by v-spadarthi** [comment]
image
Syntactically looking good

**Review by v-spadarthi — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Comment by NikTripathi** [comment]
Merging as per approval from @v-spadarthi

**Pull request merged**
