### PR TITLE
Semperis dsp updates

### PR DESCRIPTION
**Pull request by aland-semperis**
Required items, please complete
   
   Change(s):
   - Adding 3 new workbooks and replacing one.
   - 3 New analytics rules for suggested alerts on the data.

   Reason for Change(s):
   - Changes to give better views of the data.

   Version Updated:
   - Yes

   Testing Completed:
   - Yes
   
   Checked that the validations are passing and have addressed any issues that are present:
   - Yes
   
image

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @aland-semperis looking into this

**Comment by aland-semperis** [comment]
> Hello @aland-semperis looking into this

ok thanks!

**Comment by aland-semperis** [comment]
> Hello @aland-semperis looking into this

any updates?

**Comment by v-prasadboke** [comment]
all looks good

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
