### PR TITLE
Added Mimecast Solution

### PR DESCRIPTION
**Pull request by dhwanishah-crest**
Change(s):

- Added Mimecast Solution

Version Updated:

- 3.0.0

Testing Completed:

- Yes

Checked that the validations are passing and have addressed any issues that are present:

- Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @dhwanishah-crest, Is this solution made by combining 2 or more solutions

**Comment by dhwanishah-crest** [comment]
@microsoft-github-policy-service agree company="Mimecast"

**Comment by dhwanishah-crest** [comment]
> Hello @dhwanishah-crest, Is this solution made by combining 2 or more solutions

Hi @v-prasadboke ,
We want to create and publish a separate solution for this and the existing solution - Mimecast Audit, Mimecast TTP, Mimecast SEG and Mimecast TI Regional should also work.
For that, we have updated the shorten URLs in our solution for the respective data connectors.

**Comment by dhwanishah-crest** [comment]
@v-prasadboke  Any update on this PR ?

**Comment by dhwanishah-crest** [comment]
Hi @v-prasadboke ,
We have made the necessary changes to resolve Code QL Errors. Could you please look into it?

**Comment by dhwanishah-crest** [comment]
Hi

**Comment by dhwanishah-crest** [comment]
Mimecast TTP URL

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
