### PR TITLE
Workbook Standalone

### PR DESCRIPTION
**Pull request by InspiraEnterprise**
Change(s):
   - Added three Workbook

   Reason for Change(s):
   - New workbook

   Version updated:
   - No

   Testing Completed:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by InspiraEnterprise** [comment]
Hi, it's been 7 days I am waiting for the workflow approval

**Comment by InspiraEnterprise** [comment]
Waiting for the approval

**Comment by v-prasadboke** [comment]
Hello @InspiraEnterprise, Please remove maintemplate of intel471 Solution 

Also remove all the files from tools folder

**Comment by InspiraEnterprise** [comment]
> Hello @InspiraEnterprise, Please remove maintemplate of intel471 Solution
> 
> Also remove all the files from tools folder

Removed all the mentioned things

**Comment by InspiraEnterprise** [comment]
Waiting for your approval

**Pull request closed without merging**
