### PR TITLE
Created a new workbook for MDE Advance Hunting

### PR DESCRIPTION
**Pull request by samikroy**
Created a new workbook for MDE Advance Hunting

   Reason for Change(s):
   - Addition of a new workbook

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@samikroy work book validations is failed due to fromTemplateId. Can you please update workbook name. thanks!!!

**Comment by vmanojreddy** [comment]
@samikroy  Can you please provide work book meta data. thanks!!!

**Comment by samikroy** [comment]
@vmanojreddy - Thank you for the update, have added the necessary changes, please have a look and let me know for further changes.

**Comment by vmanojreddy** [comment]
work book look good we can merge. thanks!!

**Comment by vmanojreddy** [comment]
work book look good we can merge. thanks!!

**Review by vmanojreddy — APPROVED** [review]

**Pull request merged**
