### PR TITLE
Update workbook WorkspaceUsage KQL for Daily Checks - Data Connector tables

### PR DESCRIPTION
**Pull request by mlicd**
Required items, please complete
   
   Change(s):
   - Update KQL query for WorkspaceUsage.json

   Reason for Change(s):
   - KQL query change to remove tables from view in Daily Checks that were from search/restore jobs

   Version Updated:
   - Yes
   - Was 1.6.1

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes, fixed one validation error

### CODE REVIEW

**Comment by mlicd** [comment]
> @mlicd please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{Microsoft}"]

**Comment by mlicd** [comment]
@microsoft-github-policy-service agree company=Microsoft

**Comment by v-spadarthi** [comment]
@mlicd : Please resolve the below comments
In Latency section we could see below
image
In CostAnalysis -Overview section we could see below
image
In CostAnalysis -Defender for cloud section we could see below
image
In Microsoft sentinel -SolutionandTables section we could see below
image
In function or Parsers section we could see below
image

**Comment by mlicd** [comment]
@v-spadarthi, please see my replies: 

Latency section - the computer you selected didn't have any Heartbeat table data, therefore there is nothing further to show.
image

Cost Analysis - Overview section - you need to click on the Actual Data Volume graph to set the Y-axis, this is expected
image

Cost Analysis - Defender for Cloud section - SecurityAlert table doesn't seem to show a Computer column, therefore empty column on chart, this query was not written by me. The tables used in the query are those recommended for Defender for Servers billing https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#workspaces-with-microsoft-defender-for-cloud
image

Microsoft sentinel -SolutionandTables - You need to select a group and table, to see results, it works properly
image

Functions or Parsers - Works properly in my test lab, you seem to have a problem with multiple functions with same name in your environment
image

**Comment by v-spadarthi** [comment]
@mlicd : All the sections are working from your environment due to that approving the PR

**Review by v-spadarthi — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
