### PR TITLE
t-nettabrada/ddos

### PR DESCRIPTION
**Pull request by netta11**
Required items, please complete
   
   Change(s):
- added analytic rules and master playbook to the Azure DDoS Protection Solution
   Reason for Change(s):
- enriching the solution
   Version Updated:
   - 2.0.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Overall, the queries look good. 

Please remove [ ] from the requiredDataConnectors. 
Please also add the **dataTypes** field.  Here is an example query for reference. https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AzureDiagnostics/MaliciousWAFSessions.yaml

It seems the PR also has some validations error. Can we please try fixing them as well. Thanks.

**Comment by v-spadarthi** [comment]
@netta11 : Please fix Validation errors

**Comment by v-spadarthi** [comment]
@netta11 : We had internal discussion with anki and he suggested that masterplaybooks will be go for seperate solution.
Now can you please exclude masterplaybooks from your package. Thanks!!

**Review by aprakash13 — COMMENTED** [review]
Approved from a query perspective. Feel free to merge if other components of the solution looks good.

**Comment by NikTripathi** [comment]
@v-spadarthi Please check the package and go ahead with other required things.
Thanks

**Comment by v-spadarthi** [comment]
I have tested CreateUI definition 
image
Main Template also looking good
image

**Review by v-spadarthi — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
