### PR TITLE
Update mdo power bi

### PR DESCRIPTION
**Pull request by Justfyn**
Required items, please complete
   
   Change(s):
   - Updated Template version

   Reason for Change(s):
   - Internal feedback, adding a new file malware page

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @Justfyn, the report asks for credentials when it is opened. Could you please provide a brief on this. Thanks

image

**Comment by Justfyn** [comment]
@v-atulyadav It's documented in the Readme file: https://github.com/Justfyn/Azure-Sentinel/tree/master/Tools/MDO%20Power%20BI%20Dashboard#how-to-use-the-pbit-file
There is no change on authentication of the template just some new visuals on Files malware
@v-rucdu Can you approve it as you are aware of our initial pull for this https://github.com/Azure/Azure-Sentinel/pull/6447

**Comment by v-atulyadav** [comment]
Hi @Justfyn, please let me know if the below issue has been resolved in this PR regarding this PowerBI report?

[Issue 6644](https://github.com/Azure/Azure-Sentinel/issues/6644)

**Comment by Justfyn** [comment]
@v-atulyadav That issue cannot be reproduced on my side and does not contain sufficient informations to troubleshoot.
Can you approve this one and request more details in the issue?

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by v-atulyadav** [comment]
Hi @Justfyn, we will provide you with feedback as soon as possible. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rushriva, please provide an update on this. Thanks.

**Comment by Justfyn** [comment]
image
@rushriva Following up our public release and blogpost we got some feedback on a section that was missing in the dashboard, that of file malware. Report only contained email malware. Attached the screenshot.
Does it take 2 months to update something that i pushed initially anyway?

**Review by rushriva — APPROVED** [review]
Approved after power bi screenshot was provided.

**Pull request merged**
