### PR TITLE
Update AzureKeyVaultWorkbook.json

### PR DESCRIPTION
**Pull request by Dope-Lemon**
Fix spelling of "kay" vault to "key" vault in workbook

   Required items, please complete
   
   Change(s):
   - Updated spelling on Workbooks/AzureKeyVaultWorkbook.json
   Reason for Change(s):
   - Spelling error
   Testing Completed:
   - Yes
   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
We will review and provide feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon, 
All the screens of the workbook are working fine. Just need small confirmation on below.
Though I have selected Alert Severity to All but still query is looking for Alert Severity. If it is due to data, please share sample data, I will test and provide approval.
image
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
Can you please address suggested comments.
Thanks

**Comment by Dope-Lemon** [comment]
Hi @v-mchatla  I'm away at the moment I will come back to you.

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
Thanks for the update. Please address the query once you are back.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
Hope you are having a great day. Please address the query once you are back.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
Hope you are having a great day. Please address the query once you are back.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
Hope you are doing well; can you please provide sample data to test the workbook.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
It would be great if you could spare sometime and provide the requested details.
Thanks

**Comment by v-mchatla** [comment]
Hi @Dope-Lemon,
It would be great if you could spare sometime and provide the requested details.
Thanks

**Comment by Dope-Lemon** [comment]
Hi @v-mchatla  I'm still away but because I can't get the data to you remotely I will close the PR to get it out of your queue.

**Pull request closed without merging**
