### PR TITLE
1P CCP diagnostic based azure storage solution

### PR DESCRIPTION
**Pull request by mkchiliveri**
Required items, please complete
   
   Change(s):
   - 1P CCP diagnostic based azure storage solution created

   Reason for Change(s):
   - new solution

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by NikTripathi** [comment]
Hi @v-sabiraj Please look into this.

**Comment by v-sabiraj** [comment]
@mkchiliveri, can you please check if you need to add metadata for data connector? thanks

**Comment by v-sabiraj** [comment]
Hey @mkchiliveri, can we merge this if it is good?

**Comment by v-sabiraj** [comment]
@mkchiliveri, any update on this?

**Comment by v-spadarthi** [comment]
@mkchiliveri, Could you please have a look and provide an update. Thanks!

**Review by VenkataPrathibha — APPROVED** [review]

**Pull request merged**
