### PR TITLE
Digital shadows solution v2.0.0

### PR DESCRIPTION
**Pull request by yashwanth-metron**
Change(s):
   - package creation

   Reason for Change(s):
   - New package creation script used
   - package v2.0.0

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by yashwanth-metron** [comment]
> @microsoft-github-policy-service agree [company="Digital Shadows Searchlight"]

**Comment by yashwanth-metron** [comment]
@microsoft-github-policy-service agree [company="Digital Shadows Searchlight"]

**Comment by v-sabiraj** [comment]
Hey @yashwanth-metron, I can see that just version is updated but the package is still created with Version 1 of solution tool.

**Comment by v-sabiraj** [comment]
@yashwanth-metron, please refer to this [document](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md), to create it with version2 od solution tool.

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj, The package was created using Github/Azure-Sentinel/Tools/Create-Azure-Sentinel-Solution/V2/createSolutionV2.ps1 solution tool.

**Comment by v-sabiraj** [comment]
Hey @yashwanth-metron, we will check on this.

**Comment by v-sabiraj** [comment]
Hey @yashwanth-metron, can you please update the latest zip package, thanks.

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj PR has been created and is under review.

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj PR has been created and is under review.

**Comment by v-sabiraj** [comment]
I don't see the changes are made here, is there any other PR raised for this?

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj, The PR is raised in the forked repo and it is still under review.

**Comment by yashwanth-metron** [comment]
@v-sabiraj will update you once it is approved and merged.

**Comment by v-sabiraj** [comment]
> @v-sabiraj will update you once it is approved and merged.

Ok, thanks

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj, merged the changes.

**Comment by yashwanth-metron** [comment]
Hey @v-sabiraj, Please check now.

**Comment by v-sabiraj** [comment]
Let me check and merge this, thanks.

**Review by v-sabiraj — APPROVED** [review]
looks good

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
