### PR TITLE
Playbooks/Update-BulkIncidents: fix deploy to azure buttons, update branding

### PR DESCRIPTION
**Pull request by h0ffayyy**
Fixes #

## Proposed Changes

  - Fix Deploy to Azure buttons in Playbooks/Update-BulkIncidents/readme.md
  - Update branding from Azure Sentinel to Microsoft Sentinel

### CODE REVIEW

**Comment by sreedharande** [comment]
@h0ffayyy - Please resolve conflicts

**Review by NikTripathi — APPROVED** [review]

**Comment by NikTripathi** [comment]
@h0ffayyy Can you please resolve the conflicts?

**Comment by v-sabiraj** [comment]
Hey @h0ffayyy , there are conflicts in this branch, will you please resolve that, thanks.

**Comment by h0ffayyy** [comment]
@v-sabiraj looks like the changes made in this request were already fixed in #3700, closing this

**Pull request closed without merging**
