### PR TITLE
Theom solution

### PR DESCRIPTION
**Pull request by theomsoc**
Required items, please complete
   
   Change(s):
   - Add Theom Solution

   Reason for Change(s):
   - Adding 1 workbook, 20 Analytics rules

   Version Updated:
   - Yes
 
   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by theomsoc** [comment]
@microsoft-github-policy-service agree [company=“Theom"]

**Comment by v-spadarthi** [comment]
@theomsoc : Please fix the validation errors and sign in(license/cla) and resolve the below comments as well.
1)Logo
Logo needs to be in SVG format and under 5 Kb
2)Ensure raw file of logo does not have any of the following:
i)cls and style formats
ii)embedded png formats
iii) title tag is not used
image
image
Yaml file validation please fix
image
Ingested the sample data fine
image
2)Workbook
Deployed workbook working fine
image
Please add the workbook meta data in below path https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json
3) Could you please create a solution package by using V2 tool
Please follow the below URL and do the package creation. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by theomsoc** [comment]
@microsoft-github-policy-service agree [company=“Theom"]

**Comment by theomsoc** [comment]
@microsoft-github-policy-service agree company=“Theom"

**Comment by theomsoc** [comment]
@v-spadarthi addressed comments, please review

**Comment by theomsoc** [comment]
@microsoft-github-policy-service agree company=Theom

**Pull request closed without merging**
