### PR TITLE
SentinelOne: add DataFiled grouping

### PR DESCRIPTION
**Pull request by averbn**
Change(s):
   - DataField fields grouping was added

### CODE REVIEW

**Comment by anki-narravula** [comment]
Hi @averbn  - This got merge conflicts. Can you please make changes after pulling the latest from master.

**Comment by NikTripathi** [comment]
@averbn Can you please resolve conflicts?

**Comment by averbn** [comment]
> 

It seems I have no permissions for doing that

> @averbn Can you please resolve conflicts?

**Comment by NikTripathi** [comment]
> > 
> 
> It seems I have no permissions for doing that
> 
> > @averbn Can you please resolve conflicts?

You are the author I think you must have the right.

**Comment by NikTripathi** [comment]
@averbn  These conflicts are complex that why you won't be able to resolve in web editor you have to resolve locally.

**Comment by averbn** [comment]
> e in web editor you have to resolve locally.



> @averbn These conflicts are complex that why you won't be able to resolve in web editor you have to resolve locally.

New PR without conflicts: https://github.com/Azure/Azure-Sentinel/pull/4500

**Comment by NikTripathi** [comment]
@averbn  please close this PR.

**Comment by vmanojreddy** [comment]
New PR  with: [4500](https://github.com/Azure/Azure-Sentinel/pull/4500) merged. we are closing this pr. thanks!!!

**Pull request closed without merging**
