### PR TITLE
Enhanced Logstash Data Connector with Managed Identity Support

### PR DESCRIPTION
**Pull request by pkhabazi**
# Summary
In this PR, @TheCloudScout  and I introduce a significant update to the Logstash data connector, integrating Managed Identity support. This enhancement eliminates the need for users to store sensitive credentials, such as application IDs and passwords, in plain text within the configuration files. We believe this step forward not only simplifies the security model but also aligns with best practices for secure application development.

## Background
Managed Identity provides an identity for applications to use when connecting to resources that support Microsoft Entra ID authentication. By leveraging Managed Identity, we allow the Logstash data connector to authenticate to Azure services directly, without the need for explicit credentials in the configuration. This approach significantly reduces the risk of credential leakage and simplifies the management of secrets.

## Implementation Details
**Managed Identity Integration:** We've updated the connector to authenticate via Managed Identity, enabling it to securely access other Azure resources.
**Configuration Changes:** Users can now specify Managed Identity in the Logstash configuration, replacing the previous requirement for plain text credentials.
**Backward Compatibility:** The update is designed to be backward compatible, ensuring users can transition at their convenience without disrupting existing deployments. (no breaking changes)

## Further Reading
For those interested in a deeper dive into the rationale behind this update and step-by-step instructions on implementing the solution, @TheCloudScout and I have authored a detailed blog [post](https://github.com/Azure/Azure-Sentinel/pull/10032). This post outlines the security benefits of using Managed Identity and provides a comprehensive guide to users for adopting this new feature.

## Request for Action
@haim-na, we would appreciate your assistance in publishing the updated version of the Logstash data connector to RubyGems.org. The current version is released under your name as far we can see: https://rubygems.org/profiles/ms-haimn

Thank you for considering this update. We look forward to your feedback and any further steps required to bring this improvement to the community.

# Required items, please complete
   
   Change(s):
   - CHANGELOG.md
   - README.md
   - Logstash-syslog-sentinel_mi.conf
   - Microsoft-sentinel-log-analytics-logstash-output-plugin.rb
   - LoganAlyticsAadTokenProvider.rb
   - LoganAlyticsArcTokenProvider.rb
   - LogAnalyticsClient.rb
   - LoganAlyticsMiTokenProvider.rb
   - logstashloganalyticsConfiguration.rb
   - version.rb

   Reason for Change(s):
   - Adding support for Azure Managed Identity
   - Adding support for Azure ARC Managed identity
   - Updating config and docs

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - yes, see our blog post

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @pkhabazi, Can you share working images of function app.

**Comment by TheCloudScout** [comment]
> Hello @pkhabazi, Can you share working images of function app.

Hi @v-prasadboke, 

Here are two screenshots. 

1. Running on an Azure VM:

logstash_managedidentity_azure

2. Running on a VM outside of Azure using Azure Connected Machine Agent (Arc):

logstash_managedidentity_arc

Please let us know if you have any additional questions.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by TheCloudScout** [comment]
@v-prasadboke @v-prasadboke 

Thank you for approving!

We have one remaining question about updating this "Gem" in the repository at rubygems.com. 

https://rubygems.org/gems/microsoft-logstash-output-azure-loganalytics/versions

It seems that user 'ms-haimn' pushed the last update. (Which was version 1.0)
Judging by the username this seems like a Microsoft account. 

It would be nice if this version 1.2.0 would be available as an automatic downloadable package as well. 

Could you help us out with this as well?

**Comment by v-prasadboke** [comment]
Hello @TheCloudScout, This Data connector would be available in the content hub within 2 to 3 business working days

**Comment by pkhabazi** [comment]
> Hello @TheCloudScout, This Data connector would be available in the content hub within 2 to 3 business working days

Thanks for the confirmation @v-prasadboke

**Comment by TheCloudScout** [comment]
> Hello @TheCloudScout, This Data connector would be available in the content hub within 2 to 3 business working days

Hi @v-prasadboke,

Are you sure about the automatic update? Since this is not a standard Sentinel Data Connector _(although the folder structure might indicate otherwise)_ this will **not** show up in Content Hub, nor does it have anything to do with Content Hub content. We believe that this Gem needs to be pushed to rubygems.org manually.

According to [the rubygems page](https://rubygems.org/gems/microsoft-sentinel-log-analytics-logstash-output-plugin) a user named "[ms-haimn](https://rubygems.org/profiles/ms-haimn)" is owner of this "gem". I hope you know who that is and how we can get in touch with him/her.
Only this owner is able to push an update or add additional owners.

Otherwise we need to push it as a new output plugin with a different name. But this would already be the second name change so let's try to prevent this from happening.

Hope you can help us! Thank you!

**Pull request merged**
