### PR TITLE
Fix local network logic

### PR DESCRIPTION
**Pull request by sshockley**
Replace looking for only 10/8 with the ipv4_is_private function.  This should probably have logic for ipv6 as well, but we don't have it implemented here to test.

   Required items, please complete
   
   Change(s):
   - Fix existing rule for sites with private IP addresses other than 10/8

   Reason for Change(s):
   - Excessive false positives

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No (I didn't want to install the out-of-support .Net Core 3.1 on my machine)

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @sshockley,
Could you please repackage this solution with the help of below links. Thanks
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-atulyadav** [comment]
Hi @sshockley,
We are waiting for an update. Thanks

**Comment by v-atulyadav** [comment]
Hi @sshockley,
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

**Comment by v-atulyadav** [comment]
Sure @sshockley. Thanks

**Comment by v-atulyadav** [comment]
Hi @sshockley,
Let us know once you done with the changes. Thanks

**Comment by sshockley** [comment]
Sorry about the delay, I'm working through the docs now.  I'm a little confused; since I'm editing an existing solution, do I need to generate the input file and solution metadata file or should they already be present?

I'm trying to follow the steps using a freshly checked out repo (no local changes) and getting an error:
```
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Playbooks/PaloAltoCustomConnector/PaloAlto_PAN-OS_Rest_API_CustomConnector/azuredeploy.json
Generating Playbook using Playbooks/PaloAltoCustomConnector/PaloAlto_PAN-OS_Rest_API_CustomConnector/azuredeploy.json
Error occured in catch of createSolutionV3 file Error details are Cannot process argument transformation on parameter 'Attributes'. Cannot convert the "[replace(replace(parameters('PaloAlto Hostname'),'https://',''),'http://','')]" value of type "System.String" to type "System.Collections.Hashtable".
```
I'm using:
- Powershell 7.4.2
- Windows Server 2022
- powershell-yaml 0.4.7
- Node 21.7.3

I'm running .\Tools\Create-Azure-Sentinel-Solution\V3\createSolutionV3.ps1 from C:\Github\Azure-Sentinel
When prompted, I enter the path C:\Github\Azure-Sentinel\Solutions\PaloAlto-PAN-OS\data

<details>
<summary>Full output</summary>

```
PS C:\Github\Azure-Sentinel> .\Tools\Create-Azure-Sentinel-Solution\V3\createSolutionV3.ps1
=======Starting Package Creation using V3 tool=========
Enter solution data file path : C:\Github\Azure-Sentinel\Solutions\PaloAlto-PAN-OS\data
Path C:\Github\Azure-Sentinel\Solutions\PaloAlto-PAN-OS\data, DefaultPackageVersion is 3.0.0
SolutionBasePath is C:/Github/Azure-Sentinel/Solutions/, Solution Name PaloAlto-PAN-OS
CatalogAPI Details found for offerId azure-sentinel-solution-paloaltopanos
Offer Metadata Version details in MainTemplate is found!
Package version updated to 3.0.4
Package version identified is 3.0.4
currentFileDCPath C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Data Connectors/PaloAltoNetworks.json
currentFileDCPath C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Data Connectors/template_PaloAltoNetworksAMA.json
isCCPConnector False
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Data Connectors/PaloAltoNetworks.json
Generating Data Connector using Data Connectors/PaloAltoNetworks.json
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Data Connectors/template_PaloAltoNetworksAMA.json
Generating Data Connector using Data Connectors/template_PaloAltoNetworksAMA.json
Removing empty property description
Removing empty property title
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Hunting Queries/PaloAlto-HighRiskPorts.yaml
Generating Hunting Query using Hunting Queries/PaloAlto-HighRiskPorts.yaml
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Hunting Queries/Palo Alto - potential beaconing detected.yaml
Generating Hunting Query using Hunting Queries/Palo Alto - potential beaconing detected.yaml
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Workbooks/PaloAltoOverview.json
Generating Workbook using Workbooks/PaloAltoOverview.json
Downloading C:/Github/Azure-Sentinel/Workbooks/WorkbooksMetadata.json
Downloading C:/Github/Azure-Sentinel/Workbooks/WorkbooksMetadata.json
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Workbooks/PaloAltoNetworkThreat.json
Generating Workbook using Workbooks/PaloAltoNetworkThreat.json
Downloading C:/Github/Azure-Sentinel/Workbooks/WorkbooksMetadata.json
Downloading C:/Github/Azure-Sentinel/Workbooks/WorkbooksMetadata.json
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Analytic Rules/PaloAlto-UnusualThreatSignatures.yaml
Generating Alert Rule using Analytic Rules/PaloAlto-UnusualThreatSignatures.yaml
Has Sub-Techniques for Analytic rule file name PaloAlto-UnusualThreatSignatures_AnalyticalRules
Has Techniques for Analytic rule file name PaloAlto-UnusualThreatSignatures_AnalyticalRules
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Analytic Rules/FileHashEntity_Covid19_CommonSecurityLog.yaml
Generating Alert Rule using Analytic Rules/FileHashEntity_Covid19_CommonSecurityLog.yaml
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Analytic Rules/PaloAlto-NetworkBeaconing.yaml
Generating Alert Rule using Analytic Rules/PaloAlto-NetworkBeaconing.yaml
Has Techniques for Analytic rule file name PaloAlto-NetworkBeaconing_AnalyticalRules
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Analytic Rules/PaloAlto-PortScanning.yaml
Generating Alert Rule using Analytic Rules/PaloAlto-PortScanning.yaml
Has Techniques for Analytic rule file name PaloAlto-PortScanning_AnalyticalRules
Downloading C:/Github/Azure-Sentinel/Solutions/PaloAlto-PAN-OS/Playbooks/PaloAltoCustomConnector/PaloAlto_PAN-OS_Rest_API_CustomConnector/azuredeploy.json
Generating Playbook using Playbooks/PaloAltoCustomConnector/PaloAlto_PAN-OS_Rest_API_CustomConnector/azuredeploy.json
Error occured in catch of createSolutionV3 file Error details are Cannot process argument transformation on parameter 'Attributes'. Cannot convert the "[replace(replace(parameters('PaloAlto Hostname'),'https://',''),'http://','')]" value of type "System.String" to type "System.Collections.Hashtable".
```
</summary>

**Comment by v-atulyadav** [comment]
Hi @sshockley,
I have repackaged the solution, please accept Contributor License Agreement(CLA). Thanks

**Comment by sshockley** [comment]
@microsoft-github-policy-service agree

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
