### PR TITLE
Correct sample queries, data types and connectivity criteria so SonicWall Firewall reports as connected on all appliance models

### PR DESCRIPTION
**Pull request by LynxCafe**
Change(s):
   - Updated SonicWall Firewall Kusto queries in the solution package to process logs from all SonicWall appliances that send logs to the CommonSecurityLog table.

   Reason for Change(s):
   - Fixes Issue #7765 - Where configuring a SonicWall Firewall appliance to send its logs to a Microsoft OMS Agent on a log forwarding host doesn't report the Data Connector as connected in a Microsoft Sentinel log analytics workspace.
   - Eliminates the need to update the list of DeviceProduct items whenever SonicWall release a new appliance model.

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by LynxCafe** [comment]
@microsoft-github-policy-service agree

**Comment by v-vdixit** [comment]
Hi @LynxCafe we are looking into this, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @LynxCafe we are working on this, thanks!

**Comment by v-vdixit** [comment]
Hi @LynxCafe we are testing the connector queries in this will update you shortly, thanks!

**Review by v-vdixit — APPROVED** [review]

**Pull request merged**
