### PR TITLE
Apache HTTP server analytic content update

### PR DESCRIPTION
**Pull request by spsocprime**
Required items, please complete
   
   Change(s):
   - Updated analytic rules and hunting queries
     > prefiltering conditions added `isnotempty(field)`
     > adjusted rule severity

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Analytic rules and Hunting queries. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Analytic rules and Hunting queries. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Analytic rules and Hunting queries. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Analytic rules and Hunting queries. thanks!!!

**Review by aprakash13 — CHANGES_REQUESTED** [review]
The queries generally look good. 
However, would suggest removing isnotempty check from the queries where we are matching for a value against the same column later. e.g.

| where isnotempty(UrlOriginal)
| where UrlOriginal has_any (cmd_list)

**Review by aprakash13 — APPROVED** [review]
Looks ok from a query perspective. Please feel free to merge if other components look good @vmanojreddy

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
