### PR TITLE
Added solution for Cisco SD-WAN

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Required items, please complete
   
   Change(s):
   - Added initial version of solution for Cisco SD-WAN product

   Reason for Change(s):
   - New integration

   Version Updated:
   - Initial Version

   Testing Completed:
   - Done

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @jayeshprajapaticrest, can you please update the API version in the maintemplate that will fix the failing validation. Thanks

**Comment by jayeshprajapaticrest** [comment]
> Hi @jayeshprajapaticrest, can you please update the API version in the maintemplate that will fix the failing validation. Thanks

@v-rbajaj Done. Please confirm.

**Comment by v-rbajaj** [comment]
> > Hi @jayeshprajapaticrest, can you please update the API version in the maintemplate that will fix the failing validation. Thanks
> 
> @v-rbajaj Done. Please confirm.

Hi @jayeshprajapaticrest, please fix the validation failure in createui.

**Comment by v-rbajaj** [comment]
Hi @rahul0216, can you please have a look at the added workbook?

**Comment by jayeshprajapaticrest** [comment]
> > > Hi @jayeshprajapaticrest, can you please update the API version in the maintemplate that will fix the failing validation. Thanks
> > 
> > 
> > @v-rbajaj Done. Please confirm.
> 
> Hi @jayeshprajapaticrest, please fix the validation failure in createui.

Done.

**Comment by v-rbajaj** [comment]
Hi @jayeshprajapaticrest, thanks for making those changes. 
Create UI seems to be broken, can you please fix it? 
Do update the `Solutions/Cisco SD-WAN/Data/Solution_CiscoSD-WAN.json` and the package with the same. 

image

**Comment by v-rbajaj** [comment]
Hi @jayeshprajapaticrest, I am not able to load the Playbooks, I am getting this error
image

**Comment by jayeshprajapaticrest** [comment]
Don't know after resolving conflicts the PR gets automatically closed.

**Comment by v-rbajaj** [comment]
@jayeshprajapaticrest, ARM TTK validation is again failing, can you please fix it?

**Review by v-rbajaj — APPROVED** [review]
looks good

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
