### PR TITLE
Minor Update for Okta Data Connector

### PR DESCRIPTION
**Pull request by i-jmorgan**
Required items, please complete
   
   Change(s):
   - _run.ps1_: Replaced row key from $apiToken to "1"
   - _host.json_: Updated extension bundle versioning
   - _profile.ps1_: Disabled context autosave & added import statements for Az.Accounts and AzTable
   - _requirements.psd1_: Updated package references for Az & added reference for Az.Accounts

   Reason for Change(s):
   - _run.ps1_: Prevents Okta API key from being placed in table storage for deployments where the API key is managed by a key vault and should only be stored at rest in a single location. Further restricts access to the API key to those who have access to the key vault secret instead of anyone who has access to the storage account.
   - _host.json_: Updates to extension bundle resolve an issue where the function app would not run from package.
   - _profile.ps1_: Prevents credentials from being stored while the function app is operating. Import statements for Az.Accounts and AzTable ensures packages are loaded during cold starts.
   - _requirements.psd1_: Updates to package references resolves issue where function app would not run from package. 

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need help

I deployed this function app with these changes and it has been functioning without issue, please let me know about any further testing or validations that I should conduct.

### CODE REVIEW

**Comment by NikTripathi** [comment]
Hi @i-jmorgan What is this additional file in the PR? Do you have any idea?
image

**Comment by i-jmorgan** [comment]
Hi @NikTripathi, that is a directory I forgot to delete by mistake. Should I resubmit my pull request with the directory removed? Thanks!

**Comment by NikTripathi** [comment]
> Hi @NikTripathi, that is a directory I forgot to delete by mistake. Should I resubmit my pull request with the directory removed? Thanks!

You can update this PR itself.

**Comment by v-laanjana** [comment]
@i-jmorgan please fix validation error

**Comment by v-laanjana** [comment]
@i-jmorgan please fix validation error

**Comment by v-spadarthi** [comment]
@i-jmorgan: Please fix the validation error.

**Comment by i-jmorgan** [comment]
I have removed the erroneous Azure-Sentinel folder and updated the pr. Apologies for the delay, let me know if there are any more issues.

**Comment by v-laanjana** [comment]
@NikTripathi please update this PR

**Comment by v-laanjana** [comment]
@NikTripathi please update this PR.

**Comment by NikTripathi** [comment]
@i-jmorgan Can you please make the required changes?

**Comment by NikTripathi** [comment]
Hi @i-jmorgan  Can you please make the required changes?
Thanks.

**Comment by NikTripathi** [comment]
HI @i-jmorgan Did you any time to look into this?

**Comment by NikTripathi** [comment]
Hi @i-jmorgan Please let us know if you have any update. Thank you.

**Comment by v-laanjana** [comment]
Hi @i-jmorgan Please let us know if you have any update. Thank you.

**Comment by v-laanjana** [comment]
@NikTripathi  please have look once .

**Comment by NikTripathi** [comment]
Thanks for the update. Working on this.

**Comment by NikTripathi** [comment]
Hi @i-jmorgan , Everything looks good. But there is zip package missing. Sir, can you please update the zip package of respective data connector with the updated function app and other required code?
Without updating the zip package these changes won't work.
Thanks.

**Comment by NikTripathi** [comment]
Hi @i-jmorgan, Can you please update the respective data connector zip packages as well?
Thanks

**Comment by NikTripathi** [comment]
Hi @i-jmorgan , Hope you are doing well. Did you get any chance to update the the respective data connector zip packages as well?
Thanks

**Comment by NikTripathi** [comment]
Hi @i-jmorgan , Hope you are doing well. Did you get any chance to update the the respective data connector zip packages as well?
Thanks

**Comment by NikTripathi** [comment]
Hi @i-jmorgan Hope you are doing well. Did you get any chance to update the the respective data connector zip packages as well?
Thanks

**Comment by NikTripathi** [comment]
Hi @i-jmorgan Hope you are doing well. Did you get any chance to update the the respective data connector zip packages as well? Also there are conflicts, Can you please resolve them?
Thanks

**Comment by NikTripathi** [comment]
Hi @i-jmorgan Hope you are doing well. Did you get any chance to update the the respective data connector zip packages as well? Also there are conflicts, Can you please resolve them?
Thanks

**Comment by v-mchatla** [comment]
Hi @i-jmorgan 
We wanted to check on the status of PR #6038. PR is pending from more than 30 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.
Thanks

**Pull request closed without merging**
