### PR TITLE
Update createUiDefinition.json - AlertIQ

### PR DESCRIPTION
**Pull request by hieu1w**
Change(s):
   - Update some names of data connector
   Reason for Change(s):
   - Some data connector names have changed from the old version

### CODE REVIEW

**Comment by NikTripathi** [comment]
@v-spadarthi Please look into this.

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-atulyadav** [comment]
Hi @sreedharande , can you please check and provide feedback on above. Thanks

**Comment by v-mchatla** [comment]
Hi @v-rucdu 
Can you please review and provide your feedback or assign it to someone who can review it.
Thanks

**Review by v-atulyadav — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
