### PR TITLE
🐛 Remove preceding newlines in queries

### PR DESCRIPTION
**Pull request by pemontto**
### Change(s)
I've removed the preceding new lines from all queries in `Detections` and `Solutions/*/Analytic Rules`

### Reason for Changes:
This PR addresses the incredibly frustrating behaviour where during an incident investigation, clicking on the events creates a query that fails:
SCR-20221205-n9d-2
SCR-20221205-naw
This is due to the preceding newline that breaks the query into two.

### Versions updated:
   - Yes

I've painstakingly updated the version numbers, however if this isn't significant enough to warrant a version update I'm more than happy to resubmit with just the newlines removed from queries.

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@pemontto : Please resolve the conflicts. Thanks!
image

**Comment by v-sabiraj** [comment]
@pemontto, Can you please check and resolve there are more conflicts, thanks.

**Comment by v-sabiraj** [comment]
@aprakash13, can you please check on the changes as I can see there are minor changes made for the rules, thanks.

**Comment by v-sabiraj** [comment]
@pemontto, can you please update your from master to fix the failing check, also please resolve the conflicts, thanks.

**Comment by v-sabiraj** [comment]
@pemontto, changes looks good to be merged, can you please resolve the conflicts so that we can merge, thanks.

**Review by v-sabiraj — APPROVED** [review]
Approving this, as there are minor changes for removing extra white spaces, thanks.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
