### PR TITLE
Oracleweblogic analytic content update

### PR DESCRIPTION
**Pull request by spsocprime**
Change(s):
   - Optimised rule queries
      `has/has_any` usage instead of `contains`
      pre-filtering for filter out empty fields
      added relevant custom entities
   - Adjusted rule severity 
 OracleWebLogicServerEvent.json
   - Data types changes

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @aprakash13, will you please review and approve the changes, thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13, will you please review and approve the changes, thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13, please review and approve the changes, thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13, please review the changes, thanks.

**Review by aprakash13 — APPROVED** [review]
Overall, the queries look good. Please feel free to merge @v-sabiraj if other components are ok.

**Pull request merged**
