### PR TITLE
add cisco seg content

### PR DESCRIPTION
**Pull request by spsocprime**
## Proposed Changes
Added analytic content for Cisco Secure Email Gateway data connector

### CODE REVIEW

**Comment by spsocprime** [comment]
Not sure what is the problem with validation here image
cause query runs without errors
image

**Comment by spsocprime** [comment]
Since the last week unexpected errors appeared during checks:
1) npm install 
image
2) Kql validation: files which are not in this PR and not developed by our team and functions which are not used in queries
image

**Comment by v-sabiraj** [comment]
Hey @spsocprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytic rules.

**Comment by NikTripathi** [comment]
@spsocprime Please resolve conflicts.

**Comment by v-sabiraj** [comment]
Hey @spsocprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed. Thankyou.

**Pull request closed without merging**
