### PR TITLE
Remediation Host master playbook update

### PR DESCRIPTION
**Pull request by ospeka**
Change(s):
   - added nested playbook MDEIsolate
   - added nested playbook Cisco Meraki

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @ospeka  - Can you please make following changes

-For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [latest guide for playbooks contribution] (https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)

- Update Readme - Add new playbook information in all the sections (wherever applicable) - https://github.com/Azure/Azure-Sentinel/tree/master/MasterPlaybooks/Remediation-Host#readme

- Cisco Meraki playbook - Terms and Conditions banner issue, replace MICROSOFT.WEB/CONNECTIONS with Microsoft.Web/connections

- Name of the playbook, suggest having DeviceName and Action like CarbonBlack-QuarantineDevice, Crowdstrike_ContainHost

- Hardcoded values present in master playbook- search for  /subscriptions/3102b8f9-10e3-49bf-8712-51c184fddef5/resourceGroups/Socprime/providers/

- readme.md - azuredeploy link must be pointed to master after testing everything 

-Wherever support information provided, pls use Microsoft as support

**Comment by ospeka** [comment]
> * Name of the playbook, suggest having DeviceName and Action like CarbonBlack-QuarantineDevice, Crowdstrike_ContainHost

can you give me one example? is whole playbook should be renamed or just directory names?

**Comment by anki-narravula** [comment]
> 

1. Playbook name (default name) inside azuredeploy.json and folder name as well. For example 

> 1. < DeviceName >-< Action >-< Nested >
> 2.  CiscoMereki-BlockDevice-Nested
> 3. MDE-IsolateMachine-Nested
> 4. CrowdStrike-ContainHost-Nested
etc

2. (if not already) Metadata object need to be inside - please refer [Crowdstrike-Remediation-Host] as an example. Please note that certain elements (like prerequisites) are of type array.

**Comment by ospeka** [comment]
> Hi @ospeka Please look into the provided comments and update. Thanks

PR updated in this commits in accordance to provided comments.
https://github.com/Azure/Azure-Sentinel/pull/5522/commits/0dc89b2eba3dbb32a4aaf652126aaa03bf7658b9
https://github.com/Azure/Azure-Sentinel/pull/5522/commits/1551ba013c25827d6f039d868bc75e882d2a2045

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
