### PR TITLE
Update to workbook 8/15/2022

### PR DESCRIPTION
**Pull request by AlexDeMichieli**
The current update fixes a few small bugs:

Within the `Secret Scanning Alerts` panel:

- Found Secrets view:
 The `distinct` keyword is removed as it could potentially remove valid results from the list

Within the `Dependabot Alerts` panel:

- `Dismissed` and `Alert Found/Fixed ratio` views:
 The time query parameters aren't set within the panel, but are now set to take the global time query parameters

Within the `Advanced Security` panel:

- `Alerts Details` and `Open Alerts by Severity` views:
 The time query parameters aren't set within the panel, but are now set to take the global time query parameters
 
 - `Open alerts by Repository`, `Open alerts by Type` and `Resolved alert count` views:
Removed `| where isnotempty(Severity)` from each Code Scanning Alert section. Some Code Scanning events do not have a severity level, however are still valid alerts and should be counted.

### CODE REVIEW

**Comment by AlexDeMichieli** [comment]
@v-spadarthi tagging you along as well!

**Comment by v-spadarthi** [comment]
@AlexDeMichieli  : Please resolve below comments
I have seen all the sections like below "Please set: Repositories"  fix it
image

**Comment by AlexDeMichieli** [comment]
Hey @v-spadarthi , the issue does not seem related to the workbook, but rather to the ingested data. If you already have a working test environment that you've used to test the previous version, you can simply swap the workbook to a new one. Here's a video:

https://drive.google.com/file/d/1FtksXcuwziSx-N2dUk5Df6F223cBeTvZ/view?usp=sharing

Let me know if you have any questions!

**Comment by AlexDeMichieli** [comment]
Hello @v-spadarthi , is there anything I can do to help accelerate the approval process? Thanks! [😊](https://emojipedia.org/smiling-face-with-smiling-eyes/)

**Comment by v-spadarthi** [comment]
I've ingetsed the data and checked in "loganalyticsdevvetadika" workspace working fine.
image

**Review by v-spadarthi — APPROVED** [review]

**Pull request merged**
