### PR TITLE
Infoblox 3.0.0 etc

### PR DESCRIPTION
**Pull request by sschuur**
Change(s):
   - Couple more necessity changes for [#8343](https://github.com/Azure/Azure-Sentinel/pull/8343). Updated parser links to new .yaml. Couple UI fixes. Added description for workbook.

   Version Updated:
   - Updated parser link in [Infoblox-HighThreatLevelQueryNotBlockedDetected.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Infoblox%20Cloud%20Data%20Connector/Analytic%20Rules/Infoblox-HighThreatLevelQueryNotBlockedDetected.yaml), [Infoblox-ManyHighThreatLevelSingleQueryDetected.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Infoblox%20Cloud%20Data%20Connector/Analytic%20Rules/Infoblox-ManyHighThreatLevelSingleQueryDetected.yaml) and [Infoblox-TI-InfobloxCDCMatchFound-LookalikeDomains.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Infoblox%20Cloud%20Data%20Connector/Analytic%20Rules/Infoblox-TI-InfobloxCDCMatchFound-LookalikeDomains.yaml)

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @sschuur, Thanks for raising the PR. This will be investigated and will update you about the same before 30 August, 2023.

**Review by v-prasadboke — DISMISSED** [review]

**Comment by v-prasadboke** [comment]
Hello @sschuur, Please resolve the arm ttk failure by incrementing the version of analytic rules mentioned in this PR.
Thanks.

**Comment by sschuur** [comment]
Hi @v-prasadboke i incremented the versions in the .yamls to 1.0.1.

**Comment by v-prasadboke** [comment]
Hello @sschuur, Please repackage the solution again so that the modified changes in detection's would reflect in maintemplate

**Comment by sschuur** [comment]
Hi @v-prasadboke whoops sorry incremented the versions in maintemplate. Also updated the data connector instructs and added that to maintemplate too. tiny fix.

Quick question: how do i get the workbook to appear as Related Content when looking at the data connector? 

Thank you!

image

**Comment by v-prasadboke** [comment]
Hello @sschuur, Thank you for committing the requested changes.
Will examine the changes and update you about the same before 1 September, 2023.

And will update you too about the query you mentioned. But I was going through data connectors on Portal, Same case is happening with other connector to. 
We will get back to you about this issue.
Thanks.

**Review by v-prasadboke — DISMISSED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
