### PR TITLE
fix: check all events is one of them from future

### PR DESCRIPTION
**Pull request by ospeka**
Change(s):
   - fixed issue where only first event was checked for is event from future.

### CODE REVIEW

**Comment by NikTripathi** [comment]
Hi @ospeka There is an automated response for python code. Can you please fix that?
Thanks

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by v-atulyadav** [comment]
Hi @ospeka , while deploying function app we have getting error module not found as below. Please include missing module/folder. 

image

**Comment by v-atulyadav** [comment]
Hi @ospeka , please include missing module/folder as mentioned above. Thanks.

**Comment by v-atulyadav** [comment]
Hi @ospeka , please include missing module/folder as mentioned above. Thanks.

**Comment by ospeka** [comment]
@v-atulyadav hi, i have included missing modules. Can you check it now?

**Comment by v-atulyadav** [comment]
Hi @ospeka , we are looking into this.

**Comment by v-atulyadav** [comment]
Hi @ospeka , we are looking into this.

**Comment by v-atulyadav** [comment]
Hi @ospeka, we are checking on this and soon will give you a feedback regarding this. Thanks

**Comment by ospeka** [comment]
Hi, i have updated incorrect module and tested it. Can you check it now?

**Comment by v-atulyadav** [comment]
Hi @ospeka, We will check on this and provide you with feedback as soon as possible. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
