### PR TITLE
Create ConnectedNetworkDeviceDiscovery.yaml

### PR DESCRIPTION
**Pull request by mattnovitsch**
Find all devices connected to a certain network.

Testing Completed: Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @mattnovitsch,
Please check the link below, which will help you create a new hunting query.
https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide
Below is one of the example
https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Discovery/MultipleLdaps.yaml

**Comment by mattnovitsch** [comment]
@v-atulyadav I believe I meet the requirements per the guide.

**Comment by mattnovitsch** [comment]
@v-atulyadav - This is my first submission, so I apologize for the questions. Do we have a timeline when these normally get approved? Like a week or month?

**Comment by v-atulyadav** [comment]
Hi @mattnovitsch,
Validations for this query are failing. We are looking into this issue. Once it gets resolved, we will proceed with the merge. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by mattnovitsch** [comment]
Awesome this was merged, do we know how long it will take before it appears in the Microsoft Defender XDR page?

**Pull request merged**
