### PR TITLE
Dev/normalization/win event sync

### PR DESCRIPTION
**Pull request by YuvalNaor**
Fixes #

## Proposed Changes

  -adding network for windowEvent deployment
  -
  -

### CODE REVIEW

**Comment by YuvalNaor** [comment]
@oshezaf

**Review by oshezaf — DISMISSED** [review]

**Review by v-rucdu — CHANGES_REQUESTED** [review]
Please revert Illusive png images file deletion changes... Thanks!!!

**Comment by oshezaf** [comment]
@v-rucdu : those are intentional. The files block cloning the repo. Did you see @YaronFruchtmann e-mail on the topic?

**Comment by v-rucdu** [comment]
> @v-rucdu : those are intentional. The files block cloning the repo. Did you see @YaronFruchtmann e-mail on the topic?

@oshezaf : Yes, Yaron has fixed that issue and merged it in master... If we merge these changes as is these files will also be deleted... Thanks!!!

**Comment by YuvalNaor** [comment]
@oshezaf now the PR is clean

**Review by v-rucdu — APPROVED** [review]

**Review by oshezaf — APPROVED** [review]

**Pull request merged**
