### PR TITLE
Add VolumeShadowCopiesDeleted hunt query

### PR DESCRIPTION
**Pull request by AaronHoffmannRL**
Required items, please complete
   
   Change(s):
   - Adds a new hunt query to identify events where volume shadow copies were deleted

   Reason for Change(s):
   - Adding new hunt query

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 :Please review the Hunting query. Thanks !

**Comment by v-spadarthi** [comment]
@aprakash13 :Please review the Hunting query. Thanks !

**Review by aprakash13 — COMMENTED** [review]
Thanks @AaronHoffmannRL for the query submission. Wondering if adding WMIC.exe part to the current existing detection for shadow copy delete would make more sense: https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Execution/Possible%20Ransomware%20Related%20Destruction%20Activity.yaml

**Comment by AaronHoffmannRL** [comment]
Ah perfect, I didn't see that query when I did a quick search - I'll close this PR and submit an update for that one thanks!

**Pull request closed without merging**
