### PR TITLE
Update product name

### PR DESCRIPTION
**Pull request by dicolanl**
Product name is changing and needed to update product name in solution content before publishing.

   Required items, please complete
   
   Change(s):
   - Updated content due to product name change

   Reason for Change(s):
   - Product Name is changing.

   Version Updated:
   - 1.0.0 -> 1.0.1

   Testing Completed:
   - Once PR is approved, I can rule the solution creation tool.

   Checked that the validations are passing and have addressed any issues that are present:
   - Once PR runs I will check validations

### CODE REVIEW

**Comment by v-laanjana** [comment]
image

@dicolanl could you please remove s from "Analytics" it should be "Analytic Rules"

**Comment by v-laanjana** [comment]
I have fix same changes to fix validation .

**Comment by v-laanjana** [comment]
@dicolanl , For some test we need sample data could you please add sample data as well ?

**Comment by dicolanl** [comment]
@v-laanjana  yes, do you want me to put it in ./Sample Data or create a folder in ./Solutions/Zero Networks???

**Comment by v-laanjana** [comment]
@dicolanl please put in "Sample Data" folder.

**Comment by dicolanl** [comment]
@v-laanjana  added sample data to Sample Data\Custom\Zero Networks folder.

**Comment by v-laanjana** [comment]
@dicolanl  can you please fix validation error with sample data.

 Sample Data Validation Failed. File path: Sample Data/Custom/Zero Networks/ZeroNetworksSegmentAudit_raw.json. Error message: Sample data file data must be in the form of array.

**Comment by dicolanl** [comment]
@v-laanjana fixed and passes validation now.

**Comment by v-laanjana** [comment]
@dicolanl  Thanks for updates

**Review by v-laanjana — APPROVED** [review]
seems ok now

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
