### PR TITLE
Create CiscoASA.kql

### PR DESCRIPTION
**Pull request by richlilly2004**
New Cisco ASA Normalized Parser

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by richlilly2004** [comment]
> New Cisco ASA Normalized Parser
> 
> Fixes #
> 
> ## Proposed Changes

Add Cisco Parser for normalied network

**Comment by richlilly2004** [comment]
bump @ashwin-patil

**Comment by shainw** [comment]
@YaronFruchtmann - Since you own the normalization, wondering if you can have a look at this PR.

**Review by YaronFruchtmann — COMMENTED** [review]
Thanks @richlilly2004 . 
Are these the only fields that we can map? are these the only ones you see value?

Also, could you add this parser to the [meta parser](https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/Normalized%20Schema%20-%20Networking%20(v1.0.0)/MetaParser/NetworkMetaParser.kql)?
See inline comments too.

**Comment by richlilly2004** [comment]
> Thanks @richlilly2004 .
> Are these the only fields that we can map? are these the only ones you see value?
> 
> Also, could you add this parser to the [meta parser](https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/Normalized%20Schema%20-%20Networking%20(v1.0.0)/MetaParser/NetworkMetaParser.kql)?
> See inline comments too.
Example output with field names, I matched the best I could based on some of the other parsers.
image

I will also add to the metaparser.

**Review by YaronFruchtmann — APPROVED** [review]

**Pull request merged**
