### PR TITLE
Edit email address to support

### PR DESCRIPTION
**Pull request by ridgesecurity**
Required items, please complete
   
   Change(s):
   - Edit email address to support@ridgesecurity.ai

   Reason for Change(s):
   - Use alias email address instead of personal

   Version Updated:
   - No change

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No change on function

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @ridgesecurity,
Please repackage this solution with the help of below mentioned link.
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-atulyadav** [comment]
Hi @ridgesecurity,
Please check comment above and act accordingly. Thanks

**Comment by ridgesecurity** [comment]
Thanks, I will repackage it tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-atulyadav** [comment]
Thanks @ridgesecurity.

**Comment by v-atulyadav** [comment]
Hi @ridgesecurity,
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

**Comment by ridgesecurity** [comment]
I already rebuild and uploaded and published solutions. Please let know what else I need to perform.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
