### PR TITLE
Microsoft Sentinel Solution content packaging

### PR DESCRIPTION
**Pull request by cyberiskvision**
Joshua Cyberiskvision Solution - content packaging.

### CODE REVIEW

**Review by NikTripathi — CHANGES_REQUESTED** [review]
image
ARM TTK is failing for this package. I think SolutionMetadata file is not used correctly. Please generate the package again by putting SolutionMetadata.json in basepath location. If you check metadata information is missing from mainTemplate.
Thanks.

**Review by NikTripathi — CHANGES_REQUESTED** [review]
image
There are blank spaces in createUiDefinition. Please remove them.

**Comment by v-sumdh** [comment]
Already discussed with author and would update the package. Thanks

**Comment by cyberiskvision** [comment]
Is there any news regarding the approval of the PR? 
All validation checks are successfully passed and the required changes have been made. 
Is there any other problem blocking the approval process? In this case, please let us know how to solve.

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
