### PR TITLE
Adding MDE solution with updated parsers and two hunting Queries

### PR DESCRIPTION
**Pull request by manishkumar1991**
Required items, please complete
   
   Change(s):
   - Hunting queries addition
     MDE_Process-IOCs.yaml
     MDE_Usage.yaml
   - Functions/Parsers addition
      AssignedIPAddress
      Devicefromip

   Reason for Change(s):
   - It's a fresh addition of MDE solution into github  

   Version Updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by manishkumar1991** [comment]
I am filling out the necessary details by EOD

**Comment by vmanojreddy** [comment]
In checklist DocumentsLinkValidation is failing please remove  locale from url's. thanks!!!

**Review by anki-narravula — APPROVED** [review]
Looks good. Approved

**Review by ashishsyal — APPROVED** [review]
Approved

**Pull request merged**
