### PR TITLE
add: WithSecure Elements via Function Solution

### PR DESCRIPTION
**Pull request by antkma-withsecure**
Change(s):
   New Sentinel solution - WithSecure Data Connector using Azure Functions

   Reason for Change(s):
   New Sentinel solution

   Testing Completed:
   Yes

   Checked that the validations are passing and have addressed any issues that are present:
   Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @antkma-withsecure, Solution is missing with files which are required to package the solution. 
Please add input file which should be located in **data** folder. Add solution metadata file which should contain basic details of solution. 
You can refer this solution for more clarification [Solutions/Azure Activity](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20Activity)

**Comment by v-prasadboke** [comment]
Hello @antkma-withsecure, can you provide me testing account to test the connector. 
you can share it over mail.
my mail id v-prasadboke@microsoft.com

**Comment by antkma-withsecure** [comment]
I've sent you an email, Elements API client id that works with provided data is: fusion_04f9dcc70f754ac98ee47d9a

**Comment by v-prasadboke** [comment]
Received @antkma-withsecure, Continue testing the Solution.

**Comment by antkma-withsecure** [comment]
Screenshots:

sentinel1
sentinel2
sentinel3

Regarding CodeQL errors:
- Clear-text logging of sensitive information is a false-positive, in line 45 withsecure_client.py Authorization header value in dictionary to be logged is set to value "REDACTED", so no sensitive information are logged.
- Explicit returns mixed with implicit (fall through) returns - also seems like a mistake, I can't see how we can hit implicit return in function "_get_detailed_message", every case has explicit return.
- Unnecessary lambda - I'll change it

**Comment by v-prasadboke** [comment]
Hello @antkma-withsecure, Everything's good. 
Resolve Code QL error and we are good to go

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
