### PR TITLE
Cisco Stealthwatch Repackaging

### PR DESCRIPTION
**Pull request by v-prasadboke**
Change(s):
   - Repacking of solution

   Reason for Change(s):
   - https://github.com/Azure/Azure-Sentinel/pull/7547

   Version Updated:
   - 2.0.2

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @v-rusraut, please provide your feedback on this. Thanks

**Comment by v-rusraut** [comment]
hi @v-atulyadav 
For testing parser through ADF pipeline we need contributor access and we have already raised access request.

**Comment by v-atulyadav** [comment]
Hi @v-rusraut, any update on above?

**Comment by v-rusraut** [comment]
Looking into this

**Comment by v-rusraut** [comment]
hi @v-prasadboke @v-atulyadav 
For testing parser , we need to dump sample data in syslog table using ADF pipeline.
Currently that pipeline failing, so need some more time to test parser.

**Comment by v-rusraut** [comment]
Hi @v-atulyadav @v-prasadboke 

There is issue in ADF pipeline , so due to that parser testing pending.

**Comment by v-atulyadav** [comment]
Hi @v-rusraut, please provide your updates.Thanks

**Comment by v-rusraut** [comment]
Hi @v-atulyadav 
Still ADF issue not resolved, due to that parser testing pending.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
