### PR TITLE
added solution package

### PR DESCRIPTION
**Pull request by nisha-das-metron**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by nisha-das-metron** [comment]
@v-atulyadav @v-vdixit we have created the solution package but it failed run-arm-ttk test. we encountered the below issue:-

1. As you can see the error message, most of the errors are because of empty value.
added solution package · Azure_Azure-Sentinel@49cc3a9
We checked the analytical rule few empty fields are there. We have not changed the analytical rule recently and it was working fine when we created the previous versions. Do let me know how to resolve this issue. Do we need to remove these fields?  it was working fine when we created previous versions.
vs-code


2. triage-id value issue.
added solution package · Azure_Azure-Sentinel@49cc3a9 (1)
The triage_id is taking value **EventOriginalUid** in mainTeamplate.json file. We only changed the function app code and workbooks, analytics rule etc is same. Do let me know what changes I need to make to fix this issue.
maintemplate

**Comment by nisha-das-metron** [comment]
Hi, @v-atulyadav @v-vdixit we have been working on this for a very long time. Can we have a quick fix on this?

**Comment by nisha-das-metron** [comment]
> @v-atulyadav @v-vdixit we have created the solution package but it failed run-arm-ttk test. we encountered the below issue:-
> 
> 1. As you can see the error message, most of the errors are because of empty value.
>    added solution package · Azure_Azure-Sentinel@49cc3a9
>    We checked the analytical rule few empty fields are there. We have not changed the analytical rule recently and it was working fine when we created the previous versions. Do let me know how to resolve this issue. Do we need to remove these fields?  it was working fine when we created previous versions.
>    vs-code
> 2. triage-id value issue.
>    added solution package · Azure_Azure-Sentinel@49cc3a9 (1)
>    The triage_id is taking value **EventOriginalUid** in mainTeamplate.json file. We only changed the function app code and workbooks, analytics rule etc is same. Do let me know what changes I need to make to fix this issue.
>    maintemplate

Hi, @v-atulyadav @v-vdixit we have been working on this for a very long time. Can we have a quick fix on this?

**Comment by v-atulyadav** [comment]
Hi @nisha-das-metron, we will provide you with an update by today's end of day. Thanks

**Comment by v-rbajaj** [comment]
Hi @nisha-das-metron, I have fixed the failing validations in this maintemplate, attaching the same here, please push these changes.
[2.0.2.zip](https://github.com/Azure/Azure-Sentinel/files/11610978/2.0.2.zip)

Also please add `Solution_DigitalShadowsSearchlight.json` from here `Solutions\Digital Shadows\Data`

**Comment by nisha-das-metron** [comment]
> Hi @nisha-das-metron, I have fixed the failing validations in this maintemplate, attaching the same here, please push these changes. [2.0.2.zip](https://github.com/Azure/Azure-Sentinel/files/11610978/2.0.2.zip)
> 
> Also please add `Solution_DigitalShadowsSearchlight.json` from here `Solutions\Digital Shadows\Data`

Hi @v-atulyadav @v-rbajaj , I have pushed the updated solution package

**Comment by v-rbajaj** [comment]
Hi @nisha-das-metron, in the `Solution_DigitalShadowsSearchlight.json` "description" line needs to be updated to 
`\n\n**Note:** _There may be [known issues](https://aka.ms/sentinelsolutionsknownissues) pertaining to this Solution, please refer to them before installing._\n\nThe [Digital Shadows](https://www.digitalshadows.com/) Solution provides ingestion of the incidents and alerts from Digital Shadows Searchlight into the Microsoft Sentinel using the REST API. \n\n  **Underlying Microsoft Technologies used:** \r \n This solution takes a dependency on the following technologies, and some of these dependencies either may be in [Preview](https://azure.microsoft.com/support/legal/preview-supplemental-terms/) state or might result in additional ingestion or operational costs:\n\n  a. [Azure Monitor HTTP Data Collector API](https://docs.microsoft.com/azure/azure-monitor/logs/data-collector-api) \n\n b. [Azure Functions](https://azure.microsoft.com/services/functions/#overview)\n\n**Data Connectors:** 1, **Workbooks:** 1, **Analytic Rules:** 2, **Playbooks:** 1\n\n[Learn more about Microsoft Sentinel](https://aka.ms/azuresentinel) | [Learn more about Solutions](https://aka.ms/azuresentinelsolutionsdoc)`

This description needs to be updated in create ui as well and in 2.0.2 zip too

**Comment by nisha-das-metron** [comment]
> Hi @nisha-das-metron, in the `Solution_DigitalShadowsSearchlight.json` "description" line needs to be updated to `\n\n**Note:** _There may be [known issues](https://aka.ms/sentinelsolutionsknownissues) pertaining to this Solution, please refer to them before installing._\n\nThe [Digital Shadows](https://www.digitalshadows.com/) Solution provides ingestion of the incidents and alerts from Digital Shadows Searchlight into the Microsoft Sentinel using the REST API. \n\n **Underlying Microsoft Technologies used:** \r \n This solution takes a dependency on the following technologies, and some of these dependencies either may be in [Preview](https://azure.microsoft.com/support/legal/preview-supplemental-terms/) state or might result in additional ingestion or operational costs:\n\n a. [Azure Monitor HTTP Data Collector API](https://docs.microsoft.com/azure/azure-monitor/logs/data-collector-api) \n\n b. [Azure Functions](https://azure.microsoft.com/services/functions/#overview)\n\n**Data Connectors:** 1, **Workbooks:** 1, **Analytic Rules:** 2, **Playbooks:** 1\n\n[Learn more about Microsoft Sentinel](https://aka.ms/azuresentinel) | [Learn more about Solutions](https://aka.ms/azuresentinelsolutionsdoc)`
> 
> This description needs to be updated in create ui as well and in 2.0.2 zip too

Hi @v-rbajaj I have updated the description

**Review by v-rbajaj — APPROVED** [review]
Looks fine

**Comment by nisha-das-metron** [comment]
> Looks fine

Thanks

**Pull request merged**
