### PR TITLE
Auth0authentication

### PR DESCRIPTION
**Pull request by rsingh134**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - Raising new PR as old 10402 got closed.

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Please update your branch by pulling the latest from the master branch. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Please check for above comment. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
We are waiting for an update on the above request. Thanks

**Comment by rsingh134** [comment]
> Hi @rsingh134, Please update your branch by pulling the latest from the master branch. Thanks

@v-atulyadav branch is synced with Master.

**Comment by rsingh134** [comment]
Re-Open

**Pull request closed without merging**
