### PR TITLE
Modified the Phishing Investigation application to handle benign case as well as no URL extracted from entities.

### PR DESCRIPTION
**Pull request by MuhammadAli-snx**
Change(s):
   - Implemented Benign case handling in Phishing investigation app, repackaged with V3. 

   Version Updated:
   - Function App version 
   - Python Version

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Passed

### CODE REVIEW

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke , Can you please let me know why the automated checks are failing as I have already updated the DotNet SDK and repackaged the app using V3. Also, maintemplate.json is created and placed in Package folder by packager, How come the check is failing to locate the maintemplate.json file?

Please share any solution for the above. 

Thanks.

**Comment by v-prasadboke** [comment]
Hi @MuhammadAli-snx,

Thank you for jumping on the call at short notice.

As discussed, please move forward with the requested changes for the Data Connector. Be sure to add the function app files to the Sentinel repo and include the zip file.

Thanks, 
Prasad

**Comment by MuhammadAli-snx** [comment]
Hi @v-prasadboke, 

I have added the Data Connector directory including the function app code as well as added the required libraries for the function app in the suggested format. Please have a look and let me know if any changes are required.

Thanks.

**Comment by v-prasadboke** [comment]
Hello @MuhammadAli-snx, As discussed in the earlier call requirements. 
I asked for python packages and data connector ui and azure deploy file. 

From which python libraries request was fulfilled but still UI file and azuredeploy file is missing. 

Please add the required file 
You can refer this Data connectors ui and azuredeploy file for more clarification 
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoUmbrella/Data%20Connectors

**Comment by v-prasadboke** [comment]
Hello @mohsin-ali-1757 , Thanks for committing the required changes. Will take a look at these changes and come back to you by 01 December, 2024

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
