### PR TITLE
Remove guid duplicates

### PR DESCRIPTION
**Pull request by benedictschmieder**
Required items, please complete
   
   Change(s):
   - Changed guid
   - Bumped version

   Reason for Change(s):
   - "NetworkPortSweepFromExternalNetwork.yaml" and "PossibleBeaconingActivity.yaml" previosuly had the same guid
   - "ADFSSignInLogsPasswordSpray.yaml" and "CriticalCmdletsUsageDetection.yaml" previously had the same guid

   Version Updated:
   - Yes

   Testing Completed:
   - No (did not change query)

   Checked that the validations are passing and have addressed any issues that are present:
   - No (did not change query or yaml format)

### CODE REVIEW

**Comment by benedictschmieder-gkgab** [comment]
> @benedictschmieder-gkgab please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="glueckkanja-gab AG"]

**Comment by benedictschmieder-gkgab** [comment]
@microsoft-github-policy-service agree company="glueckkanja-gab AG"

**Comment by benedictschmieder-gkgab** [comment]
Hi @v-rbajaj,
No, I cannot. The runner throws the error, that the Id of the file has changed, which is exactly the point of my PR. There are duplicates of IDs present in your repository and I took the newer files (the one which was a copy of the original ID) and changed the ID to a freshly generated one.

**Comment by devikamehra** [comment]
@v-rbajaj What is the expectation from me here?
The changes are only related to metadata and thus doesn't require any validation from my end.

**Comment by benedictschmieder** [comment]
@microsoft-github-policy-service agree company="glueckkanja-gab AG"

**Comment by benedictschmieder** [comment]
@v-rbajaj  Hi,
thanks for the heads up on the merge conflict. I resolved it and kept the guid from the PR #8241.

**Review by v-rbajaj — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
