### PR TITLE
CiscoWSA analytic rules update

### PR DESCRIPTION
**Pull request by spsocprime**
Change(s):
   -  Analytic rules update
       CiscoWSAAccessToUnwantedSite.yaml
       CiscoWSADataExfiltration.yaml
   - Severity level update
       CiscoWSAAccessToUnwantedSite.yaml
       CiscoWSADataExfiltration.yaml
       CiscoWSAMultipleInfectedFiles.yaml
   - Filename changed
       CiscoWSAMultipleInfectedFles.yaml -> CiscoWSAMultipleInfectedFiles.yaml
   - Update parser schema file
       Data types update for DstBytes, SrcBytes, NetworkBytes fields

   Version Updated:
     - Yes
    - Detections/Analytic Rule templates are required to have the version updated

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review the Analytic Rules. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review the Analytic Rules. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review the Analytic Rules. thanks!!!

**Review by aprakash13 — APPROVED** [review]
Looks good from a query perspective. Since there are changes to the custom tables - please get approval from one of the owners for the /.script/ folders as well.
Thanks.

**Pull request merged**
