### PR TITLE
Microsoft exchange security solution correction

### PR DESCRIPTION
**Pull request by nlepagnez**
Required items, please complete
   
   Change(s):
   - Update Workbooks
   - Update of Data Connector for logs
   - Adding file examples

   Reason for Change(s):
   - Integrating new logs to collect
   - enhancement on Workbooks

   Version Updated:

   Testing Completed:

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @nlepagnez, 
Soon we will provide you an update on this. 
Thanks

**Comment by v-mchatla** [comment]
Hi @nlepagnez, 
I have tested the deployment files and workbooks. Repackaged the solution with all these changes, solution testing is only pending. I will try to complete it today and share you the update.
Thanks

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
As discussed, Im facing some issue after creating the maintemplate from tool. Workbook templates are not loading as expected. Yesterday I didnt get a chance to work on it. Will try to fix and provide you the update.
Thanks

**Comment by v-mchatla** [comment]
Hi @nlepagnez, 
I'm facing some issue with the sample data ingestion. Will try to close the testing today. Thanks

**Review by v-mchatla — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
