### PR TITLE
Adding hunt queries, regsvr32, rundll32 and image based payload delivery

### PR DESCRIPTION
**Pull request by JouniMi**
Required items, please complete
   
 Change(s):
   - Added anomalous-payload-delivered-from-iso-file.yaml
   - Added regsvr32-rundll32-with-anomalous-parent-process.yaml
   - Added regsvr32-rundll32-image-loads-from-abnormal-locations.yaml
   - Added regsvr32-rundll32-image-loads-abnormal-extension.yaml

   Reason for Change(s):
   - Added threat hunting queries for Defender for Endpoint.

### CODE REVIEW

**Comment by JouniMi** [comment]
@microsoft-github-policy-service agree

**Comment by v-prasadboke** [comment]
Hello @JouniMi, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 01 February, 2024. 
Also can you share sample data to test the content of the Solution.

**Comment by JouniMi** [comment]
> Hello @JouniMi, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 01 February, 2024. Also can you share sample data to test the content of the Solution.

Thanks @v-prasadboke, I am unsure of if/how the sample data could be delivered? This is hunting query for Defender for Endpoint, would you be interested of having a CSV export from advanced hunting with data to which the queries provides hits for? I created these queries a long time back so it can be a little problematic to come up with this data. I would need to generate this data in my testing environment once more which can cause a lot of work.

**Comment by v-prasadboke** [comment]
> > Hello @JouniMi, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 01 February, 2024. Also can you share sample data to test the content of the Solution.
> 
> Thanks @v-prasadboke, I am unsure of if/how the sample data could be delivered? This is hunting query for Defender for Endpoint, would you be interested of having a CSV export from advanced hunting with data to which the queries provides hits for? I created these queries a long time back so it can be a little problematic to come up with this data. I would need to generate this data in my testing environment once more which can cause a lot of work.

That would work for me

**Comment by JouniMi** [comment]
> > > Hello @JouniMi, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 01 February, 2024. Also can you share sample data to test the content of the Solution.
> > 
> > 
> > Thanks @v-prasadboke, I am unsure of if/how the sample data could be delivered? This is hunting query for Defender for Endpoint, would you be interested of having a CSV export from advanced hunting with data to which the queries provides hits for? I created these queries a long time back so it can be a little problematic to come up with this data. I would need to generate this data in my testing environment once more which can cause a lot of work.
> 
> That would work for me

Understood, is this a hard requirement? I may not be able to deliver this data as it could mean hours of work, which I may not have as this is a hobby. I did not find any requirements for a sample data from the guidance for submitting hunting queries. I understand the need for data connectors but these are MDE advanced hunt queries where the data is always structured similarly.

**Comment by v-prasadboke** [comment]
Hello @JouniMi, 10 rows of data would be enough.
I'll wait for your data. 
Thanks.

**Comment by JouniMi** [comment]
@v-prasadboke  The problem isn't the amount of data but generating the data. I need to create a certain payload which takes certain actions which is not fast to do, which is why I asked if this is requirement for pushing threat hunting queries. I didn't see the requirement for sample data, nor did I see this being requested in other PR:s containing hunting queries for Defender for Endpoint. So, is it a requirement? Do I need to provide sample data for this PR to be merged?

**Comment by v-prasadboke** [comment]
Hello @JouniMi, Dont need sample data. Queries are running in one of the LA. 
But cant see relevant technique `T1218.010` && `T1218.011` For tactic **Defense evasion** 

image

**Comment by JouniMi** [comment]
Hey @v-prasadboke, thanks for confirming that the sample data is not needed. T1218.010 and T1218.011 are sub-techniques of T1218:
https://attack.mitre.org/techniques/T1218/010/
https://attack.mitre.org/techniques/T1218/011/

They are part of Defense Evasion tactic under the **T1218 System Binary Proxy Execution:** 
Screenshot 2024-02-02 at 8 46 05

I can change them to be under T1218 if you do not wish to go to sub-technique level.

**Comment by v-prasadboke** [comment]
Hello @JouniMi, Just confirmed you can keep sub techniques.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
