### PR TITLE
RecordedFutureIdentity solution update

### PR DESCRIPTION
**Pull request by RecordedFutureOskbo**
Required items, please complete
   
   Change(s):
   - Fixed: Hardcoded subscriptionIDs
   - Fixed: Updated to Solution V3.
   - Added: releasenotes 
   - Fixed: renamed playbooks to azuredeploy.json
   - Fixed: Renamed AAD, Azure AD and Azure Active Directory to Entra ID in names, parameters and readme.
   - Added custom connector and usage in RFI-lookup-and-save-user logic app.

   Reason for Change(s):
   - Bugfix
   - Entra ID rename
   - Custom connector pulling more information from Recorded Future.

   Version Updated:
   - Only logic apps

   Testing Completed:
   - Yes
   
   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below.

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Thanks for marking this PR as ready for review state. 
This PR will be investigated and we will update you about the same before 26 Jun, 2024

Thanks, 
Prasad

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Wanted to confirm are these playbook custom connector dependent

**Comment by RecordedFutureOskbo** [comment]
> Hello @RecordedFutureOskbo, Wanted to confirm are these playbook custom connector dependent



> Hello @RecordedFutureOskbo, Wanted to confirm are these playbook custom connector dependent

Hello, only the RFI-lookup-and-save-user use custom connector.

**Comment by v-prasadboke** [comment]
Ok Thanks, 
We are still testing the Solution. Will update you once this is done. 

Thanks.

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
