### PR TITLE
Cohesity security

### PR DESCRIPTION
**Pull request by yinghuang123**
Change(s):
   - update cohesity security solution and build related stuffs.

   Reason for Change(s):
   - Bug fixes for Cohesity Security Solution

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by kishannerella** [comment]
@v-atulyadav @v-mchatla Could you please let us know when the review will start?

**Comment by v-mchatla** [comment]
Hi @kishannerella,
Sorry for the delay, we will review and share the update in sometime. Meanwhile can you please share the success screenshot and also logs from the monitor tab.
Thanks

**Comment by kishannerella** [comment]
Producer Function
Producer-Monitor
Producer-Logs



Consumer Function
Consumer-Monitor
Consumer-Logs

**Comment by v-sabiraj** [comment]
@yinghuang123 / @kishannerella, I think the Solutions/CohesitySecurity/Tools/createSolutionV2.ps1, don't need to be added. As this we already have in here (https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/createSolutionV2.ps1)

**Comment by kishannerella** [comment]
> @yinghuang123 / @kishannerella, I think the Solutions/CohesitySecurity/Tools/createSolutionV2.ps1, don't need to be added. As this we already have in here (https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/createSolutionV2.ps1)

@v-sabiraj We made some minor changes to the current file to be able to read from a different path than what's standard because there are currently some other solutions in the input directory which fail when the tool is run and it's difficult to automate the zip creation process. Please note that this doesn't impact any of the function app logic. It's added into our Tools section.

**Comment by kishannerella** [comment]
@v-sabiraj It has been 5 days since the last comment. Could you please take a look?

**Comment by v-mchatla** [comment]
Hi @kishannerella,
Sorry for the delay. We are occupied with priority work, will review and provide update by 16th March.
Thanks

**Comment by v-mchatla** [comment]
Hi @kishannerella,
Sorry for the delay, I will test it today and provide an update.
Thanks

**Comment by kishannerella** [comment]
@v-mchatla Could you please provide an update?

**Comment by v-mchatla** [comment]
Hi @kishannerella,
sorry for the delay.
@anki-narravula - Can you please review the changes and share your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @kishannerella,
1. I would request you to work on the unreachable code parts suggested by CodeQL 
2. Please remove the create solution tool from the solution folder. The usage of the tool would be, we have to remove the files that are present in the [input](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2/input) folder and place your input to create you zip file. but dont commit any chanes which are part of tools folder just discard it post creation of zip. 
Let me know if you need any further help on this.

**Comment by kishannerella** [comment]
@v-mchatla Implemented your suggestions. Please take a look.

**Comment by v-mchatla** [comment]
Hi @kishannerella,
Apologies for the delay and thanks for making the requested changes. I'm really working on priority item, didn't get a chance to work on this.
One last confirmation required before approving, are you intentionally deleted the main.py file? and also requesting you to fix codeQL alert.
Thanks

**Comment by kishannerella** [comment]
@v-mchatla Added the code to fix the CodeQL warnings. Yes, we intentionally deleted main.py. Thanks.

**Review by v-mchatla — APPROVED** [review]

**Pull request merged**
