### PR TITLE
Jamf Protect for Microsoft Sentinel v3.1.0

### PR DESCRIPTION
**Pull request by txhaflaire**
Change(s):
  - Updated mappings in JamfProtect.yaml
  - Added new Hunting Queries
  - Updated ReleaseNotes.md

Reason for Change(s):
 - Better data mapping, adding new ParentProcess fields to JamfProtect.yaml

Version updated:
  - Yes

Testing Completed:
  - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
I am encountering the following issue while deploying the main template using custom deployment. Could you please repackage this solution once again so we can check it?
image

**Comment by txhaflaire** [comment]
@v-atulyadav I'm not sure if i'm in control of fixing this. The issue seems to be generated by the createSolutionV3.ps1 script. 

Please see attached screenshot, code marked in green is as how it should be (last code on main branch) and code marked in red is being generated by the script. the JamfProtect.yaml parser does not have any changes that could related to this.

image

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
I will check on this and update you soon. Thanks

**Comment by txhaflaire** [comment]
Hi @v-atulyadav Any updates on the variables in the JamfProtect.yaml?

**Comment by txhaflaire** [comment]
@v-atulyadav You mean latest createSolutionV3 script or what latest do you want me to use from the master branch?

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
Below screenshot is for your reference. 
image
After clicking on 'Update Branch', you will need to repackage this solution. Thanks

**Comment by txhaflaire** [comment]
@v-atulyadav Merged master branch and recompiled package, can you recheck?

**Comment by txhaflaire** [comment]
@v-atulyadav Hey! can you recheck? or anything else i can do to help troubleshoot creating the solution?

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
I am still experiencing the same issue. We will look into this and provide you with an update. Thanks
image

**Comment by txhaflaire** [comment]
@v-atulyadav Hey! Any update on this or anything i can help with?

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
Please find below Files.zip file.
1. Extract the zip file, and you will find two folders inside.
a. Package folder: Copy and paste these files into your solution's package folder.
b. Hunting Queries folder: Replace these two files in your solution's hunting queries folder.
[Files.zip](https://github.com/Azure/Azure-Sentinel/files/14123894/Files.zip)

**Note**: Just push these changes to your PR; there is no need to repackage. Thanks

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
Please replace below files in package folder again. Thanks
[Package.zip](https://github.com/Azure/Azure-Sentinel/files/14123979/Package.zip)

**Comment by txhaflaire** [comment]
@v-atulyadav Done, it seems to install but with error about duplicates. did you have this while testing as well? else this might be tenant specific. (removed old solutions)

image

**Comment by v-atulyadav** [comment]
Hi @txhaflaire,
I have successfully deployed the template using custom deployment. The screenshots below are for your reference.
image
image

**Comment by txhaflaire** [comment]
@v-atulyadav Nice work - is this something i can fix myself in the future on next releases or should it not happen anymore?
Then i'm happy to merge and have it released!

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
