### PR TITLE
Update OktaSSO.yaml

### PR DESCRIPTION
**Pull request by AustinTI**
Required items, please complete
   
   Change(s):
   - Updated the Okta Single-Sign-On parser
   - Line 153, replaced oktav2_empty with OktaV2_CL

   Reason for Change(s):
   - Executing the parser via the Log Analytics Workspace with the Oktav2_empty, returns an error.  Replacing Oktav2_empty with Oktav2_CL, executes and returns the log data with no error.

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-visodadasi** [comment]
Hello @AustinTI , Could you please add missing columns to avoid kql validation errors https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/CustomTables/OktaSSO.json

**Comment by AustinTI** [comment]
@microsoft-github-policy-service agree

**Review by AustinTI — COMMENTED** [review]
Changes/ updates acknowledged.

**Comment by v-prasadboke** [comment]
Hello @AustinTI, Can you please try to resolve Branch Conflicts

**Comment by v-prasadboke** [comment]
Hello @AustinTI, Please try to resolve Branch conflicts

**Comment by v-visodadasi** [comment]
Hello @AustinTI, Could you please try to resolve Branch conflicts

**Comment by v-prasadboke** [comment]
Hello @AustinTI, We are waiting for your feedback

**Comment by v-visodadasi** [comment]
Hello @AustinTI, Could you please try to resolve Branch conflicts

**Pull request closed without merging**
