### PR TITLE
Fix invalid yaml issues in "Find Software By Name and Version.yaml"

### PR DESCRIPTION
**Pull request by jannieli**
Required items, please complete
   
   Change(s):
   - changed forward slash to back slash to try to fix issue with yaml parsing in "Find Software By Name and Version.yaml"

   Reason for Change(s):
   - parsing of this file in other features is failing for invalid yaml

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @aprakash13,
Can you please review and share your thoughts on it.
Thanks

**Comment by v-mchatla** [comment]
Hi @aprakash13,
Can you please review and share your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @jannieli,
I will test the rule and let you know in sometime. May I know the feature where it is exactly failing, so that I can test that part as well.
Thanks

**Comment by v-mchatla** [comment]
Hi @jannieli,
Seems there is no change to the query, you have removed extra spaces and you have fixed the parsing problem by changing the \ to / in the description. Is it possible to test the feature from my end to make sure it's working.
Thanks

**Comment by v-mchatla** [comment]
> Hi @jannieli, Seems there is no change to the query, you have removed extra spaces and you have fixed the parsing problem by changing the \ to / in the description. Is it possible to test the feature from my end to make sure it's working. Thanks

Hi @jannieli,
Can you please suggest how we can test from our end.
Thanks

**Comment by v-mchatla** [comment]
Hi @jannieli,
I will check with team on how to proceed in this case and do the needful.
Thanks

**Review by v-mchatla — APPROVED** [review]
Changes look good

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
