### PR TITLE
Darktrace workbook update

### PR DESCRIPTION
**Pull request by JustasZDT**
Change(s):
   - Updated workbook queries

   Reason for Change(s):
   - A change in the data export format from Darktrace /Email (one of the data types pushed to the custom log table from Darktrace) requires changes in the queries used in the workbook

   Version Updated:
   - No: Required only for Detections/Analytic Rule templates

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by JustasZDT** [comment]
Tagging @v-sabiraj as he's had prior experience with our integration content.

**Comment by v-prasadboke** [comment]
Hello @JustasZDT, Workbook was deployed successfully but due to unavailability of sample data in La workbook didnt showed any graphs. 
Can you share some working images of the same.

**Comment by seanmacdonald8** [comment]
Hi @v-prasadboke, here is an example of what the graph will look like with data being sent into log analytics. 

MicrosoftTeams-image

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by seanmacdonald8** [comment]
@v-atulyadav @v-prasadboke 

We see that this was merged into master 5 days ago. However, when we download the latest version of the integration from content hub the updates are not there. Can you please explain why that is? We need to get this update out immediately.

**Pull request merged**
