### PR TITLE
update mainTemplate for Market Place certification

### PR DESCRIPTION
**Pull request by nitsan-tzur**
Required items, please complete
   
   Change(s):
   - Updated mainTemplate.json

   Reason for Change(s):
   - Partner site offer certification process

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @nitsan-tzur, Any reasons behind changing the maintemplate

**Comment by nitsan-tzur** [comment]
> Hello @nitsan-tzur, Any reasons behind changing the maintemplate

Hi @v-prasadboke, I'm trying to submit new offer on Microsoft Partner Site for this new data connector. The manual certification process failed due to wrong link in the mainTemplate.json file

**Comment by v-prasadboke** [comment]
Can you share the rejection comments

**Comment by nitsan-tzur** [comment]
> Can you share the rejection comments

Hi @v-prasadboke here you go:
image

**Comment by v-prasadboke** [comment]
You have submitted Solution's incorrect zip not of Function apps. 

Zip which you have uploaded to Partner center is not identical with Github. Please upload correct zip from the Github's master branch

**Comment by nitsan-tzur** [comment]
> You have submitted Solution's incorrect zip not of Function apps.
> 
> Zip which you have uploaded to Partner center is not identical with Github. Please upload correct zip from the Github's master branch

Hi @v-prasadboke , thats what I did initially, but then certification failed due to incorrect internal reference within mainTemplate.json file. That was the purpose of this PR.

**Comment by v-prasadboke** [comment]
> > You have submitted Solution's incorrect zip not of Function apps.
> > Zip which you have uploaded to Partner center is not identical with Github. Please upload correct zip from the Github's master branch
> 
> Hi @v-prasadboke , thats what I did initially, but then certification failed due to incorrect internal reference within mainTemplate.json file. That was the purpose of this PR.

Sorry @nitsan-tzur, Its not for link mentioned in maintemplate. 
And its clearly mentioned in comments, Solution's package uploaded in partner center is not identical with package located on the master branch. 

Please upload once latest package from GitHub to Partner Center

**Comment by v-prasadboke** [comment]
Hello @nitsan-tzur, Can we connect for this

**Comment by nitsan-tzur** [comment]
> Hello @nitsan-tzur, Can we connect for this Can you share your availability so that I can schedule a call for the same. I work in IST time zone and my mail id is [v-prasadboke@microsoft.com](mailto:v-prasadboke@microsoft.com) You can ping me on teams too

Sure thing @v-prasadboke 
My email: nitsan.tzur@cyberark.com

**Comment by v-prasadboke** [comment]
Hello @nitsan-tzur, 
I'll be scheduling it for 10:30 AM EST 22 April, 2024. 

Which will 8:00 PM IST.

**Comment by nitsan-tzur** [comment]
Got it. Thank you

From: v-prasadboke ***@***.***>
Date: Friday, April 19, 2024 at 6:20 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Nitsan Tzur ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] update mainTemplate for Market Place certification (PR #10252)

CyberArk Security Warning: This is an external email!



Hello @nitsan-tzur<https://urldefense.com/v3/__https:/github.com/nitsan-tzur__;!!Pe07N362zA!yvudceBDvPquCLKmd-mGcZifl88CWwEpU_9KO5r-cIX1ovfNt0cVFlkVGxlfBnlIitWmgrVOYVHhKj2uZ4rQOokojatf$>,
I'll be scheduling it for 10:30 AM EST 22 April, 2024.

Which will 8:00 PM IST.

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
