### PR TITLE
Zero Networks Solution v1

### PR DESCRIPTION
**Pull request by dicolanl**
Required items, please complete
   
   Change(s):
   - Create v1 of solution package

   Reason for Change(s):
   - New solutioon

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@dicolanl : while deploying main template we got an error please fix below error
image

**Comment by dicolanl** [comment]
On it will, update and commit.

**Comment by dicolanl** [comment]
@v-spadarthi Fixed.  was missing a couple managed identity settings:
image

**Comment by v-spadarthi** [comment]
@dicolanl : Please fix the below validation errors 
image
while deploying maintemplate still getting problem can you have a look on this 
image

**Comment by dicolanl** [comment]
@v-spadarthi 
-fixed validations (changed Playbook Name to PlaybookName is all deployment files)
-fixed mainTemplate deployment issue (repackaged to zip too)

**Comment by dicolanl** [comment]
@v-spadarthi 
Do you need anything else from me to review this for merging?  its been hanging for some time.

**Comment by v-spadarthi** [comment]
@rushriva /@devikamehra : Could you please review the Playbooks. Thanks!!

**Review by sreedharande — APPROVED** [review]
Reviewed Playbooks

**Pull request merged**
