### PR TITLE
Added Infoblox Solution

### PR DESCRIPTION
**Pull request by nipun-crestdatasystem**
Change(s):
   - Added Infoblox Solution

   Version Updated:
   - 3.0.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @nipun-crestdatasystem, Thanks for raising this PR. This PR will be investigated and we will update you about the same before 19 July, 2024

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest & @jayeshprajapaticrest  as discussed in the call please add lastupdatedtime in Playbooks metadata. 
Meanwhile I'll upload the sample data to my workspace for the testing. 

Thanks,
Prasad

**Comment by jayeshprajapaticrest** [comment]
> Hello @niralishah-crest & @jayeshprajapaticrest as discussed in the call please add lastupdatedtime in Playbooks metadata. Meanwhile I'll upload the sample data to my workspace for the testing.
> 
> Thanks, Prasad

@v-prasadboke 
The suggested changes are done and committed. Can you please look forward to the PR review?

**Comment by nipun-crestdatasystem** [comment]
@v-prasadboke
Is there any updates on this PR?

**Comment by v-prasadboke** [comment]
Hello @nipun-crestdatasystem, Varun will be testing ASIM parsers

**Comment by nipun-crestdatasystem** [comment]
@v-prasadboke @vakohl
Any update on this PR?

**Comment by v-prasadboke** [comment]
> @v-prasadboke @vakohl Any update on this PR?

Hello Nipun, I have asked Varun to test the PR.

**Comment by nipun-crestdatasystem** [comment]
@vakohl @v-prasadboke 
Is there any updates on this PR?

**Comment by v-prasadboke** [comment]
Also there are some KQL validation failing for playbook. We are trying to resolve this

**Comment by vakohl** [comment]
Sorry for delay. I was on vacation last month.
@v-prasadboke @v-atulyadav 
I'll be reviewing the ASIM files. Can you please assign someone for non-ASIM review?

**Comment by nipun-crestdatasystem** [comment]
Hi @v-prasadboke ,
Is there any update on this PR? As our customers want this to be published as early as possible.
Also, as discussed with @jayeshprajapaticrest, we have raised a separate PR for ASIM Parser - https://github.com/Azure/Azure-Sentinel/pull/11070
Could you please take a look into this? 
@vakohl @v-atulyadav

**Comment by vakohl** [comment]
> Hi @v-prasadboke , Is there any update on this PR? As our customers want this to be published as early as possible. Also, as discussed with @jayeshprajapaticrest, we have raised a separate PR for ASIM Parser - #11070 Could you please take a look into this? @vakohl @v-atulyadav

@nipun-crestdatasystem I see union parser file changes in this PR, since you have created separate PR for ASim Parsers, please remove these changes and move to the other PR.
Also, I'll try doing initial review of your other PR within this week.

@v-prasadboke since this PR has solution changes. Can we assign someone else to review this PR?

**Comment by v-prasadboke** [comment]
> > Hi @v-prasadboke , Is there any update on this PR? As our customers want this to be published as early as possible. Also, as discussed with @jayeshprajapaticrest, we have raised a separate PR for ASIM Parser - #11070 Could you please take a look into this? @vakohl @v-atulyadav
> 
> @nipun-crestdatasystem I see union parser file changes in this PR, since you have created separate PR for ASim Parsers, please remove these changes and move to the other PR. Also, I'll try doing initial review of your other PR within this week.
> 
> @v-prasadboke since this PR has solution changes. Can we assign someone else to review this PR?

Thanks for the update @vakohl.

**Comment by nipun-crestdatasystem** [comment]
Hi @vakohl,
We have removed the changes related to ASIM Parsers union file.

**Comment by nipun-crestdatasystem** [comment]
@vakohl @v-prasadboke
Is there any updates on this PR?

**Comment by vakohl** [comment]
@v-prasadboke please assign this to someone from the team.

**Comment by nipun-crestdatasystem** [comment]
Hi, @vakohl @v-prasadboke
Are there any updates related on this PR?

**Comment by v-prasadboke** [comment]
Hello @nipun-crestdatasystem, Sorry for the delay in response. Already working on it. Will need some time

**Comment by v-prasadboke** [comment]
Hello @nipun-crestdatasystem & @jayeshprajapaticrest as discussed in the call. Please proceed with the required changes to resolve arm ttk failure

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke We did the suggested changes and tested internally and the armttk error was reaolve.
Committed the latest changes here. So can you please re-run the test from your end and proceed with the review and merge as early as possible?
As you can see this has been raised on July 15th.

**Comment by nipun-crestdatasystem** [comment]
Hello, @v-prasadboke 
We’ve attached the screenshot as per your suggestion. Could you kindly review it and proceed with the merge at your earliest convenience?

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
