### PR TITLE
Updates to DataConnectors/AWS-SecurityHubFindings

### PR DESCRIPTION
**Pull request by karpikpl**
Required items, please complete
   
   Change(s):
   - Updated Exception type in python code that was no longer resolving
   - Updated Azure Function extensions to latest - v4
   - Updated Readme file with information on managed identity (since getting tokens by managed identities for themselves is no longer supported in most tenants)
   - Code was reformatted with black formatter

   Reason for Change(s):
   - Customer reported errors when running the code

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Tested function with AWS

   Checked that the validations are passing and have addressed any issues that are present:
   - No validations changed

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @karpikpl, Please try to resolve Code QL failures

**Comment by karpikpl** [comment]
I've updated the code and tested with AWS:
image

had some issues with AWS permissions - hence 30 failed runs :( but eventually it worked

**Comment by karpikpl** [comment]
@v-prasadboke - how can I address those 2 failing checks for `Sentinel Content Validation` ?

**Comment by karpikpl** [comment]
anything I can do to get this merged?

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
