### PR TITLE
Pester testing for detection rules

### PR DESCRIPTION
**Pull request by azurekid**
Required items, please complete
   
   Change(s):
   - Added GitHub Action / Workflow for testing and validating Microsoft Sentinel Detection Rules

   Reason for Change(s):
   - This GitHub Action / Workflow helps organizations keep their detection rules structured and working.
      It uses a big amount of Pester tests to validate coding standards, patterns, entities, tactics, techniques matches, etc.

   Testing Completed:
   
- [x] The Solution is fully tested and working. Ran it against the Azure/Azure-Sentinel detections folder and found many errors in the repo ;-)

- [x] Checked that the validations are passing and have addressed any issues that are present:
   
image

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections.Thanks !

**Comment by v-spadarthi** [comment]
@v-rucdu and @NikTripathi : Please review the Tools validations. Thanks!!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections.Thanks !!

**Comment by shainw** [comment]
@v-spadarthi - These are not Detections, this is validations.  Removing Ajeet.

**Comment by v-marimanda** [comment]
@v-spadarthi - These are not Detections, this is validations. Removing Ajeet.

**Comment by v-spadarthi** [comment]
@v-rucdu : Please review and provide your feedback. Thanks!!

**Comment by v-spadarthi** [comment]
@v-rucdu : Please review and provide your feedback. Thanks!!

**Comment by v-marimanda** [comment]
@v-rucdu : Please review and provide your feedback. Thanks!!

**Comment by v-rucdu** [comment]
@azurekid: I know you already said the build was successful, but that was long time ago. Could you please repeat the process with the most recent GitHub content and keep us updated? We can merge this PR as soon as we get your confirmation... Thanks!!

**Comment by NikTripathi** [comment]
Thanks for the update @azurekid

**Comment by v-rucdu** [comment]
@mkchiliveri: Hey Mahesh as discussed with you yesterday, please have a look in the PR as it might be helpful for the validation enhancement work you are doing... Thanks!!!

**Comment by v-marimanda** [comment]
@mkchiliveri  can you please address the above the comment and provide your update. thanks!!!

**Comment by azurekid** [comment]
> @mkchiliveri can you please address the above the comment and provide your update. thanks!!!

Code is also available on my Github and also available in the GitHub Marketplace
[Github Marketplace](https://github.com/marketplace/actions/validate-detections)

image

**Comment by v-rucdu** [comment]
Approving as its in Tools folder... Thanks!!

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
