### PR TITLE
Hunting queries windows event batch6

### PR DESCRIPTION
**Pull request by yaelrbergman**
Change(s):
Add Windows Event Data to the following Hunting Queries:

[RIDHijacking](https://github.com/Azure/Azure-Sentinel/commit/82a0b162cfcd71a91ae4f75f8fb5ae751c88e6b2)
[FailedUserLogons](https://github.com/Azure/Azure-Sentinel/commit/86473ca44d768a762106b5c399b5d1da708a9c68)

Reason for Change(s):
Part of adding Windows Event data source project

Version Updated:
No
Testing Completed:
Yes
Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@oshezaf Please review Hunting queries and provide feedback. thanks!!!

**Comment by v-spadarthi** [comment]
@oshezaf : Please review Hunting queries and provide feedback. thanks!!!

**Comment by v-mchatla** [comment]
Hi @oshezaf 
Can you please review or provide an update on this PR
Thanks

**Comment by oshezaf** [comment]
Done

**Pull request closed without merging**
