### PR TITLE
Update Endpoint Agent Health Status Report.yaml

### PR DESCRIPTION
**Pull request by pensivepaddle**
Extened query to include Linux and macOS evaluations where applicable.

   Required items, please complete
   
   Change(s):
   - Updated `Update Endpoint Agent Health Status Report.yaml.yaml`

   Reason for Change(s):
   - Extended Endpoint Agent Health Status Report query to include Linux and macOS (all in one)

   Version Updated:
   - No

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @devikamehra, could you please check this and provide your feedback? Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra, could you please check on this PR? Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra, could you please check this and provide your feedback? Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra, could you please check on this PR? Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra, could you please check this and provide your feedback? Thanks

**Comment by v-atulyadav** [comment]
Hi @devikamehra @rushriva @vakohl, could you please check this and provide your feedback? Thanks

**Review by rushriva — COMMENTED** [review]
@pensivepaddle - Contains is a heavy kql operation, has or has_any are recommended options.

**Comment by pensivepaddle** [comment]
> @pensivepaddle - Contains is a heavy kql operation, has or has_any are recommended options.

Certainly, nice catch! Changed to "has" now, patch-3.

**Comment by v-atulyadav** [comment]
Hi @rushriva, please check response from @pensivepaddle on your comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @rushriva, check out @pensivepaddle's response to your comment. Thanks.

**Review by rushriva — APPROVED** [review]

**Pull request merged**
