### PR TITLE
Package update for TheHive solution

### PR DESCRIPTION
**Pull request by v-marimanda**
Required items, please complete
   
   Change(s):
   - Package update for TheHive solution

   Reason for Change(s):
   - Playbooks add so we repackage the solution.

   Version Updated:
   - 2.0.2
   - See guidance below

   Testing Completed:
   - https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B49713C5F-10D3-49C8-A35D-D7DAFFFFE4BC%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20The%20Hive%20with%20playbook%20testing.docx&action=default&mobileredirect=true&share=IQFfPHFJ0xDISaNd19r__-S8ARWCePFZdFBDiowmmw6kt90

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda , please replace text from `Azure Sentinel` to `Microsoft Sentinel` from playbooks ,readme file and maintemplate

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda , please check alignment for below

image

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-marimanda , please change text from `Azure Sentinel` to `Microsoft Sentinel` in playbook readme file also. Thanks.

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-marimanda** [comment]
It is in preview waiting for Kavish Bakshi

**Comment by v-atulyadav** [comment]
It is in preview waiting for Kavish Bakshi

**Comment by v-atulyadav** [comment]
It is in preview awaiting Kavish Bakshi's approval

**Comment by v-atulyadav** [comment]
Currently, it is in preview awaiting approval from Kavish Bakshi

**Comment by v-atulyadav** [comment]
It is in preview waiting for Kavish Bakshi

**Comment by v-spadarthi** [comment]
It is in preview waiting for Kavish Bakshi

**Comment by v-atulyadav** [comment]
preview waiting for Kavish Bakshi

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
