### PR TITLE
AAD Brute Force Hunting query

### PR DESCRIPTION
**Pull request by cmaneiro**
## Proposed Changes

  - Include a new hunting query for AAD Brute Force
  -
  -

### CODE REVIEW

**Comment by cmaneiro** [comment]
Hi @shainw 

Not sure what is failing in this file! 

Could you please let me know what is wrong to fix it?

Regards

**Comment by v-sabiraj** [comment]
Hey @cmaneiro, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by cmaneiro** [comment]
> Hey @cmaneiro, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

hi @v-sabiraj 

All validation pass!!! coul you please close #3634 which is a duplicated!

Regards

**Comment by cmaneiro** [comment]
Hi @aprakash13 and @shainw 

I've update the HQ according to comment in #3634 could you please close #3634 and keep working in this PR? the other one was a test that I'm not the owner.

Regards

**Comment by cmaneiro** [comment]
Hi @shainw, @aprakash13 

Any update on this PR? All the requested changes has been implemented.

Regards

**Review by aprakash13 — APPROVED** [review]
The query looks good. Approved.

**Pull request merged**
