### PR TITLE
IP Enrichment master playbook creation

### PR DESCRIPTION
**Pull request by ospeka**
Created IP Enrichment master playbook 
   Change(s):
   - added nested playbook GeoIP
   - added nested playbook HYAS Insights
   - added nested playbook Recorded Future
   - added nested playbook RiskIQ
   - added nested playbook Virus Total

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @ospeka Please find my comments below

For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [latest guide for playbooks contribution] (https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)


MasterPlaybooks/IP-Enrichment/azuredeploy.json
- Support information must be Microsoft supported, not community supported

/MasterPlaybooks/IP-Enrichment/HYAS_Insights-IP-Enrichment/readme.md
- Prerequisites and some other sections are missing in readme 

RecordedFuture-IP-Enrichment \ readme
- Prerequisites and some other sections are missing in readme 

VirusTotal-IP-Enrichment \ readme
 - "Post deployment" steps are missing

In all the playbooks (whereever used)
- Support information must be Microsoft supported, not community supported

Master Playbook MasterPlaybook_IP_Enrichment
- Terms and Condition banner issue -  replace MICROSOFT.WEB/CONNECTIONS with Microsoft.Web/connections

Maintain the similar naming convention for all the nested playbooks

Wherever support information provided, pls use Microsoft as support

**Comment by v-mchatla** [comment]
Hi @ospeka
Can you please incorporate the changes requested by [anki-narravula](https://github.com/anki-narravula)
Thanks

**Comment by ospeka** [comment]
> Maintain the similar naming convention for all the nested playbooks

Can you show me example of wrong naming?

> /MasterPlaybooks/IP-Enrichment/HYAS_Insights-IP-Enrichment/readme.md

> Prerequisites and some other sections are missing in readme
> RecordedFuture-IP-Enrichment \ readme

> Prerequisites and some other sections are missing in readme
> VirusTotal-IP-Enrichment \ readme

> "Post deployment" steps are missing

This issue will be solved via email.

**Comment by anki-narravula** [comment]
> > Maintain the similar naming convention for all the nested playbooks
> 
> Can you show me example of wrong naming?
> 
> > /MasterPlaybooks/IP-Enrichment/HYAS_Insights-IP-Enrichment/readme.md
> 
> > Prerequisites and some other sections are missing in readme
> > RecordedFuture-IP-Enrichment \ readme
> 
> > Prerequisites and some other sections are missing in readme
> > VirusTotal-IP-Enrichment \ readme
> 
> > "Post deployment" steps are missing
> 
> This issue will be solved via email.

Hi @ospeka -

For example below are current names. We can give same naming structure like I have given below example 

Current

> Enrich-Sentinel-Incident-HYAS-Insight-IP-C2-Attribution
> RecordedFuture-IOC_Enrichment-IP_Domain_URL_Hash
> RiskIQ-Data-Whois-Ip
> Get-VirusTotalIPReport
> 

New can be

> < Device Name >-< Action >-< Nested >
> HYASInsight-IP_C2-Enrichent-Nested
> RecordedFuture-IP_Domain_URL_Hash-Enrichment-Nested
> RiskIQ-Ip-Whois-Enrichment-Nested
> VirusTotal-IP-Report-Enrichment-Nested

**Comment by NikTripathi** [comment]
@ospeka Please look into the feedback provided.
Thanks

**Comment by ospeka** [comment]
> @ospeka Please look into the feedback provided. Thanks

PR updated in this commit in accordance to provided comments.
https://github.com/Azure/Azure-Sentinel/pull/5557/commits/02eb42528ac5186ea213f62c0d944182f05f384b

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
