### PR TITLE
solution created for Security Threat Essentials -- DO NOT MERGE AS THIS IS 1P SOLUTION

### PR DESCRIPTION
**Pull request by v-laanjana**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Security Threat Essentials.
See guidance below
Version Updated:
2.0.0
See guidance below
Testing Completed:
The link for test results is
[Sentinel Solution Migration](https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B2333FA53-3FC3-447D-B2F7-E7DBC61B7E52%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Sentinel%20Solution%20Migration%20-%20TemplateSpec%20-%20Security%20Threat%20Essentials.docx&action=default&mobileredirect=true&share=IQFT-jMjwz99RLL359vGG35SARU72of0ebTFWl7JlQjUmYE) Security Threat Essentials

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-spadarthi** [comment]
@v-sabiraj : Please merge it

**Comment by v-mchatla** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-sabiraj** [comment]
Approving and merging as already approved.

**Review by v-sabiraj — APPROVED** [review]

**Pull request merged**
