### PR TITLE
New Playbook to fetch machine information and run SOAR actions upon incident

### PR DESCRIPTION
**Pull request by kloudynetklassrooms**
## Proposed Changes
Added a new Playbook is for sending Microsoft Teams notification when an alert is generated by Defender for endpoint. Teams notifications should also include data about:
- Machine Vulnerabilities
- Missing KBs
- Security Recommendations
- Alerts
- Software Inventory

Also should be able to perform some actions like:
- App Execution
- Start AV scan

### CODE REVIEW

**Review by sarah-yo — CHANGES_REQUESTED** [review]
Please can you add the "Deploy to Azure" and "Deploy to Azure Gov" so this can be deployed as an ARM template. Thanks!

**Review by kloudynetklassrooms — COMMENTED** [review]
Changes added in the latest commit

**Comment by kloudynetklassrooms** [comment]
@sarah-yo changes commited

**Comment by sarah-yo** [comment]
How does this Playbook relate to Sentinel? It appears to be Defender for Endpoint focused?

**Comment by kloudynetklassrooms** [comment]
> How does this Playbook relate to Sentinel? It appears to be Defender for Endpoint focused? This does not look like it should be in the Sentinel repo.

@sarah-yo The playbook gets triggered on a Sentinel Incident. It looks into the Incident Entities, picks up the endpoint (machine) name, and then restricts app executions as well as runs an AV scan. The playbook also provides full information about the machine which is generating an Incident in Sentinel. Below are some use cases in which Sentinel/Security Analysts can use the playbook
- Security Analysts want to automate a Level 1 response on a machine on which there is a high incident alert triggered
- Security Analysts can also write a schedules query in Sentinel and trigger this playbook for specific host machines which are high-value assets
As an example, there are also other playbooks with some similar kind of functionalities "https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-MDATPInvestigationPackage"
Someone can also expand the playbook further to add comments into the incident and so on...

**Review by sarah-yo — CHANGES_REQUESTED** [review]
Please can you make the variables in the ARM template a bit clearer and have the readme instructions match the ARM template implementation? Thanks!

image

**Comment by kloudynetklassrooms** [comment]
Hi @sarah-yo ,

We've considered your comments and cleaned up the template.json by removing the parameters for the API connections. Now the API connection deployment is the part of the ARM template deployment itself - so this make is easy to deploy the ARM template and makes it look clean. 

We've also updated README.md to reflect the changes we've done in the ARM template.

Hope it addresses all your concerns, if any other changes required, please let us know.

**Comment by sarah-yo** [comment]
Hi @kloudynetklassrooms,

Removing the API connection parameters isn't what we would consider "tidying up" of the ARM template as it's is creating more configuration work for the end user. Please put as many parameters as you can in the ARM template and make it clear in the template what parameter needs to entered into the template.

Thanks!

**Comment by kloudynetklassrooms** [comment]
Hi @sreedharande and @sarah-yo,

There is no configuration the user needs to do. User need to authenticate the connectors after the deployment and select My Documents folder in SharePoint that's all. This makes it very easy for anybody to deploy this playbook.  
Hope this helps.

Best Regards,
Kloudynet.

**Comment by sreedharande** [comment]
@kloudynetklassrooms - Can you please fix the following issues

1. Change template.json to azuredeploy.json (Standard across all playbooks/deployment)
2. Your template deploying "azurekeyvault-playbookname", I don't see any keys/secrets or KeyVault name. This will throw you error when you try to authorize after deployment.

**Comment by kloudynetklassrooms** [comment]
Hi @sreedharande,

The json file has been renamed and added the secret name which needs to be added in the Azure Keyvault in the description.

**Pull request merged**
