### PR TITLE
Fix esetprotect errors

### PR DESCRIPTION
**Pull request by m11tch**
Change(s):
   - fix a typo in instructions section of Connector_Syslog_ESETPROTECT.json
   - fix UIDefinition filter

   Reason for Change(s):
   - Typo
   - UIDefinition would only allow to deploy the solution to lowercase resourcegroups. 

   Version updated:
   - No

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by m11tch** [comment]
@microsoft-github-policy-service agree company="Cyber Defense Group B.V."

**Comment by m11tch** [comment]
upgraded the templates to v2, successfully performed the validations mentioned in: https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2

**Comment by v-rbajaj** [comment]
Hi @m11tch, I have a question, the version of the packaging should be 1.1.1, right? 
Some changes required are 
1. The 2.0.0 zip includes 1.1.0 zip, please remove 1.1.0 zip. 
2. The maintemplate has "Azure Sentinel" at line no 964, please change that to "Microsoft Sentinel"
Thanks

**Comment by m11tch** [comment]
> Hi @m11tch, I have a question, the version of the packaging should be 1.1.1, right? Some changes required are
> 
> 1. The 2.0.0 zip includes 1.1.0 zip, please remove 1.1.0 zip.
> 2. The maintemplate has "Azure Sentinel" at line no 964, please change that to "Microsoft Sentinel"
>    Thanks

Hey @v-rbajaj i'm not sure which version number you mean, the 2.0.0 zip was created by the V2 solution tool (https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2) . 

I didn't change any other versions because the only other change was a typo in the instructions section of the connector

**Comment by v-rbajaj** [comment]
> 1.1.1,

Ok, Please add these two lines in `Solutions\ESETPROTECT\Data\Solution_ESETPROTECT.json`  at the end of the file

 ```
 "TemplateSpec": true,
  "Is1PConnector": false
```

Please repackage it with the same tool and ensure that 2.0.0 zip only includes createUI and Maintemplate

**Comment by m11tch** [comment]
> > 1.1.1,
> 
> Ok, Please add these two lines in `Solutions\ESETPROTECT\Data\Solution_ESETPROTECT.json` at the end of the file
> 
> ```
> "TemplateSpec": true,
> "Is1PConnector": false
> ```
> 
> Please repackage it with the same tool and ensure that 2.0.0 zip only includes createUI and Maintemplate



> > 1.1.1,
> 
> Ok, Please add these two lines in `Solutions\ESETPROTECT\Data\Solution_ESETPROTECT.json` at the end of the file
> 
> ```
> "TemplateSpec": true,
> "Is1PConnector": false
> ```
> 
> Please repackage it with the same tool and ensure that 2.0.0 zip only includes createUI and Maintemplate

Ah my bad, forgot to replace that file with the updated version. done now.

**Comment by v-rbajaj** [comment]
Hi @m11tch, The entity mapped in Threats detected by ESET Analytical rule is the old way of mapping entities please map the entites directly. 

Also, the arm-ttk is failing please fix the errors for the same.

**Comment by m11tch** [comment]
> Hi @m11tch, The entity mapped in Threats detected by ESET Analytical rule is the old way of mapping entities please map the entites directly.
> 
> Also, the arm-ttk is failing please fix the errors for the same.

Hey @v-rbajaj, 

updated the analytic-rules, arm-ttk is not failing on my end. could you confirm?

**Comment by m11tch** [comment]
@v-rbajaj Based on your screenshot you're not using the updated analytic rules from my last commit.

**Review by v-rbajaj — APPROVED** [review]

**Pull request merged**
