### PR TITLE
Varonis saas dev

### PR DESCRIPTION
**Pull request by vkorenkov-varonis**
Required items, please complete
   
   Change(s):
   - updated VaronisSaaS_CL table schema
   - updated connector page, remove manual azure function installation step
   - updated fetching data azure function installation page
   - refactor azure function

   Reason for Change(s):
   - table schema should be same as Varonis SaaS service uses
   - requirements after copywriter moderation

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by vdobrotskyi-varonis** [comment]
@v-atulyadav can you please take a look?

**Comment by v-atulyadav** [comment]
Hi @vkorenkov-varonis,
We will provide you with an update on this by July 10th. Meanwhile, could you please share with us the screenshots of the successful running connector or invocation logs?. Thanks

**Comment by vkorenkov-varonis** [comment]
> Hi @vkorenkov-varonis, We will provide you with an update on this by July 10th. Meanwhile, could you please share with us the screenshots of the successful running connector or invocation logs?. Thanks

image
image
image

**Review by v-atulyadav — COMMENTED** [review]
Hi @vkorenkov-varonis,
Please check and response on below points.
1. Data connect has `Azure Sentinel` text please replace with `Microsoft Sentinel`.
image
2. SolutionMetadata mentioned support information as Microsoft-supported, but this is a partner solution, so please update support information
image
image

**Note: After all these changes, please repackage the solution**.

**Comment by v-atulyadav** [comment]
Hi @vkorenkov-varonis,
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

**Comment by vkorenkov-varonis** [comment]
> Hi @vkorenkov-varonis, To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

Hi @v-atulyadav, I'm waiting for my manager to give me information about contribution section. Sorry for possible inconvenience.

**Comment by vkorenkov-varonis** [comment]
> Hi @vkorenkov-varonis, To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

Done

**Comment by v-atulyadav** [comment]
Hi @vkorenkov-varonis,
Is there no email address for support?
image

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
