### PR TITLE
Added Pure Storage Parser

### PR DESCRIPTION
**Pull request by skeerthivasan**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by skeerthivasan** [comment]
@microsoft-github-policy-service agree company="Pure Storage"

**Comment by v-rusraut** [comment]
Hi @skeerthivasan,
Thanks for raising this PR. We will provide you an update on 06 Feb 2024 .

**Comment by v-rusraut** [comment]
Hi @skeerthivasan,
For adding new solution, we need to package the solution, please refer below points.

- Please package the solution using V3 tool, please go through this readme file on how to use the V3 tool
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

- Add ReleaseNotes file for solution,please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by v-rusraut** [comment]
Hi @skeerthivasan,
Ok, after merging this PR, please raise new PR for solution packaging.
Thanks

**Review by v-rusraut — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
