### PR TITLE
Fixed the vulnerability related issue by passing API secret key in data instead of params.

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Change(s):
   - Updated data connector code and playbook code by passing the API secret key in data instead of query param.

   Reason for Change(s):
   - Because of passed the API secret keys in query params it generate the vulnerability related issue.

   Version Updated:
   - As per the latest guideline update solution version to 3.0.0
   
   Testing Completed:
   - yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Thanks for bringing this PR upfront. 
As discussed in the call, Do update us about the issue you are facing for the publisher id.

**Comment by jayeshprajapaticrest** [comment]
> Hello @jayeshprajapaticrest, Thanks for bringing this PR upfront. As discussed in the call, Do update us about the issue you are facing for the publisher id.

@v-prasadboke Sure we are in discussion, will updates you once we have any update on that.

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke We have fixed the validation error by updating the Publisher ID.

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Thanks for committing the requested changes. I'll take a look at it and update you by 10 November. 2023.

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Sorry for the inconvenience but due to lack of availability we were unable to Investigate this PR. 
We will investigate this PR and try to update you by 15 November, 2023.

**Comment by v-prasadboke** [comment]
Hello @jayeshprajapaticrest, Can you share the working images of function app

**Comment by jayeshprajapaticrest** [comment]
> Hello @jayeshprajapaticrest, Can you share the working images of function app

@v-prasadboke Please find the working image of the Playbook.
Playbook Success Execution

**Comment by jayeshprajapaticrest** [comment]
> Hello @jayeshprajapaticrest, Can you share the working images of function app

image

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke I have added working image of Function App.

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
