### PR TITLE
Add new playbooks for Sentinel2MISP

### PR DESCRIPTION
**Pull request by lnfernux**
Required items, please complete
   
   Change(s):
   - Add new playbook solution for pushing indicators (hashes, filenames) from Sentinel to MISP

   Reason for Change(s):
   - New capability for interaction with MISP

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

# Introduction

This is a solution that allows you to push indicators (hashes, filenames) from Defender 365 'Malware was prevented' alerts to your MISP server. 

The solution consist of two playbooks - forwarder and orchestrator. The orchestrator will live in your Azure tenant and the forwarders can be deployed to each workspace you manage. The forwarder, in combination with an automation rule will push indicators to the orchestrator, which in turn will push it to MISP.

## Required access

This solution will use 1 (optional 2) connectors:
- Azure Sentinel (with managed identity and Microsoft Sentinel Reader role)
- Azure Key Vault (with managed identity, key vault reader and access policy (`Get, List`)
    - This step is optional, but highly recommended for production

### CODE REVIEW

**Comment by rahul0216** [comment]
@infernuxmonster  According to readme file, these Playbooks are not Production ready, besides Playbook template lacks metadata. I would suggest to check other playbooks for reference and update your playbook accordingly.

**Comment by infernuxmonster** [comment]
> @infernuxmonster According to readme file, these Playbooks are not Production ready, besides Playbook template lacks metadata. I would suggest to check other playbooks for reference and update your playbook accordingly.

I can update the metadata, but the only reason I mention "not production ready" is due to the lack of a key vault integration built in. This is however something I address in the setup and advise people to add. This is the way most data connectors and solutions does it in regard to secrets - if you look at a few of them, they don't implement key vaults by default, but advise doing so for production purposes.

**Comment by rahul0216** [comment]
Thanks for the changes @infernuxmonster. I would suggest to use [Playbook Template Generator](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator) to generate the template. This will generate the template with necessary parameters and sanitize the template for any PII data. You can update the metadata after that.

**Comment by v-atulyadav** [comment]
Hi @lnfernux, 
@rahul0216 has suggested to use playbook template generator, please act accordingly.
Thanks

**Comment by lnfernux** [comment]
> Thanks for the changes @infernuxmonster. I would suggest to use [Playbook Template Generator](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator) to generate the playbook template. This will generate the template with necessary parameters and sanitize the template for any PII data. You can update the metadata after that.

@rahul0216: This template has been generated using the playbook template generator 👍🏻 But I can update the metadata again.

**Comment by rahul0216** [comment]
@lnfernux Thanks for the updates. Changes look good. Playbooks can be improved further,
1) By taking MISP Orchestrator URL as parameter in MISP Forwarder Playbook, So that user doesn't need to edit the playbook after deployment
2) Key vault integration to store MISP key 

I'll not push for these changes, but advice to implement in future updates.

**Comment by rahul0216** [comment]
@lnfernux Can you attach screenshot of successful run of these playbooks?

**Comment by lnfernux** [comment]
Hey. Will get on this once I'm back from my annual leave. No need for reminders :)
________________________________

**Comment by v-atulyadav** [comment]
sure @lnfernux. Thanks

**Comment by lnfernux** [comment]
Hey - so just made a change and added the suggestion that some parameters should be deployable as a template - that is now added so that the orchestrator takes MISP URI, Key and Org as input during deployment and no need for manual changes. The forwarder also takes the webhook URI of the MISP Orchestrator as input.

README.MD updated to reflect this.

As for sucessfull deployments:

**Orchestrator**:
*Please note this is a version where the keyvault option in the README.MD has been added.*
OrchestratorRun

**Template version of the orchestrator**:
*Just to show deployment is fine without keyvault integration as well.*
OrchestratorDeployment

**_Failures are for this reason:_**
FailureReason
This is simply because there are no good ways of quickly checking the MISP service for any existing indicators on events without using exhaustive calls. So it will fail when the indicator is already there. Plan to add some sort of check for this to make it not show errors.

**Forwarder**:
ForwarderRun

Hope this is ok, if any questions feel free to ask.

**Comment by v-atulyadav** [comment]
Thanks @lnfernux for attaching screenshots.

**Review by rahul0216 — APPROVED** [review]
@lnfernux Thanks for the updates and screenshots. Changes look good. Couple of suggestions you can consider in future updates,
1. "event_creator_mail" You can take this also as parameter. So manual change would be needed after deplyment.
2. You mentioned too, Error handling for the scenario where indicator already exist.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
