### PR TITLE
Added 5 New Analytic Rule Detections for Azure WAF

### PR DESCRIPTION
**Pull request by shabaz-github**
Added new analytic rules for Path Traversal Attack, Code Injection Attack and Scanner Detection Attack

   Required items, please complete:
   
   Change(s):
   - Added the following 5 New Analytic Rule Detections for Azure WAF
            -  AFD-WAF-Code-Injection.yaml
            -  AFD-WAF-Path-traversal-Attack.yaml
            -  App-GW WAF-Code_injection.yaml
            -  App-GW-WAF-Path-Traversal-Attack.yaml
            -  App-GW-WAF-Scanner-detection.yaml

   Reason for Change(s):
   - Adding new detection queries for Azure WAF

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @shabaz-github, 
Thank you for raising Pull Request with us! We will review the Pull Request internally and get back to you by shortly.
Thanks

**Comment by v-rusraut** [comment]
Hi @shabaz-github,
Please work on above comment and also provide sample data for testing Analytic Rule.
Thanks.

**Comment by v-rusraut** [comment]
Hi @shabaz-github,
Please add status property in Analytic Rules, refer below image for reference.



And also provide sample data for testing Analytic Rules.
Thanks

**Comment by shabaz-github** [comment]
@v-rusraut Status property has been added - Could you please guide on how to get the sample data added?

**Comment by shabaz-github** [comment]
Could you please also help with fixing the check error 'run script on changing detections / add-comment / comment (pull_request)' not sure why this check is failing.

**Comment by v-rusraut** [comment]
> @v-rusraut Status property has been added - Could you please guide on how to get the sample data added?
Hi @shabaz-github,
Please upload sample data on below path 
https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom
Thanks

**Comment by v-rusraut** [comment]
Hi @shabaz-github,
To resolve the validation error please update your branch from master branch and commit again.
Thanks

**Comment by v-atulyadav** [comment]
Hi @shabaz-github, 
Please add sample data as requested earlier. Thanks

**Comment by shabaz-github** [comment]
@v-atulyadav Sample data csv files have been added

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
