### PR TITLE
change filter condition for messages

### PR DESCRIPTION
**Pull request by rednithin**
Required items, please complete
   
   Change(s):
   - Moved ISO8601 format string into a constant.
   - Modified filter function to filter by remediationTimestamp
   - Added some logs. 

   Reason for Change(s):
   - We are filtering `threats` by using `latestTimeRemediated`.
  ```
producer = asyncio.create_task(self.generate_resource_ids(session, Resources.threats,threats_date_filter, intermediate_queue, FilterParam.latestTimeRemediated, context, producer_post_process_func))
```
 But in _extract_messages we are filtering by `receivedTime` this is causing some messages to get dropped. 

   Version Updated:
   - Do I need to upgrade the version?

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by rednithin** [comment]
```bash
AbnormalSecurity/Data Connectors/Tests on  nreddy/pr/fix-filter-for-threats [!] via 🐍 v3.12.2 
➜ python3 -m unittest -vv soar_connector_async_test.py
test_correct_flow_with_one_filtered_message (soar_connector_async_test.TestAbnormalSoarConnectorAsync.test_correct_flow_with_one_filtered_message) ... /Users/nithin/Extensions/Azure-Sentinel/Solutions/AbnormalSecurity/Data Connectors/Tests/soar_connector_async_test.py:73: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(f"Skipped processing message for threat: {ctx}")
WARNING:root:Skipped processing message for threat: {'2024-05-07T08:15:00Z', '2024-05-07T08:09:03.183578Z', 4670020130001212344, '40080400-6300-9600-f800-afb76fd00000', '2024-05-07T08:10:00Z'}
WARNING:root:Skipped processing message for threat: {'2024-05-07T08:15:00Z', '2024-05-07T08:15:03.183578Z', '40080400-6300-9600-f800-afb76fd00000', 4670020130001212346, '2024-05-07T08:10:00Z'}
ok
test_correct_flow_with_three_filtered_message (soar_connector_async_test.TestAbnormalSoarConnectorAsync.test_correct_flow_with_three_filtered_message) ... ok
test_correct_flow_with_two_filtered_message (soar_connector_async_test.TestAbnormalSoarConnectorAsync.test_correct_flow_with_two_filtered_message) ... WARNING:root:Skipped processing message for threat: {'2024-05-07T08:15:00Z', '2024-05-07T08:15:03.183578Z', '40080400-6300-9600-f800-afb76fd00000', 4670020130001212346, '2024-05-07T08:09:00Z'}
ok
test_wrong_time_format_in_context (soar_connector_async_test.TestAbnormalSoarConnectorAsync.test_wrong_time_format_in_context) ... ERROR:root:Failed to parse time for threat_id: ('40080400-6300-9600-f800-afb76fd00000', '2024-05-07T08:10:00Z', '2024-05-0708:15:00Z') with error time data '2024-05-0708:15:00Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
ok
test_wrong_time_format_in_remediation_timestamp (soar_connector_async_test.TestAbnormalSoarConnectorAsync.test_wrong_time_format_in_remediation_timestamp) ... WARNING:root:Skipped processing message for threat: {'2024-05-07T08:15:00Z', '2024-05-07T08:09:03.183578Z', 4670020130001212344, '40080400-6300-9600-f800-afb76fd00000', '2024-05-07T08:10:00Z'}
ERROR:root:Failed to process message for threat: {'2024-05-07T08:15:00Z', '40080400-6300-9600-f800-afb76fd00000', 4670020130001212345, '2024-05-07T08:10:03Z', '2024-05-07T08:10:00Z'} with error time data '2024-05-07T08:10:03Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
WARNING:root:Skipped processing message for threat: {'2024-05-07T08:15:00Z', '2024-05-07T08:15:03.183578Z', '40080400-6300-9600-f800-afb76fd00000', 4670020130001212346, '2024-05-07T08:10:00Z'}
ok

----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK

AbnormalSecurity/Data Connectors/Tests on  nreddy/pr/fix-filter-for-threats [!] via 🐍 v3.12.2 
➜ 
```

**Comment by rednithin** [comment]
@microsoft-github-policy-service agree [company="Abnormal Security"]

**Comment by rednithin** [comment]
@v-atulyadav What is the right way to generate zip file?

I am using 
```
➜ zip -r AbnormalSecurityConn4.zip host.json proxies.json requirements.txt SentinelFunctionsOrchestrator SentinelTimerTrigger SoarDatetimeEntity .python_packages
```

Copying `.python_packages` from previous zip file. 

But not sure its the right way to do it.

**Comment by v-atulyadav** [comment]
Hi @rednithin,
You need to update or replace the below-changed file into a zip file only. 
image

All the files inside zip remain as they were earlier. Once we merge the PR, your changes will reflect automatically.

**Comment by rednithin** [comment]
Made the zip with this command

```zsh
Solutions/AbnormalSecurity/Data Connectors on  nreddy/pr/fix-filter-for-threats via 🐍 v3.12.2 
➜ zip -r AbnormalSecurityConn.zip SentinelFunctionsOrchestrator/soar_connector_async.py
updating: SentinelFunctionsOrchestrator/soar_connector_async.py (deflated 74%)

Solutions/AbnormalSecurity/Data Connectors on  nreddy/pr/fix-filter-for-threats [!] via 🐍 v3.12.2 
➜ 
```

**Comment by rednithin** [comment]
image

Logs are working fine. Can ignore the duplicated messages. There are two functions running.

**Comment by rednithin** [comment]
@v-atulyadav Is there anything else needed from my end?

**Comment by rednithin** [comment]
Also tested out previously missed event by hardcoding timestamps. 
image

[More info here](https://github.com/rednithin/Azure-Sentinel/pull/1)

**Comment by v-atulyadav** [comment]
Hi @rednithin,
Please share invocation logs screenshots. Thanks

**Comment by rednithin** [comment]
Screenshot 2024-05-31 at 8 23 05 AM
Screenshot 2024-05-31 at 8 32 29 AM


@v-atulyadav is this the one you are talking about?

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
