### PR TITLE
Cloudflare data connector update

### PR DESCRIPTION
**Pull request by vu-socprime**
Change(s):
   - add supporting gzipped files in Cloudflare data connector

### CODE REVIEW

**Review by anki-narravula — COMMENTED** [review]
Hi @vu-socprime , what is the purpose of appending **(?=\{"** for line separators. Its not going to split properly with this
`lineSeparator": "[\\n\\r\\x0b\\v\\x0c\\f\\x1c\\x1d\\x85\\x1e\\u2028\\u2029]+(?=\{)"`

**Comment by vu-socprime** [comment]
> Hi @vu-socprime , what is the purpose of appending **(?={"** for line separators. Its not going to split properly with this
> `lineSeparator": "[\\n\\r\\x0b\\v\\x0c\\f\\x1c\\x1d\\x85\\x1e\\u2028\\u2029]+(?=\{)"`

Hi @anki-narravula, some of [\\n\\r\\x0b\\v\\x0c\\f\\x1c\\x1d\\x85\\x1e\\u2028\\u2029] can be present inside event's values and because of that the error is raised. So I added positive lookahead (?=\{) to be sure that the event is not divided.
But I missed one backslash in azure deploy file. Already fixed it.

**Comment by anki-narravula** [comment]
> 

Thanks @vu-socprime. Looks good

**Review by anki-narravula — APPROVED** [review]

**Comment by v-sabiraj** [comment]
The Solution is with customer, we can merge this once we get approval from customer, thanks.

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
