### PR TITLE
Resolve data connector deploy to azure error

### PR DESCRIPTION
**Pull request by FortiNDR-Integration**
Required items, please complete
   
   Change(s):
   - Update linuxFxVersion setting.
   - Update data connector custom deploy guide line

   Reason for Change(s):
   - When deploying the data connector to azure, we got error: 
   - `{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "The parameter LinuxFxVersion has an invalid value.",
        "details": [
            {
                "message": "The parameter LinuxFxVersion has an invalid value."
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}`

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by FortiNDR-Integration** [comment]
Hi,
I have raised this issue here https://learn.microsoft.com/en-us/answers/questions/1534921/azure-function-linux-python-3-9-problem?page=1&orderby=Helpful&comment=answer-1452262#newest-answer-comment. And got an answer from an Microsoft employee. I have made the change based on his answer, but could test it locally. Could you please help us with it to make sure the data connector could deploy successfully?

**Comment by v-prasadboke** [comment]
Sure @FortiNDR-Integration let's schedule a call for this, I'll get a better understanding for the same.

**Comment by FortiNDR-Integration** [comment]
@v-prasadboke , I have fixed the issue with the help from https://learn.microsoft.com/en-us/answers/questions/1534921/azure-function-linux-python-3-9-problem, and tested, it is working. Now we are having a new issue that the deployed function app is not showing any functions inside it, we will keep looking into it.

**Comment by v-prasadboke** [comment]
Thanks for the updates @FortiNDR-Integration

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
