### PR TITLE
TCPandUDP Port Description Watchlist

### PR DESCRIPTION
**Pull request by swiftsolves-msft**
This watchlist is meant to create a table of offical and unoffical tcp and udp port information. This watchlist can be used to provide context to other network based logs that do not contain port description or application service information running on port.

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@anki-narravula Please review and provide your approve.

**Comment by vmanojreddy** [comment]
@anki-narravula Please review and provide your approve.

**Comment by v-spadarthi** [comment]
@anki-narravula: Could you please review the watchlist. Thanks!

**Comment by v-spadarthi** [comment]
@NikTripathi :Please review the watchlist and provide your approve.

**Comment by v-mchatla** [comment]
Hi @NikTripathi 
Can you please review and approve the PR.
Thanks

**Comment by NikTripathi** [comment]
Looking into this.

**Comment by v-spadarthi** [comment]
Hi @NikTripathi
Can you please review and approve the PR.
Thanks

**Comment by v-mchatla** [comment]
Hi @NikTripathi,
Can you please review or assign it to someone who can work on it.
Thanks

**Comment by v-mchatla** [comment]
Hi @NikTripathi ,
Could you please provide update on this.
Thanks

**Comment by v-mchatla** [comment]
Hi @NikTripathi ,
Could you please provide update on this.
Thanks

**Comment by v-mchatla** [comment]
Hi @NikTripathi,
Could you please provide update on this.
Thanks

**Comment by v-mchatla** [comment]
Hi @NikTripathi,
Could you please provide update on this.
Thanks

**Comment by NikTripathi** [comment]
Sorry for the delay. I am working on this.

**Comment by v-spadarthi** [comment]
Hi @NikTripathi,
Could you please provide update on this.
Thanks

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
