### PR TITLE
Add Jamf Protect to the Content Hub

### PR DESCRIPTION
**Pull request by txhaflaire**
Adding a new workbook to the Content Hub that provides visual insight into events captured by Jamf Protect.

   Required items, please complete
   
   Change(s):
   - New workbook for Jamf Protect into the Sentinel Content Hub.

   Reason for Change(s):
   - Adding new workbook into the Content Hub

   Version Updated:
   - N/A

   Testing Completed:
   - YES

   Checked that the validations are passing and have addressed any issues that are present:
   - YES

### CODE REVIEW

**Comment by v-mchatla** [comment]
Please fix the validation errors, hope below information will help in fixing them:
1. Logo file added is not valid. If you are adding GUID make sure it is unique.
2. In workbook fallbackResourceIds field is having Subscription details make sure to remove hardcoded values and follow the workbook template for fixing any other validation issues.
3. Please share the sample data to test the workbook.
Let us know if you need any help over here.
Thanks.

**Comment by txhaflaire** [comment]
@v-mchatla Thank you for the support on getting this into the Content Hub.

- Any guidance on creating a proper SVG? 
- Could you guide me on how to export sample data and have it transferred to you?

**Comment by txhaflaire** [comment]
@v-spadarthi @v-mchatla I have updated the logo, the workbook and provide sample data in the related folders. Please let me know if anything needs to be done from my side still!

**Comment by v-mchatla** [comment]
Hi @txhaflaire,
Thanks for the update. I will verify the changes and let you know if anything required from your end.
Thanks

**Comment by v-mchatla** [comment]
Hi @txhaflaire 
Changes looks good to me. Just need small confirmation - We have PR #6372, seems both the Pr's having same workbook. Have you created 2PR's for the same workbook changes. If yes, please close this PR as it is part of individual folder, and 6372 Pr is already having package for the same.
Thanks

**Comment by txhaflaire** [comment]
I think this one can be closed; my main goal was to start publishing in the Content Hub, which seems it needs to be in the Solutions folder and creating a Solution package. So if having the Workbook in this location is not required let me know so we can close the PR.

Just for my understanding, what could be a reason to publish a Workbook in this Workbook folder?

**Comment by v-mchatla** [comment]
Hi @txhaflaire 
Thanks for the confirmation. You can close this PR, we will review and merge the PR #6372.
To give some context around the old way of maintaining content in individual folders has some drawbacks for example each folder will gets deployed individually, user may see stale data till all the content gets deployed to avoid this we are maintaining all the content of a solution in single folder, so all the content gets deployed in one go.
Hope this answers your question.
Thanks

**Pull request closed without merging**
