### PR TITLE
Export watchlist items

### PR DESCRIPTION
**Pull request by dagnyverbeeck**
Adding a script for exporting watchlist items to a csv file. Found under 'Tools' folder

   Required items, please complete
   
   Change(s):
   - Added functionality for exporting watchlist items

   Reason for Change(s):
   - Functionality didn't exist

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by dagnyverbeeck** [comment]
> 

@microsoft-github-policy-service agree [company="{Dagny Verbeeck from The Collective Consulting}"]

**Comment by dagnyverbeeck** [comment]
@microsoft-github-policy-service agree

**Comment by v-vdixit** [comment]
Hi, we are looking into this, will update shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @dagnyverbeeck we are waiting for updates from the concerned team, thanks!

**Comment by v-vdixit** [comment]
Hi @dagnyverbeeck we are looking into this, will update you shortly, thanks!

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, we are looking into this, will update you shortly, thanks!

**Comment by v-atulyadav** [comment]
Hi @dagnyverbeeck, can you please add author details and support information readme file. Thanks

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, hope you are doing well. Just wanted to check if you got a chance to look at the suggestions shared. Please feel free to reach out to us for any queries or support. Thanks!

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, we are waiting for your response. Thanks!

**Comment by v-atulyadav** [comment]
Hi @dagnyverbeeck, 
It would be helpful if you included author details and support information in the readme file. Thanks

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, we are waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, as mentioned above comment, can you please add author details and support information in readme file. Thanks

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, can you please add author details and support information in readme file. Thanks

**Comment by v-sudkharat** [comment]
Hello @dagnyverbeeck, hope you are doing well. As mentioned above comment, can you please add author details and support information in readme file. Thanks

**Comment by v-sudkharat** [comment]
Hi @dagnyverbeeck, we wanted to check on the status of PR #8107. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. As per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by v-sudkharat** [comment]
Hello @dagnyverbeeck, since we have not received a response in the last 7 days, we are closing your PR #8107 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
