### PR TITLE
Data connector for VMRay Email Threat Defender

### PR DESCRIPTION
**Pull request by janteske**
## Proposed Changes

  - Add a new data connector for ingesting VMRay ETD email data through a VMRay Platform API connection.

### CODE REVIEW

**Comment by janteske** [comment]
FYI, the link in the display text for the `Microsoft.OperationalInsights/workspaces/sharedKeys` permission provider from the template doesn't lead to a useful place: https://docs.microsoft.com/azure/azure-monitor/platform/agent-windows#obtain-workspace-id-and-key.

I tried to change it to https://docs.microsoft.com/azure/azure-monitor/agents/log-analytics-agent#workspace-id-and-key and fix a minor grammar error ("Read and write permissions ... is required"), but the PR checks insist on the exact values from the template being used.

**Comment by preetikr** [comment]
@v-jayakal - This would go in as solution. Thanks.

**Comment by oshezaf** [comment]
@v-rucdu : I don't see a parser here. Maybe I just missed it.

**Comment by v-rucdu** [comment]
> @v-rucdu : I don't see a parser here. Maybe I just missed it.

@oshezaf : Sorry mentioned mistakenly, Parser does not exist. Please ignore!!!
Thanks!!!

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
