### PR TITLE
Update IntrotoKQL.json

### PR DESCRIPTION
**Pull request by malowe101**
Fixing issues that appeared that broke how GitHub JSON was being parsed for use.

   Required items, please complete
   
   Change(s):
   - changed how parameter parsed another parameter that fetched JSON from GitHub.

   Reason for Change(s):
   - Issue appeared that caused parsing to fail, which broke the entire workbook.

   Testing Completed:
   - Deployed template from scratch to confirm changes were valid and still worked.

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @malowe101 
We will review the Pull Request internally and get back to you by shortly.
Thanks

**Comment by v-rusraut** [comment]
Hi @malowe101,
Just let us know, this PR is ready to review or not ?
Because as I see you are still committing few changes.
Thanks

**Comment by v-rusraut** [comment]
Hi @malowe101,

Please work on below points :

- As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using V3 tool
Please go through this readme file on how to use the V3 tool
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md 

- And we need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

- Please add below workbook images into mentioned path:
IntrotoKQL-black.png, IntrotoKQL-white.png
Path : Solutions\KQL Training\Workbooks\Images\Preview

Thanks

**Comment by malowe101** [comment]
Recalling the PR as I need to review the new method for updating workbooks in content hub.

**Pull request closed without merging**
