### PR TITLE
IPCustomEntity column is a array whereby a string (IP) is expected

### PR DESCRIPTION
**Pull request by TristanvanOnselen**
The entity mapping does not support multiple values in a array.

   Required items, please complete
   
   Change(s):
   - Removed the entity mapping for the IP address field

   Reason for Change(s):
   - The entity mapping engine expects a unique value not a array. 

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review the detections. thanks!!!

**Comment by aprakash13** [comment]
There seems to be some validation errors. Can we please address those?
Feel free to let us know if any help is needed in addressing those.

**Comment by v-sabiraj** [comment]
Hey @TristanvanOnselen, please fix the validations, thanks.

**Comment by v-dvedak** [comment]
Hey [@TristanvanOnselen](https://github.com/TristanvanOnselen), we wanted to check on the status of this PR [IPCustomEntity column is a array whereby a string (IP) is expected](https://github.com/Azure/Azure-Sentinel/pull/4479)
. It is pending from more than 60 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-dvedak** [comment]
Hi @TristanvanOnselen, Since we have not received response from last 7 days, we are closing your [PR](https://github.com/Azure/Azure-Sentinel/pull/4479) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
