### PR TITLE
Updated python packages to fix vulnerabilitis issue in DataConnector code

### PR DESCRIPTION
**Pull request by niralishah-crest**
Change(s):

Updated python packages in DataConnector zip
Reason for Change(s):

Due to the vulnerabilities found in existing version available of cryptography and aiohttp
Version Updated:

No
Testing Completed:

Yes
Checked that the validations are passing and have addressed any issues that are present:

Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest, Thanks for raising this PR. This PR will be investigated and will update you about the same before 31 January, 2024.

**Comment by v-prasadboke** [comment]
Hi @niralishah-crest, A humble request please let us know if there are any more required commits so that we can proceed with the investigation

**Comment by niralishah-crest** [comment]
> Hi @niralishah-crest, A humble request please let us know if there are any more required commits so that we can proceed with the investigation

@v-prasadboke 
You can proceed ahead with the investigation. Sorry for the incovenience if any
Thanks.

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest, Please share the functional images of function app

**Comment by niralishah-crest** [comment]
@v-prasadboke 
Please find attached screenshots of running function app.

Screenshot 2024-01-31 183035

Screenshot 2024-01-31 183152

Screenshot 2024-01-31 183322

Screenshot 2024-01-31 183351

Screenshot 2024-01-31 183436

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
