### PR TITLE
Entity mapping added to UserAccountAddedToPrivlegeGroup_1h.yaml

### PR DESCRIPTION
**Pull request by pavelmirlenko**
Change(s):
    Entity mapping added: "Security Group"

   Reason for Change(s):
   More information available on alert preview. The most important WHAT user added to WHAT security group.

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   -Yes

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @pavelmirlenko, thanks for raising this PR, we will review this PR by 28 Sep 2023.

**Comment by v-rbajaj** [comment]
Hi @pavelmirlenko, seems like the newly added EntityMapping for Security Group is failing in validation, can you please check if it correctly mapped?

**Comment by v-rbajaj** [comment]
Hi @pavelmirlenko, can you please provide some update on this PR?

**Comment by pavelmirlenko** [comment]
Yes, it continuously fails. I will close the PR.

**Pull request closed without merging**
