### PR TITLE
Update CyberArkEPMSentinelConn.zip

### PR DESCRIPTION
**Pull request by cyberark-bizdev**
Required items, please complete
   
   Change(s):
   - Repackage distribution of CyberArkEPMSentinelConn.zip as it had wrong structure

   Reason for Change(s):
   - The function CyberArkEPM was not being recognized properly

### CODE REVIEW

**Comment by cyberark-bizdev** [comment]
Approved

**Comment by v-mchatla** [comment]
Hi @cyberark-bizdev 
Sorry for the delay. We are getting module not found error while testing the latest zip.
image
Can you please add all the dependencies to the python package folder and confirm.
Thanks

**Comment by cyberark-bizdev** [comment]
Added lxml dependency to requirements.txt

Review

**Comment by cyberark-bizdev** [comment]
Approved

**Comment by v-mchatla** [comment]
Hi @cyberark-bizdev 
Can you please update the zip folder with updated requirement.txt and also add relevant lxml packages under .python_packages folder.
Can you please share the working screenshot from function app, just to ensure the function app is working fine without any errors.
I have tried adding these things locally and tested, but I'm running into below error. So please help me with the success screenshot to approve the changes.
image
Thanks

**Comment by cyberark-bizdev** [comment]
Review

**Comment by v-mchatla** [comment]
Hi @cyberark-bizdev 
I have tried testing the updated zip file, still getting the same issue.
Thanks

**Comment by v-mchatla** [comment]
Hi @cyberark-bizdev 
Can you please verify the function app and share the success screenshot.
Thanks

**Review by v-mchatla — APPROVED** [review]
Changes look good and I don't see any package related issues now.
image

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
