### PR TITLE
New Workbook

### PR DESCRIPTION
**Pull request by FelixBueltmannBarracuda**
Required items, please complete
   
   Change(s):
   - Cleaned folder structure and added a new Workbook

   Reason for Change(s):
   - See guidance below

   Version Updated:
  
   Testing Completed:
   - In running environment

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda I upgraded the api version due to which the arm ttk check was failing but now this new content validation check is failing please look into this

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please update on the following

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please provide your reply on the above comments

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please provide your feedback on this

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda its been more than a month please reply on the above comments
or this pr will be closed

**Comment by v-dvedak** [comment]
@FelixBueltmannBarracuda, Since we have not received a response from quite a long, we are closing your PR #<7443> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Pull request closed without merging**
