### PR TITLE
Update - Cybersixgill Actionable Alerts

### PR DESCRIPTION
**Pull request by syed-loginsoft**
Change(s):
   - Updated Data connector to accept Organization ID
   - Updated playbooks to accept Organization ID

   Reason for Change(s):
   - Added Multi-tenancy support

   Testing Completed:
   - Yes
AlertStatusUpdate
Function
AlertStatusDelete

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

image

### CODE REVIEW

**Comment by v-vdixit** [comment]
Hi @rahul0216 / @manishkumar1991, please check and provide your feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi @rahul0216 / @manishkumar1991 please provide update on this, thanks!

**Comment by v-vdixit** [comment]
Hi @rahul0216 / @manishkumar1991 please share your feedback, thanks!

**Review by rahul0216 — DISMISSED** [review]
Playbook changes look good.

**Comment by rahul0216** [comment]
@v-vdixit, please get the connector updates reviewed by Anki or Mahesh.

**Comment by v-vdixit** [comment]
Hi @mkchiliveri Please check the connector updates in this and provide your feedback, thanks!

**Comment by v-vdixit** [comment]
Hi @mkchiliveri please provide your updates on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula Please provide your feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula please provide your feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula please provide feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula please provide update on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula please provide feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi @anki-narravula we are waiting for your feedback on this, thanks!

**Comment by v-vdixit** [comment]
Hi we are looking into this, will update soon, thanks!

**Comment by v-vdixit** [comment]
Hi @syed-loginsoft, could you please add screenshots demonstrating successful working of the function app, thanks!

**Comment by v-vdixit** [comment]
Hi @syed-loginsoft we are waiting for your update on this, thanks!

**Comment by v-vdixit** [comment]
> Hi @syed-loginsoft, could you please add screenshots demonstrating successful working of the function app, thanks!

Hi @syed-loginsoft we are still waiting for your update on this

**Comment by v-vdixit** [comment]
Hi @syed-loginsoft we have checked all other content in the PR it looks fine, waiting for you to add screenshots demonstrating successful working of connector, thanks!

**Comment by syed-loginsoft** [comment]
I will share the screenshots today

**Comment by v-vdixit** [comment]
Hi @syed-loginsoft please fix the failing arm-ttk validation by replacing the apiVersions dated "2021-05-01" at all error locations with "2022-02-01", more details of this error can be found [here](https://github.com/Azure/Azure-Sentinel/actions/runs/5343348834/jobs/9688886990?pr=7629), thanks.

**Comment by v-vdixit** [comment]
Hi @syed-loginsoft waiting for your update on this, thanks!

**Comment by syed-loginsoft** [comment]
Requested screenshot
image

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
