### PR TITLE
Edgescan azure sentinel integration

### PR DESCRIPTION
**Pull request by hollyollyoxenfree**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by sarah-yo — CHANGES_REQUESTED** [review]
Most of your images aren't rendering in the README, and the documents validation check is failing, please can you check that you have no links that contain a localisation tag e.g. "en-us"

Thanks!

**Comment by hollyollyoxenfree** [comment]
Hi Sarah!

Are you talking about the readme in  Azure-Sentinel/Playbooks/Edgescan-AzureSentinel-Integration ? I'm seeing all pictures rendering there just fine. It does look like the readme in Azure-Sentinel/Playbooks/ is not rendering a picture but I have not modified that file. I searched through my links for the localization tag you mentioned and was unable to find anything. Please let me know what else I can try.

**Comment by sarah-yo** [comment]
Hmmm okay, it might render fine when merged, seen that before. Doing further digging, the locale scan was upset by some of the .png files which makes no sense so going to ignore that. :)

**Comment by hollyollyoxenfree** [comment]
Thank you Sarah!

**Pull request merged**
