### PR TITLE
08 16 2023  as make GitHub repository private

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
Required items, please complete
   
   Change(s):
   New Playbook

   Reason for Change(s):
   New Playbook

   Testing Completed:
   Yes

  
image

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, Thank you for raising this. This PR will be examined and will update you shortly before 24 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, can we connect tomorrow for this PR. I've a query.
If it's possible for you please let me know on this PR or even you can drop a mail to v-prasadboke@microsoft.com.
I work in IST Time Zone and I'm usually available between 2:00 PM to 6:00 PM.
Thanks,
Prasad.

**Comment by v-prasadboke** [comment]
Hello @AcceleryntSecurityDev, As asked earlier please respond if you are available for the call. 
Thanks.

**Comment by AcceleryntSecurityDev** [comment]
@v-prasadboke Hello Prasad, sorry I was unable to connect. I typically work on pacific time, so meeting in your proposed time window would be difficult. I do see these playbooks have already been merged, but if you still need to reach me, you can send me an email at githubuser@accelerynt.com.

**Pull request merged**
