### PR TITLE
Updated publisherId and offerId as per require.

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Change(s):
   - Updated publisherId and offerId

   Reason for Change(s):
   - We raised the [PR](https://github.com/Azure/Azure-Sentinel/pull/8179) for this solution and it was already merged. But when we are going to publish an offer we will getting the error as mentioned in below image. which point to mismatched in the publisherId and offerId. To make it success we updated both the value to correct and created package to raise the PR.
   
image001

   Version Updated:
   - No.

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-dvedak** [comment]
Hi @jayeshprajapaticrest, support link is currently "https://support.microsoft.com" but since this is Cisco supported solution, it should be support link for Cisco. Please correct/update it at all the locations. Thanks!

**Comment by jayeshprajapaticrest** [comment]
> 

@v-dvedak We haven't updated other information like support link etc...
Its same as the previously merged [PR](https://github.com/Azure/Azure-Sentinel/pull/8179).
https://github.com/jayeshprajapaticrest/Azure-Sentinel/blob/12750837f976cf56eeafc28545be94282e180373/Solutions/Cisco%20SD-WAN/Package/mainTemplate.json

**Comment by v-dvedak** [comment]
@jayeshprajapaticrest, I understand you haven't updated any information in this PR but support link needs to be corrected as the solution is Cisco supported. Thanks!

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest, I understand you haven't updated any information in this PR but support link needs to be corrected as the solution is Cisco supported. Thanks!

@v-dvedak I have updated the support link. Can you please proceed?
Thanks

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
