### PR TITLE
ASIM imAuthentication correction

### PR DESCRIPTION
**Pull request by Korving-F**
This PR corrects the imAuthentication ASIM parser.

   Change(s):
   - Removed incorrectly placed comma in `Parsers/ASimAuthentication/AuthenticationEmpty.yaml`
   - Corrected time query in all the other files (comparison was made against starttime while endtime was needed)

   Reason for Change(s):
   - Fixes broken parser

### CODE REVIEW

**Comment by Korving-F** [comment]
NB! This does not yet update the ARM templates.

**Comment by oshezaf** [comment]
Hi @Korving-F  (well Frank): Thaks for fixing both issues. We are in the midst of [PR a large rebuild of the Authentication package](https://github.com/Azure/Azure-Sentinel/pull/4401) and to avoid merging challenge, I will ask Yaron to apply your fixes there.

**Comment by Korving-F** [comment]
Hi @oshezaf (well Ofer ^_^). No problem, really appreciating all the ASIM development! Would you prefer me closing the PR now or wait for Yaron?

P.s. I was wondering if you could take a quick look at the following changes (sorry for the off-topic request):
- #4291
- #4287

**Comment by oshezaf** [comment]
Yes. You can close the PR>

As to the other two: I would rather that the owners take care of them. The first one looks correct, but I will let the MSTIC team review. As to the other: there was some reason sub techniques were included. Anyways, Ajeet would know.

Thanks~
~ Ofer

**Comment by Korving-F** [comment]
Will be added to #4401.

**Pull request closed without merging**
