### PR TITLE
SailPoint IdentityNow

### PR DESCRIPTION
**Pull request by prashant-kagwad-sp**
SailPoint IdentityNow Integration 

## Proposed Changes

  - Data Connector for Azure Sentinel to pull events from IdentityNow
  - Analytic Rules
  - Custom Connector for IdentityNow (Preview)

### CODE REVIEW

**Comment by prashant-kagwad-sp** [comment]
@v-jayakal - 
Thank you for reviewing the PR. I have updated the missing files. Can you please review the PR once again.

**Comment by v-maudan** [comment]
after deployement, unable to see function [PFB screenshot for reference]. Can you please fix? Thanks!
image

**Comment by prashant-kagwad-sp** [comment]
@v-maudan - For the Function to be visible in the we used the GitHub link in WEBSITE_RUN_FROM_PACKAGE. With the new changes (short links) I was under the assumption that the zip would be imported into the Function space as it did before using the GitHub link. Is that assumption wrong?

Any pointers is much appreciated.

**Comment by prashant-kagwad-sp** [comment]
Function App should now be visible.

**Comment by prashant-kagwad-sp** [comment]
> @prashant-kagwad-sp , please update Dataconnector Id (**SailPointIdentityNow**) [here](https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json) to pass PR detectionTemplateSchemaValidation. Thanks!

Updated.

**Pull request merged**
