### PR TITLE
Added CustomizedJson function to fix 500 column limit for Oracle Cloud Infrastructure

### PR DESCRIPTION
**Pull request by v-amolpatil**
Required items, please complete
   
   Change(s):
   - Added a new function in main.py file and also update the package `OCILogsConn.zip` which is under `Data Connectors` folder.

   Reason for Change(s):
   - to fix error of 500 column limit

   Version Updated:
   - No

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by NikTripathi** [comment]
Looking into this.

**Comment by NikTripathi** [comment]
It is with customer and waiting for there response

**Comment by v-atulyadav** [comment]
It is with customer and waiting for there response

**Comment by v-atulyadav** [comment]
It is with customer and waiting for their response

**Comment by v-atulyadav** [comment]
It is with customer and waiting for their response

**Comment by v-atulyadav** [comment]
It is with customer and waiting for their response

**Comment by v-atulyadav** [comment]
It is with customer and waiting for their response

**Comment by v-amolpatil** [comment]
there is no update from client so closing the PR. Will reopen when we hear back from client.

**Pull request closed without merging**
