### PR TITLE
add content for oci

### PR DESCRIPTION
**Pull request by spsocprime**
## Proposed Changes

Added analytic content for OCI data connector

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @spsocprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by v-sabiraj** [comment]
There should not be 2 templates with the same ID, but the id **a55b4bbe-a014-4ae9-a50d-441ba5e98b65** is duplicated, please update it, thanks.

**Comment by v-sabiraj** [comment]
Please add 'OracleCloudInfrastructureLogsConnector' to the list in [ValidConnectorIds.json](https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json) file, thanks.

**Comment by v-sabiraj** [comment]
An old mapping for entity 'IPCustomEntity' does not have a matching new mapping entry. Please update it. Thankyou.

**Comment by vmanojreddy** [comment]
Workbook query is failing, please look into it.

image

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Took a quick lok. The queries overall look good. 
Please fix the duplicate id : a55b4bbe-a014-4ae9-a50d-441ba5e98b65 issue that @v-sabiraj  raised. That will possibly fix the validation error after which we can approve and merge.

**Comment by vmanojreddy** [comment]
Please resolve conflicts.

**Comment by spsocprime** [comment]
> Workbook query is failing, please look into it.
> 
> image

This is default field name from API ingested events. Please double-check is there are issues related to field names in your environment
image

**Review by aprakash13 — APPROVED** [review]

**Pull request merged**
