### PR TITLE
fixes for azure deploy in the marketplace

### PR DESCRIPTION
**Pull request by edx-sayed-salman**
Required items, please complete
   
   Change(s):
   - update Zip file with the offerid
   - fix issues in the analytic rule 
 

   Reason for Change(s):
   - Zip files desnet match offer id 
   - anaytic rule have syntex error 

   Version Updated:
   - None

   Testing Completed:
   - None

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by edx-sayed-salman** [comment]
Hi @v-atulyadav i have change files as requested

**Comment by edx-sayed-salman** [comment]
@v-atulyadav, Hi , any update

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-atulyadav** [comment]
Hello @edx-sayed-salman,

It seems that the version has not been incremented for the modified analytical rule. I tried to push this change to your branch, but I don’t have access. Please replace your solution folder files with the below attached files. Also increment analytical rule version with 1.0.1.
1. 3.0.0 zip: update Maintemplate included in this
2. Maintemplate : I have modified this file to match with incremented version of rule.
[mainTemplate.zip](https://github.com/Azure/Azure-Sentinel/files/13899524/mainTemplate.zip)
[3.0.0.zip](https://github.com/Azure/Azure-Sentinel/files/13899525/3.0.0.zip)

**Comment by v-atulyadav** [comment]
Hi @edx-sayed-salman,
Increase version in below file also.
image

Version should be 1.0.1 instead of 1.0.0
image

**Comment by edx-sayed-salman** [comment]
Hi , @v-atulyadav i have change the files as requested , please have a look

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
