### PR TITLE
Add Tanium "Sentinel Realtime" integration

### PR DESCRIPTION
**Pull request by sdball**
Required items, please complete
   
   Change(s):
   - Adds the "Sentinel Realtime" integration with Tanium to this existing Microsoft Sentinel solution

   Reason for Change(s):
   - New feature

   Version Updated:
   - Yes, this build uses the new v3 build script which generates a 3.0.0 version

   Testing Completed:
   - Yes, this template has been installed and tested in an Azure resource group with Log Analytics, Sentinel, an integration account, and access to a Tanium environment

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @sdball, Thanks for raising this PR. This PR will be investigated and will update you about the same before 01 November, 2023.

**Comment by v-prasadboke** [comment]
Hello there, @sdball . It appears that the solution has not been properly packed. Please repackage the solution once more. 
Also, I'm not sure what this new Sentine Realtime feature is all about. Can we have a call as per your convenience to discuss this? I work in IST time zone. Please do share your mail id to share the meet link.
Mines: v-prasadboke@microsoft.com You can ping me on teams.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @sdball Please respond to the above comment.

**Comment by sdball** [comment]
@v-prasadboke Sorry! I no longer work at Tanium. But I'll ping the team.

**Comment by v-prasadboke** [comment]
Hi there, @sdball I'm grateful for this. Thank you so much.

**Comment by v-prasadboke** [comment]
Hello @sdball, Did you get a chance to connect with someone from Tanium?

**Comment by sdball** [comment]
@v-prasadboke Yes I got in contact, I can ping again.

**Comment by v-prasadboke** [comment]
Thanks for the reply @sdball. I'm very grateful.

**Comment by v-prasadboke** [comment]
Thanks @ajcollins0 for the updates.

**Comment by sdball** [comment]
Closing this for now, Tanium engineering will reopen when ready.

**Pull request closed without merging**
