### PR TITLE
Adding new NRT Rule for 2FA disable inn github

### PR DESCRIPTION
**Pull request by samikroy**
Adding new NRT Rule for 2FA disable inn github

### CODE REVIEW

**Comment by samikroy** [comment]
@aprakash13 - Could you please have a look here.

**Comment by samikroy** [comment]
@aprakash13 - Request your help for approval & merge.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please Review and provide your approval.

**Review by aprakash13 — APPROVED** [review]
Thanks @samikroy

**Comment by samikroy** [comment]
@aprakash13 - Thank you for the approval & merge.

**Pull request merged**
