### PR TITLE
Darktrace 2.0.1

### PR DESCRIPTION
**Pull request by JustasZDT**
Changes included in this PR:

- Darktrace branding language has been updated to reflect our new product categories
- Graphs within the workbook have been adjusted to better format the data
- Analytic rules have been modified to be NRT instead of running once every 5 minutes

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @aprakash13, can you please verify the changes in Analytic rules, thanks.

**Comment by v-sabiraj** [comment]
Hey @aprakash13, there are few changes, can you please check them , thanks.

**Comment by v-sabiraj** [comment]
@aprakash13 / @shainw, can you please check on the changes, thanks.

**Review by petebryan — APPROVED** [review]

**Comment by JustasZDT** [comment]
@v-sabiraj could you package and push up updated ZIP?

**Comment by v-sabiraj** [comment]
Hey @JustasZDT, there is issue while creating the [CreateAlertFromSystemStatus.yaml](https://github.com/Azure/Azure-Sentinel/pull/6578/files#diff-1cc3c97bbe82368f1b9a95e34796647b9554c17a83bb42d9618fea673261861e) rule, please refer the below image for details, thanks.
image

**Comment by seanmacdonald8** [comment]
Hi @v-sabiraj we will be switching from NRT back to the 5 minute interval. It appears that the issue with this is that the string "System Alert" is not being accepted and throwing this error: NRT queries cannot use joins or query more than one table. Not sure why "System Alert" isn't a valid string as I don't see any documentation saying we can't use that. Changing the string to "System Alerts" for instance will fix the issue. However, that is not something we are able to change at the moment.

**Pull request merged**
