### PR TITLE
Sentinel Costs Insights

### PR DESCRIPTION
**Pull request by Y4HYA4**
Visibility into your sentinel costs.

   Required items, please complete
   
   Change(s):
   -  workbook for more insights into the costs of sentinel environment, you should check it out. This workbook will help you understand the cost factors involved in setting up and maintaining a sentinel environment.

   Reason for Change(s):
   - The reason is simple: I couldn't find a template like this in your repository and i believe that could help someone else. By creating this template, it will be easier for others to find and use, saving them time in the long run.

   Testing Completed:
   - Yes,  I successfully tested it on my work environment/ Need Help

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by Y4HYA4** [comment]
@microsoft-github-policy-service agree [company="{Next Generation Cybersecurity Consulting Canada}"]

**Comment by Y4HYA4** [comment]
@microsoft-github-policy-service agree

**Comment by Y4HYA4** [comment]
@microsoft-github-policy-service agree

**Comment by Y4HYA4** [comment]
@microsoft-github-policy-service agree company="NEXT GENERATION CYBERSECURITY CONSULTING CANADA"

**Comment by Y4HYA4** [comment]
Help, please?

**Comment by v-sabiraj** [comment]
@Y4HYA4, please add Metadata for Workbook in [WorkbooksMetadata.json](https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Workbooks/WorkbooksMetadata.json)

**Comment by v-sabiraj** [comment]
@Y4HYA4, can you please resolve the comments provided, thanks.

**Comment by Y4HYA4** [comment]
Hello @v-sabiraj ,

I included as required; however i do not have any pictures with png attached.

Please confirm. thanks

**Comment by Y4HYA4** [comment]
I created another custom dashboards that i want to contribute as well.

**Comment by v-sabiraj** [comment]
Hey @Y4HYA4, the value for "fromTemplateId" should not be "sentinel-UserWorkbook", please add a meaningful id. e.g. "sentinel-SentinelCosts", thanks.

**Comment by v-sabiraj** [comment]
@Y4HYA4, if the images are not added please keep the "previewImagesFileNames" blanks, thanks.

**Comment by Y4HYA4** [comment]
Waiting! 
Let's be done with that, this weekend!

**Comment by v-sabiraj** [comment]
Hey @Y4HYA4, there are conflicts in this branch can you please resolve them, thanks.

**Comment by Y4HYA4** [comment]
Hello. Current pull request closed. 

Please consider my new pull request.


Regards,
Yahya

**Pull request closed without merging**
