### PR TITLE
analytic rules for Tenable.ad

### PR DESCRIPTION
**Pull request by fr4nco1s**
## Proposed Changes

  - analytic rules for Tenable.ad

### CODE REVIEW

**Comment by v-jayakal** [comment]
@aprakash13 - Can you please review analytics, Thanks.

**Comment by NikTripathi** [comment]
@aprakash13 Please review analytical rules.

**Comment by v-sabiraj** [comment]
@aprakash13 Please review analytical rules,thanks.

**Comment by NikTripathi** [comment]
@aprakash13 please review analytic rules.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
++ It seems we are using a parser instead of a table name.  We need to be clear about this in the description. The parser must be imported first into the workspace, otherwise these queries will not run as a valid query.  So, some direction about that would be helpful. Please include that in the Query as comments.

++ entityMappings are missing from the queries. Please add it to all the queries.

Also, for future, if we have multiple simple detections, with a single condition say:
| where Codename = "password guessing"
we can explore the use of a single custom alert that changes the alert name and description based on the content of the query.

**Comment by v-sabiraj** [comment]
@fr4nco1s ,please updated the requested changes, thanks.

**Comment by v-sabiraj** [comment]
@aprakash13 ,please review and approve the changes. Thanks.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Looking at the parser it seems we have IP details and Host name in the alerts. Wondering if there is a scope for their inclusion in the Entity Mapping which are currently Null.
image

One other suggestion **for future** would be  that for detections that have just a single condition, such as | where Codename == "Password Guessing" that you move these all into a single custom alert that changes the alert name and description based on the content of the query - [https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#alertdetailsoverride](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fwiki%2FQuery-Style-Guide%23alertdetailsoverride&data=04%7C01%7Caprakash%40microsoft.com%7Cc3ca25f17a2440f3b6f408d9cedcdf17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637768270317466622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NvHu6tKpCmQmRv8v6JmuoKKunHA21T91eplc4%2BXzqoQ%3D&reserved=0)

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s , please update the requested changes, thanks.

**Comment by vmanojreddy** [comment]
Hey @fr4nco1s , please update the requested changes, thanks.

**Comment by fr4nco1s** [comment]
I am unable to checkout the branch. And it does not appear when I am listing... any idea ?

Screenshot from 2022-03-28 10-28-05

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s, Use "**git branch -a**" to see all branches in repository in which the branch is there and then you can use "**git checkout branchname**" to checkout to respective branch

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s, please sign license/cla, thanks.

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s , can you please check the steps provided and update the PR with changes, thanks.

**Comment by vmanojreddy** [comment]
Hey @fr4nco1s , can you please check the steps provided and update the PR with changes, thanks.

**Comment by fr4nco1s** [comment]
> **git branch -a**"

Hi @v-sabiraj , my branch does not appear in the list when I execute this command.

**Comment by v-sabiraj** [comment]
> > **git branch -a**"
> 
> Hi @v-sabiraj , my branch does not appear in the list when I execute this command.

Hey @fr4nco1s, Please check the repository, maybe you have published this branch in the forked repository, will you please check the repository in which you are trying to execute this command. Thanks.

**Comment by fr4nco1s** [comment]
> > > **git branch -a**"
> > 
> > 
> > Hi @v-sabiraj , my branch does not appear in the list when I execute this command.
> 
> Hey @fr4nco1s, Please check the repository, maybe you have published this branch in the forked repository, will you please check the repository in which you are trying to execute this command. Thanks.

my bad.. indeed it was a forked, I switched on the branch successfully

**Review by aprakash13 — APPROVED** [review]
Thanks @fr4nco1s. Approved from a query perspective. Please fix the validation issues before this is merged.

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s, the validations are failing as the spaces got removed, can you please check and add '.'  at the end of every line of description. e.g 'Searches for DCShadow attacks.'

**Comment by v-sabiraj** [comment]
Hey @fr4nco1s, the validations are failing, as the value of description as well as query are coming in line with the fields, so it is taking the values as entity fields, some space is needed at start for values but the spaces between two lines should be avoided, please check and update, thanks.

**Comment by fr4nco1s** [comment]
@v-sabiraj the KqlValidations CI is still failing, but I dont get why. It says my template IDs are not good :
image

**Comment by fr4nco1s** [comment]
@v-sabiraj , it should be good now.

**Review by v-sabiraj — APPROVED** [review]
Validations are now passing, thanks.

**Pull request merged**
