### PR TITLE
/MITREATT&CK/Workbooks/

### PR DESCRIPTION
**Pull request by thbanasi**
The MITRE ATT&CK Cloud Matrix Workbook provides an automated visualization of MITRE ATT&CK principles cross walked to Microsoft security offerings. Threat Modeling isn’t just an annual requirement, and organizations must monitor configurations over time like a muscle. This workbook leverages the full breadth of Microsoft security offerings across Azure, Office 365, Teams, Intune, Windows Virtual Desktop, and many more. This workbook enables SecOps Analysts, Assessors, Security & Compliance Decision Makers, and MSSPs to gain situational awareness for cloud workloads' security posture. The workbook features 45+ technique cards aligned to 11 MITRE ATT&CK Cloud Matrix tactics with selectable GUI buttons for navigation. This workbook is designed to augment staffing through automation, artificial intelligence, machine learning, query/alerting generation, visualizations, tailored recommendations, and respective documentation references.

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by v-rucdu** [comment]
Workbook file should be placed under **Solutions --> <SolutionName> --> Workbooks** path.
Please refer any existing solution [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions)

**Comment by thbanasi** [comment]
Are you able to provide DEV support for rollout of this solution?

**Comment by v-rucdu** [comment]
Please provide atleast 1-1 preview image for white and dark themes each.  File names must have White and Black words.

Please refer Preview images [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Box/Workbooks/Images/Preview) for file path and Naming convention

**Comment by v-rucdu** [comment]
> Workbook file should be placed under **Solutions --> --> Workbooks** path.
> Please refer any existing solution [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions)

Please ignore as this is a community contribution it does not need to be part of solutions folder.

Thanks!!

**Comment by v-rucdu** [comment]
For deploying any workbook its entry needs to be added in [WorkbooksMetadata.json](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json).
Please refer [instructions](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/README.md) to understand more on how to add a new workbook.

**Review by v-rucdu — CHANGES_REQUESTED** [review]
1. For deploying any workbook its entry needs to be added in [WorkbooksMetadata.json](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json).
Please refer [instructions](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/README.md) to understand more on how to add a new workbook.

2. Please provide atleast 2 preview images one for white theme and other for black theme.

**Pull request closed without merging**
