### PR TITLE
V rbajaj/n xlogs dns

### PR DESCRIPTION
**Pull request by v-rbajaj**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by jszigetvari-nxlog** [comment]
@v-rbajaj Unfortunately, as my understanding goes @devikamehra asked me (us) to remove the parser from this solution, because an ASIM parser does not belong to a solution. She asked me to move the changes I deem necessary to the ASIM parser, which I created a PR for: #8516

I believe the parser and the parser's supporting files should be stripped from this solution.
Also, I think the data connector should fall back to use the ASIM parser as a fallback, after the parser is removed.

**Comment by v-rbajaj** [comment]
> @v-rbajaj Unfortunately, as my understanding goes @devikamehra asked me (us) to remove the parser from this solution, because an ASIM parser does not belong to a solution. She asked me to move the changes I deem necessary to the ASIM parser, which I created a PR for: #8516
> 
> I believe the parser and the parser's supporting files should be stripped from this solution. Also, I think the data connector should fall back to use the ASIM parser as a fallback, after the parser is removed.

Hi @jszigetvari-nxlog, the ASim which was in solution folder we are converting it as a normal parser and which will stay in this solution folder. We don't need to remove the parser completely. 

The ASim parser which is present in `Parsers/ASimDns/Parsers/` will stay in there.

I hope this clarifies your question.

**Comment by jszigetvari-nxlog** [comment]
> Hi @jszigetvari-nxlog, the ASim which was in solution folder we are converting it as a normal parser and which will stay in this solution folder. We don't need to remove the parser completely.
> 
> The ASim parser which is present in `Parsers/ASimDns/Parsers/` will stay there.

The goal of the parser that was/is in the solution was the very same as the (now) official ASIM NXLog DNS parser. In fact it likely served as a model for the official parser. Now that there is an official one, IMHO there is no point in maintaining two  different versions of parsers that serve the same purpose.

**Comment by v-rbajaj** [comment]
Hi @jszigetvari-nxlog, we understand your concern, we will discuss this internally with the team and will get back to you.

**Comment by v-rbajaj** [comment]
> > Hi @jszigetvari-nxlog, the ASim which was in solution folder we are converting it as a normal parser and which will stay in this solution folder. We don't need to remove the parser completely.
> > The ASim parser which is present in `Parsers/ASimDns/Parsers/` will stay there.
> 
> @v-rbajaj The goal of the parser that was/is in the solution was the very same as the (now) official ASIM NXLog DNS parser. In fact it likely served as a model for the official parser. Now that there is an official one, IMHO there is no point in maintaining two different versions of parsers that serve the same purpose.

Hi @jszigetvari-nxlog, we are discussing internally on this and will soon update you.

**Comment by v-rbajaj** [comment]
Hi @jszigetvari-nxlog, we are closing this PR and will raise a new PR with required changes in the solution and will update you by 31st Jul 2023

**Comment by jszigetvari-nxlog** [comment]
Thank you @v-rbajaj!

**Pull request closed without merging**
