### PR TITLE
Repackaging  for Handled Event Breaking in AzureFunction

### PR DESCRIPTION
**Pull request by v-rusraut**
Required items, please complete
   
   Change(s):

   -Updated Cloudflare/Data Connectors/AzureFunctionCloudflare/main.py.
   - This PR Open becasue we closed PR : https://github.com/Azure/Azure-Sentinel/pull/8627

   Reason for Change(s):
   -To handle unsupported characters

   Version Updated:
   - 3.0.1

   Testing Completed:
   -Yes

### CODE REVIEW

**Comment by pranav-sacumen** [comment]
Hi @v-rusraut Is there anything pending in this PR or we can start publishing process?

**Comment by v-atulyadav** [comment]
Hi @pranav-sacumen,  Once we have checked a few things, we will merge this PR, and you will begin publishing. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-atulyadav** [comment]
Hi @pranav-sacumen, 
We have merged this PR please carry on with publishing.
Thanks

**Pull request merged**
