### PR TITLE
Google Directory API Playbooks

### PR DESCRIPTION
**Pull request by vu-socprime**
Changes:
   - added custom logic apps API connector for Google Directory API 
   - added Google-EnrichIncidentWithUserInfo playbook
   - added Google-SignOutUser playbook
   - added Google-SuspendUser playbook

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @vu-socprime - Can you please make following changes. Thanks in advance

1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example 
```
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
```
3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)
6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specidied identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken)

**Comment by vu-socprime** [comment]
> Hi @vu-socprime - Can you please make following changes. Thanks in advance
> 
> 1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
> 2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example
> 
> ```
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
> ```
> 
>  3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
> 4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
> 5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)
> 6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specidied identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken)

Hi @anki-narravula 
I updated playbooks according to all points that you mentioned. But regarding to point 4 - after adding ManagedIdentity option I started to get the following error during deployment:
```
{
      "code": "WorkflowManagedIdentityConfigurationInvalid",
      "message": "The workflow connection parameter 'azuresentinel' is not valid. The API connection 'azuresentinel' is not configured to support managed identity."
}
```

**Comment by anki-narravula** [comment]
> > Hi @vu-socprime - Can you please make following changes. Thanks in advance
> > 
> > 1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
> > 2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example
> > 
> > ```
> >  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
> >  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
> > 4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
> > 5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)
> > 6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specidied identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken)
> 
> Hi @anki-narravula I updated playbooks according to all points that you mentioned. But regarding to point 4 - after adding ManagedIdentity option I started to get the following error during deployment:
> 
> ```
> {
>       "code": "WorkflowManagedIdentityConfigurationInvalid",
>       "message": "The workflow connection parameter 'azuresentinel' is not valid. The API connection 'azuresentinel' is not configured to support managed identity."
> }
> ```

hi @vu-socprime - you need to add system identity for workflow resource as well

**Comment by vu-socprime** [comment]
> > > Hi @vu-socprime - Can you please make following changes. Thanks in advance
> > > 
> > > 1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
> > > 2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example
> > > 
> > > ```
> > >  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
> > >  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. In CustomConnector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest to make host url also as parameter
> > > 4. Wherever sentinel connection used, use ManagedIdentity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
> > > 5. Please consider limited actions for Custom connector actions (whatever relavant or closer to SOAR perspective). Also please describe in readme (if it is missing)
> > > 6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specidied identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken)
> > 
> > 
> > Hi @anki-narravula I updated playbooks according to all points that you mentioned. But regarding to point 4 - after adding ManagedIdentity option I started to get the following error during deployment:
> > ```
> > {
> >       "code": "WorkflowManagedIdentityConfigurationInvalid",
> >       "message": "The workflow connection parameter 'azuresentinel' is not valid. The API connection 'azuresentinel' is not configured to support managed identity."
> > }
> > ```
> 
> hi @vu-socprime - you need to add system identity for workflow resource as well

@anki-narravula, system identity was added. Thanks!

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @vu-socprime , For while authenticating custom API, we supposed to challenge with client id and secret to enter, but no option to enter please check this 

image


image

**Comment by vu-socprime** [comment]
> Hi @vu-socprime , For while authenticating custom API, we supposed to challenge with client id and secret to enter, but no option to enter please check this
> 
> image
> 
> image

Hi @anki-narravula - client id and client secret are configured in the connector (not the connection). Check docs for reference - https://github.com/vu-socprime/Azure-Sentinel/tree/gcp-identity-playbooks/Solutions/GoogleDirectory/Playbooks/GoogleDirectoryAPIConnector#configurations-steps

**Comment by anki-narravula** [comment]
> > Hi @vu-socprime , For while authenticating custom API, we supposed to challenge with client id and secret to enter, but no option to enter please check this
> > image
> > image
> 
> Hi @anki-narravula - client id and client secret are configured in the connector (not the connection). Check docs for reference - https://github.com/vu-socprime/Azure-Sentinel/tree/gcp-identity-playbooks/Solutions/GoogleDirectory/Playbooks/GoogleDirectoryAPIConnector#configurations-steps

Thanks for clarifying @vu-socprime

**Review by anki-narravula — APPROVED** [review]
Approved

**Pull request merged**
