### PR TITLE
Added Forcepoint Security Cloud files

### PR DESCRIPTION
**Pull request by Dlo-Bagari**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by v-jayakal** [comment]
@Dlo-Bagari, This PR also has changes related to Notebooks which will corrupt the system. There is a PR https://github.com/Azure/Azure-Sentinel/pull/1608 that has only Forcepoint changes. Can you please review this PR and give us approval. We will approve and merge this PR https://github.com/Azure/Azure-Sentinel/pull/1608 with clean Forcepoint changes. Please let us know your comments, Thanks.
 @preetikr, @nayef997, @nazang - FYI.

**Comment by Dlo-Bagari** [comment]
> @Dlo-Bagari, This PR also has changes related to Notebooks which will corrupt the system. There is a PR #1608 that has only Forcepoint changes. Can you please review this PR and give us approval. We will approve and merge this PR #1608 with clean Forcepoint changes. Please let us know your comments, Thanks.
> @preetikr, @nayef997, @nazang - FYI.

**Comment by Dlo-Bagari** [comment]
> > @Dlo-Bagari, This PR also has changes related to Notebooks which will corrupt the system. There is a PR #1608 that has only Forcepoint changes. Can you please review this PR and give us approval. We will approve and merge this PR #1608 with clean Forcepoint changes. Please let us know your comments, Thanks.
> > @preetikr, @nayef997, @nazang - FYI.

@v-jayakal the  Notebooks file in not included in this PR, can you please point to the changes related to Notebooks.

**Comment by v-jayakal** [comment]
@Dlo-Bagari , Thanks for closing the PR, I have assigned the PR #1608 to you for review.

**Comment by v-jayakal** [comment]
> > > @Dlo-Bagari, This PR also has changes related to Notebooks which will corrupt the system. There is a PR #1608 that has only Forcepoint changes. Can you please review this PR and give us approval. We will approve and merge this PR #1608 with clean Forcepoint changes. Please let us know your comments, Thanks.
> > > @preetikr, @nayef997, @nazang - FYI.
> 
> @v-jayakal the Notebooks file in not included in this PR, can you please point to the changes related to Notebooks.

THis PR https://github.com/Azure/Azure-Sentinel/pull/1647 has notebook changes. Please find the screenshot.
ForcePointWithNoteBooks

**Pull request closed without merging**
