### PR TITLE
Auth0audit

### PR DESCRIPTION
**Pull request by rsingh134**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - Raising new PR as old 10415 got closed

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @rsingh134 ,
Please check for failure validations and also accept Contributor License Agreement. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Please check for failure validations. Thanks

**Comment by rsingh134** [comment]
> Hi @rsingh134, Please check for failure validations. Thanks

I am not much aware of these errors and also files doesn't seems relevant.

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Please provide me a contributor access to your branch, so I will check for these failures. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Please respond. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
We are waiting for your reply. Thanks

**Comment by rsingh134** [comment]
@v-atulyadav I am not sure, how to add you as contributor. I am having some issues, will ping you on teams to sort this.

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
I will check this. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
As per our discussion please check with branch's original author for contributor access. And also get latest of master and push into your branch. Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Any update on above? Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134,
Any update on contributor access? Thanks

**Comment by v-atulyadav** [comment]
Hi @rsingh134, We wanted to check on the status of PR #10441. PR is pending for more than 60 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by v-atulyadav** [comment]
Since we have not received a response in the last 7 days, we are closing your PR #10441 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 

If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
