### PR TITLE
Create AzDiagSettingsDeleted.yaml

### PR DESCRIPTION
**Pull request by KennethMLdk**
Detection rule for deleted diagnostic settings on Azure resources

   Required items, please complete
   
   Change(s):
   - Created new detection rule for Azure Diagnostic Settings

   Reason for Change(s):
   - New functionality

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by KennethMLdk** [comment]
@aprakash13: I think the problem is a missing id: The given key 'id' was not present in the dictionary. Should I create a GUID for the id key value or is it something you'll assign??

**Comment by v-spadarthi** [comment]
@KennethMLdk : Pkease fix the validation errors.
@aprakash13 : Please review the detections.

**Comment by v-spadarthi** [comment]
@KennethMLdk : Pkease fix the validation errors.
@aprakash13 : Please review the detections.

**Comment by v-spadarthi** [comment]
@KennethMLdk : Pkease fix the validation errors.
@aprakash13 : Please review the detections.

**Review by shainw — APPROVED** [review]

**Pull request merged**
