### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ITSec365**
New Workbook for Sensitive Operations in Azure Activity Logs Review

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@ITSec365 : Please resolve the validation errors
image
After deploying the workbook in our environment, we could see below
image

**Comment by ITSec365** [comment]
Updated filenames with Black and White. Also added those files with new names.

**Comment by v-spadarthi** [comment]
@ITSec365 : Thanks for providing the images.
We could see empty after deploying the workbook, please add at least 4 charts / graphs in the workbook.
image
Please remove the one .json from workbook metadata from below
image

**Comment by ITSec365** [comment]
Updated the template relative path in metadata file.

**Comment by ITSec365** [comment]
Regarding the blank workbook, can you close the workbook and retry again (open workbook from deployment page). Sometimes, it may take few min to load the data.

**Comment by v-spadarthi** [comment]
@ITSec365 : Please address the above comments

**Pull request closed without merging**
