### PR TITLE
Tanium IP Address Schema Fix

### PR DESCRIPTION
**Pull request by ajcollins0**
Required items, please complete
   
   Change(s):
   - Resolves an issue where a response from a Tanium Server may break the expected schema. 
   - If Tanium has no data for the requested host, a comment is added to the incident informing the user. 

   Reason for Change(s):
   - Applying Fix 
   - New Feature

   Version Updated:
   - Yes, this build uses the new v3 build script which generates a 3.0.0 version

   Testing Completed:
   - Yes, this template has been installed and tested in an Azure resource group with Log Analytics, Sentinel, an integration account, and access to a Tanium environment

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Thanks for raising this PR. We will investigate this PR and will come back to you with an update.

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Can you prove me write access to your Branch. Need to commit some required changes.

**Comment by ajcollins0** [comment]
Hey @v-prasadboke I cannot do that due to our security policies. Can you fork our fork at https://github.com/tanium/Azure-Sentinel, then pull the [tanium-LogicAppIPAddressFix](https://github.com/tanium/Azure-Sentinel/tree/tanium-LogicAppIPAddressFix) branch to your local repo then check out a new branch and PR against our fork? This will allow you to commit changes without us providing access to a repo in our public corporate organization.

As for the images, they are unchanged as this PR does not edit what the desired output looks like. The only output that is changed has been updated in the most recent commit

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Take the latest the from master and repackage the solution again. The latest V3 tool has some updates.

**Comment by ajcollins0** [comment]
hey @v-prasadboke I have rebased this branch against the latest master branch and rebuilt the solution. Let me know if there is anything else you'd like to see sir.

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Thanks for this. will check it once and update you before 20 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, due to lack of availability it was not possible for me to touch this PR.
I'll investigate this PR and get back to you by 22 December, 2023.

**Comment by ajcollins0** [comment]
> Hello @ajcollins0, due to lack of availability it was not possible for me to touch this PR. I'll investigate this PR and get back to you by 22 December, 2023.

roger that - thank you @v-prasadboke

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Can you provide me write access to your branch. I'm unable to pull and push the latest commits.

**Comment by ajcollins0** [comment]
> Hey @v-prasadboke I cannot do that due to our security policies. Can you fork our fork at https://github.com/tanium/Azure-Sentinel, then pull the [tanium-LogicAppIPAddressFix](https://github.com/tanium/Azure-Sentinel/tree/tanium-LogicAppIPAddressFix) branch to your local repo then check out a new branch and PR against our fork? This will allow you to commit changes without us providing access to a repo in our public corporate organization.
> 
> As for the images, they are unchanged as this PR does not edit what the desired output looks like. The only output that is changed has been updated in the most recent commit

hey @v-prasadboke please stop asking for this. I'm not going to give you access to a repo on our corporate github. This is not approved for our company and what you're asking for will get me into trouble. You can fork this and send me a PR against my branch. Otherwise just tell me what you would like to have done over email/teams/here and I will make any required changes, otherwise you must send me a PR against my branch. You can do this through a fork.

**Comment by v-prasadboke** [comment]
> > Hey @v-prasadboke I cannot do that due to our security policies. Can you fork our fork at https://github.com/tanium/Azure-Sentinel, then pull the [tanium-LogicAppIPAddressFix](https://github.com/tanium/Azure-Sentinel/tree/tanium-LogicAppIPAddressFix) branch to your local repo then check out a new branch and PR against our fork? This will allow you to commit changes without us providing access to a repo in our public corporate organization.
> > As for the images, they are unchanged as this PR does not edit what the desired output looks like. The only output that is changed has been updated in the most recent commit
> 
> hey @v-prasadboke please stop asking for this. I'm not going to give you access to a repo on our corporate github. This is not approved for our company and what you're asking for will get me into trouble. You can fork this and send me a PR against my branch. Otherwise just tell me what you would like to have done over email/teams/here and I will make any required changes, otherwise you must send me a PR against my branch. You can do this through a fork.

Sorry @ajcollins0 for asking this again but this time I'm unable to pull the latest changes which you have commited to this branch. 
Theres one way where I can pull this changes by force pushing the `latest from master` to your branch but that would mess up your changes. 
image

**Comment by v-prasadboke** [comment]
Hello @ajcollins0 that would work

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, Sorry I wont be available for the call. Can you pull the latest from master and again repackage the solution. The V3 tool has some changes in it. 
Thanks, thats all needed

**Comment by ajcollins0** [comment]
> Hello @ajcollins0, Sorry I wont be available for the call. Can you pull the latest from master and again repackage the solution. The V3 tool has some changes in it. Thanks, thats all needed

This is done sir! Let me know what else you would need. I will send you an email with what I wanted to show you on the meeting.

**Review by v-prasadboke — APPROVED** [review]

**Comment by Tanium-Nicole** [comment]
@v-prasadboke hello! My name is Nicole and I'm working on some updates we have for our integration. I've been trying to figure out why the v3 build isn't incrementing the version and I see that both in the Azure Portal and in the Catalog lookup used in the PowerShell script to check the version is returning version 2.0.1 even though this PR was completed and merged. Can you help me determine what needs to be done to resolve this?

**Comment by v-prasadboke** [comment]
> @v-prasadboke hello! My name is Nicole and I'm working on some updates we have for our integration. I've been trying to figure out why the v3 build isn't incrementing the version and I see that both in the Azure Portal and in the Catalog lookup used in the PowerShell script to check the version is returning version 2.0.1 even though this PR was completed and merged. Can you help me determine what needs to be done to resolve this?

Hello @Tanium-Nicole, Please ping me on teams. : v-prasadboke@microsoft.com
We cannot follow up on merged PR's regularly

**Pull request merged**
