### PR TITLE
SailPoint IdentityNow

### PR DESCRIPTION
**Pull request by prashant-kagwad-sp**
Required items, please complete
   
   Change(s):
   - Fixed Date Parsing Issue for Function App

   Reason for Change(s):
   - Bug Fix (no events were imported)

   Version Updated:
   - NA

   Testing Completed:
   - Need Help

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by prashant-kagwad-sp** [comment]
@vmanojreddy, @ashishsyal, @preetikr - Requesting a review for this PR. Please let me know if you need any information from our end. Thanks!

**Comment by vmanojreddy** [comment]
Tested the data connector by deploying the function app. we see error for function. Please check and update. Thanks.
image

**Comment by prashant-kagwad-sp** [comment]
Can you verify if a valid **Customer Id** was provided during the connector setup?
You can use this for reference:
·      Customer Id - Azure Object Id of your workspace (Workspace Id) to log event data. Navigate to the associated Log Analytics workspace > Agents management > Workspace ID.
·      Shared Key - Primary Key of the Log Analytics workspace to log event data. Navigate to the associated Log Analytics workspace > Agents management > Primary key.

**Comment by prashant-kagwad-sp** [comment]
@vmanojreddy, @ashishsyal, @preetikr - Please let me know if you need additional information on this.

**Comment by vmanojreddy** [comment]
@devikamehra Please review Dashboard(SailPoint_IdentityNow_Dashboard.json). thanks!!!

**Review by devikamehra — CHANGES_REQUESTED** [review]
As of today, we only support workbook for the Solution. The dashboard won't make it to the Solution package. It would be better to leverage workbook at the moment.

**Comment by devikamehra** [comment]
The suggestion is to convert the existing dashboard to Workbook and then add the same to Workbook folder for the final approval.

**Comment by prashant-kagwad-sp** [comment]
@vmanojreddy - We are currently removing the dashboard from this PR (we will create a separate PR for that). Please review and let me know if anything needs to be done from our end. Thanks!

**Review by devikamehra — CHANGES_REQUESTED** [review]
Following changes are required to gain approval for this PR
1. Sample data for this API in the file [SailPointIDN_Events_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Events_CL.json) and [SailPointIDN_Triggers_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Triggers_CL.json)  should be actual REST API results and not dump from the Sentinel Custom Table. This is inline with the uniformity we are trying to create for all the Data Connectors. Also, please ensure no PII data is provided here.
2. Title of the connector should not contain the word "connector" in [SailPoint_IdentityNow_FunctionApp.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Solutions/SailPointIdentityNow/Data%20Connectors/SailPoint_IdentityNow_FunctionApp.json)
Old Value:  "SailPoint IdentityNow Connector"
New Value:  "SailPoint IdentityNow"

**Comment by prashant-kagwad-sp** [comment]
@devikamehra - Thank you for the comments. I have updated [SailPointIDN_Events_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Events_CL.json) and the title in the [SailPoint_IdentityNow_FunctionApp.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Solutions/SailPointIdentityNow/Data%20Connectors/SailPoint_IdentityNow_FunctionApp.json) file. 

For [SailPointIDN_Triggers_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Triggers_CL.json) the data returned by the API can differ based on the trigger type. Do you want all data structures types to be added as a list in that file?

Also it would be great if we can do a full review of the solution so that we can fix it all in a single PR. We have partners & customers waiting for this to be approved ASAP. Thanks!

**Comment by devikamehra** [comment]
@prashant-kagwad-sp Thanks for updating the [SailPointIDN_Events_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Events_CL.json) and [SailPoint_IdentityNow_FunctionApp.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Solutions/SailPointIdentityNow/Data%20Connectors/SailPoint_IdentityNow_FunctionApp.json).
For [SailPointIDN_Triggers_CL.json](https://github.com/sailpoint-tech-partner-eng/Azure-Sentinel/blob/SailPointIdentityNow/Sample%20Data/Custom/SailPointIDN_Triggers_CL.json), try including diverse set of Trigger data as this would give good sense of data structure for testing and analyzing data.

**Comment by prashant-kagwad-sp** [comment]
@devikamehra - Thank you for the insights. The changes are done. Please re-review and let us know if anything was missed.

**Review by devikamehra — APPROVED** [review]

**Comment by devikamehra** [comment]
The changes look good to me now.

**Pull request merged**
