### PR TITLE
Fix incorrect file names associated with rules

### PR DESCRIPTION
**Pull request by ryan-aus**
I believe I have identified 2 rules with incorrect file names. This PR makes no changes to the rules or the file contents, only corrections to the file names.

Please let me know if there are any issues with this PR.   

Required items, please complete
   
   Change(s):
-  Rename ExcessiveNetworkFailuresFromSource.yaml to ExcessiveHTTPFailuresFromSource.yaml
-  Rename ExcessiveHTTPFailuresFromSource.yaml to ExcessiveNetworkFailuresFromSource.yaml

   Reason for Change(s):
   - Current files are incorrectly named with each other's associated name

   Version Updated:
   - No - There are no changes to any file contents, I am unsure if updating the version is appropriate for these changes. Please inform me if you would like the changes to be made, or feel free to update the version.

   Testing Completed:
   - Yes, rules ran without any issues (there is no change to the file contents so the deployed rules are identical to previous version) 

   Checked that the validations are passing and have addressed any issues that are present:
   - Some validations are failing on duplicate names caused by the file name changes. I am unsure how to resolve. Perhaps making both file name changes in one commit could resolve this?

### CODE REVIEW

**Comment by ryan-aus** [comment]
@microsoft-github-policy-service agree company="Department of the Premier and Cabinet"

**Comment by oshezaf** [comment]
@devikamehra : I am fine with the name change, but don't know what's the impact on the rule that is part of your solutoin, so letting you approve.

**Comment by v-rbajaj** [comment]
Hi @ryan-aus, can you please fix the validations?

**Comment by devikamehra** [comment]
@ryan-aus Can you please make the same changes in here as well?

**Comment by ryan-aus** [comment]
> @ryan-aus Can you please make the same changes in here as well? https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimNetworkSession/ExcessiveHTTPFailuresFromSource.yaml

By changing the file names as suggested in my PR the URL in the ASimNetworkSession/ExcessiveHTTPFailuresFromSource.yaml should point to the correct rule so I don't see a need to make the changes here, unless I am misunderstanding something?

**Comment by v-rbajaj** [comment]
Hi @ryan-aus, can you please fix the validations

**Comment by v-atulyadav** [comment]
Hi @ryan-aus, waiting your reply on @devikamehra comments. Thanks

**Comment by v-rbajaj** [comment]
> > @ryan-aus Can you please make the same changes in here as well? https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimNetworkSession/ExcessiveHTTPFailuresFromSource.yaml
> 
> edit: I understand what you are asking now. I'll get onto it :)

Hi @ryan-aus, please provide some update on this PR

**Comment by v-rbajaj** [comment]
Hi @ryan-aus, can you please act upon Devika's comment?

**Comment by v-rbajaj** [comment]
Hi @ryan-aus, kindly provide some update.

**Comment by v-rbajaj** [comment]
Hi @ryan-aus, can you please provide some update?

**Comment by v-atulyadav** [comment]
We wanted to check on the status of PR #7695. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

**Comment by v-atulyadav** [comment]
Since we have not received a response in the last 7 days, we are closing your PR #7695 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 

If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
