### PR TITLE
Remove BlastRadius where improperly used

### PR DESCRIPTION
**Pull request by jannieli**
Required items, please complete
   
   Change(s):
   - Removed usage of BlastRadius from IdentityInfo where it was used incorrectly
   - Fixed new_locations_azuread_signin.yaml - where there was a broken join

   Reason for Change(s):
   - Improper usage of BlastRadius

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by praveenthepro** [comment]
@v-prasadboke , Seeing an error on like "Add Comments" Error: Unhandled error: HttpError: Resource not accessible by integration, seems some integration is failing,

**Comment by v-prasadboke** [comment]
can you describe your issue more

**Comment by v-prasadboke** [comment]
Hello @jannieli and @praveenthepro please can you tell me more about the issue or should I continue with my PR investigation

**Comment by v-atulyadav** [comment]
Hi @jannieli @praveenthepro,
We're waiting for an update on this. Thanks

**Comment by jannieli** [comment]
> Hi @jannieli @praveenthepro, We're waiting for an update on this. Thanks

Hello, I'm getting this error:
Error: Unhandled error: HttpError: Resource not accessible by integration
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"**Hello how are you I am GitHub bot**\\n😀😀\\nI see that you changed templates under the detections/analytic rules folder. Did you remember to update the version of the templates you changed?\\nIf not, and if you want customers to be aware that a new version of this template is available, please update the ``version`` property of the template you changed.\\n"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}

I am not sure what resource this is referring to - not sure if it has something to do with my code. I also changed all versioning as this message mentions. Any idea where this error is coming from?

**Comment by v-prasadboke** [comment]
Its good now, We will investigate the PR and comeback to you by 20 February, 2024

**Comment by v-prasadboke** [comment]
Hello @jannieli, We are still working on the PR. We will get back to you by 23 February, 2024

**Comment by v-prasadboke** [comment]
Hello @jannieli, still working on solution testing. 
Lacking from sample data.

**Review by v-prasadboke — DISMISSED** [review]

**Review by v-prasadboke — DISMISSED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
