### PR TITLE
Update SigninAttemptsByIPviaDisabledAccounts.yaml

### PR DESCRIPTION
**Pull request by vnayak99**
Change(s):
   - Added a SFRatio check to the rule SigninAttemptsByIPviaDisabledAccounts.yaml to stop false positive of re-enabled accounts.

   Reason for Change(s):
   - Re-enabling disabled accounts was causing false positive.
   - Resolves Issue# [https://github.com/Azure/Azure-Sentinel/issues/8409](url)

   Version Updated:
   - Yes
 
   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @vnayak99, Thank you for raising this PR. We will examine this PR and update you before 10 Aug 2023.
Thank you.

**Comment by v-atulyadav** [comment]
Hi @vnayak99, 
1. We have tested the query, but we are getting an error due to the sample data. Can you please provide us with the sample data and put it in the location below?
https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom

image

2. We are also getting a KQL validation error. Can you please resolve it?
image

**Thanks**

**Comment by vnayak99** [comment]
> Hi @vnayak99,
> 
> 1. We have tested the query, but we are getting an error due to the sample data. Can you please provide us with the sample data and put it in the location below?
>    https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom
> 
> image
> 2. We are also getting a KQL validation error. Can you please resolve it?
> 
> image
> **Thanks**

Provided Behavior Analytics Sample Data in PR#8768.

**Comment by v-atulyadav** [comment]
Thanks @vnayak99, we will provide you an update on this by 14 Aug 2023.

**Review by v-atulyadav — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Review by v-atulyadav — DISMISSED** [review]

**Review by Tichandr — DISMISSED** [review]
Approving this since the team has already reviewed the content and approved. looks like they don't access to approved from fork

**Comment by vnayak99** [comment]
Closing this PR due to branch conflicts. Opening up a new PR to merge.

**Pull request closed without merging**
