### PR TITLE
Create releaseNotes.md

### PR DESCRIPTION
**Pull request by lior-tamir**
Required items, please complete
   
   Change(s):
   - Raised version to 1.1

   Reason for Change(s):
   - Reflect the update in playbook templates tab

   Version Updated:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by dicolanl — APPROVED** [review]

**Review by anki-narravula — APPROVED** [review]
Looks good. Approved.

**Comment by vmanojreddy** [comment]
@lior-tamir Please resolve  conflicts. thanks!!!

**Comment by vmanojreddy** [comment]
@lior-tamir Please resolve conflicts. thanks!!!

**Comment by vmanojreddy** [comment]
@lior-tamir Please resolve conflicts. thanks!!!

**Comment by vmanojreddy** [comment]
Hey @lior-tamir, We wanted to check on the status of this PR [Create releaseNotes.md #4172](https://github.com/Azure/Azure-Sentinel/pull/4172). It is pending from more than 60 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by vmanojreddy** [comment]
Hi @lior-tamir  Since we have not received response from last 7 days, we are closing your PR [Create releaseNotes.md #4172](https://github.com/Azure/Azure-Sentinel/pull/4172) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
