### PR TITLE
Changing Sentinel deployment to onboardingStates

### PR DESCRIPTION
**Pull request by javiersoriano**
Removing old solutions method and moving to onboardingStates

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@anki-narravula / rushriva : Could you please review.Thanks!

**Comment by javiersoriano** [comment]
@v-spadarthi @anki-narravula any updates?

**Comment by javiersoriano** [comment]
No, it should be good to go @anki-narravula

**Review by anki-narravula — APPROVED** [review]
Approved

**Pull request merged**
