### PR TITLE
Create SOCMA

### PR DESCRIPTION
**Pull request by rinure-msft**
## Before submitting this PR please ensure that you have read the following sections and then completed the template below:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures, there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

## After the submission has been made, please look at the Validation Checks:

> Check that the validations are passing and address any issues that are present. Let us know if you have tried fixing and need help.

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

## PR Template

-----------------------------------------------------------------------------------------------------------
 **Description for the PR:**
  (Enter the description below)

**Testing Completed:**
  Yes/ No : 

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @rinure-msft , the watchlist is not in correct format, it is missing  with "watchlistdescription" part, please refer [WatchlistTemplate](https://github.com/Azure/Azure-Sentinel/blob/master/Watchlists/Templates/WatchlistTemplate.json) and update accordingly, thanks.

**Comment by rinure-msft** [comment]
It doesn't need the "watchlistdescription" part, that is a parameter and I removed the parameter and hard coded/called the description.

  "parameters": {
      "workspaceName": {
          "type": "string",
          "metadata": {
              "description": "Workspace name for Log Analytics where Sentinel is setup"
          }
      },
        "watchlistdescription": {
            "type": "string",
            "metadata": {
                "description": "Describe what the Watchlist is for."
            }
        }
  },

        "properties": {
            "displayName": "ReferenceTemplate",
            "source": "ReferenceTable.csv",
            "description": "[parameters('watchlistdescription')]",

So you can see it is simply calling the parameter, but I am not using it, so there is no need to call it. Instead, I hardcoded the description. Here is what I used and I know this works because other watchlists are following the same format:

          "properties": {
              "displayName": "SOC Maturity Assessment (CMMI)",
              "source": "SOCMA.csv",
              "description": "The SOC CMMI model was created by evaluating scientific and non-scientific literature to determine characteristics and features of SOCs, such as specific technologies or processes. These characteristics and features were then aggregated into respective domains. Then, a survey was held among SOCs to determine the existence of identified theoretical elements in practical situations. The outcome of that survey, combined with the initial literature review and augmented with literature review on maturity models was used to create the SOC CMMI model.",
              "provider": "Microsoft",
              "isDeleted": false,

Hope this clears this up! Please proceed with the pull request. :)

Rin

**Comment by preetikr** [comment]
@ashishsyal @v-jayakal - Seems @rinure-msft is adding watchlist description to the property. Can you please review this PR and accordingly let know if any additional action is needed? That way this PR can be moved to the next stage. Thanks.

**Comment by rinure-msft** [comment]
@ashishsyal @v-jayakal - Can I get an updated on this Pull Request??? I have several customers who are waiting on this content and I would like to be able to give them an update.

**Comment by elforb** [comment]
Hi @rinure-msft, 
I've reviewed and tested deployment of the watchlist and all appears well.
All that need be done now is to ensure the validation passes on this PR. I'd tried to check the failing build but it has expired and is no longer visible. Try pulling the latest changes from master and updating the PR to rerun the validations.

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
