### PR TITLE
Package Creation for Amazon Web Services -- DO NOT MERGE AS 1P

### PR DESCRIPTION
**Pull request by v-spadarthi**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Amazon Web Services.

See guidance below
Version Updated:
2.0.0

See guidance below
Testing Completed:
The link for test results is 
https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B84307BED-7D8D-42A3-A8F8-815C518513A6%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Amazon%20Web%20Services.docx&action=default&mobileredirect=true&share=IQHtezCEjX2jQqj4gVxRhROmAavOoU_NaKywugYodhwOXSI

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by anki-narravula — APPROVED** [review]
Looks good. Approved.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-spadarthi Please lookinto the validation errors.

**Comment by v-marimanda** [comment]
@v-spadarthi and @v-sabiraj Please lookinto the validation errors.

**Comment by v-marimanda** [comment]
@v-spadarthi and @v-sabiraj Please lookinto the validation errors.

**Comment by v-spadarthi** [comment]
@v-sabiraj Please look into the validation errors.

**Comment by v-marimanda** [comment]
@v-sabiraj Please look into the validation errors.

**Comment by v-marimanda** [comment]
@v-spadarthi and @v-sabiraj Please look into the validation errors.

**Comment by v-marimanda** [comment]
@v-spadarthi and @v-sabiraj Please look into the validation errors.

**Comment by v-marimanda** [comment]
@v-spadarthi and @v-sabiraj Please look into the validation errors.

**Comment by v-marimanda** [comment]
@v-sabiraj  can you please take a look and review the pr provide your sign off thanks!!!

**Comment by v-amolpatil** [comment]
Please check and undo this change if added by mistake

image

**Comment by v-amolpatil** [comment]
Please add `status: Available` in all Analytic Rules as I see it is missing

**Review by v-amolpatil — APPROVED** [review]

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]
Approving as @v-sabiraj has reviewed.

**Pull request merged**
