### PR TITLE
Update data connectors and workbooks

### PR DESCRIPTION
**Pull request by nlepagnez**
Change(s):

Updating Data Connector to correct errors on "LastReceived" values and IsConnected values
Updating the 2 workbooks to include new information and a comparison
Adding 2 new workbooks to analyze OfficeActivityLogs
Adding Parsers to support the new and updated workbooks.
Reason for Change(s):

Bug correction and enhancements
Version Updated:

Workbooks version updated
Dataconnector versions updated
Solution Version updated

### CODE REVIEW

**Comment by nlepagnez** [comment]
hi @v-prasadboke, you can find here the new pull request with the merged conflict.

I added the parsers in the file to skip validation as per our previous discussion.

**Comment by v-atulyadav** [comment]
Hi @nlepagnez,
Due to a lack of availability, we will provide feedback on this by 27th March, 2024. Thanks

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, 
I'm facing an issue with content hub. 
I have custom deployed couple of solutions and facing issue for Content Hub broken page. 
Here I'm facing same with Microsoft Exchange Solutions. 

image

**Comment by nlepagnez** [comment]
Hi @v-prasadboke, @v-atulyadav, It's more than 1 month now that we request the solution update (https://github.com/Azure/Azure-Sentinel/pull/10076) with multiple support cases opened and customers waiting for update.

Please can you give us a deadline as it's now critical ?

**Comment by v-prasadboke** [comment]
Hey Nicolas sorry for the inconvenience. 
We will make sure to provide you an update or get this PR merged by Tomorrow EOD 29 March, 2024.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by nlepagnez** [comment]
Thank you @v-prasadboke , @v-atulyadav. Can you confirm me that the push to the content hub was also done yesterday ?

**Comment by v-prasadboke** [comment]
No Nicolas, 
I'll push it today

**Comment by nlepagnez** [comment]
Great, thank you

**Comment by nlepagnez** [comment]
> No Nicolas, I'll push it today

Hi @v-prasadboke, I don't see any update in our content Hub. Did you have any problem to push the solution ?

**Comment by nlepagnez** [comment]
> > No Nicolas, I'll push it today
> 
> Hi @v-prasadboke, I don't see any update in our content Hub. Did you have any problem to push the solution ?

It's now visible. thank you.

**Pull request merged**
