### PR TITLE
Adding missing parameter

### PR DESCRIPTION
**Pull request by dicolanl**
Required items, please complete
   
   Change(s):
   -Added a missing parameter to solution template

   Reason for Change(s):
   - Missing parameter was causing issue with native data connector.

   Version Updated:
   - 2.0.3

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @dicolanl, please fix the validations.

**Comment by dicolanl** [comment]
@v-rbajaj fixed

**Comment by v-rbajaj** [comment]
Please change the version to 2.0.3 in this file `Solutions\ZeroNetworks\Data\Solution_ZeroNetworks.json` and repackage this solution using this tool https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2

**Review by v-rbajaj — APPROVED** [review]

**Comment by v-rbajaj** [comment]
@dicolanl, please fix the validations.

**Comment by dicolanl** [comment]
@v-rbajaj fixed what I can but ARM TTK is wrong.

```
[+] apiVersions Should Be Recent In Reference Functions (2 ms)                                                      
  apiVersions Should Be Recent                                                                                          
    [-] apiVersions Should Be Recent (100 ms)                                                                           
        The apiVersion 2021-03-01-preview was not found for the resource type: Microsoft.SecurityInsights               
        The apiVersion 2021-03-01-preview was not found for the resource type: Microsoft.SecurityInsights               
        The apiVersion 2021-03-01-preview was not found for the resource type: Microsoft.SecurityInsights               
        Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/savedSearches is 984 
days old Line: 357, Column: 12                                                                                          
        Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                                                                                              
        2021-06-01                                                                                                      
        Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/savedSearches is 984 
days old Line: 373, Column: 12                                                                                          
        Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                                                                                              
        2021-06-01                                                                                                      
        Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/savedSearches is 984 
days old Line: 398, Column: 12                                                                                          
        Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                                                                                              
        2021-06-01                                                                                                      
        Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/savedSearches is 984 
days old Line: 423, Column: 12                                                                                          
        Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                                                                                              
        2021-06-01                                                                                                      
        Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/savedSearches is 984 
days old Line: 448, Column: 12                                                                                          
        Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                                                                                              
        2021-06-01                                                                                                      
        The apiVersion 2021-03-01-preview was not found for the resource type: Microsoft.SecurityInsights               
        The apiVersion 2021-03-01-preview was not found for the resource type: Microsoft.SecurityInsights               
                                        
```
This check is saying saved searches is using on old api, but according to docs
https://learn.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces/savedsearches?pivots=deployment-language-arm-template this is the latest api

**Comment by v-rbajaj** [comment]
@dicolanl, the arm ttk is still failing, please fix it, use the valid API versions 
```
 Valid Api Versions:                                                                                             
        2022-10-01                                                                                                      
        2022-10-01                                                                                                      
        2021-12-01-preview                               
        2021-06-01
```

**Comment by dicolanl** [comment]
@v-rbajaj please see my previous comment.  those are not supported APIs for saved searches.  the latest is what being used in the template.

**Comment by v-prasadboke** [comment]
Hello @dicolanl you can change the  Microsoft.OperationalInsights/workspaces/savedSearches  version 2020-08-01 to 2022-10-01 as  Microsoft.OperationalInsights resource type ' workspace ' supports this version. 
I runned arm ttk after changing the version to 2022-10-01 and it was successful

**Comment by dicolanl** [comment]
@v-rbajaj done

**Review by v-rbajaj — APPROVED** [review]

**Pull request merged**
