### PR TITLE
Solution/threatconnect1

### PR DESCRIPTION
**Pull request by punkrokk**
Required items, please complete
   
   Change(s):
   - First Release ThreatConnect Solution

   Reason for Change(s):
   - First Release

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @punkrokk, Thank you for raising this PR. 
This PR will be investigated and will update you about the same before 18 September, 2023.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @punkrokk, Sorry for the inconvenience but this PR is still under investigation and will update you about the same before 20 September, 2023.`

**Comment by punkrokk** [comment]
@v-prasadboke I have resolved all of your requests.

**Comment by punkrokk** [comment]
regarding the analytic version, that is so we can version it from 1.0.0. That shouldn't matter and works fine and shows up at 1.0.0 on my side.

**Comment by v-prasadboke** [comment]
Thank you for the reply @punkrokk, Please resolve validation errors.

**Comment by v-prasadboke** [comment]
Thank you @punkrokk for resolving branch conflicts.

**Comment by v-prasadboke** [comment]
Hello @punkrokk, reason any reason behind adding a large amount of py packages to grey noise

**Comment by punkrokk** [comment]
Oops. I’ll pull them out.On Sep 29, 2023, at 6:14 AM, v-prasadboke ***@***.***> wrote:﻿
Hello @punkrokk, reason any reason behind adding a large amount of py packages to grey noise

**Comment by punkrokk** [comment]
@v-prasadboke If we are good I'm ready to go.

**Comment by v-prasadboke** [comment]
Hello @punkrokk, I was trying to resolve the image. Modified the code. Some tags were not closed properly and style keyword was missing before fill:url
Which I added but still logo is in B&W.
Please work on the same for correct Logo.

svgviewer-output

**Comment by v-prasadboke** [comment]
Hello @punkrokk can you please provide me write access to the branch so that I can push some changes from my side.

**Comment by v-prasadboke** [comment]
> You should have write access. I'll fix the logo soon been traveling

Sorry but I dont have the access

**Comment by punkrokk** [comment]
@v-prasadboke working on it

**Comment by punkrokk** [comment]
@v-prasadboke graphics fixed

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
