### PR TITLE
Create Theom Solution

### PR DESCRIPTION
**Pull request by theomsoc**
Required items, please complete
   
   Change(s):
   - Adding Solution for Theom
   - Added 1 Data Connector,1 Workbook, 20 Analytics Rules

   Reason for Change(s):
   - New

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@theomsoc :  
Logo is looking good 
image
Workbook is looking good
image
Could you please create a solution package by using V2 tool
Please follow the below URL and do the package creation. Thanks!
[Azure-Sentinel/README.md at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md)

**Comment by theomsoc** [comment]
@v-spadarthi should I use my branch as `input` for Logo and Basepath in input file at https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md#create-input-file

**Comment by theomsoc** [comment]
@v-spadarthi added solution package, please review

**Comment by theomsoc** [comment]
@v-spadarthi thanks for the review. Addressed comments and rebuilt package. Shortcut names and atypical are as expected, to match the wording on our application.

**Comment by v-spadarthi** [comment]
@theomsoc : Data connector is looking fine
image
CreateUI definition 
image
Main Template
image
Arm-ttk also running fine
image

@aprakash13 : Please review the analytics and provide your signoff. Thanks!
Once Analytics rules reviewed by @aprakash13 we are going to approve this PR.

**Review by aprakash13 — CHANGES_REQUESTED** [review]
A few small suggestions from an analytics template perspective:

- Just for the sake of uniformity can we please have the different fields of the template in a particular order. For example requiredDataConnectors should not be in the end. Please have the template modeled to something similar to this: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CiscoDuoSecurity/Analytic%20Rules/CiscoDuoADSyncFailed.yaml

- It seems the solution includes a data connector. Can we please have the data connector details in the requiredDataConnectors section.

- Also, please include the dataTypes field in the template under data connector for the analytics template.

- Please also remove the last blank lines from the template.

**Comment by theomsoc** [comment]
@aprakash13 addressed comments and re-published new package

**Comment by theomsoc** [comment]
@aprakash13 @v-spadarthi could you please review and merge PR soon, as we are waiting on publishing solution.

**Review by aprakash13 — APPROVED** [review]
Please feel free to merge if other content looks good. Thanks.

**Comment by theomsoc** [comment]
Thanks @aprakash13 !! @v-spadarthi please do the needful.

**Comment by v-spadarthi** [comment]
@theomsoc : Please add the solution input file for that create Data folder under Solutions/Theom/ and keep it here.

**Comment by v-spadarthi** [comment]
@theomsoc : Thanks for adding solution input file.
Plz remove the empty properties from solution input file like parsers and playbooks
image
image

**Comment by theomsoc** [comment]
> @theomsoc : Please add the solution input file for that create Data folder under Solutions/Theom/ and keep it here.

@v-spadarthi Added input file, resolved conflicts and removed empty properties. 
If all looks good, please merge PR, thanks!

**Comment by theomsoc** [comment]
@v-spadarthi could you please check and merge PR soon, so we are able to publish today ?

**Comment by v-spadarthi** [comment]
Create UI definition is looking good
image
Arm ttk also running fine
image
image
image
All are looking good

**Review by v-spadarthi — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Comment by v-dvedak** [comment]
Approved and merged since Suresh's has approved the PR

**Pull request merged**
