### PR TITLE
Update Zoom data connector to pass Zoom webhook endpoint validation

### PR DESCRIPTION
**Pull request by aka0**
Required items, please complete
   
   Change(s):
   - Implemented data connector response to Zoom's challenge-response check in run.ps1

   Reason for Change(s):
   - Zoom requires new webhook endpoints created after Oct 23, 2022 to be validated through a challenge-response-check.
   - See: https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint.

   Testing Completed:
   - Yes
   - Passed validation and successfully received events
  
image

   Checked that the validations are passing and have addressed any issues that are present:
   - Resolves ISSUE #9163

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @aka0 Thanks for raising this PR. This PR will be investigated and will update you about the same before 16 October, 2023.

**Comment by aka0** [comment]
Resolved validation error

**Comment by v-prasadboke** [comment]
Hello @aka0, Thank you for resolving the validations. Will take a look at this and will update you about the same before 19 October, 2023.

**Comment by v-prasadboke** [comment]
Hello @aka0, Sorry for the convenience due to some priority task didn't got time to check on this. 
Will investigate this PR and update you about the same before 23 October, 2023.

**Comment by v-prasadboke** [comment]
1. SecretToken should be fetched from parms of function app,please do necessary changes
Armdeply.json

2. Need to add details in Readme how to get the secret and add in function app configuration->Steo

3 .Please add null check secret token.
If its null or empty please ask them to add secret token in azuredeploy,json

4 The Zoom Developer Platform is an open platform that allows third-party developers to build applications and integrations upon Zoom’s video-first unified communications platform.
Pay load parameters null check->Zoom side plain token this should be having null check
if its null log and show app
If its not null then only proceed
8.validationPayload null check should happen and its present proceed

**Comment by aka0** [comment]
Can you clarify on point #4?
```
4 The Zoom Developer Platform is an open platform that allows third-party developers to build applications and integrations upon Zoom’s video-first unified communications platform.
Pay load parameters null check->Zoom side plain token this should be having null check
if its null log and show app
If its not null then only proceed
```

**Comment by v-prasadboke** [comment]
Add a null check to payload parameter.

**Comment by aka0** [comment]
> Add a null check to payload parameter.

That's done.

**Comment by v-prasadboke** [comment]
Hello @aka0, Thank you for committing the requested changes. We will investigate this and will update you about the same before 31 October, 2023.

**Comment by v-prasadboke** [comment]
Hello @aka0, Can you please share the latest working/running images of the function app

**Comment by aka0** [comment]
> Hello @aka0, Can you please share the latest working/running images of the function app

image

**Comment by v-prasadboke** [comment]
Hello @aka0, You have added one enviorment variable zoomsecrettoken  to the Powershell script. May I know where its fetching the secret token from. 

Can we schedule a call for this as per your conveniency. I work in IST time zone. Please do share your email id so we can connect for the same. @v-muuppugund will be in the call too. 
Thanks.

**Comment by aka0** [comment]
> Hello @aka0, You have added one enviorment variable zoomsecrettoken to the Powershell script. May I know where its fetching the secret token from.
> 
> Can we schedule a call for this as per your conveniency. I work in IST time zone. Please do share your email id so we can connect for the same. @v-muuppugund will be in the call too. Thanks.

ZoomSecretToken is a parameter set in azuredeploy.json.

I'll send a teams invite via company account.

**Comment by v-prasadboke** [comment]
Hello Arthur, Received invitation. Thanks.

**Comment by v-prasadboke** [comment]
Hello @aka0, As discussed in the call we will get back to you on 06 November, 2023. 
Thanks.

**Comment by aka0** [comment]
Updated screenshots
Screenshot 2023-11-06 at 8 04 21 PM
Screenshot 2023-11-06 at 8 03 41 PM

**Review by v-muuppugund — APPROVED** [review]
Approving the changes as per discussion tested on call with Arthur

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
