### PR TITLE
Talon solution

### PR DESCRIPTION
**Pull request by aviatam**
Change(s):
   - Created Talon Solution including connector and workbook in the correct path

   Reason for Change(s):
   - Talon and Sentinel Integration

   Testing Completed:
   - Verified Talon_CL data worked correctly and displayed ingested data

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @aviatam, below are a few points to request change.
1. This solution should be repackaged with version 2.0.0 since this is the version we use by default for TemplateSpec solutions.

2. Workbook is as a part of Solution V2 version then metadata should be added in V2 folder e.g...\Tools\Create-Azure-Sentinel-Solution\V2\WorkbookMetadata.
so remove workbook description from data file and add in metadata file
image

3. Also domain category is not as per our standard please refer [domain categories](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/sentinel-solutions.md?msclkid=9a240b52b11411ec99ae6736bd089c4a#microsoft-sentinel-out-of-the-box-content-and-solution-categories) and change in solutionmetada.json file
image

4. Also provide sample data to check data connector queries.

**Comment by aviatam** [comment]
@v-atulyadav made the changes you've requested please review 
thanks

**Comment by aviatam** [comment]
@v-atulyadav I see you've added a TODO-talon-article 
can I change it to https://docs.console.talon-sec.com/en/articles/254-microsoft-sentinel-integration

**Review by v-atulyadav — COMMENTED** [review]
Hi @aviatam, can you please save below images in respective workbooks images folder. Thanks

image


image

**Comment by aviatam** [comment]
@v-atulyadav done

**Comment by v-atulyadav** [comment]
> @v-atulyadav I see you've added a TODO-talon-article can I change it to https://docs.console.talon-sec.com/en/articles/254-microsoft-sentinel-integration?

Hi @aviatam, please go ahead to change. Thanks.

In addition, the sample data in csv format you have attached is not valid. Please refer to the below link for the same.
https://github.com/Azure/Azure-Sentinel/tree/1926771adee64edeb848eac1053f2a84890e77ab/Sample%20Data

**Comment by aviatam** [comment]
@v-atulyadav the file is a valid csv but for some reason, it's not loaded I also added a scheme as requested in the documentation above, if I'm missing something can you please point it out? 
thanks

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
