### PR TITLE
asim normalization support for Vectra Stream

### PR DESCRIPTION
**Pull request by danymello**
Fixes #

 - fix 2 attributes renaming

## Proposed Changes

  - ASIM Network session 
  - ASIM HTTP
  - ASIM DNS

### CODE REVIEW

**Comment by v-rucdu** [comment]
@oshezaf : Can you please take a look at the Parser?... Thanks!!!

**Review by oshezaf — CHANGES_REQUESTED** [review]
To be ASIM compliant, you must:
- Pick a specific schema you normalize to. I think that in your case there are two or three separate ones: DNS, NetworkSession and WebSession . Each event would typically be mapped only to one of those.
- Create a seperate parser for each schema based on your source tables. 
- Address all mandatory fields in the relevant schema, and preferably also recommended fields.

Otherwise, the field names might look like ASIM, but your source will not be able to be part of ASIM and automatically get value from Sentinel analytics and ML.

**Comment by v-jayakal** [comment]
@danymello  - Can you please modify as per @oshezaf's comments? Thanks.

**Comment by vmanojreddy** [comment]
@danymello - Parser is failing. please look into it.
image

**Comment by NikTripathi** [comment]
@danymello Please update,

**Comment by v-sabiraj** [comment]
@danymello ,please update the changes, thanks.

**Comment by v-sabiraj** [comment]
@danymello ,please update the changes, thanks.

**Comment by v-sabiraj** [comment]
@danymello , please update ,thanks.

**Comment by v-rucdu** [comment]
As per email from Eric, Fabien team will be raising a new PR hence closing this... Thanks!!!

**Pull request closed without merging**
