### PR TITLE
Support sovereign clouds and other minor changes

### PR DESCRIPTION
**Pull request by doc352**
Change(s):
   - Updated azuredeploy.json in "O365 Data" connector to calculate StorageSuffix, LogAnalyticsUri, and LoginEndpoint from environment function and collect the O365 Management Activities API URI as a parameter.
   - Updated run.ps1 to remove hardcoded endpoints and consume the environment variables instead
   - Updated azuredeploy.parameters.json to remove a stale parameter "FunctionName"
   - Updated the ZIP to include the changes to run.ps1

   Reason for Change(s):
   - Provides better support for automated deployment to sovereign clouds
   - Resolves ISSUE #8314 

   Version Updated:
   - n/a

   Testing Completed:
   - Need Help

   Checked that the validations are passing and have addressed any issues that are present:
   - n/a

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @doc352, 
Thank you for raising Pull Request with us! We will review the Pull Request and get back to you by 16 Aug 2023.

**Comment by v-prasadboke** [comment]
Hello @doc352, Thank you for raising this PR. This PR will be investigated. You can expect an update till 21 Aug 2023.

**Comment by v-prasadboke** [comment]
Hello there, @doc352. Please update your branch from master.
I can't see the validation error.

**Comment by doc352** [comment]
@v-prasadboke I updated the branch from master and fixed the documentation link that was causing the validation issue.

**Comment by v-prasadboke** [comment]
Hello @doc352, Thanks for updating the branch from master and resolving the validation error. I'll update you before 23 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @doc352, We apologize for the inconvenience. But we are unable to test the data connector owing to technical issues.
We will get back to you soonest before 25 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @doc352, Can you please share the working images of this function app.
Thanks.

**Comment by doc352** [comment]
Hi @v-prasadboke I'm not sure exactly what images you are looking for, so I grabbed a screenshot that shows the history of successful invocations of the TimerTrigger function and the full output details of an invocation that retrieved a record from the Office 365 Management Activity API and uploaded it to the LAW.

image

**Comment by v-prasadboke** [comment]
Hello @doc352, Thanks for sharing the images.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
