### PR TITLE
Update azuredeploy_Cloudflare_API_FunctionApp.json

### PR DESCRIPTION
**Pull request by aaronbeuhring**
Updated template with parameter definitions for newly added properties. This could not be tested as a new deployment is needed to fully test. Please work with Cloudflare Support to verify.

   Required items, please complete
   
   Change(s):
   - Added parameter definitions for MaxRunTime and MaximumStorageBlobSize which were previously added as properties. Updated default and descriptions for SimultaneouslyProcessingFiles

   Reason for Change(s):
   - Could resolve https://github.com/Azure/Azure-Sentinel/issues/9601 Needs to be tested in a new deployment. I am unable to test that in our production environment.

   Version Updated:
   - No

   Testing Completed:
   - Need Help

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @aaronbeuhring 
Thanks for fixing the azure deploy file. Can you also fix the folder structure of the function app zip file. 
You can download the zip from this [link](https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip) for your reference.
Thanks

**Comment by aaronbeuhring** [comment]
> Hi @aaronbeuhring Thanks for fixing the azure deploy file. Can you also fix the folder structure of the function app zip file. You can download the zip from this [link](https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip) for your reference. Thanks

What needs to be fixed in the ZIP? Is that not built automatically from the repo code? When I tested I just replaced main.py with the updated version, hosted the zip on azure storage, and used a SAS ink to point to it in the function app and it worked resolving the issues I had experienced.

**Comment by aaronbeuhring** [comment]
> Hi @aaronbeuhring Thanks for fixing the azure deploy file. Can you also fix the folder structure of the function app zip file. You can download the zip from this [link](https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip) for your reference. Thanks

What needs to be fixed in the ZIP? Is that not built automatically from the repo code? When I tested I just replaced main.py with the updated version, hosted the zip on azure storage, and used a SAS ink to point to it in the function app and it worked resolving the issues I had experienced.

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, there was issue in folder structure of existing zip file. If you check the zip which is in master, it is having a folder inside zip file which is not required, due to that the function is not visible. 
You can take the reference from below zip file in which we have corrected that. 
Corrected Zip link - https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip

Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, Could you please check on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, I hope you are doing well. We are waiting for your response on above comment. It would be great if you check on that. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, Could you please check our comment? Feel free to reach out to us if you have any queries regarding this.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, We are still waiting for your response on above comments. It would be great if you have a look into that. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, We are still waiting for your response. Could you please have a look on above comment. Thanks!

**Review by v-sudkharat — APPROVED** [review]
The Updated changes looks good.

**Review by v-atulyadav — APPROVED** [review]

**Comment by pir8g33k** [comment]
awesome thanks for the update and fixes, will do some testing later today

**Pull request merged**
