### PR TITLE
IP Remediation master playbook update

### PR DESCRIPTION
**Pull request by ospeka**
Change(s):
   - added nested playbook CiscoASA
   - added nested playbook CiscoFirepower
   - added nested playbook CiscoUmbrella
   - added nested playbook F5-BigIP
   - added nested playbook MDE

### CODE REVIEW

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @ospeka  - Please find my feedback below

ForcepointNGFW-BlockIP-Nested-Remediation

- Terms and Condition banner issue - ; replace MICROSOFT.WEB/CONNECTIONS with Microsoft.Web/connections

F5-BlockIP-Nested-Remediation
 - Terms and Condition banner issue -  replace MICROSOFT.WEB/CONNECTIONS with Microsoft.Web/connections
 - Hardcoded values present - "/subscriptions/3102b8f9-10e3-49bf-8712-51c184fddef5/resourceGroups

Master Playbook - Remediation-IP
 - Deployment issue - Parameter CiscoASACiscoASA is invalid. Use valid one (looks like it should be CiscoASAPlaybookName)
 - Terms and Condition banner issue -  replace MICROSOFT.WEB/CONNECTIONS with Microsoft.Web/connections

Master readme.md
- "Playbook steps explained" section need to be updated with new playbooks
- "Input Schema" section need to be updated with new playbooks

**Comment by anki-narravula** [comment]
Hi @ospeka - Looks like below are still not fixed. 

- In readme files, change azure deploy links to point to master branch
- In Playbooks metadata object - support information should be Microsoft supported.

**Comment by ospeka** [comment]
> Master readme.md

> "Playbook steps explained" section need to be updated with new playbooks
> "Input Schema" section need to be updated with new playbooks

Can you clarify what should be added?

**Comment by anki-narravula** [comment]
> > Master readme.md
> 
> > "Playbook steps explained" section need to be updated with new playbooks
> > "Input Schema" section need to be updated with new playbooks
> 
> Can you clarify what should be added?

Hi @ospeka 

- Playbook steps explained - Currently I see the screenshots for old playbooks, but you have added new playbooks "FirePower", "ASA", "F5" and can we add the screenshot for new aswell
- Input schema and output schema - Currently I see only screenshots Cisco Meraki added, can you please add screenshots for new playbooks

**Comment by ospeka** [comment]
> > > Master readme.md
> > 
> > 
> > > "Playbook steps explained" section need to be updated with new playbooks
> > > "Input Schema" section need to be updated with new playbooks
> > 
> > 
> > Can you clarify what should be added?
> 
> Hi @ospeka
> 
> * Playbook steps explained - Currently I see the screenshots for old playbooks, but you have added new playbooks "FirePower", "ASA", "F5" and can we add the screenshot for new aswell
> * Input schema and output schema - Currently I see only screenshots Cisco Meraki added, can you please add screenshots for new playbooks

Unfortunately, I can't make screenshots of comments from playbook because i don't have permission to this products.

**Comment by NikTripathi** [comment]
@anki-narravula Can you please have a look. Thanks

**Comment by v-spadarthi** [comment]
@anki-narravula: Could you please check and provide your signoff. Thanks!!

**Review by anki-narravula — COMMENTED** [review]
Looks good. Approved

**Pull request merged**
