### PR TITLE
Added a new firewall / CGW workbook by Barracuda

### PR DESCRIPTION
**Pull request by FelixBman**
fbueltmann@barracuda.com

   Required items, please complete
   
   Change(s):
   -added a new workbook

   Reason for Change(s):
   - new workbook

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   yes

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @FelixBman, I can see that many irrelevant changes are committed in this PR. Can you please check and close this and raise another PR just with the changes that are needed. Thanks.
image

**Comment by NikTripathi** [comment]
@FelixBman Can you please fix the PR? This PR contains so much of errors.

**Comment by shainw** [comment]
@rushriva - This PR should be closed and a new clean one opened by the contributor.

**Comment by v-atulyadav** [comment]
Hi @FelixBman, we have closed this PR now you can open new PR for the same. Thanks

**Pull request closed without merging**
