### PR TITLE
Updating Azure WAF Solution with the recent Workbook

### PR DESCRIPTION
**Pull request by shabaz-github**
Required items, please complete
   
   Change(s):
   - Added new Workbook AzureWAFMonitorWorkbook.json into the WAF Solution and removed the other old ones which are outdated.

   Reason for Change(s):
   - Updating the solution with most up to date workbook and consolidating other workbooks.

   Version Updated:
   - Not required as this is a workbook file.

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes
  
-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Please share working images of workbook with white and black background. 

Also add workbook metadata at location 
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Please work on the above requested changes

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, we are waiting for your feedback

**Comment by shabaz-github** [comment]
@v-prasadboke Hello Prasad, the workbook Metadata and Images have been added in the requested places. Please help review the PR and help with packaging as usual.

**Comment by v-prasadboke** [comment]
Hello @shabaz-github, Sorry for the delay. I had some priority tasks on my plate. I was trying to go through the validation error but it seems i have lost access to it. If possible can you please share the failures. 

Also try to update the branch from master and resolve branch conflicts.

**Comment by shabaz-github** [comment]
Hello @v-prasadboke I closed this PR as there were conflicts, I will reopen another one

**Comment by shabaz-github** [comment]
Hello Prasad,

I have closed this PR, will submit another one as I was not able to resolve conflicts. Now my branch is updated and will submit another PR.


Thanks,

Shabaz Shaik
Product Manager II
***@***.******@***.***>

Azure Network Security CxE Team

[MSFT_logo]

Learn more about Azure Network Security: AzNetSecNinja<https://aka.ms/AzNetSecNinja> | Blogs<https://aka.ms/aznetsecblog> | GitHub<https://aka.ms/AzNetSec> | Portal<https://aka.ms/AzNetSecSPO> | Private Community<https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR-kibZAPJAVBiU46J6wWF_5URDFSWUhYUldTWjdJNkFMVU1LTEU4VUZHMy4u>

**Comment by v-prasadboke** [comment]
Thanks for the update @shabaz-github

**Pull request closed without merging**
