### PR TITLE
Azure Firewall/DDoS Workbooks

### PR DESCRIPTION
**Pull request by chboeh**
Fixes #

## Proposed Changes

  -Updating Azure Firewall Workbook, New ICON File, Workbook update, New Screenshots
  -Adding Azure DDoS Standard Protection Workbook, New ICON File, New Screenshots
  -

### CODE REVIEW

**Comment by morshabi** [comment]
Hi @chboeh, can you please add the updates to the workbooks metadata file as well?

**Comment by chboeh** [comment]
I've added changes (Edit Only Visible) on the Azure Firewall Workbook.

**Comment by chboeh** [comment]
Updated Metadata file, with the new screen shots and workbooks.

**Comment by chboeh** [comment]
Checking on the status update of this.

**Review by liatlishams — APPROVED** [review]

**Pull request merged**
