### PR TITLE
PaloAlto PAN-OS OnPrem  playbooks and connector versions

### PR DESCRIPTION
**Pull request by ospeka**
Created OnPrem versions of playbooks and connector.
Change(s):

- added BlockIP OnPrem playbook
- added BlockURL OnPrem playbook
- added GetSystemInfo OnPrem playbook
- added GetThreatPCAP OnPrem playbook
- added GetURLCategoryInfoOnPrem playbook
- added PAN-OS Logic Apps OnPrem Custom connector

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@ospeka : Please resolve the conflicts.
image

**Comment by v-spadarthi** [comment]
@ospeka : Please resolve the conflicts.
@manishkumar1991/ @rahul0216 : Please have a look Playbooks and provide your suggestions.

**Comment by v-spadarthi** [comment]
@ospeka : Please resolve the conflicts.
@manishkumar1991/ @rahul0216 : Please have a look Playbooks and provide your suggestions.

**Comment by v-spadarthi** [comment]
@ospeka : Please resolve the conflicts.
@manishkumar1991/ @rahul0216 : Please have a look Playbooks and provide your suggestions.

**Comment by ospeka** [comment]
> 

looks like fork repository have some issues so i have created new PR.
here is a link - https://github.com/Azure/Azure-Sentinel/pull/6561

**Comment by v-mchatla** [comment]
Hi @ospeka,
Can you please close this PR and track the status under #6561.
Thanks

**Comment by v-spadarthi** [comment]
> > 
> 
> looks like fork repository have some issues so i have created new PR. here is a link - #6561

@ospeka : Could you please close this PR you have already raised another PR #6561 for the same

**Pull request closed without merging**
