### PR TITLE
updated package with apiVersion fix

### PR DESCRIPTION
**Pull request by daspiker**
Required items, please complete
   
   Change(s):
   - updated package mainTemplate.json with apiVersion fix.  was fixed in prior PR but did not update package zip file so failed marketplace automations.  updated package version from 2.0.0 to 2.0.1

   Reason for Change(s):
   - arm-ttk fail during marketplace validations for certification

   Version Updated:
   - 2.0.0 updated to 2.0.1

   Testing Completed:
   - re-ran software validation and passed

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @daspiker, please include this file `Solutions\Island\Data\Solution_Island.json` in this PR and in 2.0.1 zip there is a folder _MACOSX, please remove this folder

**Comment by daspiker** [comment]
hey @v-rbajaj not sure what the workflow errors are.  looking at the file changes i don't see anything that would cause these.  let me know if you need me to do anything on my side to kick off the workflow again.

**Comment by v-rbajaj** [comment]
Hi @daspiker, sorry for delay in response, I see you have removed 2.0.0 zip, please discard that change as we do need the older version of the package, thanks!

**Comment by daspiker** [comment]
@v-rbajaj 2.0.0.zip package added back in per your request

**Comment by daspiker** [comment]
@v-rbajaj i re-ran the packaging with createSolutionV2.ps1, fixed the apiVersion issue and successfully tested with Test-AzTemplate.  I also loaded the new Solution_Island.json file i'm using for packaging to the Island/Data/Data folder.

**Review by v-rbajaj — APPROVED** [review]
l

**Pull request merged**
