### PR TITLE
Created NRT Rule on First credential added to SPN

### PR DESCRIPTION
**Pull request by samikroy**
First access credential added to Application or Service Principal where no credential was present

### CODE REVIEW

**Comment by samikroy** [comment]
@aprakash13 - Could you please have a look here.

**Comment by samikroy** [comment]
@aprakash13 - Request yo help on approval & merge.

**Comment by vmanojreddy** [comment]
@aprakash13 Please take a look provide your sign off. thanks!!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please take a look provide your sign off. thanks!!!

**Review by aprakash13 — APPROVED** [review]
Thanks a bunch @samikroy for all your contributions.

**Comment by samikroy** [comment]
Thank you for the approval & merge @aprakash13 .

**Pull request merged**
