### PR TITLE
Update Solution Package for darktrace

### PR DESCRIPTION
**Pull request by v-sabiraj**
test doc - https://microsoftapc.sharepoint.com/:w:/r/teams/EcosystemCATTeam/_layouts/15/doc.aspx?sourcedoc=%7B374a85e4-aa92-43ba-9493-d1f8f9de22b4%7D&action=edit&share=IQHkhUo3kqq6Q5ST0fj53iK0AYZag77BA_JscRgBATd9LfE

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Waiting on confirmation from customer, thanks.

**Comment by v-sabiraj** [comment]
Waiting for customer response, as there is issue with Analytic rule, thanks.

**Comment by v-sabiraj** [comment]
We have got confirmation, will merge once changes are done.

**Review by v-vdixit — APPROVED** [review]
Looks good!

**Pull request merged**
