### PR TITLE
Update ForescoutEvent.yaml

### PR DESCRIPTION
**Pull request by pawelCPS**
I haven't had much success understanding what ```ACTIONidentity``` was supposed to be resolving to and so since Forescout was something that I could identify somewhat easily in the syslog table as the ProcessName I chose to go down this route. Please review and let me know if this doesn't make sense. Appreciate it, thank you!

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by pawelCPS** [comment]
I hope I'm not trying to do anything crazy, appreciate your patience with me everyone!

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
The ProcessName varies from customer to customer, making it difficult to set a ProcessName for a particular entity at this time. We are working on enhancing this parser. So, I am requesting you to close this PR for now. Thanks

**Comment by pawelCPS** [comment]
> Hi @pawelCPS, The ProcessName varies from customer to customer, making it difficult to set a ProcessName for a particular entity at this time. We are working on enhancing this parser. So, I am requesting you to close this PR for now. Thanks

Hi @v-atulyadav, thank you for your quick response. I suspected what I proposed might not be the best way of achieving my goal but the thing is I still don't know what ```ACTIONidentity``` was supposed to be resolving to in terms of capturing that process name. I can only say Forescout was something that I was able to confirm seeing in the syslog table consistently coming from this device, whether there's more process names which regard to this particular log source I can't tell, but was hoping that was the only one. Because of this ```ACTIONidentity``` being an unknown variable to me I suspect the data connector is not picking up the logs from said device. I hope this makes sense.

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
You can comment process name line and try to filter with computer from where they are ingesting data. So that it will pull all the process details coming from forescout. Thanks

**Comment by pawelCPS** [comment]
> Hi @pawelCPS, You can comment process name line and try to filter with computer from where they are ingesting data. So that it will pull all the process details coming from forescout. Thanks

That is fine and perhaps I am missing the point here but my understanding was I could be using the data connector out of the box without the need of adjusting anything on its output. I followed the data connector connection steps as advertised in the help section but I'm not sure if there's anything else that I might be missing because Forescout data connector shows its state as Disconnected with no events on the graph but I've already confirmed there are forescout events in Syslog table. The watchlist I have gone with as suggested on the help page was Sources_by_SourceType and its contents as follows: Forescout and IP address of the log source device that I can see in the logs. That did not help at all. Then I've started looking into the function/parser to evaluate how the events from forescout being picked up from syslog where I found this ACTIONidentity key which I couldn't find explanation for. As soon as it's replaced with Forescout in the process name or as you said Computer is used everything works just fine.
Hence I wanted to do something to fix it for me and the client and came up with this, say, "fix".
I really appreciate your prompt response and help on this, thank you sir!

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
We have modified the parser as per your suggestion or requirement. Please check it once at your end and let me know the result. Thanks
[ForescoutEvent.zip](https://github.com/Azure/Azure-Sentinel/files/14771599/ForescoutEvent.zip)

**Comment by pawelCPS** [comment]
> Hi @pawelCPS, We have modified the parser as per your suggestion or requirement. Please check it once at your end and let me know the result. Thanks [ForescoutEvent.zip](https://github.com/Azure/Azure-Sentinel/files/14771599/ForescoutEvent.zip)
Hi @v-atulyadav, thanks a ton for providing a solution, this is very much appreciated. Excuse my ignorance please, but does that mean this is going to be pushed upstream, so the change should be visible once the data connector receives this update? Or should I follow some extra steps on my end to make it work as expected?

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
We will repackage this solution after receiving your approval, as we need to add a few informational steps to the connector as well. Thanks

**Comment by pawelCPS** [comment]
> Hi @pawelCPS, We will repackage this solution after receiving your approval, as we need to add a few informational steps to the connector as well. Thanks

Hi @v-atulyadav,
Understood, so I went ahead and tested the new parser and I'm happy to report back that it does yield expected results from Syslog table. This looks very promising now. I can provide you with a sanitised sample if you'd like.
Appreciate the effort!

**Comment by v-atulyadav** [comment]
> > Hi @pawelCPS, We will repackage this solution after receiving your approval, as we need to add a few informational steps to the connector as well. Thanks
> 
> Hi @v-atulyadav, Understood, so I went ahead and tested the new parser and I'm happy to report back that it does yield expected results from Syslog table. This looks very promising now. I can provide you with a sanitised sample if you'd like. Appreciate the effort!

Hi @pawelCPS, Thanks for your confirmation we will repackage this solution.

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
Could you please share logs after parser change

> > Hi @pawelCPS, We will repackage this solution after receiving your approval, as we need to add a few informational steps to the connector as well. Thanks
> 
> Hi @v-atulyadav, Understood, so I went ahead and tested the new parser and I'm happy to report back that it does yield expected results from Syslog table. This looks very promising now. I can provide you with a sanitised sample if you'd like. Appreciate the effort!

Please share logs. Thanks

**Comment by pawelCPS** [comment]
> > > Hi @pawelCPS, We will repackage this solution after receiving your approval, as we need to add a few informational steps to the connector as well. Thanks
> > 
> > 
> > Hi @v-atulyadav, Understood, so I went ahead and tested the new parser and I'm happy to report back that it does yield expected results from Syslog table. This looks very promising now. I can provide you with a sanitised sample if you'd like. Appreciate the effort!
> 
> Hi @pawelCPS, Thanks for your confirmation we will repackage this solution. Also you can upload your sample data in below location. https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data

Hi @v-atulyadav,
No problem at all, can do, however when I try to follow the link provided and then attempt to upload it comes back with: "Uploads are disabled. File uploads require push access to this repository."

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
You can share logs on my mail id v-atulyadav@microsoft.com.
Thanks

**Comment by v-atulyadav** [comment]
Thanks @pawelCPS.

**Comment by pawelCPS** [comment]
> Thanks @pawelCPS.

Hi @v-atulyadav,
No problem at all, happy to help. Looking forward to this change making its way to production.

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
We need to discuss a few things with you on this. Can we schedule a call for the same? Please send me your mail ID at v-atulyadav@microsoft.com. I will schedule a call according to our convenience. Thanks

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
Waiting for your response on above. Thanks

**Comment by pawelCPS** [comment]
> Hi @pawelCPS, Waiting for your response on above. Thanks

Hi @v-atulyadav,
I did respond to you via email and shared my business contact with you. Did you not receive it?

**Comment by v-atulyadav** [comment]
Hi @pawelCPS,
What is your timezone? I would like to schedule a call accordingly, as we are operating in IST. Thanks

**Comment by v-atulyadav** [comment]
As per discussion we are good to close this PR.

**Pull request closed without merging**
