### PR TITLE
Fixed typos in readme.md

### PR DESCRIPTION
**Pull request by simonkudla**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @simonkudla, there are more typos can you please fix those 

**Registrtion --> Registration**

image

**powerhshell-->PowerShell**

image

**temporaily-->temporarily**

image

**Appplication-->Application**

image

**Managment--> Management**

image

**Comment by simonkudla** [comment]
> Hey @simonkudla, there are more typos can you please fix those
> 
> **Registrtion --> Registration**
> 
> image
> 
> **powerhshell-->PowerShell**
> 
> image
> 
> **temporaily-->temporarily**
> 
> image
> 
> **Appplication-->Application**
> 
> image
> 
> **Managment--> Management**
> 
> image

**Comment by simonkudla** [comment]
Hey @v-sabiraj, updated as requested :)

**Comment by v-sabiraj** [comment]
Hey @simonkudla, I still see two of the typos are not fixed

**Managment to Management** 

image

**Appplication to Application,** it has 3 p's instead of 2.

image

can you fix this quickly so we can merge this, thanks.

**Comment by simonkudla** [comment]
@v-sabiraj sorry was away for a few days, updated the last 2 typos for you.

**Comment by simonkudla** [comment]
Fixed remaining typos in README.md

**Review by v-sabiraj — APPROVED** [review]

**Pull request merged**
