### PR TITLE
Add XML API Connector, and two playbooks to the demo the API. Playboo…

### PR DESCRIPTION
**Pull request by smisun**
Add XML API Connector, and two playbooks to the demo the API. Playbooks added are Playbook to get threat PCAPs and  Playbook to get system infor of the firewall from Sentinel Alert and create and Update an incident

   Required items, please complete
   
   Change(s):
   - Updated Playbooks/PaloAlto-PAN-OS/PaloAltoCustomConnector/azuredeploy.json
   - Created a new folder for PaloAlto-PAN-OS-GetSystemInfo  under Playbooks/PaloAlto-PAN-OS/Playbooks/
   - Created a new folder for PaloAlto-PAN-OS-GetThreatPCAP under Playbooks/PaloAlto-PAN-OS/Playbooks/

   Reason for Change(s):
   - Added a new Sentinel Connector for PAN-OS XML API

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Review by sreedharande — APPROVED** [review]

**Comment by lior-tamir** [comment]
Hi,

Thanks for this great contribution! :)

Regarding playbook logic: 
Please use the incident trigger and not the alert trigger. The readme file says it will start with incident trigger while the code says alert trigger. When doing so, the action "Alert - Get incident" is not required. 
Also, the description says that "Alert - Get incident" creates an incident while it doesn't (it just looks for an existing incident contains this alert)
In the playbook description it is mentioned to check if the alert is a palo alto alert - are these playbooks meant only for specific anlytic rules? If yes, we should mention it in the prerequistes.


Regarding playbook ARM templates:
The location is hard coded. Please change the location value to: "[resourceGroup().location]"

The Azure Sentinel connector under $connections should include the managed identity object:
                "connectionProperties": {
                  "authentication": {
                    "type": "ManagedServiceIdentity"
                  }
                },

API connection resources are missing from the playbook template?

Could Log Analytics connector recieve resource group from the incidnet trigger, or it must be the playbook parameter?

**Comment by sreedharande** [comment]
@smisun - Did you get a chance to incorporate changes suggested by lior

**Review by sreedharande — CHANGES_REQUESTED** [review]
Please update playbook trigger

**Comment by smisun** [comment]
> @smisun - Did you get a chance to incorporate changes suggested by lior

@sreedharande - Sorry, I haven't had a chance to get to this. I got pulled into an incident and haven't been able to look at anything else. I hope to get to this tomorrow.

**Comment by smisun** [comment]
> Hi,
> 
> Thanks for this great contribution! :)
> 
> Regarding playbook logic: Please use the incident trigger and not the alert trigger. The readme file says it will start with incident trigger while the code says alert trigger. When doing so, the action "Alert - Get incident" is not required. Also, the description says that "Alert - Get incident" creates an incident while it doesn't (it just looks for an existing incident contains this alert) In the playbook description it is mentioned to check if the alert is a palo alto alert - are these playbooks meant only for specific anlytic rules? If yes, we should mention it in the prerequistes.
> 
> Regarding playbook ARM templates: The location is hard coded. Please change the location value to: "[resourceGroup().location]"
> 
> The Azure Sentinel connector under $connections should include the managed identity object: "connectionProperties": { "authentication": { "type": "ManagedServiceIdentity" } },
> 
> API connection resources are missing from the playbook template?
> 
> Could Log Analytics connector recieve resource group from the incidnet trigger, or it must be the playbook parameter?

Thanks for the review, Lior!
I've changed the incident trigger, and removed the action "Alert - Get incident". Thanks for clearing up my confusion about what the action "Alert - Get incident" does :). I've added the prerequisite to indicate that this works only for Palo Alto incidents.

I've removed the hard coded location from the Playbooks.

I've the added the "ManagedServiceIdentity" authentication type for Sentinel connector

I've added the API connection resources to the playbook templated

In our team, we have a practice of separating the Log Analytics resource group, so it's easier to just get the name from the playbook parameter.

**Comment by smisun** [comment]
> > @smisun - Did you get a chance to incorporate changes suggested by lior
> 
> @sreedharande - Sorry, I haven't had a chance to get to this. I got pulled into an incident and haven't been able to look at anything else. I hope to get to this tomorrow.

@sreedharande - I've incorporated Lior's suggestions and updated things

**Comment by smisun** [comment]
> Please update playbook trigger

Done

**Review by sreedharande — APPROVED** [review]

**Pull request merged**
