### PR TITLE
remove optional parameters

### PR DESCRIPTION
**Pull request by davidobrien1985**
Required items, please complete
   
   Change(s):
   - removing optional parameters that broke arm-ttk

   Reason for Change(s):
   - broke arm-ttk when packaging

   Version Updated:
   - 1.0.2

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@davidobrien1985 :  Could you please provide the sample data to test the queries and address the below comments.

1.May i know why you kept [Connector_ARGOS.json] file under Solution folder and individual folder (Dataconnector) as well, If not required both the places you can remove from Individual folder and Keep Solution folder itself.
2. While deploying Main Template we are getting an error please fix
image
3.The Analytic rule templates in GitHub follows a specific format. Here is a link to an example: https://github.com/Azure/Azure-Sentinel/blob/ae40b7e77fd406a5ea0297a7916c564eed2fc3c4/Detections/AWSGuardDuty/AWS_GuardDuty_template.yaml
Can we please have the query modified to the suggested format.

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the analytic rules. Thanks!

**Comment by v-spadarthi** [comment]
Main template looks good
image
Please provide the solution Input file for your reference(https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution) and keep it in under Data folder.
Please rectify CreateUI Definition 
image

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the analytic rules. Thanks!

**Comment by v-spadarthi** [comment]
@davidobrien1985 :  Could you please address the above comments.

**Comment by NikTripathi** [comment]
@davidobrien1985 Is there any update?
Thanks

**Comment by davidobrien1985** [comment]
Sorry, I was travelling to Europe and I'm back online again.
Will action this before the end of the week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by shainw — COMMENTED** [review]
There is no real change to the query, just parameters.  So approved from the AnalyticRules perspective.

**Comment by davidobrien1985** [comment]
@v-spadarthi updated the UI config.
I'm unable to provide you with the input file, as I don't have access to it for the next 5.5 weeks. I never committed that file to the repo and it's locally on a machine I won't have access to while traveling.
Is this a blocker?

**Comment by davidobrien1985** [comment]
@v-spadarthi @shainw is this really a blocker here?

**Comment by v-spadarthi** [comment]
@davidobrien1985 : it is not a blocker, but we need to re-package the version 2.0.0.

**Review by v-spadarthi — APPROVED** [review]

**Pull request merged**
