### PR TITLE
PRv2: Advanced Sentinel Costs, custom queries

### PR DESCRIPTION
**Pull request by Y4HYA4**
Visibility into your sentinel costs.

Required items, please complete

Change(s):

workbook for more insights into the costs of sentinel environment, you should check it out. This workbook will help you understand the cost factors involved in setting up and maintaining a sentinel environment.
Reason for Change(s):

The reason is simple: I couldn't find a template like this in your repository and i believe that could help someone else. By creating this template, it will be easier for others to find and use, saving them time in the long run.
Testing Completed:

Yes, I successfully tested it on my work environment/ Need Help
Checked that the validations are passing and have addressed any issues that are present:

Need Help

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@Y4HYA4 : Please resolve the validation errors
Please remove this property from below 
image
In workbook metadata already added  please see the below which one is correct please correct it
image
image
If you have any preview images, please add 
below workbook is looking good
image

**Comment by Y4HYA4** [comment]
Got i

**Comment by Y4HYA4** [comment]
The current PR has concluded. Please test the new; everything should be fine now.

**Comment by Y4HYA4** [comment]
Hey @v-spadarthi , I did what was asked of me. It should now work!

Thanks for the documentation!

**Comment by Y4HYA4** [comment]
Lgtm now

**Review by v-spadarthi — APPROVED** [review]

**Comment by Y4HYA4** [comment]
Indeed!

**Comment by Y4HYA4** [comment]
Thank you; it was a pleasure interacting with you!

**Review by v-dvedak — APPROVED** [review]

**Comment by Y4HYA4** [comment]
Amazing!!!!!

**Comment by Y4HYA4** [comment]
Amazing.

**Comment by yaya2devops** [comment]
For the history!

**Pull request merged**
