### PR TITLE
Microsoft Defender for Cloud Apps TemplateSpec Solution-- DO NOT MERGE AS 1P

### PR DESCRIPTION
**Pull request by v-atulyadav**
Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution Microsoft Defender for Cloud Apps.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B69984E87-EE96-485E-B47C-0638B2589563%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20Microsoft%20Defender%20for%20Cloud%20Apps.docx&action=default&mobileredirect=true&share=IQGHTphplu5eSLR8BjiyWJVjAX2QVm6r9px6ahcT8Fop-iA

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by mkchiliveri — DISMISSED** [review]
Looks good, Approved

**Comment by v-spadarthi** [comment]
@v-dvedak and @v-sabiraj : Please review the solution and provide your approval.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please look into this.

**Comment by v-mchatla** [comment]
@v-atulyadav  
Please resolve the conflicts and get approval for merging.
Thanks

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
