### PR TITLE
update parser with new attributes and fixes for some prefixes issues

### PR DESCRIPTION
**Pull request by danymello**
Required items, please complete
   
   Change(s):
   - Updated the parser for Vectra Stream: VectraStream_function.kql

   Reason for Change(s):
   - Missing attributes (new attributes released in Vectra's product)
   - Some attributes did not have the right prefix (e.g. sometimes identified as string, sometimes as digit)

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@danymello : Could you please resolve the below errors 
image
image
image
image

**Comment by v-spadarthi** [comment]
@danymello : Please fix above commented errors still we are getting same errors.

**Comment by v-laanjana** [comment]
@danymello : Please fix above commented errors still we are getting same errors. and let us know

**Comment by NikTripathi** [comment]
Hi @danymello Please fix the comments. Thanks

**Comment by v-laanjana** [comment]
Hi @danymello Please fix the comments. Thanks

**Comment by v-laanjana** [comment]
Hi @danymello Please fix the comments. Thanks

**Comment by v-laanjana** [comment]
@v-spadarthi , could you please update ??

**Comment by v-spadarthi** [comment]
@danymello : We will check with internal team and let you know the update.

**Comment by v-spadarthi** [comment]
@danymello  : Could you please have a look and let us know if it meets your criteria, we are providing the updated parser [VectraStreamParser.txt](https://github.com/Azure/Azure-Sentinel/files/9675211/VectraStreamParser.txt) to you. Thanks!!

**Comment by v-mchatla** [comment]
Hi @danymello 
Please let us know if the provided parser can help or do you need any help over there.
Thanks

**Comment by danymello** [comment]
@v-mchatla , updated parser I just pushed should be good to go

**Comment by v-amolpatil** [comment]
Hi @danymello, We will have a look and let you know if anything is missing. Thank you!

**Comment by fgu-vectra** [comment]
> @danymello : Please resolve below error image

I don't see the same issue. columns exist in my setup

image

**Comment by v-spadarthi** [comment]
@danymello / @fgu-vectra : Could you please share the updated sample data and will ingest and test it again the parser. Thanks!

**Comment by v-spadarthi** [comment]
@danymello / @fgu-vectra : Could you please share the updated sample data and will ingest and test it again the parser. Thanks!

**Comment by v-spadarthi** [comment]
@danymello / @fgu-vectra : Please share the updated sample data.

**Comment by fgu-vectra** [comment]
> @danymello / @fgu-vectra : Please share the updated sample data.

please take a look at the new samples added.

**Comment by v-spadarthi** [comment]
Thanks for sharing the sample data.
I have ingested sample data 
image
Parser tested again working fine
image
 But,This PR is depending on https://github.com/Azure/Azure-Sentinel/pull/5816 as well please fix below
image

**Comment by fgu-vectra** [comment]
> Thanks for sharing the sample data. I have ingested sample data image Parser tested again working fine image But,This PR is depending on #5816 as well please fix below image

added smtp metadata sample which has the "date" attribute

**Comment by v-spadarthi** [comment]
@danymello : Please resolve the validation errors. Thanks!

**Comment by v-spadarthi** [comment]
@danymello : Thanks for the fixing the validation error.

**Review by v-spadarthi — APPROVED** [review]

**Comment by v-spadarthi** [comment]
Ingested sample data again 
image

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
