### PR TITLE
ACN_CD_SymantecEndpointProtection_Parser_03

### PR DESCRIPTION
**Pull request by chicduong**
## Proposed Changes

  - The initial parser was written for a SyslogMessage that included the syslog header:
      <51>Nov 12 09:46:30 SAMPLESERVER SymantecServer: AA1030546,10.11.11.11...

The SyslogMessage, if ingested into the workspace properly will start with the Server details first, dropping the syslog header: 
       AA1030546,10.11.11.11...

The following revisions will correct this.
(updated sample data included)

12/15 - 
- Added parsing for Agent Risk Logs
- Corrected RemoteHostName field that was of datetime type

### CODE REVIEW

**Review by shainw — CHANGES_REQUESTED** [review]
When testing your query against your sample events from the JSON, it only parses some data fields, of the 177 sample rows, 67 of the rows are not parsed.

image

**Comment by shainw** [comment]
@chicduong - See my PR comment please. ;)

**Comment by chicduong** [comment]
@shainw Sample data was created from old data from an inconsistent syslog feed, the new sample data is from a working active syslog feed. The parser has been going through multiple updates since. I have updated both parser and sample data. I have added an "Other Log" types for those that were not captured.

**Review by shainw — APPROVED** [review]
Looks good, apologies for delay on this one, been wrapped up in the recent security incident. :)

**Pull request merged**
