### PR TITLE
ACN_CD_CrowdStrikeFalcon_Parser01

### PR DESCRIPTION
**Pull request by acnccd**
## Proposed Changes

+ CrowdStrike Falcon Endpoint Protection Parser
+ Sample Data

### CODE REVIEW

**Review by v-jayakal — DISMISSED** [review]

**Review by shainw — CHANGES_REQUESTED** [review]
@acnccd - Apologies on the delay here, a bit behind on reviews.   I cannot test the parser as the sample data set doesn't have the columns needed.  For example, you are parsing DeviceCustomNumber*, DeviceCustomDate*, DeviceCustomString*, but these are not included.  I only see DeviceCustomIPv6Address* and DeviceCustomFloatingPoint*.  The AdditionalExtensions parsing seems to work fine, but there is no example of SessionStartTime or SessionEndTime in the field, so I cannot confirm that specific part functions properly.

**Comment by acnccd** [comment]
> 
> 
> @acnccd - Apologies on the delay here, a bit behind on reviews. I cannot test the parser as the sample data set doesn't have the columns needed. For example, you are parsing DeviceCustomNumber*, DeviceCustomDate*, DeviceCustomString*, but these are not included. I only see DeviceCustomIPv6Address* and DeviceCustomFloatingPoint*. The AdditionalExtensions parsing seems to work fine, but there is no example of SessionStartTime or SessionEndTime in the field, so I cannot confirm that specific part functions properly.

@shainw, sample data was usually submitted for data exports post-parsing. I will try to generate more sample data to export pre-parsed data.

**Comment by acnccd** [comment]
@shainw new sample data uploaded

**Comment by acnccd** [comment]
@shainw any updates on this?

**Review by shainw — APPROVED** [review]

**Pull request merged**
