### PR TITLE
fixed broken McAfee link and improved wording

### PR DESCRIPTION
**Pull request by yenba**
Change(s):
   - Fixed broken links and improved documentation wording

   Reason for Change(s):
   - McAfee link was broken

   Version updated:
   - No

   Testing Completed:
   - No

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@yenba : Please resolve the below validation error.
image

**Comment by yenba** [comment]
> @yenba : Please resolve the below validation error. image

I only changed the readme.md file which does not have any versions, since it is not actually a detection.

**Comment by v-spadarthi** [comment]
@yenba : This is False alarm we are working on the fix in the validation code.

**Comment by v-spadarthi** [comment]
@yenba : we are working on the fix and let you know the update.

**Comment by yenba** [comment]
> @yenba : we are working on the fix and let you know the update.

Sounds good. Thank you!

**Comment by v-spadarthi** [comment]
We are testing the fix

**Comment by v-spadarthi** [comment]
Once @v-rucdu is approved the testPR[#6508 ] we are going to merge

**Review by v-spadarthi — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
