### PR TITLE
Handled Event Breaking in AzureFunction

### PR DESCRIPTION
**Pull request by pranav-sacumen**
Required items, please complete

Change(s):
Updated Cloudflare/Data Connectors/AzureFunctionCloudflare/main.py.

Reason for Change(s): 
To handle unsupported characters

Version Updated: yes

Testing Completed:
Yes

Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @pranav-sacumen,
Please check comment above and act accordingly.
Thanks

**Comment by pranav-sacumen** [comment]
Hi @v-rusraut Changes are done.

> hi @pranav-sacumen Please work on below points.
> 
> * Please update main.py in CloudflareConn zip file as well.  - **Done**
>   Path :\Solutions\Cloudflare\Data Connectors\CloudflareConn.zip\AzureFunctionCloudflare
> * After 3.0.0 package version we need to create package with 3.0.1, please create package with 3.0.1 - **Changed**
> * Please do not keep older zip package file in 3.0.1 , currently your zip file 3.1.0  having older version zip file  present. - **Removed**
> 
> 
> * We need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
>   https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md
> 
> Thanks

**Comment by v-rusraut** [comment]
Hi @pranav-sacumen 

While deploying mainTemplate getting error **Deployment template validation failed**.
This error getting due to Workbook metadata was not present in WorkbooksMetaData.Json file, so we added workbook metadata and fixed the issue.

Now please work on below points :

- Take latest of you branch and repackage the solution again with version 3.0.1.
- Update Below highlighted dataconnector and parser description with provided description in CreateUiDefinition File.


**DataConnector Description** = This solution installs the data connector for ingesting Cloudflare logs into Microsoft Sentinel. After installing the solution, configure and enable this data connector by following guidance in Manage solution view.

**Parser Description** = The solution installs a parser that transforms ingested data. The transformed logs can be accessed using the Cloudflare Kusto Function alias.

- Update createUiDefinition file in 3.0.1 zip as well. 
- We need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by pranav-sacumen** [comment]
@v-rusraut I have made the changes as requested.

**Comment by v-rusraut** [comment]
Hi @pranav-sacumen,
Thanks for reply, we will provide update on 04 Aug 2023.

**Comment by v-rusraut** [comment]
Hi @pranav-sacumen,
This PR having validation issue and branch conflicts, While resolving the issue few files added into branch.
So we created New PR with your changes and fixed the validation issue.
Now we are closing this PR.
You can check update on new PR : https://github.com/Azure/Azure-Sentinel/pull/8708
Thanks

**Pull request closed without merging**
