### PR TITLE
Adding Azure DevOps data connector and onboarding scripts

### PR DESCRIPTION
**Pull request by azurekid**
Required items, please complete
   
   Change(s):
   - Adding data connector for Azure DevOps

   Reason for Change(s):
   - Didn't exist yet

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Tested and validated see screenshots reamd.md for proof
   
image

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by azurekid** [comment]
removed external links from templates and documentation

**Comment by azurekid** [comment]
@vmanojreddy I've also created a PR for the issue causing this pipeline not to run succesfully:
https://github.com/Azure/Azure-Sentinel/pull/4738

**Comment by v-spadarthi** [comment]
@azurekid  :Please resolve the validation checks (DataConnectorValidations)

**Comment by vmanojreddy** [comment]
@azurekid  Logo need to svg format not be in png format. thanks!!

**Comment by vmanojreddy** [comment]
@azurekid  In Create UI Definition logo not displaying properly. Please  correct  logo format and update in Create UI Definition. thanks!!!
image

**Comment by vmanojreddy** [comment]
@azurekid  Please provide correct folder structure. Please refer below path for the folder structure.
Refer pat:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Alsid%20For%20AD

**Comment by vmanojreddy** [comment]
> > @azurekid Please provide correct folder structure. Please refer below path for the folder structure. Refer pat:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Alsid%20For%20AD
> 
> @vmanojreddy Thanks for the feedback, Do I also need to follow the solutions structure for just a data connector? If so, I will update the folder structure with pleasure of course

@azurekid  Please follow folder structure for the package as well and provide zip with latest version. thanks!!!

**Comment by azurekid** [comment]
> > > @azurekid Please provide correct folder structure. Please refer below path for the folder structure. Refer pat:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Alsid%20For%20AD
> > 
> > 
> > @vmanojreddy Thanks for the feedback, Do I also need to follow the solutions structure for just a data connector? If so, I will update the folder structure with pleasure of course
> 
> @azurekid Please follow folder structure for the package as well and provide zip with latest version. thanks!!!

- [x] added the data connector as a solution.
- [x] updated logo to .svg
- [x] updated raw links to Azure/Azure-Sentinel/master
- [x] removed raw links to SecureHats/Azure-Sentinel/main

**Comment by azurekid** [comment]
@vmanojreddy @v-spadarthi,  
Anything else I need to do?

**Comment by vmanojreddy** [comment]
@azurekid  Logo Should be under 5 Kb. Thanks!!!

**Comment by vmanojreddy** [comment]
@azurekid  In Data connector folder why we are adding another uiMainTemplate.json file.

**Comment by azurekid** [comment]
> @azurekid In Data connector folder why we are adding another uiMainTemplate.json file.

uiMainTemplate.json is used for the mainTemplate.json deployment
the other uiDefinition file is related to the azuredeploy.json

**Comment by azurekid** [comment]
> @azurekid Logo Should be under 5 Kb. Thanks!!!

I cannot make the file any smaller than it is now.
Shall I just completely remove the logo and references?

**Comment by vmanojreddy** [comment]
@azurekid why we are maintaining same files at data connector and in solution folder . Please maintain all files in the solution folder remove from data connector folder.
Reference Path : https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Bitglass

**Comment by vmanojreddy** [comment]
@azurekid In check DataConnectorValidations is failing due schema is matching sample template. can you please check once.

**Comment by azurekid** [comment]
> > @azurekid In check DataConnectorValidations is failing due schema is matching sample template. can you please check once.
> 
> I am aware of this, that is why I also created a PR to fix the validation script. It seems to miss the standard table and schema for AzureDevOpsAuditing.
> 
> See PR #4738

**Comment by azurekid** [comment]
> @azurekid why we are maintaining same files at data connector and in solution folder . Please maintain all files in the solution folder remove from data connector folder. Reference Path : https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Bitglass

Hi @vmanojreddy [vmanojreddy](https://github.com/vmanojreddy), Maybe it is more useful to have a call about this.
I initially created just a data connector and opened a PR
Then I got a question from you to create a solution for it. I asked if this was the new standard but never got a reply on it
Now I'm getting the question of why it is a data connector.

So question: If we are creating just a data connector, does this need to be a solution?
There are several examples of recent data connectors being added without a solution pack.

Waiting for your reply.

**Comment by v-marimanda** [comment]
Hi @azurekid, Please accept our apologies for not communicating the things clearly to you. I am was in migration mode and migrating all the old solutions to new template specs and missed out this. really sorry for this.

For maintaining constancy all file should be in solution folder and following one folder structure in solution folder [Folder structure reference  Path](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Box). So, could you please remove file from data connector folder and maintain files in solution folder only. thanks!!!

**Comment by NikTripathi** [comment]
@azurekid Can you please do the needful. Thanks

**Comment by v-marimanda** [comment]
@azurekid  please address above comment and we have merged the [4738](https://github.com/Azure/Azure-Sentinel/pull/4738) but still checks are not passing. Please take a look once. thanks!!!

**Comment by v-mchatla** [comment]
hi @azurekid 
Can you please address @v-marimanda comments,
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid 
Can you please remove the content inside the individual data connector folder. If you want to push any changes, please add those inside solution folders.

**Comment by azurekid** [comment]
> Hi @azurekid Can you please remove the content inside the individual data connector folder. If you want to push any changes, please add those inside solution folders.

done

**Comment by v-mchatla** [comment]
Hi @azurekid 
Sorry for multiple comments, I just noticed that you have created Package with 1.0.0 version.
We have recently changed the solutioning approach. Can you please use V2 version of tool to create package, [new version can be found here](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2) . All packages that are created using V2 version of the tool starts with v2.0.0 so, please use the version for your package 2.0.0

**Comment by v-mchatla** [comment]
> Hi @azurekid Sorry for multiple comments, I just noticed that you have created Package with 1.0.0 version. We have recently changed the solutioning approach. Can you please use V2 version of tool to create package, [new version can be found here](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2) . All packages that are created using V2 version of the tool starts with v2.0.0 so, please use the version for your package 2.0.0

Hi @azurekid 
Please accommodate above changes. Let us know if you need any help over there.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid
Please accommodate above changes. Let us know if you need any help over there.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid
Please accommodate above changes. Let us know if you need any help over there.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid 
We are happy to help you out. Let us know if you are blocked with something.
Thanks

**Comment by v-spadarthi** [comment]
Hi @azurekid
Please accommodate above changes. Let us know if you need any help over there.
Thanks

**Comment by azurekid** [comment]
Hi will pick this up straight away. A bit frustrating do, because this PR has been created months ago when everything was running fine.

Now need to do a complete re-test of the solution after so many changes and requests 🤔

**Comment by v-mchatla** [comment]
Hi @azurekid 
We would like to hear back from you. Let us know if you need any assistance in accommodating the above changes.
Thanks

**Comment by azurekid** [comment]
Hey Guys!
Can we please have a teams call about this.
I have been trying to use your PowerShell script for the Create Solution V2 but this contains some errors.

In the script there are some hardcoded values for API versions that are used to create the 'mainTemplate.json'
This causes a lot of failures in the tests that are being executed after the templates are build by the script!

image

This error is caused by this part in the PowerShell script:
image

Another error occurs because of this code in the PowerShell script:
image

With error in the output:
image

This script also creates a bunch of variables that in the mainTemplate.json that also gives errors:
image

It starts to become frustrating because I provided a fully working solution that could already be used by the Microsoft Security community. But due late response on the PR (5 months now) and change in processes, scripts etc. I continuously run in to new impediments. 

Please come with a proper solution and plan to action otherwise I will, to my regret, retract my PR

**Comment by azurekid** [comment]
Okay as it seems, My folder was reused to create a AzureDevOps solution only containing Analytics Rules and Hunting Rules.
All work that wsa put in creating a custom Data Connector for Azure DevOps is gone and assumably lost.

The whole purpose of this PR in the first place was just a data connector for MS Sentinel, and after a lot of messages to create a solution package of it I did. Because of this some else overwritten all my code, and is it gone now.

How would you like to proceed, as there is now a Azure DevOps Auditing solution in MS Sentinel, but no connector to ingest the required data. :-(

I hope you do understand that I am not very happy right now after putting in a lot of free evening hours.
@v-spadarthi @v-marimanda @NikTripathi @v-mchatla @oshezaf

**Comment by v-mchatla** [comment]
Hi @azurekid ,
We really appreciate your patience and continued support on this. I agree that this is a long pending PR but we are also occupied with solution migration during that phase. Now we are actively working on the GIT Hub Prs to get it closure as soon as it's get created. The only way is that we can create a v2 version of the package for you. I will also check with team on how to proceed in this case and keep you posted.
In the meantime, can you please confirm on the content we will be using for the new package. Can I add data connector to the existing Azure devops Auditing package which is alredy having Analytic rules and hunting queries.
Thanks

**Comment by v-mchatla** [comment]
> 
Hi @azurekid 
Please confirm on the content, we will create package based on your inputs.
Thanks

**Comment by azurekid** [comment]
Yes, I am nowcin the process of redeployment in my own tenant to make sure everything still works as expected. ETA is 12h CET

**Comment by v-mchatla** [comment]
Thanks for the update!!!

**Comment by v-mchatla** [comment]
Hi @azurekid,
I hope you have already started working on it. Let me know if you need any help over there.
Thanks

**Comment by azurekid** [comment]
Hi @v-mchatla, I have updated the solution files according to the documentation and tested it in my own dev environment

**Comment by v-mchatla** [comment]
Hi @azurekid 
I Really appreciate your efforts in accommodating the requested changes. 
I could see 2 different folders for AzureDevopsAuditing. Can we just have one and place all the content inside that. Please refer to [this](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Bitglass) folder structure if required.
image

**Comment by v-mchatla** [comment]
Hi @azurekid,
Please accommodate the requested changes and resolve conflicts.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Can you please address suggested changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Sorry for multiple follow ups, It would be great if you can spare some time to address the suggested changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Please address the comments.
Thanks

**Comment by azurekid** [comment]
Hi @v-mchatla very busy lately unfortunately.
Folders can be merged indeed. Ca nyou guys do that, as I have some issues with my local branches and stuff. :-/

**Comment by v-mchatla** [comment]
Hi @azurekid,
Thanks for the response. I will discuss with team and try to fix it from our end.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Currently we are working on priority items, I will let you know once I discussed with team and make respective changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Please expect some delay, as we are currently occupied with priority items. We will come back to you soon.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Thanks for understanding, will let you know once your changes are done.
Thanks

**Comment by v-spadarthi** [comment]
@v-mchatla : Please have a look and provide your feedback.

**Comment by v-mchatla** [comment]
Hi @azurekid,
Team is occupied with priority work. I will discuss about the timelines for fixing this and comeback to you.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Team is occupied with priority work. I will discuss about the timelines for fixing this and comeback to you.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
Please expect some delay, as we are currently occupied with priority items. We will come back to you with timelines for fixing this.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
We have added this to our backlog item, will let you know once done with the changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
We have added this to our backlog item, will let you know once done with the changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
We have added this to our backlog item, will let you know once done with the changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
I'm going work on this today. Will share you the update by EOD.
Thanks

**Comment by v-mchatla** [comment]
Hi @azurekid,
As its long pending PR and having lot of conflicts, I have created a new PR #7005 with the data connector and packaging changes. You can track the status in that PR and also post your queries there. I'm still testing the changes will get it reviewed and merged the changes as soon as possible.
Thanks

**Pull request closed without merging**
