### PR TITLE
Create-AzureSnapshot/readme: add quick deployment option

### PR DESCRIPTION
**Pull request by juju4**
## Proposed Changes

  - Readme: add quick deployment option

(Todo: Prerequisites and fix per #3489)

### CODE REVIEW

**Comment by sarah-yo** [comment]
@juju4 please complete the Readme doc (add in the prerequisites that are marked as TBD)

**Comment by NikTripathi** [comment]
@juju4 Please make the required changes.

**Comment by juju4** [comment]
I have not identified all the requirements to make this logicapp run "as is" and plan to submit an alternate version.

it seems to me the information below is not made available anymore from sentinel block
```
@{body('Parse_JSON')?['ExtendedProperties']?['Query']}
```
at least, not present in my environment.

**Comment by v-sabiraj** [comment]
Hey @sarah-yo , please review and approve the changes, thanks.

**Comment by v-sabiraj** [comment]
Hey @juju4, can we close this for now, you can reopen or raise new PR once it is decided, thanks.

> I have not identified all the requirements to make this logicapp run "as is" and plan to submit an alternate version.
> 
> it seems to me the information below is not made available anymore from sentinel block
> 
> ```
> @{body('Parse_JSON')?['ExtendedProperties']?['Query']}
> ```
> 
> at least, not present in my environment.

**Comment by juju4** [comment]
Closing.
It would be easier if initial author could confirm if current version is working and add requirements.

**Pull request closed without merging**
