### PR TITLE
SIGNL4 Solution Packaging

### PR DESCRIPTION
**Pull request by rons4**
Fixes #
Packaging for SIGNL4.

## Proposed Changes
This is the packaging for the SIGNL4 solution here: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/SIGNL4.
The tests all went fine except one.

When testing the mainTemplate.json here: https://aka.ms/AzureSentinelPrP I got the error:
Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/69d7587b-7319-4f09-aa7f-ef6e16eba8e5' for type 'Microsoft.OperationalInsights/workspaces/providers/dataConnectors' at line '192' and column '85' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)

When using " Test-AzTemplate" it mentioned: Please have only azureDeploy.json or mainTemplate.json, not both.
So, probably I have to remove mainTemplate.json.

Thanks a lot in advance and I appreciate your assistance.

### CODE REVIEW

**Comment by v-jayakal** [comment]
@rons4 - Please find the attached package and validate this package and update the PR. Support tier value is modified to "Partner", please update the solutionmetadata accordingly. Please test this package and update the PR.
[1.0.0.zip](https://github.com/Azure/Azure-Sentinel/files/7787682/1.0.0.zip)

**Comment by rons4** [comment]
Thanks @v-jayakal, I tested the template from your .zip file and I get the following error:

Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/78314b2d-533a-4393-b2e0-b7f6dc719ca3' for type 'Microsoft.OperationalInsights/workspaces/providers/dataConnectors' at line '191' and column '85' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)

The UI definition file looks fine.

Not sure how I can proceed now. Thanks again for your help.

**Comment by v-jayakal** [comment]
@rons4 - Are you talking about arm-ttk validations, then please run your test at the package level (not at solution level). If it is deployment, its successful at my end.
image
You have conflicts in the PR, that has to be resolved and have many files (509) modified in your PR which should not be part of the PR. Please take care of them. Thanks.

**Comment by rons4** [comment]
Thanks @v-jayakal, indeed something went wrong here. I will clean it up and then get back to you.

I tested the JSON files (createUiDefinition.json and mainTemplate.json) as mentioned here:
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution#azure-sentinel-solutions-packaging-tool-guidance

What link do you you use to test the package? I tried the one from your screenshot but it seems I cannot get there.

Thanks again for your help.

**Comment by rons4** [comment]
Hi @v-jayakal,
Happy New Year ....
I think I repaired the Pull Request  and it should look fine now.
Please let me know if you should have any further comments.
Thanks again.

**Review by rons4 — COMMENTED** [review]
Mistake from previous commit fixed.

**Comment by rons4** [comment]
Hi @v-jayakal, for your information, I fixed one small mistake and not everything should look fine.
Just let me know if you need anything from my side or if you should have any further comments.

**Comment by v-jayakal** [comment]
@rons4 - Thanks for resolving the validation, hope you have tested the package at your end. we will merge this. Please go ahead with publishing of the solution. Please let us know if you need any help. Thanks.

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
