### PR TITLE
Update Playbook_ARM_Template_Generator.ps1

### PR DESCRIPTION
**Pull request by ThijsLecomte**
Required items, please complete
   
   Change(s):
   - Updated Playbook ARM Generator to allow for other Parameter types such as Arrays and booleans

   Reason for Change(s):
   - Current version converted all types to Strings, independent of the configuration in the Playbook

   Version Updated:
   -N/A

   Testing Completed:
   -OK

   Checked that the validations are passing and have addressed any issues that are present:
   - OK

@sreedharande Could you verify this?

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Thanks for making these changes @ThijsLecomte, we will soon provide an update on this.

**Comment by sreedharande** [comment]
Thanks for making these changes @ThijsLecomte, can you please update Playbook_ARM_Template_Generator.zip also with these code changes

**Review by sreedharande — DISMISSED** [review]

**Comment by v-atulyadav** [comment]
Hi @ThijsLecomte, please update Playbook_ARM_Template_Generator.zip also with these code changes. Thanks

**Comment by v-rbajaj** [comment]
Hi @ThijsLecomte, please provide update on above comment.

**Comment by ThijsLecomte** [comment]
@v-rbajaj  & @v-atulyadav , zip has been updated

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
