### PR TITLE
Proofpoint TAP native poller connector

### PR DESCRIPTION
**Pull request by vu-socprime**
Change(s):
   - add Proofpoint TAP native poller connector

### CODE REVIEW

**Review by anki-narravula — APPROVED** [review]
Looks good. Working as expected. 

image
image


image

**Comment by v-sabiraj** [comment]
Hey @vu-socprime , please move the data connector file to Solutions folder, thanks.

**Comment by vu-socprime** [comment]
> Hey @vu-socprime , please move the data connector file to Solutions folder, thanks.

Hi @v-sabiraj. Done.

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @vu-socprime  -  when we have both CCP and function app based connector, we are including both the tables in Parser so that one parser is enough irrespective of the connector. We can find example [Parser (Slack) here ](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlackAudit/Parsers/SlackAudit.txt). So can you please include regular table also as part of the parser.

like - ` union isfuzzy=true SlackAudit_CL, SlackAuditNativePoller_CL`

**Review by anki-narravula — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
