### PR TITLE
Qualys VM v2 version azure function 

### PR DESCRIPTION
**Pull request by v-jayakal**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by preetikr** [comment]
@v-maudan Please resolve conflicts. Thanks

**Comment by v-maudan** [comment]
> @v-maudan Please resolve conflicts. Thanks

Done

**Review by pranaybqualys — APPROVED** [review]
Looks good.

**Review by pbankar28 — DISMISSED** [review]

**Comment by pbankar28** [comment]
looks good.

**Comment by v-maudan** [comment]
@pbankar28 , Can you please confirm which of the below should be used for URI:
https://qualysguard.qg3.apps.qualys.com 
        OR
https://qualysapi.qg3.apps.qualys.com 

Thanks !

**Comment by pbankar28** [comment]
@v-maudan , please use this URL https://qualysapi.qg3.apps.qualys.com

**Comment by v-jayakal** [comment]
> @v-maudan , please use this URL https://qualysapi.qg3.apps.qualys.com

@pbankar28 - we used the given API, for us, data is not returned. We might not have any data to be retrieved.  Were you getting the data if you use the above API you provided? Please let us know. Thanks.

**Comment by pbankar28** [comment]
@v-maudan , I'm sure you would be having a valid Qualys subscription with the VM application activated, right? If you don't have any assets data scanned in the subscription please check with Qualys support at support@qualys.com.

**Comment by v-maudan** [comment]
> @v-maudan , I'm sure you would be having a valid Qualys subscription with the VM application activated, right? If you don't have any assets data scanned in the subscription please check with Qualys support at [support@qualys.com](mailto:support@qualys.com).

@pbankar28 , We have qualys subscription but no VM application activated , Can you please check once at your end, if you get data and working as expected, so that we will merge this PR ? Thanks!

**Comment by pbankar28** [comment]
@v-maudan , that has to be done by contacting Qualys support at support@qualys.com from your side.

**Comment by v-maudan** [comment]
@pbankar28, I have tested Qualys VM v2 version changes E2E and found following issues, Can you please fix. Thanks!
1. [Data connector](https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Qualys%20VM/QualysVM_API_FunctionApp.json) and [workbook ](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/QualysVM.json)queries are failing.
Issue - **Detections** column missing in Qualys V2 version which is used in queries .[PFB screenshot for reference]
image
image

**Comment by v-maudan** [comment]
@pbankar28, Can you please update on this ?

**Comment by pbankar28** [comment]
Hi v-maudan, The detections data was normalized earlier. In this version, we have flatten the detections data so the query can be formed on columns related to detections easily without going to the second level of querying. You may use the below KQL to get the detection related data. Please query  the QualysHostDetection_CL table only to get the list of all the available columns.

`KQL:
QualysHostDetection_CL
| mv-expand todynamic(QID_s) 
| extend Vulnerability = tostring(QID_s) 
| summarize count() by Vulnerability
| top 10 by count_
`

**Comment by v-jayakal** [comment]
Closing this as a new PR https://github.com/Azure/Azure-Sentinel/pull/2728 is created for Qualys V2

**Pull request closed without merging**
