### PR TITLE
3.0.3 Atlassian Beacon solution name update

### PR DESCRIPTION
**Pull request by dark-binary**
Required items, please complete
   
   Change(s):
   - Solution Name updated to "Integration for Atlassian Beacon"
   - Updated version to 3.0.3 in main template
   - Updated Release Notes

   Reason for Change(s):
   - To comply with Atlassian's legal naming convention

   Version Updated:
   - N/A
   
   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @dark-binary,
Thanks for raising this PR. This PR will be investigated and we will update you about the same before 07 March, 2024

**Comment by v-rusraut** [comment]
Hi @dark-binary,
If you want to update solution name, then you need to update solution name in data file.
After that you need to repackage it.
Thanks

**Comment by dark-binary** [comment]
Hey @v-rusraut,

We tried updating the solution name in data file, but that packaging kept failing - since the folder name doesn't match with the solution's new name. Does this mean - we have to rename the folder from "Atlassian Beacon" to "Integration for Atlassian Beacon" as well?

Happy to jump on a call if that will make it easier :)

**Comment by v-rusraut** [comment]
Hi @dark-binary,
Please rename folder from "Atlassian Beacon" to "Integration for Atlassian Beacon" and create package of solution.
Thanks

**Comment by v-atulyadav** [comment]
Hi @dark-binary, please act on above comments. Thanks

**Comment by dark-binary** [comment]
Apologies for the delay - will rename the folder and updaete shortly

**Comment by dark-binary** [comment]
Hey @v-rusraut and @v-atulyadav - completed 🙂

**Comment by v-atulyadav** [comment]
Thanks @dark-binary, we will review this PR and let you know if anything required from your end. Thanks

**Review by v-rusraut — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
