### PR TITLE
Add API 404 handling.

### PR DESCRIPTION
**Pull request by adamhuang97**
Required items, please complete
   
   Change(s):
   - Add API 404 handling.

   Reason for Change(s):
   - Bug fix.

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by NikTripathi** [comment]
looking into this.

**Comment by NikTripathi** [comment]
Hi @adamhuang97 Please update the corresponding zip packages as well.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97, can you please update the corresponding zip packages as well.

**Comment by adamhuang97** [comment]
Hi @NikTripathi , @v-atulyadav,
Thanks for your reminder.

Best regards,
Adam

**Comment by v-atulyadav** [comment]
Hi @adamhuang97 , thanks for your response.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97 , we want update in corresponding zip package; but we can see update in 2.0.0 also, can you please explain what change you have made in 2.0.0. Thanks

**Comment by adamhuang97** [comment]
Hi @v-atulyadav 
Sorry for confusion caused.
We would like to re-publish our solution on Sentinel content hub.
So I re-submit a solution package at some pr.

Thank you.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97 , thanks for your clarification we will look into this.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97  , we are looking into this.

**Review by v-atulyadav — COMMENTED** [review]
Hi @adamhuang97 , we get below error while testing functions(a. timer_trigger b. timer_trigger_oat c.queue_trigger_wb), can you please check and fix this.

image

image

**Comment by adamhuang97** [comment]
Hi @v-atulyadav ,
Please refer last pr review result.
It seem cause by incorrect token.
https://github.com/Azure/Azure-Sentinel/pull/4610
I think you could pass this error.

**Comment by NikTripathi** [comment]
@adamhuang97 Please look into this sir.
Thanks

**Comment by adamhuang97** [comment]
Hi @NikTripathi , @v-atulyadav ,
Already sent api token by MS support.
Please help to review by api token.
Thank you.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97 , using API token timer trigger functions works properly but queue trigger functions still giving below error. Also branch has some conflicts.

image

**Comment by adamhuang97** [comment]
Hi @v-atulyadav,
Please help to provide queue message.
Or re-setup test env, it maybe cause by api token issue before.

**Comment by adamhuang97** [comment]
Hi @v-atulyadav ,
Already solve conflicts.
Please help to try it again.

**Comment by v-atulyadav** [comment]
Hi @adamhuang97 ,  thank you for getting in touch. We will look into this.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
