### PR TITLE
Increased bin to 10m and fixed deprecated commands

### PR DESCRIPTION
**Pull request by tduarte14**
Increased bin outcomes from 5 to 10 minutes to reduce even more the volume of data Fixed deprecated commands:
- makeset to make_set
- makelist to make_list
- mvexpand to mv-expand

   Change(s):
   - Increased bin to 10m 
   - fixed deprecated commands

   Reason for Change(s):
   - Increased bin outcomes from 5 to 10 minutes to reduce even more the volume of data Fixed deprecated commands:
   - replaced makeset with make_set and limit
   - replaced makelist with make_list and limit
   - replaced mvexpand with mv-expand

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by shainw — CHANGES_REQUESTED** [review]
- I don't have specific issues with the changes, but in larger environments the change to 10m bins doesn't help much, results dropped by about 30% based on quick testing.  
  - There are still potentially thousands of results and the query can take excessively long (meaning high resource use).  
- The timeRange value should be adjusted to 2h
- The queryFrequency/queryPeriod should be changed to 2h each.  
  - These changes will allow for the query to use less resources at any given time.
- MS internal folks - please have a look at improving the performance of this query in the next semester.

**Review by v-prasadboke — APPROVED** [review]

**Review by v-prasadboke — COMMENTED** [review]
need to review again

**Comment by v-prasadboke** [comment]
Hello @tduarte14 any respond to @shainw's Comment

**Comment by tduarte14** [comment]
I'm really not 100% sure of what shainw wants, but I can add extra changes.
I haven't made bigger changes because I didn't want to change too much, but if it's ok, I can:

- adjust timeRange to 2h
- set queryFrequency and queryPeriod to 2h

regarding the bin of 10 min, would it be ok with the changes above or you recommend different value?

**Comment by tduarte14** [comment]
@microsoft-github-policy-service agree

**Comment by devikamehra** [comment]
@shainw I agree, I will get this detection added in the list for quality improvement.
According to your comments, the changes are made by @tduarte14. Can you please provide your approval?

**Comment by v-atulyadav** [comment]
Hi @shainw, please provide your approval. Thanks

**Comment by v-prasadboke** [comment]
Hello @shainw waiting for your approval

**Comment by v-prasadboke** [comment]
@shainw anything on this pr

**Review by shainw — APPROVED** [review]

**Pull request merged**
