### PR TITLE
Citrix WAF: Fixed Pkg

### PR DESCRIPTION
**Pull request by msft-sm**
Citrix WAF: Fixed Pkg
- Azure Sentinel to Microsoft Sentinel

   Required items, please complete
   
   Change(s):
   - Azure Sentinel to Microsoft Sentinel

   Reason for Change(s):
   - Azure Sentinel to Microsoft Sentinel

   Version Updated:
   - N/A

   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by msft-sm** [comment]
@v-dvedak 
I fixed the mainTemplate to reflect Microsoft Sentinel instead of Azure Sentinel and I used 2.0.1. 
Let me know if you are not seeing 2.0.1.

**Review by v-dvedak — DISMISSED** [review]

**Comment by v-dvedak** [comment]
@msft-sm, please accommodate the changes for text Microsoft Sentinel in data connector [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Citrix%20Web%20App%20Firewall/Data%20Connectors/Citrix_WAF.json)

**Comment by msft-sm** [comment]
@v-dvedak 
Fixed data connector.

**Comment by v-dvedak** [comment]
There was validation error for python link, it should be fixed now. So will review PR today.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
