### PR TITLE
Update the query to include the DeviceVendor  condition to include th…

### PR DESCRIPTION
**Pull request by gaurava-delinea**
@v-sabiraj  Please review the PR and approve the changes.

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@gaurava-delinea, please update the package as well, thanks.

**Comment by gaurava-delinea** [comment]
> @gaurava-delinea, please update the package as well, thanks.
@v-sabiraj
Are your talking about the zip file? but zip file does not contain the CEF file. Please elaborate what is your meaning with package.

**Comment by v-sabiraj** [comment]
Hi @gaurava-delinea, you need to update the mainTemplate and same in zip of solution package, thanks.

**Comment by gaurava-delinea** [comment]
> Hi @gaurava-delinea, you need to update the mainTemplate and same in zip of solution package, thanks.

@v-sabiraj   Done the requested changes

**Comment by tylerezimmerman** [comment]
@v-mchatla @v-sabiraj any update on this?

**Comment by tylerezimmerman** [comment]
@v-sabiraj any update here?

**Comment by v-sabiraj** [comment]
Hey @gaurava-delinea, @tylerezimmerman, sorry for delay in review.
There are two instances of data connector in main template, the queries are changed for only one. Can you please check and update at other instance as well. It will be better if you create it solution with tool rather than manual update. Please update zip as well once maintemplate is updated. Thanks. 
image

**Comment by gaurava-delinea** [comment]
> Hey @gaurava-delinea, @tylerezimmerman, sorry for delay in review. There are two instances of data connector in main template, the queries are changed for only one. Can you please check and update at other instance as well. It will be better if you create it solution with tool rather than manual update. Please update zip as well once maintemplate is updated. Thanks. image

@v-sabiraj @tylerezimmerman 

Done the requested change. Please approve the PR

**Review by v-sabiraj — APPROVED** [review]
looks good

**Pull request merged**
