### PR TITLE
Replaces PR #5904

### PR DESCRIPTION
**Pull request by techwriter-dev**
See issue [NXLog FIM Solution v2.0.0](https://github.com/Azure/Azure-Sentinel/issues/6263) for details.
   
   Change(s):
   - Resolved various discussions opened by @v-atulyadav

   Reason for Change(s):
   - This PR replaces PR #5904 whose creator is no longer a contributor for NXLog Solutions
   - There have been many URLs changes to the NXLog documentation now that our online documentation supports multiple versions.

   Version Updated:
   - Updated to version 2.0.0 because @v-atulyadav requested this in https://github.com/Azure/Azure-Sentinel/pull/5904#discussion_r969267995

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - May need help

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @techwriter-dev 
We are looking into it.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev 
Can you please address the below things to proceed with further review of your PR.
1. Please provide the sample data to test the Data connector.
2. I could see the solution is named with 2.0.0 version. But when I tested it seems packaged with V1 version of the tool. Can you confirm on the same. If it is not packaged with [V2 Version](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2) of the tool, please create it now.
3.  Replace Azure Sentinel with Microsoft Sentinel as we are following this Naming convention.
Let me know if you need any help over there.
Thanks

**Comment by v-spadarthi** [comment]
@techwriter-dev : Seems some issue with Contributor License Agreement acceptance, please try to sign [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/Azure-Sentinel?pullRequest=6264) again to accept your contribution. Let us know if you need any help over there.
Thanks

**Comment by v-spadarthi** [comment]
@techwriter-dev : Seems some issue with [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/Azure-Sentinel?pullRequest=6264) acceptance, please try to sign Contributor License Agreement again to accept your contribution. Let us know if you need any help over there.
Thanks

**Comment by v-mchatla** [comment]
> Hi @techwriter-dev Can you please address the below things to proceed with further review of your PR.
> 
> 1. Please provide the sample data to test the Data connector.
> 2. I could see the solution is named with 2.0.0 version. But when I tested it seems packaged with V1 version of the tool. Can you confirm on the same. If it is not packaged with [V2 Version](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2) of the tool, please create it now.
> 3. Replace Azure Sentinel with Microsoft Sentinel as we are following this Naming convention.
>    Let me know if you need any help over there.
>    Thanks

Hi @techwriter-dev,
Can you please address the above comments.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev,
Can you please accommodate the requested changes and also accept CLA to accept your contributions.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev,
Can you please accommodate the requested changes and also accept CLA to accept your contributions.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev 
Can you please accommodate the requested changes and Let us know if you need any help over there.
Thanks

**Comment by techwriter-dev** [comment]
@v-mchatla I will need to some time to research what action is required on my part. Because it has been about a year since I have worked on this project, it will take some time for me to work through all the new requirements that have evolved in the meantime.

Unfortunately, my current resources are extremely limited. Presently, I am tasked with a unrelated, high-priority issue that directly impacts our production environment which needs to be resolved before I can invest any time in this issue (NXLog FIM Solution).

Thanks for your understanding.

**Comment by v-mchatla** [comment]
Hi @techwriter-dev 
Thanks for your prompt response. It would be great if you can assign differed tag to this PR for now and resume the work whenever you have time. Let us know if you need any help.
We really appreciate your efforts and contribution.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev,
As per our standard proces we supposed to act or follow up with the respective person to act up on the active PRs. If you need some time to resume the work please move the PR to draft state or assign differed label. So we won't follow up on those items. Thanks for understanding.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev,
As per our standard proces we supposed to act or follow up with the respective person to act up on the active PRs. If you need some time to resume the work please move the PR to draft state or assign differed label. So we won't follow up on those items. Thanks for understanding.
Thanks

**Comment by v-mchatla** [comment]
Hi @techwriter-dev,
Please accomodate the requested changes.
Thanks

**Comment by jszigetvari-nxlog** [comment]
Subscribing to this thread.

**Comment by techwriter-dev** [comment]
Hi @v-mchatla,
This PR will most likely be closed in the near future and reopened again as a new PR by another colleague at NXLog since today is my last day NXLog before I start a new career opportunity next week.

**Comment by v-mchatla** [comment]
Hi @jszigetvari-nxlog 
Can you please close this PR and reopen it as new PR as its pending from long back.
Thanks

**Comment by jszigetvari-nxlog** [comment]
Hi @v-mchatla,
unfortunately I don't seem to find any way to close this pull request, but I will try to arrange to have it closed.

**Comment by v-mchatla** [comment]
Hi @jszigetvari-nxlog,
I have closed this Pull Request for now; you can reopen it whenever you want to resume your work, or you can also create new PR with your change as its pending from long back.
Thanks

**Pull request closed without merging**
