### PR TITLE
Update wiz queries with new tables

### PR DESCRIPTION
**Pull request by yanivblumWiz**
Required items, please complete
   
   Change(s):
   - Updated the queries on the workbook and connector to match with the new table names we offer
   - Updated some descriptions on the ARM template of the solution creation

   Reason for Change(s):
   - We added a code version with new table names for Wiz logs, so we updated the queries accordingly

   Testing Completed:
   - I need help with packaging 

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by yanivblumWiz** [comment]
Hi @v-atulyadav @v-prasadboke 
I need help with packaging everything into a new package version 2.0.1. Can you please assist me with it?

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, There stands 2 workbooks with same name WizFindings.json. One stands in standalone workbook folder while the other one is in the Solution folder. This the reason the validation check is failing. 

We are checking on this issue and we will get back to you by 26 Jun, 2024. 

Thanks, 
Prasad

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz, There stands 2 workbooks with same name WizFindings.json. One stands in standalone workbook folder while the other one is in the Solution folder. This the reason the validation check is failing.
> 
> We are checking on this issue and we will get back to you by 26 Jun, 2024.
> 
> Thanks, Prasad

@v-prasadboke Thnks for your reply!
Let me know if there is anything else you need from me.
Looking forward to hearing back from you
Yaniv

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Sorry for the delay in response. This issue is under discussion and we will update you about the same. 

Thanks, 
Prasad

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Azure deploy file in the Solution is for function app. 
I'm a bit confused about missing data connector. 

Facing issue while packaging the solution. As the azuredeploy file is missing with property "id" which is basically data connector id 

image

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz, Azure deploy file in the Solution is for function app. I'm a bit confused about missing data connector.
> 
> Facing issue while packaging the solution. As the azuredeploy file is missing with property "id" which is basically data connector id
> 
> image

What do you mean by data connector ID? 
I did not change anything in the infrastructure of our solution in this PR.
We have had this solution for over a year and everything was fine.
Maybe you should use the V2 solution package, this is what you guys have used on our solution in the past.

**Comment by yanivblumWiz** [comment]
@v-prasadboke Anyway, the code of our function app is located on a Wiz registry and the URL is within the ARM template, and that's the way we were approved to use by the Sentinel team when we certified our solution initially. 
Let me know if you have any more questions.
Looking forward to hearing from you :)

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, I see you have added a data connector in maintemplate but it is not in the data connector folder. 
Can you please create a data connector for the same.

**Comment by yanivblumWiz** [comment]
@v-prasadboke I am not sure I am following.
I did not add anything new to the main template here, I just updated some queries.
Can you please show me an example of what I need to add? I already have a data connector folder with everything needed for the integration to work.

**Comment by v-prasadboke** [comment]
Hello @yanivblumWiz, Can we get on a call for this. Please share your availability so that we can plan for the same. 
My mail id is - v-prasadboke@microsoft.com 
You can ping me on teams on the same id if needed

**Comment by v-prasadboke** [comment]
Add a custom table schema named **WizIssuesV2_CL  WizIssues_CL**  at location 
https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by yanivblumWiz** [comment]
@v-atulyadav @v-prasadboke 
Hi!
quick question, we can see this:
 
image
image

I still don't see the updated package on the content hub? Why is that?

**Pull request merged**
