### PR TITLE
SlashNext Logic App Connector and playbook templates package.

### PR DESCRIPTION
**Pull request by SaadatAbid-snx**
Signed-off-by: Saadat Abid <saadat.abid.2540@slashnext.net>

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by SaadatAbid-snx** [comment]
Hi Reviewers, Please let us know if anything is required from our side. Thanks.

**Comment by v-spadarthi** [comment]
@rushriva /@devikamehra : Could you please review the Playbooks. Thanks!!

**Comment by SaadatAbid-snx** [comment]
> @SaadatAbid-snx : Could you please resolve the below comments In CreateUI definition while testing we found 2 playbooks only but in master we found 3 playbooks please include all the playbooks and create a package. Can you please provide us the solution input file as well image image While deploying the MainTemplate we are getting below issues, can you please have a look at once and fix it image image image

@v-spadarthi  There are only two playbooks in this folder third folder contains connection connector which is already merged in previous two playbooks. This change was done as per the suggestion from the sentinel team.
Kindly let us know where we need to place the input file. As per the available document we are not able to find location of input file on repo.

These errors are related to the solution files which are generated from the utility which is mentioned in the document. Utility is refactoring the playbook code which is causing these errors. Can you please guide us or share document which can help us in fixing these errors. Thanks.

**Comment by SaadatAbid-snx** [comment]
@v-spadarthi Hi, I hope that you are doing well. Just wanted to confirm if anything is required from our side for continued progress on this PR. Do let us know. Thanks

**Comment by SaadatAbid-snx** [comment]
Dear Reviewers, Please let us know how we can speed up the review process? Thanks.

**Comment by NikTripathi** [comment]
Sorry for the delay @SaadatAbid-snx .
@v-spadarthi please have a look and do the needful.
Thanks

**Comment by SaadatAbid-snx** [comment]
> Sorry for the delay @SaadatAbid-snx . @v-spadarthi please have a look and do the needful. Thanks

@NikTripathi Thanks, really appreciate it if you can help us merge this.

**Comment by v-spadarthi** [comment]
@rushriva /@devikamehra : Could you please review the Playbooks. Thanks!!

**Comment by rushriva** [comment]
Playbooks are approved.

**Comment by SaadatAbid-snx** [comment]
> Playbooks are approved.

Thanks @rushriva.

**Comment by v-sabiraj** [comment]
@SaadatAbid-snx , https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextWebAccessLogAssessment/deploy.json this playbook file contains multiple resource creation like azure functions and storage accounts, can you please make them separate azure deploy file. Thanks.

**Comment by v-sabiraj** [comment]
@SaadatAbid-snx,  Can you please remove the solution package as we are not supporting the creation of multiple resources with solution tool, thanks.

**Comment by SaadatAbid-snx** [comment]
> @SaadatAbid-snx , https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextWebAccessLogAssessment/deploy.json this playbook file contains multiple resource creation like azure functions and storage accounts, can you please make them separate azure deploy file. Thanks.

@v-sabiraj It was done on the request on a Sentinel team reviewer @devikamehra 
Here is the previous PR https://github.com/Azure/Azure-Sentinel/pull/5533

**Comment by SaadatAbid-snx** [comment]
> @SaadatAbid-snx, Can you please remove the solution package as we are not supporting the creation of multiple resources with solution tool, thanks.

@v-sabiraj Please guide how should we create the solution package. Thanks

**Comment by SaadatAbid-snx** [comment]
> @SaadatAbid-snx, Can you please remove the solution package as we are not supporting the creation of multiple resources with solution tool, thanks.

Hi @v-sabiraj, The package with the related artifacts has been removed from PR as per email from Eric

**Comment by v-sabiraj** [comment]
> 

Sorry for the confusion, all the child folders ARM template should deploy the resources directly. For example you already have a [folder](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextPhishingIncidentInvestigation/deploy.json), this have direct resources not the linked templates, please update ARM template similar to above one.

If you want an example for you reference, please refer this [folder](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AWS_IAM/Playbooks) to add function app.
1. Function app resource is created separately through a different ARM template.
2. The function app will be referred inside playbook. (where required in workflow)

**Comment by v-sabiraj** [comment]
> > @SaadatAbid-snx , https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextWebAccessLogAssessment/deploy.json this playbook file contains multiple resource creation like azure functions and storage accounts, can you please make them separate azure deploy file. Thanks.
> 
> @v-sabiraj It was done on the request on a Sentinel team reviewer @devikamehra Here is the previous PR #5533

Sorry for the confusion, all the child folders ARM template should deploy the resources directly. For example you already have a [folder](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextPhishingIncidentInvestigation/deploy.json), this have direct resources not the linked templates, please update ARM template similar to above one.

If you want an example for you reference, please refer this [folder](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AWS_IAM/Playbooks) to add function app.

1. Function app resource is created separately through a different ARM template.
2. The function app will be referred inside playbook. (where required in workflow)

**Comment by SaadatAbid-snx** [comment]
> Hey @SaadatAbid-snx, can you please for the requested changes, thanks.
> 
> > > > @SaadatAbid-snx , https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextWebAccessLogAssessment/deploy.json this playbook file contains multiple resource creation like azure functions and storage accounts, can you please make them separate azure deploy file. Thanks.
> > > 
> > > 
> > > @v-sabiraj It was done on the request on a Sentinel team reviewer @devikamehra Here is the previous PR #5533
> > 
> > 
> > Sorry for the confusion, all the child folders ARM template should deploy the resources directly. For example you already have a [folder](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SlashNext/Playbooks/SlashNextPhishingIncidentInvestigation/deploy.json), this have direct resources not the linked templates, please update ARM template similar to above one.
> > If you want an example for you reference, please refer this [folder](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AWS_IAM/Playbooks) to add function app.
> > 
> > 1. Function app resource is created separately through a different ARM template.
> > 2. The function app will be referred inside playbook. (where required in workflow)

Updated as per understanding

**Comment by v-sabiraj** [comment]
Hi @anki-narravula, can you please review this, so that we can procced to merge, thanks.

**Review by anki-narravula — APPROVED** [review]

**Comment by SaadatAbid-snx** [comment]
@v-sabiraj I hope that you are well. Do you any update for us on the package for SlashNext solution. Our product team needs it to create an offer. Hoping to hear from you soon. Thanks

**Pull request merged**
