### PR TITLE
ASIM Added User Management Schema

### PR DESCRIPTION
**Pull request by azurekid**
ASIM Added User Management Schema

   Required items, please complete
   
   Change(s):
   - Updated SchemaTester.csv

   Reason for Change(s):
   - Added ASIM User Management Schema.
   - Previous PR got closed after fixing merge conflict.

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by azurekid** [comment]
Will do as soon as the bandwidth allows me to...
Sorry for the delay

**Comment by v-atulyadav** [comment]
Hi @azurekid,
Have you completed the changes to the PR yet or is it ready for review?
Thanks

**Comment by azurekid** [comment]
> Hi @azurekid, Have you completed the changes to the PR yet or is it ready for review? Thanks

Yes,

Everything is updated and free from conflicts

**Comment by v-atulyadav** [comment]
noted @azurekid, Thanks.

**Comment by v-atulyadav** [comment]
Hi @azurekid, 
Please accept our apologies for the delay in responding. We will provide you with an update as soon as possible.
Thanks.

**Comment by vakohl** [comment]
ETA for this review is 18th Aug

**Comment by azurekid** [comment]
> ETA for this review is 18th Aug

I will do a git merge in the meantime to avoid any merge conflicts.
Thanks for the update

**Comment by v-atulyadav** [comment]
Noted @azurekid, thanks.

**Comment by vakohl** [comment]
@azurekid We have an existing PR for User Management Update that's reviewed and will be merged soon. I'll wait for that PR to get merged before reviewing this, ideally these should have the same content.
https://github.com/Azure/Azure-Sentinel/pull/8564/files#diff-33a5a2a62460f8b04fe72fd22a290172c018f5c79801d6315d8d564aef22c7ba

**Comment by azurekid** [comment]
I noticed the PR from KustoKing (Gianni Castaldi) 
Mine was previously approved, but had a merge conflict. Merging caused some issues so reopened a PR with the already approved content.

See PR #8257

**Comment by vakohl** [comment]
> I noticed the PR from KustoKing (Gianni Castaldi) Mine was previously approved, but had a merge conflict. Merging caused some issues so reopened a PR with the already approved content.
> 
> See PR #8257

Will try to get both of this PR changes merged.

**Comment by vakohl** [comment]
> > I noticed the PR from KustoKing (Gianni Castaldi) Mine was previously approved, but had a merge conflict. Merging caused some issues so reopened a PR with the already approved content.
> > See PR #8257
> 
> Will try to get both of this PR changes merged.

@azurekid Please pull the latest changes from Tester CSV. We have merged the user management schema fields.

**Review by azurekid — COMMENTED** [review]
Pulled latest from master

**Comment by vakohl** [comment]
@azurekid there isn't any changes showing. Seems all changes you suggested has been incorporated.

**Comment by azurekid** [comment]
> @azurekid there isn't any changes showing. Seems all changes you suggested has been incorporated.

Yeah,  I noticed.  But if a bummer but I will talk with him as he would only update the documentation.  We are working on the same client project.  😕

**Comment by azurekid** [comment]
> @azurekid there isn't any changes showing. Seems all changes you suggested has been incorporated.

Hi @vakohl,

I have noticed some errors in the approved Pull Request for UserManagement.
The fields 'EventSchema', 'EventSeverity', 'EventSchemaVersion' are duplicated.

This is causing a breaking issue. I will therefor update my PR to remidiate the errors in the pr of @KustoKing

**Comment by vakohl** [comment]
> > @azurekid there isn't any changes showing. Seems all changes you suggested has been incorporated.
> 
> Hi @vakohl,
> 
> I have noticed some errors in the approved Pull Request for UserManagement. The fields 'EventSchema', 'EventSeverity', 'EventSchemaVersion' are duplicated.
> 
> This is causing a breaking issue. I will therefor update my PR to remidiate the errors in the pr of @KustoKing

@azurekid Thankyou for re-validating and fixing the bug.

**Review by vakohl — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
