### PR TITLE
Veritas analytics rules

### PR DESCRIPTION
**Pull request by swapnildombaleveritas**
Change(s):
   - Added Analytic Rules for Veritas NetBackup product. These rules includes many login failures detection and many anomalies being generated detection.

   Reason for Change(s):
   - Analytic rules for Veritas NetBackup product.

   Version Updated:
   - V1

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas, 
Could you please look into the validation failures? Thanks

**Comment by swapnildombaleveritas** [comment]
> Hi @swapnildombaleveritas, Could you please look into the validation failures? And also add sample data to test the rules in below location. Thanks https://github.com/Azure/Azure-Sentinel/tree/master/Sample%20Data/Custom

Sure. We will look into this

**Comment by v-atulyadav** [comment]
Thanks @swapnildombaleveritas.

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
We're waiting for an update on this. Thanks

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
Please add the sample data as mentioned earlier and also look into the validation failures. Thanks

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas, waiting for your update. Thanks

**Comment by swapnildombaleveritas** [comment]
> Hi @swapnildombaleveritas, waiting for an update. Thanks

Hello, we will update the PR in couple of days.

Thanks
Swapnil

**Comment by swapnildombaleveritas** [comment]
We would be updating PR with changes in couple of days.

thanks

**Comment by v-atulyadav** [comment]
Thanks @swapnildombaleveritas.

**Comment by swapnildombaleveritas** [comment]
We have uploaded sample data file for test NetBackupAlerts_CL.json.

Kindly review

**Comment by v-atulyadav** [comment]
Thanks @swapnildombaleveritas

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,

Sample data validation is failing. Thanks
image

**Comment by swapnildombaleveritas** [comment]
> Hi @swapnildombaleveritas,
> 
> Sample data validation is failing for the reasons listed below. Please sanitize the sample data. Thanks image

Thanks. We have updated the sample data file.

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
I have cleared all failed validations. Could you please confirm if we require the files below in this PR?
image

**Comment by swapnildombaleveritas** [comment]
> Hi @swapnildombaleveritas, I have cleared all failed validations. Could you please confirm if we require the files below in this PR? image

Hi, I am not aware  of those files but definitely not required for the functionality we adding.

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
It seems these files have been present since your first commit. I suggest you uncommit these files from your PR. Thanks

**Comment by swapnildombaleveritas** [comment]
> Hi @swapnildombaleveritas, It seems these files have been present since your first commit. I suggest you uncommit these files from your PR. Thanks

Thanks. 

I have removed bot the files now.
Kindly review.

**Review by v-atulyadav — APPROVED** [review]

**Comment by swapnildombaleveritas** [comment]
Thanks for merging the changes. 
Kindly let me know how do I see the changes in the content hub of Sentinel workspace?

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
We need to discuss on this, can we schedule a call? my email id is v-atulyadav@microsoft.com. Or share your email id I can schedule a call. Thanks

**Comment by v-atulyadav** [comment]
Hi @swapnildombaleveritas,
Please reply on above asks. Thanks

**Pull request merged**
