### PR TITLE
Origin/users/rahul/acsc

### PR DESCRIPTION
**Pull request by rahul0216**
Change(s):
   - Initial commit
   - Added ARM template, readme files, screenshot and logo

   Reason for Change(s):
   - Initial commit

   Version Updated:
   - First commit
   - 1.0.0

   Testing Completed:
   - End to end deployment testing
   - End to end functionality testing

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Review by anki-narravula — COMMENTED** [review]
Pls add dark theme image aswell

**Review by anki-narravula — APPROVED** [review]
Looks good except pagination feature required for API calls. We need to incorporate in future release. For now it is good

**Comment by anki-narravula** [comment]
@v-laanjana I think this is for pP November cycle and community solution. Please speak with Prateek and package

**Comment by v-laanjana** [comment]
> @v-laanjana I think this is for pP November cycle and community solution. Please speak with Prateek and package

sure Anki

**Comment by v-laanjana** [comment]
ok let me see.

**Pull request merged**
