### PR TITLE
Playbook to pull AlienVault OTX for Sentinel TI rule

### PR DESCRIPTION
**Pull request by AndrewBlumhardt**
First contribution. MSIT employee. AlienVault OTX based on Jason Wescott’s article on OTX-Sentinel integration. Preparing a blog post for the MSIT SI blog for more detailed info.

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by sarah-yo — CHANGES_REQUESTED** [review]
Can you add a "deploy to Azure" and "deploy to azure gov" in the read me, please?

**Comment by AndrewBlumhardt** [comment]
Updated Readme. First try :-)

**Review by RoundNutz4 — APPROVED** [review]

**Comment by richlilly2004** [comment]
@AndrewBlumhardt want to collaborate on this? I have one in my repo here if you'd like.

https://github.com/richlilly2004/Azure-Sentinel/tree/master/Playbooks/Get-TIfromOTX

**Comment by AndrewBlumhardt** [comment]
> @AndrewBlumhardt want to collaborate on this? I have one in my repo here if you'd like.
> 
> https://github.com/richlilly2004/Azure-Sentinel/tree/master/Playbooks/Get-TIfromOTX

Hi Rich,

Happy to collaborate or let you post your solution instead. I am fairly new to logic apps and github. Mainly posting for learning and to fill a gap.  You may want to add file-hash to cover all of the Sentinel rules. I like your use of parameters and MDAPT section. 

I am confused about one thing. This method limits the collection to 1000 records per run. There are reportedly millions of OTX records. Is there a need to maintain a longer running list of historic IOCs or is a daily pull of recent updates sufficient. It seems like you would want all non-expired IOCs going back as far as reasonably possible. I was thinking of creating a nested version to pull IOCs going back much further; sort of an one-time collection to seed the workspace. Maybe I have an incorrect understanding of OTX. The analytic rules do only look back 14 days.

Thanks, Andrew
andrew.blumhardt@microsoft.com

**Pull request merged**
