### PR TITLE
solution folder & repackaged azure activity 

### PR DESCRIPTION
**Pull request by v-laanjana**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution 
Azure activity
See guidance below
Version Updated:
2.0.1
See guidance below
Testing Completed:
The link for test results is
[Test document](https://microsoftapc.sharepoint.com/:w:/r/teams/EcosystemCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7BD1064527-7970-4F14-A91B-CCD4B8C42F24%7D&file=Sentinel%20Release%20Checklist%20-V2%20solutions-Azure%20Activity.docx&action=default&mobileredirect=true&share=IQEnRQbRcHkUT6kbzNS4xC8kAb9IU_zWkRu00cFZy0_7P5E)

See guidance below
This is an 1p solution.

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @v-laanjana,
There is file movement from detection and hunting query folders. Can you please add skip validations.
Thanks

**Comment by v-mchatla** [comment]
I will review and share the feedback.

**Comment by v-mchatla** [comment]
Hi @v-laanjana,
Please resolve the conflicts.
Thanks

**Comment by v-laanjana** [comment]
> Hi Team, Is it ready for review? Thanks

please review it.

**Review by v-mchatla — DISMISSED** [review]
Changes looks good

**Comment by v-mchatla** [comment]
Hi @v-laanjana,
Can you please resolve the conflicts.
Thanks

**Review by v-mchatla — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
