### PR TITLE
Cloudformation template for AWS S3 connector

### PR DESCRIPTION
**Pull request by chrisjaimon2012**

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 : Please fix the validation errors.

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 : Please fix the validation errors and data connector file should not be a .YAML file.
Could you please refer the below URL for data connector templates and do the necessary changes if required. https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/Templates

**Comment by chrisjaimon2012** [comment]
> @chrisjaimon2012 : Please fix the validation errors and data connector file should not be a .YAML file. Could you please refer the below URL for data connector templates and do the necessary changes if required. https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/Templates

hey @v-spadarthi , the PR consists of a Cloudformation template that deploys the necessary components for the AWS-S3 data connector, similar to the Powershell scripts that achieves the same. Its not a new connector.

**Comment by NikTripathi** [comment]
@v-spadarthi Please look into this.

**Comment by v-spadarthi** [comment]
Checking with CAT team to proceed further

**Comment by v-spadarthi** [comment]
Waiting for the update from CAT team to proceed further

**Comment by devikamehra** [comment]
@chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector?

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector? Thanks

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector? Thanks

**Comment by v-mchatla** [comment]
> @chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector? Thanks

Hi @chrisjaimon2012,
Can you please address the above comments. 
Thanks

**Comment by v-sabiraj** [comment]
> @chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector? Thanks

@chrisjaimon2012, can you please provide your thoughts on this, thanks.

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 Can you please provide brief description of what your template does and how do you think this can help the existing connector? Does this add a missing piece, or it is simply another way of creating the same connector? Thanks

Hi @chrisjaimon2012,
Can you please address the above comments.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrisjaimon2012,
Can you please address the above comments.
Thanks

**Comment by v-spadarthi** [comment]
Hi @chrisjaimon2012,
Can you please address the above comments.
Thanks

**Comment by v-spadarthi** [comment]
@chrisjaimon2012 :
We wanted to check on the status of PR https://github.com/Azure/Azure-Sentinel/pull/5656 . PR is pending from more than 60 days. Let us know if any assistance is required for this PR. As Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-spadarthi** [comment]
We are waiting for the update from author. Thanks!

**Comment by v-spadarthi** [comment]
We are waiting for the update from author. Thanks!

**Comment by v-spadarthi** [comment]
We are waiting for the update from author. Thanks!

**Comment by v-spadarthi** [comment]
Hi @chrisjaimon2012 Since we have not received response from last 7 days, we are closing your [PR](https://github.com/Azure/Azure-Sentinel/pull/5656) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
