### PR TITLE
Aki2419 patch 2

### PR DESCRIPTION
**Pull request by aki2419**
Fixes #

## Proposed Changes
This is a new hunting detection query in Azure Sentinel for detecting Drive by compromise technique.
  -
  -
  -

### CODE REVIEW

**Review by sreedharande — CHANGES_REQUESTED** [review]
@aki2419: Can you please correct  yaml file DriveByCompromiseDetection.yaml. Error message: can not read a block mapping entry; a multiline key may not be an implicit key at line 27, column 1

**Review by shainw — CHANGES_REQUESTED** [review]
Thanks for the contribution.  Some specific changes required.  In general, please review the [Content Contribution Guidance](https://github.com/Azure/Azure-Sentinel/wiki/Contribute-to-Sentinel-GitHub-Community-of-Queries) and the [Query Style guide](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide) to make sure you are aligned with all requirements.  You will want to include the EntityMapping piece also.

**Comment by shainw** [comment]
@aki2419  - When do you think you will be able to do the requested updates to this PR?

**Comment by aki2419** [comment]
> @aki2419 - When do you think you will be able to do the requested updates to this PR?

@shainw i'll try and complete the requested updates by this weekend, if that's ok..

**Comment by shainw** [comment]
Closing, no updates and very old.

**Pull request closed without merging**
