### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lior-tamir**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@manishkumar1991 : Please review the Playbook and provide your approval. Thanks!

**Comment by v-spadarthi** [comment]
@manishkumar1991 : Please review the Playbook and provide your approval. Thanks!

**Comment by v-spadarthi** [comment]
@manishkumar1991 : Please review the Playbook and provide your approval. Thanks!

**Review by rahul0216 — APPROVED** [review]
These Playbooks look goos.

**Review by rahul0216 — COMMENTED** [review]
1. For Playbook EntityTrigger-VirusTotal-GetIPReport, there should be a check if ARM ID exist or not.
2. In playbook EntityTrigger-ResetAADUserPassword, there is no action being taken if ARM ID doesn't exist. So if analyst runs the playbook from entity context, he/she won't get any feedback of completion. Don't you think there should be a way communicate the completion of action?

**Comment by v-atulyadav** [comment]
Hi @rahul0216, please provide your feedback. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on @rahul0216 comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on @rahul0216 comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on @rahul0216 comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, we still waiting for your response on above comment's. Thanks

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on @rahul0216 comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, waiting for your response on above comment's. Thanks

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on @rahul0216 comment. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, please respond on above comments. Thanks.

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, waiting for your response on above comment's. Thanks

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, we wanted to check on the status of PR #<[6971](https://github.com/Azure/Azure-Sentinel/pull/6971)>. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

**Comment by v-atulyadav** [comment]
Hi @lior-tamir, we wanted to check on the status of PR #<https://github.com/Azure/Azure-Sentinel/pull/6971>. PR is pending for more than 32 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

**Comment by rahul0216** [comment]
@v-atulyadav , I've made the suggested changes. @manishkumar1991 @anki-narravula Please review the updates.

**Comment by BenjiSec** [comment]
Hi, Lior is not part of the org anymore. Is there anything that I can do instead so that it is merged?

**Comment by v-atulyadav** [comment]
Hi @manishkumar1991 @anki-narravula, could you please review the updated. Thanks.

**Comment by manishkumar1991** [comment]
> Hi @manishkumar1991 @anki-narravula, could you please review the updated. Thanks.

I am reviewing it.

**Review by manishkumar1991 — APPROVED** [review]
approved

**Comment by v-atulyadav** [comment]
Hi @BenjiSec, please check with Contributor License Agreement(CLA). Thanks.

**Comment by BenjiSec** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by v-atulyadav** [comment]
Closed this as this branch was owned by Lior and he has left the org new PR#(https://github.com/Azure/Azure-Sentinel/pull/7497)

**Pull request closed without merging**
