### PR TITLE
solution folder created for zoom reports solution

### PR DESCRIPTION
**Pull request by v-laanjana**
Change(s):
See guidance below
Reason for Change(s):
This PR is part of template spec solution 
Zoom Report
See guidance below
Version Updated:
2.0.1
See guidance below
Testing Completed:
The link for test results is
[Test document](https://microsoftapc.sharepoint.com/:w:/r/teams/EcosystemCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B716A3FBB-6888-4F8E-95D3-38D7D871C742%7D&file=Sentinel%20Release%20Checklist%20-V2%20solutions-Azure%20Activity.docx&action=default&mobileredirect=true&share=IQG7P2pxiGiOT5XTONfYccdCAUczA2coJgCEz9sUCnYVR0w)

See guidance below
This is an 1p solution.

### CODE REVIEW

**Comment by v-laanjana** [comment]
@v-mchatla  please review

**Comment by v-mchatla** [comment]
Hi @v-laanjana,
There are instances of Azure sentinel in the data connector. Please check and replace with Microsoft Sentinel. Also update the screenshots with actual Dataconnector currently pointed the preview version in the test document.
image
image
Function app is returning 503. Check with Team/Darshana how to proceed on this.
image
Thanks

**Comment by v-laanjana** [comment]
> Hi @v-laanjana, There are instances of Azure sentinel in the data connector. Please check and replace with Microsoft Sentinel. Also update the screenshots with actual Dataconnector currently pointed the preview version in the test document. image image Function app is returning 503. Check with Team/Darshana how to proceed on this. image Thanks

for 503  error it will fixed once  extensionBundle vesrion changed so we  can ignore for now?

**Comment by v-mchatla** [comment]
Hi @v-laanjana,
Please address the suggested changes.
Thanks

**Comment by v-laanjana** [comment]
> Hi @v-laanjana, There are instances of Azure sentinel in the data connector. Please check and replace with Microsoft Sentinel. Also update the screenshots with actual Dataconnector currently pointed the preview version in the test document. image image Function app is returning 503. Check with Team/Darshana how to proceed on this. image Thanks
function app issue will fix in below PR 
https://github.com/Azure/Azure-Sentinel/pull/6675

**Review by v-mchatla — APPROVED** [review]
Changes looks good. Just keep an eye on the dependency PR, once that is merged, will retest the function app.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
