### PR TITLE
DomainTools Playbooks 

### PR DESCRIPTION
**Pull request by RamboV**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-marimanda** [comment]
Hi @rushriva and @devikamehra Please review the playbooks and provide your signoff. thanks!!!

**Comment by v-atulyadav** [comment]
Hi @rushriva and @devikamehra Please review the playbooks and provide your signoff. thanks!!!

**Comment by v-laanjana** [comment]
Hi @rushriva and @devikamehra Please review the playbooks and provide your signoff. thanks!!!

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @RamboV  - Thank you for your submission and apologies for the delay in getting back to you. Please find my comments below.

- We have recently migrated to new approach (template specs) and as part of this, now having metadata object is mandatory for every playbook. You can find the instructions here - https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide#contribution-guidelines
- For examples you can refer this playbook https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Playbooks/OktaPlaybooks/Okta-EnrichIncidentWithUserDetails/azuredeploy.json
- I see one of the playbooks using function app, can you please move function app resource to separate folder, outside playbook, so that when we create package, we don't miss this resource. We can name it as <Purpose>FunctionApp
- Once you make the changes, we can deploy and test these playbooks

**Comment by v-laanjana** [comment]
@RamboV could  you please check anki-narravula's  comments.

**Comment by RamboV** [comment]
> @RamboV could you please check anki-narravula's comments.

@anki-narravula @v-laanjana 
attended the requested changes, kindly review and provide your feedback.

**Comment by v-spadarthi** [comment]
@anki-narravula :  Requested changes resolved by @RamboV and again could you please review and provide your signoff. Thanks!!

**Comment by anki-narravula** [comment]
Hi @v-spadarthi  - Looks good to me. Approving this. Any idea who creates package for this? Asking because we need to use V2 version of the tool, and we don't support function app directly in the tool. We need to little bit manual work. 
@v-sabiraj  aware of this on how to handle function apps. Can you please be in touch with Sanmit and make sure we provide flawless package to @RamboV

**Review by anki-narravula — APPROVED** [review]
Approving playbooks. While creating package please consider my advice given separately

**Comment by v-laanjana** [comment]
@v-dvedak  please merge it.

**Pull request merged**
