### PR TITLE
onboard Forcepoint Cloud Security Gateway

### PR DESCRIPTION
**Pull request by v-admahe**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by Dlo-Bagari** [comment]
@v-jayakal  as you requested, I need to review and approve this PR. can you add me to the list of reviewers for this PR?

**Comment by Dlo-Bagari** [comment]
> @v-jayakal as you requested, I need to review and approve this PR. can you add me to the list of reviewers for this PR?

@v-jayakal I see you have assigned the PR to me, but I still can not review and approve this PR . this review and approval will be done on the Azure/Sentinel repo and I am not sure if I have permission to do that. 
please the below screenshot. I do not have reviewing button.

image

**Comment by Dlo-Bagari** [comment]
Approval, All the changes are captured in this PR,

**Comment by preetikr** [comment]
Thanks @Dlo-Bagari for the review - please close out the old PRs related to this. It'll help to scorch your repo and possibly re-fork and clone the repo for future changes. 
@v-jayakal - please merge this and take it forward - thanks.

**Comment by v-rucdu** [comment]
@Dlo-Bagari : We have updated Id and Title of connector to match with Vendor Name as per Rule. Below are the old and changed values. Thanks!!!

**Old Values:**
"id": "ForcepointCloudSecurityGateway",
"title": "Forcepoint Cloud Security Gateway",

**New Values:**
"id": "ForcepointCSG", 
"title": "Forcepoint CSG",

**Review by v-maudan — APPROVED** [review]

**Comment by v-jayakal** [comment]
> @Dlo-Bagari : We have updated Id and Title of connector to match with Vendor Name as per Rule. Below are the old and changed values. Thanks!!!
> 
> **Old Values:**
> "id": "ForcepointCloudSecurityGateway",
> "title": "Forcepoint Cloud Security Gateway",
> 
> **New Values:**
> "id": "ForcepointCSG",
> "title": "Forcepoint CSG",

@Dlo-Bagari, Please note the change of id and title to have consistency and to follow the guidelines here https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Data%20Connectors%20Template%20Guidance.md. The expectation is to have the Provider name in id and title. Please let us know that you are aware of this change and okay with it. Rest of the connector is ready for approval and merging. Thanks.

**Comment by Dlo-Bagari** [comment]
> > @Dlo-Bagari : We have updated Id and Title of connector to match with Vendor Name as per Rule. Below are the old and changed values. Thanks!!!
> > **Old Values:**
> > "id": "ForcepointCloudSecurityGateway",
> > "title": "Forcepoint Cloud Security Gateway",
> > **New Values:**
> > "id": "ForcepointCSG",
> > "title": "Forcepoint CSG",
> 
> @Dlo-Bagari, Please note the change of id and title to have consistency and to follow the guidelines here https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Data%20Connectors%20Template%20Guidance.md. The expectation is to have the Provider name in id and title. Please let us know that you are aware of this change and okay with it. Rest of the connector is ready for approval and merging. Thanks.

@v-jayakal I am ok with this change.

**Comment by v-jayakal** [comment]
> > > @Dlo-Bagari : We have updated Id and Title of connector to match with Vendor Name as per Rule. Below are the old and changed values. Thanks!!!
> > > **Old Values:**
> > > "id": "ForcepointCloudSecurityGateway",
> > > "title": "Forcepoint Cloud Security Gateway",
> > > **New Values:**
> > > "id": "ForcepointCSG",
> > > "title": "Forcepoint CSG",
> > 
> > 
> > @Dlo-Bagari, Please note the change of id and title to have consistency and to follow the guidelines here https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Data%20Connectors%20Template%20Guidance.md. The expectation is to have the Provider name in id and title. Please let us know that you are aware of this change and okay with it. Rest of the connector is ready for approval and merging. Thanks.
> 
> @v-jayakal I am ok with this change.

@Dlo-Bagari , Thanks.

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
