### PR TITLE
DataComparisonHourly

### PR DESCRIPTION
**Pull request by pranjalv01**
# Data-Comparison-Hourly-Workbook-
Building a custom Sentinel Workbook to get an overview of data Comparison on Hourly basis of log sources 

# Description
The Data Ingestion Comparison Hourly workbook offers a comprehensive view of ingested data, presenting the total data volume and ingestion amounts in GB, categorized by each hour. This breakdown helps in monitoring and comparing data ingestion trends over time, ensuring visibility into hourly ingestion patterns and potential anomalies.
 
# Business Requirements

•  Real-Time Monitoring of Data Ingestion Trends: The workbook provides visibility into hourly data ingestion volumes, allowing businesses to track and monitor trends in real-time, ensuring that data from critical sources is ingested without delays.

•  Proactive Identification of Anomalies: The workbook helps identify inconsistencies or unusual drops in data ingestion volumes, enabling early detection of potential issues with data connectors or source systems, ensuring timely resolution.

•  Data Volume Optimization and Cost Management: By offering detailed insights into hourly data volumes in GB, the workbook allows businesses to optimize ingestion processes, helping to manage and forecast Azure consumption costs more effectively based on data usage patterns.

 
# Prerequisites
•	An active Azure subscription

•	Contributor RBAC role assigned to a development resource group

•	An active Sentinel workspace

•	A Log Analytics workspace linked to Sentinel

•	Basic Required Tables (Syslog, Events, Security Events, Azure Activity) 

 
# Setup Guide
The following provides step-by-step instructions to deploy the Workbook:
 
**Step 1: Access Microsoft Sentinel**
 
• Sign in to the Azure portal: https://portal.azure.com.

• In the search bar, type Microsoft Sentinel and click on it from the results.

• Select the appropriate Sentinel workspace where you want to deploy the custom workbook.

**Step 2: Navigate to the Workbooks Section**
 
• Once in the Sentinel workspace, on the left-hand panel, scroll down and click on Workbooks under the Threat Management section.

**Step 3: Create a New Workbook**
 
• At the top of the Workbooks page, click on the + New button to start creating a custom workbook.

• You’ll now see the workbook editor interface, where you can start designing your custom workbook.

**Step 4: Import a Custom Workbook Template**
 
• If you already have a custom workbook template in JSON format, click on the "Advanced Settings" gear icon (⚙️) in the top right corner of the workbook editor.

• In the menu, choose "Edit as Code".

• Copy your custom workbook JSON code and paste it into the code editor.

• Click Apply to load the template into the workbook.

**Step 5: Save the Workbook**
 
• Once your custom workbook is ready, click Save at the top of the page.

• Provide a name and description for your workbook.

• Select Save to Microsoft Sentinel or My Workbooks to choose the visibility of the workbook. Saving it to Sentinel will make it available to all users in the workspace.
 
# Solution Insights: Workbook Visuals
image

   Required items, please complete
   
   Change(s):
   Created first version

   Reason for Change(s):
   Uploaded the first version

   Testing Completed:
   - Yes, this workbook is tested successfully and requires the Syslog data connector to be connected.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by pranjalv01** [comment]
> @pranjalv01 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
@microsoft-github-policy-service agree [company="Inspira Enterprise Pvt Ltd"]

**Comment by pranjalv01** [comment]
@microsoft-github-policy-service agree [company="Inspira Enterprise Pvt Ltd"]

**Comment by pranjalv01** [comment]
@microsoft-github-policy-service agree company="Inspira Enterprise Pvt Ltd"

**Comment by pranjalv01** [comment]
Not able to find the exact error which I have to resolve to commit it successfully.

@azure-pipelines
Sentinel Content Validation Failing after 17m — Build #Azure Sentinel Validations failed
Required
[Details](https://github.com/Azure/Azure-Sentinel/pull/11132/checks?check_run_id=30262324683)
@azure-pipelines
Sentinel Content Validation (WorkbooksTemplateValidations) Failing after 10m — WorkbooksTemplateValidations failed
Required
[Details](https://github.com/Azure/Azure-Sentinel/pull/11132/checks?check_run_id=30261860168)

**Comment by v-prasadboke** [comment]
Hello @pranjalv01, Can you share your mail id to discuss some doubts about the content of the PR

**Comment by pranjalv01** [comment]
pranjal.verma@inspiraenterprise.com

**Pull request closed without merging**
