### PR TITLE
Adding Data Connector for Commvault Sentinel Integration

### PR DESCRIPTION
**Pull request by Cv-securityIQ**
Required items, please complete
   
   Change(s):
   - Adding Data Connector for Commvault Sentinel Integration
   - Added Azure Function as a data connector

   Reason for Change(s):
   - Adding more functionality to the integration

   Version Updated:
   Yes

   Testing Completed:
   Yes

   Checked that the validations are passing and have addressed any issues that are present:
   Yes

### CODE REVIEW

**Comment by Cv-securityIQ** [comment]
We have built an azure function as a data connector for our integration with microsoft sentinel. In order to package and publish it for the PR, I see that we need an ARM template for this. Is there a way that we can generate the ARM template automatically for the azure function similar to the tool we had for logic apps. Please let me know if you have any suggestions regarding this and if you need any other additional information.

P.S. I'm following this documentation - [Azure-Sentinel/DataConnectors at master · Azure/Azure-Sentinel · GitHub](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors#build-the-connector) to build the connector and here there are no steps mentioned for creating the ARM template.

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
I have cleared failed validations apart from above CodeQL failures, please act on them. Thanks

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Could you please brief us on why dataconnector is in a standalone folder and not in the solution folder? And fill out the  PR template for playbook changes, as you mentioned for the connector in the below.
image

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
We are waiting for your reply. Thanks

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav ,

I've moved the dataconnector folder to the solutions folder.

I have one query, for this key in the ARM template - azuredeploy_CommvaultSecurityIQ_FunctionApp.json
 "WEBSITE_RUN_FROM_PACKAGE": ""
 Do I have to wait for the PR to push the dataconnector zip file to the master repo and then add that link?

**Comment by Cv-securityIQ** [comment]
> Hi @v-atulyadav ,
> 
> I've moved the dataconnector folder to the solutions folder.
> 
> I have one query, for this key in the ARM template - azuredeploy_CommvaultSecurityIQ_FunctionApp.json "WEBSITE_RUN_FROM_PACKAGE": "" Do I have to wait for the PR to push the dataconnector zip file to the master repo and then add that link?

Same goes for the ARM Template link to be present in uiconfig file - CommvaultSecurityIQ_API_AzureFunctionApp

 "description": "**Option 1 - Azure Resource Manager (ARM) Template**\n\nUse this method for automated deployment of the Commvault Security IQ data connector.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[Deploy To Azure](<Add Link to ARM Template on https://aka.ms/threathunter GitHub repo, name template as azuredeploy_Connector_PROVIDER_NAME_APPLIANCE_NAME_AzureFunction.json>)\n2. Select the preferred **Subscription**, **Resource Group** and **Location**. \n3. Enter the **Workspace ID**, **Workspace Key**, **API Username**, **API Password**, 'and/or Other required fields'. \n>

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
I have created both shortlinks, once PR merge will update with the actual path.
1. WEBSITE_RUN_FROM_PACKAGE : https://aka.ms/sentinel-CommvaultSecurityIQ-functionapp
2. Deploy to Azure: https://aka.ms/sentinel-CommvaultSecurityIQ-azuredeploy
Update the above links in your files and repackage again. Thanks

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
We are waiting for your replay on above asks. Thanks

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav ,

We are working on it. We will update by this Thursday EOD.

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav ,

We have fixed all the issues. 

Thanks

**Comment by v-atulyadav** [comment]
Thanks @Cv-securityIQ, 
We will update you on this.

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
I am still seeing that the `WEBSITE_RUN_FROM_PACKAGE` and `Deploy to Azure` links were not updated. Please refer to the comment above, where we shared the links. Thanks

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav, We have made changes as suggested.

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Please share with us screenshot of running connector and invocation logs. Thanks

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav ,

Apologies for delay here.
We are running into some issues. We will update you by Friday EOD.

**Comment by v-atulyadav** [comment]
Thanks @Cv-securityIQ.

**Comment by Cv-securityIQ** [comment]
Please find details below:
Invocation Logs:
[Invocation Logs.log](https://github.com/Azure/Azure-Sentinel/files/15338572/Invocation.Logs.log)

Screenshots:
Alert Details
Landing
List

Thanks

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Thank you for the screenshots. Please repackage the solution so that the newly added content will be visible within the solution. Refer to the link below for your reference. Thanks
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Please repackage the solution. Thanks

**Comment by v-atulyadav** [comment]
Thanks @Cv-securityIQ.

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Please add your newly added analytical rule (CommvaultSecurityIQ_Alert.yaml) and data connector (CommvaultSecurityIQ_API_AzureFunctionApp.json) to the data file, increase the solution version to 3.0.1, and repackage the solution again. Thanks
image

**Review by v-atulyadav — APPROVED** [review]

**Comment by Cv-securityIQ** [comment]
Hi @v-atulyadav , thank you for your assistance in getting the changes merged. Do you know how long it might take for the data connector to be visible in the content hub page?

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ,
Please publish the latest package in the partner center so it will come in Darsy certification. Once certification is cleared, it will land in the deployment cycle, so it will be visible in the content hub. Thanks

**Comment by v-sudkharat** [comment]
Hey @Cv-securityIQ, I have tried to make some correction in ARM template file of azure deploy in this PR -https://github.com/Azure/Azure-Sentinel/pull/11050

Which helps to resolve the above-mentioned error, but i am unable to test it due to credentials issue, so can you please check the changes and let me know if it's correct. Thanks!

**Comment by Cv-securityIQ** [comment]
Hi @v-sudkharat , I believe it must be failing because of the credentials. I will validate the function app once and let you know.

**Comment by v-sudkharat** [comment]
@Cv-securityIQ, Ok, please let us know, once it done

**Comment by Cv-securityIQ** [comment]
**Update**

We are making changes by replacing Commvault Security IQ to Commvault Cloud to align with our current branding requirements. We will be pushing a change in couple of days.  

cc @v-sudkharat @v-atulyadav

**Comment by Cv-securityIQ** [comment]
Hi @v-sudkharat . Created a pr with the changes you suggested : https://github.com/Azure/Azure-Sentinel/pull/11135

**Pull request merged**
