### PR TITLE
Archiving, Basic Logs, Retention Workbook

### PR DESCRIPTION
**Pull request by seanstark**
Required items, please complete
   
   Change(s):
   - New Archiving, Basic Logs, Retention Workbook Created 

   Reason for Change(s):
   - New workbook provides more detailed information on table plans, easier ability to update table plans, view search and restore tables. Update workbook also includes more help specific context to guide users better

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Review by alexkarabas — DISMISSED** [review]

**Comment by vmanojreddy** [comment]
@seanstark  Logo should be less than 5kb.

**Comment by seanstark** [comment]
> 

Is there a list of requirements for the svg logo? I keep running into validation issues with the pipeline checks

**Comment by seanstark** [comment]
Fixed the logo issues, new one provided should meet the requirements.

**Comment by vmanojreddy** [comment]
@seanstark Workbook query is failing. Please look into it. thanks!!!
image

**Comment by seanstark** [comment]
> @seanstark Workbook query is failing. Please look into it. thanks!!! image

That's expected and there is nothing I can do about it unfortunately with the current workbook supported features. The error occurs due to a underlying query returning no results that is used in the merge query. 

If you click Show Help, the user will have information on the error.

**Review by vmanojreddy — APPROVED** [review]

**Pull request merged**
