### PR TITLE
Support changed from Microsoft to Cloudflare

### PR DESCRIPTION
**Pull request by pranav-sacumen**
Required items, please complete
   
   Change(s):
   - Changed support from Microsoft to Cloudflare

   Reason for Change(s):
   - Support tier change

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by pranav-sacumen** [comment]
@microsoft-github-policy-service agree [company="Cloudflare"]

**Comment by pranav-sacumen** [comment]
@microsoft-github-policy-service agree company="Cloudflare"

**Comment by pranav-sacumen** [comment]
/@microsoft-github-policy-service agree company="your company"

**Comment by pranav-sacumen** [comment]
@microsoft-github-policy-service agree company="cloudflare"

**Comment by v-mchatla** [comment]
Hi @pranav-kalariya 
Can you please update the below things in the createUIDefinition:
1. Update the solution Description with old description
image
image
2. Update the Description in the [DataFile](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloudflare/Data/Solution_Cloudflare.json) with below content.
"Description": "The [Cloudflare](https://www.cloudflare.com/) solution provides the capability to ingest [Cloudflare logs](https://developers.cloudflare.com/logs/) into Microsoft Sentinel using the Cloudflare Logpush and Azure Blob Storage. Refer to [Cloudflare documentation](https://developers.cloudflare.com/logs/about/) for more information.\n \n  **Underlying Microsoft Technologies used:** \r \n This solution takes a dependency on the following technologies, and some of these dependencies either may be in [Preview](https://azure.microsoft.com/support/legal/preview-supplemental-terms/) state or might result in additional ingestion or operational costs:\n\n  a. [Azure Monitor HTTP Data Collector API](https://docs.microsoft.com/azure/azure-monitor/logs/data-collector-api) \n\n b.[Azure Functions](https://azure.microsoft.com/services/functions/#overview)",
3. Remove redundant data connector text from all the Hunting Queries description in the CreateUIDefinition File.
image

**Comment by pranav-sacumen** [comment]
Hi @v-mchatla ,

1. Updated the solution Description with old description

2. Updated the Description in the [DataFile](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloudflare/Data/Solution_Cloudflare.json) with the given content.


3. Removed redundant data connector text from all the Hunting Queries description in the CreateUIDefinition File.

Do I need to change anything in 2.0.3.zip file?

**Comment by v-mchatla** [comment]
> Hi @v-mchatla ,
> 
> 1. Updated the solution Description with old description
> 2. Updated the Description in the [DataFile](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloudflare/Data/Solution_Cloudflare.json) with the given content.
> 3. Removed redundant data connector text from all the Hunting Queries description in the CreateUIDefinition File.
> 
> Do I need to change anything in 2.0.3.zip file?
Hi @pranav-sacumen 
Yes, please update the 2.0.3.zip file with updated createUIDefinition file.
Thanks

**Comment by pranav-sacumen** [comment]
Thanks @v-mchatla , I have updated 2.0.3.zip wth latest CreateUIDefinition File.

> > Hi @v-mchatla ,
> > 
> > 1. Updated the solution Description with old description
> > 2. Updated the Description in the [DataFile](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloudflare/Data/Solution_Cloudflare.json) with the given content.
> > 3. Removed redundant data connector text from all the Hunting Queries description in the CreateUIDefinition File.
> > 
> > Do I need to change anything in 2.0.3.zip file?
> > Hi @pranav-sacumen
> > Thanks for making the suggested changes, please update the 2.0.3.zip file with updated createUIDefinition file.
> > Thanks

**Review by v-mchatla — APPROVED** [review]
Changes look good

**Pull request merged**
