### PR TITLE
Bumped cryptography from 3.3.2 to 39.0.1

### PR DESCRIPTION
**Pull request by dhara-shah-sp**
Change(s):
   - Bumped cryptography from 3.3.2 to 39.0.1

   Reason for Change(s):
   - Updated cryptography from 3.3.2 to 39.0.1

   Version Updated:
   - No

   Testing Completed:
   - Yes

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @v-rucdu, please provide your feedback on this. Thanks

**Comment by v-atulyadav** [comment]
Closing this PR, as informed partner to update their cryptography to latest version... Thanks!!!

**Review by v-atulyadav — COMMENTED** [review]
Hi @dhara-shah-sp, please see below point and act accordingly

1. The cryptography version of requirements.txt inside SearchEvent.zip is not updated.
image
image

2. In addition, you will need to update the respective version folder from the below-mentioned location
image

**Once you have done with these changes, attach screenshots of successful running data connector invocation logs**.

**Comment by dhara-shah-sp** [comment]
@v-atulyadav : Changes have been committed. Kindly review and let me know you if anything else is still required.

**Review by v-atulyadav — COMMENTED** [review]
Hi @dhara-shah-sp, update these files with 41.0.0 version as new dependent bot PR #8191 has been raised for this version. I also noticed that your zip package has the wrong folder structure. As shown below, your zip file contains all remaining files.

image

As shown below, you have done the wrong structure.
image

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, could we have a call to discuss this? We will correct these changes over the call. We work in IST timezone.

**Comment by dhara-shah-sp** [comment]
Sure. What is your good email address where we can discuss further about setting up a meeting?
I can be reached out via email at ***@***.******@***.***> . I work in CST timezone

Regards,
Dhara Shah
Software Engineer II
***@***.******@***.***>

From: v-atulyadav ***@***.***>
Date: Wednesday, June 7, 2023 at 05:44
To: Azure/Azure-Sentinel ***@***.***>
Cc: Dhara Shah ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Bumped cryptography from 3.3.2 to 39.0.1 (PR #8054)
Hi @dhara-shah-sp, could we have a call to discuss this? We will correct these changes over the call. We work in IST timezone. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @dhara-shah-sp<https://urldefense.com/v3/__https:/github.com/dhara-shah-sp__;!!MsNKLpFGsw!Lrbs6mIXoRNWncHj9-5ZbbK7d_xxPTAQkDBWcJynOXH8Bgmyd0CNKgfBNiDhixanqHYTfUS5dCXT3fmBF-HTMtg201s$>, could we have a call to discuss this? We will correct these changes over the call. We work in IST timezone.

**Comment by v-atulyadav** [comment]
v-atulyadav@microsoft.com is my email id, please schedule a call. Thanks

**Comment by dhara-shah-sp** [comment]
@microsoft-github-policy-service agree [company="{SailPoint}"]

**Comment by dhara-shah-sp** [comment]
@microsoft-github-policy-service agree company="SailPoint"

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, please attach screenshots of the successful running connector logs and also make sure the folder structure is correct as we discussed. The first level is SearchEvent.zip and the second level is all files contained within it. please refer below correct folder structure screenshots

image

image

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, waiting for your response. Thanks

**Comment by dhara-shah-sp** [comment]
Hi @v-atulyadav : I will be submitting the changes by end of the week. Thank you!

**Comment by dhara-shah-sp** [comment]
Function App (Data Connector)

**Comment by dhara-shah-sp** [comment]
@v-atulyadav kindly review the recent changes and let me know your feedback. Thank you!

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, please download below `attached zip` and include in path `Solutions/SailPointIdentityNow/Data Connectors/` and then share successful running data connector/invocation log screenshots.

[SeachEvent.zip](https://github.com/Azure/Azure-Sentinel/files/11933382/SeachEvent.zip)

For dataconnector invocation log screenshots, please click on function name then select monitor tab. Refer below example screenshots
image

image

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, looking forward to your response. Thanks

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, if you are experiencing any challenges with changes, please contact me. Thanks

**Comment by dhara-shah-sp** [comment]
@v-atulyadav  Kindly find the attached successful running data connector/invocation log screenshot 

Screenshot 2023-07-09 at 23 25 45

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, 
There is still a problem with the folder structure. We need to schedule a call to discuss this. 
Thanks

**Comment by dhara-shah-sp** [comment]
Hello @v-atulyadav : Can you please elaborate on what the issue is ? Because I exactly followed the steps you mentioned earlier. I am unsure of what more is to be done here.

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, I have attached a zip file with proper folder structure above, please include this zip in the suggested path below.
image

Your zip file has the following folder structure
image

**Comment by v-atulyadav** [comment]
Hi @dhara-shah-sp, waiting for your response. Thanks

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
