### PR TITLE
Create Cross-tenantAccessSettingsOrganizationDeleted.yaml

### PR DESCRIPTION
**Pull request by dimmand**
Required items, please complete
   
   Change(s):
   - Updated syntax for Cross-tenantAccessSettingsOrganizationDeleted.yaml

   Reason for Change(s):
   - New schema used for Cross-tenantAccessSettingsOrganizationDeleted.yaml

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections and provide your comments. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections and provide your comments. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections and provide your comments. Thanks!

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the Detections and provide your comments. Thanks!

**Review by aprakash13 — CHANGES_REQUESTED** [review]
Thanks @dimmand.

Have a couple of very small suggestions:

In most of the queries we have
      | where OperationName contains "Update a partner cross-tenant access setting"

Considering that **contains** is resource intensive can this be replaced by has or == operator in all the queries that has contains.

Also, if we have public documentation regarding the OperationName and the intended query findings it might be a good idea to have the link added to the description section as reference.

**Comment by dimmand** [comment]
> Thanks @dimmand.
> 
> Have a couple of very small suggestions:
> 
> In most of the queries we have | where OperationName contains "Update a partner cross-tenant access setting"
> 
> Considering that **contains** is resource intensive can this be replaced by has or == operator in all the queries that has contains.
> Dimitris Response: Thank you for your suggestion, Aprakash13. Regarding contains, I am aware that contains more resources, however the time frame and frequency for running such query is not big, so no issue is expected to occur even for large environments due to the nature of the query "Cross Tenant Access Setitings"
> Also, if we have public documentation regarding the OperationName and the intended query findings it might be a good idea to have the link added to the description section as reference.
There is no public documentation as of now. If one is published, i will update it accordingly.

**Pull request merged**
