### PR TITLE
New workbook

### PR DESCRIPTION
**Pull request by FelixBueltmannBarracuda**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   API version update

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda Some checks are failing for the pr
Can you please check

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda can you please check the checks which are failing

**Comment by v-prasadboke** [comment]
And #7455 and #7453 are one and the same PR can you please close one of it

**Comment by v-atulyadav** [comment]
Hi @FelixBueltmannBarracuda, Respond to the above comments from @v-prasadboke. Thanks

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda any updates

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda any prior updates on the following

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda can you please resolve the validation and remove the merge conflicts

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please update on the following

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please provide your reply on the above comments

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda please provide your feedback on this

**Comment by v-prasadboke** [comment]
Hello @FelixBueltmannBarracuda its been more than a month please reply on the above comments 
or this pr will be closed

**Comment by v-dvedak** [comment]
@FelixBueltmannBarracuda, Since we have not received a response from quite a long, we are closing your PR #7455 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Pull request closed without merging**
