### PR TITLE
Island sentinel solution

### PR DESCRIPTION
**Pull request by daspiker**
Required items, please complete
   
   Change(s):
   - New Solution - first PR

   Reason for Change(s):
   - first PR

   Version Updated:
   - NA

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @daspiker can you share the sample data of this solution

**Comment by daspiker** [comment]
@v-prasadboke  v-prasadboke i have added the two sets of sample data per your request and it has passed validation checks

**Comment by v-prasadboke** [comment]
Thank You for the sample data @daspiker 
Working on this

**Comment by v-prasadboke** [comment]
Hello @daspiker some colums from the sample data are missing please update the sample data as some of the queries from the workbook are failing 
Thank you

**Comment by daspiker** [comment]
hey @v-prasadboke  v-prasadboke i have updated the sample data so all the workbooks should load properly.

**Comment by v-prasadboke** [comment]
image
image
still some columns of "island_user_cl" are missing 

if possible can you share some preview images of workbook

**Comment by daspiker** [comment]
hey @v-prasadboke that data is in the updated sample logs (Island_User_CL.json).   you can see the fields in the logs, the fields in a logs query response and how the workbooks show in the attached.  how are you testing this so i can try and recreate the issue you are seeing on my side?
new_user_sample_log
new_user_sample_log_2
new_user_sample_log_3

i'll work on the preview images.

**Comment by daspiker** [comment]
@v-prasadboke i added two preview images.  not sure if they are in the right location for a solution or not.

**Comment by v-prasadboke** [comment]
Thank you @daspiker 
will look into this again

**Comment by v-prasadboke** [comment]
how are you testing this so i can try and recreate the issue you are seeing on my side? 

- i just ingested the sample data in eco-connector workspace
  and tested the workbook in workbook blade using add workbook option

**Comment by v-prasadboke** [comment]
Hello @daspiker any updates on the following

**Review by v-prasadboke — APPROVED** [review]

**Comment by v-vdixit** [comment]
Hi @daspiker could you please send an email to [AzureSentinelPartners@microsoft.com](mailto:AzureSentinelPartners@microsoft.com) to discuss next steps for packaging and publishing of this solution, Thanks

**Comment by daspiker** [comment]
@v-vdixit i sent an email per your request and it was rejected:
image

**Pull request merged**
