### PR TITLE
Correct exchange environment list parser in Workbook to match the name in the solution

### PR DESCRIPTION
**Pull request by nlepagnez**
Change(s):
   - Change the parser in all Workbooks to be "ExchangeEnvironmentList"

   Reason for Change(s):
   - The name of the parser created by the solution was not the same that the one used in Workbooks

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, Thank you for raising this PR. This PR will be investigated and and will update you before 24 August, 2023.

**Comment by nlepagnez** [comment]
> Hello @nlepagnez, Thank you for raising this PR. This PR will be investigated and and will update you before 24 August, 2023.

Hi @v-prasadboke, Package was rebuilt in V3 as requested.

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, Thank you for committing the changes. We will examine this PR and will update you about the same before 29 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, Please replace the parsers mentioned in input file with .yaml extension which are currently in .txt format.
After making this changes please repackage the solution again with V3.
Also please share the sample data to test the content of these two solutions.
Thanks.

**Comment by nlepagnez** [comment]
> 

The solution is updated as requested. The sample data are already here. I updated the dates for you.

Please, it's a bug on the current deployed solution that block the usage of wokbooks due to a wrong publication. Can you be efficient on your analysis and stop to ask 1 thing each 3 days.

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, Sorry for the inconvenience you have faced. But the format change of parser from .txt to .yaml was implemented few days ago, Thats the reason I asked you to repackage the solution again. 

I custom deployed the maintemplate but due to lack of sample data I was unable to test the content of the solution.
As you have uploaded the sample data I'll continue with my testing and update you about the same before 2 September, 2023.

**Comment by v-prasadboke** [comment]
Hello @nlepagnez, Can we schedule a call as most of the parsers are not working as expected might be due to irrelevant Sample data.
I work in IST time zone and usually available between 2:00 PM to 7:00 PM IST.
If possible can we connect today or tomorrow, Please let us know.
Thanks

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
