### PR TITLE
Mdvm connector updates

### PR DESCRIPTION
**Pull request by anders-alex**
Required items, please complete
   
   Change(s):
   - Fixed issues in M365 MDVM Connector.

   Reason for Change(s):
   - Deployment was not working.

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @anders-alex, Thank you for raising this PR. This PR will be investigated and will update you by August 23, 2023.

**Comment by v-prasadboke** [comment]
Hello @anders-alex , We apologize for the inconvenience. But we are unable to test the data connector owing to technical issues.
I hope you will understand the situation we are in, We will get back to you soonest before 25 August, 2023.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, An error occurred while custom deploying the azuredeploy.json.
image
Please check on to this.

**Comment by anders-alex** [comment]
@v-prasadboke - How did you deploy? If you used the link in the readme, it still references the current outdated deployment file in the master branch.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, I didnt deployed it from the readme file. I custom deployed the ( DataConnectors/M365Defender-VulnerabilityManagement/azureDeploy.json ) using custom deployment.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, Hope you are doing good. I was just waiting for some updates from your side.
Thanks.

**Comment by v-prasadboke** [comment]
Hello there, @anders-alex. I hope everything is fine with you. You must be busy, but could you perhaps please offer us some updates.
Thanks.

**Comment by anders-alex** [comment]
@v-prasadboke - I think you are using the LAW ID instead of the LAW Azure Resource ID. Please see the description of the parameter for more info.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, Hope you are doing well. We just wanted to know if there are any updates on the above requested images.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, It's been a while. Please respond to the requested content above.

**Comment by anders-alex** [comment]
@v-prasadboke - please see below: 
image

**Comment by v-prasadboke** [comment]
Hello @anders-alex, Thank you for sharing the  deployment screenshots. Can you share the functional images as well.

**Comment by v-prasadboke** [comment]
Hello @anders-alex, Please upload the requested images.

**Comment by anders-alex** [comment]
@v-prasadboke - here is a screenshot of the successful runs:
image

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
