### PR TITLE
Adding DCR toolkit and incident tasks workbook

### PR DESCRIPTION
**Pull request by malowe101**
Required items, please complete
   
   Change(s):
   - Added DCR toolkit images, metadata, and template
   - Added incident tasks workbook images, metadata, and template
   - Fixed docusign error that occurred in local repo

   Reason for Change(s):
   - New content

### CODE REVIEW

**Comment by malowe101** [comment]
Have to update template bottom lines. will resubmit

**Review by v-atulyadav — COMMENTED** [review]
Hi @malowe101, please see below comments and act accordingly.

1. can you please add support, author, source, domains for both the workbooks in workbookmetadata.json file. Below is for your reference

image

2. Also change text from `Azure Sentinel` to `Microsoft Sentinel` from DCR-Toolkit.json
image

**Comment by malowe101** [comment]
Change has been made. Please let me know if there are any other issues.

**Comment by v-atulyadav** [comment]
Hi @malowe101, please update your branch from master and push again to resolve conflicts. Thanks

**Pull request closed without merging**
