### PR TITLE
 Update InsecureProtocols.json

### PR DESCRIPTION
**Pull request by Palciny**
Empty ClientAppUsed is not considered Legacy Auth

Required items, please complete

Change(s):

    Changed KQL from
    ClientAppUsed !contains "Browser" and ClientAppUsed !contains "Mobile Apps and Desktop clients"
    to
    ClientAppUsed !in ("Browser", "Mobile Apps and Desktop clients", "")

Reason for Change(s):

    Empty ClientAppUsed is not considered Legacy Auth

Version Updated:

    No - I didn't found version field that would be relevant.

Testing Completed:

   No

Checked that the validations are passing and have addressed any issues that are present:

   Yes

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @Palciny, Please increase the version of insecure protocols in Workbooks metafile
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/WorkbooksMetadata.json

**Comment by Palciny** [comment]
@v-rbajaj thanks for the information. It would be valuable, if this information was mentioned in notes when pull request is generated.

**Comment by Palciny** [comment]
@v-rbajaj done

**Review by v-rbajaj — APPROVED** [review]

**Comment by Palciny** [comment]
@v-sabiraj, @petebryan, @rod-trent do you know any code owner that could review my changes? Thnaks

**Review by v-dvedak — APPROVED** [review]

**Comment by Palciny** [comment]
Hi @v-rbajaj, @v-dvedak, @v-sabiraj can anyone tell me then this update will be available in production?

I have a feeling that some upgrade process is not working correctly. 

image

**Comment by v-rbajaj** [comment]
@Palciny, it will be available till next week

**Pull request merged**
