### PR TITLE
Performance fix

### PR DESCRIPTION
**Pull request by abhishikta-sacumen**
Change(s):
   - Fixed performance issue(updated the configuration parameters in Azure Sentinel/Solutions/Cloudflare/Data Connectors/AzureFunctionCloudflare/main.py)

   Reason for Change(s):
   - To fix data load on AzureFunctionCloudflare

   Version Updated:
   - Version updated to 3.1.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by abhishikta-sacumen** [comment]
@microsoft-github-policy-service agree company="Cloudflare"

**Comment by v-sabiraj** [comment]
Hi @abhishikta-sacumen , can you please fix the branch conflicts? Thanks.

**Comment by v-sabiraj** [comment]
@abhishikta-sacumen , please add the working images for the successful function app execution, thanks.

**Comment by abhishikta-sacumen** [comment]
Hi ,

We are working on it and will update you as soon as the conflicts are
resolved.

Thanks
Abhishikta Ajay

**Comment by abhishikta-sacumen** [comment]
> Hi @abhishikta-sacumen , can you please fix the branch conflicts? Thanks.

@v-sabiraj We have resolved the conflicts.

**Comment by pranav-sacumen** [comment]
Hi @v-sabiraj @v-sabiraj @v-mchatla  What's the update on this?

**Comment by v-sabiraj** [comment]
Hey @abhishikta-sacumen / @pranav-sacumen , still there are branch conflicts, can you please resolve them, thanks.

**Comment by v-sabiraj** [comment]
Hi @abhishikta-sacumen/ @pranav-sacumen , the latest zip (https://github.com/Azure/Azure-Sentinel/raw/906bf617f0f2d9d434935a33a652fc3d5b71cddb/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip) in this PR is missing with .python packages, please add them.

image

**Comment by v-sabiraj** [comment]
@pranav-sacumen , @abhishikta-sacumen, the release notes updated is incorrect, as there are duplicate entries for the versions, can you please check and update correctly? 
Thanks.

**Comment by v-sabiraj** [comment]
HI @pranav-sacumen , @abhishikta-sacumen ,can you please address other comment as well for resolution of the conflicts and adding the python packages in the zip? Thanks.

**Comment by pranav-sacumen** [comment]
@v-sabiraj zip file has been fixed.

**Review by v-mchatla — APPROVED** [review]
Changes look good

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-mchatla** [comment]
@abhishikta-sacumen, @pranav-sacumen 
We missed to inform you that there is no need of repackaging the solution for function app related changes. Can you please raise one more PR to delete the 3.1.0 zip.
Let me know if you need more information on the same.
Thanks

**Comment by ingest0x** [comment]
As of 14:45 utc our Cloudflare Function App no longer executes - it simply does nothing at all. No execution, so no logs. Currently trying to understand whether a new package was pulled down with updated code causing it to break.

**Comment by ingest0x** [comment]
Is this schedule now running very 5 hours??

`{
  "scriptFile": "main.py",
  "bindings": [
    {
      "name": "mytimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *",
      "runOnStartup": false
    }
  ]
}`

**Comment by ingest0x** [comment]
> > @abhishikta-sacumen , please add the working images for the successful function app execution, thanks.
> 
> image
> 
> @v-sabiraj Please find the screenshot of successful execution of the function app.

This screenshot is showing an execution date in 2023... ?

**Pull request merged**
