### PR TITLE
Update Sign-in Burst from Multiple Locations.yaml

### PR DESCRIPTION
**Pull request by ehudk-msft**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by mgladi — APPROVED** [review]

**Review by petebryan — COMMENTED** [review]
Is there a reason for dropping the timestamp entity?

**Comment by ehudk-msft** [comment]
@petebryan the TimeGenerated column is no longer available after the summarize takes place

**Comment by petebryan** [comment]
Thanks @ehudk-msft makes sense. Do you think there is value in using max(TimeGenerated) in the summarize to pull a timestamp through?

**Comment by ehudk-msft** [comment]
@petebryan please close this PR and review this one instead
https://github.com/Azure/Azure-Sentinel/pull/1252

Thanks

**Comment by shainw** [comment]
duplicate of https://github.com/Azure/Azure-Sentinel/pull/1264

**Pull request closed without merging**
