### PR TITLE
Create ActivityLogs_ExtractDomain.md

### PR DESCRIPTION
**Pull request by TheAlistairRoss**
Fixes #

## Proposed Changes

Adding a KQL query to identify user principal names within Azure Activity Logs and extract the domain and top level domain names
  -
  -
  -

### CODE REVIEW

**Review by shainw — CHANGES_REQUESTED** [review]
I would suggest this is simply included as a hunting query versus a sample.

**Review by aprakash13 — APPROVED** [review]
Thanks TheAlistairRoss.

**Comment by NikTripathi** [comment]
@TheAlistairRoss Can you please resolve the comments.

**Comment by shainw** [comment]
@TheAlistairRoss - closing this as it has not had movement, please re-open after you make suggested changes.

**Pull request closed without merging**
