### PR TITLE
Solution Packaging for Endpoint threat protection essentials

### PR DESCRIPTION
**Pull request by v-sabiraj**
test doc- https://microsoftapc.sharepoint.com/:w:/r/teams/EcosystemCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B6A07C45B-E693-4A75-A7AA-B369BAB29C1C%7D&file=Sentinel%20Release%20Checklist%20-V2%20solutions.docx&action=default&mobileredirect=true&share=IQFbxAdqk-Z1Sqeqs2m6spwcARTaI9HlOW93cQ5hmsa1gjM

### CODE REVIEW

**Comment by v-laanjana** [comment]
@v-atulyadav  please review

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-sabiraj , please add status: Available in analytical rules

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-sabiraj , duplicate GUID found please check

image

image

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-sabiraj , the name must not exceed 50 characters. Please check

**Analytical Rules:**
image

image

image

image

**Hunting Query**
image

image

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-sabiraj , the following analytical rule is missing relevanttechniques

image

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-sabiraj , please add skip validations

**Comment by v-atulyadav** [comment]
Hi @v-sabiraj, please resolve branch conflicts. Thanks.

**Comment by v-atulyadav** [comment]
Hi @v-sabiraj, please resolve branch conflicts. Thanks.

**Comment by v-spadarthi** [comment]
@v-atulyadav : Please review the PR and provide your comments. Thanks!

**Review by v-amolpatil — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
