### PR TITLE
ASIM DNS fix for CiscoUmbrella

### PR DESCRIPTION
**Pull request by briandelmsft**
The Umbrella parser is failing as it references Timestamp_s but I have only seen this as Timestamp_t.  Timestamp_t is also referenced elsewhere in the parser.

### CODE REVIEW

**Comment by v-admahe** [comment]
@briandelmsft could you please provide a sample data as per the new changes in datatype of Timestamp so that we can test the query.

Thanks,
Aditi Maheshwari

**Comment by briandelmsft** [comment]
here is some sample data exported from the environment
[ciscoumreblla-sanitized.xlsx](https://github.com/Azure/Azure-Sentinel/files/6670964/ciscoumreblla-sanitized.xlsx)

**Review by oshezaf — APPROVED** [review]

**Comment by oshezaf** [comment]
Thanks @briandelmsft for spotting this!

**Comment by oshezaf** [comment]
Also @v-admahe , @preetikr : please assign anything ASIM to @YaronFruchtmann and me

**Pull request merged**
