### PR TITLE
Updated DataConnector code to handle parameter type changes of Dataminr API.

### PR DESCRIPTION
**Pull request by niralishah-crest**
Change(s):

Updated DataConector code and steps in README.md file
Reason for Change(s):

type of id parameter is changed in API. So handled type conversion in code.
Version Updated:

Yes
Testing Completed:

Yes
Checked that the validations are passing and have addressed any issues that are present:

Yes

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest, Thanks for raising this PR. We will investigate this PR and come back to you with an update by 19 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest, Please update the branch from master. The validation error will show valid errors. 
Thanks.

**Comment by niralishah-crest** [comment]
@v-prasadboke I have updated the branch from master and now all validations have been succeeded
Thanks

**Comment by v-prasadboke** [comment]
Hello @niralishah-crest, can you provide me write access to your branch. Thanks

**Comment by niralishah-crest** [comment]
> Hello @niralishah-crest, can you provide me write access to your branch. Thanks

@v-prasadboke We are unable to provide write access to a particular branch. It's possible to add you as a collaborator in my forked  repository which will give you an edit access to whole repository.

**Comment by v-prasadboke** [comment]
Thats fine. You can invite me as a collaborator so that I can push the required changes

**Comment by niralishah-crest** [comment]
@v-prasadboke I have sent an invite to add you as a collaborator in my repository.
Thanks

**Comment by niralishah-crest** [comment]
@v-prasadboke Can you please provide the ETA for merging this PR?
Thanks

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
