### PR TITLE
Create Detect DNS Obfuscation Using @ Symbol in Email URLs.yml

### PR DESCRIPTION
**Pull request by mjmelone**
Required items, please complete
   
   Change(s):
   - New file

   Reason for Change(s):
   - New detection capability

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the huntings.

**Comment by v-mchatla** [comment]
Hi @aprakash13 
Could you please review the PR and provide your comments.
Thanks

**Comment by v-spadarthi** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by NikTripathi** [comment]
@aprakash13 Please have a look.

**Comment by v-laanjana** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-laanjana** [comment]
Hi @aprakash13 please have look.

**Comment by v-spadarthi** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-laanjana** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-spadarthi** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-laanjana** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-laanjana** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Comment by v-spadarthi** [comment]
Hi @aprakash13
Could you please review the PR and provide your comments.
Thanks

**Review by shainw — APPROVED** [review]

**Pull request merged**
