### PR TITLE
SOLUTION: NXLog FIM (File Integrity Monitoring) (yet again)

### PR DESCRIPTION
**Pull request by jszigetvari-nxlog**
[SOLUTION: NXLog FIM (File Integrity Monitoring)](https://github.com/Azure/Azure-Sentinel/commit/b045dc1897318f13b45e63ec4798d7a8666e1656)

This Pull Request should replace
[Replaces PR 5904](https://github.com/Azure/Azure-Sentinel/pull/6264)
related to the issue:
[NXLog FIM Solution v1.0.0](https://github.com/Azure/Azure-Sentinel/pull/5904)

CHANGES:

- Corrected outdated NXLog documentation URLs
- Handled most of the requests in the open discussion found in the former PR https://github.com/Azure/Azure-Sentinel/pull/5904
- Updated Package 1.0.0.zip to 2.0.1.zip
- Added sample log data
- Generated the package with the V2 packaging script

REASONS FOR CHANGE(S):

- Tried to address the findings raised in the previous PR
- I took over the maintenance tasks from former colleagues who worked on this earlier

VERSION UPDATED:

- Yes, to version 2.0.1

TESTING COMPLETED:

- Need Help / I did not do any actual tests on this, but compared the former PRs of my former colleagues, I only made metadata changes

RAN VALIDATIONS:

- Yes, all validations returned passed

This work is associated with NXLog's Jira Issue IN-161

Signed-off-by: Janos Szigetvari <janos.szigetvari@nxlog.org>

### CODE REVIEW

**Comment by jszigetvari-nxlog** [comment]
@microsoft-github-policy-service agree company="NXLog"

**Comment by v-atulyadav** [comment]
Looking into this

**Comment by jszigetvari-nxlog** [comment]
@v-atulyadav addressed the same problems you raised in PR #8073.

**Comment by v-rbajaj** [comment]
Hi @jszigetvari-nxlog, please add `NXLogFIM_CL` table on this path ` .script/tests/KqlvalidationsTests/CustomTables`, this will solve the failing KQL Validations, thanks

**Comment by jszigetvari-nxlog** [comment]
@v-rbajaj Thanks for the guidance.
I have taken care of all the failing tests.
We should be all set.

**Review by v-dvedak — APPROVED** [review]

**Comment by jszigetvari-nxlog** [comment]
Thanks again for your help!

**Pull request merged**
