### PR TITLE
05 01 2023  as edgescan integration

### PR DESCRIPTION
**Pull request by AcceleryntSecurityDev**
**Change(s):**
- Updated playbook name to match our company's current naming convention
- Updated sentinel connection to use managed identity
- Updated playbook to use Azure Key Vault for Edgescan API token
- Updated documentation to cover aforementioned changes and to match our company's current documentation practices
- Created new directory to match new playbook name
- Deleted old directory with outdated playbook and documentation

**Reason for Change(s):**
- Matching current convention
- Keeping up with MS recommended best practices

**Testing Completed:**
- Yes
image

image

image

### CODE REVIEW

**Comment by AcceleryntSecurityDev** [comment]
@manishkumar1991 Suggested changes have been made, thanks!

**Comment by v-rbajaj** [comment]
Hi @manishkumar1991, can you please provide your feedback on the updates?

**Comment by manishkumar1991** [comment]
> Hi @manishkumar1991, can you please provide your feedback on the updates?

Reviewing the changes

**Review by manishkumar1991 — APPROVED** [review]
Playbooks approved

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
