### PR TITLE
Update AWS_FailedBruteForceS3Bucket.yaml

### PR DESCRIPTION
**Pull request by 0x10F8**
Change(s):
   - Updated AWS_FailedBruteForceS3Bucket.yaml so that query matches intention.

   Reason for Change(s):
   - Query changed to find failed attempts as described. Existing query looked for successful S3 GetObject events - as this was looking for isempty(ErrorCode) and isempty(ErrorMessage) - however to look for fails this should be surrounded by a not().

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Tested in own environment as working - previous query returned successful GetObject events.

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @0x10F8, Please accept license agreement

**Comment by v-prasadboke** [comment]
Hello @0x10F8, Please accept license agreement. Checks has not started yet due to this

**Comment by v-prasadboke** [comment]
Hello @0x10F8, Please accept license agreement.

**Comment by v-prasadboke** [comment]
Hello @0x10F8, Can you please accept license agreement

**Comment by 0x10F8** [comment]
@microsoft-github-policy-service agree

**Comment by v-prasadboke** [comment]
Thanks @0x10F8, For agreeing the license

**Review by v-prasadboke — APPROVED** [review]

**Pull request merged**
