### PR TITLE
Created a workbook for Zoom Report & added as a part of the solution.

### PR DESCRIPTION
**Pull request by samikroy**
Create a workbook for Zoom Report & added as a part of the solution.

### CODE REVIEW

**Comment by rahul0216** [comment]
@v-rbajaj Please work on creating an environment to collect the logs to test the workbook. Reach out to me if you have any query.

**Comment by v-rbajaj** [comment]
Hi @samikroy, can you please fix the query in this workbook?
image

**Comment by samikroy** [comment]
> Hi @samikroy, can you please fix the query in this workbook? image

@v-rbajaj - Thank you for your review. The workbook is built upon the parser which seems to be causing the error.
https://github.com/samikroy/Azure-Sentinel/blob/patch-41/Solutions/ZoomReports/Parsers/Zoom.txt

For more reference, have used the below sample data to test the parser which is providing an error free result.
https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Zoom_CL.json

Could you please let me  know if you are testing it with any other data set, and in that case the sample date need to updated and can update parser accordingly.
The workbook should automatically reflect the changes.

**Comment by v-rbajaj** [comment]
> > Hi @samikroy, can you please fix the query in this workbook? image
> 
> @v-rbajaj - Thank you for your review. The workbook is built upon the parser which seems to be causing the error. https://github.com/samikroy/Azure-Sentinel/blob/patch-41/Solutions/ZoomReports/Parsers/Zoom.txt
> 
> For more reference, have used the below sample data to test the parser which is providing an error free result. https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Zoom_CL.json
> 
> Could you please let me know if you are testing it with any other data set, and in that case the sample date need to updated and can update parser accordingly. The workbook should automatically reflect the changes.

Can you please add a screenshot of the working workbook 

> > Hi @samikroy, can you please fix the query in this workbook? image
> 
> @v-rbajaj - Thank you for your review. The workbook is built upon the parser which seems to be causing the error. https://github.com/samikroy/Azure-Sentinel/blob/patch-41/Solutions/ZoomReports/Parsers/Zoom.txt
> 
> For more reference, have used the below sample data to test the parser which is providing an error free result. https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Zoom_CL.json
> 
> Could you please let me know if you are testing it with any other data set, and in that case the sample date need to updated and can update parser accordingly. The workbook should automatically reflect the changes.

Hi @samikroy, can you please provide a screenshot of the working workbook?
I did try to insert data into Zoom_CL but I am still getting the same error as I shared earlier.

**Comment by samikroy** [comment]
> > > Hi @samikroy, can you please fix the query in this workbook? image
> > 
> > 
> > @v-rbajaj - Thank you for your review. The workbook is built upon the parser which seems to be causing the error. https://github.com/samikroy/Azure-Sentinel/blob/patch-41/Solutions/ZoomReports/Parsers/Zoom.txt
> > For more reference, have used the below sample data to test the parser which is providing an error free result. https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Zoom_CL.json
> > Could you please let me know if you are testing it with any other data set, and in that case the sample date need to updated and can update parser accordingly. The workbook should automatically reflect the changes.
> 
> Can you please add a screenshot of the working workbook
> 
> > > Hi @samikroy, can you please fix the query in this workbook? image
> > 
> > 
> > @v-rbajaj - Thank you for your review. The workbook is built upon the parser which seems to be causing the error. https://github.com/samikroy/Azure-Sentinel/blob/patch-41/Solutions/ZoomReports/Parsers/Zoom.txt
> > For more reference, have used the below sample data to test the parser which is providing an error free result. https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Zoom_CL.json
> > Could you please let me know if you are testing it with any other data set, and in that case the sample date need to updated and can update parser accordingly. The workbook should automatically reflect the changes.
> 
> Hi @samikroy, can you please provide a screenshot of the working workbook? I did try to insert data into Zoom_CL but I am still getting the same error as I shared earlier.

Thank you for your response @v-rbajaj 
Here it is 

image

Query result from Raw Data 

image

Query result from Parser
image

Running the parser in your data set might be helpful.

**Review by v-rbajaj — APPROVED** [review]
looks fine

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
