### PR TITLE
Updated GoogleWorkspaceReports instruction step to get token.pickle

### PR DESCRIPTION
**Pull request by v-maudan**
Fixes #

## Proposed Changes
PFB screenshot of updated instruction **step 1.**
image

### CODE REVIEW

**Comment by v-jayakal** [comment]
@v-maudan , can you please check this PR https://github.com/Azure/Azure-Sentinel/pull/2398 and modify the instructions accordingly?

**Comment by pemontto** [comment]
Why not just output the base64'd pickle string right from this script rather than going `Generate_Google_Pickle_String.py` -> `token.pickle` -> `get_pickle_string.py` -> `b64 pickle string`?

With the added benefit that you're not saving secret material to disk so no need to worry about forgetting to clean it up.

You'd just need to add an import (`import base64`) and this line from get_pickle_string.py:
```python
print("\n\nCopy pickle string and save. Paste it during installation GWorkspace Function App:\n\n{}".format(base64.b64encode(pickle.dumps(creds))))
```

**Comment by pemontto** [comment]
From a user perspective there are still steps missing, I think more explicit instructions would be helpful, something like:

1. Download the `credentials.json` file from you GCP console (screenshot)
2. Add `http://localhost:8081/` under Authorised redirect URIs in GCP (seeing as we're fixing the port to 8081 here)
3. Run `get_pickle_string.py` with the downloaded `credentials.json` in the same path
4. Login with your chosen Google account to get the string required for the `GooglePickleString` Azure Function application setting

`get_pickle_string` can just be

```python
from __future__ import print_function

import base64
import pickle

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/admin.reports.audit.readonly']

def main():
    flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
    creds = flow.run_local_server(port=8081)
    print("\n\nCopy pickle string and save. Paste it during installation GWorkspace Function App:\n\n{}".format(base64.b64encode(pickle.dumps(creds))))           

if __name__ == '__main__':
    main()

```

**Comment by v-maudan** [comment]
> From a user perspective there are still steps missing, I think more explicit instructions would be helpful, something like:
> 
> 1. Download the `credentials.json` file from you GCP console (screenshot)
> 2. Add `http://localhost:8081/` under Authorised redirect URIs in GCP (seeing as we're fixing the port to 8081 here)
> 3. Run `get_pickle_string.py` with the downloaded `credentials.json` in the same path
> 4. Login with your chosen Google account to get the string required for the `GooglePickleString` Azure Function application setting
> 
> `get_pickle_string` can just be
> 
> ```python
> from __future__ import print_function
> 
> import base64
> import pickle
> 
> from google.auth.transport.requests import Request
> from google.oauth2.credentials import Credentials
> from google_auth_oauthlib.flow import InstalledAppFlow
> from googleapiclient.discovery import build
> 
> # If modifying these scopes, delete the file token.json.
> SCOPES = ['https://www.googleapis.com/auth/admin.reports.audit.readonly']
> 
> def main():
>     flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
>     creds = flow.run_local_server(port=8081)
>     print("\n\nCopy pickle string and save. Paste it during installation GWorkspace Function App:\n\n{}".format(base64.b64encode(pickle.dumps(creds))))           
> 
> if __name__ == '__main__':
>     main()
> ```

@pemontto , Thanks., I tried to follow the given steps but getting following issue, Can you please suggest.

image

**Comment by pemontto** [comment]
Did you follow step 2? That could also do with a screenshot...

In your Google Cloud Console -> `APIs and services` -> `Credentials` -> `OAuth 2.0 Client IDs` -> `<your google audit log creds>` -> `Authorised redirect URIs`, add `http://localhost:8081/`.

Client_ID_for_Web_application_–_APIs_and_services_–_Sentinel_logging_–_Google_Cloud_Platform

**Comment by v-maudan** [comment]
> Did you follow step 2? That could also do with a screenshot...
> 
> In your Google Cloud Console -> `APIs and services` -> `Credentials` -> `OAuth 2.0 Client IDs` -> `<your google audit log creds>` -> `Authorised redirect URIs`, add `http://localhost:8081/`.
> 
> Client_ID_for_Web_application_–_APIs_and_services_–_Sentinel_logging_–_Google_Cloud_Platform

 @pemontto , Thanks, I am able to redirect successfully, but getting following issue which seems related google-auth-library-python-oauthlib.[[wsgi_app.last_request_uri has no attribute 'replace' · Issue #69 · googleapis/google-auth-library-python-oauthlib · GitHub](https://github.com/googleapis/google-auth-library-python-oauthlib/issues/69)] 
are you getting this issue?

image

**Comment by pemontto** [comment]
> @pemontto , Thanks, I am able to redirect successfully, but getting following issue which seems related google-auth-library-python-oauthlib.[[wsgi_app.last_request_uri has no attribute 'replace' · Issue #69 · googleapis/google-auth-library-python-oauthlib · GitHub](https://github.com/googleapis/google-auth-library-python-oauthlib/issues/69)]
> are you getting this issue?
> 
> image

Nope haven't come across this. Looks like it's a browser issue.

**Comment by guarismo** [comment]
My workaround to this issue was look for the old version of the quickstart.py file from Google which I found in here:
https://github.com/googleworkspace/python-samples/raw/aacc00657392a7119808b989167130b664be5c27/admin_sdk/reports/quickstart.py
This script will create the token.pickle file expected instead of the token.json

**Comment by v-maudan** [comment]
> My workaround to this issue was look for the old version of the quickstart.py file from Google which I found in here:
> https://github.com/googleworkspace/python-samples/raw/aacc00657392a7119808b989167130b664be5c27/admin_sdk/reports/quickstart.py
> This script will create the token.pickle file expected instead of the token.json

@guarismo, Please check updated [script ](https://github.com/Azure/Azure-Sentinel/blob/8b8bbe63f2aeae6a6f8eec5791d6a1bfdf6bda8e/DataConnectors/GoogleWorkspaceReports/get_google_pickle_string.py)to generate Googlepickle string. Thanks!

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
