### PR TITLE
Fixed ESET Inspect pubID and offerID

### PR DESCRIPTION
**Pull request by msft-sm**
Required items, please complete
   
   Change(s):
   - Fixed ESET Inspect pubID and offerID

   Reason for Change(s):
   - Incorrect pubID and offerID

   Version Updated:
   - No version update required.

   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by v-dvedak** [comment]
@sm-microsoft, the changes for Jamf Protect are already in place. Please check [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Jamf%20Protect). So please revert those changes.

**Comment by v-sabiraj** [comment]
@msft-sm, can you please resolve the conflicts, thanks.

**Comment by msft-sm** [comment]
Conflict resolved. Thanks!

**Comment by v-dvedak** [comment]
Contributor License Agreement is not agreed yet. Please refer [here](https://github.com/microsoft/contributorlicenseagreement) for more details.

**Comment by msft-sm** [comment]
I'm not sure how I'm supposed to write this.
I am raising this PR on behalf of the Sentinel team.

@microsoft-github-policy-service agree

**Comment by v-dvedak** [comment]
@msft-sm, for **BETTER Mobile Threat Defense (MTD)** solution, the changes for replacing Azure Sentinel to Microsoft Sentinel are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip.

**Comment by v-dvedak** [comment]
@msft-sm , for Citrix Web App Firewall solution, the changes for replacing Azure Sentinel to Microsoft Sentinel are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip. Also, I don't think any changes to zip to 2.0.0 are needed.

**Comment by v-dvedak** [comment]
@msft-sm , **ESET Inspect** solution changes looks good

**Comment by v-dvedak** [comment]
@msft-sm , **Netskope** solution changes looks good

**Comment by v-dvedak** [comment]
@msft-sm , for **Orca Security Alerts** solution, the changes for replacing Azure Sentinel to Microsoft Sentinel are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip. Also, I don't think any changes to zip to 2.0.0 are needed.

**Comment by v-dvedak** [comment]
@msft-sm , for **Perimeter 81** solution, the changes for replacing Azure Sentinel to Microsoft Sentinel and offerId are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip. Also, I don't think any changes to zip to 2.0.0 are needed.

**Comment by v-dvedak** [comment]
@msft-sm , for **SecurityScorecard Cybersecurity Ratings**, there is domain category "Security". But this domain category doesn't exist. Please check link - https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/sentinel-solutions.md?msclkid=9a240b52b11411ec99ae6736bd089c4a#microsoft-sentinel-out-of-the-box-content-and-solution-categories. Please remove this category.

**Comment by v-dvedak** [comment]
@msft-sm , **Semperis Directory Services Protector** solution changes looks good

**Comment by v-dvedak** [comment]
@msft-sm , for **Zero Networks** solution, the changes for publisherId are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip. Also, I don't think any changes to zip to 2.0.0 are needed.

**Comment by v-dvedak** [comment]
@msft-sm , for **Zimperium Mobile Threat Defense** solution, the changes for replacing Azure Sentinel to Microsoft Sentinel are done in mainTemplate.json but not in the zip package 2.0.1. Please incorporate those changes in zip. Also, I don't think any changes to zip to 2.0.0 are needed.

**Comment by msft-sm** [comment]
@v-dvedak Thanks for checking.
I've uploaded 2.0.1 for the following packages:
- Better Mobile
- Citrix WAF
- Orca
- Perimeter 81
- ZeroNetworks
- Zimperium

**Comment by msft-sm** [comment]
Also added SecurityScorecard fixed pkg. 
Removed the word "Security" from the Domain Categories.

**Comment by v-dvedak** [comment]
> @v-dvedak Thanks for checking. I've uploaded 2.0.1 for the following packages:
> 
> * Better Mobile
> * Citrix WAF
> * Orca
> * Perimeter 81
> * ZeroNetworks
> * Zimperium

@msft-sm , Please revert the changes in 2.0.0. I still see updates in zip folder 2.0.0 whereas those are not needed. Else we will end up with inconsistency.

**Comment by msft-sm** [comment]
Hi @v-dvedak - Just to make sure I understand your ask, you would like me to add back "Azure Sentinel" and or any other changes I made to each of the (6) packages. Is that correct?

**Comment by v-dvedak** [comment]
As discussed with @msft-sm, closing the PR since she will raise separate new PRs instead of this one.

**Pull request closed without merging**
