### PR TITLE
SecurityBridge Logo Push

### PR DESCRIPTION
**Pull request by frozenstrawberries**
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> After the submission has been made, please look at the Validation Checks.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by frozenstrawberries** [comment]
Hi Team,
Can you please confirm what is the issue here: https://dev.azure.com/azure/43fcaf68-ba3d-474b-97f3-7a1e6fbb5c8d/_apis/build/builds/35806/logs/102

I have checked already built solutions and I can't find any file named '.script/utils/schemas/_ConnectorSchema.json' as mentioned in the logs, in the connector folder
image

**Comment by v-rucdu** [comment]
> Hi Team, Can you please confirm what is the issue here: https://dev.azure.com/azure/43fcaf68-ba3d-474b-97f3-7a1e6fbb5c8d/_apis/build/builds/35806/logs/102
> 
> I have checked already built solutions and I can't find any file named '.script/utils/schemas/_ConnectorSchema.json' as mentioned in the logs, in the connector folder image

Hey @frozenstrawberries, the validation is failing because you are using the parser in the DataType query, instead of the custom log table name. DataType query must use either Syslog, CommonSecurityLog or DATATYPE_NAME_CL, this is used to identify the type of the Connector and apply the respective schema for it in the validations. The error that you are receiving is because the DataType is not matching with this format. 

Please change it as **SecurityBridgeLogs_CL** instead of **SecurityBridgeLogs** in the DataType query.

Thanks!!!

**Comment by frozenstrawberries** [comment]
@v-rucdu  , @v-sabiraj  , 
I have updated the logo with the correct format, I have updated the base query, datatype query, sample query, IsConnectedQuery
 but the validation for the connector is still failing.

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , this may be because the name of datatype mentioned is "SecurityBridgeLogs" rather than SecurityBridgeLogs_CL, please check and update. Thanks.

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , It is syslog type , so refer this [template](https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_Syslog_template.json) for your data connector, thanks.

**Comment by frozenstrawberries** [comment]
@v-sabiraj it is not Syslog type, the table is a custom table and we are fetching the logs from Linux via a custom table configuration.

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries, please update the short link of parser (https://aka.ms/sentinel-SecurityBridgeLogs-parser) in data connector and workbook, thanks.

**Comment by v-sabiraj** [comment]
@frozenstrawberries , Please check and fix the typo Senitnel to Sentinel in read.md file, thanks.

**Comment by frozenstrawberries** [comment]
@v-sabiraj updated

**Comment by v-sabiraj** [comment]
> Hey @frozenstrawberries, please update the short link of parser (https://aka.ms/sentinel-SecurityBridgeLogs-parser) in data connector and workbook, thanks.

@frozenstrawberries , please update this, thanks.

**Comment by v-sabiraj** [comment]
Hey  @frozenstrawberries , the query of data connector is failing, please check and update.
image

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , workbook queries are failing , please check and update , thanks.
image
Failed to resolve column or scalar expression named 'User' , please update , thanks.
image

**Comment by frozenstrawberries** [comment]
This is fixed in the next PR
https://github.com/Azure/Azure-Sentinel/pull/3985#issuecomment-1053902690

**Comment by frozenstrawberries** [comment]
> Hey @frozenstrawberries , the query of data connector is failing, please check and update. image

This is fixed in the next PR

**Comment by frozenstrawberries** [comment]
Won't fix this because the errors are being shows due to parameters dependencies that can be set within the workbook

> Hey @frozenstrawberries , workbook queries are failing , please check and update , thanks. image Failed to resolve column or scalar expression named 'User' , please update , thanks. image

**Comment by v-sabiraj** [comment]
There is an error on deploying a mainTemplate 

image


To rectify the error please change the tier in SolutionMetadata file , the tier is "SecurityBridge" change it to "Partner", thanks.

image

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , the version in SolutionMetadata file is 1.1.8, please change it to "1.0.0" ,thanks.

**Comment by frozenstrawberries** [comment]
> Hey @frozenstrawberries , the version in SolutionMetadata file is 1.1.8, please change it to "1.0.0" ,thanks.

done

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , the workbook preview images should be named as SecurityBridgeThreatDetectionWhite.png, SecurityBridgeThreatDetectionWhite1.png , if preview image is of black background name it as SecurityBridgeThreatDetectionBlack.png, thanks.

**Comment by frozenstrawberries** [comment]
@v-sabiraj updated again

**Comment by v-sabiraj** [comment]
Hey @frozenstrawberries , there are still [Threat_Detection.png](https://github.com/Azure/Azure-Sentinel/pull/3985/files#diff-aed17deda27f12a49236360c579c31aa67603758d1f1521e46146af76aac05a1) and [Threat_Detection_1.png](https://github.com/Azure/Azure-Sentinel/pull/3985/files#diff-a00482a35e5ad3aebb1e4158f0c3c6d8e15b78deb739190cca55e8b8c1439873) you need to remove those as you have already added [SecurityBridgeThreatDetectionWhite.png](https://github.com/Azure/Azure-Sentinel/pull/3985/files#diff-3fdd2a17c54b9a8fd8db2dc51bae8856549284fc349ced3a0930bdb01aaec5dc) and [SecurityBridgeThreatDetectionWhite1.png](https://github.com/Azure/Azure-Sentinel/pull/3985/files#diff-7c10d6dc9a6e3f8834bb98c5633d85eece6f0c9221dfba47566c63f9e7416a7c), thanks.

**Comment by frozenstrawberries** [comment]
@v-sabiraj deleted those files

**Review by v-sabiraj — APPROVED** [review]

**Pull request merged**
