### PR TITLE
FortiNDR-Cloud-Sentinel-Client-API-Update

### PR DESCRIPTION
**Pull request by FortiNDR-Integration**
Required items, please complete
   
   Change(s):
   - Data connector logic changed,
   - Parser for detections updated
   - Workbook and workbook previews updated
   - Detections Sample data updated
 
   Reason for Change(s):
   - Replace Metastream with Fortinet Client API
   - Handle timeout issue when pulling events history

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by FortiNDR-Integration** [comment]
Hi there,

There is one thing we need some help, when I was testing `Deploy to Azure` button in Data connectors, I was able to use the new deploy json `azuredeploy_FortinetFortiNdrCloud_API_FunctionApp.json` to deploy the function app. But after the deployment, in the function app page, there is no functions showing up. Could you please help us with it?

Thanks

**Comment by FortiNDR-Integration** [comment]
Hi @v-prasadboke ,

I have a quick question about the packaging. We have updated the solution version to 3.0.2, but when packaging, it got packed to 3.0.1.zip, and in mainTemplate.json, all the places with the version are showing 3.0.1, could you please help us with it?

Best,
Bobby

**Comment by v-prasadboke** [comment]
Hello @FortiNDR-Integration, Can you share working images of function app

**Comment by FortiNDR-Integration** [comment]
> u share working images of function app

Here are the working images:
Overview:
Overview

OrchestratorWatchdog;
Woking1

SingletonEternalOrchestrator:
Working2

FetchAndSendEventsHistory:
Working3

FetchAndSendDetectionsHistory:
Working4

FetchAndSendEvents:
Working5

FetchAndSendDetections:
Working6

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
