### PR TITLE
Infoblox 2.0.10

### PR DESCRIPTION
**Pull request by sschuur**
Change(s):
   - Update 2.0.9 -> 2.0.10 package

   Reason for Change(s):
   - 2.0.9 mainTemplate.json caused grid tables in workbook to appear blank. Reverted workbook ARM code serializedData to 2.0.7
- Update outdated text as per publishing pointers
- Changed '2.0.9' to '2.0.10' where applicable

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - No

   Testing Completed:
   - Tested in closed enviro

Question - In the data connector page how do I show the workbook as related content? it only seems to find the analytic queries 
image

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @sschuur, please include this `Solutions\Infoblox NIOS\Data\Solution_InfobloxNIOS.json` file in the PR. Thanks

**Comment by sschuur** [comment]
Hi @v-rbajaj, updated the version in `Solutions\Infoblox Cloud Data Connector\Data\Solution_Infoblox.json`

**Review by v-rbajaj — APPROVED** [review]
Looks good.

**Comment by v-rbajaj** [comment]
Hi @sschuur, can you please update the API versions in maintemplate, that will fix the failing ARM ttk validation

**Comment by sschuur** [comment]
Hi @v-rbajaj,
Looked through the failure details. Looks like I should update every `apiVersion` to either  `2022-10-01,` or `2021-12-01-preview.` Is that right? Is one better than the other? Are there any I should not update?

**Comment by sschuur** [comment]
Hi @v-rbajaj, I updated the versions on lines 1028 and 976 in `maintemplate.json`. I did not see any other `/savedsearches` with an `apiVersion` right above or below so hopefully that will work? I don't think I can verify that on my end.

**Comment by v-rbajaj** [comment]
> Hi @v-rbajaj, I updated the versions on lines 1028 and 976 in `maintemplate.json`. I did not see any other `/savedsearches` with an `apiVersion` right above or below so hopefully that will work? I don't think I can verify that on my end.

Thanks @sschuur, that error got fixed. 

To fix the ARM TTK validation failure we need to remove the "blanks" variable (under variables array) from the maintemplate.json file

**Review by v-rbajaj — APPROVED** [review]
looks fine

**Pull request merged**
