### PR TITLE
Amir Katz (RSA/Outseer) changes to the Atlassian Jira data connector Azure function

### PR DESCRIPTION
**Pull request by Amir-Katz-RSA**
Change(s):
   - Fixed logic bugs in get_result() so it does not loop forever in some cases
   - Fixed formatting, added missing spaces, split long lines, fixed typos and grammar
   - Replaced .format() with f-strings
   - Added type hints
   - Removed redundant parentheses
   - In build_signature(), renamed two function arguments to avoid shadowing global variables with same names
   - Replaced 'elif' with 'if' after a 'return'
   - Simplified code in some places
   - Replaced deprecated logging.warn() with logging.warning()

   Reason for Change(s):
   - Code may loop forever in some edge cases
   - Code uses Python 2 constructs (str.format function)
   - Code is not Pythonic in some places

   Version updated:
   - No

   Testing Completed:
   - No, as I cannot deploy this - only Microsoft can

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @devikamehra @rushriva, please provide your feedback. Thanks.

**Comment by v-atulyadav** [comment]
Hi @devikamehra @rushriva, Could you please provide your feedback? Thanks.

**Comment by v-atulyadav** [comment]
Hi @devikamehra @rushriva, please provide your feedback. Thanks.

**Comment by v-atulyadav** [comment]
Hi @v-sabiraj, can you please look into this. Thanks.

**Comment by v-sabiraj** [comment]
@Amir-Katz-RSA, please sign the license by adding the comment "@microsoft-github-policy-service agree [company="{your company}"]", thanks.

**Comment by v-sabiraj** [comment]
@Amir-Katz-RSA , can you please resolve the conflicts, thanks.

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, please check above comments and respond accordingly. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, could you please sign the license by adding the comment "@microsoft-github-policy-service agree [company="{your company}"]" and also resolve the branch conflicts. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, waiting for your response. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, please check above comments and respond accordingly and also have branch conflicts so please resolve them. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, please respond on above comments and also have branch conflicts so please resolve them. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, respond on above comments and also have branch conflicts so please resolve them. Thanks

**Comment by v-atulyadav** [comment]
Hi @Amir-Katz-RSA, please respond on above comments and also have branch conflicts so please resolve them. Thanks

**Comment by v-atulyadav** [comment]
We wanted to check on the status of PR #7333 . PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

**Comment by v-atulyadav** [comment]
We wanted to check on the status of PR https://github.com/Azure/Azure-Sentinel/pull/7333 . PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 2 business days, we will close this PR. Thank you for your cooperation

**Pull request closed without merging**
