### PR TITLE
update query parameter for abnormal security solution

### PR DESCRIPTION
**Pull request by tyng94**
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - updates cases endpoint to use `customerVisibleTime` parameter
   - Updated Abnormalsecurityconn.zip

   Reason for Change(s):
   - polling queries to abnormal soar API unable to return cases.
   - in prior PR, https://github.com/Azure/Azure-Sentinel/pull/3649 code was changed but the the wrong files were placed within the ZIP file. this PR updates the files within

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes
   - Able to deploy with the `WEBSITE_RUN_FROM_PACKAGE=https://github.com/tyng94/Azure-Sentinel/blob/abnormal_1.1/Solutions/AbnormalSecurity/Data%20Connectors/AbnormalSecurityConn.zip?raw=true`

_Note: If updating a detection, you must update the version field._

> After the submission has been made, please look at the Validation Checks.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by tyng94** [comment]
Hey @ritika-msft, I had previously uploaded the wrong code files in the zip file in the previous PR. could you help to approve this PR to update the zip file?

**Comment by tyng94** [comment]
Hey @v-jayakal could we move forward with the PR?

**Comment by v-sabiraj** [comment]
Hey @tyng94 , can see some unexpected error, please check and update , thanks.
image

**Comment by tyng94** [comment]
@v-sabiraj I suspect we are using different versions, and have updated `requirements.txt` to force the same version in our code. Could you check it again? 

If it doesn't work, could you also provide the steps to reproduce? 

I am pointing my `WEBSITE_RUN_FROM_PACKAGE` to 
`https://github.com/tyng94/Azure-Sentinel/blob/abnormal_1.1/Solutions/AbnormalSecurity/Data%20Connectors/AbnormalSecurityConn.zip?raw=true`

**Comment by v-sabiraj** [comment]
Hey @tyng94 , the version for "azure-functions-durable==1.1.3" in requirements.txt but it is not updated in site-packages of zip file it is still "azure_functions_durable-1.1.0.dist-info" ,please check and update ,thanks.

**Comment by tyng94** [comment]
@v-sabiraj updated the packages! restarted my test app and it's working fine too

**Comment by tyng94** [comment]
hi @v-rucdu I have made some changes to the python files to fix a bug but i have a instance tested and running using the zip file in this PR. could we work towards merging this into main?

**Review by v-sabiraj — APPROVED** [review]

**Pull request merged**
