### PR TITLE
Fix Atlassian Confluence API parameter

### PR DESCRIPTION
**Pull request by nevermoe**
Required items, please complete
   
   Change(s):
   - Fix Atlassian Confluence API parameter

   Reason for Change(s):
   - The audit API of confluence takes startDate and endData as a parameter. These two paramters should be in utc timestampe format but the current implementation passed a datetime string. And thus the function app is not retrieving any log from the API. See: https://developer.atlassian.com/cloud/confluence/rest/api-group-audit/#api-wiki-rest-api-audit-get

   Version Updated:
   - N/A

   Testing Completed:
   - Only tested in my personal environment

   Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@nevermoe Please update the changes in zip file. thanks!!!

**Comment by vmanojreddy** [comment]
@nevermoe Please update the changes in zip file. thanks!!!

**Comment by nevermoe** [comment]
@vmanojreddy Hi, I just updated the __init__.py and host.json in the zip file. I don't know if I should update the .python_packages directory in the zip file so I just leave it unchanged.
Thanks!

**Comment by vmanojreddy** [comment]
Tested the data connector by deploying the function app. we see error for function. Please check and update. Thanks.
image

**Comment by nevermoe** [comment]
@vmanojreddy Hi, sorry I didn't test that case. I think I fixed this bug. Would you please test deploy again? Thanks!

**Comment by vmanojreddy** [comment]
@nevermoe Tested the data connector by deploying the function app. Still we are getting error for function. Please check and update. Thanks!!!
image

**Comment by nevermoe** [comment]
@vmanojreddy 
Hi, thank you for testing. I checked the zip file and the __init.py__ is successfully updated. However, from the error message, it indicates that it's using an old version of __init__.py. Is the __init.py__ cached somewhere?

**Comment by nevermoe** [comment]
@vmanojreddy Hi, Any updates here?

**Comment by nevermoe** [comment]
@vmanojreddy Hi, The error code is 404 which indicates there is something wrong with the confluence URL. Are you sure the tested confluence domain is correct? Because I made no change in this function, it's probably some configuration problem. If you can provide more information of the http request/response log, it would be more easy for me to locate the problem.

**Comment by nevermoe** [comment]
@vmanojreddy Hi, do we have any progress here?

**Comment by vmanojreddy** [comment]
Hi @nevermoe sorry for late, I deployed the function app again with proper Confluence URL. Still we are getting error in function. Please check and update. Thanks!!!
image

**Comment by nevermoe** [comment]
@vmanojreddy Hi, the time format written to the funcstatemarkerfile in storage account is in old format. I am doubting that some old version of function apps is running and writing strings to this file. Would you please have a check that all the function apps and the storage accounts deployed previously are deleted and deploy this new version again?

**Comment by nevermoe** [comment]
@vmanojreddy Hi, how's everything going

**Comment by vmanojreddy** [comment]
Hi @nevermoe  I am working and trying to deploy i am facing issues. I will check and update you. thanks!!!

**Comment by nevermoe** [comment]
@vmanojreddy Thank you very much for your help! Looking forward to hearing good news!

**Comment by nevermoe** [comment]
@vmanojreddy Hi, just to check, how's everything going?

**Comment by v-mchatla** [comment]
Hi @nevermoe 
I have tried deleting and redeploying the function app, storage account and dependent resources. As you have applied condition on the past_time in the file _init_.py line:38, that issue was fixed. But we are still getting other errors, please add not null or empty check on the result variable on line 84 and also it would be great if you can add more custom exceptions wherever you feel like breaking, so that it will be easier to identify the issue.

image

**Comment by v-spadarthi** [comment]
Hi @nevermoe 
Could you please resolve the above comments and conflicts as well. Thanks!!

**Comment by v-mchatla** [comment]
Hi @nevermoe 
Do we have any update on the changes requested. Please let us know if you need any clarification
Thanks

**Comment by v-mchatla** [comment]
Hi @nevermoe 
Could you please resolve the comments, so that we can verify and merge your changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @nevermoe
Sorry for multiple follow ups, can you please resolve the comments.
Thanks

**Comment by nevermoe** [comment]
@v-mchatla @v-spadarthi Hi, thank GOD you guys finally come back to review this issue. You got a 404 error so it's likely you entered a wrong confluence url when using the ARM. E.g. for site like https://xxxxxxxxx.atlassian.net/, you should only enter the `xxxxxxxxx` part in `ConfluenceHomeSiteName`.

**Comment by v-mchatla** [comment]
> @v-mchatla @v-spadarthi Hi, thank GOD you guys finally come back to review this issue. You got a 404 error so it's likely you entered a wrong confluence url when using the ARM. E.g. for site like https://xxxxxxxxx.atlassian.net/, you should only enter the `xxxxxxxxx` part in `ConfluenceHomeSiteName`.

Hi @nevermoe,
   We don't have any test data for this to test. Can you please provide some test data if you have, otherwise I will check with team on how to proceed in this case and update you.
Thanks.

**Comment by nevermoe** [comment]
@v-mchatla I don't have any test data. The test should be run with a JIRA service and I think you have tested the JIRA connection successfully before according to this thread.

**Comment by v-mchatla** [comment]
Hi @nevermoe 
Please resolve the conflicts. I will try to test once again and let you know the result.
Thanks

**Comment by nevermoe** [comment]
@v-mchatla Hi, I think the conflicts are resolved.

**Comment by v-mchatla** [comment]
Hi @nevermoe 
Thanks for resolving the conflicts. I will check with my team on how to proceed in this case as we don't have test data to do thorough testing and will update you soon.
Thanks

**Comment by v-mchatla** [comment]
Hi @nevermoe
We are still working on it, will update you soon.
Thanks

**Comment by v-spadarthi** [comment]
@v-mchatla : Please have a look and update

**Comment by v-mchatla** [comment]
Hi @nevermoe 
Sorry for the delay. I will be working on it today and provide you the update.
Thanks

**Comment by v-mchatla** [comment]
Hi @nevermoe,
I tried retesting the function app by redeploying but still getting the same error. I don't have test Confluence URL. If this function app is working fine in your environment, then we are good. Please confirm on the same so that we can proceed further.
image

Thanks

**Comment by nevermoe** [comment]
@v-mchatla Hi, the errors shows **HOMESITENAME.atlassian.net.atlassian.net** is NOT a valid URL and apparently you didn't input a valid HOMESITENAME. I think in some previous comments some guy in your team managed to test it with your own Confluence URL. Anyway, these codes run good in my environment but if you can't test it, I can't help with that.

**Comment by v-mchatla** [comment]
Hi @nevermoe,
Thanks for the confirmation. I will just validate all the files and approve this PR in sometime.
Thanks

**Comment by v-mchatla** [comment]
Hi @nevermoe,
I could see 2 host.json files. Do we need both or just keep which one is required?
Thanks

**Comment by nevermoe** [comment]
@v-mchatla Hi, I removed the unnecessary host.json.

**Comment by v-mchatla** [comment]
Hi @nevermoe,
Thanks for the quick response. Checks are running at my end. Once all the checks are passed, I will approve and merge the PR

**Review by v-mchatla — APPROVED** [review]
Approving the PR

**Pull request merged**
