### PR TITLE
Updated and Combined data connector of Armis Alerts and Armis Activities to ingest activities associated with each alerts.

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Change(s):
   - Combined Armis Alerts and Armis Activities data connector to ingest activities associated with each alerts.

   Reason for Change(s):
   - To make sync of Armis alerts and its associated activities.

   Version Updated:
   - Yes (3.1.0)

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke 
Any update on this PR since it has been raise long time back and we want this merge as early as possible?

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke 
Can you please provide an update on this PR we want this fix/enhance live as early as possible?

**Comment by v-prasadboke** [comment]
Hello Jayesh, Can you please share working images of function app

**Comment by jayeshprajapaticrest** [comment]
image

**Review by v-prasadboke — APPROVED** [review]

**Comment by jayeshprajapaticrest** [comment]
@v-prasadboke 
Thank you for approving the PR. Could you please update the Armis Device Data Connector zip file shorthand URL to point to the master branch instead of a specific branch, as we noticed? In this version, we've upgraded to Python 3.11, and when the customer configured the data connector, we instructed them to use 3.11. However, the current reference points to an older version of the package that uses Python 3.8, which caused the client to encounter the "Module Not Found" error.

**Pull request merged**
