### PR TITLE
Initial Commit For Send-Slack-Message-Webhook

### PR DESCRIPTION
**Pull request by ZLT-ops**
Required items, please complete
   
   Change(s):
   - Adding Send-Slack-Message-Webhook Playbook

   Reason for Change(s):
   - Adding feature

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by lior-tamir** [comment]
Hi @ZLT-ops,  thanks for this contribution!
Is this playbook different then[ this](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Post-Message-Slack) by allowing the Slack user to interactively response from Slack?
Can you also add screenshot of how the Slack message looks like?

If you want this playbook to be shared in the playbook templates tab, please add also the metadata and screenshots. (the screenshot you shared has an issue in the trigger component)
https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide

**Comment by vmanojreddy** [comment]
@anki-narravula Please review playbooks. Thanks.

**Review by lior-tamir — DISMISSED** [review]

**Comment by lior-tamir** [comment]
Only comment is that the card says "close alerts", while you cannot close alerts in Sentinel, you are probably closing the incidents :)

**Comment by lior-tamir** [comment]
Please change the action titles in the card:
1) the card says "close alerts", while you cannot close alerts in Sentinel, you are closing the incidents
2) Please change the term "whitelist" to "allow list" or something similar :)

Please fix the screen shots to show the trigger (currently it shows an "connection" error instead of its title
I added some fixes and metadata so we can show this in playbook templates tab

**Review by anki-narravula — COMMENTED** [review]
Hi @ZLT-ops  - Along with @lior-tamir's feedback, Can you also please take care of the following 

1. Give intuitive default name for Playbook Name ( deployment parameter). like  - "Send Slack Message to Webbook"
2. Can you add information option for deployment parameters. For example, Slack Webhook parameter does not have any information and may be useful for newbies.
3. Use managed identity for Sentinel connection as default option - @lior-tamir  to suggest
4. URLs are missing for deployment buttons in ReadMe

**Comment by vmanojreddy** [comment]
@ZLT-ops please update the requested changes. thanks!!!

**Comment by vmanojreddy** [comment]
@anki-narravula Please check and approve the requested changes. thanks!!!

**Comment by vmanojreddy** [comment]
@anki-narravula Please check and approve the requested changes. thanks!!!

**Comment by ZLT-ops** [comment]
Any updates on the approvals ? @vmanojreddy @anki-narravula

**Comment by vmanojreddy** [comment]
@anki-narravula Please check and approve the requested changes. thanks!!!

**Comment by vmanojreddy** [comment]
@anki-narravula Please check and approve the requested changes. thanks!!!

**Comment by vmanojreddy** [comment]
@anki-narravula Please check and approve the requested changes. thanks!!!

**Comment by v-spadarthi** [comment]
@anki-narravula : Please check and approve the requested changes. thanks!!!

**Comment by v-spadarthi** [comment]
@anki-narravula :  Please check and approve. thanks!!!

**Review by anki-narravula — CHANGES_REQUESTED** [review]
Hi @ZLT-ops  - Sorry for delay in revieing this. Can you please make following changes

1. Sentinel Connection Id is not correct, can you please use the correct one. You can find the right one in the [template ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
image

2. Please use managed identity for sentinel connection and System identity in workflow 

image

image



3. Playbook Name: Default Name must be valid one, so that if someone don't want to change, they can use the same

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
