### PR TITLE
Update ReversingLabs solution to v2.0.1

### PR DESCRIPTION
**Pull request by AaronHoffmannRL**
Required items, please complete
   
   Change(s):
   - Updates workbook "ReversingLabs-CapabilitiesOverview": update KQL queries in workbook to match playbook names as deployed by solution; update guide text

   Reason for Change(s):
   - Typo in workbook query would prevent data from being properly displayed

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
We will review and provide you an update.

**Comment by AaronHoffmannRL** [comment]
@v-spadarthi done, version has been updated

**Comment by v-mchatla** [comment]
Hi @AaronHoffmannRL,
Thanks for making the requested changes will review and share the feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @AaronHoffmannRL,
I will review the changes today and share the feedback.
Thanks

**Comment by AaronHoffmannRL** [comment]
@v-mchatla any updates?

**Comment by v-mchatla** [comment]
> @v-mchatla any updates?

Hi @AaronHoffmannRL,
Sorry for the delay. I have reviewed the content everything looks good except the filenames for the preview images.
Please be consistent with the filename conventions - the dark theme filename should contain the word "black" and the light theme image should contain the word "white".
You can refer the existing filename conventions from [here](https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks/Images/Preview).
Thanks

**Comment by AaronHoffmannRL** [comment]
@v-mchatla thanks for the updates - I've updated the image files as requested

**Comment by v-mchatla** [comment]
Hi @AaronHoffmannRL,
Sorry for multiple requests, I just found that logo file is missing under Images folder please follow [this](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/42Crunch%20API%20Protection/Workbooks/Images/Logo) structure (Workbooks/Images/Logo) to add your logo file. No need to update anything in the metadata file for this.
Thanks

**Comment by AaronHoffmannRL** [comment]
@v-mchatla no worries, I've added the logo file

**Review by v-mchatla — APPROVED** [review]
changes look good

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
