### PR TITLE
On Hold - Added normalization support for DEV-0322_SolarWinds_Serv-U_IOC

### PR DESCRIPTION
**Pull request by oshezaf**
Added sections for imDns and imProcess to the detection rule.

In addition, the following comments on this detection (I did not update based on them, just commenting):

 - "has_any_ipv4" is significantly more performant than "in" for IP Addresses.
 -  Whenever you extract IP addresses from a string, you take the first one, which enables evasion by just having the IoC as the second IP address on in the string.  Something along those lines will solve that:

```
	let IPListDynamic = toscalar(IPList | summarize make_set(IoC));  
	let IPRegexGroup = '([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})';
	imDns
	  | where has_any_ipv4 (DnsResponseName, IPListDynamic)
	  | extend DnsResponseAddresses = extract_all(IPRegexGroup, ResponseName)
	  | extend IPAddresses = set_intersect(IPListDynamic,DnsResponseAddresses)

```	
 - Specific to DnsEvents: IPAddresses can have multiple values, which will not enable a match if only one matches. Same solution as above will help

```
         DnsEvents 
         | where IPAddresses in (IPList)  
```

- AlertDetail, why? It is in the alert description anyways.

### CODE REVIEW

**Comment by oshezaf** [comment]
@oshvartz , @Amitbergman : The validation fails on the new has_any_ipv4() KQL function. Any change the validation script is not up to date?

**Comment by oshezaf** [comment]
@shainw , @aprakash13 : as an update - the analytics team is working on the has_any_ipv4 challenge. Another challenge is the 10K limit. obviously my update is just the last Straw that broke the camel's back. However the multisource pattern is getting to this limit anyways. As discussed in another thread normalization is a solution. I will see what I can do on this one.

**Comment by shainw** [comment]
@oshezaf - What's the plan for this one?

**Comment by oshezaf** [comment]
@shainw : got stuck at the 10K query size limit. We will revisit when ASIM is available by default at each workspace and we can remove some of the original sources covered by ASIM.

**Comment by shainw** [comment]
@oshezaf - Got it, I am going to update the title to On Hold.

**Comment by shainw** [comment]
@oshezaf - Seems like we can update this now?

**Comment by oshezaf** [comment]
True @shainw : I will add it to the short term list.

**Comment by v-mchatla** [comment]
Hi @oshezaf
Can you please review and provide update on this PR.
Thanks

**Pull request closed without merging**
