### PR TITLE
Added the implementation of an API that ingests extensive data of an event

### PR DESCRIPTION
**Pull request by MuhammadAli-snx**
Required items, please complete
   
   Change(s):
   - Integrated an API in the existing SlashNext Security Events for enriching the events with more details. 

   Version Updated:
   - Package version updated to 3.1.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by MuhammadAli-snx** [comment]
Hi @v-atulyadav , 

Please provide an ETA. 

Thanks.

**Comment by v-atulyadav** [comment]
Hi @MuhammadAli-snx,
Please check for below points.
1. I can see some difference in the template from your PR and the template generated by using the v3 tool. Is there any specific reason for this change?
image

2. Release Note file : The latest version should be on top.
image

**Comment by MuhammadAli-snx** [comment]
> Hi @MuhammadAli-snx, Please check for below points.
> 
>     1. I can see some difference in the template from your PR and the template generated by using the v3 tool. Is there any specific reason for this change?
> 
> 
> image
> 
>     2. Release Note file : The latest version should be on top.
> 
> 
> image

1. The SlashNext Security Events version 1.0.0 is published on marketplace. Hence, updated the version of the package and made it 2.0.0 because a new API is integrated in the app which enriches the events with more data. 

2. Fixed: Updated the release notes.

**Comment by MuhammadAli-snx** [comment]
Hi @v-atulyadav ,

Any update on the above would be great.

Thanks.

**Comment by v-atulyadav** [comment]
Hi @MuhammadAli-snx,
I am reviewing this by deploying the template. I will let you know if anything more is needed. Thanks

**Pull request merged**
