### PR TITLE
V1.6.1 Workspace Usage

### PR DESCRIPTION
**Pull request by clivewatson**
Required items, please complete
   
   Change(s):
   - Improve Weekly view and Rules. Add Function Alias view, add DCR view

   Reason for Change(s):
   - updated 

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

### CODE REVIEW

**Comment by CliveWatsonQC** [comment]
Any idea when this will be looked at for release - I have some documentation pending aligned to this? Thanks

**Comment by CliveWatsonQC** [comment]
Hello again.  When is this due to release so I can align articles and documentation release? 

@v-marimanda @v-sabiraj

**Comment by v-marimanda** [comment]
Hi @clivewatson  Workbook query is failing please take a look and please resolve it. thanks!!!

image


image

**Comment by CliveWatsonQC** [comment]
#1 This is working as expected - it's been that way for 3years and many versions - you must first select a Solution in the Table above (circled).
I'll add some code to not display these until selected in the next version (v1.6.2).

***@***.***

#2 This has been tested in 100+ Workspaces - and I've never seen that error before?  It's a minor feature, and will be massively updated in the current preview version I'm working on.


Thanks




Clive Watson
Solutions Director
+44 7496 314624
***@***.***
 
Quorum Cyber Security Limited
​Registered Office: First Floor Suite (West Wing), Verdant, 2 Redheughs Rigg, South Gyle, Edinburgh, EH12 9DQ
​Registered Number: SC510322. Registered in Scotland
From: Manoj ***@***.***>
Sent: 06 September 2022 06:19
To: Azure/Azure-Sentinel ***@***.***>
Cc: Clive Watson ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] - Re: [Azure/Azure-Sentinel] V1.6.1 Workspace Usage (PR #5613)


Hi @clivewatson<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclivewatson&data=05%7C01%7Cclive.watson%40quorumcyber.com%7Cfa44e147a6b545a882fb08da8fc74104%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637980383214710193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=FAYI%2FpK7bnU6SzSMPlaA3ZG93%2FBezhHpa%2FoQLbT55ag%3D&reserved=0> Workbook query is failing please take a look and please resolve it. thanks!!!

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F90677907%2F188551691-210840b6-5fe5-4ff9-aae4-0041ad386253.png&data=05%7C01%7Cclive.watson%40quorumcyber.com%7Cfa44e147a6b545a882fb08da8fc74104%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637980383214866425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=2xLx%2FgrPt7GSBfoEq57AlaVChc0UQpe9pX%2F%2FBvZ8Z2U%3D&reserved=0>

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F90677907%2F188551781-b284fb5a-7629-468c-b1f0-c99331f7c02a.png&data=05%7C01%7Cclive.watson%40quorumcyber.com%7Cfa44e147a6b545a882fb08da8fc74104%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637980383214866425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=2T3y6zJZLjQoB53jIXcwXWgwpQZomYlaU0r2a3RZef8%3D&reserved=0>

-

**Review by v-marimanda — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
