### PR TITLE
Resolved duplicate text in UI definition & Aligned Playbook, Data Connector & Workbook version numbers with rest of Dynatrace solution 

### PR DESCRIPTION
**Pull request by keyoke**
Required items, please complete
   
   Change(s):
- Resolved duplicate text in UI definition
- Aligned Playbook, Data Connector & Workbook version numbers with rest of solution 

   Reason for Change(s):
   - #9787 

   Testing Completed:
   - No functional changes were made

   Checked that the validations are passing and have addressed any issues that are present:
   - TBA

### CODE REVIEW

**Comment by keyoke** [comment]
screenshot of success for playbook where removed unused API connections 
image

**Comment by v-prasadboke** [comment]
Hello @keyoke, No need to align content version with the solution version. Please revert content version changes. 
Also the current changes made wont be visible in 3.0.1 as it is already live. 
I've gone through your issue, Please revert the content version changes and keep only required. I'll repackage the solution and provide you a better UI. 

Thanks.

**Comment by keyoke** [comment]
> Hello @keyoke, No need to align content version with the solution version. Please revert content version changes. Also the current changes made wont be visible in 3.0.1 as it is already live. I've gone through your issue, Please revert the content version changes and keep only required. I'll repackage the solution and provide you a better UI.
> 
> Thanks.

Hi @v-prasadboke, most artifact versions were stuck on 1.0 from the very first release of the solution a lot of changes have been made since then therefore makes sense that we reflect current version which is 3.0.1
Cheers

**Comment by v-prasadboke** [comment]
> > Hello @keyoke, No need to align content version with the solution version. Please revert content version changes. Also the current changes made wont be visible in 3.0.1 as it is already live. I've gone through your issue, Please revert the content version changes and keep only required. I'll repackage the solution and provide you a better UI.
> > Thanks.
> 
> Hi @v-prasadboke, most artifact versions were stuck on 1.0 from the very first release of the solution a lot of changes have been made since then therefore makes sense that we reflect current version which is 3.0.1. As far as I'm aware 3.0.1 is not yet live only staged in preview for testing Cheers

Sorry @keyoke, But this is not how it works. Version is incremented by 0.0.1 for every content according to the content type. 
We can only increment version if there are any modification to the prior artifact.

**Comment by v-prasadboke** [comment]
Hello @keyoke, we are waiting for your reply.

**Comment by v-prasadboke** [comment]
Hello @keyoke, hope you are doing well. Wanted to know if you some updates on above.

**Comment by v-prasadboke** [comment]
Hello @keyoke, It would be very helpful if you can provide some updates on the above

**Comment by v-prasadboke** [comment]
Hello @keyoke we are waiting for your feedback

**Comment by v-prasadboke** [comment]
This is ok now, we can start incrementing the version now onwards.

**Comment by v-prasadboke** [comment]
Hello @keyoke, 
We are waiting for your updates

**Comment by keyoke** [comment]
> Hello @keyoke, We are waiting for your updates

ok what do you need from your last message i assumed we agreed to go with the currently proposed versioning - https://github.com/Azure/Azure-Sentinel/pull/9788#issuecomment-1948134384

**Comment by v-prasadboke** [comment]
Waiting for confirmation from engineering team, if we should keep these version increment changes. 
Will update you as soon as I receive response

**Comment by v-prasadboke** [comment]
Hello @keyoke, can we go for call to discuss about this. 
My mail id is v-prasadboke@micrsoft.com and I work in IST time zone. You can directly ping me on teams as well.

**Comment by v-prasadboke** [comment]
Hello @keyoke can you please respond on the above

**Comment by v-prasadboke** [comment]
Hello @keyoke, Can we go on a call to discuss. 
We cannot increment version of content without any updates to the content

**Comment by keyoke** [comment]
> Hello @keyoke, Can we go on a call to discuss. We cannot increment version of content without any updates to the content

ok i will look at the pending changes and change accordingly when complete will let you know

**Comment by v-prasadboke** [comment]
Thanks @keyoke, Will be waiting for your updates.

**Comment by keyoke** [comment]
> Thanks @keyoke, Will be waiting for your updates.

@v-prasadboke I have rolled back the version numbers on unchanged artifacts

**Comment by v-prasadboke** [comment]
Hello @keyoke, All the playbooks are missing with Postdeployment steps. Please add them to it in the metadata section. 

Due to its unavailability playbook is not visible in the automation blade

**Comment by keyoke** [comment]
> Hello @keyoke, Please update metadata of the Playbooks.

hi @v-prasadboke I have added the additional metadata

**Comment by v-prasadboke** [comment]
Thanks @keyoke, For adding the metadta

**Comment by v-prasadboke** [comment]
Hello @keyoke, Everythings good. 

But can you make default value of playbook to less than 43 characters 
image

Reason being - Playbooks name cannot exceed 64 characters, Limited by content hub. And while creating playbook " **Microsoft.Template-** " gets appended to the playbook name which exceeds 64 characters. 

image

Can you please check all the playbooks and limit the playbook name in defaultvalue parameter 

Thanks

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
