### PR TITLE
Show only ConditionalAccessPolicies that failed

### PR DESCRIPTION
**Pull request by Palciny**
User can have defined lot of policies and original query was showing only 3. New query will filter only on ConditionalAccessPoliciesName that failed during the login process.

Required items, please complete

Change(s):
Added filter that will show only ConditionalAccessPolicies that have failed

Reason for Change(s):
Results were too broad

Version Updated:
Yes

Testing Completed:
Yes

Checked that the validations are passing and have addressed any issues that are present:
Yes

### CODE REVIEW

**Comment by Palciny** [comment]
@petebryan, @v-sabiraj, @aprakash13, @NikTripathi can someone review my changes please? Thanks

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the analytics and provide your feedback. Thanks!

**Review by aprakash13 — DISMISSED** [review]
Thanks @Palciny . The changes look good. 

However, you might want to remove **ConditionalAccessPol0Name**, **ConditionalAccessPol1Name**, **ConditionalAccessPol2Name** from the final summarize statement in the end as we are removing these earlier from the query.

**Comment by Palciny** [comment]
@aprakash13  good catch, forgot to remove it after too many changes. Thanks

Please check new commit.

**Comment by v-spadarthi** [comment]
@aprakash13 : Author addressed your comments please check and provide your approval. Thank you

**Review by petebryan — APPROVED** [review]

**Pull request merged**
