### PR TITLE
SentinelOne | Updated the requirements file for py_310 import errors

### PR DESCRIPTION
**Pull request by saurabh-metron**
Required items, please complete
   
   Change(s):
   - Updated requirements file to include the libraries: `cffi` and `cryptography` 

   Reason for Change(s):
   - When the function runs on Python 3.10 version it fails to import. After some research on the web and Microsoft portal, got to know that adding these libraries will resolve the issue and it does, hence want to publish it for all Customers. 
image

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Comment by saurabh-metron** [comment]
@v-prasadboke any ETA on the review of this please?

**Comment by saurabh-dongare-s1** [comment]
> @v-prasadboke any ETA on the review of this please?

any updates on this?

**Comment by saurabh-dongare-s1** [comment]
> > @v-prasadboke any ETA on the review of this please?
> 
> any updates on this?

@v-prasadboke @v-atulyadav any updates on the review, any ETA?

**Comment by v-prasadboke** [comment]
Hello @saurabh-metron, Please accept license agreement

**Comment by saurabh-metron** [comment]
@microsoft-github-policy-service agree company="SentinelOne"

**Comment by saurabh-metron** [comment]
> Hello @saurabh-metron, Please accept license agreement

Done

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
