### PR TITLE
ACN_CD_CrowdStrikeFalcon_Workbook01

### PR DESCRIPTION
**Pull request by chicduong**
## Proposed Changes

  + CrowdStrike Falcon Endpoint Protection Workbook
  + Screenshots - Black and White
  + WorkbookMetadata Updates

### CODE REVIEW

**Review by v-jayakal — APPROVED** [review]

**Comment by v-jayakal** [comment]
@Amitbergman, @liatlishams  - Can you please review the PR?, Thanks.

**Comment by v-jayakal** [comment]
@Amitbergman, @liatlishams  - Can you please review the PR? Thanks.

**Comment by v-jayakal** [comment]
Can you please change the value of fromTemplateId to "sentinel-CrowdStrikeFalconEndpointProtection" as it should be sentinel-workbookname. Please refer the documentation here https://github.com/Azure/Azure-Sentinel/blob/45310fe6be3cb30cbd8f073443a0c2f9144115fa/Workbooks/README.md

**Review by v-jayakal — CHANGES_REQUESTED** [review]
Can you please change the value of fromTemplateId to "sentinel-CrowdStrikeFalconEndpointProtection" as it should be sentinel-workbookname. Please refer the documentation here https://github.com/Azure/Azure-Sentinel/blob/45310fe6be3cb30cbd8f073443a0c2f9144115fa/Workbooks/README.md

**Comment by v-jayakal** [comment]
@liatlishams and @Amitbergman - As per discussion with @preetikr , this PR will be reviewed and approved by us, Thanks..

**Comment by chicduong** [comment]
> 
> 
> Can you please change the value of fromTemplateId to "sentinel-CrowdStrikeFalconEndpointProtection" as it should be sentinel-workbookname. Please refer the documentation here https://github.com/Azure/Azure-Sentinel/blob/45310fe6be3cb30cbd8f073443a0c2f9144115fa/Workbooks/README.md

updates made

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
