### PR TITLE
Abnormal Security Solution bug fixes and improvements

### PR DESCRIPTION
**Pull request by tyng94**
## Proposed Changes

  - add a origin header to track metrics originating from Sentinel
  - for all messages obtained from threats, filter out messages with received time older than the `stored_datetime` to prevent duplicates
  - for cases, use the firstObserved filter param instead of createTime param

### CODE REVIEW

**Comment by tyng94** [comment]
@preetikr @v-rucdu @v-maudan @v-jayakal @NikTripathi will it be possible to get this PR approved? Anything I can help with to unblock its progress?

**Comment by tyng94** [comment]
Hi @v-jayakal anything i can help with to move the ticket forward?

**Comment by ritika-msft** [comment]
Tested the data connector by deploying the functions. Can see unexpected error for "**SentinelTimerTrigger**" function. Please check this once.
image

**Comment by tyng94** [comment]
> Tested the data connector by deploying the functions. Can see unexpected error for "**SentinelTimerTrigger**" function. Please check this once. image

Hi @ritika-msft is this the link that you used to test the data connector? https://aka.ms/sentinel-abnormalsecurity-azuredeploy

**Comment by ritika-msft** [comment]
Hi @tyng94 , Yes I have deployed the function using https://aka.ms/sentinel-abnormalsecurity-azuredeploy, but as this URL points to the code in master, it will not take the changes you have made in this PR. Therefore post deployment I updated the function configuration "WEBSITE_RUN_FROM_PACKAGE" to point to the zip in your PR, "https://github.com/tyng94/Azure-Sentinel/blob/abnormal_1.1/Solutions/AbnormalSecurity/Data%20Connectors/AbnormalSecurityConn.zip?raw=true". 

once the setting is updated and I restarted the function I can see error for "SentinelTimerTrigger" function, screenshot of which I have provided earlier. Thanks.

**Comment by tyng94** [comment]
> Hi @tyng94 , Yes I have deployed the function using https://aka.ms/sentinel-abnormalsecurity-azuredeploy, but as this URL points to the code in master, it will not take the changes you have made in this PR. Therefore post deployment I updated the function configuration "WEBSITE_RUN_FROM_PACKAGE" to point to the zip in your PR, "https://github.com/tyng94/Azure-Sentinel/blob/abnormal_1.1/Solutions/AbnormalSecurity/Data%20Connectors/AbnormalSecurityConn.zip?raw=true".
> 
> once the setting is updated and I restarted the function I can see error for "SentinelTimerTrigger" function, screenshot of which I have provided earlier. Thanks.

Hi @ritika-msft thanks for the details. Was able to fix the issues and it is not showing any more errors. Could you do a final check and give an approval if it looks ok? thanks!

**Review by ritika-msft — APPROVED** [review]
Tested the function with latest changes. Everything looks good.

**Pull request merged**
