### PR TITLE
File content validation- Azure Sentinel to Microsoft Sentinel

### PR DESCRIPTION
**Pull request by v-amolpatil**
Required items, please complete
   
   Change(s):
   - When there is any change in any file in PR then search for "Azure Sentinel". If found give error and fail the build as we are now using "Microsoft Sentinel".

   Reason for Change(s):
   - Azure Sentinel text is now updated to Microsoft Sentinel so we need to give error in build if any of this text appears in the PR file.

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Comment by v-amolpatil** [comment]
this is in review with Mahesh

**Review by mkchiliveri — APPROVED** [review]
Looks good, approved.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
