### PR TITLE
DNS template spec solution -> DO NOT MERGE

### PR DESCRIPTION
**Pull request by v-marimanda**
…S 1P

Change(s):

See guidance below
Reason for Change(s):
This PR is part of template spec solution migration for solution DNS.

See guidance below
Version Updated:
2.0.0

Required only for Detections/Analytic Rule templates
See guidance below
Testing Completed:
The link for test results is - https://microsoftapc.sharepoint.com/:w:/r/teams/SentinelCATTeam/_layouts/15/Doc.aspx?sourcedoc=%7B1B142443-0D8E-44C8-AB97-0A2ABB7E69FB%7D&file=Sentinel%20Solution%20Migration%20-TemplateSpec%20-%20DNS.docx&action=default&mobileredirect=true

See guidance below
This is an 1P solution.

### CODE REVIEW

**Review by mkchiliveri — DISMISSED** [review]
Looks good, Approved.

**Comment by v-marimanda** [comment]
Hi @v-sabiraj
Can you please get confirmation on this PR merging or closing and act accordingly.
Thanks

**Comment by NikTripathi** [comment]
@v-sabiraj Please have a look.

**Comment by v-mchatla** [comment]
Hi @v-atulyadav, @v-marimanda  
Can you please get it reviewed and merged to master.
Thanks

**Review by v-atulyadav — APPROVED** [review]

**Review by v-sabiraj — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
