### PR TITLE
Fix for #3446

### PR DESCRIPTION
**Pull request by samikroy**
Fix for #3446

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @samikroy, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

**Comment by samikroy** [comment]
> Hey @samikroy, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

Thank you @v-sabiraj , the build error is fixed now.

**Comment by samikroy** [comment]
> > Hey @samikroy, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!
> 
> Thank you @v-sabiraj , the build error is fixed now. Could you please help approving this PR.

**Comment by samikroy** [comment]
@aprakash13 - Could you please help approving this PR.

**Comment by aprakash13** [comment]
This being a playbook related change will let @sreedharande take a look and approve/merge.

**Comment by samikroy** [comment]
@sreedharande - Could you please help merging this. Thank you.

**Comment by samikroy** [comment]
@sreedharande  - Could you please approve this.

**Comment by samikroy** [comment]
@aprakash13 , @shainw , @sreedharande - Request your help to approve & merge this.

**Review by sreedharande — APPROVED** [review]

**Comment by samikroy** [comment]
Thank you for the approval & merge @sreedharande

**Pull request merged**
