### PR TITLE
Create Fortinet-Fortigate-Traffic-parser

### PR DESCRIPTION
**Pull request by stuartjordan**
Required items, please complete
   
   Change(s):
   - New file - function to extract fields from SyslogMessage field in Fortinet Fortigate syslog messages into new columns.

   Reason for Change(s):
   - New function - not present on the repo

   Version Updated:
   - This is version 1.0

   Testing Completed:
   - Ran against my own data

   Checked that the validations are passing and have addressed any issues that are present:
   - No issues

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, can you please move the parser to solution folders of Fortinet-FortiGate, please check and update, thanks.

**Comment by iionescu** [comment]
Hey folks, when do you think you'll have a chance to review this, please?

**Comment by v-sabiraj** [comment]
Hey @iionescu , there is a comment already added to move the parser to the Solution folder, it is directing to the master, please check and update, thanks.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, can you please check and move the file to Parsers folder or the Solutions folder of Fortinet-Fortigate. Thanks.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, can you please check and move the file to Parsers folder or the Solutions folder of Fortinet-Fortigate. Thanks.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, can you please check and move the file to Parsers folder or the Solutions folder of Fortinet-Fortigate so, we can proceed to merge, Thanks.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan @iionescu, can you please check and move the file to Parsers folder or the Solutions folder of Fortinet-Fortigate so, we can proceed to merge, Thanks.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, please move the file to Parsers folder or the Solutions folder of Fortinet-Fortigate.

**Comment by v-sabiraj** [comment]
Hey @stuartjordan, will you please make the requested change, thanks.

**Comment by v-dvedak** [comment]
Hey [@stuartjordan ](https://github.com/stuartjordan), we wanted to check on the status of this PR [Create Fortinet-Fortigate-Traffic-parser](https://github.com/Azure/Azure-Sentinel/pull/4542). It is pending from more than 60 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by v-dvedak** [comment]
Hi @stuartjordan , Since we have not received response from last 7 days, we are closing your [PR](https://github.com/Azure/Azure-Sentinel/pull/4542) per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
