### PR TITLE
Change folder names & add deploy buttons

### PR DESCRIPTION
**Pull request by ThijsLecomte**
Fixes #
Change some folder names
Removed spaces from parent folder
Changed Logic Apps => Playbooks

Added deploy to Azure buttons

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by sreedharande — CHANGES_REQUESTED** [review]
@ThijsLecomte - I've observed you created a new folder "Playbooks" under each individual play book. Ex: Playbooks/Sync-IncidentsWithJIRA/**Playbooks**/Add-JIRALinkComment.json. Please update path as "Sync-IncidentsWithJIRA/**src**/Add-JIRALinkComment.json

**Comment by lior-tamir** [comment]
@sreedharande, the code here includes components of different types: Playbooks and Functions, so it might be more clear to separate them.

Another thought - maybe it worth to offer a linked arm template that has references to all the other templates and will allow to deploy them all in one click.

**Comment by ThijsLecomte** [comment]
@lior-tamir  @sreedharande don't know to what I should change the Playbooks folder? I agree that changing only the Playbooks folder to src doesn't seem right as there is a Function in there aswel...

**Comment by ThijsLecomte** [comment]
@lior-tamir  @sreedharande , any update?

**Comment by sreedharande** [comment]
@ThijsLecomte -LGTM

**Review by sreedharande — APPROVED** [review]

**Pull request merged**
