### PR TITLE
Upload UserDetectPrivilegeGroup

### PR DESCRIPTION
**Pull request by jocarolo**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by jocarolo** [comment]
will you please review and approve the changes, thanks.

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review. Thanks !

**Comment by jocarolo** [comment]
> @aprakash13 : Could you please review. Thanks !

Hi, what do you need for commit?

**Comment by jocarolo** [comment]
> @aprakash13 : Could you please review. Thanks !

Please, could you review?

**Review by aprakash13 — DISMISSED** [review]
Thanks. The query looks good. I have added the Relevant Technique and entity mappings section. However, can you please move the file to the AuditLogs folder instead of the SigninLogs folder and we will get this merged.

**Comment by jocarolo** [comment]
> Thanks. The query looks good. I have added the Relevant Technique and entity mappings section. However, can you please move the file to the AuditLogs folder instead of the SigninLogs folder and we will get this merged.

@aprakash13 Thanks, i moved the file to AuditLogs. Please you can review? Regards

**Comment by jocarolo** [comment]
> > Thanks. The query looks good. I have added the Relevant Technique and entity mappings section. However, can you please move the file to the AuditLogs folder instead of the SigninLogs folder and we will get this merged.
> 
> @aprakash13 Thanks, i moved the file to AuditLogs. Please you can review? Regards

Some news about this? best regards

**Comment by jocarolo** [comment]
> > > Thanks. The query looks good. I have added the Relevant Technique and entity mappings section. However, can you please move the file to the AuditLogs folder instead of the SigninLogs folder and we will get this merged.
> > 
> > 
> > @aprakash13 Thanks, i moved the file to AuditLogs. Please you can review? Regards
> 
> Some news about this? best regards

Hi, some news?

**Comment by v-spadarthi** [comment]
@aprakash13 : Could you please review and let us know.

**Comment by aprakash13** [comment]
> > > > Thanks. The query looks good. I have added the Relevant Technique and entity mappings section. However, can you please move the file to the AuditLogs folder instead of the SigninLogs folder and we will get this merged.
> > > 
> > > 
> > > @aprakash13 Thanks, i moved the file to AuditLogs. Please you can review? Regards
> > 
> > 
> > Some news about this? best regards
> 
> Hi, some news?

Thanks for your patience on this. I still see the file location as signinlogs folder instead of AuditLogs folder. Wondering if I am missing something here.
image

**Comment by v-marimanda** [comment]
@jocarolo  Can you please take a look and address  the above comment

**Comment by jocarolo** [comment]
The is moved but i can't aprovved the movement

> @jocarolo Can you please take a look and address the above comment

Moving UserDetectPrivilegeGroup to AuditLogs

**Comment by v-marimanda** [comment]
Hi @aprakash13 Please rereview and provide your sign off. thanks!!!

**Review by jocarolo — COMMENTED** [review]
Please can you aprove the movement?

**Comment by v-marimanda** [comment]
Hi @aprakash13 Please check once provide your sign off. thanks!!!

**Comment by jocarolo** [comment]
Hi,

Please guys, you can finish this task? i moved the file 11 days Ago.

**Review by shainw — APPROVED** [review]

**Pull request merged**
