### PR TITLE
Updating Detection queries with Resource Specific logs for Azure Firewall

### PR DESCRIPTION
**Pull request by shabaz-github**
Required items, please complete
   
   Change(s):
   - Updated following queries with Resource specific logs for Azure firewall

ActiniumFeb2022.yaml
IridiumIOCs.yaml
SOURGUM_IOC.yaml
ZincJan272021IOCs.yaml
PHOSPHORUSMarch2019IOCs.yaml
KnownPHOSPHORUSDomainsIP-October2020.yaml
POLONIUMIPIoC.yaml
GalliumIOCs.yaml
NICKELIOCsNov2021.yaml
STRONTIUMJuly2019IOCs.yaml
ChiaCryptoMining.yaml
DEV-0322_SolarWinds_Serv-U_IOC.yaml
Dev-0530_July2022.yaml
BariumDomainIOC112020.yaml 
BariumIPIOC112020.yaml
CERIUMOct292020IOCs.yaml
Mercury_Log4j_August2022.yaml
NOBELIUM_DomainIOCsMarch2021.yaml
NOBELIUM_IOCsMay2021.yaml
Solorigate-Network-Beacon.yaml
ThalliumIOCs.yaml
WSLMalwareCorrelation.yaml 

   Reason for Change(s):
   - Updates the queries to support new resource specific logs on Azure Firewall

   Version Updated:
   - Yes
   - All files have been updated with new version.

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@aprakash13 : Please review the detections and provide your comments. Thanks!

**Review by aprakash13 — COMMENTED** [review]
@shabaz-github has reached out and we are discussing this PR today. Based on the discussions will move it forward.

**Review by aprakash13 — DISMISSED** [review]
Thanks @shabaz-github

**Comment by shabaz-github** [comment]
Hello Meena,

This has now been fixed. All checks have passed again. Please help with merging.

***@***.***

Thanks,

Shabaz Shaik
Program Manager II
***@***.******@***.***>

Azure Network Security CxE Team

[MSFT_logo]

Learn more about Azure Network Security: AzNetSecNinja<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSecNinja&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x7pX1ClCd%2FxOdsAQBURWqHZffzwhjpDwKaIOa8mSR0I%3D&reserved=0> | Blogs<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Faznetsecblog&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ds2PZxqSrv%2BhZP6KWQtEnpez4e5Fk2%2Bp93regtpzgQA%3D&reserved=0> | GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSec&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B%2BzgI6B%2BKn71zLl90yOz%2FDHWad9GPxTE6InKhOaN1Os%3D&reserved=0> | Portal<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSecSPO&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jU6AA%2BHwwTCpvsvjTvUBDygg2ILHKpbojHjLrcNMAf8%3D&reserved=0> | Private Community<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fpages%2Fresponsepage.aspx%3Fid%3Dv4j5cvGGr0GRqy180BHbR-kibZAPJAVBiU46J6wWF_5URDFSWUhYUldTWjdJNkFMVU1LTEU4VUZHMy4u&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CgiQFR3bi0kg%2Br8qDn41RdT9TLFV12junCJ%2BoQIajZY%3D&reserved=0>

**Comment by v-mchatla** [comment]
Hi @shabaz-github,
Please resolve the conflicts.
Thanks

**Comment by shabaz-github** [comment]
Hello Meena,

All conflicts have been resolved.

Thanks,

Shabaz Shaik
Program Manager II
***@***.******@***.***>

Azure Network Security CxE Team

[MSFT_logo]

Learn more about Azure Network Security: AzNetSecNinja<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSecNinja&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x7pX1ClCd%2FxOdsAQBURWqHZffzwhjpDwKaIOa8mSR0I%3D&reserved=0> | Blogs<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Faznetsecblog&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ds2PZxqSrv%2BhZP6KWQtEnpez4e5Fk2%2Bp93regtpzgQA%3D&reserved=0> | GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSec&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B%2BzgI6B%2BKn71zLl90yOz%2FDHWad9GPxTE6InKhOaN1Os%3D&reserved=0> | Portal<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzNetSecSPO&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jU6AA%2BHwwTCpvsvjTvUBDygg2ILHKpbojHjLrcNMAf8%3D&reserved=0> | Private Community<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fpages%2Fresponsepage.aspx%3Fid%3Dv4j5cvGGr0GRqy180BHbR-kibZAPJAVBiU46J6wWF_5URDFSWUhYUldTWjdJNkFMVU1LTEU4VUZHMy4u&data=05%7C01%7Cshabazshaik%40microsoft.com%7C1a5733189e9f46acbaf108da3a84f027%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637886639913152705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CgiQFR3bi0kg%2Br8qDn41RdT9TLFV12junCJ%2BoQIajZY%3D&reserved=0>

**Comment by v-spadarthi** [comment]
We will check with concern team let you know the update.

**Comment by v-spadarthi** [comment]
We are checking with team and let you know the update.

**Comment by v-spadarthi** [comment]
Ajit Prakash approved these changes previously

**Comment by v-spadarthi** [comment]
@shabaz-github : Please resolve the conflicts. Thanks!

**Comment by shabaz-github** [comment]
@v-spadarthi All conflicts have been resolved. Yes, this has already been reviewed and approved before. Please help with merging.

**Comment by v-spadarthi** [comment]
@shabaz-github : Please resolve the conflicts. Thanks

**Comment by v-atulyadav** [comment]
Hi @shabaz-github, there are still conflicts, could you please resolve them. Thanks

**Comment by v-sabiraj** [comment]
Hey @shabaz-github, this is regarding the conflicts that are there in the branch. Actually the Analytic rules are moved to particular solution folders and the query changes should be done at that location from solution folder. Please check and let us know if you face any difficulties, thanks.

**Comment by shabaz-github** [comment]
@v-sabiraj @v-spadarthi @v-atulyadav All conflicts have been resolved now as well has the detections have been updated in the new location (solutions). Please help with merging this PR as the changes were already approved.

**Comment by v-atulyadav** [comment]
Hi @shabaz-github, thank you for this fix. We will check and update you soon.

**Review by aprakash13 — APPROVED** [review]
Thanks @shabaz-github for the additions.

**Comment by aprakash13** [comment]
@v-atulyadav Please feel free to merge if the detections are in the right solutions. Thanks.

**Pull request merged**
