### PR TITLE
Imperva Cloud WAF content update

### PR DESCRIPTION
**Pull request by spsocprime**
Required items, please complete
   
   Change(s):
   - Rule severity adjusted
   - Updated query time for High severity rules
   - contains -> has_any
   - fixed confusing description

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Hey @spsocprime please resolve the conflicts, thanks.

**Review by aprakash13 — APPROVED** [review]
Changes looks good. Thanks.

**Comment by v-sabiraj** [comment]
Hey @spsocprime, this branch has conflicts that must be resolved, can you please resolve so we can merge, thanks.

**Comment by v-sabiraj** [comment]
Hey @spsocprime, this branch has conflicts that must be resolved, can you please resolve so we can merge, thanks.

**Review by aprakash13 — APPROVED** [review]
Thanks.

**Comment by v-sabiraj** [comment]
@spsocprime, can you please resolve conflicts so we can merge, thanks.

**Comment by spsocprime** [comment]
Please refer to new PR:
https://github.com/Azure/Azure-Sentinel/pull/5357

**Pull request closed without merging**
