### PR TITLE
Sentinel4github Updates

### PR DESCRIPTION
**Pull request by felickz**
##  Change(s):

### Sentinel4github Solution 
- Updates for Go Live

#### Updates
 - [x] Workbook - Rename GitHub Advanced Security Workbook json from `workbook/update-to-workbook-1.json` to `GitHubAdvancedSecurity.json`
 - [x] Workbook -  Rename `GithubSecurity.json` to `GitHubSecurity.json`
 - [x] Data Connector - Webhook Instructions include GitHub Advanced Security specific events
 - [x] Parser - Rename `GithubSecretScanningData` to `GitHubSecretScanningData` - case sensitive in KQL
- [x] Logo - Moved the [GitHub icon svg](https://github.com/Azure/Azure-Sentinel/blob/46bac4203a2fa02b4b9f256072479848e3bf16ad/Logos/GitHub.svg) into @repo/Logos from 
 [existing location](https://securityinsights.hosting.portal.azure.net/securityinsights/Content/1.0.02074.135-220906-074901/Workbooks/Images/Logos/GitHub.svg) 

####  Publish Step (TODO: review if any of these can be done in json)
-  SentinelTeam - per our understanding these tasks must be done during publish. Let us know if these updates are needed in repo!
- [ ] Content Hub -  Publish workbooks using new naming `GitHubSecurity.json` and `GitHubAdvancedSecurity.json` (currently just known as `workbook`)
- [ ] Content Hub - Add the [GitHub icon svg](https://securityinsights.hosting.portal.azure.net/securityinsights/Content/1.0.02074.135-220906-074901/Workbooks/Images/Logos/GitHub.svg) to both workbooks and the overall solution in the Content hub
- [ ] Content Hub - Enhance workbook Description on the content hub for `GitHubAdvancedSecurity.json` to: `Visualize GitHub Advanced Security alerts for Code Scanning, Secret Scanning, and Dependabot.`
- [ ] Content Hub - Enable Azure Gov flag for deployment
- [ ] Connector - Webhook instructions in UI experience (currently deep links to repo doc) - Post Deployment Steps / Step 2 / # 5 ... edit text to be: Subscribe for events (include `Code scanning alerts`, `Repository vulnerability alerts`, and `Secret scanning alerts`)  and Click on "Add Webhook"
- [ ] Marketplace - can you confirm this will remain the [link to the Sentinel4GitHub solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftcorporation1622712991604.sentinel4github?tab=overview) in both public beta/GA
- [ ]  Gallery - is the intention that we have content living @ [parsers](https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/GitHub)/[hunting](https://github.com/Azure/Azure-Sentinel/tree/master/Hunting%20Queries/GitHub)/[workbooks](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/GitHubSecurityWorkbook.json)/[detections](https://github.com/Azure/Azure-Sentinel/tree/master/Detections/GitHub) and inside the [GitHub solution](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/GitHub) or is this best combined?
- [ ] Solution - Description should include some additional information about the GitHub Advanced Security support via WebHooks:  `The GitHub audit log connector provides the capability to ingest GitHub logs into Microsoft Sentinel. The GitHub (using webhooks) connector further provides the ability to ingest GitHub events including GitHub Advanced Security alerts into Microsoft Sentinel.   Please note - this solution works only with GitHub enterprise license.` 

 ##  Reason for Change(s):
   - Final review of sentinel4github Advanced Security / webhook integration

 ###  Version Updated:
   - N/A
   
 ### Testing Completed:
   - N/A

 ###  Checked that the validations are passing and have addressed any issues that are present:
   - N/A

### CODE REVIEW

**Comment by NikTripathi** [comment]
@felickz  Let us know once it is ready for review.

**Comment by felickz** [comment]
Hi @NikTripathi ready for review here, working with @prtanej  on this one.

**Comment by v-atulyadav** [comment]
Hi @felickz , Workbook.json was added recently by @AlexDeMichieli with PR# https://github.com/Azure/Azure-Sentinel/pull/5764, but I can see in this PR you are removed this workbook file can we proceed with merging this PR?.

**Comment by felickz** [comment]
> Hi @felickz , Workbook.json was added recently by @AlexDeMichieli with PR# #5764, but I can see in this PR you are removed this workbook file can we proceed with merging this PR?.

`update-to-workbook-1.json` was actually the latest updated version of `workbook.json`.  In this PR I renamed `update-to-workbook-1.json` to `GitHubAdvancedSecurity.json`

Since it was showing up in the content hub as just `workbook` - we renamed the file to match the expected title in Content Hub.  The display name in the hub should be `GitHub Advanced Security`
image

**Review by v-atulyadav — APPROVED** [review]

**Review by v-sabiraj — APPROVED** [review]

**Review by NikTripathi — APPROVED** [review]

**Pull request merged**
