### PR TITLE
Fixing bytes ecoding.

### PR DESCRIPTION
**Pull request by NikitaGrunskyHolm**
Fixing `bild_signature` function.

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello @NikitaGrunskyHolm, Please update function app zip too

**Comment by NikitaGrunskyHolm** [comment]
> Hello @NikitaGrunskyHolm, Please update function app zip too

Done.

**Review by v-prasadboke — APPROVED** [review]

**Comment by NikitaGrunskyHolm** [comment]
@v-prasadboke Hi! Do you know when my changes will be available for customers?

**Comment by NikitaGrunskyHolm** [comment]
@v-prasadboke Hello! The updated file `Solutions/HolmSecurity/Data Connectors/AzureFunctionHolmSecurityAssets.zip` is not downloads with link `https://aka.ms/sentinel-holmsecurityassets-functionapp`. How I can update it?

**Comment by v-prasadboke** [comment]
Hello @NikitaGrunskyHolm, The link works. I tried it out. For further more queries you can ping me on teams. My teams handle is v-prasadboke@microsoft.com 

As this is a merged PR, I wont be able to keep it in front of my eyes everytime. 

Thanks, 
Prasad Boke

**Pull request merged**
