### PR TITLE
Updates two AzureActivity based rules to look for data in correct format

### PR DESCRIPTION
**Pull request by Korving-F**
Required items, please complete
   
   Change(s):
   - [Detections/AzureActivity/RareRunCommandPowerShellScript.yaml](https://github.com/Azure/Azure-Sentinel/compare/master...Korving-F:azure_vm_run_command_rule_correction?expand=1#diff-f610c75458e897a40d80fe2ad7d6115c72bf86309e4c7e58057a8d11431858ad)
   - [Detections/MultipleDataSources/RunCommandUEBABreach.yaml](https://github.com/Azure/Azure-Sentinel/compare/master...Korving-F:azure_vm_run_command_rule_correction?expand=1#diff-6a878ab32344fe44512e8c33f28bc4f0dfb4f4f6620d1edc4770a59b8e70073f)

   Reason for Change(s):
   - Rules will never find data since values seems to be formatted different (uppercase vs. lowercase / returned value change)

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - Versions changed

## Screenshots
image002
image003
image004

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks!!

**Comment by vmanojreddy** [comment]
@aprakash13 Please review Detections. Thanks!!

**Comment by Korving-F** [comment]
@vmanojreddy bump ^_^
The current rules will never trigger due to case sensitivity / incorrect return value. 
Do you prefer the suggested correction or using the `=~` operator?

**Review by aprakash13 — APPROVED** [review]
Thanks @Korving-F

**Pull request merged**
