### PR TITLE
Azure Active Directory Identity Protection

### PR DESCRIPTION
**Pull request by v-prasadboke**
Change(s):
     - New Schema for Data connector: template_AzureActiveDirectoryIdentityProtection

  Version Updated:
   -  2.0.4
   - Resolved PR #7215

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @v-prasadboke, please remove blank space. Thanks.

image

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, data connector not visible in manage section also check count and number of contents.

image

image

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, please check comments above.

**Comment by v-atulyadav** [comment]
Hi @v-prasadboke, please respond on comments above. Thanks.

**Comment by v-prasadboke** [comment]
Hello @v-atulyadav as these solution are 1p conenctors there is an issue with the links which are present in the data connector description

**Comment by v-atulyadav** [comment]
Looking into this

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
