### PR TITLE
Modified PR for creation of RidgeSecurity Sentinel Solution

### PR DESCRIPTION
**Pull request by YiY-Xu**
Change(s):

- Solutions/RidgeSecurity/Analytic Rules/RidgeSecurity_Risks.yaml
- Solutions/RidgeSecurity/Analytic Rules/RidgeSecurity_Vulnerabilities.yaml
- Logos/Ridge-Security-R-Background.svg
- Solutions/RidgeSecurity/Data Connectors/RidgeSecurity.json
- Sample Data/RidgeSecurity_RawLogs.txt
- Sample Data/RidgeSecurity_IngestedLogs.csv
- Sample Data/RidgeSecurity_Schema.csv
- Solutions/RidgeSecurity/Package/3.0.0.zip
- Solutions/RidgeSecurity/Package/createUiDefinition.json
- Solutions/RidgeSecurity/Package/mainTemplate.json
- Solutions/RidgeSecurity/ReleaseNotes.md
- Solutions/RidgeSecurity/SolutionsMetada.json
- .script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json

Reason for Change(s):
Creation of RidgeSecurity Sentinel Solution

### CODE REVIEW

**Comment by YiY-Xu** [comment]
@microsoft-github-policy-service agree [company=“RidgeSecurity"]

**Comment by v-rusraut** [comment]
Hi @YiY-Xu,

Thank you for raising Pull Request with us! We will review it till 31 Oct 2023.

**Comment by v-rusraut** [comment]
Hi @YiY-Xu,

Please resolve below validation error.

- There is query validation  error in Analytical rule and Dataconnector file.


Please resolve the query error in Analytical rule and data connector.



-   There is product branding validation error.



Please add keyword Microsoft before Sentinel keyword and repackage the solution.
image

Thanks

**Comment by YiY-Xu** [comment]
Hi v-rusraut,

I have updated the code accordingly. But I still see two errors when I rebuild the package:
1.     [-] IDs Should Be Derived From ResourceIDs (66 ms)                                                                  
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
2.   Template Should Not Contain Blanks                                                                                    
    [-] Template Should Not Contain Blanks (109 ms)                                                                     
        Empty property:  "" Line: 91, Column: 49   

But I have no clue where to dive into. Please advice.

**Comment by v-rusraut** [comment]
Hi @YiY-Xu,

I verified that you resolved Analytical rule query error, but  dataconnector query error not resolved yet.



Please resolve dataconnector query error and repackage the solution, I will resolve other validation errors.

Thanks

**Comment by YiY-Xu** [comment]
@v-rusraut , I'm sorry I missed the KQLs in the data connector. Have fixed them and pushed again.

**Comment by v-rusraut** [comment]
Hi @YiY-Xu,
As this is partner supported solution, you need to update support information in SolutionMetadata file and repackage the solution.

image

Refer below sample SolutionMetadata file of partner solution.
image


Please copy and paste below line in comment box to accept Contributor License Agreement.
@microsoft-github-policy-service agree company="RidgeSecurity"

Thanks

**Comment by YiY-Xu** [comment]
@microsoft-github-policy-service agree company="RidgeSecurity"

@v-rusraut I have updated the branch according to your comments.

**Comment by v-rusraut** [comment]
Hi @YiY-Xu,

There is validation issue due to incorrect SolutionId format.
image

Solution Id Expected format : publisherID.offerID. and it must be in lowercase.

Please update it and repackage the solution.

Thanks

**Comment by YiY-Xu** [comment]
@v-rusraut , I followed your example last time to update the offerID. I have updated it into small cases.

**Comment by v-rusraut** [comment]
Hi @YiY-Xu ,
Please work on below points:

- Offer ID added by you is incorrect .please refer below link for offer Id format.
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions#author-and-publish-a-solution-offer 
Instead of solution keyword you need to add your solution name (RidgeSecurity)
for ex : microsoft-sentinel-ridgesecurity
image

- Also remove additionalRequirementBanner property from dataconnector, becasue it's value is empty.
image

- After that please  repackage the solution.

Thansk

**Comment by YiY-Xu** [comment]
@v-rusraut I have updated accordingly. However, I still see one error left, but I can't find any clues. 
  IDs Should Be Derived From ResourceIDs                                                                                
    [-] IDs Should Be Derived From ResourceIDs (55 ms)                                                                  
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "contentProductId" must use one of the following expressions for an resourceId property:              
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid
        Property: "id" must use one of the following expressions for an resourceId property:                            
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid

**Comment by YiY-Xu** [comment]
@v-rusraut can we have an update on this?

**Comment by v-rusraut** [comment]
Looks good.

**Review by v-rusraut — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
