### PR TITLE
SOLUTION: NXLog FIM (File Integrity Monitoring) - preparing for publi…

### PR DESCRIPTION
**Pull request by jszigetvari-nxlog**
SOLUTION: NXLog FIM (File Integrity Monitoring) - preparing for publishing

CHANGES:

- Changed the SolutionId/OfferId value in accordance with the requirements of
  the release process

REASONS FOR CHANGE(S):

- The release process has format requirements for the OfferId, and it also has
  to match with the value in mainTemplate.json

VERSION UPDATED:

- No, just updated the SolutionId value EVERYWHERE, where applicable

TESTING COMPLETED:

- No, as I did not touch anything else

RAN VALIDATIONS:

- No, as no other changes were made

This work is associated with NXLog's Jira Issue IN-161

Signed-off-by: Janos Szigetvari <janos.szigetvari@nxlog.org>

### CODE REVIEW

**Review by v-atulyadav — COMMENTED** [review]
Hi @jszigetvari-nxlog, Normally, a zip file contains only MainTemplate and createUiDefinition files, but in 2.0.0, I see another file. 
image

In your PR, please include the attached version `2.0.0`
[2.0.0.zip](https://github.com/Azure/Azure-Sentinel/files/11935485/2.0.0.zip)

Alos update offerid in `SolutionMetadata` file. 
Thanks

**Comment by jszigetvari-nxlog** [comment]
@v-atulyadav Thanks for the super-fast feedback! I have addressed the things you highlighted.
The zip files was created by my former colleague, he was likely using a Mac when creating the archive file.

**Comment by v-atulyadav** [comment]
Hi @jszigetvari-nxlog, there is a difference between maintemplate and maintemplate inside 2.0.1. Please include same maintemplate inside zip also.
image

**Comment by jszigetvari-nxlog** [comment]
@v-atulyadav v2.0.0 was created by a former colleague of mine, whose work I took over after he left. I had to finish up his unfinished PR 5904, in PR 8022. I opted to call my version v2.0.1 as I did not want to overwrite the "past" or disrespect his work. I had to change that particular part you highlighted in v2.0.1, because the tests were failing, as that particular field/column seems to have ceased to exist.
Either way, I have updated it as you asked.

**Comment by v-atulyadav** [comment]
Hi @jszigetvari-nxlog, can we connect over call to resolve this? please schedule a call; v-atulyadav@microsoft.com is my mail id, we are working in IST TimeZone.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
