### PR TITLE
Update to Azure Sentinel Cost Workbook

### PR DESCRIPTION
**Pull request by kenrward**
Required items, please complete
   
   Change(s):
   - Updated Billable query to create/edit categories to reduce the number of tables going into the 'other' category.  

   Reason for Change(s):
   - Too many tables in the other category was causing customer confusion

   Version Updated:
   - N/A

   Testing Completed:
   - Need Help (works in CyberSecuritySoc Sentinel instance)

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Review by kenrward — COMMENTED** [review]
Updated Azure Cost Workbood to reduce number of tables going to other category

**Comment by kenrward** [comment]
Fixed all issues with the checks.

**Comment by kenrward** [comment]
We have tested this with 4 different customers in the US Federal space and they love it.  Can we get this approved for the larger community?

**Review by sreedharande — APPROVED** [review]

**Comment by v-spadarthi** [comment]
image
Version not updated due to this we have created a another [PR](https://github.com/Azure/Azure-Sentinel/pull/6680)

**Pull request merged**
