### PR TITLE
Recorded Future solution2.5

### PR DESCRIPTION
**Pull request by RecordedFutureOskbo**
Changes:
   - New playbooks using the new TI Api for ingesting ThreatIntelligenceIndicator
   - Message in app and documetaion about deprecating graph API for TI indicators.
   - New correlation workbooks using the format of the TI data.
   - New Alert logic app and workbook, downloading alerts from Recorded Future into custom log and visualizing the result.
   - New "PlaybookAlert" logic app and workbook, pulling playbookalerts from Recorded Future to a custom log and visualizing the result. 
   - Render incident comments serverside for entity enrichment.
   - Solution  versioning, tagging and changelog improvements.
   - Readme updates
   
   Reason for Changes:
   - Deprication of GraphAPI for ingesting Threat Intelligence.
   - New Alert and PlaybookAlert integration.

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

Please contact us if you have questions or want to set up a meeting where we talk through the changes.

### CODE REVIEW

**Comment by v-prasadboke** [comment]
We wanted to check on the status of PR #8473. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

**Comment by RecordedFutureOskbo** [comment]
> We wanted to check on the status of PR #8473. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

We have been waiting for our Power Platform Connector to be certified and rolled out before activating this PR. Good news is that it's released since last week. We are doing final testing and will activate this PR within days.

**Comment by RecordedFutureOskbo** [comment]
@v-prasadboke we are ready for review finally.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Thank you for marking this PR as ready for review. This PR will be investigated and will update you about the same before 19 September, 2023.
Thanks.

**Comment by RecordedFutureOskbo** [comment]
I did a merge with master yesterday and did used the V3 tool for packaging the solution.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Please update the branch from master.

**Comment by RecordedFutureOskbo** [comment]
@v-prasadboke  I need help!
After I updated the version in the Solution_RecordedFuture.json to 3.0.0 I get validation errors that I have a hard time to track back to my ARM files.
image

My current ARM files works when I run them in [Deploy custom template] and the same files validated in previous versions.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Is there any other except this

**Comment by RecordedFutureOskbo** [comment]
> Hello @RecordedFutureOskbo, Is there any other except this

Here is how it looks when I just include one playbook
image

So It complains about contentProductId and id in the manTemplate.json getting generated py the ```createSolutionV3.ps1 ``` script.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, That is an exceptional error. You can proceed with 3.0.0
Also please share sample data and add images of other workbooks as well.

**Comment by RecordedFutureOskbo** [comment]
> Hello @RecordedFutureOskbo, That is an exceptional error. You can proceed with 3.0.0 Also please share sample data and add images of other workbooks as well. Please add release notes in the solution https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

All done! 
We correlate data from the ThreatIntelligenceIndicator table and one or more custom logs. I have uploaded csv that I use for correlation. All data in the custom log is demo events.

**Comment by v-prasadboke** [comment]
Thank you @RecordedFutureOskbo, For adding the sample data. I'll test the content and update you about the same before 22 September, 2023.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Thanks for the committing the changes. I'll continue with the review and update you about the same before Tomorrow.

**Comment by RecordedFutureOskbo** [comment]
I see the Azure.Sentinel test is failing on "RecordedFutureURLCorrelationWhite.png" but the file is in the PR if I'm not mistaken.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Please rename the underlined text to 
"RecordedFutureUrlCorrelationWhite.png"
"RecordedFutureUrlCorrelationBlack.png"
image

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Can you provide me access to your branch.
Thanks.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Sorry for the inconvenience. This PR is still under investigation and will update you before 26 September, 2023.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, We have uploaded the sample data to test the content of the solution. Will review the content and update you before 29 September, 2023.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, Deployment is failing for Recorded Future Alert Importer playbook.
image

**Comment by RecordedFutureOskbo** [comment]
> Hello @RecordedFutureOskbo, Deployment is failing for Recorded Future Alert Importer playbook. image

Thanks, found and fixed.

**Comment by v-atulyadav** [comment]
Hi @RecordedFutureOskbo, validations are stuck could you please take latest of master into your branch. Thanks

**Comment by v-atulyadav** [comment]
Thanks @RecordedFutureOskbo.

**Comment by v-prasadboke** [comment]
Thank you @RecordedFutureOskbo for committing the requested changes.
Will take a look at it and update you about the same before 09 October, 2023.

**Comment by RecordedFutureOskbo** [comment]
@v-prasadboke I don't mind going on a teams call in order to get progression on this PR.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo Can you please tell me your time zone and availability as per the same. 
I work in IST time zone and I'm available tomorrow from 4:30 PM IST onwards.
Thanks.

**Comment by RecordedFutureOskbo** [comment]
> c

I'm in Europe CET and will make time for you if you set up a call.

**Comment by v-prasadboke** [comment]
Hello @RecordedFutureOskbo, I'll setup a call for 4:30 PM IST which is 1:00 PM in CET. 
Joining link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDU3ZGZhZTEtM2FiZi00ODY5LTk3YjctYzk5Njc0ZGI4NDBl%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2228263f0a-981b-4a56-a4c9-1e91e9ea44fb%22%7d

**Comment by v-prasadboke** [comment]
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/BloodHound%20Enterprise/Package/createUiDefinition.json

**Review by v-prasadboke — APPROVED** [review]

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-prasadboke** [comment]
14983aa3-9ee2-40f2-a01e-8563d61ca383
b5d64d9f-a518-434f-9d60-992c2b6db6ad
bafd4f38-0de9-4078-98d7-320b7c73a7ee
1bf28b68-3d97-4cad-a1bb-72cdb688daac
b6783ce6-a718-4d77-a960-ce446a011af1
b17f3ea8-b0da-4713-9382-bee881db284c

Screenshot received

**Pull request merged**
