### PR TITLE
Adding a query looking for signs of drive-by-compromise by seo poisoning

### PR DESCRIPTION
**Pull request by JouniMi**
Required items, please complete
   
   Change(s):
   - Added Hunting Queries/Microsoft 365 Defender/Initial access/drive-by-compromise-by-seo-poisoning.yaml

   Reason for Change(s):
   - Added a Defender for Endpoint threat hunting query to look for signs of drive-by-compromise utilizing SEO poisoning.

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hi @JouniMi,
Validation checks are stuck, please update your branch from master and push again.
Thanks

**Comment by JouniMi** [comment]
@v-rusraut  I made small modification to the description and pushed again. It seems that the checks started to run. 👍

**Comment by v-rusraut** [comment]
Hi @JouniMi,

There is kql validation error, to fix this error need to add table and function definition:

1. Add custom table definition in below path
https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables
2. Add custom function definition in below path
https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomFunctions

Also while running the query getting error  below error
image

Please share the sample data and working query screen shot.

Thanks

**Comment by v-rusraut** [comment]
Hi @JouniMi,
Checking more on this issue, we will provide you an update before 06 March 2024.
Thanks

**Comment by v-rusraut** [comment]
Hi @JouniMi,
FileProfile function will not work here, need to update query or you can close this PR.
Thanks

**Comment by JouniMi** [comment]
Hi @v-rusraut 
Unfortunate that this repo does not support built-in functions on the product, but as this is the case I can't do anything else than close the PR. I am not willing to rewrite the function for sake of having a query in MS repo.

**Pull request closed without merging**
