### PR TITLE
Block-ExchangeIP

### PR DESCRIPTION
**Pull request by ThijsLecomte**
Playbook that blocks the IP from an alert in an on-premises Exchange server using Azure Automation.
#495

### CODE REVIEW

**Comment by dicolanl** [comment]
@ThijsLecomte looks like you have some failures. please review the failures and fix your submission

**Comment by ThijsLecomte** [comment]
@dicolanl I have updated the code. Seems that I uploaded an older version of the template. My apologies.

**Comment by dicolanl** [comment]
@ThijsLecomte Thank you for your submission.

Please add a screenshot of the successful run here in the comments.

In your readme, you say there are some required prereqs but its not clear to end users how or what they would need to go deploy.  Could you either include deployments for those in an ARM template OR include instructions for the steps to deploy the prereqs.

**Comment by ThijsLecomte** [comment]
@dicolanl updated the readme.

I cannot implement it in the ARM template as a hybrid worker in an ARM template isn't doable.
Let me know if anything needs to change

The screenshot for the successful run:
image

**Pull request merged**
