### PR TITLE
changed python version from 3.8 to 3.11

### PR DESCRIPTION
**Pull request by RamboV**
Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-sudkharat** [comment]
Hi @RamboV, thank you for raising Pull Request with us! You should expect an initial response to your Pull Request from the team within 2 business days. Thanks!

**Comment by v-sudkharat** [comment]
Hey @RamboV, Can we connect via a teams?

**Comment by v-sudkharat** [comment]
@RamboV, I have checked for the File -Solutions/CognyteLuminar/Data Connectors/Cognyte Luminar.zip, which is missing the required python 3.11 packages modules folder. 
Could you add that -  ,python_packages folder with its modules into the zip. 
sharing screenshot for your reference - 
image

**Comment by RamboV** [comment]
> @RamboV, I have checked for the File -Solutions/CognyteLuminar/Data Connectors/Cognyte Luminar.zip, which is missing the required python 3.11 packages modules folder. Could you add that - ,python_packages folder with its modules into the zip. sharing screenshot for your reference - image

Added python packages

**Comment by v-sudkharat** [comment]
Hi @RamboV, After deployment of function app, the function are still not visible into the overview tab - 
image

can you please check for the function one. Thanks!

**Comment by RamboV** [comment]
> Hi @RamboV, After deployment of function app, the function are still not visible into the overview tab - image
> 
> can you please check for the function one. Thanks!

Hi @v-sudkharat, I've updated the Python packages. The changes should be visible now. Could you please check and confirm?

**Comment by RamboV** [comment]
Hi @v-sudkharat, I've updated the Python packages. The changes should be visible now. Could you please check and confirm?

**Comment by v-sudkharat** [comment]
@RamboV, Thanks for update, I will validate the changes and get back to you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @RamboV, The changes look good now and can see the function after deployment. 
Please update the python version from 3.8 to 3.11 in below highlighted file and repackage the solution, so all changes get added into the main file:-
image

And just want to verify, there is no workspace ID and Workspace key define while pre-deployment of azure deploy file. So, it is expected or are missing something? 
Could you please share the successfully connector connected screenshot with us, as we don't have the required credentials to connect it and check the logs. 
Thanks!

**Comment by RamboV** [comment]
Hi @v-sudkharat ,

I've made the necessary updates to the CognyteLuminar_FunctionApp.json file. Note that there's no Workspace ID and Workspace Key included, as the client will provide the Application ID and Secret instead. For more details, please refer to the [Sentenil TIP creds](https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-tip#sign-up-for-an-application-id-and-client-secret-from-your-microsoft-entra-id)

PFA
Connector

TI

**Comment by v-sudkharat** [comment]
Thanks @RamboV

**Review by v-sudkharat — APPROVED** [review]
Approved

**Pull request merged**
