### PR TITLE
On-Premises Exchange Security Configuration first commit

### PR DESCRIPTION
**Pull request by nlepagnez**
Change(s):
   - First PR of new solution "ESI - On-Premises Exchange Security Configuration" without package

   Reason for Change(s):
   - Adding new REST API Connector with its parser and the first Workbook

   Version Updated:
   - First version 1.0.0

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No

### CODE REVIEW

**Comment by NikTripathi** [comment]
@v-spadarthi Can you please look into this

**Comment by v-marimanda** [comment]
@nlepagnez  Parser query is falling please take a look and resolve it. thanks!!!
image

**Comment by v-marimanda** [comment]
@nlepagnez  Workbook query's is also failing could you please check it once. thanks!!!
image

**Comment by nlepagnez** [comment]
> @nlepagnez Parser query is falling please take a look and resolve it. thanks!!! image

Hi @v-marimanda, as you can read at the beginning of the parser, that you need to save the parser as a function called "ExchangeConfiguration" and this function has parameters. SpecificSectionList is one of the 4th parameters.

Also for the Workbook, the "ExchangeConfiguration" parser function is needed. If you have this error, it's because you didn't follow the installation steps and you didn't savce the parser as function.

I just added a new instruction part on Connectors to be more explicit than just the previous "Note".

**Comment by nlepagnez** [comment]
Hi @v-marimanda, @v-spadarthi, there is any update on that PR ?

**Comment by v-marimanda** [comment]
@nlepagnez  I have followed all the steps you have mention on parser but i could only one sample data attached. 
I have used this sample data for ESIExchangeConfig_CL.  can i use the same sample data for another table ESIExchangeOnlineConfig_CL, If not please provide sample data for ESIExchangeOnlineConfig_CL. Currently i am getting below error as i don't have any table with name  ESIExchangeOnlineConfig_CL.
image

**Comment by nlepagnez** [comment]
@v-marimanda, yes you can use the same content for the other table. 
But what you say is something interesting as we can have condition where one of the two tables doesn't exist and in this case, the parser has errors. 

I have to work on the parser to see how to avoid that.

**Comment by nlepagnez** [comment]
@v-marimanda you can find an update of the parsers with the fuzzy mode to be able to be agnostic of missing tables.

This can allow you to be able to finish your tests.

**Comment by v-laanjana** [comment]
@nlepagnez  thank for update we are checking ...

**Comment by v-spadarthi** [comment]
@v-laanjana : Could you please provide an update on this.

**Comment by v-spadarthi** [comment]
@v-laanjana : Could you please provide an update on this.

**Comment by v-mchatla** [comment]
Hi @v-laanjana, 
Did you get a chance to check on this. Can you please provide an update.
Thanks

**Comment by v-laanjana** [comment]
@v-mchatla  we are working ..

**Comment by NikTripathi** [comment]
Hi @v-laanjana this is a long pending one. Can you please have a look?

**Comment by nlepagnez** [comment]
@v-laanjana , @v-marimanda, is it possible to have any update ?

**Comment by v-marimanda** [comment]
Hi @nlepagnez,

I have save the parsers  with parameter's and sending default value as well but still Workbook query's are failing can you please take a look once for your reference i am attaching screen shot below. 

 Workbook
image

Parsers 

image

**Comment by v-marimanda** [comment]
Hi @nlepagnez  can you please address the above comment. thanks!!!

**Comment by nlepagnez** [comment]
> Hi @nlepagnez can you please address the above comment. thanks!!!

Hi @v-marimanda, I think it's because the sample data are too old, as we can't use TimeGenerated for filtering but another property. How do you fill the sample data in your table ? I want to try in my side and be sure that the Sample data is correct before launching a new round.

**Comment by nlepagnez** [comment]
@v-marimanda, I have just updated Sample Data, Parser and Workbook so that they can show you results on potentially old "Sample" data (which will never be the case in normal use).

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Thanks for sharing the sample data. We will check and provide more details once done.
Thanks

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Sorry for the delay. I'm going to start working on it today and provide you the update by EOD.
Thanks

**Comment by nlepagnez** [comment]
> Hi @nlepagnez, Sorry for the delay. I'm going to start working on it today and provide you the update by EOD. Thanks

@v-mchatla Perfect. Do not hesitate to ask me everything if you need.

**Comment by v-mchatla** [comment]
ExchangeConfiguration Parser is working fine
Getting below issue for the other parser ESI_ExchConfigAvailableEnvironments
image
Can you please have a look at it and let me know if I'm missing something.
Thanks

**Comment by nlepagnez** [comment]
> ExchangeConfiguration Parser is working fine Getting below issue for the other parser ESI_ExchConfigAvailableEnvironments image Can you please have a look at it and let me know if I'm missing something. Thanks

Hi @v-mchatla, the error message indicates that the tables ESIExchangeConfig_CL and/or ESIExchangeOnlineConfig_CL are missing. Did you create one of them with sample data ?

**Comment by v-mchatla** [comment]
Hi @nlepagnez 
I have already dumped the data to Log Analytics as you can see below.
image
Thanks

**Comment by v-mchatla** [comment]
Parsers are working fine. Need your help in fixing the below workbook related issues.
1. Workbook should be of json format, please update it accordingly.
2. Role Assignee dropdown should populate with some data but its not fetching any data while rendering the workbook page.
image
3. Getting below issue for ExchangeAdminAuditLogs
image
4. Workbook is referring data from watchlist (ExchCUSU), please share those watchlist data to test end to end.
image
5. server data is not rendering in the dropdown.
image

Thanks

**Comment by nlepagnez** [comment]
> Parsers are working fine. Need your help in fixing the below workbook related issues.
> 
> 1. Workbook should be of json format, please update it accordingly.
> 2. Role Assignee dropdown should populate with some data but its not fetching any data while rendering the workbook page.
>    image
> 3. Getting below issue for ExchangeAdminAuditLogs
>    image
> 4. Workbook is referring data from watchlist (ExchCUSU), please share those watchlist data to test end to end.
>    image
> 5. server data is not rendering in the dropdown.
>    image
> 
> Thanks

Hi @v-mchatla, 

- For the point 1, I transformed the Workbook to JSON Extension file.
- For the point 2 and 5, with gave you a sample data file but with only 2 to 3 entries. There are many and many entries from a production environment and Workbooks are made to display Real production data. I update the sample data with a complete simulated infrastructure data file.
- For the point 3, we removed the part calling ExchangeAdminAuditLogs that is planned for a V2 of this solution package, we want to validate a simple V1 version before adding all connectors, workbooks, analytic rules, etc..
- For the point 4, sorry, we have changed our strategy since August on how we want to manage this list. The new version of the Workbook that I commit reflect that.

I hope this new commit will be good for you.

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
With the Latest sample data Role Assignee details are auto populated. But help page is not rendering any data. Is that okay?
image
Rest all things looks good. 
Please fix the validation errors to proceed with approval and merge.
Hope the below clues can help you in resolving the validation errors.
1. should not contain hardcoded values.
image
2. should not contain reference to any resources.
image

**Comment by nlepagnez** [comment]
@v-mchatla, 

I removed the hardcoded values and commit the new version.

It's normal that help page is empty for the moment.

**Comment by v-mchatla** [comment]
> @nlepagnez please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

Can you please respond to this with your company details

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by nlepagnez** [comment]
Hi @v-mchatla, I have accepted the CLA but it's marked as queued. Is it normal or do I have to do something ?

**Comment by v-mchatla** [comment]
> Hi @v-mchatla, I have accepted the CLA but it's marked as queued. Is it normal or do I have to do something ?

Hi @nlepagnez,
Unless and until the below check is passed, I can't merge the pr. Let me also check with my team if you can do anything for this case.
image

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Can you try signing again, I will also check with team and provide you the update
Thanks

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by nlepagnez** [comment]
> Hi @nlepagnez, Can you try signing again, I will also check with team and provide you the update Thanks

Hi @v-mchatla I tried to sign again, but nothing changes. Is it because it's "Microsoft" in company name ?

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Can you just try sending only the below command.
@microsoft-github-policy-service agree
Thanks

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Can you please go through the steps specified [here](https://github.com/microsoft/contributorlicenseagreement)
Thanks

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree

**Comment by nlepagnez** [comment]
@microsoft-github-policy-service agree

**Comment by nlepagnez** [comment]
@v-mchatla I think you can now approve the merge as CLA is validated.

**Review by v-mchatla — APPROVED** [review]
Changes are looking good. Approving this PR.

**Comment by v-mchatla** [comment]
Hi @nlepagnez,
Thank you for your continued support. It would be great if you can share the steps you followed to fix the CLA issue as lot of other GitHub users are also facing the similar issue, because of that we are not able to accept their contribution.
Thanks

**Comment by nlepagnez** [comment]
> Hi @nlepagnez, Thank you for your continued support. It would be great if you can share the steps you followed to fix the CLA issue as lot of other GitHub users are also facing the similar issue, because of that we are not able to accept their contribution. Thanks

Hi @v-mchatla, Using the link you sent me about the CLA application, I installed it on my Github account. I have created the ".Github" repository and begin to configure it, but I see that the CLA approval was validated before I finished to configure the .Github repo. 

So to resolve the problem, for sure they need to install the CLA Application in their Github account, but after it's sure that they need to create the .Github repo or not.

**Pull request merged**
