### PR TITLE
UpdatingCustomTablesforDataConnectorsKQLValidations

### PR DESCRIPTION
**Pull request by v-sudkharat**
Required items, please complete.
   
   Change(s):
   - Adding new custom tables and updating existing ones.

   Reason for Change(s):
   - We have some data connectors' KQL queries failing validation tests due to missing custom tables which is being referred in 
     these queries or some column missing in any of the existing custom tables, so we referred to the sample data added by 
     authors for these tables and made updates in tables accordingly.

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

### CODE REVIEW

**Comment by vakohl** [comment]
@v-sudkharat why so many files being added? can you please update more details in the description for this PR?

**Comment by v-sudkharat** [comment]
> @v-sudkharat why so many files being added? can you please update more details in the description for this PR?

We have updated the details in description please check.

**Comment by vakohl** [comment]
> * We have some data connectors' KQL queries failing validation tests due to missing custom tables which is being referred in
>   these queries or some column missing in any of the existing custom tables, so we referred to the sample data added by
>   authors for these tables and made updates in tables accordingly.

thanks. changes looking good.

**Review by vakohl — APPROVED** [review]
Addition of these custom tables in bulk is due to the planned cleanup activity for kqlskipvalidation file.

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
