### PR TITLE
Adding Talon Security Workbook 

### PR DESCRIPTION
**Pull request by aviatam**
Adding Talon Workbook to Microsoft Sentinel

   Required items, please complete
   
   Change(s):
   - Talon Insights workbook
   - Logo
   - Screenshots
   - updated Metadata json

   Reason for Change(s):

- Display Talon Insights on Microsoft Sentinel

   Version Updated:

   Testing Completed:
   - tested on ingesting data with azure work analytics

### CODE REVIEW

**Comment by v-atulyadav** [comment]
Hi @aviatam, can you please replace text from `Azure Sentinel` with `Microsoft Sentinel` to pass the validations. Thanks

image

**Comment by aviatam** [comment]
@microsoft-github-policy-service agree [company="Talon Security"]

**Comment by aviatam** [comment]
@microsoft-github-policy-service agree company="Talon Security"

**Comment by aviatam** [comment]
hey dear @v-atulyadav , please let me know if you need any additional info 
thanks

**Comment by v-atulyadav** [comment]
Hi @aviatam, logo validation fails please check below error message.

image

**Comment by aviatam** [comment]
@v-atulyadav i don't understand , logo validation is not require check , also the svg seems okay + other svg do not have id in them 
i don't see any documentation regarding how to define the guid

**Comment by aviatam** [comment]
@v-atulyadav @v-mchatla i've removed the pic , can you guys please review and approve 
much appreciated

**Comment by v-atulyadav** [comment]
Hi @aviatam, as you changed this Python file from individual folder, you need to also change this file in the zip folder. Thanks.
image

**Comment by v-atulyadav** [comment]
Hi @aviatam, I would also like to request a sample data set, as the workbook query fails, or you can paste screenshots of the working workbook here.

image

**Comment by aviatam** [comment]
@v-atulyadav zip file was updated , also please look inside the pr you can see the workbook screenshots are already attached and are part of the requirements for the pull request [image](https://github.com/Azure/Azure-Sentinel/pull/7284/files#diff-932a6c708ab87e5d4db1ff62389dcd4c54e9e311dfcfe12ad22572ac9884d34a)

**Comment by v-atulyadav** [comment]
Hi @aviatam, could you please explain why you deleted init.py from below? I would also appreciate if you could share screenshots of the invocation logs for functionapp if possible.

image

**Comment by aviatam** [comment]
@v-atulyadav I've removed all Connector-related changes from the PR and updated the title 
now the PR includes only workbook resources 
apologies for the confusion I've caused 
please review and approve

**Review by v-atulyadav — APPROVED** [review]

**Review by v-dvedak — APPROVED** [review]

**Pull request merged**
