### PR TITLE
Formatting fixes revealed during parsing

### PR DESCRIPTION
**Pull request by ccmsft**
Required items, please complete
   
   Change(s):
   - Updated metadata for rules to adhere to convention.

   Reason for Change(s):
   - Some rule metadata was incorrect

### CODE REVIEW

**Comment by v-shukore** [comment]
Hi @ccmsft,

Please update the version of all Hunting Queries that you have modified, as the validation checks are failing due to the version not being updated.
image

Thanks...!!

**Comment by v-shukore** [comment]
Hi @ccmsft, please update on above comment. Thanks

**Comment by v-shukore** [comment]
Hi @tduarte14, please update the Hunting Queries version to resolve the validation checks. After that, we can proceed with the next steps. Thanks!

**Comment by v-shukore** [comment]
Hi @ccmsft, please update on above comment. Thanks...!!

**Comment by v-shukore** [comment]
Hi @tduarte14, please update the Hunting Queries version to resolve the validation checks. After that, we can proceed with the next steps. Thanks!

**Comment by v-shukore** [comment]
Hi @ccmsft,

We wanted to check on the status of PR #11300. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR.

Thank you for your cooperation.

**Comment by v-shukore** [comment]
Hi @ccmsft, please update the Hunting Queries version to resolve the validation checks. After that, we can proceed with the next steps. Thanks!

**Comment by v-shukore** [comment]
Hi @ccmsft, please repackage the solutions using V3 tool and commit the changes.
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md
Thanks!!

**Comment by v-shukore** [comment]
Hi @ccmsft, waiting for your update please do the packaging to proceed. Thanks!!

**Comment by ccmsft** [comment]
PR is too large, will potentially just provide a parsing tool to identify issues missed in current validations.

**Pull request closed without merging**
