### PR TITLE
Update CorrelateIPC_Unfamiliar-Atypical.yaml

### PR DESCRIPTION
**Pull request by briandelmsft**
The KQL logic was not consistent with the description of the alert in line 4.  The description indicates a correlation within 20 minutes but the KQL logic looked for correlation within 10 minutes

Fixes #

## Proposed Changes

  - Update KQL to look for +/- 20 minutes instead of +/- 10 minutes
  -
  -

### CODE REVIEW

**Review by shainw — CHANGES_REQUESTED** [review]
The timeframe is +-10m so 20 min window around the Alert time so the 10m value is correct. I would recommend an update to the description to make this more clear versus changing the time window.

**Comment by briandelmsft** [comment]
Updated description and reverted KQL change based on feedback

**Review by shainw — APPROVED** [review]
@briandelmsft - I did some further tweaks, look good?

**Comment by briandelmsft** [comment]
I'm good with that option, but here's a slight rewording for your consideration.  Either way is fine with me.

"The combination of an Unfamiliar sign-in properties alert and an Atypical travel alert about the same user within a +10m or -10m window is considered a high severity incident."

**Comment by shainw** [comment]
@briandelmsft - Better wording, I agree.  I implemented it and merged the PR.  Thanks for having a look at this and improving the explanation.

**Pull request merged**
