### PR TITLE
edited solution id to match Azure marketplace requirements

### PR DESCRIPTION
**Pull request by yanivblumWiz**
Required items, please complete
   
   Change(s):
   - updated solution id for solution
   - updated package with new file

   Reason for Change(s):
   - To match the Azure marketplace guidelines

   Version Updated:
   - No

   Testing Completed:
   - Not needed

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-rusraut** [comment]
Hello @yanivblumWiz 

As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using V3 tool
Please go through this readme file on how to use the V3 tool
https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

**Comment by yanivblumWiz** [comment]
> Hello @yanivblumWiz
> 
> As per latest guidelines issued by Microsoft Sentinel, please repackage the solution using V3 tool Please go through this readme file on how to use the V3 tool https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md

@v-rusraut I edited it to V3, although the automatic tool did not work. 
Also, please don't merge it yet, I am waiting for approval from the Sentinel PM (Eric B)

**Comment by v-rusraut** [comment]
Hi @yanivblumWiz 

Which issue you are facing with V3 ? 
Can you please share the screen shots for the same.
Also there is validation failed due to incorrect solution Id Format, SolutionId should be combination of PublisherId.OfferId.
I see previous version SoulutionId is in correct format, so why you need to update it.  
And we need to add ReleaseNotes file for solution.Please refer below link for how to create ReleaseNotes.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ReleaseNotesGuidance.md

Thanks

**Comment by yanivblumWiz** [comment]
> 

This is the error I get: 
image

I edited the solution ID to match it with the solution ID needed for the Azure general marketplace. They do not allow dots there, and they say the ID needs to match the ID in this GH repo, so we are quite confused in this area. 

I added the RN

**Comment by yanivblumWiz** [comment]
Also, please don't approve the PR yet, I will let you know if we need it open or no

**Comment by v-rbajaj** [comment]
Hi @yanivblumWiz, thanks for marking this a draft, please do let us know once it is ready for review.

**Pull request closed without merging**
