### PR TITLE
[feedly] add python packages to data connector

### PR DESCRIPTION
**Pull request by Mathieu4141**
Required items, please complete
   
   Change(s):
   - Adding python packages in the data connector zip

   Reason for Change(s):
   - missing folder

### CODE REVIEW

**Comment by v-prasadboke** [comment]
Hello Mathieu, I hope this function app is good now. Can you share the working images of the same

**Comment by Mathieu4141** [comment]
> Hello Mathieu, I hope this function app is good now. Can you share the working images of the same

The connector has been working since the beginning when I send it with VSCode, it's the deployment that is not working, but I don't know how to test that without updating the offer...

**Review by v-prasadboke — APPROVED** [review]

**Comment by Mathieu4141** [comment]
> image Can you share this with me

How do I share that securely?

**Comment by v-prasadboke** [comment]
> > image Can you share this with me
> 
> How do I share that securely?

you can mail me at v-prasadboke@microsoft.com

**Comment by v-prasadboke** [comment]
Hey hi @Mathieu4141 maybe you missed sharing the credentials over mail. Can you please share it.

**Comment by v-prasadboke** [comment]
Hello @Mathieu4141, Can you please share the credentials.

**Comment by v-prasadboke** [comment]
Hello @Mathieu4141, we are waiting for the credentials.

**Comment by v-prasadboke** [comment]
Hello @Mathieu4141, We are waiting for the credentials

**Comment by Mathieu4141** [comment]
> Hello @Mathieu4141, We are waiting for the credentials

I already sent the details to the email you provided above

**Comment by v-prasadboke** [comment]
Hey thanks @Mathieu4141, for sharing the details. I'll test the connector and get back to you by 20 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @ajcollins0, due to lack of availability it was not possible for me to touch this PR.
I'll investigate this PR and get back to you by 22 December, 2023.

**Comment by v-prasadboke** [comment]
Hello @Mathieu4141, The folder structure in the zip file is still improper. Correcting the folder structure. Will update you by today EOD or tomorrow first half (**IST**)

**Review by v-prasadboke — APPROVED** [review]

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
