### PR TITLE
CMMC2.0 Solution (Private Preview)

### PR DESCRIPTION
**Pull request by thbanasi**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by v-sabiraj** [comment]
@aprakash13 ,please review Analytic Rules, Thanks.

**Comment by v-sabiraj** [comment]
image
Please fix the workbooks query, thanks.

**Comment by v-sabiraj** [comment]
image
Please fix the queries, thanks.

**Comment by thbanasi** [comment]
@v-sabiraj, thank you for reviewing. Both errors you're seeing are expected behavior. In the workbooks error, you don't have Azure Information Protection logs in your demo environment. Any time a custom log isn't present, it'll throw this error message. This is an indication the customer should onboard Azure Information Protection or another Data Loss Prevention tool to meet this control. I recommend requesting Ninja Demo environment access (https://aka.ms/NinjaDemoAccess). I can walk you through accessing it for the first time and this environment has all security tools onboarded showing desired state of the content. 

For the second error in the Analytics Rule, this is also expected behavior because your workspace doesn't have Microsoft Defender for Cloud Regulatory Compliance logging onboarded. If you follow Getting Started Steps#4-5 (https://docs.microsoft.com/en-us/azure/defender-for-cloud/update-regulatory-compliance-packages | https://docs.microsoft.com/en-us/azure/defender-for-cloud/continuous-export) they provide customer steps to enable the Microsoft Defender for Cloud Regulatory Compliance Assessment for NIST SP 800-171 and export policy assessments to the Sentinel workspace. If you follow the steps above for getting access to the Ninja demo environment, it has these logs so you can see the desired state.

**Review by aprakash13 — APPROVED** [review]
Queries look good overall. Approved.

**Pull request merged**
