### PR TITLE
Microsoft Defender for Office Workbook Addition

### PR DESCRIPTION
**Pull request by briandelmsft**
New Workbook that utilizes the data from the Microsoft Defender for Office Connector Public Preview.
Helps analysts with analyzing EmailEvents, EmailAttachmentInfo and EmailUrlInfo data.

### CODE REVIEW

**Comment by v-jayakal** [comment]
Hi, Can you please tell us what is 'EmailEvent' used in 'EmailDirectionQuery'? Is it a parser or table? Where is it define? Getting error 
image
Thanks.

**Comment by briandelmsft** [comment]
> Hi, Can you please tell us what is 'EmailEvent' used in 'EmailDirectionQuery'? Is it a parser or table? Where is it define? Getting error

This workbook uses EmailEvents, EmailUrlInfo and EmailAttachmentInfo tables which are part of the Microsoft 365 Defender connector.  No parser is required.  See docs on this connector [here](https://docs.microsoft.com/en-us/azure/sentinel/connect-microsoft-365-defender?tabs=MDO).

image

**Review by NikTripathi — CHANGES_REQUESTED** [review]
Please take the latest from master and then create your branch. Because of old version in CybersecurityMaturityModelCertification(CMMC) file references are there in metadata which are deleted. Please update it because of that validation is failing. Thank you.

**Comment by briandelmsft** [comment]
@NikTripathi I fetched the upstream changes into the branch which removed them but the validation still fails.  I can't see any issues with the addition that would cause a failure to validate the workbooks metadata.  I can do a new branch with the changes if you prefer

**Comment by NikTripathi** [comment]
Hi @briandelmsft , Now workbook metadata is fine. Actually there is a bug in system. For passing the validations please update **MicrosoftDefenderForOffice365** metadata at second last place instead of last in workbookmetadata.json file. This will resolve our issue. Thank you.

**Comment by briandelmsft** [comment]
@NikTripathi done, validation is now passing.

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
