### PR TITLE
[TrendMicro] Update new version data connector.

### PR DESCRIPTION
**Pull request by adamhuang97**
## Before submitting this PR please ensure that you have read the following sections and then completed the template below:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures, there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

## After the submission has been made, please look at the Validation Checks:

> Check that the validations are passing and address any issues that are present. Let us know if you have tried fixing and need help.

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

## PR Template

-----------------------------------------------------------------------------------------------------------
 **Description for the PR:**
  - Remove custom table, TrendMicro_XDR_CL.
  - Add new custom table: TrendMicro_XDR_WORKBENCH_CL, TrendMicro_XDR_RCA_Task_CL, TrendMicro_XDR_RCA_Result_CL and TrendMicro_XDR_OAT_CL.
  - Add new azure function with time and queue trigger for new custom table.

**Testing Completed:**
  Yes/ No :  Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-sabiraj** [comment]
Please add preview images and workbook metadata for updated workbook, thanks.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 , The workbook TrendMicroXDROverview.json has been modified but the version has not been incremented in the Workbooks/WorkbooksMetadata.json file, please update this, thanks.

**Comment by v-sabiraj** [comment]
@adamhuang97 ,TrendMicro_XDR_OAT_CL does not refer to any table or column, please fix this, thanks.

**Comment by v-sabiraj** [comment]
"alertProvider_s" does not refer to any column entity in TrendMicro_XDR_RCA_Result_CL, please fix this, thanks.
image

**Comment by v-sabiraj** [comment]
> @adamhuang97 ,TrendMicro_XDR_OAT_CL does not refer to any table or column, please fix this, thanks.

The queries are failing as **TrendMicro_XDR_OAT_CL** does not refer to any table or column

**Comment by v-sabiraj** [comment]
There is message when the function is deployed and clicked on Test/Run, please fix this. 
image

**Comment by adamhuang97** [comment]
Hi @v-sabiraj ,
For Code+Test.
It seems fine from my side, which part I missing about it?
Thank you.
Screen Shot 2022-01-26 at 6 09 31 PM

**Comment by v-sabiraj** [comment]
Tested the data connector by deploying the functions. Can see unexpected error for "queue_trigger_oat" function. Please check and update. Thanks.
image

**Comment by v-sabiraj** [comment]
Can see unexpected errors for "queue_trigger_oat_poison, timer_trigger, timer_trigger_oat" functions . Please check and update. Thanks.
image

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 , please update the requested changes, thanks.

**Comment by v-sabiraj** [comment]
Can see unexpected error for "queue_trigger_oat" function as no module named 'dataclasses' found, please fix this, thanks.
image

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 , Can see unexpected errors for "queue_trigger_oat_poison, timer_trigger, timer_trigger_oat" functions as no module named '_cffi_backend', please fix this ,thanks.

**Comment by adamhuang97** [comment]
Hi @v-sabiraj,
I've update the package of data connector and azure deploy template.
Please help to check is python assigned to 3.8?
Thank you.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97, I think that there is no need to add "pythonVersion": "3.8", in azure deploy file. Please check and update. 
Please fix the no module error for module names "dataclasses" and "_cffi_backend", thanks

**Comment by adamhuang97** [comment]
Hi @v-sabiraj,
Since "dataclasses" and "_cffi_backend" are built in python 3.7 later.
I think our data connector need set runtime version to 3.8.
May I have your help to check current runtime version?
Thank you.

**Comment by v-sabiraj** [comment]
> Hi @v-sabiraj, Since "dataclasses" and "_cffi_backend" are built in python 3.7 later. I think our data connector need set runtime version to 3.8. May I have your help to check current runtime version? Thank you.

Hey @adamhuang97, the current runtime version showing is ~3 
image

**Comment by adamhuang97** [comment]
Hi @v-sabiraj 
Thanks for your help.
May I know the last changes(add python version to 3.8), is solved the module error?
Thank you.

**Comment by v-sabiraj** [comment]
> Hi @v-sabiraj Thanks for your help. May I know the last changes(add python version to 3.8), is solved the module error? Thank you.

Hey @adamhuang97 , not sure that if the runtime version can be changed to ~3 to 3.8

**Comment by adamhuang97** [comment]
Hi @v-sabiraj,
Form our side, data connector run as expected with new deployment template (change [5e01a91](https://github.com/Azure/Azure-Sentinel/pull/3871/commits/5e01a91d1a4ba96ec367fb44ba54d996bc6f73af) ).
Would you please help to use new deploy template to verify it?
Thank you.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97, I verified with new deployment template, still giving the same error, just check if the line "pythonVersion": "3.8", can be removed from azure deploy file in "siteConfig" ,thanks.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 ,"linuxFxVersion": "PYTHON|3.8" here the word **python** must be in lowercase, please check and update.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 , the query "TrendMicro_XDR_OAT_CL\n    | project-reorder detectionTime_t*, xdrCustomerId_g, filterRiskLevel_s\n  | project-away SourceSystem, TenantId" in data connector is still failing, please check and update , thanks.
image

**Comment by adamhuang97** [comment]
Hi @v-sabiraj 
Sorry for incorrect version template in package file.
Already update it.
Thank you.

**Comment by v-sabiraj** [comment]
> Hey @adamhuang97 , the query "TrendMicro_XDR_OAT_CL\n | project-reorder detectionTime_t*, xdrCustomerId_g, filterRiskLevel_s\n | project-away SourceSystem, TenantId" in data connector is still failing, please check and update , thanks. image
 
Hi @adamhuang97 , the query is failing, it might be because the entities  _detectionTime_t*, xdrCustomerId_g, filterRiskLevel_s_ are not available in sample data of  "TrendMicro_XDR_OAT_CL" , please check and update,thanks.

**Comment by adamhuang97** [comment]
Hi @v-sabiraj 
I've update the sample data file name in package file.
Thank you.

**Comment by v-sabiraj** [comment]
Hey @adamhuang97 , you have updated the sample data file in package, but if you check "TrendMicro_XDR_OAT_CL" sample data by opening it , you will find that the columns  **detectionTime_t*, xdrCustomerId_g, filterRiskLevel_s** does not exist in that particular sample data file.

**Comment by v-sabiraj** [comment]
> Hey @adamhuang97 , you have updated the sample data file in package, but if you check "TrendMicro_XDR_OAT_CL" sample data by opening it , you will find that the columns detectionTime_t, xdrCustomerId_g, filterRiskLevel_s  does not exist in that particular sample data file.

@adamhuang97 , you need to update the sample data file "TrendMicro_XDR_OAT_CL" by adding these fields or columns, thanks.

**Comment by adamhuang97** [comment]
Hi @v-sabiraj 
Thanks for your reminder.
I've update the sample data to folder and package file.

**Comment by venbea** [comment]
I have installed the new function and I have errors in timer_trigger_oat

Client-Request-ID=e563ff9e-93c8-11ec-9c27-00155df0d882 Retry policy did not allow for a retry: Server-Timestamp=Tue, 22 Feb 2022 10:19:19 GMT, Server-Request-ID=320ec165-b002-0045-65d5-2794b4000000, HTTP status code=409, Exception=Conflict{"odata.error":{"code":"TableAlreadyExists","message":{"lang":"en-US","value":"The table specified already exists.\nRequestId:320ec165-b002-0045-65d5-2794b4000000\nTime:2022-02-22T10:19:19.3943466Z"}}}.

Any feedback about this issue ?

**Pull request merged**
