### PR TITLE
FlareSystemsFirework: create 1.0.0 solution

### PR DESCRIPTION
**Pull request by aviau**
- Remove empty variables in `Connector_REST_API_FlareSystemsFirework.json` which caused solution validation errors
- Create the first 1.0.0 solution and add it to the `Package` folder

### CODE REVIEW

**Comment by aviau** [comment]
cc @elforb 

This creates the first version of our solution!

**Review by elforb — CHANGES_REQUESTED** [review]
@aviau --

General
- Some characters are encoded improperly, and should be replaced. Alternatively, you can use PowerShell 7.1+ to re-generate the package, and the encoding will automatically be correct.
   - `\u003c` should be the `<` character
   - `\u003e` should be the `>` character
   - `\u0027` should be the `'` character
- Ensure that [arm-ttk](https://github.com/Azure/arm-ttk) validation is run, using `Test-AzTemplate`. Validation command should be automatically imported with the solution package creation tool.

MainTemplate.json
- Remove Unused Parameters
   - `formattedTimeNow`
- Remove Unused Variables
   - `workbook-source`
   - `_workbook-source`
- Add `location` property to data connector resource
   - `"location": "[parameters('workspace-location')]",`
   - Ex. image

CreateUiDefinition.json
- Remove Workbook Tab, since no workbook is included
   - This tab is the object that spans lines 79-100 of createuiDefinition.json

**Comment by elforb** [comment]
Also, has this been published to the marketplace yet?

**Comment by aviau** [comment]
@elforb 

> Also, has this been published to the marketplace yet?

The Offer is waiting for "Certification" on the partner center:
- Offer ID: flare-systems-firework-sentinel
- Plan ID: flare-systems-firework-sentinel-1

I'll work on your other feedback soon.

**Comment by aviau** [comment]
@elforb 

I think that most of your comments were fixed by switching to Powershell 7.1+ to generate the solution.


> Remove Unused Parameters formattedTimeNow

Looks like its now used in the workbook display name

> Remove Unused Variables workbook-source _workbook-source

Looks like its now used by the workbook.

> Add location property to data connector resource "location": "[parameters('workspace-location')]",

I had to add that one manually. Maybe the solution creation script should have done it?


> Remove Workbook Tab, since no workbook is included

This was a bug, the workbook is now included.

**Comment by elforb** [comment]
@aviau Thanks for fixing, the solution is passing validation and deployable now.

Could you also provide the Publisher ID for your solution? You can find it on your Marketplace offering, under the "Usage Information + Support" tab.
Ex. image

**Comment by aviau** [comment]
@elforb 

Here you go: `flaresystmesinc1617114736428`.

We tried updating the zip of our sumissions with the fixes that you have recommended but we got the following message:
- `You have an in-progress submission. You can't publish until the in-progress submission has been published.`

Not sure what to do here. Should this be `1.0.1`? Or can you just replace the content of whatever we uploaded on the store to the `1.0.0` that is now in this PR?

**Comment by elforb** [comment]
@aviau 

Regarding the issue with in-progress submission, did you happen to click go-live already? Either way you should be able to click "Cancel Publish" and the offer will shortly allow you to update as necessary and publish.

**Comment by aviau** [comment]
@elforb 

Ahhhh, got it! Thanks! I canceled the publish, edited the zip, and published again!

The package is back to the "Certification" step:
 
Screenshot from 2021-06-11 14-06-09

**Review by v-jayakal — APPROVED** [review]

**Pull request merged**
