### PR TITLE
adding initial package

### PR DESCRIPTION
**Pull request by daspiker**
Required items, please complete
   
   Change(s):
   - adding initial package for island solution

   Reason for Change(s):
   - initial package

   Version Updated:
   - NA

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-rbajaj** [comment]
Hi @daspiker, 
The maintemplate isn't getting deployed for this solution .
Also, data file (`Solutions\Island\Data\`) isn't included in this package, can you please commit it in this PR?
image

**Comment by v-rbajaj** [comment]
Hi @daspiker, any update on this?

**Comment by daspiker** [comment]
hey @v-rbajaj the mainTemplate.json file was auto-generated by the "Sentinel Solution Packaging Tool" and passed the validation tests so I'm not sure how to correct and error for a file generate by this tool.  
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2

I can see the Microsoft.Resources/templateSpecs/versions section the error is referring to but the doc links are helping me figure out what the segment length error is referring to.  Any help you can provide fixing this error would be greatly appreciated.

Sample data files are at:
Sample Data/Custom/Island_Admin_CL.json
Sample Data/Custom/Island_User_CL.json

Is this the wrong place or are you talking about a different Data file?

**Comment by v-rbajaj** [comment]
> hey @v-rbajaj the mainTemplate.json file was auto-generated by the "Sentinel Solution Packaging Tool" and passed the validation tests so I'm not sure how to correct and error for a file generate by this tool. https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2
> 
> I can see the Microsoft.Resources/templateSpecs/versions section the error is referring to but the doc links are helping me figure out what the segment length error is referring to. Any help you can provide fixing this error would be greatly appreciated.
> 
> Sample data files are at: Sample Data/Custom/Island_Admin_CL.json Sample Data/Custom/Island_User_CL.json
> 
> Is this the wrong place or are you talking about a different Data file?

Hi @daspiker, I can help you with the maintemplate deployment issue once you include the file present on this path `Solutions\Island\Data\`, it is a json file. I am assuming the name of the file would be `Solution_island.json`, please include that file in this PR. 

Also if you check the ARM ttk validation is failing which is related to API versions. I have fixed the validations by changing the API versions at line 84, 98, 408, 422, 732, 746, 817 and 831 to `2022-02-01` in the maintemplate.

**Comment by daspiker** [comment]
@v-rbajaj i'm seeing the below error in VSCode but when i load the example from the documentation i'm seeing the same error.  here is file i am referencing for that i see the same error on:
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/GitHub/Data%20Connectors/azuredeploy_GitHub_native_poller_connector.json

and seeing the same reference here:
https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_API_CCP_template.json

and here is how i see it for my file in vscode:
image

**Comment by v-rbajaj** [comment]
Hi @daspiker, Thanks for making the changes.  I was able to deploy maintemplate successfully. 
Only ARM TTK failure I can see is for API versions, please change API versions in the maintemplate to `2022-02-01` as mentioned earlier. This will pass ARM TTK validation. 

Regarding the VScode error, I pulled this PR on my local I didn't get that error.

**Comment by daspiker** [comment]
@v-rbajaj i updated the apiVersions that were failing arm-ttk per your request

**Review by v-rbajaj — APPROVED** [review]
Looks good!

**Pull request merged**
