### PR TITLE
Commvault Integration with Microsoft Azure Sentinel - V.1.0 (minor changes)

### PR DESCRIPTION
**Pull request by Cv-securityIQ**
Change(s):

Made formatting changes like modified "azure sentinel" to "Microsoft sentinel" and formatted the descriptions.

Reason for Change(s):
Changes required to complete the publishing of the solution from the partner center.

Initial integration PR.
Version Updated:

Yes
Initial pull request.
Testing Completed:

Yes
Checked that the validations are passing and have addressed any issues that are present:

Yes

### CODE REVIEW

**Review by v-atulyadav — APPROVED** [review]

**Comment by v-atulyadav** [comment]
Hi @Cv-securityIQ, 
As per certification the solutionid should be `commvault.cvsecurityiq`, can you please confirm with this. In your maintemplate, we can see the following solutionid.
image
Also there is `Azure Sentinel` text in playbook's prerequisites and maintemplate.json
image
Thanks

**Comment by Cv-securityIQ** [comment]
> Hi @Cv-securityIQ, As per certification the solutionid should be `commvault.cvsecurityiq`, can you please confirm with this. In your maintemplate, we can see the following solutionid. image Also there is `Azure Sentinel` text in playbook's prerequisites and maintemplate.json image Thanks

Hi, should I make the changes to the maintemplate.json manually or repackage the solution after changing the text in the playbook pre-requisites?

By the solution id as per certification you mean the offer name that gets mentioned in the Partner Center, right? Also, should the solution id be formed as "publisherId.offerId" that will be used in the partner center?

**Comment by v-atulyadav** [comment]
> > Hi @Cv-securityIQ, As per certification the solutionid should be `commvault.cvsecurityiq`, can you please confirm with this. In your maintemplate, we can see the following solutionid. image Also there is `Azure Sentinel` text in playbook's prerequisites and maintemplate.json image Thanks
> 
> Hi, should I make the changes to the maintemplate.json manually or repackage the solution after changing the text in the playbook pre-requisites?
> 
> By the solution id as per certification you mean the offer name that gets mentioned in the Partner Center, right? Also, should the solution id be formed as "publisherId.offerId" that will be used in the partner center?

Hi @Cv-securityIQ, 
1. Make these changes manually, but make sure you keep the same maintemplate in the zip file.
2. The offer is mentioned in the partner center and the solution ID is formed as `publisherId.offerId`

**Comment by Cv-securityIQ** [comment]
> commvault

I've made the required changes, the publisher id and offer id have been modified. Since the official documentation says "Ensure that the OfferID contains the keyword "sentinel". Consider using the format: microsoft-sentinel-solution-<productname>", we are following this naming convention and we'll create a new publish request with the same as we cannot modify the offer id of the existing publish request.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
