### PR TITLE
Added workbook for AI Vectra Stream solution

### PR DESCRIPTION
**Pull request by jayeshprajapaticrest**
Required items, please complete
   
   Change(s):
   - Added workbook for AIVectraStream

   Reason for Change(s):
   - New implementation

   Version Updated:
   - Initial Version

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : Please fix the below validation errors
In Connection section we are getting below error please see the below screenshot
image
image
In DNS section we are getting below error please see the below screenshot
image
In Host section we are getting below error please see the below screenshot
image

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest : Please fix the below validation errors In Connection section we are getting below error please see the below screenshot image image In DNS section we are getting below error please see the below screenshot image 
@v-spadarthi 
This issue is because of no data available in dropdown filter within selected time range.
**Details :** If there is no data available in "Service" and "Query Type" dropdown filter within selected time range then by default "All" will be selected in UI and as there is no data available it will display that we must need to set the filter value which will be used in all the implemented queries. We are unable to handle this as no data available in the selected time range.

But if you select time range to more than 3 days then the data is available above filter and also in panels. 

In Host section we are getting below error please see the below screenshot image
@v-spadarthi 
This issue is because of "Date" is not available in the current version of parser.
The PR has been raised with the latest updated parser with the "Date" implementation, so once this is merged the above error might gets resolved automatically.
Latest parser PR link : https://github.com/Azure/Azure-Sentinel/pull/5825

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest : Please fix the below validation errors In Connection section we are getting below error please see the below screenshot image image In DNS section we are getting below error please see the below screenshot image 
@v-spadarthi 
I have fixed the above validation errors could you please confirm it and let us know if it works or not?

**Comment by jayeshprajapaticrest** [comment]
@v-spadarthi 
Is there any updates on above PR merging request as we have fixed the required information suggested by you?

**Comment by jayeshprajapaticrest** [comment]
@v-spadarthi 
Is there any updates on above PR merging request?

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : As this PR having dependency on #5825, Please fix the issues in the PR .

**Comment by v-laanjana** [comment]
image


Hello,  

 please fix the issue .

**Comment by jayeshprajapaticrest** [comment]
> image
> 
> Hello,
> 
> please fix the issue .

@v-laanjana 
Sorry, But is it fine it remains as it is as this is the part of requirements?

To view the data of Host, user must need to provide host name.
If user provide * as input in it will display all host name data.

**Comment by NikTripathi** [comment]
@v-laanjana Please look into this.

**Comment by v-laanjana** [comment]
@NikTripathi we are checking .

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : As this PR having dependency on https://github.com/Azure/Azure-Sentinel/pull/5825, Please fix the issues in the PR .

**Comment by v-laanjana** [comment]
@jayeshprajapaticrest : As this PR having dependency on https://github.com/Azure/Azure-Sentinel/pull/5825, Please fix the issues in the PR .

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest : As this PR having dependency on #5825, Please fix the issues in the PR .

OK Will ask PR raised person to fix it as early as possible so we can proceed with this.

**Comment by v-mchatla** [comment]
> OK Will ask PR raised person to fix it as early as possible so we can proceed with this.

Thanks for the update. Please keep us posted on the same.

**Comment by NikTripathi** [comment]
@jayeshprajapaticrest Do we have any update on this sir?
Thanks.

**Comment by v-laanjana** [comment]
@jayeshprajapaticrest Do we have any update on this?

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest Do we have any update on this sir? Thanks.

They already have updated on the dependent [PR(#5825)](https://github.com/Azure/Azure-Sentinel/pull/5825) and waiting for the response from reviewer.
image

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : Still we are getting the error and requested the updated sample data to test the Parser.

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : We requested the updated sample data.

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest : We requested the updated sample data.

@v-spadarthi OK Thanks for the update. We need to wait till they provide data and merge that [PR(#5825)](https://github.com/Azure/Azure-Sentinel/pull/5825)

**Comment by v-spadarthi** [comment]
image
image
image
image
Above all are fine
@Jayeshprajapaticrest: Still, we are getting below error after #5825 sample data provided and ingested also, please check and fix it.
In Host section we are getting below please fix it
image
image

**Comment by jayeshprajapaticrest** [comment]
> Above all are fine @jayeshprajapaticrest: Still, we are getting below error after #5825 sample data provided and ingested also, please check and fix it. In Host section we are getting below please fix it
> image
> 
> image
As I checked on the parser they are going to commit in the [PR(5825)](https://github.com/Azure/Azure-Sentinel/pull/5825), there is a column with the name **"date"** is available. I don't know why it would not be available in the provided sample data.

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest :  Thanks for sharing the updated sample data we ingested and tested working fine.
image
Anyway we need to re-package this once #5825 validation error fixes we can good to merge. Thanks!

**Comment by jayeshprajapaticrest** [comment]
> @jayeshprajapaticrest : Thanks for sharing the updated sample data we ingested and tested working fine. image Anyway we need to re-package this once #5825 validation error fixes we can good to merge. Thanks!

@v-spadarthi Thanks for the Update.

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : The https://github.com/Azure/Azure-Sentinel/pull/5825 validation error fixed now all looks good

**Review by v-spadarthi — APPROVED** [review]

**Comment by v-spadarthi** [comment]
By mistakenly closed  sorry for that we are good to merge

**Comment by jayeshprajapaticrest** [comment]
@v-spadarthi Thanks for the support.
Can you please let me know approx how much time it would take to publicly available of this workbook in Azure portal?

**Pull request merged**
