### PR TITLE
adding playbook - incident status sync to wdatp

### PR DESCRIPTION
**Pull request by mahelsay**
Fixes #

## Proposed Changes
I added a playbook to sync incident status from azure sentinel to wdatp. tested successfully and ready for going public.
details are originally in my LinkedIn post: 
https://www.linkedin.com/pulse/azure-sentinel-incident-status-sync-mdatp-mahmoud-elsayed/?trackingId=gbV1tHCrV8q3%2BFZdkedZtg%3D%3D

  -
  -
  -

### CODE REVIEW

**Review by mahelsay — COMMENTED** [review]
done!

**Review by sarah-yo — CHANGES_REQUESTED** [review]
Hello, please can you tidy up the formatting of your readme and add both a "deploy to azure" and "deploy to azure gov" template as per the other playbooks in our repo. Thanks!

**Comment by mahelsay** [comment]
added both a "deploy to azure" and "deploy to azure gov" template and re-edited readme file

**Comment by mahelsay** [comment]
read me file is ready. could you check please @sarah-yo  ? or @sreedharande ? many thanks

**Comment by mahelsay** [comment]
> Hello, please can you tidy up the formatting of your readme and add both a "deploy to azure" and "deploy to azure gov" template as per the other playbooks in our repo. Thanks!

It's all done and looks good now, added also some images for better explanation. could you approve ? Thanks

**Review by mahelsay — COMMENTED** [review]
done and waiting for final review

**Comment by mahelsay** [comment]
Hi @sarah-yo @sreedharande , just a reminder to possibly review this playbook and approve if no further changes are required please? Thanks

**Comment by sarah-yo** [comment]
@mahelsay could you please change some of the wording in your readme to align more closely with other readmes in the repo and be less casual in it's conversational tone? For example, whilst we do release new features all the time it's not necessary to include this statement in the readme. Also please could you review your spelling, punctuation and capitalization in the readme. Thank you!

**Comment by mahelsay** [comment]
@sarah-yo now readme looks more aligned and similar to other readme files under master branch. could you have a look? appreciated.

**Comment by sarah-yo** [comment]
@mahelsay looks good :)

**Comment by mahelsay** [comment]
Thanks @sarah-yo i just created a new pull request updating Author name in the readme file. Thanks

**Pull request merged**
