### PR TITLE
Updated GCP IAM code to handle projects in batch processing

### PR DESCRIPTION
**Pull request by mkchiliveri**
Required items, please complete
   
   Change(s):
   - Updated GCP IAM code to handle projects in batch processing

   Reason for Change(s):
   - Bug Fix

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @devikamehra, @rushriva,
Can you please review and share your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @Devika, @rushriva,
Can you please review the changes and share your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @devika, @rushriva,
Can you please review the changes and share your feedback.
Thanks

**Review by anki-narravula — COMMENTED** [review]
Your changes looks good. But there is a bug in the old code where we might lose data. Need to correct that. 

if diff_seconds > MAX_PERIOD_MINUTES * 60:
        old_last_ts = last_ts
        last_ts = now - datetime.timedelta(minutes=MAX_PERIOD_MINUTES)

we should not modify the last_ts (last processed time), rather we should restrict the time by introducing endTime. So that we can restrict the time window (data that need to process) to certain minutes/hours

**Comment by v-mchatla** [comment]
Hi @anki-narravula - Thanks for reviewing the changes and feedback.
@mkchiliveri - Can you please accommodate the requested changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @VenkataPrathibha,
If you are done with all the changes please request for review.
Thanks

**Comment by v-mchatla** [comment]
Hi @mkchiliveri,
Can you please confirm and request for review once you are done with the requested change
Thanks

**Comment by v-mchatla** [comment]
Hi @mkchiliveri,
Can you please provide an update on this.
Thanks

**Comment by v-atulyadav** [comment]
Hi @mkchiliveri,
Please provide an update on this.
Thanks

**Comment by v-mchatla** [comment]
Hi @mkchiliveri,
It would be great if you could provide an update on the progress.
Thanks

**Comment by v-mchatla** [comment]
Hi @mkchiliveri,
It would be great if you could provide an update on the progress.
Thanks

**Review by anki-narravula — DISMISSED** [review]

**Review by anki-narravula — APPROVED** [review]

**Pull request merged**
