### PR TITLE
Adding M365D to NwS and converting to new format

### PR DESCRIPTION
**Pull request by YaronFruchtmann**
Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by oshezaf** [comment]
Naming changes:

- NwS -> NetworkSession
- vimNwSPaloAlto -> vimNwSPaloAltoPanOS -> vimNetworkSessionPaloAltoPanOS 
- vimNwSWireData -> vimNwSMicrosoftWireData -> vimNetworkSessionMicrosoftWireData 
- vimNwSzScalera -> vimNwSzScalerZIA -> vimNetworkSessionzScalerZIA 
- Schema: NetworkSessions -> NetworkSession (singular)
- Network Sessions schema -> Network Session schema

yaml2json template issue: You currently build sentences with the "product" field from the Yaml which is incosistent and creates strange readmes. The readme sentence:

**This template deploys the ASIM {{Schema}} schema parser for {{Product}}.**

Should end with {{Vendor}} {{Product}} which should be added to the YAML. We also need to be consistent about it with the naming above.

Also, make sense to build the function alias and display name automatically based on Schema/Vendor/Product rather than put it in the YAML.

**Comment by oshezaf** [comment]
@YaronFruchtmann : 
- Your readme template has a typo, so you need to correct it and rerun generataion (missing "l" at the end in "This template deploys the ASIM NetworkSession schema parser for Multiple. The parser is a part of the Azure Sentinel Information Mode.")
- NetworkSessioneGenericYaml product should be "multiple products" to fit the Readme generation.
- No template and readme for vimNetworkSessionEmpty.

**Comment by YaronFruchtmann** [comment]
Thanks for finding the typo. I fixed the template that generated those.
As for this: Since we already have the physical table – do we need the empty vim?

**Comment by YaronFruchtmann** [comment]
Thanks for finding the typo. Also fixed the generating template. 
As for empty vim: since we already have the physical table for network - I am not sure we need that.

**Review by oshezaf — APPROVED** [review]

**Pull request merged**
