### PR TITLE
fix typo and remove URL mapping

### PR DESCRIPTION
**Pull request by fgu-vectra**
Required items, please complete
   
   Change(s):
   - fix a typo which generate an error while creating the rule

   Reason for Change(s):
   - Wrong mapping with URL

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Need Help

### CODE REVIEW

**Comment by fgu-vectra** [comment]
@microsoft-github-policy-service agree

**Comment by fgu-vectra** [comment]
@microsoft-github-policy-service agree [company="Vectra"]

**Comment by fgu-vectra** [comment]
@microsoft-github-policy-service agree company="Vectra"

**Comment by v-prasadboke** [comment]
Hello @fgu-vectra have you repackaged the solution after making the changes in the analytic rules

**Comment by v-prasadboke** [comment]
Hello @fgu-vectra I repackaged the solution with latest analytic rule in my own branch but arm ttk is failing for the main template due to analytic rule "VectraDetect-Account-by-Severity" &" VectraDetect-Host-by-Severity " because the ( alertTacticsColumnName: ) parameter has been set as null 
should i set that ( alertTacticsColumnName: null ) to ( alertTacticsColumnName: tactics )

Thank you

**Comment by fgu-vectra** [comment]
> Hello @fgu-vectra I repackaged the solution with latest analytic rule in my own branch but arm ttk is failing for the main template due to analytic rule "VectraDetect-Account-by-Severity" &" VectraDetect-Host-by-Severity " because the ( alertTacticsColumnName: ) parameter has been set as null should i set that ( alertTacticsColumnName: null ) to ( alertTacticsColumnName: tactics )
> 
> Thank you

Hi @v-prasadboke, you can set it to null as those alerts are not related to a specific tactic.

**Comment by v-prasadboke** [comment]
Hello @fgu-vectra they are already set to null 
Is there any other way we can work on

**Comment by fgu-vectra** [comment]
> Hello @fgu-vectra they are already set to null Is there any other way we can work on

what are the options here? I could not find the documentation for this attribute

**Review by v-prasadboke — APPROVED** [review]

**Comment by v-prasadboke** [comment]
Arm ttk was successfully intiated on the main template and all looks good here @fgu-vectra

**Pull request merged**
