### PR TITLE
Create AzureInformationProtection_Advanced.json

### PR DESCRIPTION
**Pull request by peterabele**
Required items, please complete
   
   Change(s):
   - Added advanced Workbook for Azure Information Protection

   Reason for Change(s):
   - The original workbook provides very limited information

   Version Updated:
   - No

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@peterabele  Please add preview images for workbooks, you can refer sample images from this [folder](https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks/Images/Preview), thanks.

**Comment by v-sabiraj** [comment]
@peterabele, please check and resolve the comments, thanks.

**Comment by vmanojreddy** [comment]
@peterabele, please check and resolve the comments, thanks.

**Comment by v-sabiraj** [comment]
@peterabele, please add InformationProtectionLogs_CL sample data, thanks.

**Comment by v-sabiraj** [comment]
@peterabele, resolve the requested changes, thanks.

**Comment by v-spadarthi** [comment]
@peterabele:  Please resolve the requested changes, thanks.

**Comment by v-mchatla** [comment]
Hi @peterabele,
We wanted to check on the status of PR #5169. PR is pending from more than 90days. Let us know if any assistance is required for this PR. As per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

**Comment by NikTripathi** [comment]
@v-mchatla Please do the needful.

**Comment by v-marimanda** [comment]
HI @peterabele  
Since we have not received response from last 7 days, we are closing your PR #5169  per our standard operating procedures. If you still need support for this issue you can re-open the PR at any time.

If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

**Pull request closed without merging**
