### PR TITLE
OneLogin: first_commit_27.06.2022

### PR DESCRIPTION
**Pull request by averbn**

### CODE REVIEW

**Comment by v-spadarthi** [comment]
@averbn : Please resolve the below comments for Parser and Validation errors
Sample data ingestion done and working fine 
image
After deploying Parser i'm getting below errors Not able to see below columns in that table please fix and provide the correct sample data
image
While deploying Dataconnector after that if you click on Azure to Deploy button it is working is fine
image
While testing funtion app also working fine
image

Please fix the Validation errors as well.

**Comment by averbn** [comment]
> 

Added full sample, pls check

**Comment by v-spadarthi** [comment]
@averbn :Please fix the below error in Dataconnector samplequery change OneLogin to OneLogin_CL
image

**Comment by v-spadarthi** [comment]
@averbn : Thanks for the providing full sample data we have ingested and tested the parser working fine.
image

**Review by v-spadarthi — APPROVED** [review]

**Review by v-rucdu — APPROVED** [review]

**Pull request merged**
