### PR TITLE
Adding PS function New-AzureSentinelAlertRuleDeployment 

### PR DESCRIPTION
**Pull request by pkhabazi**
Required items, please complete
   
Change(s):
- Added New-AzureSentinelAlertRuleDeployment.ps1

Reason for Change(s):
- Deploying JSON Detection rules to Azure by looping is time consuming

Testing Completed:
- yes

Checked that the validations are passing and have addressed any issues that are present:
- yes

References:

### CODE REVIEW

**Comment by vmanojreddy** [comment]
@aprakash13  Please review and provide your feedback. thanks!!!

**Comment by aprakash13** [comment]
@sreedharande Is this something that you can help review. Thanks.

**Comment by pkhabazi** [comment]
Do you need more support with merging this PR?

> @sreedharande Is this something that you can help review. Thanks.

Do you need more support with merging this PR?

**Comment by v-sabiraj** [comment]
Hey @sreedharande,can you please check and approve , thanks.

**Comment by vmanojreddy** [comment]
Hey @sreedharande,can you please check and approve , thanks.

**Comment by v-spadarthi** [comment]
@sreedharande : can you please check and approve , thanks.

**Comment by v-spadarthi** [comment]
@sreedharande : can you please check and approve , thanks.

**Comment by v-marimanda** [comment]
@sreedharande : can you please check and approve , thanks.

**Comment by v-mchatla** [comment]
Hi @sreedharande 
Can you please review the PR or assign it to the right person who can review it.
Thanks

**Comment by NikTripathi** [comment]
@sreedharande Please look into this.

**Comment by v-spadarthi** [comment]
Hi @sreedharande
Can you please review the PR or assign it to the right person who can review it.
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande 
It would be great if you could review the PR and provide your feedback
Thanks

**Comment by v-mchatla** [comment]
Hi @sreedharande 
Can you please review or assign it to someone who can work on this.
Thanks

**Review by sreedharande — APPROVED** [review]

**Pull request merged**
