### PR TITLE
Fix empty array issue and json valid or not after package

### PR DESCRIPTION
**Pull request by v-amolpatil**
Required items, please complete
   
   Change(s):
   - Fix empty error issue on playbook
   - added json valid or not check in tool
   - minor change incorporated for Rahul in V3 tool line 70

   Reason for Change(s):
   - Fix empty error issue on playbook

   Version Updated:
   - NA

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

**Testing results:**
**1.Source playbook file having null value:**
image

**After generating maintemplate:**
image

**After deployment of playbook to Azure Portal:**
image

**Check the code for actual replaced value:**
image

**2.When playbook file has empty object as value. After deployment we see below: **
image

**Check the code for actual replaced value:**
image

### CODE REVIEW

**Comment by manishkumar1991** [comment]
Reviewing

**Comment by manishkumar1991** [comment]
Observation 

Playbook before template packaging 
image

Playbook deployed through template spec post packaging :
image

Both the screenshots are matching hence script has generated the desired and expected output.

@rahul0216  : Do you think of any other use case of null value or empty assignment of variable, which we need to test

**Comment by rahul0216** [comment]
@manishkumar1991 Looks good to me. Both Empty and null assignment test cases look good.

**Review by manishkumar1991 — APPROVED** [review]
approved

**Review by rahul0216 — APPROVED** [review]
Changes look good.

**Review by v-atulyadav — APPROVED** [review]

**Pull request merged**
