### PR TITLE
Add UI kickstart scripts

### PR DESCRIPTION
**Pull request by dvir-ms**
I've added a few scripts for the UI flow.
The auto-update is still not used.

### CODE REVIEW

**Comment by v-mchatla** [comment]
Hi @v-spadarthi, 
Can you please route it to someone who can review it.
Thanks

**Comment by v-mchatla** [comment]
Hi @tamirkopitz -
Can you please review this PR and share your feedback.
Thanks

**Comment by v-spadarthi** [comment]
Hi @tamirkopitz -
Can you please review this PR and share your feedback.
Thanks

**Comment by dvir-ms** [comment]
> Hi @tamirkopitz - Can you please review this PR and share your feedback. Thanks

hi 
he is on maternity leave 
the one that should review and approve is @udidekel

**Comment by v-mchatla** [comment]
Hi @dvir-ms,
Thanks for the details. 
Hi @udidekel - Can you please review and share your feedback.
Thanks

**Comment by v-mchatla** [comment]
Hi @udidekel - Can you please review and share your feedback or route it to someone who can help us with the review.
Thanks

**Comment by v-mchatla** [comment]
Hi @udidekel - 
It would be great if you can spare some time to review and share your feedback or route it to someone who can help us with the review.
Thanks

**Comment by v-atulyadav** [comment]
Hi @udidekel -
Can you please review and share your feedback or route it to someone who can help us with the review.
Thanks

**Comment by v-mchatla** [comment]
Hi @rushriva,
Can you please route this to someone who can help in reviewing the content.
Thanks

**Review by udidekel — APPROVED** [review]

**Pull request merged**
